### ISSUE TITLE
Users should be able to CRUD databases and retention policies when using an Influx Enterprise source

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1005]
Users should be able to get and set:
• Databases
• Retention policies 

Not in scope:
• Shards
• Meta info on shards

**Comment by goller** [comment]
https://docs.influxdata.com/influxdb/v1.2/query_language/database_management/

## RP

### Variables:
    1. name
    2. database
    3. duration
    4. replication
    5. shard duration
    6. is default retention policy

### CRUD InfluxQL
#### Create
```sql
CREATE RETENTION POLICY <retention_policy_name> ON <database_name> DURATION <duration> REPLICATION <n> [SHARD DURATION <duration>] [DEFAULT]
```
Note:
> A successful CREATE RETENTION POLICY query returns an empty response. If you attempt to create a retention policy identical to one that already exists, InfluxDB does not return an error. If you attempt to create a retention policy with the same name as an existing retention policy but with differing attributes, InfluxDB returns an error.


#### Read
```sql
SHOW RETENTION POLICIES [ON <database_name>]
```

#### Update
```sql
ALTER RETENTION POLICY <retention_policy_name> ON <database_name> DURATION <duration> REPLICATION <n> SHARD DURATION <duration> DEFAULT
```

#### Delete 
```sql
DROP RETENTION POLICY <retention_policy_name> ON <database_name>
```

Note:
> A successful DROP RETENTION POLICY query returns an empty result. If you attempt to drop a retention policy that does not exist, InfluxDB does not return an error.

## Databases
### Variables
### CRUD InfluxQL
#### Create
```sql
CREATE DATABASE <database_name> [WITH [DURATION <duration>] [REPLICATION <n>] [SHARD DURATION <duration>] [NAME <retention-policy-name>]]
```
Note: 

> A successful CREATE DATABASE query returns an empty result. If you attempt to create a database that already exists, InfluxDB does nothing and does not return an error.

#### Read
```sql
SHOW DATABASES
```

#### Update
**N/A**

#### Delete 
```sql
DROP DATABASE <database_name>
```
Note:

> A successful DROP DATABASE query returns an empty result. If you attempt to drop a database that does not exist, InfluxDB does not return an error.

**Comment by jademcgough** [comment]
per @nhaugo this should be accessible for both enterprise and OSS sources
