### ISSUE TITLE
Support Uptime Percentage in Hosts List

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#1025]
A user wrote in here: https://community.influxdata.com/t/server-availability-percentage-value/243 asking how to construct a query for computing server uptime percentage.

I believe that this would be a useful enhancement to the existing status lights, since it would allow sorting by more / less stable hosts. This can be accomplished using subqueries like:

```
select sum("isUp") / count("isUp") from (select non_negative_derivative(mean("uptime")) / non_negative_derivative(mean("uptime")) as isUp from system where time > now() - 10m group by time(1m) fill(0));
```

Since this query relies on subqueries (introduced in v1.2.0), we would need to detect that the source supports this, and have a graceful fallback to the existing behavior.

EDIT: add info about v1.2.0

**Comment by russorat** [comment]
i am closing this in favor of making the query user customizable in #682
