### ISSUE TITLE
[Feature Request] Add time range selector to the Alert History page

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1030]
Currently, it's not possible to filter alerts on the time column on the ALERT HISTORY page. It would be cool/useful to have a time range selector (like the one for dashboards and the explorer) in the top bar.

**Comment by nhaugo** [comment]
@alexpaxton can we get a design for this

**Comment by alexpaxton** [comment]
Can we find date picker for react then custom style it?

This one looks okay: https://hacker0x01.github.io/react-datepicker/#example-13
Wish it was possible to display the start/end times simultaneously though

This one looks awesome, made by Airbnb so likely solid:
http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by nhaugo** [comment]
Looks good, but needs to be a date time selector.

**Comment by nhaugo** [comment]
Default selected time should be the past 24 hours

**Comment by 121watts** [comment]
@nhaugo do we need to remember the users selection for time range?

**Comment by nhaugo** [comment]
no the default should always be current time and current time - 24 hours

**Comment by nhaugo** [comment]
@121watts clicking on the time selector produces the correct query, but clears the alert list
