### ISSUE TITLE
As a user I can edit a graph to display as a table

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1031]
Instead of toggling back and forth in the Data Explorer Visualization, we would move the Table option to be one of the Visualization Types, i.e.: `Line, Step-Plot, Stacked, SingleStat, Table`.

@nhaugo @alexpaxton Thoughts on this idea?

**Comment by alexpaxton** [comment]
I am a huge fan, I think that will simplify the UI a bit.

**Comment by alexpaxton** [comment]
This gave me an idea that would affect dash editing and to some extent the data explorer

![screen shot 2017-03-16 at 11 03 22 pm](https://cloud.githubusercontent.com/assets/2433762/24060725/bccfa528-0b11-11e7-813c-08acd656d304.png)

**Comment by jaredscheib** [comment]
@121watts why close this?
