### ISSUE TITLE
putDashboard action is created on dashboard load

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1032]
Not clear why this is happening, and if it's happening for multiple cells.

**Comment by nhaugo** [comment]
@jaredscheib are there negative side effects of this, or is it just a bit sloppy?

**Comment by jaredscheib** [comment]
@nhaugo It has a negative side effect in a hypothetical future where we want to more nicely handle concurrency of updating the time_modified by overwriting the current entire dashboard any time any user loads a dashboard. For the upcoming Viewer, this will actually not even work, so it will have to be redone for that role type.

@121watts Why was this closed?

**Comment by nhaugo** [comment]
Doesn't this get fixed with multitenancy

**Comment by jaredscheib** [comment]
Not sure I understand what you mean 😕 

My current hypothesis of what will happen in the multitenancy world, if this is left as-is, is above. Though, if by "fixed with multitenancy" what you mean is, "will this work become necessary once we implement the current vision for multitenancy?", then I believe the answer is yes. We will need to do this work to 1) avoid the above error cases, and 2) prevent race conditions and possible overwrites during concurrency situations between one user who is concurrently loading a dashboard while another user saves a part of that dashboard, specifically due to the current behavior of "re-save on dashboard load".

**Comment by 121watts** [comment]
@jaredscheib this was closed because 

1) There was no response from a question asked 5 months ago
2) This hasn't caused any problems and isn't an issue
