### ISSUE TITLE
[beta5] Blue sidebar marker isn't consistent

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1040]
(disclaimer: super nit!)

The sidebar's blue marker that shows which tab I'm in only shows up for the `ALERTING` and `CONFIGURATION` pages:

![blue-highlight](https://cloud.githubusercontent.com/assets/8750814/24169511/1bb8b102-0e3b-11e7-8785-ad937f63adc3.gif)

**Comment by alexpaxton** [comment]
@121watts want to tackle when you have a free 30?
