### ISSUE TITLE
Disable Dashboard editing abilities when in Presentation Mode

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1050]
From a UX perspective I believe it makes sense to not mix modes here. Following other apps that use a presentation mode, there is usually no more editing UI when presenting.

I have the context menu set to `display: none` when in presentation mode, but the user can still drag and rename cells. This feels like unexpected behavior

**Comment by nhaugo** [comment]
Disable only editing for now

**Comment by lukevmorris** [comment]
Solved by [959b387f6](https://github.com/influxdata/chronograf/commit/959b387f6155336b68f2559f4ebb7cd3ef44973e)
