### ISSUE TITLE
Add Page Spinner to alert history page

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1054]
Would be nice to have this consistent with the other parts of the app
![screen shot 2017-03-23 at 12 26 00 pm](https://cloud.githubusercontent.com/assets/2433762/24266415/ee72faf6-0fc3-11e7-8ad0-d9adabc2344a.png)

**Comment by nhaugo** [comment]
@alexpaxton says we have a full page spinner we can use for this
