### ISSUE TITLE
need real authentication for chronograf

### ISSUE THREAD

**Issue by peaksnail** [influxdata/chronograf#1073]
hi team,

For current version of chronograf, chronograf will reveal the details of influxdb like username and password.
  
Everyone can visit the configuration of influxdb in conf page even the chronograf is required login with third party account if he has the account with github,google or heroku. 
  
If there is some way can avoid this now?
thanks

**Comment by nhaugo** [comment]
@peaksnail Authorization is on the roadmap, but for the time being when a user has authenticated they have full permissions. I can't give you an exact time line around when we will start adding authorization, but we know it will be top of mind to many users once we have a base level of functionality.
