### ISSUE TITLE
Remove highlighting feature in DE

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1079]
• When the user is not clicked into the query builder all lines should have a uniform width and/or opacity
• Fix random lines getting focus on refresh
• @alexpaxton to look into using opacity to show focus instead of line width
• Do not show highlighting when there is only one query

**Comment by alexpaxton** [comment]
I believe there is some code in there for changing line widths between "active" and "inactive" graphs. Now that there is only 1 graph the "active" concept doesn't make sense anymore
