### ISSUE TITLE
As a user I should be able to leave the app to the source selection screen

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#108]
There should be a new option in the left hand nav that will show the list of sources available. When the user clicks on a source they should be directed to the same page they are on, but with the new source selected.

The selected source should be a query parameter source=<id>

**Comment by goller** [comment]
<img width="1141" alt="explorations" src="https://cloud.githubusercontent.com/assets/1922921/20539851/374482ac-b0bc-11e6-942b-b71cd4f1edca.png">

**Comment by nhaugo** [comment]
This has been addressed in a few ways, closing
