### ISSUE TITLE
As a user I can delete dashboard

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1080]
@alexpaxton to provide ui elements
Requires a confirm button

**Comment by alexpaxton** [comment]
<img width="705" alt="screen shot 2017-03-27 at 4 23 50 pm" src="https://cloud.githubusercontent.com/assets/2433762/24382246/d89c9f40-1309-11e7-8102-a12352c9a5c0.png">

Similar UI to Alert Rules page, delete on right column, always visible
