### ISSUE TITLE
Deleting databases using the green check, deletes without checking the string

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1086]
• Create database foobar
• When prompted type "asjflsj"
• Click green check
• Watch database be deleted

**Comment by jaredscheib** [comment]
Weird... I smoke-tested this when reviewing https://github.com/influxdata/chronograf/pull/1072 and did not have the same experience at all. And those commits are still part of the codebase. @121watts could probably solve this one the quickest.
