### ISSUE TITLE
Tie data source to queries

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1088]

**Comment by alexpaxton** [comment]
Might make sense to add more cases instead of just "No Results"

<img width="498" alt="screen shot 2017-03-27 at 4 41 19 pm" src="https://cloud.githubusercontent.com/assets/2433762/24382656/824a9a7c-130c-11e7-9af2-07a76253f1cd.png">

**Comment by nhaugo** [comment]
@alexpaxton can you provide some design ideas for later discussion.

**Comment by jackzampolin** [comment]
I would just like to jump in here and +1 this. I could really use this feature.

**Comment by nhaugo** [comment]
• Optional field on the cell object
• If not set, use the current connected source

**Comment by 121watts** [comment]
Optional field `source` will now be in the `queries: [query...]` (not to be confused with queryConfig) array of objects on the cell.  

For iteration 0 any change to a queries' source will affect all queries on that cell.

**Comment by nhaugo** [comment]
With no query, if i select a new source the source jumps back to the default
