### ISSUE TITLE
As a user I can see a tabular view of my configured kapacitor alert nodes

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1089]
• Show a list of all options
• When an option is selected show its config values
• When an option is properly set up show an indicator in the table view that the end point is good to go

@alexpaxton can you provide an initial design

**Comment by alexpaxton** [comment]
![screen shot 2017-04-04 at 3 17 10 pm](https://cloud.githubusercontent.com/assets/2433762/24878081/87aa5748-1de6-11e7-9283-fd1d530bffa0.png)

**Comment by alexpaxton** [comment]
Screenshot from #918 

![edit-create-kap-node](https://cloud.githubusercontent.com/assets/2433762/24881728/9f30f32e-1df3-11e7-8a02-e7029389e602.png)

**Comment by jademcgough** [comment]
closing this in favor of #918
