### ISSUE TITLE
Cells in the Kubernetes dashboard should not be editable

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1090]
Notice the cells have a dropdown caret in the top right

<img width="1626" alt="screen shot 2017-03-27 at 5 51 47 pm" src="https://cloud.githubusercontent.com/assets/1438089/24384087/218074dc-1316-11e7-8dcd-b9262caacec1.png">

**Comment by jaredscheib** [comment]
Believe this was solved by #1069.
