### ISSUE TITLE
If possible add uptime/status for windows hosts

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#1103]
The default telegraf windows configuration would need to be updated to add some other fields.

**Comment by brianbaker** [comment]
I have 1.2.0-beta9 installed but am still not seeing a Status indicator show up for windows hosts.  It appears the uptime query is pulling from `system` but when `[[inputs.system]]` is added to the `telegraf.conf` it will error with `ERROR in input [inputs.system]: not implemented yet`.  Is this functionality for windows hosts still a work in progress?
