### ISSUE TITLE
Cell tooltip should not appear below other cells in Dashboard (if at all)

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1106]
On mouse hover on a Cell in a Dashboard:
<img width="459" alt="screen shot 2017-03-28 at 2 46 30 pm" src="https://cloud.githubusercontent.com/assets/6403018/24429103/78f1eade-13c5-11e7-874e-c49796536abf.png">

Haven't noticed these appear before – are they supposed to at all?

**Comment by lukevmorris** [comment]
Maybe related to recent cell z-index changes?

**Comment by alexpaxton** [comment]
That is the Dygraphs legend. Used to have a fix for this, but had to undo it for some reason I don't remember. Shouldn't be too crazy to fix
