### ISSUE TITLE
Map default enter key...Add Source

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1110]
When configuring connections to InfluxDB (or Enterprise), the default enter key should be mapped to "Add Source" 

If a user hits enter after inputting data within any of the fields, an attempt to should be made to add the instance of InfluxDB (or Enterprise) described using the input data.

**Comment by cryptoquick** [comment]
I spoke with @timhallinflux and we determined there was no work to be done on this ticket. The interface behaves as expected. There are, however, validation issues that are interfering with UX on the Kapacitor page, as described in #1111 
Closing.
