### ISSUE TITLE
Map default enter key...Connect Kapacitor

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1111]
When configuring connections to Kapacitor, the default enter key should be mapped to "Connect Kapacitor"

If a user hits enter after inputting data within any of the fields, an attempt to should be made to use the information contained within the fields to connect to that instance of Kapacitor .

**Comment by jaredscheib** [comment]
Apparently, hitting Enter in any of the fields on a Kapacitor page will cause that field to return to its original value.
