### ISSUE TITLE
Specify the slack channel per rule

### ISSUE THREAD

**Issue by miry** [influxdata/chronograf#1113]
Currently we can setup the channel on Kapacitor setup page. It would great to have custom channel per rule.

**Comment by goller** [comment]
Hi @miry, thanks for writing in !  This should be really easy for us to add.  @cryptoquick created architecture for us to add custom fields to tick script alerts here: https://github.com/influxdata/chronograf/blob/master/ui/src/kapacitor/reducers/rules.js#L76

As an aside, we'll be revamping the kapacitor setup page.  We're hoping to simplify it a great deal and make it easier to configure alerts.

**Comment by goller** [comment]
Hey @miry my patch to allow slack channel overrides was just merged to master and should in our release of beta8 tomorrow!
