### ISSUE TITLE
Size the table columns to the data size in the data explorer

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1123]
When in table view columns do not adjust view for the size of the data. This is particularly bad when running commands such as `show series` where the data is usually long and there is only one column. The columns should attempt to fit data, or at a minimum if there is only one row returned the column should take the full width of the table

**Comment by jademcgough** [comment]
as an example of this, for replication:

![screen shot 2017-03-31 at 12 33 20 pm](https://cloud.githubusercontent.com/assets/1147449/24566404/389a9d78-160e-11e7-99ff-a198d000d832.png)
