### ISSUE TITLE
[beta 7] Blinking dashboards

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1128]
> This has been difficult to capture and it's not easily repro-ed.

Sometimes, when I switch to a different dashboard or click on a dashboard from the dashboard list, the cells on the dashboard blink a ton. This GIF is a bit long because I was just waiting for it to happen and the GIF doesn't capture the speed of the blinking.

In some cases, I've lost all my cells, but in this case, they remained on the dashboard.

![haunted](https://cloud.githubusercontent.com/assets/8750814/24482089/acd6595a-14a3-11e7-9662-7257f41a0ee9.gif)

**Comment by rkuchan** [comment]
@nhaugo: got it!

**Comment by jaredscheib** [comment]
@rkuchan Is this happening due to over-long tooltips possibly? @jackzampolin got flashing dashboards to occur when the tooltip contains way too many measurements, such that it would extend below the bottom of where the cells are

**Comment by jaredscheib** [comment]
I'd guess it's a React/Redux state + rendering issue, possibly related to the strange way we are setting Dashboard data.
