### ISSUE TITLE
Configure Endpoint for Kapacitor should conform to dropdown style in rest of app

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1139]
<img width="600" alt="screen shot 2017-03-30 at 4 09 18 pm" src="https://cloud.githubusercontent.com/assets/6403018/24529910/63a750a2-1563-11e7-9f5b-3dce6a2429bd.png">

**Comment by alexpaxton** [comment]
Ah this is going to go the way of the dinosaur, got a whole new config flow coming together

**Comment by nhaugo** [comment]
Fixed by redesign
