### ISSUE TITLE
When adding initial source prompt for enterprise credentials

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1145]

**Comment by jademcgough** [comment]
@nhaugo what needs to be added to the form for this?

**Comment by jademcgough** [comment]
context get:

![screen shot 2017-03-31 at 4 26 15 pm](https://cloud.githubusercontent.com/assets/1147449/24572607/d681aef8-162e-11e7-93f3-dad03b8890c7.png)

The "meta service connection url" field needs to appear when an enterprise connection string is entered.

**Comment by jademcgough** [comment]
also, probably need to add the unsafe SSL option as well
