### ISSUE TITLE
Cannot select text "Name this Graph"

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#1146]
When trying to rename a graph in a dashboard I attempted to select the text "Name this Graph" but instead all I could do is move the graph around.

![Example](https://cloud.githubusercontent.com/assets/3771906/24559794/e6d7194e-15f4-11e7-8aa4-3e48fcdf9e7c.gif)

**Comment by alexpaxton** [comment]
Should be fixed via #1124 

See this comment: https://github.com/influxdata/chronograf/pull/1124#issuecomment-290853709

**Comment by alexpaxton** [comment]
Looks like the click to toggle works in reverse (when it probably shouldn't)

**Comment by cryptoquick** [comment]
I'll take you up on that offer, @alexpaxton 
lmk when you're available

**Comment by avimar** [comment]
Chronograf Version: 1.3.8-2

How am I supposed to edit the name? single click, double click.. nothing. Thanks!

![ezgif com-crop](https://user-images.githubusercontent.com/314077/31326846-86fd12c8-acd3-11e7-81c4-2470efa8a043.gif)

**Comment by avimar** [comment]
Oh. Found  a "rename" in the dropdown...  it works.

**Comment by nhaugo** [comment]
For future reference in 1.3.9.0 and above the cell title edit has been moved into the cell overaly editor. 
![rename](https://user-images.githubusercontent.com/1003269/31347718-17034ff6-acd2-11e7-9dad-f8577a72a518.gif)
