### ISSUE TITLE
Cursor color changes are distracting and broken

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#1147]
OS LInux
Browser Chrome 56 (64-bit)

The cursor color changes give it weird backgrounds and is quite distracting.

![test](https://cloud.githubusercontent.com/assets/3771906/24559911/5ceb3d86-15f5-11e7-8a19-e8dd3ff7e608.gif)

**Comment by alexpaxton** [comment]
Ugh that looks nasty, looks like no support for alpha transparency

**Comment by zodman** [comment]
chrome problem!
