### ISSUE TITLE
Hosts > hostnames are on red [Solved]

### ISSUE THREAD

**Issue by zodman** [influxdata/chronograf#1148]
telegraf its running correct, sending data to influxdb
but the hostname are on red.

I had this issues its because the red status server the datetime are not on sync.

apt-get install ntp
service ntp stop
ntp ntp.ubuntu.com
service ntp start

now the telegraf are sending the same datetime of all servers.
I found how to resolved the issues reading 
https://github.com/influxdata/chronograf/blob/master/ui/src/hosts/apis/index.js#L8

and send direct queries to influxdb

    select mean("load1") from "system" where time > now() - 10m group by host; 

close the issue a put this comment if someone had the same problem.

**Comment by goller** [comment]
Ah that's excellent!  @rkuchan do you think this should be documented in our GETTING_STARTED?

**Comment by nhaugo** [comment]
Fixed in https://github.com/influxdata/docs.influxdata.com/pull/1106

**Comment by zodman** [comment]
it is a deb packages created ?

**Comment by zodman** [comment]
confirm fixed! 

thanks!
