### ISSUE TITLE
Add support for Okta as an OAuth Provider

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1153]
This might already be possible via the generic OAuth 2.0 provider support.  But, perhaps getting some help testing to confirm this works would be good.

http://developer.okta.com/docs/api/resources/oauth2.html

**Comment by russorat** [comment]
might be possible to do with generic Oauth #2677

**Comment by russorat** [comment]
Verified this working with generic OAuth. basic instructions are here: https://github.com/influxdata/chronograf/issues/2677#issuecomment-375823992
