### ISSUE TITLE
Chronograf not storing alert emails

### ISSUE THREAD

**Issue by kumudt** [influxdata/chronograf#1156]
I am using Chronograf 1.2.0-beta7.

I created a Kapacitor SMTP alert in chronograf and configured Kapacitor with a working SMTP endpoint. I am able to see the alert getting triggered in the alert history but unable to receive the email.

The issue I observed was email addresses given while creating the alert are not getting stored in the Chronograf database. After saving the alert, if I try to reload the page, I see empty email addresses field.

Is this a known issue or am I doing something wrong?

**Comment by goller** [comment]
Hi @kumudt, thanks for writing in.  This is a bug for sure. We see this in #1100 as well.  We are doing a bunch of bug fixes and polish this sprint, so, I'd expect this to be fixed very, very soon!

**Comment by kumudt** [comment]
Thanks @goller. I will be waiting for this update.

**Comment by nhaugo** [comment]
May be a dupe of #1100

**Comment by jaredscheib** [comment]
Yes, it's a dupe
