### ISSUE TITLE
Document restrictions around OSS permissions

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1163]
@goller wasn't there a reason we could not add readonly/write only to users in OSS, if so can you explain here so we can put it in the documentation.

**Comment by goller** [comment]
Yes, `GRANT` without a database must be `ALL`.  If the database is specified then `READ` and/or `WRITE` are possible.

Once the app has support for manipulating permissions on specific databases then `READ` and `WRITE` then we could use 'em.
