### ISSUE TITLE
Expired auth should navigate user to /login

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1165]
Expired auth is failing to forcibly navigate user to `/login`.

This seems due to the fact that a different router is currently returned depending on the `App` container's `this.state.loggedIn` bool. When that state changes, it's intended to navigate the user to `/login`, but instead fails with the error that we `cannot change <Router routes>`:
<img width="552" alt="screen shot 2017-04-03 at 5 29 38 pm" src="https://cloud.githubusercontent.com/assets/6403018/24637072/24fd431a-1893-11e7-9e37-1f7c5d4d4d19.png">

This is related to https://github.com/influxdata/chronograf/issues/1095.

**Comment by gunnaraasen** [comment]
We should also provide a notification to the user on the `/login` page that their auth has expired.

**Comment by goller** [comment]
@gunnaraasen,   @jaredscheib and I were talking about how to be more informative to the user when expiration occurs.  We were discussing if the server's router should redirect to `/login` or if the react router should.  

The current plan is that the react router will handle the redirect _because_ it gives the front-end opportunity to display good messaging as you ask for above.

**Comment by jaredscheib** [comment]
Agreed, @gunnaraasen and @goller!
