### ISSUE TITLE
Data explorer and dashboard edit does not work in Safari

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1167]
Hi!

I upgraded from beta 4 to beta 7 the other day, and noticed that it does not work well in Safari anymore. Affects at least the Data Explorer view and when trying to edit a cell in Dashboards.

In Safari the "edit" box is simply missing.

See difference below.

**Chrome:**
![chrome](https://cloud.githubusercontent.com/assets/16920380/24659643/9a1c00d6-194d-11e7-8274-162f7c75a9b1.png)

**Safari:**
![safari](https://cloud.githubusercontent.com/assets/16920380/24659652/9dea7238-194d-11e7-888a-dd83dda2355b.png)

**Comment by goller** [comment]
Hey @hasselrot , yup I've been able to reproduce this in safari as well.  We'll take a look!

**Comment by hasselrot** [comment]
Woho!

**Comment by lukevmorris** [comment]
Hiya @hasselrot -- I saw the issues you mentioned in both DataExplorer and CellEditorOverlay. These should be addressed in the PR above.
