### ISSUE TITLE
Unable to see databases

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#1170]
For some reason I'm not able to see databases in the admin page.  I checked the server and it is returning the correct respose.

<img width="1237" alt="image" src="https://cloud.githubusercontent.com/assets/1922921/24668460/95cbf692-192c-11e7-8570-e10c7e53249c.png">

**Comment by timraymond** [comment]
@goller Any Repro steps? Influx Enterprise or OSS w/ versions?

**Comment by 121watts** [comment]
@goller any console warnings / errors?

**Comment by goller** [comment]
@timraymond influx 1.2 and `master` branch

@121watts : 
<img width="471" alt="image" src="https://cloud.githubusercontent.com/assets/1922921/24669028/63e14702-192e-11e7-8097-895d5ae89cf4.png">

**Comment by lukevmorris** [comment]
@goller potentially relevant line:
https://github.com/influxdata/chronograf/blob/master/ui/src/admin/components/DatabaseTable.js#L44

Can you verify that one of your databases either:
1. is missing a `retentionPolicies` key
2. has a `retentionPolicies` key with a value of `null`

**Comment by lukevmorris** [comment]
Verified that if a database lacks a `retentionPolicy`, it will omit that key, and the JS will break. Removing `omitempty` for the `retentionPolicy` key should do the trick. After:
![screen shot 2017-04-04 at 1 53 35 pm](https://cloud.githubusercontent.com/assets/1438089/24678124/33522722-193e-11e7-820f-63194fb278ac.png)
