### ISSUE TITLE
Spike on #447

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1172]
Try to narrow down on scope and size of the feature and propose a solution.

**Comment by 121watts** [comment]
This requires two large redesigns:

1) The UX of applying functions to queries in the QueryBuilder
2)  A redesign of how we represent more complex functions in the QueryConfig

**Comment by nhaugo** [comment]
Lets time box this, @121watts what do you think is a decent amount of time to spend researching this before we circle back and make a final decision.

**Comment by 121watts** [comment]
@nhaugo it's going to be too big of a change to do this correctly and in time for GA.

**Comment by goller** [comment]
@nhaugo I agree with @121watts I think we could land it before GA.
