### ISSUE TITLE
Users should be able to logout

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1176]
There's currently no way to do this via the UI. Sessions time out only via auth expiration. Thoughts?

**Comment by nhaugo** [comment]
This used to be available, there was a user link in the bottom right.

**Comment by nhaugo** [comment]
https://github.com/influxdata/chronograf/issues/565

**Comment by goller** [comment]
The server needs the following:
1. a logout route `/oauth/logout`
2. The logout route needs to look at the JWT's issuer and redirect (302) the user to the appropriate provider logout endpoint.

**Comment by jaredscheib** [comment]
@nhaugo Turns out it's in there, but isn't showing because its display logic hinges upon unreliable/obsolete data (whether the response from `/me` returns a `email` property. Currently, I'm getting my email under `name`, and there is no `email` key.

@goller Just looked it up and found that route existent `server/mux.go`, and it issues a `307 (StatusTemporaryRedirect)`. That being said, I'm not sure I'm seeing a new cookie served anywhere in the chain, including within the `Logout` function called by that route (at `server/logout.go`). Is that right? Maybe we ought to include something for `/logout` (and possibly `/login`) in our session timeout work at https://github.com/influxdata/chronograf/pull/1119 pre-merge?

**Comment by jaredscheib** [comment]
Spoke with @goller and he showed me where the auth is able to handle this in middleware, so we fixed it and included it in https://github.com/influxdata/chronograf/pull/1119.
