### ISSUE TITLE
Host lists and autoscaling

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1177]
Hi!

Using autoscaling hosts, that come and go all day, creates a lot of clutter in the Host List.
A filter, or option to show "only active during the last 24 hours" or similar would be great!

![hostlist](https://cloud.githubusercontent.com/assets/16920380/24675011/e0adab0a-197d-11e7-9d76-5909295c80ff.png)

**Comment by nhaugo** [comment]
Dupe of #1241
