### ISSUE TITLE
Revert changes to a cell's name when a user presses escape

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1188]
Hitting `ESC` closes the cell rename but still updates with the new name. From initial foray it looks like there is no concept of "Old Name" / "New Name". The component uses the `onChange` event which fires at every key press, might suggest not using that event

**Ideally:**
`ESC` -> Update with old name
`Enter` -> Update with new name

**Comment by 121watts** [comment]
This works now :)
