### ISSUE TITLE
Users should not be able to name a cell with empty string

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1190]
If the user tries to submit a rename and has entered nothing, it should prevent the action from going through. Also should display some sort of error message "Cells require a name"

Trying to prevent this case:
<img width="523" alt="screen shot 2017-04-05 at 11 51 56 am" src="https://cloud.githubusercontent.com/assets/2433762/24721811/50d50720-19f6-11e7-9da5-51c702d8d2b0.png">

Becomes confusing where to click to rename at this point

**Comment by alexpaxton** [comment]
Alternatively, we could revert to the default cell name if the user enters an empty string

**Comment by rkuchan** [comment]
Closing for now.
