### ISSUE TITLE
MetaClient for Chronograf needs to use the CheckRedirect function

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1195]
If the meta node specified in the config's `Meta Service Connection URL` input isn't the leader, creating users, creating roles, assigning permissions, and assigning users to role returns:
```
Failed to [...]: EOF
```
https://golang.org/pkg/net/http/#Client

**Comment by rkuchan** [comment]
@goller

**Comment by goller** [comment]
@rkuchan I just merged a patch for this into master!
