### ISSUE TITLE
Redesign: Overlay Technology

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1200]
With the impending re-design of the Data Explorer, some concerns have arisen. Modifying the DE in isolation is tricky since Overlay Technology uses a handful of the DE's components. As each feature's use case becomes more focused, the need to share components lessens.

**Here is the purpose of Overlay Technology, as I understand it:**
- Provide users a way to create/edit cells within a dashboard
- Just enough power to add basic queries (does not include all functionality from the DE)
- Provide users a way to customize the appearance of a cell
  - Visualization type
  - Colors
  - Axis Labels
  - Custom Y Range

**UX Goals**
- User is aware of their limitations
  - User knows to use the DE when constructing an "advanced" query
  - User knows how to move a query from the DE into a dashboard cell
- Maintain context
  - User should be aware of which cell they are editing, and the dashboard they are in at all times
  - Do not obscure dashboard name
  - Avoid completely obscuring the edited cell's position beneath Overlay Technology
  - User should not feel like they are leaving the dashboard to make an edit
- Cell edits should feel like a "lightweight" action, to emphasize our UX goals of being the fastest tool (Time to Value)
  - The feeling of fast is more powerful than the task's actual duration
  - Hypothesis: the less we obscure dashboards with Overlay Technology, the more natural cell edits will feel

**UI Goals**
- Slick transition when Overlay Technology enters / exits (helps maintain context, better UX)
- Find a layout for Overlay Technology that satisfies above UX goals

### Rough Concept Mockup
![cell-editor-panel](https://cloud.githubusercontent.com/assets/2433762/24732452/e92a27e2-1a25-11e7-883c-28ebe94b779b.png)

### MVP
- No transition animation for Overlay Technology
- No custom axis labels
- No custom Y range
- No color palette selector

**Comment by lukevmorris** [comment]
Heya @alexpaxton -- this looks ok for MVP, but biggest concern is how this design scales out to supporting more and more options.
* How do we start to differentiate from each other different groups of options? (Tabs? Section Headers w/ Accordion?) Maybe we're ok with having a super tall div and just letting the user scroll?
* Do we still want to support multiple queries per cell?
  * How do we indicate a cell has multiple queries in the right rail?
  * How do we move between them?
* We'll definitely be adding more Viz Types. I think a second row of types would look pretty good, actually.

**Comment by jaredscheib** [comment]
Will give a more thoughtful review in the morning, but my main concern is this idea that Overlay Technology (Cell Editor) shouldn't allow for complex queries. Where did this arise? How would a user create a complex query in DE and then Edit that in a simpler Overlay Technology view?

**Comment by pauldix** [comment]
Is there a reason we need to have an overlay vs. just having the edit screen be the DE with a clear breadcrumb that the user arrived there from a specific Dashboard? I suspect users will be frustrated if they aren't able to fully edit their graphs on a dashboard and are instead forced to remove the graph and then start with a new DE and add it in.

In my mind the DE is just part of the CRUD process for specific graphs. Where it's the Create and Update screen. The difference is that Update is always within the context of a dashboard. It's a single page app so it seems it can be snappy and the right animation with a clear breadcrumb will still give them the context that they're editing for that specific dashboard.

**Comment by alexpaxton** [comment]
I think I might have planted a bad seed with the concept of basic/advanced queries. As far as I can tell users would not be using Meta Queries in a dashboard, and that's really the only "advanced" query. Even if both the DE and Cell Editing share a ton of features, the use cases are different. 

| Data Explorer            | Cell Editing       |
|:-------------------------|:-------------------|
| Ad-hoc                   | Visual controls    |
| Edit a single query      | Multiple queries   |
| Graph is de-emphasized   | Graph emphasized   |
| User does not save work  | User saves work    |

I'm predicting that as these features mature they will diverge more, and it will become increasingly hard to share components between them

**Comment by alexpaxton** [comment]
@lukevmorris good Qs, I'm imagining the right panel would be able to scroll and would have clearly labelled accordion sections. I'll mock that up next

@pauldix we used to have a more breadcumb oriented navigation pattern in old chronograf (it had back buttons in the UI) that emphasized where the user had just come from. Those patterns are more common in mobile apps than in web and the current UI has moved away from the pattern.

That being said, I imagine having a "Back to Dashboard X" button or "Save and Return to Dashboard" button would be effortless to add in the UI. My only concern there is that it's a new pattern and I would have to comb through the other parts of the UI and see if I can extend the pattern there as well (for consistency's sake).

**Comment by pauldix** [comment]
Ah yes, you wouldn't be doing meta queries from the dashboard edit. One thing I want to capture on the DE that might not be obvious from that list is that a user should be able to use the DE to drill down into something and then share that view with someone else via either a URL or an image. I know we can't do that now, but it's something to keep in mind.

It's a very common flow for someone to do some ad-hoc querying/digging in during problem investigation and then want to share that exact view with team members. Ideally, without having to create a dashboard to do it.

**Comment by alexpaxton** [comment]
@pauldix down with the poor man's dashboard! I think that once we have strong sharing features in the DE it can live on its own more effectively
