### ISSUE TITLE
Issues with TLS SNI InfluxDB upstream

### ISSUE THREAD

**Issue by johngilden** [influxdata/chronograf#1206]
Hey,

I have the following problem, haven't figured out why yet. My InfluxDB is behind an nginx with multiple vhosts (TLS). Hence it can only be accessed with the correct vhost (influxdb.domain.name). Chronograf seems to use the wrong vhost for some queries:

http://127.0.0.1:10000/api/v0/servers/2/version - works, uses correct towards the influxdb host
http://127.0.0.1:10000/api/v0/servers/2/query?q=SHOW%20DATABASES - does not work, vhost is 127.0.0.1

The latter request also logs as the user agent of the browser, so my guess would be that this is the issue, i.e. the request is passed through rather than done by Chronograf itself.

**Comment by goller** [comment]
Hi @johngilden, thanks for writing in! Could you be using chronograf version 1.0 (I'm guessing so because chronograf v1.0 used port 10000)? 

Is it possible for you to try out chronograf 1.2 from our downloads page https://www.influxdata.com/downloads/ and see if you still have the issue?

**Comment by johngilden** [comment]
Hey @goller,

thanks for the quick reply, yes, it looks like I was using an old version of Chronograf. After using 1.2 it works for InfluxDB, but now I'm having the same issue with my Kapacitor instance. I have Kapacitor on https://kapacitor.domain.com, also needs a vhost, also gets a request with vhost set to "127.0.0.1". This is run from localhost, not docker.

**Comment by goller** [comment]
@johngilden Interesting... so, basic questions first... 
1. What version of kapacitor are you running?
2. Is your influx using authentication?
3. Does your kapacitor configuration have the authentication to influx in its config file?
4. Any hints within the kapacitor logs?

**Comment by johngilden** [comment]
Sorry, should have started with that.

1. Chronograf 1.2.0~beta7 (git: 7ec0190063edd1ae37e14527f6e25e99fb01c11e)
2. InfluxDB and Kapacitor are both publicly reachable, both on their own vhost domains with TLS
3. Kapacitor can talk to InfluxDB
4. No, because the request does not reach Kapacitor

Again, the problem is that my Chronograf can not reach my Kapacitor instance since Kapacitor is behind an nginx with virtual hosts. When Chronograf tries to contact Kapacitor it will send vhost 127.0.0.1. This is the URL in question as I see it in my browser: `http://127.0.0.1:8888/chronograf/v1/sources/1/kapacitors/1/proxy?path=%2Fkapacitor%2Fv1%2Fconfig`
So the request does not even reach the Kapacitor instance since nginx does not know what to do with the request with an invalid vhost set.

**Comment by johngilden** [comment]
```
From 6bd12fbdc90bab3ad24929795fc3554ada57e086 Mon Sep 17 00:00:00 2001
From: John Gilden <john@gilden.com>
Date: Fri, 7 Apr 2017 10:02:19 +0200
Subject: [PATCH] Use the Host header from the original Kapacitor URL

---
 server/proxy.go | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/server/proxy.go b/server/proxy.go
index 5e1a0fa8..b00709e0 100644
--- a/server/proxy.go
+++ b/server/proxy.go
@@ -44,6 +44,9 @@ func (h *Service) KapacitorProxy(w http.ResponseWriter, r *http.Request) {
 	u.Path = path
 
 	director := func(req *http.Request) {
+		// Set the Host header of the original Kapacitor URL
+		req.Host = u.Host
+
 		req.URL = u
 		// Because we are acting as a proxy, kapacitor needs to have the basic auth information set as
 		// a header directly
-- 
2.12.1
```

**Comment by goller** [comment]
@johngilden Ah! That totally makes sense. Thank you for the patch!  I've created PR #1223 with it.

I've just been testing the patch and it is working great for me.  It will be in today's beta8 release.
