### ISSUE TITLE
URL to presentation mode

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1208]
It would be great to be able to link to a dashboard in presentation mode.

In my use case I put together a bunch of rotating dashboards in iframes, and it looks much better in presentation mode.

**Comment by cryptoquick** [comment]
Great idea! We'll see if we can get to it soon.

**Comment by XDGFX** [comment]
Could this be made so that any dashboards accessed through 'present=true' url are completely read only; i.e. people can't drag elements or resize them?

I want to put a dashboard in an iframe and allow other users access, but don't want them moving stuff around on the dashboard.
