### ISSUE TITLE
Cells should have an over-writable template time

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1213]
cc: @jackzampolin @goller 

I'm able to save 3 queries to a cell now:

`SELECT count FROM usage_computed.autogen.unique_clusters_by_day WHERE time > now() - 90d AND product = 'influxdb'`
`SELECT count FROM usage_computed..active_clusters_fourteen WHERE time > now() - 90d AND product = 'influxdb'`
`SELECT moving_average(mean("count"),14) FROM "usage_computed"."autogen".unique_clusters_by_day WHERE time > now() - 90d AND product = 'influxdb' group by time(1d)`

They all return data, and the graph looks correct. Upon saving the queries, only the third one shows data. On closer inspection, the first two queries are submitted with a `WHERE time > now() - 90d` clause, and are saved with a `WHERE time > now() - 15m`. :-(

**Comment by goller** [comment]
Sadly the queryConfig does not persist the time range... so, the first two are identified as queryBuilder-like queries, but, because we don't persist time range we get the range from the drop down.

**Comment by rkuchan** [comment]
Including this global time template var will refer to the value currently selected in the Dashboard time range dropdown.

User has the option to replace this template var with a particular time range specific to the query

**Comment by jaredscheib** [comment]
We'll wait to implement this until template variables from #1213 are ready.

In the meantime, it'd be great to see designs from @alexpaxton.
