### ISSUE TITLE
there is an updated docker image? ( latest is for version 0.13)

### ISSUE THREAD

**Issue by toni-moreno** [influxdata/chronograf#1234]
When downloading latest available image in hub I've found that latest is also 0.13.

 There is any other way to get the lastest docker image ?

Thank you very much!

```
root@dockerdev01:~/# docker image inspect chronograf
[
    {
        "Id": "sha256:00a35047b7fb1cd5d0d1cd6ed42f766143eb15572b113970b0655a6925621673",
        "RepoTags": [
            "chronograf:latest"
        ],
        "RepoDigests": [
            "chronograf@sha256:801da07c8ea6d307019f6bbd7239af6f54c6c30255b14487211eb8bfdfeb7c15"
        ],`
...
...
            "Env": [
                "PATH=/opt/chronograf:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "CHRONOGRAF_VERSION=0.13.0"
            ],
```

**Comment by samhatchett** [comment]
It took me a few minutes to figure this one out - check the release notes:
https://github.com/influxdata/chronograf/releases/tag/1.2.0-beta8

there is a section about pulling to docker using `quay.io/influxdb/chronograf:1.2.0-beta8`

**Comment by nhaugo** [comment]
https://github.com/influxdata/influxdata-docker/pull/55
https://github.com/influxdata/docker-docs/pull/5

**Comment by jsternberg** [comment]
This is being tracked in influxdata/influxdata-docker so I'm going to close this issue.
