### ISSUE TITLE
Persist sources set via the CLI

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/chronograf#1237]
## Current behavior

Sources configured via the CLI (add in https://github.com/influxdata/chronograf/pull/1129) are stored in memory.

## Desired behavior

Sources added via the  `--influxdb*` or `--kapacitor*` CLI options should persist even if the options are no longer set via the CLI.

The user-specified source name should be auto-generated from the CLI options. Probably something like `InfluxDB {hostname} from CLI`.

To prevent duplicate sources from being created, CLI options should only create a new source when the values of `--influxdb`/`--influxdb-username` (or `--kapacitor`/`--kapacitor-username`) do not match an existing source's address and username.

## For discussion

Should passwords set in the CLI be persisted to the matching source? My first inclination is "no".

cc'ing @jackzampolin for more input.

**Comment by russorat** [comment]
users should use a `.src` file as described in https://github.com/influxdata/chronograf/issues/2659#issuecomment-354164604 if they want persistent sources.
