### ISSUE TITLE
hosts never disappear.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/chronograf#1241]
hosts never disappear from the host list.  I assume this is due to it just querying the tags in influx directly.
be nice for a way to clear out hosts automatically if they have been dead for X time.

**Comment by nhaugo** [comment]
This will be addressed by features in InfluxDB 1.4

**Comment by dibits** [comment]
Any ETA on this feature? Also any workarounds in the meantime?

**Comment by nhaugo** [comment]
The workaround is to drop series from hosts that you don't want. We should be working on a bit easier solution when we tackle https://github.com/influxdata/chronograf/issues/682
