### ISSUE TITLE
Remove the k8s dashboard

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/chronograf#1242]

**Comment by danisabad** [comment]
https://github.com/influxdata/chronograf/releases/tag/1.2.0-beta8
#1112: Add ability to delete a dashboard

**Comment by james-lawrence** [comment]
ha sorry thought I had the most recent version. =) will reinvestigate.

**Comment by james-lawrence** [comment]
okay the kubernetes dashboard still exists unfortunately and still no way to delete that. but otherwise looks good. (still investigating if that dashboard is related to the canned directory)

**Comment by 121watts** [comment]
@james-lawrence.  There will be a way to remove the Kubernetes dashboard in the not too distant future.

**Comment by nhaugo** [comment]
Remove this dashboard and create an empty state for the dashboard index.
