### ISSUE TITLE
define dashboards via a directory/file structure.

### ISSUE THREAD

**Issue by james-lawrence** [influxdata/chronograf#1243]
be nice to be able to define dashboards into a folder that gets loaded at startup. version control/ease of deployment. reduces operational cost of running the tick stack such as ensuring db backups/restores etc.

```
../dashboards/example/dashboard.meta
../dashboards/example/graph1.graph
../dashboards/example/graph2.graph
../dashboards/example/graph3.graph
../dashboards/example/table1.table
```

**Comment by james-lawrence** [comment]
noticed the canned directory, that is more or less what I was interested in being able to define but have it be a directory the user can specify and add files to.

**Comment by goller** [comment]
Hi @james-lawrence, I'm happy to hear that!

Chronograf as the `--canned-path=` command line options (or `$CANNED_PATH` env var) to help you define where those files go:

https://docs.influxdata.com/chronograf/v1.3/administration/configuration/#c-canned-path

**Comment by nhaugo** [comment]
@james-lawrence a workaround for the version control would be to GET the resources you want saved from the server.

You can use $HOST/docs for documentation on the ReST API also https://github.com/influxdata/chronograf/blob/master/docs is a good reference

**Comment by goller** [comment]
Hi @james-lawrence , it's been a while, but, I've just submitted PR #2593 that allows dashboards to be hosted from files!

**Comment by james-lawrence** [comment]
Cool, will take a look. Was looking into updating chronograph today. And
reconfiguring it, will check this out sometime the next two weeks.

**Comment by nhaugo** [comment]
• We will need the ability to define a data source from a file
• Both this new file and the org file will need to support pulling in env variables
• The org file should be able to reference source definitions
• Also ensure that sources can have kapaictors added to them
• Deprecate the --new-sources command line flag
