### ISSUE TITLE
Chore: Research bind parameters in InfluxDB

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1246]
https://docs.influxdata.com/influxdb/v1.2/tools/api/#query-string-parameters

**Comment by goller** [comment]
Appears to be a no-go using query string parameters.  As documented it only appears to work in where clauses. I've read through the source code in influx and I suspect it was intended to be general purpose but seems to be restricted.

@pauldix do you know the history behind query string `params` for influxql queries?  We were hoping to use them as general purpose template strings.

**Comment by pauldix** [comment]
Do you mean that `params` is a query string parameter that can be used on InfluxDB?

**Comment by goller** [comment]
@pauldix yup, the `params` parameter to the `/query` endpoint.

**Comment by pauldix** [comment]
@goller Didn't know that existed. I don't think it does anything. Must be like vestigial prehensile tail.
