### ISSUE TITLE
As a user I can add and edit template variables

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1249]

**Comment by alexpaxton** [comment]
#### Creating a template variable
1. User clicks `New Variable` (blue button on right)
2. New table row appears in "Edit Mode" with the first field in focus (dropdown label)
3. Shortcode field cannot include spaces, only `A-Z a-z 0-9`, always prefixed with `$`
4. The Data field accepts queries that produce the matching type of data (eg. a list of tag values for a tag variable)
5. The Data field also accepts comma separated lists
6. Error handling TBD
7. User can click the green check to confirm or the x to cancel

#### Editing a template variable
1. User hovers over a table row, `Edit` & `Delete` buttons appear
2. Clicking edit changes the row to edit mode
3. See above

#### Deleting a template variable
1. User hovers over a table row, `Edit` & `Delete` buttons appear
2. Clicking delete causes confirmation buttons to appear, requires a second click
    * This might be overkill, could be smoother to just single-click delete

#### Permanent template variables
- Ex: global time
- Cannot be deleted or modified

![template-variables-panel](https://cloud.githubusercontent.com/assets/2433762/24930569/cd0f4de2-1ebe-11e7-8957-792ddb865838.jpg)
