### ISSUE TITLE
As a user I can see a list of template variables in the query builder

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1252]

**Comment by alexpaxton** [comment]
![screen shot 2017-04-11 at 6 08 32 pm](https://cloud.githubusercontent.com/assets/2433762/24937545/4293bf7c-1ee6-11e7-98c7-fa4c4e6173e3.png)

See #1253 for more detail

**Comment by lukevmorris** [comment]
Closing in favor of #1262
