### ISSUE TITLE
As a user, I can click on a template variable in the query builder to include it in the query I'm building.

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1253]

**Comment by alexpaxton** [comment]
### Overview
- Shuffled some things around so this addition will fit nicely
  - No more "Graph Editor" title (don't miss it when it's gone, probably wasn't adding much)
  - Shortened "Visualization Type" to "Type", pushed to left side

### Inserting a template variable into a query
![screen shot 2017-04-11 at 6 08 32 pm](https://cloud.githubusercontent.com/assets/2433762/24937048/cc07b62c-1ee2-11e7-8aed-daf043fcaec2.png)

- User clicks `Insert` dropdown in "Variables" section
  - Populated with configured variables, represented by their shortcode
  - Query builder should know where to insert the variable, based on the specified type (Tag / Measurement / Etc.)

<img width="400" alt="screen shot 2017-04-11 at 6 08 58 pm" src="https://cloud.githubusercontent.com/assets/2433762/24937061/de898eb0-1ee2-11e7-9c2f-2501fe263f3b.png">

- Once a variable is inserted, its corresponding dropdown appears to the right of the `Insert` dropdown
- The Query builder should respond accordingly (see below for example)
- User should also be able to manually delete `$variable1` from the query string

<img width="295" alt="screen shot 2017-04-11 at 6 21 10 pm" src="https://cloud.githubusercontent.com/assets/2433762/24937181/b32c798e-1ee3-11e7-94cd-717a8e801759.png">

**Comment by lukevmorris** [comment]
Closing in favor of #1262
