### ISSUE TITLE
As a user I can see configured template variables in the dashboard view

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1255]

**Comment by alexpaxton** [comment]
Include the `Dropdown Label` in the dropdown in the same fashion as AutoRefresh and Time Range

### Potential Issues
- Too many items in heading

### Potentail fix
- Only show a variable dropdown if that variable is present in at least 1 query in 1 cell in the dashboard.
- Else hide until it is used

![template-variables-dash-heading](https://cloud.githubusercontent.com/assets/2433762/24931120/e46a8482-1ec0-11e7-82ff-bbbf23467d99.jpg)

**Comment by cryptoquick** [comment]
For fixture, see: https://github.com/influxdata/chronograf/pull/1304#issuecomment-294578021
