### ISSUE TITLE
As a user I can see a list of variables populate in "raw query mode" when i type "$"

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1262]
Put list of variables near the "$" similar to how slack handles emoji

**Comment by alexpaxton** [comment]
https://draftjs.org/

Facebook built this after a lot of UI issues with tagging users as you type. Seems like it could also be a good foundation for stuff we might do in the future (TICKscript editor, query syntax highlighting, inline query errors, etc.)

**Comment by alexpaxton** [comment]
I would also add that we will likely have to switch between `<textarea>` and `<pre>` to get this to work, and there will be mad jitter between the two. `<textarea>` is extremely limiting on what you can customize with it, will be a major headache to figure out and facebook already went through that journey
