### ISSUE TITLE
Make Heartbeats Great Again

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1266]
We need to replace Everlasting JWTs with Refreshing JWTs:
- If a server has `auth_duration=0` then we need to use refreshing JWTs
- JWTs should thus be extended by a heartbeat, or any other client request
- Get rid of `EverlastingClaims` (JWT)

NOTE: The heartbeat currently exists to ensure proper auth between server processes that may have different configuration options for `auth_duration`.

**Comment by lukevmorris** [comment]
![refreshing](http://www.zastavki.com/pictures/1920x1200/2012/Food_Berries__fruits__nuts_Refreshing_lime_033619_.jpg)
