### ISSUE TITLE
bashboard table no data

### ISSUE THREAD

**Issue by hmmatos** [influxdata/chronograf#1267]
Hello, 
not sure what happened but anyone knows why table data show in data-explorer but not in table dashboard?

![screenshot-185 79 226 223-8888-2017-04-13-16-09-47](https://cloud.githubusercontent.com/assets/4135196/25011790/7c9b2e4a-2066-11e7-8c72-729a27614f12.png)

![screenshot-185 79 226 223-8888-2017-04-13-16-13-07](https://cloud.githubusercontent.com/assets/4135196/25011799/83324e0a-2066-11e7-8ff7-290cd2a8bfaf.png)

**Comment by 121watts** [comment]
@hmmatos.  Thanks for writing in!  I'll dig into this today.

**Comment by nhaugo** [comment]
- Remove table option in dashboard editor overlay
