### ISSUE TITLE
Query builder inserts "=" when "!=" is selected the opposite is also true

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1268]
If this is not the case the radio button is very hard to tell what is the current selection.

**Comment by 121watts** [comment]
@nhaugo im not seeing this behavior.  I can work with @alexpaxton on making it clearer on which one is selected.

**Comment by alexpaxton** [comment]
@121watts just took a look, is definitely confusing. I have an idea for how to fix, might even look nicer too

**Comment by alexpaxton** [comment]
Working on this inside a larger PR
