### ISSUE TITLE
Query builder shows "no measurement selected" in the tags section when typing in a query

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1269]
Start with an empty query builder, type out the query:
SELECT "usage_user" FROM telegraf..cpu WHERE time > now() - 15m AND "cpu" = 'cpu0'

The db, measurement and field is selected, but the tags section is empty.

**Comment by 121watts** [comment]
That's because an RP wasn't specified in the query.  

@nhaugo @goller what should be the behavior of the /queries endpoint when an RP isnt specified?  Should we the response attach the default RP?

**Comment by goller** [comment]
@121watts when no RP is specified it should use default RP.  I don't think there should be a problem with @nhaugo 's query.
