### ISSUE TITLE
As a user, in a dashboard, I can see a Template Variable Control Bar at the top of the dashboard

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1281]
See design [here](https://github.com/influxdata/chronograf/issues/1255#issuecomment-293402156). This should be present for an empty Dashboard, and should appear above any Dashboard Cells.

`V1`: Given a dashboard with many cells, and a user who scrolls down the page, let the user scroll the TV Control Bar off the page
`V2`: Stick the TV Control bar to the top of the Dashboard such that it can't be scrolled off the page. [See this issue](https://github.com/influxdata/chronograf/issues/1282)

**Comment by 121watts** [comment]
![template-variables-control-bar](https://cloud.githubusercontent.com/assets/7582765/25051399/406b031e-2101-11e7-8fe7-70e3477760a6.png)
