### ISSUE TITLE
RFC: When creating a database, auto-sort by alphabetical feels jarring

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1284]
Repro steps:
1. go to Admin/DB Management
2. click Create Database
3. type in a name of something
4. feel page jump as you type in a name that would sort to somewhere not at the top

Thoughts?

**Comment by nhaugo** [comment]
It would be better to drop it in place once the user has completed typing. In the future look at something a with a bit better of a ux.
