### ISSUE TITLE
Show influxdb source in header

### ISSUE THREAD

**Issue by danisabad** [influxdata/chronograf#1287]
If you have to deal with many datasources it would be very convenient to see what is your corrent one.

**Comment by timraymond** [comment]
Hey @danisabad ! Thanks for writing in.

This icon shows the currently connected source when you hover over it:

![hover](http://g.recordit.co/uUj3mNPc4b.gif)

**Comment by danisabad** [comment]
Thank you, for me it was a little unobvious :)
Maybe it make sense to just display name?

**Comment by jaredscheib** [comment]
@alexpaxton what do you think about changing this icon to a more standard "database" style icon, like the SVG you added recently to cloud?
