### ISSUE TITLE
As a user, when navigating to a dashboard, I can use the dashboard's name/slug in place of its id in the resource url

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1290]
See [this](https://community.influxdata.com/t/dashboard-id-in-url-problems/537) for more details

**Comment by hasselrot** [comment]
Thats great news!

**Comment by nhaugo** [comment]
In the case that more than one dashboard share the same name, use the first one found

**Comment by nhaugo** [comment]
add the name as a resource eg `http://localhost:8888/sources/2/dashboards/foo`
