### ISSUE TITLE
Unable to get apps for hosts

### ISSUE THREAD

**Issue by zodman** [influxdata/chronograf#1307]
version 1.2.0~beta6-1

```
Unhandled promise rejection TypeError: seriesObj.tags is undefined
Traza de la pila:
getAppsForHosts/</<@webpack:///./src/hosts/apis/index.js?:240:11
getAppsForHosts/<@webpack:///./src/hosts/apis/index.js?:234:5
notify/</run@webpack:///./~/core-js/library/modules/es6.promise.js?:87:22
notify/<@webpack:///./~/core-js/library/modules/es6.promise.js?:100:28
module.exports/flush@webpack:///./~/core-js/library/modules/_microtask.js?:18:9


```
For some reason the error was showed.
the problem not show error on console or network of my chrome.

The only think can be its affecting a new node with empty hostname can be the problem!

**Comment by nhaugo** [comment]
@zodman can you test this out on a newer version?

**Comment by zodman** [comment]
using ‘chronograf_1.2.0~beta9_amd64.deb’ 

the problem still.

take a look if my developer bar of chrome show some some info.
https://www.useloom.com/share/b15062a70bc24413a15df1daf123660f

**Comment by 121watts** [comment]
@zodman.  Tracked down the issue.  Should have a fix up for this relatively soon.
