### ISSUE TITLE
Modify Template Variable Control Bar Display/Functionality in Presentation Mode

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1310]
Moved from #1255

### Control Bar in Presentation Mode
- Read Only in presentation mode
- Adds clarity and context (when the user wonders, what exactly am I looking at?)
- Up for discussion:
  - Time range & auto refresh values (why not?)
  - Dashboard name

![dash-presentation-mode-v3](https://cloud.githubusercontent.com/assets/2433762/24936335/39201430-1edd-11e7-91bf-8c041a4c347f.png)

**Comment by 121watts** [comment]
Looks like we've got this now!
