### ISSUE TITLE
As a user, I should be able to select multiple values in a template variable dropdown

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1313]

**Comment by nhaugo** [comment]
See also #2244

**Comment by Gelob** [comment]
I'd very much like this feature, as someone trying to look at using chronograf in place of grafana.

**Comment by candlerb** [comment]
Seconded.  However I think this would need influxql to gain the SQL `IN` operator, plus the ability to expand a variable as a list rather than a string, e.g.

~~~
SELECT ... WHERE mytag IN (:mylist:)
~~~

**Comment by Gelob** [comment]
People still want this feature!

**Comment by geniousphp** [comment]
Yes, this is important feature. At least, we'd like to have the option to "select all" (or ignore the variable filtering)

**Comment by tmdoit** [comment]
Are you planning to add this feature?
