### ISSUE TITLE
As a user I can write data using the admin de

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1328]

**Comment by alexpaxton** [comment]
Simplest implementation is probably to use the `QueryEditor` text box and allow Line Protocol. We would need to indicate to the user that they are now in a different mode, but can re-use the query status bar.

### Proposed Flow
1. User begins with the `QueryMaker` text field
![write-data-1](https://cloud.githubusercontent.com/assets/2433762/25597323/f0721700-2e82-11e7-8e45-83fbefd61e99.png)

2. User initiates **Line Protocol** mode by typing `INSERT`
![write-data-2](https://cloud.githubusercontent.com/assets/2433762/25597339/0550cbbc-2e83-11e7-8b65-935d7c3b1bec.png)

3. **Line Protocol** mode is made evident via the tab name and the Query Templates dropdown being replaced by the **Write Data** button
![write-data-3](https://cloud.githubusercontent.com/assets/2433762/25597363/1f69f3a2-2e83-11e7-86cf-f88f24d570c6.png)

4. User has typed in a full line of data, then clicks **Write Data**
![write-data-4](https://cloud.githubusercontent.com/assets/2433762/25597391/461b92d0-2e83-11e7-9bd9-58bd65d04713.png)

5. If the line is correct, the status reads "Write Successful!" and the **Write Data** button becomes a **Clear** button, which keeps the tab in Line Protocol mode while clearing the contents out to make room for a new line
![write-data-5](https://cloud.githubusercontent.com/assets/2433762/25597434/82d4ba08-2e83-11e7-8f84-9fa5e0e5e5ff.png)

6. If the user wants to go back to writing queries, they would need to create a new tab. However, might also be more convenient to have the tab revert to query mode once `onBlur` fires and the field is empty
