### ISSUE TITLE
RFC: As a user I can support time range as a template variable

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1329]

**Comment by lukevmorris** [comment]
After discussion with Nate, here's my current understanding:
- Currently Time Range is stored as a single global value across all dashboards
- We want to replace Time Range's foundation with a template variable
- This means that a user will have one Time Range per dashboard, and their values will be persisted on the backend nested beneath each dashboard

- If a user explicitly enters a time range (`where time > now - 17m`), then we'll store that and respect it
- If a user explicitly enters the time range template variable (`where time > now - :timerange:`), we will respect it
- If a user doesn't enter a time range, we'll implicitly use the time range template variable

**Comment by jaredscheib** [comment]
Seems like this could be done as follows:
- [ ] add tempVar `:defaulttimerange:` to every new dashboard via NEW_DASHBOARD const
- [ ] create a list of permanent tempVars and store under `dashboards/constants`, i.e. `['defaulttimerange']`
- [ ] prevent display of `DELETE` button for any permanent tempVars
- [ ] style permanent tempVars slightly differently to indicate special status
- [ ] remove `<TimeRangeDropdown />` from `<DashboardHeader />`
- [ ] remove wiring of `timeRange` value through `<Dashboard />` children
- [ ] replace `timeRange` from invocations of `buildInfluxQLQuery` (& `timeBounds` within it) to insert `WHERE time > :defaulttimerange:`
- [ ] add new `Time Range` type to <TemplateVariableManager />'s `type` dropdown
