### ISSUE TITLE
[1.2.0~beta9] Slack's Send Test Message button doesn't work

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1333]
Nothing happens when I configure Slack as an event handler and click the `Send Test Message` button.
The behavior is the same both before I save the configuration and after I save the configuration.

### Repro steps

1. Configure the Slack with webhook url
2. Click `Send Test Message`
3. I wait impatiently as it connects, I go online, and my breath catches in my chest until I ... see nothing happen (https://www.youtube.com/watch?v=ipA-EfdJJrc)
4. Click `Save`
5. Try `Send Test Message` again
6. Stare into the abyss

The green `Slack test message sent` box does show up at the top of the page.

**Comment by jademcgough** [comment]
ref #1437

**Comment by nhaugo** [comment]
This will be solved by #1437
