### ISSUE TITLE
Settings for Axes

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1339]
Hi!

In grafana it is possible to change settings for the graphs, such as "Axes".

In my use case I would like to set the Axes Y-Min to "0" so I know that the graph always starts on 0.

My graph in Chronograf:
![screen shot 2017-04-27 at 09 37 15](https://cloud.githubusercontent.com/assets/16920380/25472887/80c0fdb6-2b2d-11e7-8d76-d754c272bb0a.png)

Settings in Grafana:
![screen shot 2017-04-27 at 09 38 06](https://cloud.githubusercontent.com/assets/16920380/25472901/8ccc03e4-2b2d-11e7-99fc-f4389872914f.png)

Expected Result (example from Grafana):
![screen shot 2017-04-27 at 09 40 36](https://cloud.githubusercontent.com/assets/16920380/25472931/a3bd18e0-2b2d-11e7-8b5a-221ec2fe4681.png)

**Comment by nhaugo** [comment]
@hasselrot this is on our roadmap, not totally sure when yet though.

**Comment by hasselrot** [comment]
@nhaugo great!

**Comment by hasselrot** [comment]
Is there a public roadmap?

**Comment by nhaugo** [comment]
@hasselrot only what is in github

**Comment by a9tm** [comment]
I really hope Chronograf supports changing Units of y axis soon. 

Current setting is unmeaningful:
![Imgur](https://i.imgur.com/ZOT7Mo7.png)

**Comment by hasselrot** [comment]
@a9tm yeah I almost forgot about this. This is pretty urgent I would say for a graphing tool.

**Comment by nhaugo** [comment]
See also #1413 and #1536

**Comment by 121watts** [comment]
@hasselrot With the release of 1.3.6 you can now set the range and y-axis label.  You can find the settings under the new 'Display Options' tab when editing a graph in a dashboard.  Currently working on adding more axes features.

**Comment by lukevmorris** [comment]
Blocked on #1844

**Comment by jaredscheib** [comment]
No longer blocked there.

**Comment by danlg** [comment]
It is a bit better with label and range for Y axis but still a chart for 2 series with 2 Y axis cannot be visualised yet. See https://github.com/influxdata/chronograf/issues/1936
