### ISSUE TITLE
[beta9] Host List's status icon goes missing instead of turning red

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1346]
When one of my Telegraf instances goes down, I'd expect the status icon to turn red. Instead, it disappears - leaving me like https://www.youtube.com/watch?v=Yt-KMPvgKPo.

![image](https://cloud.githubusercontent.com/assets/8750814/25509031/c782c9c2-2b6a-11e7-847c-b857e2e39632.png)

### Repro steps

1. Turn off a Telegraf
2. Wait a minute
3. See the status icon disappear

**Comment by pratibhadeepti** [comment]
do systemctl status telegraf
then you will see the error in running telegraf file,rectify the same.

**Comment by pratibhadeepti** [comment]
do systemctl status telegraf
then you will see the error in running telegraf file,rectify the same.
 systemctl status telegraf
![trobleshoot2](https://cloud.githubusercontent.com/assets/24888412/26447094/9363070a-4164-11e7-83fb-8a5ba163de02.PNG)

After making changes to my telegraf file and restarting the telegraf gave me result as:
![trobleshoot1](https://cloud.githubusercontent.com/assets/24888412/26447035/4afb481a-4164-11e7-9324-d5b8e76d6d23.PNG)
