### ISSUE TITLE
Kapacitor config edit page UX confusing upon failure to connect to kapacitor

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1360]
An error notification comes up, but the empty space at the right makes me think that the UI is formatted for mobile, or that something is missing. Seems like a gray box with "Failed to retrieve Kapacitor config" should appear at the right, or something to a similar effect as the `<EmptyTable>` component when a table is empty.
<img width="1440" alt="screen shot 2017-04-28 at 5 44 47 pm" src="https://cloud.githubusercontent.com/assets/6403018/25551483/6300e670-2c3a-11e7-868c-55566f36110b.png">

**Comment by alexpaxton** [comment]
![screen shot 2017-05-01 at 3 50 09 pm](https://cloud.githubusercontent.com/assets/2433762/25597822/e485f6f2-2e85-11e7-8807-e4a48894a750.png)
