### ISSUE TITLE
Improve Template Variable Manager UX

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1361]
- [ ] "Confirm" dialogue appears when clicking X with unsaved changes -- should be something organic
- [ ] should not have to click "Get Values" -- just automatically retrieve them when changing dropdown selection
- [ ] don't call `this.componentDidUpdate()` ever.
- [ ] don't enable "Save Changes" button when edit mode is entered for a TV row and no changes are actually made
- [ ] possibly change name of `handleRunQuerySuccess` to `onRunQuerySuccess` -- let's discuss
- [ ] possibly try a different look/layout for Template Variable labels in the selector at the top of a dashboard
- [ ] add ability to rearrange template variables in the ui (https://github.com/influxdata/chronograf/issues/1466)

**Comment by russorat** [comment]
[template-variables-config--v2.pdf](https://github.com/influxdata/chronograf/files/2069895/template-variables-config--v2.pdf)

**Comment by russorat** [comment]
feedback on v2 design
 - no reordering of the template variables
 - the regular expression should be run as part of the query
 - regular expression can be removed from custom query
 - add ability to upload a csv file for the map type
 - add the ability to download the values of the template variable as a csv

**Comment by alexpaxton** [comment]
[template-variables-config--v3.pdf](https://github.com/influxdata/chronograf/files/2086206/template-variables-config--v3.pdf)

**Comment by russorat** [comment]
- [ ] add a note to the custom query saying it should be a valid meta query
- [ ] if there is an error in the results (it returned more that one column for example), we don't let them save the template variable
- [ ] csv upload accepts line delimited values as well as comma delimited

**Comment by russorat** [comment]
add requirements list
break into multiple stories

**Comment by russorat** [comment]
closing this in favor of:
https://github.com/influxdata/chronograf/issues/3631
https://github.com/influxdata/chronograf/issues/3635
https://github.com/influxdata/chronograf/issues/3637
https://github.com/influxdata/chronograf/issues/3639
