### ISSUE TITLE
What InfluxDB - Query Performance means

### ISSUE THREAD

**Issue by jimaek** [influxdata/chronograf#1362]
![chrome_2017-04-29_12-21-13](https://cloud.githubusercontent.com/assets/1834071/25554773/5e2e97b8-2cd6-11e7-8aba-fec4bd0524a3.png)

This is the default influxdb chart, I didnt modify it in any way.
I dont understand what this chart shows.  What the value of 10M means? 10 million? Of what?

**Comment by goller** [comment]
Hi @jimaek , well, that chart isn't very useful!  The units are in nanoseconds, but I've just added a PR here: https://github.com/influxdata/chronograf/pull/1478
