### ISSUE TITLE
Misc refactoring / code cleanup / implement conventions

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1372]
Ongoing list of miscellaneous syntax updates & refactoring, written with @lukevmorris:
- [ ] Update old React patterns to current syntax (ex. `createClass` --> ES6 `class`)
  - [ ] can try using the official tool for this: https://github.com/reactjs/react-codemod
- [ ] Action type strings => action type constants
    - [ ] shared/constants/actionTypes.js
- [ ] declarative vs imperative Redux actions, i.e. redux actions syntax: imperative style (`ADD_EVERY`) for synchronous action creators and declarative style (`USER_REQUESTED/_COMPLETED/_FAILED`) for async action creators
- [ ] Use normalizr
    - [ ] .map((c) c.x === x && c.y === y ? newCell : c)
    - [ ] Also .find((c) syntax … 
        - [ ] [c.id]: newCell maybe? Wherever possible
        - [ ] Stop using x/y coordinates
    - [x] Remove updeep
    - [ ] a lot of our reducers use array methods, ex.`.map`, which does in some sense mutate state when items are objects
- [ ] Get rid of `function` and other non-ES6 syntax
- [ ] Rename dashboard/reducers/ui.js
- [ ] Rename dashboard/actions/ui.js
- [ ] React router passing string dashboardID, have to convert to +dashboardID
- [ ] `setState(isLoading: true/false)` patterns
    - [ ] indication that it could likely be done via action creator + redux & we could take that state out of the respective component
    - [ ] fetchTimeSeriesAsync and other AJAX are being called directly by components
- [ ] editCellQueryStatus vs editQueryStatus
- [ ] use aliased absolute paths for `import` statements instead of relative paths
    - [ ] ex. `import AlertsTable from '../components/AlertsTable'` => `import AlertsTable from 'src/alerts/components/AlertsTable'`
- [ ] on a related note, Dashboard-related components do a lot of checking to first see if there is a dashboard present -- [ ] this should be asserted at a point closer to the root of the component tree, rather than performing a check in multiple places deeper down
- [ ] clarify var name use of `template` vs `tempVar`
- [ ] `import {errorThrown as errorThrownAction}` --> `import {errorThrown as errorThrownActionCreator}`
- [ ] rename `templateControlBarVisibilityToggled` & `TEMPLATE_CONTROL_BAR_VISIBILITY_TOGGLED` to follow sync/async convention
- [ ] factor out functionality like autorefresh, presentationmode, timerange, etc. from DashboardHeader into a (boolean-configurable) HOC
- [ ] refactor links trickery from AJAX into `shared/links` action + reducer
  - [ ] move auth links and logout link into this object (and consolidate respective actions, action creators, and reducers, ex. `logoutLinkReceived`, part of `authReceived`)

### Status Page
- [ ] Refactor LayoutRenderer to take pre-constructed cells, instead of making decisions about cells that have `isWidget: true` flag, and decide how to handle widget cells pre-LayoutRenderer.
- [ ] Consider factoring graph-builder parts of LayoutRenderer out into a middle component so that LR is just about positioning, and StatusPage can use it
- [ ] dynamically get `const` values in LayoutRenderer for STATUS_PAGE_ROW_COUNT and PAGE_HEADER_HEIGHT and PAGE_CONTAINER_MARGIN
  - [ ] consider getting all styles and loading into memory for dynamic className-based lookup so that these kinds of values don't get out of sync
  - ref: https://stackoverflow.com/questions/324486/how-do-you-read-css-rule-values-with-javascript

### Server
- [ ] refactor smart JSON unmarshaler for template variables

**Comment by jaredscheib** [comment]
@russorat we had considered breaking this up into multiple stories, but upon review here, i think that it would be best to simply tackle this as one chore. and whoever does it -- whether myself or someone else -- can create stories for any that seem like larger chunks of work. but i think that whoever addresses this would find it easier to simply get in the mode of doing a sweep. i don't know which are still relevant, either. let's leave it as one story for now. i'm happy to tackle it and close it if it seems unapproachable to anyone else.

**Comment by russorat** [comment]
:sweep: :sweep: :broom:!
