### ISSUE TITLE
Host Pages can't be navigated to when --basepath is used

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1388]
Possibly due to `react-router` deprecating `location.query`: https://github.com/ReactTraining/react-router/issues/3336

It should still fail but seems to work (though there are no query params?) when loading a Host Page when `--basepath` is not enabled.

**Comment by nhaugo** [comment]
Can we try to reproduce this @jaredscheib or @timraymond

**Comment by russorat** [comment]
i don't see this problem in the latest builds.
