### ISSUE TITLE
Esc does not exit Presentation mode

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1393]
Hi!

In Safari, pressing Esc does not exit Presentation mode.
I have to reload the page to get out.

Running Chronograf 1.2.0~beta10 (git: ae27d5e6fd847b689a833112f6e701d25805f83c)

**Comment by jademcgough** [comment]
Hi hasselrot!

Yikes - I just tried it out and was able to replicate the problem. I'll work on a fix later today.
