### ISSUE TITLE
Chronograf URL in EC2

### ISSUE THREAD

**Issue by xylene1980** [influxdata/chronograf#1402]
I have installed TICK stack on my EC2 instance. But not able to access the same with http://<ec2instanceip>:8888 . Do i need to any other setup to access the Chronograf interface to access in EC2

**Comment by jackzampolin** [comment]
@xylene1980 Have you set the Security groups to enable access to the :8888 port?

**Comment by xylene1980** [comment]
@jackzampolin Thanks , Yes i had not given to :8888 port. Thanks for the reply. 👍
