### ISSUE TITLE
Export as CSV option for Query Builder

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1405]
Currently there are Table and Graph options. It would be nice if there was a CSV export. This would be useful for business users. Some more justification in [this community post as well](https://community.influxdata.com/t/options-for-data-explorer-csv-export/839).

**Comment by mkarlesky** [comment]
Just wanted to pipe up as the author of the referenced community post.

Relevant section from that post:

> We know we're going to have data analysis needs outside well-defined workflows and visualizations. This means ad hoc number crunching in Python, Mathematica, R, Excel, etc. CSV dumps are pretty much the defacto standard for importing data into these sorts of tools.
> 
> Of course, we'd rather not have our ad hoc data analysts interacting directly with the database. Similarly, we'd like to avoid relying on a single person specializing in formulating command line queries to extract needed data from Influx.
> 
> Ideally, we want the Data Explorer interface of Chronograf (1.2) with the option to export CSV data from query results. We had high hopes for this given that Chronograf already has a nicely formatted tabular view of Data Explorer results. But, unfortunately, no download feature exists.

**Comment by danlg** [comment]
@nhaugo confirm need for business users

**Comment by core-process** [comment]
CSV and Excel would be nice! There are npm modules out there which are able to generate valid *.xlsx within the browser.

Looking forward to this feature! :-)

**Comment by core-process** [comment]
Is there a timeline available for this feature? :-)

**Comment by lipoteFR** [comment]
Est il possible d'avoir accès à l'ancienne interface en 8083 !!!!!!
On tapait du sql on faisait Ctrl+A Ctrl+C dans Excel Ctrl+V et c'était gagné 
C'était trop facile (certainement) 
ça fait chier de devoir cliquer 12 fois dans des IHM 5.0 qui 1x sur 2 crache le message "Script to long" et te plante ton FF

Could we have a simple interface (as before) please
Léopold

**Comment by jaredscheib** [comment]
@lipoteFR, je veux clarifier ce que vous nous avez demandé.
1. Que veux dire `IHM 5.0`?
1. Où est-ce que tu dois cliquer 12 fois.. le boton que te laisse télécharger votre data en CSV?
1. Et vous voudriez une table simple pour que vous pouvez copier votre data directement?
