### ISSUE TITLE
Server needs to return queryConfig for queries including template variables

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1411]
Yes QC
```
SELECT "usage_idle", "usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > now() - 15m
```

No QC
```
SELECT :newvar:, "usage_idle", "usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > now() - 15m
```

No QC
```
SELECT "usage_idle", "usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime:
```

**Comment by lukevmorris** [comment]
How is `:dashboardTime:` represented in the QC?

How is `:newvar: ` represented in the QC?
How does the builder behave when there are template variables in the query?

**Comment by russorat** [comment]
@lukevmorris @121watts is this still needed?

**Comment by 121watts** [comment]
@russorat nope.  even if we wanted to, the server no longer hold the context on template variables.  if the frontend needs a `queryConfig` for a templated query it will need to do the replacement itself and hit the `/queries` endpoint.
