### ISSUE TITLE
Extra Commas in CSV tvar input causes empty items

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#1415]
Repro Steps:
1. Create a CSV template variable.
2. Put more commas than you actually need. Like,,,,,,this,,,,,,,,,,,,,,,
3. See empty entries in the tvar dropdown

![Extra Commas Demo](http://g.recordit.co/6jV3KH6O2N.gif)

**Comment by nhaugo** [comment]
Lets convert to set

**Comment by nhaugo** [comment]
@jaredscheib why did this get put back into delivered? I don't see any changes addressing my comment in the PR
