### ISSUE TITLE
Create user initiated tests with buttons for all kapacitor alert nodes

### ISSUE THREAD

**Issue by jademcgough** [influxdata/chronograf#1437]
On the kapacitor configuration page, configuring a slack alert endpoint and clicking "send test message" does nothing. All I get is a `service is not enabled` response.

**Comment by jademcgough** [comment]
This actually isn't broken, I just forgot to enable slack on kapacitor... might be worth adding some better user messaging though.

**Comment by nhaugo** [comment]
Fixed by #428
