### ISSUE TITLE
Support for sub millisecond queries

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1449]

**Comment by poikilotherm** [comment]
I was the guy who asked on the webinar and I would like to extend my question a bit:

Something Grafana and Chronograf as of today are not able to do is display timeseries plots with timestamps of nano- or microseconds.

This seems to be related to Javascript not supporting 64bit timestamps, but maybe you engineering guys come up with some clever tricks to avoid that?

As I want to plot scientific data measured at a few MS/s and let the scientists quickly view things in dashboards / ..., it would be a great relief to have this feature available. :-)

**Comment by goller** [comment]
Hi @poikilotherm, just did a bit of research on this and we could definitely do it.  

InfluxDB can return RFC3339 with nanosecond precision.

We'd need to update our front-end parsing in a few places like https://github.com/influxdata/chronograf/blob/8ad883906379c54f59b74dbf69c1714cadf46142/ui/src/utils/timeSeriesToDygraph.js#L158
... 
and our backend server here: https://github.com/influxdata/chronograf/blob/master/influx/influx.go#L87

**Comment by poikilotherm** [comment]
With a touch of Star Wars: that seem to be the droid you are looking for... 👍

**Comment by nhaugo** [comment]
If dygraphs 2.0 does not support auto x-axis relabeling spin out another issue

**Comment by jaredscheib** [comment]
#1470 and #1471 are prerequisites for this issue

**Comment by nhaugo** [comment]
Looks like the prerequisites for this are complete

**Comment by lukevmorris** [comment]
We're going to do some requirements gathering and then potentially break this out into multiple stories

**Comment by jaredscheib** [comment]
Side note: in the community influxdb Node client they have implemented nanosecond-based Dates: https://github.com/node-influx/node-influx/blob/master/src/doc.ts. Looks like there may be some useful stuff there to glean or at least for reference.

**Comment by nhaugo** [comment]
• The math for interval selection needs to support values less than one
• Dygraph will need updating to support display less than one second

**Comment by relihanl** [comment]
This feature would definitely be of interest to me. I have an urgent need to display waveforms for electricity. I'm happily loading 6000-7000 samples per second into Influx at nanosecond resolution, but right now i have no way to display them.

**Comment by nhaugo** [comment]
@relihanl we are starting with milliseconds, both micro and nano seconds produce new sets of challenges on the frontend. Hopefully micro second resolution won't be far behind, but nanosecond might prove more challenging.

**Comment by relihanl** [comment]
Thanks for the update Nathan. Appreciate the work you are doing on this.

L
