### ISSUE TITLE
Error adding InfluxCloud Kapacitor

### ISSUE THREAD

**Issue by brycekahle** [influxdata/chronograf#1454]
Docker Chronograf: `1ede53723a2e`
Kapacitor version: 1.2.2

Adding our InfluxCloud Kapacitor instance, the UI presents this error: "There was an error getting the Kapacitor config".

Inspecting in the Chrome debugger reveals a failed request:
```
GET https://<redacted>/chronograf/v1/sources/0/kapacitors/1/proxy?path=%2Fkapacitor%2Fv1%2Fconfig

403 Forbidden
user admin does not have \"read\" privilege for API endpoint \"/kapacitor/v1/config\"
```

**Comment by nhaugo** [comment]
Hi @brycekahle I should have this fixed for the admin user. Can you test it out and create a support ticket if it still isn't working.
