### ISSUE TITLE
Sort arrows are reversed on Host List

### ISSUE THREAD

**Issue by brycekahle** [influxdata/chronograf#1455]
Docker Chronograf: `1ede53723a2e`

Sorting a column shows an arrow indicating ascending sort, but is clearly using descending.

<img width="232" alt="screen shot 2017-05-10 at 6 28 25 pm" src="https://cloud.githubusercontent.com/assets/1010430/25924022/90dd5ef2-35ae-11e7-9f83-c91e5f4b9973.png">

**Comment by goller** [comment]
Hey there, thanks for writing in!

@alexxx is on the case and we will have this for our next release next Friday
