### ISSUE TITLE
Update InfluxData Repo with Stable Chronograf

### ISSUE THREAD

**Issue by austinbutler** [influxdata/chronograf#1456]
My understanding is that 1.3.0 is the stable release of the "new" Chronograf, but the [InfluxData repo](https://repos.influxdata.com/centos/7Server/amd64/stable/) has the "old" Chronograf at 1.0.0.

**Comment by nhaugo** [comment]
Thanks for the heads up, we will get this updated

**Comment by austinbutler** [comment]
Looks like it's present now.
