### ISSUE TITLE
Apps do not fully map when number of series is large

### ISSUE THREAD

**Issue by lepi** [influxdata/chronograf#1459]
It seems when you have 10000 or more series in a database, the apps mapping will be incomplete resulting in missing apps on the hosts page.

I am not experienced with javascript debugging, but happy to gather more information from my environment if needed (some pointers on what to look for would be helpful!).

**Comment by lepi** [comment]
Further, appears this is linked to the max-row-limit in influxdb.

**Comment by goller** [comment]
Hey @lepi, thanks for writing in!  Yes, you are totally right.  It is the max-row-limit issue.  If you set it to zero it will be unlimited.

We have some ideas how to handle this issue and we're tracking it here: https://github.com/influxdata/chronograf/issues/1233

Let us know if setting it to zero works!
