### ISSUE TITLE
y value on stacked line chart does not scale properly

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1460]
• Create a group by cpu with user usage
• See graph as scaled to the highest single value point instead of the max of the sum

**Comment by rizadh** [comment]
Similar to #1091

**Comment by danlg** [comment]
same issue for me. Please include in the next release @nhaugo . Is there a workaround ?

**Comment by jaredscheib** [comment]
Notice the clipping at the top of the y-axis when graph type is Stacked:
<img width="629" alt="screen shot 2017-07-22 at 5 16 04 pm" src="https://user-images.githubusercontent.com/6403018/28495464-4802c194-6f02-11e7-81f0-681f2b40d20f.png">

Whereas the same graph as a Line type:
<img width="604" alt="screen shot 2017-07-22 at 5 16 11 pm" src="https://user-images.githubusercontent.com/6403018/28495465-480a5c88-6f02-11e7-89d8-afd1f6a4d769.png">
