### ISSUE TITLE
Template variable selector needs auto complete

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1462]

**Comment by jaredscheib** [comment]
As in, when you type, you can hit `tab` to have it complete with the selected TV?

**Comment by nhaugo** [comment]
Say i have the following vars
1) "aab"
2) "abc"
3) "bac"

I should be able to type:
"a" and see 1 and 2
"aa" I should see 1
"ab" I should see 2
"b" I should see 3

**Comment by jaredscheib** [comment]
Looks like you're talking about filtering based on exact match from the head of the string, yeah?

There is currently filtering, but it matches based on partial string, from anywhere in a string.

**Comment by nhaugo** [comment]
Front of string

**Comment by nhaugo** [comment]
I should be able to type in this field
![1462](https://cloud.githubusercontent.com/assets/1003269/26130908/2f48e134-3a54-11e7-906a-ab3cc03401c2.gif)

**Comment by jaredscheib** [comment]
Ah, I see..
