### ISSUE TITLE
Cannot Open Data Explorer

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/chronograf#1465]
This all the sudden started happening in my local testing environment after playing around with Chronograf for around 1 hour. I haven't been able to figure out how to fix it.

I've recompiled Chronograf, restarted my computer. Deleted all InfluxDb data. Still I get this every time I click on the "Data Explorer" tab. I had compiled from source on the head of master. It's still happening when I checkout v1.3.0. I even downloaded the binary from the releases tab, but I'm still running into this issue.

```
FieldList.js:90 Uncaught TypeError: Cannot read property 'some' of undefined
    at Object.render (FieldList.js:90)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:362)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:238)
    at ReactDOMComponent._createInitialChildren (ReactDOMComponent.js:691)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:516)
    at Object.mountComponent (ReactReconciler.js:46)
```

When I refresh the page on the Data Explorer tab I get this

![image](https://cloud.githubusercontent.com/assets/4132322/25978776/7007c6d8-3692-11e7-8e9f-bf1924424970.png)

I installed Chronograf on a separate VM and did not experience this issue. One thing I noticed different is that the data explorer seems to be kicking this request off on my MacBook where this isn't working. On the CentOS VM it is not sending the SHOW RETENTION POLICIES query when hitting the data explorer.

![image](https://cloud.githubusercontent.com/assets/4132322/25978854/e55cf1e2-3692-11e7-9727-4e2eb68a0f59.png)

**Comment by jademcgough** [comment]
Hi mpchadwick,

I'm not positive that this is the cause, but we use local storage for some persistence in the data explorer. This can sometimes cause a broken state after version upgrades (a fix for this is in the works).

Could you try seeing if the data explorer works in an incognito window? If it does, blowing away your local storage for the page should fix the issue (`window.localStorage.clear()` in your javascript console).

**Comment by mpchadwick** [comment]
Yup that fixed it. I was caught up in the idea that it had something to do with the state of the data on my machine and didn't think that it could be related to some storage in my browser. I think I did actually run multiple versions of chronograf (accidentally executed the wrong binary) when this started happening. Perhaps the local storage should be prefixed with the chronograf version number or commit sha to help mitigate these types of issues when switching versions.

**Comment by mpchadwick** [comment]
Just wanted to state that I experienced the issue again after clearing storage this morning and definitely didn't switch chronograf versions. In that case it was happening while trying to click into a specific Kapacitor alert. 

It seems that this can happen via some workflow without switching versions, although I can't provide repro steps. If do find consistent repro steps I'll advise. I may also be worth adding a guard clause to the JS to prevent the error.

**Comment by jademcgough** [comment]
Ugh, thanks for the heads up, I'll keep an eye out for it. If you do find a way to repro, that'd be super helpful.

The issue for the broken localStorage bug is https://github.com/influxdata/chronograf/issues/1443, should be in our next release.
