### ISSUE TITLE
Feature: Ability to reorder template variables

### ISSUE THREAD

**Issue by Austinpayne** [influxdata/chronograf#1466]
This is somewhat pedantic, but it would be nice to be able to reorder template variables after they have been created. As is, in order to get variables in the order I would like I have to delete and re-create variables.

Ideally, I could reorder them either in the dashboard view or in the add variables view

<img width="342" alt="screen shot 2017-05-12 at 2 24 50 am" src="https://cloud.githubusercontent.com/assets/7528924/25989862/ef5abb70-36ba-11e7-9b9a-a2ff2701f0ea.png">

<img width="1289" alt="screen shot 2017-05-12 at 2 24 59 am" src="https://cloud.githubusercontent.com/assets/7528924/25989863/f229f5be-36ba-11e7-82a9-0ff9e994ed4a.png">

Note: values have been obfuscated above.

**Comment by goller** [comment]
@Austinpayne thanks for writing in! Yeah, I think it would be really nice to move them around in both situations.
