### ISSUE TITLE
Upgrade to dygraphs 2.0

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1469]

**Comment by jaredscheib** [comment]
@121watts @cryptoquick @nhaugo Could you provide context as to the motivation for upgrading? Dygraphs doesn't appear to have been updated in basically 4 months, except for 4 minor commits. It's also on v2.0.0 and has 191 open issues and 13 open PRs. We may have to start maintaining a fork of this library if we want to continue. It'd be good to discuss this.

**Comment by jaredscheib** [comment]
Upon further review, it does appear to be generally stable. Pending further testing by @nhaugo on more complex dashboards. The 2.0.0 release appears to have gone through 4 RCs, and makes at least 5 explicit changes that directly affect making synchronization easier. Whether or not the library continues to be under development, doesn't seem to affect the decision to upgrade or not when considering 2.0.0 vs 1.1.1.
