### ISSUE TITLE
Apply a default time interval in the group by clause for all queries that have a function

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1471]
@goller has the math for this, please add it to the issue.

**Comment by goller** [comment]
https://github.com/influxdata/chronograf/issues/829#issuecomment-279301239

**Comment by jaredscheib** [comment]
@timraymond Could you be sure to mind https://github.com/influxdata/chronograf/issues/1493 when tackling this issue in case it has bearing?

**Comment by timraymond** [comment]
[ ] Add `group by time(auto)` when field is applied
