### ISSUE TITLE
Add more precision to Y-Axis and Legend

### ISSUE THREAD

**Issue by AlleoNET** [influxdata/chronograf#1479]
Hi!
Great job, very easy setup, but also disappointment. 
Please FIX it.
![Image](https://s14.postimg.org/m5e33smip/image4144.png)

**Comment by goller** [comment]
Hi @AlleoNET, thanks for writing in! Yes, we should totally fix this.  I'm going to rename this issue to be add precision to Y-Axis and Legend.

**Comment by AlleoNET** [comment]
Thanks. And.. will be possoble to view chart from more than 30 days?
Limits are not ok.

**Comment by goller** [comment]
Limits are not ok! We'd like to add custom date ranges to the drop down as well.  We have a UI element that does so now for the kapacitor alerts.  We'll need to write it into our date range picker.

**Comment by goller** [comment]
(similar to https://github.com/influxdata/chronograf/issues/839)

**Comment by AlleoNET** [comment]
Very good! Tank you very much.
goller, one think more and Chronograf will be great not only for me -  in Kibana (similar tool from Elastic) each developer can create plugin. I know that Chronograf is OpenSource and also everybody can write something new, but plugins make it a lot of easier. Should be in Chronograd Roadmap.

**Comment by goller** [comment]
@AlleoNET what would be an example of a plugin?

**Comment by AlleoNET** [comment]
I would like to present on one linear chart also some points (from other data source).. Of course we can show two charts one followed by second, but it is not the same. Maby also it is possible, I am testing Chronograf from yesterday so maby current featured fit my needs.

**Comment by nhaugo** [comment]
Arbitrary time/date selection is available. Closing this issue unless there are unaddressed issues in it.

**Comment by andheiberg** [comment]
I would argue this issue has not been addressed. I would still like the ability to see the actual values of the data being graphed. Currently I'm left with imprecise axis and even the overlay on hover doesn't show full values.

![screenshot 2018-02-01 17 27 47](https://user-images.githubusercontent.com/820962/35693215-621b8f28-0775-11e8-88c4-b0bcdcf19529.png)

**Comment by belowm** [comment]
Please look at the screenshot posted by the author of this issue. As far as I can tell, none of these issues have been addressed. Chronograf still lacks a precision setting in the visualization tab.

**Comment by nhaugo** [comment]
I have separated this into the individual asks:
https://github.com/influxdata/chronograf/issues/2838
https://github.com/influxdata/chronograf/issues/2839
https://github.com/influxdata/chronograf/issues/2840
