### ISSUE TITLE
Hover lines and zoom should affect all graphs in a dashboard

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1480]
- [ ] Add support for graphs with different time ranges, i.e. do not show the hover line on graphs that are not on the same time frame as the currently hovered graph.

**Comment by jaredscheib** [comment]
By "hover line", do you mean the vertical white line that indicates where your mouse cursor is over a graph?

**Comment by jaredscheib** [comment]
Dygraphs calls these crosshairs, fyi.

**Comment by nhaugo** [comment]
@jaredscheib yes, the crosshairs. I think the only thing that is missing is if you were to set up two graphs with the following queries:
SELECT "usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime:
and
SELECT "used" FROM "telegraf"."autogen"."mem" WHERE time > now() - 168h
