### ISSUE TITLE
Selecting a time range does not affect graphs that are zoomed

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1481]

**Comment by jaredscheib** [comment]
Could you clarify what the desired behavior is? In other words, do you mean: "Selecting a time range should not affect graphs that are zoomed" ?

**Comment by cryptoquick** [comment]
Also, if you select a time range on the graph, should it update the data set time range in the upper right hand corner? If so, we may need to implement custom time range as part of delivering this feature, re: #1482.

**Comment by cryptoquick** [comment]
Also, also, should the graph zoom reset when the time range in the upper right hand corner is selected, so as to present the user with a blank graph?

**Comment by nhaugo** [comment]
Don't worry about changing the global time when you zoom. So you should only need to reset the zoomed in graphs.

**Comment by jaredscheib** [comment]
And what about if a graph is zoomed, and then you go and select the current time range from the Time Range dropdown-- should graphs reset then as well?

**Comment by jaredscheib** [comment]
Also, if a graph is zoomed, is the expect behavior that it remain zoomed in on that exact slice of time, or just the same window as zoomed into but adjusted forward by how much time has elapsed since zoom?

**Comment by jaredscheib** [comment]
If the time range is changed, do you want the graph to reset immediately, or only upon redraw once the async call for the updated query with the new time range returns from the server?
