### ISSUE TITLE
Add Support For Mathematical Operators On Fields When Configuring Kapacitor Rules (and possibly in the data explorer)

### ISSUE THREAD

**Issue by mpchadwick** [influxdata/chronograf#1487]
It would be helpful to be able to configure Kapacitor rules that use mathematical operators on fields. For example, let's say I want to send an alert based on high redis memory usage. It would be more useful to alert when `memory_used / max_memory` is greater than 0.9 than than based on some static threshold.

![image](https://cloud.githubusercontent.com/assets/4132322/26085604/91c3b8d0-39b3-11e7-9434-c3185bb697e2.png)

It probably makes sense for the implementation to include the data explorer, or be built in such a way that it can later be included in the data explorer.

**Comment by jaredscheib** [comment]
Great idea, @mpchadwick! :+1:

**Comment by mpchadwick** [comment]
I've been digging through the code and giving some thought to how this might be implemented. I have some ideas, but I'm also wondering if this use case would be better accounted for when https://github.com/influxdata/chronograf/issues/789 is implemented...

**Comment by goller** [comment]
@mpchadwick yup, you are totally right.  That's how I imagine we'll get a first version out.  Currently, the `queryConfig` structure is not descriptive enough.  In the future we'll move away from it and begin to use `queryAST`.  

Additionally, @nathanielc and I have talked about exposing more of kapacitor's AST to help ease the construction of tickscripts.

**Comment by mpchadwick** [comment]
@goller ok, i'm going to close this issue then as I don't think it makes sense to implement as a standalone feature.
