### ISSUE TITLE
Warn user about using GROUP BY with graph type of SingleStat or Line+Stat

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1493]
Sometimes a stat (from `SingleStat` or `Line+Stat`) will display a `0` temporarily, which can be very concerning. The problem has been diagnosed below as being related to using a `GROUP BY` in a query. As mentioned below, it would be good to provide a warning to the user via the Query Editor warning display when they're trying to use a `GROUP BY` with a `SingleStat` or `Line+Stat`, per the below.

**Comment by jaredscheib** [comment]
I wonder if this might be resolved by #1530

**Comment by jaredscheib** [comment]
Doesn't seem to be resolved by #1530.

**Comment by jaredscheib** [comment]
Upon inspection, the `data` object passed into `<SingleStat>`, which is returned by a `proxy` call, shows that the `lastValue` in the time series data array is sometimes `0`. This appears due to sparse data, regardless of a `fill` function being used in the influxQL (ex. `fill(0)` or `fill(null)`), as `Math.round(+0|null|'' * 100) / 100` will all yield `0`.

**Comment by jaredscheib** [comment]
It turns out that the issue was in the InfluxQL queries. Solutions to avoid a final value being null are to:
- use `fill(previous)`
- use `fill(none)`
- use a subquery, ex. select last("max")(<query>)
- don't use a GROUP BY, and instead use :dashboardTime:, or use whatever would've been the GROUP BY time interval as the WHERE
- dynamically calculate an offset (second argument passed to `GROUP BY`) and use an absolute time range to ensure that the number of buckets match the number of expected groups

Closing this issue.

**Comment by jaredscheib** [comment]
In the meantime, what would be excellent is to warn the user if they are trying to use a `SingleStat` or `Line + Stat` per the above, so that they don't experience the same `0` result and panic that their cluster has crashed, or whatever other metrics they're watching have collapsed.

**Comment by nhaugo** [comment]
Fixed by #1881
