### ISSUE TITLE
Better Web GUI design

### ISSUE THREAD

**Issue by mcandre** [influxdata/chronograf#1496]
Alerting integrations, like Alerta, PagerDuty, Slack, etc., are configured in a strange way in Chronograf. Specifically, the user is required to select one of these integrations in order to begin creating Kapacitor rules, even though later on in the rule creation workflow, the user may choose to alert with raw TCP or HTTP calls, ignoring Slack integration configuration, for example.

Please:

* Unify these two sets of alerting methods
* Select all alerting method(s) either at the beginning, or at the end, of rule configuration.
* Don't require any Alerta/Slack/PagerDuty/etc. integration configuration if the user is just going to use raw TCP/HTTP methods anyway.
* Allow alert integrations to be reconfigured after rule creation, such as switching from Slack to PagerDuty.

**Comment by goller** [comment]
@mcandre thanks for writing in!  Yeah, that makes sense.  We've had discussions about how to handle that workflow better.  I'll attach the issues.

**Comment by nhaugo** [comment]
I think part of the UX problem is that when you add the kapacitor host it brings up the alert node config section, which has a big `Save` button. There is no indication that you don't need to click `Save` at this time. Maybe the alert node panel need an "Update" or "Add" button and the config screen should have a `Save` button.

![1496](https://cloud.githubusercontent.com/assets/1003269/26174816/d037cec0-3b0d-11e7-8eb8-ed2022992efb.gif)

**Comment by alexpaxton** [comment]
@nhaugo did some copy rewrites as per your suggestion - #1524 Not sure I'd call this a complete solution to the problem but should help a little
