### ISSUE TITLE
Please update chronograf package in your debian repo

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/chronograf#1501]
Hi,

Unless I'm wrong, your debian repo still provides chronograf 1.0:

https://repos.influxdata.com/debian/pool/stable/c/chronograf/

As now 1.3 is marked as stable, could you please update your repo so that we can install the whole TICK plateform via apt ?

Btw, other packages are not up to date too on debian repo (InfluxDB 1.2.2 vs 1.2.4, Telegraf 1.2 vs 1.3, etc)

Thanks,
Nicolas

**Comment by goller** [comment]
Hi @nsteinmetz, thanks for writing in!  We'll get that updated.

**Comment by goller** [comment]
Hi @nsteinmetz, we've updated the repos!  (ty @gunnaraasen !)

**Comment by nsteinmetz** [comment]
Thanks a lot @goller @gunnaraasen :)

**Comment by lafrech** [comment]
Hi.

I'm installing Influxdb + Chronograf on a Debian Stretch VM.

I followed the [installation procedure](https://docs.influxdata.com/influxdb/v1.7/introduction/installation/) for InfluxDB, adding the Influx repo.

I expected the same procedure for Chronograf but the [installation procedure](https://docs.influxdata.com/chronograf/v1.7/introduction/installation/) does not mention any repo. It relies on manual download + `dpkg -i`.

I found this issue while searching for a repo. So apparently, there is a repo. Not exactly as up to date as the main download page (chronograf 1.7.4 in the repo vs. 1.7.5 on the DL page) but oh well.

How come the repo is not advertized? Any reason not to use it?

Thanks.

**Comment by nsteinmetz** [comment]
@lafrech 

Weird, it works for me:

```shell
# apt-cache madison chronograf
chronograf |    1.7.4-1 | https://repos.influxdata.com/debian stretch/stable amd64 Packages
```

With:

```shell
# cat /etc/apt/sources.list.d/influxdata.list
deb https://repos.influxdata.com/debian stretch stable
```

**Comment by nsteinmetz** [comment]
Yep indeed, I saw the end of your comment after I commented ;-)

From what I remember, there was a period of time where only influx was available in a repo. Other products were manatory to downloand from the site and install via `dpkg -i`.
