### ISSUE TITLE
hipchat server (on-prem) not supported by Chronograf

### ISSUE THREAD

**Issue by brianbaker** [influxdata/chronograf#1506]
It appears that past decisions for #919, #1138 made it so that those that have to run HipChat on-prem cannot configure the HipChat url via the UI.  Instead, a manual curl to the Kapacitor HTTP API is required to configure HipChat.  Can the interface be updated to ask for something like the "HipChat Rooms API URL" (and any other logic to append .hipchat.com removed)?

**Comment by russorat** [comment]
- [ ] in the chrono ui, we should rename the field to be hipchat url
- [ ] we should not append anything to the url
