### ISSUE TITLE
Correlate value while hover a graf

### ISSUE THREAD

**Issue by olivierlambert** [influxdata/chronograf#1507]
A simple way to understand this is to check how it's done for Datadog dashboard:

![correlate](https://cloud.githubusercontent.com/assets/1241401/26253067/57188ff6-3cb2-11e7-961b-90a8e1004afc.png)

When you hover a graph, a vertical bar (in black) is displayed on all other graphs: this is helpful to "correlate" spikes for example.

**Comment by goller** [comment]
Hi there @olivierlambert, thanks for writing in!  We are actually working on this right now: https://github.com/influxdata/chronograf/issues/1480

I think it is not going to make it in this weeks release, but, it'll be in the very next release (2 weeks).

**Comment by olivierlambert** [comment]
Sorry for the duplicate! Tried to find it but missed it.

**Comment by goller** [comment]
No worries! The picture is very helpful though.
