### ISSUE TITLE
Spike: Evaluate frontend testing solutions

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1514]
- What are the available options?
- Write a few tests in each framework
- Evaluate the live code, see how they feel
- We can make a decision and move forward

@cryptoquick and @goller have made some progress already on integration testing, and @cryptoquick has volunteered to own this / break this issue down into smaller ones as necessary.

Here's an overview ticket for our testing spikes.

Connect:
#1517 
#1518 
#1519 
#1520 
#1521 

Feel free to mix and match tools, add more, or provide thoughts and comments on the respective tools.

**Comment by cryptoquick** [comment]
I may have duped this in #1522
