### ISSUE TITLE
Creating user for login into chronograf

### ISSUE THREAD

**Issue by bhuvangu** [influxdata/chronograf#1516]
Q1: How to create user to login into chronograf and remove no auth?
Explanation: Currently once i have installed chronograf,  i can access the chronograf ui without login.

Q2: Just for exploration i wanted to look in to chronograf sqllite db `/var/lib/chronograf/chronograf-v1.db`, but sqllite viewer ask for the sqlchipher, what it the sqlchipher key?

Q3: Chronograf give pre buit dashboard in form of json in `/usr/share/chronograf/canned`  , but how to use them?

I know these are not the bug or feature, But i could not find any documentation on above and also no forum/stackoverflow tag is mentioned , i even try browsing the code, but i lack GO skills as of now. 

Thanks in advance

**Comment by jensoleg** [comment]
check out the authentication documentation here: https://docs.influxdata.com/chronograf/v1.3/administration/security-best-practices/#chronograf-with-oauth-2-0-authentication

The influx forum can be reached at
https://community.influxdata.com/c/visualize

**Comment by bhuvangu** [comment]
Thanks

**Comment by goller** [comment]
Hi @bhuvangu, thanks for writing in! Just to add some more information

> Q2: Just for exploration i wanted to look in to chronograf sqllite db /var/lib/chronograf/chronograf-v1.db, but sqllite viewer ask for the sqlchipher, what it the sqlchipher key?

We are using the bolt database.  It is a key/value database.  Here is the repository for boltdb: https://github.com/boltdb/bolt



> Q3: Chronograf give pre buit dashboard in form of json in /usr/share/chronograf/canned , but how to use them?

Those pre-built dashboards will work if you are already sending data from telegraf to influxdb.  To see how to get telegraf and friends working here are the docs: https://docs.influxdata.com/chronograf/v1.3/introduction/getting-started/
