### ISSUE TITLE
[ux] Unreadable labels in cell legends 

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1523]
<img width="1050" alt="screenshot 2017-05-22 08 15 09" src="https://cloud.githubusercontent.com/assets/7452680/26315756/fa98011e-3ec6-11e7-997e-409be558f6be.png">

Queries with long measurement names and multiple `GROUP BY`s can easily generate giant unreadable labels. It would be ideal if users had some sort of control over how this happens. Many times the title of the chart, in the case above `Container Memory`, gets repeated in each of the entries along with a bunch of other non relevant information. In this case, as with many others I can think of, the lines should be labeled with a user defined tag value.

**Comment by jaredscheib** [comment]
Yeah I'd love to see this addressed as well

**Comment by jackzampolin** [comment]
Also see: https://community.influxdata.com/t/hard-to-find-metrics/1272

**Comment by jaredscheib** [comment]
Current proposal:
- Give users to option and ability to put a graph's legend in a dedicated "support" (linked) cell.
- Introduce the idea of linkedCells: ```linkedCells: {
  legend: <cell_id>,
  config: <cell_id>, (just an idea)
}```

**Comment by pauldix** [comment]
Filter by top or bottom N?
Hide/show measurement name?

Is the future linked cell thing an idea for putting the legend off to the side/bottom of the graph so that it's always visible? If the side thing then it would also be interesting later to be able to show summary stats about those series (e.g. first, last, min, max, mean).

**Comment by alexpaxton** [comment]
@pauldix I still got those designs we put together that encapsulates some of those features

**Comment by jaredscheib** [comment]
Filter by N sounds good.
And yes, hide/show measurement name.

And yes, the future linked cell is an idea for associating one cell with another, which would, yes, include putting a legend for one graph in another cell. To the side/bottom so that it could be always visible, yes. Good ideas @pauldix

**Comment by rfbonett** [comment]
Is this feature still a part of Chronograf? I can't find any documentation on modifying the legend, and don't see any options in the dashboard.

**Comment by jaredscheib** [comment]
cc @russorat

**Comment by optimuspaul** [comment]
is this a thing?  It's maddening that I can't control the legend text. Instead I get these stupid long labels and I can't read the values in the hover thingy.

**Comment by russorat** [comment]
@optimuspaul thanks for commenting! you can control the legend text using the `SELECT field AS "custom_name"` in the InfluxQL statements. If you have additional requirements or feature requests, please let us know in a new issue.

**Comment by stelikov** [comment]
Is there plan to move out first part of the label AKA SELECT mean("used") AS "test", mean("active") AS "test2" FROM "telegraf"."autogen"."mem"
it displays labels in form of mem. test & mem.test2, and i want to be just test and test2

**Comment by KhashayarDanesh** [comment]
Hi, there's a problem with this. 
If the measurement's name is too long, it makes the filter and sort buttons disappear from the other end of the display, 
also I could not find a way to alias the measurements using regular expressions. There's a tag for this measurement that includes a "process name" and I want to select a part of this tag value as the legend. 

<img width="1440" alt="Screen Shot 2020-09-28 at 15 28 47" src="https://user-images.githubusercontent.com/7428430/94438640-ac797180-019f-11eb-9d7a-f1f0b5963d85.png">
