### ISSUE TITLE
Show version in web interface

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1532]
It would be useful to be able to see the running version of Chronograf, and the other parts of the stack through the web interface.

I deploy new version very often in multiple environments and sometimes it would make troubleshooting a lot easier, not having to SSH to a server. And also when reporting bugs.

**Comment by 121watts** [comment]
We've now got the Chronograf version in the configuration tab.

![screen shot 2017-08-30 at 1 07 46 pm](https://user-images.githubusercontent.com/7582765/29892676-58c88892-8d84-11e7-9b65-7a28a4b1d763.png)

**Comment by nhaugo** [comment]
This does not display all connected components which was part of the initial issue.
