### ISSUE TITLE
Timeseries data missing in graph

### ISSUE THREAD

**Issue by jensoleg** [influxdata/chronograf#1533]
In this grouped graph the last points of the  "red"  timeseries is missing    
30 day view grouped

![skaermbillede 2017-05-23 kl 16 42 11](https://cloud.githubusercontent.com/assets/5655197/26359853/d7ed6576-3fd6-11e7-9e4e-05aae786a54e.png)

If i selected this timeseries only the points are shown
30 day view with 
![30dayselected](https://cloud.githubusercontent.com/assets/5655197/26358219/203c5148-3fd2-11e7-9da3-0056146767a0.png)

also when i switch to the 7 day view (grouped) the timeseries points is displayed 
7 day view grouped
![7day](https://cloud.githubusercontent.com/assets/5655197/26358224/22653db8-3fd2-11e7-9d6d-b4a21536d6ff.png)

The raw data of the this timeseries (using the influx CLI) has the points.

Any idea why this is happening ? I can't figure it out

**Comment by goller** [comment]
Hi @jensoleg , thanks for writing in.  This is a result of an InfluxDB configuration option.  We are going to add support for chunked responses eventually.  Here is the issue: https://github.com/influxdata/chronograf/issues/1233

Basically, the `max-row-limit` defaults to 10000 rows.  To workaround this behavior you'll need to change your InfluxDB configuration so `max-row-limit` is zero.  

Here is more explanation about the issue from the FAQ:

https://docs.influxdata.com/enterprise/v1.2/troubleshooting/frequently_asked_questions/#why-are-my-grafana-panels-returning-truncated-partial-data

**Comment by jensoleg** [comment]
Hi @goller Thanks for prompt response ! I will change configuration.
