### ISSUE TITLE
Addl query run between function and group by selection creates jarring UX

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#1534]
While building a kapacitor alert rule, a query is currently executed between selection of a function and selection of a group by time.

 `GROUP BY` is not set so the results look strange because the graph has a single data point.
![badrobot](https://cloud.githubusercontent.com/assets/1922921/26380857/9f3bcd66-3fe6-11e7-96a3-410fef8f416d.gif)

**Comment by nhaugo** [comment]
@timraymond will this be solved by #1471

**Comment by timraymond** [comment]
@nhaugo No, it will not. #1471 could be a tool to fix this, but it will not fix this issue by itself.

**Comment by 121watts** [comment]
GROUP BY time() is now automatically selected in the Rule builder.  Should resolve issue.
