### ISSUE TITLE
Error handling refactor

### ISSUE THREAD

**Issue by danielnelson** [influxdata/chronograf#1539]
**Steps:**
1. Go to admin page
2. Try to create database named `oh"no`

**Expected:**
Database is created, or error displayed indicating the database name is invalid.

**Actual:**
Page displays "Cannot communicate with server."

Server logs contain:
```
time="2017-05-24T12:17:57-07:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found BADSTRING, expected ; at line 1, char 22" component=server http_status =400 
time="2017-05-24T12:17:57-07:00" level=info msg="Response: Bad Request" code=400 component=server remote_addr="[::1]:59956" response_time=1.289548ms 
```

**Comment by goller** [comment]
@danielnelson here is one of the error sites in the code: https://github.com/influxdata/chronograf/blob/master/influx/databases.go#L25

We'll need to run the escaping algorithm used in Influxql here:

https://github.com/influxdata/influxdb/blob/master/influxql/parser.go#L2930-L2933

**Comment by nhaugo** [comment]
• Chose one common error reporting scheme
• Remove promise based errors
• Use error string when displaying errors. 

See also https://github.com/influxdata/chronograf/issues/1301

**Comment by jaredscheib** [comment]
This refactor will also need to address displaying a notification (or something in the UI) when a user tries to set a cell's source to one that doesn't work, and may send back a 400 or some other error. Currently this case is not handled as an error in the UI and provides a confusing UX, only displaying the error in the console.

**Comment by russorat** [comment]
we now show this which i think is ok

![image](https://user-images.githubusercontent.com/4805997/43012781-ef5dde9e-8bfb-11e8-9bb0-4b3ccfb81246.png)
