### ISSUE TITLE
Add further validation on server for Kapacitor alert requests

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1545]
There needs to be further validation performed by the server on Kapacitor alerts, ex. if the server receives a `tickscript`, it should include a `DBRP`.

This would follow-on from some work that has been done in https://github.com/influxdata/chronograf/pull/1535.

This work would support the implementation of TICK script editing in Chronograf: https://github.com/influxdata/chronograf/issues/789

**Comment by nhaugo** [comment]
@jaredscheib is this still valid?
