### ISSUE TITLE
File upload in Data Explorer

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1548]
Users should be able to upload files filled with line protocol and insert them into the database.

**Comment by jaredscheib** [comment]
Would this be as an add-on to https://github.com/influxdata/chronograf/issues/1328 ?

**Comment by jackzampolin** [comment]
@jaredscheib Thats would be good! Could be non-performant doing the rendering for large files tho. Just a `upload a file` button with some feedback. I was imagining a basic wrapper on top of [`influx -import`](https://docs.influxdata.com/influxdb/v1.2/tools/shell/#import-data-from-a-file-with-import).

**Comment by nhaugo** [comment]
In the data explorer a user should be able to select a file of line protocol and it should be added to the selected database.
Design needed for how to select a database and retention policy (can probably use the default rp if one is not selected)
Bonus points for drag and drop
- [ ] add a "upload" button to the existing add data overlay
- [ ] attempt to write data
- [ ] return errors from influx
- [ ] return with number of points written
- [ ] add support for batch size selection
- [ ] make consistent with the current user experience of the database
