### ISSUE TITLE
Template variables from queries should refresh on dashboard load

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1551]
When the dashboard is loaded the list should be populated. The results from queries should not be stored in chronograf.

Do not remove the ability to cache them since this might be an option later, but loading dynamically should be the default behavior.

**Comment by nhaugo** [comment]
This does not work in 1.4.3, possibly older versions too

**Comment by jkrukoff** [comment]
I'm seeing this bug in "Chronograf Version: 1.4.0-1", the version provided by my hosted influxcloud instance.

**Comment by russorat** [comment]
Looks good!
