### ISSUE TITLE
Add support for Auth0 as an OAuth provider

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1553]

**Comment by timraymond** [comment]
Is there any reason this can't be done with the Generic OAuth2 support? It seems that Auth0 is OpenID Connect compliant, which is what that was built for.

**Comment by dbender-platformatics** [comment]
I'm also trying to get auth0 working using the generic OAuth2 support. Wondering if anyone else has had any success. I'm getting "Unable to issue redirect for Auth 2.0 transaction" errors on the redirect.

**Comment by nhaugo** [comment]
@dbender-platformatics did you try using a nightly. The code for this was merged a few days ago. Additionally it should be in our next release if you would prefer to wait until then. 1.3.4 should be shipping in the near future.

**Comment by dbender-platformatics** [comment]
@nhaugo we made a similar patch (to #1645) here; will checkout 1.3.4 when it's out. Thanks!
