### ISSUE TITLE
Add support for organizations from auth0

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1554]
Sync @jademcgough and @lukevmorris to define this

**Comment by nhaugo** [comment]
@timraymond check @jademcgough about how we are handling organizations via auth0

**Comment by timraymond** [comment]
After some investigating yesterday, I believe that this is possible to do in Auth0 using an "organization" key that is set on users in their Auth0 profile. This can either be done via an Auth0 Rule automatically, or manually by an administrator.
