### ISSUE TITLE
Datasource should be persisted if created from the command line

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1555]
This may be easier accomplished via api calls @lukevmorris

**Comment by timraymond** [comment]
I think this might be introducing surprising behavior. If I start Chronograf with:

```
chronograf --influxdb-url=http://localhost:8086
```

I would first expect that to be idempotent, which is easy enough to solve by making sure hostnames and ports are unique within the source bucket. However what should the behavior be when it's started with a different URL? Should it also persist that? Which one should be the default?

I think it might make more sense to migrate to a command structure like:

```
chronograf add-source https://localhost:8086 --default --insecure-skip-verify --username=<username> --password=<password>
```

This would exit immediately but update the Bolt store. The server than could be started with `chronograf serve`.

**Comment by nhaugo** [comment]
Lets do a combo of these ideas. A flag --add-source that takes a json string or something else that contains:
the id
the name
the url
the user
the pass
whatever else is needed for a data source

This will try to create a new data source if it does not exist, if the id exists it does nothing with a successful return.

**Comment by jaredscheib** [comment]
RFC:

We'll pass a JSON string with InfluxDb and Kapacitor connection information, e.g.:
```
--new-source="{"influx":{"id":"0","name":"Influx 1","username":"user1","password":"pass1","url":"http://localhost:8086","metaUrl":"http://metaurl.com","default":true,"telegraf":"telegraf","links":{"self":"/chronograf/v1/sources/0","kapacitors":"/chronograf/v1/sources/0/kapacitors","proxy":"/chronograf/v1/sources/0/proxy","write":"/chronograf/v1/sources/0/write","queries":"/chronograf/v1/sources/0/queries","permissions":"/chronograf/v1/sources/0/permissions","users":"/chronograf/v1/sources/0/users","roles":"/chronograf/v1/sources/0/roles"}},"kapacitor":{"id":"0","name":"Kapa 1","url":"http://localhost:9092","active":true,"links":{"proxy":"/chronograf/v1/sources/0/kapacitors/0/proxy","self":"/chronograf/v1/sources/0/kapacitors/0","rules":"/chronograf/v1/sources/0/kapacitors/0/rules"}}}"
```

The above value is the stringified form of:
```
{
  "influx":{
    "id": "0",
    "name": "Influx 1",
    "username": "user1",
    "password": "pass1",
    "url": "http://localhost:8086",
    "metaUrl": "http://metaurl.com",
    "default": true,
    "telegraf": "telegraf",
    "links": {
      "self": "/chronograf/v1/sources/0",
      "kapacitors": "/chronograf/v1/sources/0/kapacitors",
      "proxy": "/chronograf/v1/sources/0/proxy",
      "write": "/chronograf/v1/sources/0/write",
      "queries": "/chronograf/v1/sources/0/queries",
      "permissions": "/chronograf/v1/sources/0/permissions",
      "users": "/chronograf/v1/sources/0/users",
      "roles": "/chronograf/v1/sources/0/roles"
    }
  },
  "kapacitor": {
    "id": "0",
    "name": "Kapa 1",
    "url": "http://localhost:9092",
    "active": true,
    "links": {
      "proxy": "/chronograf/v1/sources/0/kapacitors/0/proxy",
      "self": "/chronograf/v1/sources/0/kapacitors/0",
      "rules": "/chronograf/v1/sources/0/kapacitors/0/rules"
    }
  }
}
```

**Comment by nhaugo** [comment]
I would remove the "id" from both, and let the system decide, otherwise i could foresee sadness

**Comment by nhaugo** [comment]
Also, do we need the links or can the system figure those out.

**Comment by jaredscheib** [comment]
Sounds good.

I wondered the same, was going to ask @goller for comment.

And what of the idempotence question?

**Comment by jaredscheib** [comment]
Checked the docs again and looks like links and id are not Required.

Here's our current draft that we're working from:
```
{
  "influxdb":{
    "name": "Influx 1",
    "username": "user1",
    "password": "pass1",
    "url": "http://localhost:8086",
    "metaUrl": "http://metaurl.com",
    "default": true,
    "telegraf": "telegraf"
  },
  "kapacitor": {
    "name": "Kapa 1",
    "url": "http://localhost:9092",
    "active": true
  }
}
```

**Comment by jaredscheib** [comment]
As for the idempotence question, @timraymond brings up the complication of running behind ALBs, where IP may change, knowing whether a source is behind an ALB with a fixed address, etc.

**Comment by jaredscheib** [comment]
And @nhaugo, could any of these have default values, such that the user could skip setting them via the CLI?

**Comment by jaredscheib** [comment]
@goller recommended that instead of JSON, we use the built-in package http://godoc.org/github.com/jessevdk/go-flags and specifically implementing https://github.com/jessevdk/go-flags/blob/master/examples/main.go#L21, using something like a comma-delimited `map[string]string` data type of key:value pairs, comma-delimited.

**Comment by nhaugo** [comment]
"Should --new-source be idempotent by name, or by host?"

Name

**Comment by nhaugo** [comment]
Instead of json use the format --howdy one:two,three:four 
Then shell escape the password

**Comment by jaredscheib** [comment]
👍

**Comment by jaredscheib** [comment]
```
inf-name:"Influx 1",
inf-username:"user1",
inf-password:"pass1",
inf-url:"http://localhost:8086",
inf-metaUrl:"http://metaurl.com",
inf-insecureSkipVerify:false,
inf-default:true,
inf-telegraf:"telegraf"
kap-name:"Kapa 1",
kap-url:"http://localhost:9092",
kap-active:true
```
-->
`--new-source=inf-name:"Influx 1",inf-username:"user1",inf-password:"pass1",inf-url:"http://localhost:8086",inf-metaUrl:"http://metaurl.com",inf-insecureSkipVerify:false,inf-default:true,inf-telegraf:"telegraf"kap-name:"Kapa 1",kap-url:"http://localhost:9092",kap-active:true`
