### ISSUE TITLE
Fix logout when not connected to a source

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1558]
Clicking the user menu should display a logout option, which is not.

**Comment by jaredscheib** [comment]
Do you want the `Logout` submenu to simply not working, if source is not connected? Or what should be the UX?

**Comment by nhaugo** [comment]
It should log you out of oauth, same as a session timeout.

**Comment by jaredscheib** [comment]
But of course.

**Comment by nhaugo** [comment]
This does not work for me, steps:
- connect to a source (probably localhost for ease)
- kill influxdb
- reload page
- the logout option does not show

**Comment by jaredscheib** [comment]
I don't have that experience... it shows for me when I follow those repro steps.

**Comment by jaredscheib** [comment]
Good catch. That's actually the case for all menu NavHeaders -- none display under your repro steps. Let's make a new issue for it. I don't think it's related to this issue or #1564.
