### ISSUE TITLE
Ensure that the H in GitHub is capitalized as provided by server

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1568]
Capitalization is being incorrectly done here by only capitalizing the first letter, whereas GitHub and other possible providers may have non-standard capitalization: https://github.com/influxdata/chronograf/blob/master/server/mux.go#L225

**Comment by russorat** [comment]
i don't think this link is relevant anymore.

**Comment by jaredscheib** [comment]
At the very least, our login page should say GitHub, not `Github`
