### ISSUE TITLE
Uncaught exception in AutoRefresh allows "Save" of invalid query

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1569]
1. Construct a query via the Query Builder.
2. Erase everything except whatever would yield an invalid query (ex. `SELECT * FROM 'telegraf'`).
3. Hit 'Enter'
4. See error in the console from AutoRefresh
  1. If https://github.com/influxdata/chronograf/pull/1561 is merged, note also that the Save button remains enabled due to that logic failure.

**Comment by russorat** [comment]
the refresh interval no longer saves the query
