### ISSUE TITLE
Data explorer crashes

### ISSUE THREAD

**Issue by ChristianTrolleMikkelsen** [influxdata/chronograf#1576]
Hi

Data explore stopped working suddenly in chrome.
Whenever i click the data explore the error on the attachmen occours and every click on any other menu item causes the error again.
Tried restarting chronograf but the error persists the second i click data explore, the rest of the menu items are ok.
The last thing i did while it was working was closing ALL open query tabs and since then it have become inaccessible.
I closed them since the data explore had started freezing up on me.

![chrono chrome explore crash](https://cloud.githubusercontent.com/assets/2988027/26675293/af6061fa-46c3-11e7-8bfc-465b7d5bbbda.PNG)

**Comment by jaredscheib** [comment]
Hi @ChristianTrolleMikkelsen, thanks for writing. Could you tell us which version of Chronograf you're using? And have you upgraded recently?

Could you send a screenshot of your console that shows the first error printed out when this problem starts?

This could be related to local storage getting corrupted. We are clearing local storage for Chronograf between version upgrades to try to allay this issue.

If you're ok with losing your current queries in Data Explorer, you could try running `localStorage.setItem('state', null)` in your Chrome console and see if you continue to have issues. This would reset your local storage for Chronograf, and so you might be able to discover what seems to be causing the issue.

**Comment by jademcgough** [comment]
Not sure how helpful this is, but I remember @lukevmorris fixing a bug ~2 months ago where we were seeing the same error (ended up being a bug in the query parser). I'm fairly sure the data explorer is choking on a query that isn't being parsed correctly. Kind of surprised that clearing localstorage didn't resolve this though :\

**Comment by ChristianTrolleMikkelsen** [comment]
Update: I tried opening the Data Explore in a Chrome "incognito" window, and this seemed to work so im note sure why localStorage.setItem('state', null) did not work.
On my standard "non incognito" chrome it still fails as described, even though i call  localStorage.setItem('state', null).
Any ideas?

**Comment by geekbrother** [comment]
I have the same issue. It hangs in Safari too. When I open it in Chrome incognito, it works. Seems to be local storage issue.

**Comment by roiamitay** [comment]
Same here, nothing helps except using incognito.

**Comment by JamisonWhite** [comment]
@roiamitay This stinks, but it worked for me. In Chrome open a new window with Chronograf. Then open the console (ctrl-shift-j). Open the Application tab. Clear Local Storage, Session Storage, Cookies, and Cache Storage. Re-open Chrome and you're good.

**Comment by jaredscheib** [comment]
What @JamisonWhite wrote above should work. The temporary fix is simply to reset your local storage. Maybe the console command is different in your particular browser for some reason.

**Comment by 121watts** [comment]
I'm working on a fix for the specific issue that caused the OP's crash

**Comment by 121watts** [comment]
PR merged.  Closing :)
