### ISSUE TITLE
User menu item covers others on short screen

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1579]
When Chronograf is used in a short window/screen, the User menu item can cover up other menu items and also make them inaccessible. This happens often when using dev tools.
<img width="58" alt="screen shot 2017-06-01 at 2 33 52 pm" src="https://cloud.githubusercontent.com/assets/6403018/26701865/81d7efaa-46d7-11e7-959a-a8a37474ae8c.png">
<img width="58" alt="screen shot 2017-06-01 at 2 33 58 pm" src="https://cloud.githubusercontent.com/assets/6403018/26701864/81c9f85a-46d7-11e7-9a64-a22cf938679e.png">

**Comment by nhaugo** [comment]
This was fixed when we moved the user menu
