### ISSUE TITLE
Request for "like/not like" expressions when creating rules

### ISSUE THREAD

**Issue by ChristianTrolleMikkelsen** [influxdata/chronograf#1591]
Hi we have migrated a set of rules from chronograf 1.0
They used a lot of expressions like: ("brand" !~ /Test$/) AND ("server" !~ /^PC/)
The rules still work but the create/edit rule interface cant interpret these expressions.
We would love that they did :)

**Comment by nhaugo** [comment]
Do you mean kapacitor rules or influxdb queries

**Comment by russorat** [comment]
@alexpaxton can we incorporate this into the updated query builder?
