### ISSUE TITLE
Upper and Lower Bounds Plotting

### ISSUE THREAD

**Issue by xylene1980** [influxdata/chronograf#1602]
Hi All,

The question may be trivial, but i would like to know how to plot upper and lower bounds in Chronograf?

**Comment by alexpaxton** [comment]
**Design Notes**
- This is a "maximal" concept I put together to help future-proof the design
- Color Palette & Legend Formatting are nice to haves, will probably implement another time
- Removed `Visualization Type` selector from `OverlayControls` in favor of a tab selector
- Tab selector swaps out the area currently occupied by `QueryMaker`
- **Display Options** tab will contain the visualization type options as well as axes controls
  - The visualization "tiles" will feature icons or other simple graphics to visually communicate graph type
- In the future we can fit more things in here and/or add more sections as needed

![screen shot 2017-06-28 at 1 36 22 pm](https://user-images.githubusercontent.com/2433762/27663613-102bb890-5c18-11e7-8a12-d852fec1783f.png)
![screen shot 2017-06-28 at 3 30 53 pm](https://user-images.githubusercontent.com/2433762/27663615-13ed6564-5c18-11e7-8f1f-c86e2f7298dc.png)

**More Notes**
- I'd like to introduce a feature in which a user can type "inherit" (or "auto" or whatever makes the most sense) to have Chronograf decide the value of a field
  - I have this in the mockup for `Axis Label` but it might make sense to use it on Min/Max values as well
- The `Units` dropdown should probably be "None" by default. Not sure what options we should provide in here
  - Perhaps in the future we can modify this so users can specify their own scale

**Comment by 121watts** [comment]
This story is "done".  Needs some style love and a backend to support yRanges being saved to a cell via the PUT to `/dashboards/:dashboardID/cells/:cellID `
