### ISSUE TITLE
Bug with data value mouse hover on graph

### ISSUE THREAD

**Issue by agirot** [influxdata/chronograf#1603]
Hi,
When you have many data in single graph you can't see all your lines. It's worse in low resolution.

Maybe you can display that on two columns or more ?

![issue](https://user-images.githubusercontent.com/5726728/27071036-a3304a60-501b-11e7-848a-6f94b06d41e9.png)

**Comment by jaredscheib** [comment]
Thanks, @agirot. Could you clarify: do you mean that you can't see all of your data on the graph, or in the legend? If the legend, this seems related to https://github.com/influxdata/chronograf/issues/1523 and possibly worth tackling both at once.

**Comment by agirot** [comment]
Yeah in the legend. It's look like the same issue yes. I close my issue ?

**Comment by nhaugo** [comment]
Fixed by new legend
