### ISSUE TITLE
Data Explorer query configs multiplying

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1606]
Not sure what the repro steps are, though I seem to recall someone saying they noticed it happening when you switch branches (in development). Not sure if it's only limited to dev. At any rate, when this happens, Chronograf starts slowing down.
<img width="1440" alt="screen shot 2017-06-12 at 4 01 11 pm" src="https://user-images.githubusercontent.com/6403018/27112077-6955137c-5069-11e7-8bef-e9ef6408c183.png">

**Comment by nhaugo** [comment]
Cannot reproduce

**Comment by jaredscheib** [comment]
Solved by #1777, I believe.
