### ISSUE TITLE
multiple event handlers in an alert

### ISSUE THREAD

**Issue by petercelentano** [influxdata/chronograf#1610]
Hi all,

Quick question: does chronograf support sending alerts to multiple event handlers (sending an alert to both email and slack event handlers simultaneously).  Kapacitor supports this, but it seems there is no option in the UI for selecting multiple event handlers.  If I import an alert containing multiple event handlers and then attempt to edit and of the handlers, only the handler which was edited is saved (and the other is deleted).  I'm running chronograf v1 and kapacitor 1.2 with influxDB 1.2.

Thank you!

**Comment by nhaugo** [comment]
That is not currently support but should be doable.

**Comment by nhaugo** [comment]
Store the value of all tabs, one value of each output. Add an enabled toggle.

**Comment by alexpaxton** [comment]
![kapacitor-config-ideation](https://user-images.githubusercontent.com/2433762/30837483-1d592e60-a21a-11e7-9c6f-537fa8688a3d.jpg)

Mockup of tentative design changes

**Comment by petercelentano** [comment]
This looks cool, but will this handle multiple alert types (email and slack) in addition to multiple versions of the same alert type (multiple slack configs, as shown in the mockup)?

**Comment by alexpaxton** [comment]
@petercelentano yes we are planning to support that. Should be easy & intuitive to add multiple alerts (such as slack) to a rule
