### ISSUE TITLE
Graph x-axis doesn't re-scale with query changes

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1611]
The graph's x-axis ought to adjust to changes in WHERE time, but it doesn't.

That said, if it's saved, the dashboard reflects the correct x-axis, so this problem appears isolated to the CEO.

<img width="1440" alt="screen shot 2017-06-14 at 11 41 41 am" src="https://user-images.githubusercontent.com/6403018/27148796-72ee609a-50f6-11e7-8447-f11fd5181bd5.png">

**Comment by lukevmorris** [comment]
Pls to verify that dataset is actually `5m` long
