### ISSUE TITLE
no pre- canned dashboards on ubuntu server 16.04.2

### ISSUE THREAD

**Issue by PitPaul** [influxdata/chronograf#1614]
Custom dasboards, are visible - predefined are not.
Same config on onther ubuntu's (dsktop's) works
Versions 
chronograf_1.3.2.1_amd64.deb
telegraf_1.3.2-1_amd64.deb

**Comment by cryptoquick** [comment]
I just set up the latest TICK stack on Ubuntu Server LTS 16.04.2. I see a pre-canned dashboard populate in the host list, and no other issues. @PitPaul -- Is this still an issue, and can you describe what led to the issue in greater detail?

Versions:

```
influxdb_1.3.1_amd64.deb
telegraf_1.3.5-1_amd64.deb
kapacitor_1.3.1_amd64.deb
chronograf_1.3.5.0_amd64.deb
```

**Comment by 121watts** [comment]
If this is still an issue hit us up!  Closing :smile:
