### ISSUE TITLE
Please to investigate GROUP BY time on new auto-function selection

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#1617]
@jaredscheib asked me to log this from a discussion that came out of a demo yesterday. In the demo, an aggregation function is automatically selected with an auto-selected group by time based on the time range. On short time ranges (like if they're only looking at the last five minutes), they could have very short group by times, which could result in strange graphs.

For instance, if you have one data point every 10 seconds, but have a group by time of 5s, you'll have a bunch of zeroed out points. Adding a `fill(previous)` to the query should handle things. Might already be doing this, so please to investigate.

**Comment by timraymond** [comment]
@pauldix Is this only an issue where the group by time is less than the collection rate? Would it suffice to substitute the collection rate in that case? In your example, if the group by time worked out to 5s, we'd just replace that with 10s so it wouldn't fall below the minimum.

**Comment by pauldix** [comment]
@timraymond that's right it's only a problem when the group by time is less than the collection rate. However, you won't know the collection rate of any given time series so the fill would probably be a better option.

**Comment by nhaugo** [comment]
Fill was added along with better group by times, closing.
