### ISSUE TITLE
RFC: User should be able to determine their Chronograf version number via the UI

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1624]

**Comment by timraymond** [comment]
Yes, absolutely this. Also, it should be possible to determine whether a new version is available from within Chronograf.

**Comment by timraymond** [comment]
Dupe of #1532

**Comment by timraymond** [comment]
@jaredscheib Can this be closed given #1662 ?

**Comment by jaredscheib** [comment]
Yep!
