### ISSUE TITLE
RFC: Add ability to put use any page in the app as a widget

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1629]
Possibly create HOC to be able to widgetize any app/page. Along the lines of how AlertsApp was included in the Status Page.

This would also have bearing on fixtures used for Status Page, which tack on an `isWidget` property that is interpreted by LayoutRenderer.

**Comment by timraymond** [comment]
I think I would wait until we do this a few times and it becomes a repetitive pain point.
