### ISSUE TITLE
Misc Status Page UI improvements

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1630]
- [ ] rethink design for "Last 30 Days" text on Status Page to feel like a separate concept, something other than plain text
- [x] fix Alerts headers in Recent Alerts; make Alerts History an unscrollable page (only scroll subcomponent) -- consider using DIV table to extend usability of Recent Alerts & Alert History
- [x] add visibility into Version of Chronograf (subheader to `Welcome to Chronograf`?)
- [ ] possibly add an upgrade link/indication (to Getting Started?)
- [ ] some kind of initial empty state for the bar graph that encourages users to set up alerts and maybe shows them what it could look like (use an image that's clearly explained?)
- [ ] make Cubeoctohedron glow when Status Page is clicked & live, like other side nav items
- [ ] ensure width on alerts history columns where appropriate:
<img width="240" alt="screen shot 2017-07-05 at 2 51 46 pm" src="https://user-images.githubusercontent.com/6403018/27886579-8e7715e0-6191-11e7-9482-bd70cf2f9590.png">

**Comment by alexpaxton** [comment]
@jaredscheib tackled the second item via #1644  - is the first item still relevant after the previous work we did on the recent alerts cell?

**Comment by jaredscheib** [comment]
@alexpaxton it is still relevant – as I understand it, per our discussion you were interested in making `Last 30 Days` visually unique, rather than plaintext
