### ISSUE TITLE
CEO text strangely capitalizing on window width increase

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1631]
See change below, including at least:
- `group by time` --> `GROUP BY TIME`
- `Databases` --> `DATABASES`
- `Measurements` --> `MEASUREMENTS`
- `Fields` --> `FIELDS`

![screen shot 2017-06-15 at 4 44 25 pm](https://user-images.githubusercontent.com/6403018/27249394-6dbd1b46-52c9-11e7-8802-e71e9313dd99.png)
![screen shot 2017-06-15 at 4 44 17 pm](https://user-images.githubusercontent.com/6403018/27249393-6db949ee-52c9-11e7-9e1a-f0baa95ac3f1.png)

**Comment by alexpaxton** [comment]
I actually did that on purpose so that the headings would more closely resemble the page headers. Alas the page headers are no longer all caps, so the resemblance has been rendered nonexistant
