### ISSUE TITLE
Dashboards of apps always have another order

### ISSUE THREAD

**Issue by luca-moser** [influxdata/chronograf#1634]
Opening a host dashboard always shuffles the cells around, the order is never kept. However, custom dashboards do not have this problem.

* Chrome ` 58.0.3029.110`
* Chronograf `1.3.2.1-alpine` docker image

Opening 1:
![image](https://user-images.githubusercontent.com/1385611/27274283-00cb4402-54d3-11e7-9830-faaa5e34f9cd.png)

Opening 2:
![image](https://user-images.githubusercontent.com/1385611/27274306-0da9d72e-54d3-11e7-9d8f-6c4b9d1b0ebd.png)

Opening 3:
![image](https://user-images.githubusercontent.com/1385611/27274331-1c9c6f26-54d3-11e7-996a-aee83211948f.png)

**Comment by ghmax** [comment]
This behaviour still occures...
Browser: Firefox 62.0.2 (64-Bit)
Chronograf 1.6.2
