### ISSUE TITLE
Don't keep time range when switching between custom dashboards

### ISSUE THREAD

**Issue by luca-moser** [influxdata/chronograf#1636]
Chronograf `1.3.2.1-alpine` docker image:
If you use a time range of 7 days on a custom dashboard where data is usually in 3 hour intervals, switching then to a dashboard with data of 10s intervals makes the browser cry for mercy. Store the last selected time range of a dashboard per dashboard.

**Comment by nhaugo** [comment]
Hi @luca-moser we recently added a auto created group by time that should fix these issues. This is not retroactively applied to queries. If you create the query it should add this in for you. Let me know if that fixes your issue.
