### ISSUE TITLE
Can not apply function in Alert Rules

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1638]
When trying to apply a function to a value in the Alert rules, the box with functions does not appear.

Im running chronograf version 1.3.2.1 and its the same on Safari and Chrome.

![screen shot 2017-06-19 at 12 39 01](https://user-images.githubusercontent.com/16920380/27281490-628fe210-54ec-11e7-908a-c7968802216e.png)

**Comment by timraymond** [comment]
@alexpaxton Was this what you were working on fixing late last week? @jaredscheib and I ran into it as well last Thursday.

**Comment by hasselrot** [comment]
Same problem in 1.3.3.0.

**Comment by jaredscheib** [comment]
Thanks for reporting, @hasselrot. This appears to be a dupe of https://github.com/influxdata/chronograf/issues/1618.

**Comment by jackzampolin** [comment]
I've been running into this too!
