### ISSUE TITLE
Error loading Feeds when basepath and prefix-routes are used

### ISSUE THREAD

**Issue by nesasit** [influxdata/chronograf#1640]
I am using the following additional command line options with my chronograf install:

--basepath /chronograf --prefix-routes

The page mainly works as it should, but I a pop-up that reads: Failed to fetch News Feed. JSON Feed at 'https://www.influxdata.com/feed/json' returned 404 (Not Found).

There is an 'x' to close out the pop-up but it comes back on next reload.

In my access logs I get a log entry that the browser is trying to load this file: /chronografhttps://www.influxdata.com/feed/json

The URL for the feed is getting the prefix but it should not be.

I am using version 1.3.3.0-1 of chronograf installed from the influxdata RPM repository on CentOS 7.3

<img width="1616" alt="screen shot 2017-06-20 at 10 37 55 am" src="https://user-images.githubusercontent.com/19539381/27342445-d27a4f2a-55a5-11e7-8bbf-4475fa3cd287.png">

**Comment by jaredscheib** [comment]
Ah, great catch, @nesasit! We'll get this fixed ASAP. Thank you.

**Comment by jaredscheib** [comment]
@nesasit The fix has been merged, as you can see. We're working on a hot fix release.

**Comment by nhaugo** [comment]
Fixed, shipping with 1.3.3.1
