### ISSUE TITLE
In Host view, vertical marker in graphs is off

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#165]
![screen shot 2016-10-03 at 4 09 35 pm](https://cloud.githubusercontent.com/assets/2433762/19057344/f31ee1a8-8983-11e6-94bf-8e945538c7c3.png)

Looks fine in the Data Explorer
Tried a few top of the head fixes but didn't get anywhere

**Comment by nhaugo** [comment]
Cannot reproduce
