### ISSUE TITLE
Add the ability to embed Chronograf's graphs within other pages

### ISSUE THREAD

**Issue by rizadh** [influxdata/chronograf#1654]
Chronograf v1 allowed a user to copy HTML to embed the current cell (i.e. a graph or stat) into another webpage.

This would be a handy feature to not only bring back but also build upon. Ideally, the embedded frame should contain the target cell, the `Template Variables` toolbar, the `Time Range` selector and the `AutoRefresh` rate selector. Normal Chronograf zooming behavior (click-and-drag to zoom, double-click to reset) should also be implemented.

Editing the cell query or name should probably be disabled. It should essentially be a read-only view.

Adding parameters to the URL to allow a default time range and template variable choices would take this one step further. That way specific "snapshots" of a graph could be stored as a link, for easy reference.

**Comment by jademcgough** [comment]
Hi Rizadh!

We've talked about this a bit internally, and I think it'd be great to have. It's on our roadmap, though we have some other big features that will probably come before this.

Thanks for making this issue - it's helpful for us to know the features that chronograf users want, and I really like your ideas around the implementation (having an embedded template variables toolbar would be awesome).

**Comment by hanssens** [comment]
+1 👍  from me; this would really make it a killer feature for quickly integrating dashboards in a custom web application. Especially @rizadh's comment about a read-only view is definitely good enough. Keep it simple, at first...

This is the part where tools like Power BI (Embedded) and Tableau fall short: embedding.

**Comment by aharonamir** [comment]
This would certainly be a major change, right now i am using grafana instead of choronograf only because grafana has a sharing/embedding (link/snapshot) option.

**Comment by lmangani** [comment]
:+1: @jademcgough if there's anything the community can help with to make this possible, please do advice. Would be particularly efficient if the timerange or other parameters could be optionally passed via the embedding URL and easily controllable by the embedding application.

**Comment by cryptoquick** [comment]
It's easy enough to embed a link to a dashboard in presentation mode, using the `&present=true` query param. We'll have to add setting autorefresh and timerange as params, but Template Variables can also be set using a query string param as well.

Let's provide some definition to this feature.

## Cell Embed

### Sub-Features

- [ ] Dashboard cell view page by cell id (`CellPage` container component)
- [ ] Disable cell edit controls
- [ ] Cell share URL menu item from Dashboard
- [x] Query URL param
- [x] Template variable URL param selection
- [ ] Autorefresh URL param
- [ ] Time Range URL param
- [ ] Time Range snapshot

Issue stakeholders, let me know if I've captured everything. Good feature request.

**Comment by airhorns** [comment]
Have any of the interim features like autorefresh and timerange query params landed perhaps? Would love to be able to use Chronograf embeds in other parts of an internal product!

**Comment by russorat** [comment]
@airhorns we have completed #2934 for setting variables and time ranges in the url. The other items have not been addressed.

**Comment by techedemic** [comment]
For what it's worth, I can +1 this request! Would be a game changer for me/us!

**Comment by russorat** [comment]
@techedemic thanks! can you let me know what your use case for this is? Where would you like to embed chronograf graphs?

**Comment by techedemic** [comment]
@russorat We have a fairly complex system built over the years that integrates into a lot of other tools. One of the key areas for our tool is obviously the graphing of our time based values.
Up to now, we've been using RRD. We're migrating everything over to influxdb as I type this, but we still have to develop the API's, etc. to pull the data back to our (existing) front-end. 

If it could be as simple as creating embed-able graph templates in chronograf and then place them in our system where we currently have graphs based on other 3rd party tools (e.g. FusionCharts) then it will save a lot of time.

**Comment by brian15co** [comment]
@russorat We have a very similar use case to @techedemic. Using Chronograf as an embeddeble "engine" of sorts would be awesome

**Comment by bliet** [comment]
I'm also interested to embed Charts in PowerBI and Cognos Analytics.
Both have the possibility to embed Java Script Extensions or just iframes.

**Comment by brabidou** [comment]
This would be great!

**Comment by nemani** [comment]
Is this still not possible?

**Comment by alfresanc** [comment]
Not yet?
