### ISSUE TITLE
chronograf alert history error，thanks

### ISSUE THREAD

**Issue by zhangwenliang012** [influxdata/chronograf#1657]
[chronograf-v1-a00a7255-ec5e-45a2-a467-e86b65ddcada:influxdb_out4] 2017/06/23 11:50:19 E! failed to write points to InfluxDB: partial write: field type conflict: input field "value" on measurement "alerts" is type integer, already exists as type float dropped=2

[chronograf-v1-b9c10b07-6022-4125-aced-b6aafeda5488:eval2] 2017/06/23 15:10:50 E! missing value: "used_percent"
[chronograf-v1-21a84139-c1eb-4068-b666-d68a89a87d14:eval2] 2017/06/23 15:10:50 E! missing value: "usage_iowait"
[chronograf-v1-8717a35b-c442-4797-972c-b51283e54d9e:eval2] 2017/06/23 15:10:50 E! missing value: "used_percent"
[chronograf-v1-b9c10b07-6022-4125-aced-b6aafeda5488:eval2] 2017/06/23 15:10:50 E! missing value: "used_percent"
[chronograf-v1-5f44c4b1-ae38-4560-9492-6bcae399a9b7:eval2] 2017/06/23 15:10:50 E! missing value: "available_percent"
[chronograf-v1-21a84139-c1eb-4068-b666-d68a89a87d14:eval2] 2017/06/23 15:10:50 E! missing value: "usage_iowait"
[chronograf-v1-24a70137-bc3b-42f0-bb5d-622be970935a:eval2] 2017/06/23 15:10:50 E! missing value: "bytes_sent"
[chronograf-v1-8717a35b-c442-4797-972c-b51283e54d9e:eval2] 2017/06/23 15:10:50 E! missing value: "used_percent"
[chronograf-v1-b9c10b07-6022-4125-aced-b6aafeda5488:eval2] 2017/06/23 15:10:50 E! missing value: "used_percent"
[chronograf-v1-3a3f39f6-c587-4474-a321-ac7e7bad1cb7:eval2] 2017/06/23 15:10:50 E! missing value: "bytes_recv"
[chronograf-v1-5f44c4b1-ae38-4560-9492-6bcae399a9b7:eval2] 2017/06/23 15:10:50 E! missing value: "available_percent"
[chronograf-v1-1eca6c20-f256-4101-9c07-703ab86fc6e2:eval2] 2017/06/23 15:10:50 E! missing value: "load15"

> show field keys
name: alerts
fieldKey      fieldType
--------      ---------
current.value integer
duration      integer
message       string
past.value    integer
value         float

influxdb-1.2.4-1.x86_64
chronograf-1.3.3.4-1.x86_64
kapacitor-1.3.1-1.x86_64
telegraf-1.3.2-1.x86_64

**Comment by zhangwenliang012** [comment]
rules：
SELECT "n_containers_stopped" FROM "telegraf"."autogen"."docker" WHERE time > now() - 15m GROUP BY "host"
threshold   n_containers_stoped is greater than 0

**Comment by nhaugo** [comment]
Todo, check if kapacitor is forcing the values to be floats.

**Comment by jaredscheib** [comment]
Thanks for reporting this, @zhangwenliang012.

**Comment by nhaugo** [comment]
Kapacitor writes the fields through as they exist on the database. The 'value' field in alerts can come from different data types. One fix would be to have the templated tick scripts coerce the type to a float using `lamda: float("field")`

**Comment by cygnushan** [comment]
@zhangwenliang012 , have you solve this problem yet? Could you tell me how to do it? Thanks a lot!
