### ISSUE TITLE
Set telegraf database name with different retention policy

### ISSUE THREAD

**Issue by zygis** [influxdata/chronograf#1658]
My retention policy is named "90D"
Tried to set telegraf database names "telegraf.90D", "telegraf"."90D", telegraf.90D but no luck. Getting this kind of error:
`{results: [{statement_id: 0, error: "database not found: "telegraf.90D""}]}`

Is it possible set custom retention policy?

**Comment by nhaugo** [comment]
Hi @zygis,
Would you mind taking this to https://community.influxdata.com We try to reserve github for bug reports and feature requests.

You should be able to do what you want, I just want to make sure the info makes it into our knowledge base.

Thanks
