### ISSUE TITLE
Windows hosts marked as "down"

### ISSUE THREAD

**Issue by hasselrot** [influxdata/chronograf#1659]
It looks like all my Windows hosts are marked red for down in the host dashboard.
All the metrics work.

![c18b48384a6386c1b294ccdd5552b19eb32ab7e6](https://user-images.githubusercontent.com/16920380/27519390-5ca03fe2-59f3-11e7-9d1f-1f8acf449429.png)

From:
https://community.influxdata.com/t/windows-host-red-status/1353

**Comment by luca-moser** [comment]
dup https://github.com/influxdata/chronograf/issues/1633

**Comment by nhaugo** [comment]
Closing dupe
