### ISSUE TITLE
Request: Sync vertical markers on all graphs in Host dash

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#166]
![screen shot 2016-10-03 at 4 11 34 pm](https://cloud.githubusercontent.com/assets/2433762/19057364/2517672a-8984-11e6-9ab2-551c467a6f0c.png)

Since they all have the same time range, would be sweet to have vertical markers appear on all graphs at the same time, also showing legends.

Stretch goal: sync dygraphs interaction models as well, so zooming on a graph zooms on all graphs with the same window, zooming out affects all graphs as well

**Comment by agrrh** [comment]
+1, great feature, just as it is at DigitalOcean "Graphs" page. Would be super cool.

**Comment by lukevmorris** [comment]
@alexpaxton check it

**Comment by 121watts** [comment]
@alexpaxton we currently sync the vertical markers but don't sync zoom.

**Comment by cryptoquick** [comment]
it's not that we can't sync zoom, I think we just omitted that functionality due to performance reasons.
