### ISSUE TITLE
Access Chronograf with just a Read Only user

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1661]
See: https://community.influxdata.com/t/how-to-setup-chronograf-to-grant-access-to-a-read-only-user-for-influxdb/1410

**Comment by jaredscheib** [comment]
@nhaugo Does this map directly to the `Viewer` role that's about to drop in post-RC 1.4.0?

**Comment by nhaugo** [comment]
@jaredscheib yes, closing
