### ISSUE TITLE
As a user I can see TICK scripts from kapacitor

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1663]

**Comment by alexpaxton** [comment]
[kapacitor-sketch.pdf](https://github.com/influxdata/chronograf/files/1112894/kapacitor-sketch.pdf)

Thinking about using the same `Builder / Editor` paradigm we had in with queries. User would have to choose one or the other when they create one. Builder rules have the "View TICKscript" button that shows a read-only modal w/ the script in it (should the user want to copy and paste it)

Also tentatively using the diamond / circle icons to denote the two types
