### ISSUE TITLE
Login with auth0 fails with invalid URL

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1666]
When I have ENV vars set for `AUTH0_CLIENT_DOMAIN`, `AUTH0_CLIENT_ID`, and `AUTH0_CLIENT_SECRET` and attempt to login to Chronograf with the `Login with auth0` button, the login fails as I'm taken to an invalid URL: `https://authorize/?access_type=online&client_id=...`

**Comment by jademcgough** [comment]
You won't have that error if you provide a `--public-url`

**Comment by timraymond** [comment]
The `AUTH0_CLIENT_DOMAIN` ENV is incorrect. It should be `AUTH0_DOMAIN`

**Comment by jaredscheib** [comment]
Sounds good. Thanks!

**Comment by jademcgough** [comment]
closing this, ENV vars are now consistent

**Comment by danlg** [comment]
@lukevmorris @timraymond
I'm having this exact issue where the splash screen prompts "login with Auth0" but when clicking on the button, it redirects to https://authorize/?access_type=online&client_id=..

I find https://authorize URL bizarre. When I roll over the button, the link is "http://swarm-dev-external-xxxx.eu-west-2.elb.amazonaws.com:8888/oauth/auth0/login" which looks correct.

I want to enable auth0 authentication, not disable it so the previous solutions will not work. The Auth0 set up on Auth0 side looks OK.

the code to run it is:

docker service create --name chrono  \
    --detach=false \
    -e "INFLUXDB_URL=https://mydb:8086" \
    -e "INFLUXDB_USERNAME=xxx" \
    -e "INFLUXDB_PASSWORD=xxx" \
    -e "AUTH0_DOMAIN=xxx.eu.auth0.com" \
    -e "AUTH0_CLIENT_ID=clientid" \
    -e "AUTH0_CLIENT_SECRET=secret" \
    -e "PUBLIC_URL=http://swarm-dev-external-xxxx.eu-west-2.elb.amazonaws.com:8888" \
    -e "PORT=8888" \
    -p 8888:8888 chronograf:latest
Please reopen the issue ;-)
Any ideas on solving it ? Tx

**Comment by danlg** [comment]
The issue was due to a bad documentation: AUTH0_DOMAIN variable is NOT xxx.eu.auth0.com provided by Auth0 but instead **https://**xxx.eu.auth0.com  in front of it to be a URL.

**Comment by timraymond** [comment]
@danlg The documentation [here](https://docs.influxdata.com/chronograf/v1.3/administration/configuration/#auth0-domain) includes the scheme. "Domain" is also the terminology that Auth0 uses for this concept in their documentation.
