### ISSUE TITLE
Add 90d, 180d and 1 year to the time selector for dashboards

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1672]
Only on the dashboard time selector, not the data explorer or host view for now.

**Comment by cryptoquick** [comment]
Correct me if I'm wrong, but I worry the stipulation that the changes to the ranges used by the TimeRangeDropdown should only be on the dashboard time selector, might significantly complicate and/or reduce the maintainability of the component in question.

It gets its configuration data from a single hson file, so either multiple files are introduced, and/or multiple components that do similar things. I could be wrong about the difficulty and aesthetics of this approach, perhaps there's a better way.

Though, perhaps it would shed more light on the matter if I knew the reason for why that stipulation is warranted in the first place.

**Comment by nhaugo** [comment]
Thanks @cryptoquick wasn't sure these were the same component, lets punt on this for now.
