### ISSUE TITLE
Add Pushover alert support

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#1680]
Kapacitor 1.3 now has support for Pushover. See https://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/#pushover for docs.

Here is an example config 
```
[pushover]
  # Configure Pushover.
  enabled = false
  # Your Pushover API token.
  token = ""
  # Your Pushover USER_TOKEN.
  user-key = ""
  # The URL for the Pushover API.
  url = "https://api.pushover.net/1/messages.json"
```

**Comment by nhaugo** [comment]
Add fields for configuration values.
Ensure the node works in the templated tick scripts (possibly adding to the templates)
