### ISSUE TITLE
Unable to visit :8888 web UI

### ISSUE THREAD

**Issue by nifflerfox** [influxdata/chronograf#1683]
Ubuntu 16.04 LTS 64 bit, Kernel 4.4.0-79-generic
Chronograf 1.3.3.4, influxdb_1.2.4_amd64, telegraf_1.3.2-1_amd64, kapacitor_1.3.1_amd64
Description: It works well before last 12 hours. But now, unable to visit Chronograf-IP:8888 web UI, Chrome says: ERR_EMPTY_RESPONSE. I checked service is still running, and TCPing tool tells: Chronograf-IP:8888 port is open, and influxdb works well (influxdb-client can access influxdb api).

In last version, there is the same question, it is "fixed" after reinstalling all new version of influx products.

**Comment by nhaugo** [comment]
@rafw does `curl -v $CHRONOGRAF_IP:8888` return anything

**Comment by rafw** [comment]
I will check it next time. Now web ui works again.

**Comment by birjesh-rawat** [comment]
I have followed all the steps as provided  in the below link 
https://docs.influxdata.com/chronograf/v1.6/introduction/getting-started/

not able to access web UI of  chronograf using http://localhost:8888  .  There is no output kindly help over this.

**Comment by russorat** [comment]
@birjesh-rawat thanks! could you create a new issue for this and add some information about the system you are running on, which version of chronograf you are using, and what you've tried so far?
