### ISSUE TITLE
Moving Time Ranges

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#1685]
In #1681 the capability to do fixed custom time ranges was implemented. We should probably also do moving time ranges, in some sort of calendar interface.

Some possible moving time range suggestions, thanks to @gianarb and @samubd  :
- [ ] today so far
- [ ] this week so far
- [ ] yesterday
- [ ] last week

**Comment by gianarb** [comment]
Thanks Samuele for the initial feedback

**Comment by samubd** [comment]
You are welcome!
Thanks for the effort!

**Comment by alexpaxton** [comment]
Does it make sense to have some TempVars for these a la `:dashboardTime:`? Could have a dropdown or something for the user to choose from

```
:lastWeek:
:yesterday:
:todaySoFar:
:thisWeekSoFar:
```

**Comment by cryptoquick** [comment]
In our IPM, we determined it wasn't a good idea to have tempvars for every choice, due to the fact that we'd have a heck of a lot of them. we'd need to improve our custom tempvar code, too, since it's pretty hardcoded right now.

**Comment by nhaugo** [comment]
For a start we can just do, "last week", "year to date", "last month" and "last year". We can add more ranges as needed.

**Comment by alexpaxton** [comment]
Probably should re-evaluate / re-define this issue

**Comment by jaredscheib** [comment]
I believe the designs for this issue are in https://github.com/influxdata/chronograf/pull/1744 -- could you confirm, @alexpaxton? If so, I believe this should be ready for implementation.

**Comment by jaredscheib** [comment]
Just saw that @alexpaxton created #1824. This issue should probably be closed in deference to that one, but I'll leave that up to @nhaugo.
