### ISSUE TITLE
Kapacitor connect dropdown style messed up

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1692]
<img width="381" alt="screen shot 2017-07-05 at 5 26 28 pm" src="https://user-images.githubusercontent.com/6403018/27890409-5b2dd0be-61a7-11e7-9e14-6f4206f6ac98.png">

**Comment by alexpaxton** [comment]
Unable to repro in `master`

**Comment by alexpaxton** [comment]
Seems like it might be related to #1706

**Comment by 121watts** [comment]
@alexpaxton confirmed that this persists
