### ISSUE TITLE
Custom Time Range Text Input

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#1696]
@goller 's comment: "would love to be able to type in the custom date range as well. It would take a long time for me to scroll back to October 25th, 1985"

**Comment by alexpaxton** [comment]
Here's a design for how this could look/work:

![image](https://user-images.githubusercontent.com/2433762/29050079-9344f74c-7b8e-11e7-8269-6755409d7018.png)

- Added `Begin` and `End` labels for clarity
- Added text fields below labels in which the user can modify the time

**Comment by 121watts** [comment]
I've got this prototyped out.  Will wait for the shortcut PR to get merged in before continuing.

**Comment by lukevmorris** [comment]
Blocked on #1869
