### ISSUE TITLE
As a backend I can save y ranges on a cell

### ISSUE THREAD

**Issue by 121watts** [influxdata/chronograf#1699]
For a given cell on a dashboard we need another field on the cell object to persist range selection.  Something like:
```
{
  x: 0,
  y: 0,
  ...
  ranges: {
    y: [0, 1],
    y2: [null,  null],
  },
}
```
Open to a different shape for `ranges`.  Something like 

```
ranges: [
    {
      axis: 'y',  
      bounds: [0, 1]
    },
    {
      axis: 'y2',  
      bounds: [0, 1]
    },
  ]

```

**Comment by jaredscheib** [comment]
lol @ title

**Comment by timraymond** [comment]
I would like @goller 's input on this before this is taken on. After spending some time reviewing the existing API, I think this would require a data migration as an equivalent API already exists here:

<img width="564" alt="chronograf_api" src="https://user-images.githubusercontent.com/288061/28092173-7a72999c-6660-11e7-90e6-c2e1c0f2d6e0.png">

The current API is inconvenient from the way #1714 is put together. However, the proposed API destroys context provided by having view information like ranges and labels associated with queries, which may be beneficial to some clients.

**Comment by 121watts** [comment]
We can talk more about this when you're back.

**Comment by nhaugo** [comment]
@timraymond i don't think I understand. If this is an optional field there is no migration step that would be needed. What makes adding this field inconvenient.

**Comment by 121watts** [comment]
@goller i think we settled on something like:

```
{
  axes: {
     y: {min: 0, max: 1},
     y2: {..., label: "foo"}
  },
}
```

**Comment by goller** [comment]
```json
{
    "axes": {
        "y": {
            "bounds": [
                0,
                1
            ]
        },
        "y2": {
            "bounds": [
                0,
                1
            ]
        },
        "x": {
            "bounds": []
        }
    }
}```
