### ISSUE TITLE
Custom Time Range indicator in presentation mode feels slightly out of alignment

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1704]
<img width="365" alt="screen shot 2017-07-07 at 3 57 55 pm" src="https://user-images.githubusercontent.com/6403018/27979925-6fbc8be6-632e-11e7-827f-d44acc0839f4.png">

Maybe it should move over to the right, where the `<ContextMenu>` caret was, when `inPresentationMode` is `true`?

**Comment by alexpaxton** [comment]
Ahhh good catch
