### ISSUE TITLE
Vertical crosshair (aka cursor) should show above bar graph lines, like in other graphs

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1705]
Below:
<img width="144" alt="screen shot 2017-07-07 at 3 57 03 pm" src="https://user-images.githubusercontent.com/6403018/27980010-41e90fea-632f-11e7-9436-550bc4cc4fc3.png">
<img width="401" alt="screen shot 2017-07-07 at 3 56 53 pm" src="https://user-images.githubusercontent.com/6403018/27980011-41ec0c40-632f-11e7-8c9d-edcd0c257d9f.png">
Whereas, ostensibly above:
<img width="90" alt="screen shot 2017-07-07 at 3 57 18 pm" src="https://user-images.githubusercontent.com/6403018/27980009-41dfd524-632f-11e7-8976-6e191bcb49fa.png">
Feels weird to me for the cursor to be below the bar graph elements, but open to discussion of course.

**Comment by nhaugo** [comment]
I don't think the hover line is a great fit for bargraphs, i would rather the hovered item highlight.
