### ISSUE TITLE
Unclear UX with snip button in new legend

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1710]
This button appears to be a toggle, so I would expect the UX to be consistent with other UI toggles, i.e. on/off state.
![snip](https://user-images.githubusercontent.com/6403018/28036594-93fda3d2-656d-11e7-9fcb-70363f1e74e9.gif)

**Comment by 121watts** [comment]
The button should probable indicate whether the string is snipped or not

**Comment by cryptoquick** [comment]
Should that button also snip common prefixes entirely? There's algorithms / packages for that.

It would take `cpu.mean_usage_system` and `cpu.mean_usage_user` and turn them into `system` and `user` while also keeping `guest` and `guest_nice` from de-duplicating the term `guest`.

**Comment by 121watts** [comment]
@cryptoquick that would be cool me thinks.
