### ISSUE TITLE
Chronograf 1.3.4.0 uses an unminified build of React

### ISSUE THREAD

**Issue by AlbinOS** [influxdata/chronograf#1719]
Hi,
 
I'm getting a warning from "React Developer Tools" that Chronograf is using an unminified build of React.

I installed Chronograf on Ubuntu using:

```
wget https://dl.influxdata.com/chronograf/releases/chronograf_1.3.4.0_amd64.deb
sudo dpkg -i chronograf_1.3.4.0_amd64.deb
```

The warning:

![chronograf_warning](https://user-images.githubusercontent.com/1978405/28161064-6161da22-67c2-11e7-8c26-41b021ea343d.png)

Thanks a lot for the great work anyway !

**Comment by jaredscheib** [comment]
Thanks for reporting this, @AlbinOS

**Comment by luca-moser** [comment]
Still the same at 1.3.8.1...this really slows down the experience of the UI.
