### ISSUE TITLE
Can't create a query with multiple ANDs relating to the same item

### ISSUE THREAD

**Issue by dhasenan** [influxdata/chronograf#1720]
I have data values representing REST API calls. They're tagged with the HTTP response status code. I want a graph like:

    SELECT count("value") AS "count_value" FROM "rest"."autogen"."apicall" WHERE time > :dashboardTime: AND "response"!='200' AND "response"!='201' GROUP BY time(5m), "response"

Chronograf converts that to:

    SELECT count("value") AS "count_value" FROM "rest"."autogen"."apicall" WHERE time > :dashboardTime: AND ("response"!='200' OR "response"!='201') GROUP BY time(5m), "response"

Which filters nothing -- there are no strings equal to both '200' and '201'.

**Comment by jaredscheib** [comment]
Thanks for reporting this, @dhasenan!

Also, could you clarify what you mean by "helpfully" and "obviously"?

**Comment by sebbacon** [comment]
My workaround is to use regex:

    SELECT sum("c") AS "count" FROM "telegraf"."autogen"."mailgun" 
        WHERE time > :dashboardTime: 
        AND "event_type" !~ /(clicked|opened)/ 
    GROUP BY :interval: FILL(0)
