### ISSUE TITLE
cannot config smtp successfully

### ISSUE THREAD

**Issue by zhugw** [influxdata/chronograf#1722]
I want to send alert info by email so I should config smtp first, but I cannot config it successfully and I always got below error

<img width="985" alt="screen shot 2017-07-14 at 11 05 26" src="https://user-images.githubusercontent.com/4953871/28197251-3a3f8716-6888-11e7-8005-cf46518b271a.png">

```
{
    "error": "failed to update configuration smtp/: timeout"
}
```

I'm very confused why access local network could timeout, in addition the log info in `kapacitor.log` cannot help 

```
[httpd] ::1 - - [14/Jul/2017:11:25:17 +0800] "POST /kapacitor/v1/config/smtp/ HTTP/1.1" 500 85 "http://192.168.0.24:8888/sources/1/kapacitors/1/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" 0eeefa2c-6844-11e7-b03d-000000000000 5004115
```
and there is no `chronograf.log` exist.

And if in this situation, it also cannot display alerts rules page(http://192.168.0.24:8888/chronograf/v1/sources/1/kapacitors/1/rules), it seems it is blocked

<img width="1111" alt="screen shot 2017-07-14 at 11 07 58" src="https://user-images.githubusercontent.com/4953871/28197357-e27a74ea-6888-11e7-9800-f4fb06c74e69.png">

**Comment by jaredscheib** [comment]
Thanks for reporting this, @zhugw

**Comment by jaredscheib** [comment]
This may be related to https://github.com/influxdata/kapacitor/issues/1472#issuecomment-353440476.

**Comment by russorat** [comment]
I've configured smtp many times from chronograf. closing for now. if this is still an issue, please reopen.
