### ISSUE TITLE
[bug] Having too many queries in DE leads to unexpected behavior

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#1726]
### Steps to reproduce:

- Open Chronograf
- Navigate to Data Explorer
- Create 4 queries that pull data (Doesn't present with 3 queries)
- Navigate to a separate pane
- Close all 4 query panes
- A single query pane (Query 1) will then appear that user can't interact with. 
- Opening a new pane and attempting to create a query leads to unexpected behavior

<img width="1436" alt="screen shot 2017-07-17 at 3 56 26 pm" src="https://user-images.githubusercontent.com/7452680/28287222-d28b5c8e-6b08-11e7-8f4c-ed273e2b5133.png">

**Comment by russorat** [comment]
this ui has changed and this issue is no longer relevant.
