### ISSUE TITLE
User should be able to set Kapacitor alert rule 'priority' level via alert rule builder UI

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1728]
Currently the only way to set the priority level for a Kapacitor alert is via a TICKscript, i.e. `.crit()`, `.warn()`, etc. It seems like it would be valuable for a user to be able to set the alert level for a given alert via the UI when creating an alert rule.

cc @nathanielc

**Comment by nathanielc** [comment]
An alert has a level, which can be one of 

* OK (cannot be directly specified but indicates that no other alert level was met)
* INFO
* WARNING
* CRITICAL

I see two ways this could work for a user:

1. Allow the user to specify the alert level for a rule
2. Allow the user to specify the condition for each alert level for each rule.

Option 2 maps better to how the alerts work in Kapacitor but requires a more complicated UI.

**Comment by goller** [comment]
Hey there, I think this is a dup of #669
