### ISSUE TITLE
Result Tabs need Tag Values

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1731]
Found in Chronograf 1.3.4.0

Create a database called `state_fair_db` 

Write the following data into the `state_fair_db` using the write data capability of Chronograf....
```
foods,fair_id=1 funnel_cakes=23 1500267600000000000
foods,fair_id=1 funnel_cakes=28 1500267960000000000
foods,fair_id=1 funnel_cakes=27 1500268320000000000
foods,fair_id=2 funnel_cakes=14 1500267600000000000
foods,fair_id=2 funnel_cakes=18 1500267960000000000
foods,fair_id=2 funnel_cakes=36 1500268320000000000
```

Now, execute the following query in data explorer:
SELECT mean("funnel_cakes") AS "mean_funnel_cakes" FROM "state_fair_db"."autogen"."foods" WHERE time > now() - 1w GROUP BY time(1w), "fair_id" fill(none)
(note: you may need to expand the time range here to capture the correct date/time.  7/17/2017 06:00UTC)

Select Table as the result display type.  There are two tabs available -- however, the user is unable to disambiguate them.  One represents fair_id=1 and the other is fair_id=2.  However, the tabs are both named "foods".  In fact, they should be labeled with the tag key and value to make this useful.

<img width="1147" alt="chronograf-tag-key-value-issue" src="https://user-images.githubusercontent.com/23535264/28313395-8edde7a0-6b6b-11e7-9477-402eaf094c72.png">

Example of what is returned via CLI:
<img width="1097" alt="cli-output" src="https://user-images.githubusercontent.com/23535264/28313420-a5a3e160-6b6b-11e7-9152-607346adb5a2.png">

**Comment by jaredscheib** [comment]
yum!

**Comment by russorat** [comment]
that component was removed in 1.7.
