### ISSUE TITLE
Provide a self-describing schema for Kapacitor alerts to Chronograf client

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1746]
Currently, the values that can be provided to a Kapacitor alert node by the Chronograf client, whether `args`, `properties`, `message`, or `details`, are having to be constructed and managed in the client. This is highly fragile (error prone), and difficult to test, and brings up a number of specific questions in each case: how should the data be formatted/parsed for each particular node type, what would sample data look like, and where can a user find instructional information?

This would take care of versioning for which capabilities are available as well.

The server would then provide a self-describing schema, including grammatical (formatting/parsing) information, sample data via a `placeholder` (or similar) field, the exact name of each key expected for any arg or property, and instructional information. Basically providing `kapacitor/pipeline/pipeline.go` in a parsed and actionable format.

It would provide for a much better developer and user experience if the server provided a collection of zero-value'd schemas of pertinent arguments, properties, message, and/or details, and metadata, as well as sample (placeholder) data about what format it needs to receive that data back in (for use in formatting and validation by the client), and instructional information about each possible field, rather than the client having to recreate these structs explicitly.

See `/src/kapacitor/constants/index.js` at `RULE_ALERT_OPTIONS` in the branch `feature/kapa_alert_props-1755` for what these constructs currently look like.

Also, it may be that some valued are incorrectly configured, or that we are not sending data correctly back to Kapacitor via proxy. For example, the recently added Pushover. Which should be arrays? How does the server expect these values to be formatted?

**Comment by goller** [comment]
Added in #2447

**Comment by russorat** [comment]
@goller can this be closed?

**Comment by goller** [comment]
@russorat I think so, yes.
