### ISSUE TITLE
Add empty table state when no Kapacitor alerts set

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1747]
<img width="1275" alt="screen shot 2017-07-20 at 2 41 26 pm" src="https://user-images.githubusercontent.com/6403018/28440052-927de9d8-6d59-11e7-93a4-38723ba195ff.png">
Should be consistent with other empty tables in Chronograf client.

**Comment by russorat** [comment]
decided not to fix in 1.x branch
