### ISSUE TITLE
Improve discovery of adding query to dashboard cell

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1765]
For a new user, it is somewhat unintuitive as to how one might add a query to get a new graph populated. Clicking the caret and then `Edit` would be discovered by process of elimination, rather than intuitive and direct clarity.

Maybe a blue `Edit` or `Add Query` button, like in other Empty State cases, would be useful?

<img width="464" alt="screen shot 2017-07-22 at 5 13 42 pm" src="https://user-images.githubusercontent.com/6403018/28495424-29b3bb5e-6f01-11e7-8183-cf95ee382492.png">

**Comment by alexpaxton** [comment]
I like this idea
