### ISSUE TITLE
Cells on Layouts should have axes like the cells on Dashboards

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#1768]
This is follow-on work uncovered during #1740 which is an implementation of #1699. As of #1740, it's possible to persist axes on a dashboard cell. The same should be possible for the cells of a pre-canned dashboard.

**Comment by 121watts** [comment]
@timraymond this has been in progress for 10 days.  What's the status?

**Comment by timraymond** [comment]
I have some work on this, but there's been so much churn on the spec for it
that I've set it aside until #1602 is merged

-- 
Timothy Raymond
Developer at InfluxData
Enterprise Team
tim@influxdb.com
