### ISSUE TITLE
Add all Kapacitor alert args and properties, with correct formatting for each service

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1769]
See #1755.

Most args and properties are now implemented, but work that remains to be done can be found in various `TODO`s in `src/kapacitor/constants/index.js` and `/src/kapacitor/reducers/rules.js`. This work is primarily determining how to format and delimit args and props (ex. `headers` for `http`), uncommenting them, and adding any possible formatting/parsing to the respective service's `case` in the reducer.

We should also:
- [ ] refactor `alerta` to use UI fields instead of TICKscript
- [ ] add UserKey as an optional property to `pushover`
- [ ] replace `ALERT_NODES_ACCESSORS` with a dedicated action creator and reducer, which would parse received data for display in the UI
- [ ] include sample data as `placeholder`
- [ ] include instructional data where useful

Doing this would should result in a standardized handler for displaying all alert services fields in the UI and processing via reducers, such that any arbitrary number of args and properties can be displayed and be functional.

**Comment by craig-mulligan** [comment]
Hey @jaredscheib, I've just started digging into tick stack and looking for a way to add custom headers to the alert webhooks, is this something the above would include? Or is that still something that needs to be implemented in kapacitor?

**Comment by jaredscheib** [comment]
Hi @craig-mulligan, thanks for writing in! I'll be able to look into this question early next week. I'm not sure, off hand. In the meantime, I'd suggest for now that you check out the docs for Kapacitor, and see whether you can determine if that's possible in Kapacitor currently, apart from Chronograf. Kapacitor has a ton of functionality that Chronograf doesn't currently support, and I'm not immediately familiar with this one you're asking about. Let me know what you find, or otherwise I'll respond again when I'm back.

**Comment by desa** [comment]
Currently only the `post` alert handler allows you to add headers. Here's the associated documentation: http://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/#post.

It might be worthwhile to have Chronograf utilize the `endpoint` functionality, but that might be a bigger story. Happy to add more color here if there's interest.

**Comment by goller** [comment]
@desa, @jaredscheib we shoudl be able to utilize `endpoint` via the `KapacitorProperties` here https://github.com/influxdata/chronograf/blob/master/chronograf.go#L514

**Comment by craig-mulligan** [comment]
Thanks for the quick responses 💯  For extra context I'd like to add headers so I can hook it up to a an [`sns` service](https://hub.docker.com/r/octoblu/sns-service/) but I imagine there are a lot of usecases. 

I maybe able to lend a hand but I'll wait till @jaredscheib is back and we have a clearer picture.

**Comment by jaredscheib** [comment]
Thanks @desa and @goller  for the insight.

@craig-mulligan Do you mean specifically that you'd like to be able to set custom headers using the `http` alert in the Chronograf UI here:
<img width="304" alt="screen shot 2017-08-28 at 11 52 29 am" src="https://user-images.githubusercontent.com/6403018/29788428-65ec24aa-8be7-11e7-8c3a-32c1f527a3fd.png">

Seems like what's required is uncommenting (as referred to in the OP) the `endpoint` and `header` property and determining how to implement header delimiting, per the the TODO comment there. We may also want to provide for the ability to add multiple endpoints with headers. The Chronograf server is already ready to receive these properties.

Let me know if this would address your inquiry, and thanks again.

**Comment by craig-mulligan** [comment]
Yes, custom headers is all I currently need, but multiple endpoints I'm sure would be useful too.

**Comment by whyou5945** [comment]
@jaredscheib Hey, sorry to trouble you. But it seems we can add header on the UI when we using an post handler already. But we can only add one pair of key value. How can we add multi pairs header?

**Comment by jaredscheib** [comment]
@whyou5945 thanks for writing in. @russorat can help field this question for you!

**Comment by whyou5945** [comment]
@jaredscheib  Thanks a lot. @russorat could u please have a look of my question?

**Comment by whyou5945** [comment]
@russorat

**Comment by russorat** [comment]
bump
