### ISSUE TITLE
Expand the size of the Write Data modal

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1774]
I typically paste a large number of data points through the "write data" modal window in the Data Explorer.  It would be nice to expand the size of the modal itself to decrease the amount of scrolling required.  

There appears to be plenty of real-estate to expand this.

**Comment by lukevmorris** [comment]
We can increase the default size of the modal, and make the text area resizeable in case the user wants to click+drag to expand its size.
