### ISSUE TITLE
Add spinner to Write Data modal

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1775]
I pasted in a large data set into the Write Data modal window and hit submit. 

It all seemed to work fine.....but there was a long pause and I was concerned things had hung up.  

Having a progress indicator of some sort would be ideal.

**Comment by lukevmorris** [comment]
Curious -- how big was the file?

If the main concern is communicating to the user that nothing has hung, then we can solve that with a spinner for now. A progress indicator is significantly more complex.

**Comment by timhallinflux** [comment]
Use the dataset described here:
https://docs.influxdata.com/influxdb/v1.3/query_language/data_download/
