### ISSUE TITLE
RFC: Legend snip functionality should remove the whole common substring among legend items

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1778]
See [here](https://github.com/influxdata/chronograf/issues/1710#issuecomment-314497626) for more information

**Comment by jaredscheib** [comment]
It would be important to think through the possibilities and get an exact spec on what the behavior of this would be. It _may_ not always be right to get rid of the full or any part of the common strings.

**Comment by 121watts** [comment]
I agree with jared.  Also, the issue this is referencing is closed.  Closing.
