### ISSUE TITLE
Bug in Data Explorer: table not scrollable when applying "Group by 5m"

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1786]
First of all I would like to say that I love Chronograf and InfluxDB!

I found the following issue: when applying "Group by 5m" the data table is not scrollable and one is not able to see all data available.

OS: Ubuntu 16.10, 64bit
Version of Chronograf: 1.3.4.0 (Docker Image)
Version of InfluxDB: 1.3.1 (Docker Image)
Version of Kapacitor: 1.3.1 (Docker Image)

Screenshots

Table is not scrollable:
![table_not_scrollable](https://user-images.githubusercontent.com/1226918/28621005-beafacd4-720f-11e7-8490-fce0ea86b47c.png)

Graph is OK:
![graph_is_ok](https://user-images.githubusercontent.com/1226918/28621011-c464342e-720f-11e7-8234-14226a92abc0.png)

**Comment by 121watts** [comment]
@core-process thanks for writing in!  We will take a look

**Comment by core-process** [comment]
@121watts @nhaugo Awesome, thanks!
