### ISSUE TITLE
Table titles not meaningful in Data Explorer when applying "GROUP BY"

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1787]
First of all I would like to say that I love Chronograf and InfluxDB!

I found the following issue: The table titles not meaningful in Data Explorer when applying "GROUP BY". It is not obvious which tab relates to which tag-value.

OS: Ubuntu 16.10, 64bit
Version of Chronograf: 1.3.4.0 (Docker Image)
Version of InfluxDB: 1.3.1 (Docker Image)
Version of Kapacitor: 1.3.1 (Docker Image)

Screenshot:
![table-titles-confusing](https://user-images.githubusercontent.com/1226918/28622055-65c0002a-7213-11e7-920e-75cd84f9ca6d.png)

**Comment by nhaugo** [comment]
Thanks @core-process, good catch.

**Comment by nhaugo** [comment]
Start with the series key and we will break it down from there.

**Comment by 121watts** [comment]
@core-process something like this?
![kapture 2017-10-23 at 13 49 35](https://user-images.githubusercontent.com/7582765/31912540-1775b01e-b7f9-11e7-998e-bd7519b4a4cf.gif)

**Comment by core-process** [comment]
@121watts awesome, thanks!
