### ISSUE TITLE
Feature request: make name and range of axis editable for graphs in dashboards

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1788]
Would be nice if one could edit ranges and names of axes of graphs in dashboards!

Is this already part of the roadmap? :-)

**Comment by core-process** [comment]
seems to be related to this pull request: https://github.com/influxdata/chronograf/pull/1714

looking forward too! :-)

**Comment by 121watts** [comment]
@core-process def on the roadmap. keep your eyes peeled!
