### ISSUE TITLE
[Feature Request] LDAP/AD integration 

### ISSUE THREAD

**Issue by adityacs** [influxdata/chronograf#1791]
LDAP/AD integration would be a nice feature. Gives more controls over user access management.

**Comment by cobaugh** [comment]
Grafana has this: http://docs.grafana.org/installation/ldap/

We don't want to use influxdb users to grant access to chronograf, and we want to control which non-influxdb users have access to administer influxdb through chronograf.

**Comment by jaredscheib** [comment]
Note for the future: for our current multitenancy implementation, we are forcing `Scheme: OAuth2` on all users. So when the time comes to implement LDAP or other provides, reminder to remove this forced value in `server/me.go` and `server/users.go`.

**Comment by goller** [comment]
PR #2526 from @cxcv should be able to handle this.

**Comment by Mailerm** [comment]
+1

**Comment by jcmartins** [comment]
+1
