### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by Rizbe** [influxdata/chronograf#1793]
We have been using Grafana for awhile but decided to give this project a shot because we love InfluxDB. Out the gate, noticed a few things and was not able to find info in the wiki regrading this, so figured I would ask here.

Is there no way to change units? For example, I would like to see my memory usage in GB but haven't found a way to change it.

If I am using multiple host in one graph, is there a legend somewhere?

Not sure if the above 2 things exist or just hiding in the UI very well.

**Comment by 121watts** [comment]
@Rizbe Thanks for writing in!  There isn't a way to change units but it is in the roadmap.  There definitely is a legend for every visualization.  Unless I'm misunderstanding, hovering over the graph should produce the legend you seek.

**Comment by jaredscheib** [comment]
Thanks @Rizbe!

Sounds like the first of your questions would be a dupe of #1413. Anything missing from that story that you're requesting?
