### ISSUE TITLE
Telegraf on Windows show up as Red (down) Status in Chronograf

### ISSUE THREAD

**Issue by jl98800** [influxdata/chronograf#1794]
Two reasons (so far) why a Windows sever shows up as red (down) in Chronograf:

1.  NTP - time if off. 
2.  Telegraf.conf is set to intervals greater than 1m.

In my case neither is true and the Windows instance still shows up as down in Chronograf.

I can query data all day long so I know Telegraf is sending data to InfluxDB. I built a dashboard around this too.  

So why do Windows servers show up as Red (down) in Chronograf?

**Comment by jademcgough** [comment]
@jl98800 We are currently working on a fix for this. You can monitor our progress in #1633.

Closing this as a duplicate.

**Comment by jl98800** [comment]
<img width="796" alt="screen shot 2017-07-27 at 1 39 24 pm" src="https://user-images.githubusercontent.com/25671374/28689019-448674d4-72d1-11e7-8cd0-38bd572cf8ce.png">
