### ISSUE TITLE
Query text and custom time range get out of sync in DE (and elsewhere?)

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1801]
@alexpaxton wrote in #1785 :
""
In the DE, When choosing a custom time range that is large it takes a bit to load, so it's been tougher to test certain things. I've been able to get around the load times by manually changing the group by time to something much larger and resubmitting the query manually. Though once I manually change something in the query, the custom time range option does not seem to update.

For example if I select July 22 - July 25 and apply, it loads for a bit then displays the correct points on the graph. If I edit the query manually, and change the start date to July 20 it loads then displays correctly, but if I open the custom time range selector it still shows the range as being July 22 - July 25. If I try to select a standard time range like Past 6 hours it does not affect the query. I am assuming that this is because I have modified the query such that it cannot be represented by the builder any longer.

Seems like the time range dropdown as a whole no longer affects the query at this point. Makes me wonder if we need something indicating that their query modifications have disabled the UI.
""

**Comment by 121watts** [comment]
@jaredscheib also, the DE's `timeRange` dropdown is not effected at all when you manually enter a time range in the query text.
