### ISSUE TITLE
Prevent Kapacitor rule creation if missing mandatory node values (e.g. for Alerta)

### ISSUE THREAD

**Issue by amartorelli** [influxdata/chronograf#1804]
Hi!
I'm trying to send alerts to Alerta. Everything works fine and I can get the alert sent, but when trying to edit the rule again in Chronograf the page hangs. It only hangs after the alert has triggered.

The path it's trying to open is:
`/sources/1/alert-rules/chronograf-v1-90640728-3af0-4211-97b4-18b4705fee6b`

<img width="2558" alt="screen shot 2017-07-30 at 18 26 56" src="https://user-images.githubusercontent.com/9568357/28755534-1bd51410-7555-11e7-86d2-af3c59c3b7cd.png">

Looking at what's happening in the browser console I can see these errors:
<img width="707" alt="screen shot 2017-07-30 at 18 40 41" src="https://user-images.githubusercontent.com/9568357/28755610-aa15a31a-7556-11e7-8dbd-f96fd1b7fdf7.png">

![screen-shot-2017-07-30-at-18 31 18](https://user-images.githubusercontent.com/9568357/28755571-d3ff7300-7555-11e7-90dc-a209794828cf.png)

I'm not sure if this is a bug and whether if affects only Alerta or other systems.
Please let me know if I can give you more info.

Thanks

**Comment by jaredscheib** [comment]
Thank you for reporting this, @AlessioMartorelli.

Could you tell us:
1) what version of Chronograf are you using, and which version did you create it with?
2) does the alert continue to work despite this error?
3) if you run your server with the flag --log-level=debug, could you tell us if there's any particular errors you're seeing that may be related?

**Comment by jaredscheib** [comment]
Thanks for the info @AlessioMartorelli.

So it sounds like this is more of a UX issue, where you were not made aware of what was missing from your alert rule, and thus allowed to create an improper rule that then errored out, yeah?

If that sounds accurate, three possible solutions that come to mind are:
1) enforce mandatory fields in rule creation;
2) automatically add default values for mandatory fields that the user doesn't input (either in Chronograf or Kapacitor);
3) handling this error by notifying the user via the UI what the specific problem is.

**Comment by AlessioMartorelli** [comment]
Hi @jaredscheib , yes that sounds about right!
Of course I must say I was new too the product so should have read the documentation beforehand but as you say it'd be nice to be at least flagged somehow.

Thanks!

**Comment by jaredscheib** [comment]
Cool -- thanks again!

**Comment by jaredscheib** [comment]
Note for development: This may also be due to the fact that Alerta nodes are currently created by simply pasting a TICKscript. This should be updated to use the new UI options as of 1.3.5.0.

**Comment by AlessioMartorelli** [comment]
I'll take advantage of this issue to ask something else. I've noticed that the `value` field is not passed on to Alerta. I'm trying to set it explicitely like this:
```
alerta().event('Something went wrong').value("value")
```
But the UI wouldn't let me. Maybe it'd be nice to pass the value by default or at least explain how to do it via the UI.
Reading the documentation the following should be valid:
```
node.alerta()
      .value(value string)
```

**Comment by jaredscheib** [comment]
Are you passing these nodes in by pasting a TICKscript into the input field in the Chronograf UI?

And could you tell me whether the Network request is sending `value` down the wire? And if `details` has any value as well in that XHR (the post to `http://localhost:8888/chronograf/v1/sources/{sourceID}/kapacitors/{kapacitorID}/rules`?

**Comment by AlessioMartorelli** [comment]
Hi @jaredscheib,
yes I'm copying and pasting the script.
When pasting the TICKscript I've put in my previous comment I can't see anything happening at the network level:
<img width="720" alt="screen shot 2017-08-01 at 18 35 47" src="https://user-images.githubusercontent.com/9568357/28838480-5f2c22c8-76e8-11e7-827d-79b8e2c62c6e.png">

Let me know if I'm looking at the right thing or you meant something else.

**Comment by jaredscheib** [comment]
Ah, I meant the network request after you paste and then when you hit `Save Rule` at the top right.

**Comment by AlessioMartorelli** [comment]
This is the source including the full TICKscript: https://pastebin.com/RptD3zQt
This is the parsed version:
<img width="2346" alt="screen shot 2017-08-01 at 18 54 50" src="https://user-images.githubusercontent.com/9568357/28839268-fd48a16e-76ea-11e7-9dd4-cc4ff3fd6111.png">
