### ISSUE TITLE
Single line graph doesn't unhighlight on mouseaway

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1808]
Watch the line graph in the bottom right. When you mouse away from it, it doesn't unhighlight, as other lines and other graph types do. Seems to only happen on single line graphs.

![line_doesnt_unhighlight](https://user-images.githubusercontent.com/6403018/28804817-6f6c8d36-761a-11e7-94bf-60b9f628db21.gif)

**Comment by nhaugo** [comment]
Fixed in #1766
