### ISSUE TITLE
Group by interval resets to 10s after changing aggregate functions

### ISSUE THREAD

**Issue by hoomanv** [influxdata/chronograf#1809]
In Data Explorer, every time I add or remove an aggregate function and press Apply, the group by interval resets to 10s. If the data being queried spans over a year, this will certainly make the GUI unresponsive.

**Comment by jaredscheib** [comment]
Thanks for letting us know, @hoomanv. It sounds like the ideal UX would be that the GROUP BY interval remains at whatever you last set it. How does sound to you?

**Comment by hoomanv** [comment]
I agree 👍

**Comment by gee-forr** [comment]
I have the same problem here. My browser normally lands up hanging because I'm working with quite large datasets.

I'll keep an eye out for `v1.4`.
