### ISSUE TITLE
Ability to pass query to data explorer via a URL call to Chronograf

### ISSUE THREAD

**Issue by edbernier** [influxdata/chronograf#1815]
Within Chronograf in the data explorer you have the possibility to query manually by using the InfluxDB query language. So instead of entering the parameters within the Chronograf UI we would like to hand it over by URL to Chronograf and see a Chronograf Data Explorer tab open with the output of this query.

**Comment by nhaugo** [comment]
I don't fully understand what you mean, you would like to be able to open a the data exporter with the query as a URL parameter?

**Comment by edbernier** [comment]
To clarify. Within Chronograf in the data explorer you have the possibility to query manually by using the InfluxDB query language. So instead entering the parameters within the Chronograf UI we would like to hand it over by URL to Chronograf and see then the data explorer with the output of this query. Our inventory application will open a new browser window with this Chronograf query URL and the user can see the graph as they would type the query manually within Chronograf. We only wish to query by URL and visualize the output within Chronograf data explorer. We have no intension to import any data this way.

**Comment by graf3net** [comment]
Correct! 

Within Chronograf in the data explorer you have the possibility to query manually by using the InfluxDB query language. So instead entering the parameters within the Chronograf UI we would like to hand it over by URL to Chronograf and see then the data explorer with the output of this query. 

As an example. Our inventory application will open a new browser window with this Chronograf query URL and the user can see the graph as they would type the query manually within Chronograf. 

We only wish to query by URL and visualize the output within Chronograf data explorer. We have no intension to import any data this way. Does this make sense?

kind regards
Swisscom, Thomas Graf

**Comment by nhaugo** [comment]
It does, thank you for the clarification.

**Comment by axbu123** [comment]
Kindly understand me how can i pass value of dashboard's variable through URL?
