### ISSUE TITLE
Allow user to customize :interval: resolution

### ISSUE THREAD

**Issue by rizadh** [influxdata/chronograf#1819]
The current `:interval:` template variable chooses the maximum possible resolution (or minimum interval) that will fit the pixels on the screen. That is, each interval corresponds to one pixel on the screen.

However, certain graphs have values that tend to fluctuate quite a bit, which muddies the information being presented.

It would be nice if the user could change how dense the intervals should be. I can think of two ways to present this:

- Allow the user to choose "pixels per interval". For example, if set to `10 pixels`, each interval would be 10 pixels widet. Setting to `1px` would simulate the current `:interval:` implementation.

- Allow the user to choose how many "intervals per graph". For example, if set to `10 intervals` on a 24-hour graph, then each interval would be 2.4 hours or 144 minutes, meaning `:interval:` would translate to `time(144m)`.

Having both options available would be even better.

**Comment by russorat** [comment]
we don't have any plans to support this feature.

**Comment by cyounkins** [comment]
It looks like you can do math on the time interval to achieve this effect! For example, you can do `GROUP BY time(:interval: * 2)` to multiple the automatically selected interval by 2, giving you half the graph points.

It looks like the operator needs to come after `:interval:` - `GROUP BY time(2 * :interval:)` yields "time dimension must have duration argument" so there may be some restrictions on what you can do.
