### ISSUE TITLE
Automatically adjust :interval: when zooming in

### ISSUE THREAD

**Issue by rizadh** [influxdata/chronograf#1820]
The `:interval:` template variable allows a graph to be as information dense as possible.

However, I have found that a graph using `:interval:` loses its density when zooming in.

For example, it may be calculated that a graph's ideal interval is `1h`. When zooming into a smaller section of the graph, the graph the interval should automatically shrink to make the most use of the available screen space. However, this does not happen and the data points became quite spread out.

Changing the actual time range of the entire graph does make the change, but it is not as intuitive or quick.

This makes it impossible for a user to look at a quick-loading overview of a graph, then dig down for a more detailed look.

**Comment by 121watts** [comment]
@rizadh great suggestion.  Is [this what you are looking for](http://g.recordit.co/Yw5hH1eeGq.gif)?

**Comment by rizadh** [comment]
@121watts Yes, that looks perfect!
