### ISSUE TITLE
Plugin/Mod Support

### ISSUE THREAD

**Issue by lmangani** [influxdata/chronograf#1822]
Hello Chronografers,

In complimenting the latest release and usefulness, I was wondering if there is existing or planned support to allow plugins, mods or UI extensions for Cronograf without forking it?

Thanks!

EDIT: autocorrect

**Comment by cryptoquick** [comment]
What sort of features or plugins would you like to see? Which parts of the application would you like to augment?

**Comment by lmangani** [comment]
Mostly thinking of new Visualization Types / Options and other types of non-Graph Cells for Dashboards, maybe providing the ability to add new "tabs" to the leftie column with new "Apps" providing internal or external functionality - long term goal of adding other datasources and search forms to the mix without bastardizing its wonderful codebase.

**Comment by cryptoquick** [comment]
Those are some fabulous ideas! I'd welcome you to open a few detailed, separate issues on each idea, so they can be made more concrete concepts, then we can decide if that should be optional functionality that should be in 'plugin' form, for which there is no obvious technical obstacle towards, say, providing a HOC API for certain select places components, however, if there's value in the feature for you, there's likely value in the feature for others. Further, to develop a HOC API, we'd need to establish the actual features from what plugins might require from its portion of the component, just to create an API. Does all that make sense?

**Comment by lmangani** [comment]
It does make sense, and thanks for the welcoming approach. 
I've developed mods and plugins for other notorious platforms in the past, particularly Kibana, and was trying to find an analogy to attempt some here. I'll try isolate a few patters in separate issues to further discuss the various ideas/needs, or maybe refine this one with a more specific request starting from the bottom up. Any suggestion appreciated and once again thanks!

**Comment by cryptoquick** [comment]
One additional consideration:
If you wanted to develop a plugin for standard Chronograf, from what I understand, you'd need to make it open source also, due to our project's use of the AGPL license.
Influx Enterprise does not have this constraint, however.

**Comment by lmangani** [comment]
100% our project HOMER which is focal to the above questions is also AGPL and fully compatible from that perspective :)

**Comment by cryptoquick** [comment]
👍 😄

**Comment by dowstreet** [comment]
Has there been any more thinking / progress in this area?  We're currently running InfluxDB with a custom front-end for visualization, but it would be great to develop this code as one or more plugins for Chronograf instead - especially given how much Chronograf has matured recently.  :-)

I think our roadmap would be similar to Imangani's thinking:

a. custom panel for different types of visualization (initially)
b. custom 'apps' in the left side menu (eventually)

**Comment by lmangani** [comment]
@cryptoquick as I am 100% certain you already know the awesome guys at LoudML shipped a very cool extension for Chronograf which unfortunately still requires to compile a custom fork - hopefully this adds to the valid examples for this request topic :)

**Comment by hertzg** [comment]
Is this feature no longer considered?
