### ISSUE TITLE
As a user I can toggle now() in the date picker

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1825]
### Problem:
- User can not mix `now()` and a fixed date

![image](https://user-images.githubusercontent.com/2433762/29050153-f7161b84-7b8e-11e7-9e71-52682b715815.png)

### Proposed Solution:
- Add a checkbox (or toggle) for `Now` in the `Begin` half of the date picker
![image](https://user-images.githubusercontent.com/2433762/29050210-5f59e5e0-7b8f-11e7-90ee-f6ed3319d9d5.png)

- When `Now` is toggled, replace timestamp with `now()`
![image](https://user-images.githubusercontent.com/2433762/29050220-6b2c21f8-7b8f-11e7-821a-3c10c73a8372.png)

**Comment by nhaugo** [comment]
If you could find a way to move this to end instead of begin, then we won't turn back time.
