### ISSUE TITLE
As a user I can see a list of Chronograf users

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1829]

**Comment by alexpaxton** [comment]
![chronograf-web-admin-2](https://user-images.githubusercontent.com/2433762/29431472-e8768b98-834c-11e7-94ce-91dea715cefe.png)

**NOTES**
- Follows same table edit paradigm from existing admin page
- When hovering over a row:
  - Role becomes dropdown, enables assignment of new role
  - Delete user link appears on rightmost cell
- When `Create User` is clicked:
  - Create new role at the top of the table
  - Editable fields for `Username` & `Email Address`
  - Role dropdown has default value specified via org settings ( #1831 )
  - Save/Cancel buttons in rightmost cell
- Roles & Permissions column is just for reference
  - Each section accordions open

**Comment by jaredscheib** [comment]
Cool to see -- thanks @alexpaxton. Let's revisit this once a design doc is finalized shortly.

**Comment by nhaugo** [comment]
Creating users here is out of scope for this, no editing needed

**Comment by alexpaxton** [comment]
I should add that instead of simply titling the left panel `Users` I would like to include the name of the user's current org: `[CurrentOrgName] Users`
