### ISSUE TITLE
Admins can whitelist / create a user for their organizations

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1830]

**Comment by jaredscheib** [comment]
Two users could authenticate through two different OAuth providers, and as part of two different OAuth organizations, and end up in the same Chronograf Organization, because Chronograf Organizations are entirely independent (though future-backfillable) from OAuth Organizations.

**Comment by nhaugo** [comment]
yes

**Comment by jaredscheib** [comment]
Double-check that this just works.
