### ISSUE TITLE
Chronograf Organizations should have settable default role

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1831]

**Comment by alexpaxton** [comment]
![chronograf-web-admin--manage](https://user-images.githubusercontent.com/2433762/29431441-cb25216c-834c-11e7-8b4e-ab1db159369f.png)

This modal is accessible via the `Manage` button in the `Chronograf Admin` page header

**Comment by jaredscheib** [comment]
Do you mean, Chronograf Organizations should have a default settable role, @nhaugo?

**Comment by nhaugo** [comment]
The role can come from the Chronograf Org default. But we should have a way to map Oauth Orgs into Chronograf orgs
