### ISSUE TITLE
As a user I can set the organization to have an open/specified user type

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1832]

**Comment by jaredscheib** [comment]
@nhaugo Could you clarify what this means?

**Comment by jaredscheib** [comment]
So if they're from GitHub, they're a Viewer; but if they're from GitHub:Influx, they're an Editor.

See #2217.

**Comment by jaredscheib** [comment]
This should be solved in the client and server in the same PR.

**Comment by jaredscheib** [comment]
This issue is rendered obsolete by https://github.com/influxdata/chronograf/issues/2217. Closing.
