### ISSUE TITLE
As a user I can select fill() as part of my query in the query builder

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1842]

**Comment by alexpaxton** [comment]
All queries should have `fill()` tacked onto the end. User can currently type this in manually, but now we want a UI to make it easier. When in the CEO a dropdown appears in the bottom right (where the meta queries dropdown appears in the DE) -- (See Documentation)[https://docs.influxdata.com/influxdb/v1.3/query_language/data_exploration/#group-by-time-intervals-and-fill]

![screen shot 2017-08-11 at 2 03 25 pm](https://user-images.githubusercontent.com/2433762/29232030-6b169600-7e9e-11e7-8cf6-d25512192d40.png)

Default value is `null`

![screen shot 2017-08-11 at 2 03 57 pm](https://user-images.githubusercontent.com/2433762/29232077-a10c96c4-7e9e-11e7-8326-eca955a1397c.png)

If the user selects `Number` a number input appears to the right

![screen shot 2017-08-11 at 2 06 52 pm](https://user-images.githubusercontent.com/2433762/29232118-cfb71d28-7e9e-11e7-9b3b-4ffb70954864.png)

**Comment by alexpaxton** [comment]
As I understand it, `fill(null)` is the same as not having a fill option at all, so I figure we just show that by default to be transparent to the user
