### ISSUE TITLE
SingleStat Doesn't show correctly 

### ISSUE THREAD

**Issue by siamaksalman** [influxdata/chronograf#1865]
I'm running Chronograf-1.3.6.0-1.x86_64 on "CentOS Linux release 7.3.1611 64 bit from pre-built package.

This is my query : 
SELECT max(sum_online) FROM ( 
SELECT sum("online") AS "sum_online" FROM "mydb"."autogen"."cuncurrent_user" WHERE time > :dashboardTime: GROUP BY time(5s) )

and I'm selecting SingleStat Visualization type but when I press okey, I see a Line graph with a single point in as the result.
![screenshot from 2017-08-14 21-28-36](https://user-images.githubusercontent.com/5879053/29282369-d3519242-8137-11e7-8341-742a9f996b13.png)
![screenshot from 2017-08-14 21-28-57](https://user-images.githubusercontent.com/5879053/29282370-d3564de6-8137-11e7-89e2-9d4ebd0df3af.png)
![screenshot from 2017-08-14 21-29-25](https://user-images.githubusercontent.com/5879053/29282371-d3572554-8137-11e7-8318-2973811f4244.png)

**Comment by 121watts** [comment]
We are on it!  Thanks for opening the issue

**Comment by jaredscheib** [comment]
https://github.com/influxdata/chronograf/releases/tag/1.3.6.1 has been published and fixes this issue. If this was an upgrade, unfortunately your graph types will have been lost. Let us know if you experience any other issues @siamaksalman, and thanks again!

**Comment by siamaksalman** [comment]
Thanks for your fast update, I've upgraded to this version and the singlestat worked well.
![screenshot from 2017-08-15 18-28-39](https://user-images.githubusercontent.com/5879053/29319000-98340996-81e7-11e7-8f80-a6c0d92d3059.png)
