### ISSUE TITLE
Long custom time range + small group by interval = broken graph x-axes

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1871]
Repro:
Set a custom time range to the past 2 months. Use a small (`10s`) or auto group by. Graph will only show 2 hours of data from the lower bound as a start date.

Somehow we need to indicate to the user that that their group by needs to be changed, if this is going to be broken. Or we can automatically change their group by to 1 day, or something like that, if they select a time range longer than 1 month.

Thoughts on what the UX should be here, @nhaugo?

<img width="1440" alt="screen shot 2017-08-14 at 3 44 34 pm" src="https://user-images.githubusercontent.com/6403018/29296482-797cb3be-810f-11e7-903c-c5b4b96d2c34.png">

**Comment by nhaugo** [comment]
@jaredscheib is this fixed with the updating of :interval:s
