### ISSUE TITLE
Display Options are squished on Safari

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1873]
Chronograf 1.3.6.x -- display options under cell editor overlay.

see image.

Safari: Version 10.1.2 (11603.3.8)
<img width="931" alt="screen shot 2017-08-14 at 6 27 18 pm" src="https://user-images.githubusercontent.com/23535264/29298728-b65dbf3a-811e-11e7-9156-d6b6a3f01a4a.png">

**Comment by jaredscheib** [comment]
Looks like the new SVG hotness isn't rendering @alexpaxton
