### ISSUE TITLE
Add ability to show a single graph in fullscreen mode

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1876]

**Comment by nhaugo** [comment]
Can't this be accomplished by putting a single cell on a dashboard and going into presentation mode? Any further info on the use case for this?

**Comment by salty-horse** [comment]
I'm also missing this feature.

My use-case is that I wish to zoom in on a particular graph for a quick detailed view.
I do not wish to create new dedicated dashboards for each one.
