### ISSUE TITLE
Maintain cursor pointer (hand) when moving over border between 'auto' and toggle on OptIn

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1877]
Follows on from #1858

It becomes an arrow where the hidden border would be, between `auto` and the groove knob.

See the first pass of this mouse movement:
![mouser_pointer_optin](https://user-images.githubusercontent.com/6403018/29899686-c2386d98-8da1-11e7-98d3-734b4c31e22a.gif)

**Comment by alexpaxton** [comment]
Took a stab at this and spent an hour trying different approaches, but ultimately ran into the same issue with different markup. Not sure what the solution is but I'm mostly out of hacky fixes. I theorize that having two adjacent children with matching cursor hover attributes within a parent that does not have hover styles creates the "gap".
