### ISSUE TITLE
Auto-save user database files for n number of releases

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1880]
It would be good to implement some approach that amounts to saving `n` number of database files, such as one for each of the past 5 releases. That way, if accidents happen and things break, or if the schema changes, or a user wants to use a previous version of Chronograf, they can restore and/or downgrade successfully.

This is specifically in light of the graph type bug in 1.3.6.0. Additionally, when I attempted to downgrade from 1.3.6.1 to 1.3.5.0, the server panicked because the schema had changed. There are a number of reasons why saving previous database files could be valuable.

**Comment by nhaugo** [comment]
The best approach now is for the user to save the boltdb file for backups

**Comment by russorat** [comment]
we have the backup file taken anytime there is a new version made, so i think we can close this
