### ISSUE TITLE
Pagerduty config error

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1888]
The problem is that the data being sent to kapacitor is `{"set":{"serviceKey":"asdf","url":"https://events.pagerduty.com/generic/2010-04-15/create_event.json","enabled":true}}` the actual format is `{"set":{"service-key":"asdf","url":"https://events.pagerduty.com/generic/2010-04-15/create_event.json","enabled":true}}` (difference is service-key vs serviceKey)

**Comment by 121watts** [comment]
@nhaugo ill take care of that today
