### ISSUE TITLE
"add kapacitor" button isn't properly centered

### ISSUE THREAD

**Issue by jademcgough** [influxdata/chronograf#1889]
<img width="387" alt="screen shot 2017-08-15 at 11 51 27 pm" src="https://user-images.githubusercontent.com/1147449/29350786-bc24de0c-8214-11e7-9f63-c753322bcf13.png">

**Comment by jademcgough** [comment]
Looks like the whole rightmost part of the dropdown is being truncated, which partially obscures icons.

<img width="311" alt="screen shot 2017-08-16 at 12 04 56 am" src="https://user-images.githubusercontent.com/1147449/29351186-90b65500-8216-11e7-9237-b3488e0fd5a1.png">

**Comment by jaredscheib** [comment]
@jademcgough Seems like this should have been fixed by https://github.com/influxdata/chronograf/pull/1773 – was this on the latest `master`? cc @alexpaxton

**Comment by jademcgough** [comment]
It's possible I was seeing stale styling, feel free to close if you can't
reproduce

**Comment by nhaugo** [comment]
@nhaugo to verify
