### ISSUE TITLE
Chronograf not saving Alert Rule of Type: Deadman

### ISSUE THREAD

**Issue by Bedasek** [influxdata/chronograf#1890]
I've already described the issue in Influxdata Community:
https://community.influxdata.com/t/chronograf-not-saving-alert-rule-of-type-deadman/1939

- All instances installed it using a pre-built packages (no self-builds from sources)
```
[foo@server ~]$ chronograf -v;service kapacitor version;cat /etc/redhat-release
2017/08/08 09:26:09 Chronograf 1.3.5.0 (git: 9e87035b7f9d8f1e78a77789d69ab4709a095f67)
Kapacitor 1.3.1 (git: master 3b5512f7276483326577907803167e4bb213c613)
CentOS release 6.8 (Final)
```

**Comment by quadriq** [comment]
I have the issue issue. I updated to chronograf 1.3.6 but it did not help.

I am assuming that the deadman rule is saved in kapacitor, I could see it with `kapacitor list tasks`. But it never triggered.

**Comment by quadriq** [comment]
I figured out that chronograf doesn;t create a correct query..  e.g. it does not write which value was used in a query. For example, if I would like to create a `deadman` on `cpu` measurement, looking at `usage_user` field... then if I create this in cronograf, the `usage_user` rule is missing in a tick script:

```
var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
```

so I added manually:

```
var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |mean('usage_user')
        .as('value')

```

then it worked.

**Comment by 121watts** [comment]
Hey all!  Thanks for writing in!  You all definitely uncovered a problem with out UI/UX.  

You see, the UX is lying to you.  

The Chronograf UI makes it appear that you can set a deadman rule for a specific `field`.  However, in Kapacitor this is not the case.  Kapacitor considers something dead if a `database`, `retentionPolicy`, and `measurement` have not reported over a specified time interval.  Put another way Kapacitor doesn't care about `fields` for a `deadman` trigger.  

So, we need to fix the UI for the `deadman` trigger specifically. 

Until then, you can still create `deadman` rules and they will work.  You just wont see a line graph.

**Comment by alexpaxton** [comment]
![screen shot 2017-09-05 at 8 24 03 pm](https://user-images.githubusercontent.com/2433762/30093232-d0fc28f2-9278-11e7-9902-eb426422f55c.png)

Here's a mockup of what the rule builder would look like with the suggested changes

I added some static markup into `KapacitorRule.js` above `<DataSection />`:
```
<div className="rule-section">
  <h3 className="rule-section--heading">Alert Type</h3>
  <div className="rule-section--body">
    <div className="rule-section--row rule-section--row-first rule-section--row-last">
      <p>Choose One:</p>
      <ul className="nav nav-tablist nav-tablist-sm nav-tablist-malachite">
        <li className="active">Threshold</li>
        <li>Relative</li>
        <li>Deadman</li>
      </ul>
    </div>
  </div>
</div>
```

`rule-section--row-first` and `.rule-section--row-last` simply round the top and bottom corners respectively. Designed to add on to `.rule-section--row`.

![screen shot 2017-09-05 at 8 34 28 pm](https://user-images.githubusercontent.com/2433762/30093365-aa0e0232-9279-11e7-8bd5-2e25e8930669.png)
this section needs `.rule-section--row-first` and `.rule-section--border-bottom` to appear properly
