### ISSUE TITLE
Use line stacked in mem.json ?

### ISSUE THREAD

**Issue by Joxit** [influxdata/chronograf#1892]
Why do not you use the lines stacked for memory? `"type": "line-stacked"`

https://github.com/influxdata/chronograf/blob/e2e684b5e24d789eb453c07dc4bf436616bc283a/canned/mem.json#L6-L22

This could be more meaningful given that used + available = total

**Comment by nhaugo** [comment]
@Joxit any interest in submitting a PR

**Comment by Joxit** [comment]
Done in #1933
