### ISSUE TITLE
Time picker is misaligned

### ISSUE THREAD

**Issue by danielnelson** [influxdata/chronograf#1901]
The time picker is slightly misaligned in firefox-45.8.0.

2017/08/18 02:34:47 Chronograf 1.3.6.1 (git: 07fade83a6360429cfd9d52bbce9cd59cdd42399)

![03](https://user-images.githubusercontent.com/1048079/29442238-2866b47a-8385-11e7-8792-2354d18e8322.png)

**Comment by alexpaxton** [comment]
Wonky!

**Comment by danielnelson** [comment]
Literally unusable

**Comment by alexpaxton** [comment]
@danielnelson your firefox is old, latest version is 55.0.3
Cannot reproduce in new firefox

**Comment by nhaugo** [comment]
Literally unreproducible

**Comment by danielnelson** [comment]
LOL, I'm using the ESR, and not even the latest one.  The latest ESR is version 52, which is what Debian Stretch was released with this spring and will probably be the one most Linux users have until 2019.

**Comment by russorat** [comment]
@danielnelson is this still an issue with the latest release?

**Comment by danielnelson** [comment]
Looks okay with Firefox 52 and 1.4.3.1
