### ISSUE TITLE
Can't delete role - Chronograf

### ISSUE THREAD

**Issue by pootzko** [influxdata/chronograf#1902]
Hi, this is an error I get in the Influx Cloud Chronograf when I try to remove a role or modify it's permisisons:

From dev tools:
```
index.js:933 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at _callee16$ (webpack:///./src/admin/actions/index.js?:933:111)
    at tryCatch (webpack:///./~/regenerator-runtime/runtime.js?:64:40)
    at Generator.invoke [as _invoke] (webpack:///./~/regenerator-runtime/runtime.js?:355:22)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./~/regenerator-runtime/runtime.js?:116:21)
    at step (webpack:///./~/babel-runtime/helpers/asyncToGenerator.js?:17:30)
    at eval (webpack:///./~/babel-runtime/helpers/asyncToGenerator.js?:28:13)
    at <anonymous>
```

![image](https://user-images.githubusercontent.com/535842/29451605-29ca91b2-83fb-11e7-9ef9-2a0373a079c1.png)

Which means I can't delete some roles, or modify permissions on some other ones.

Any hints?

Thanks :)

**Comment by pootzko** [comment]
Roles also can't be assigned to users, after selecting them and clicking "apply" and refreshing the page after that - user roles are not listed/assigned.

**Comment by jaredscheib** [comment]
Thanks for this detailed report, @pootzko!

**Comment by nhaugo** [comment]
This is currently not reproducible. I suspect this might be related to #1948 @pootzko can you try again after it is fixed

**Comment by pootzko** [comment]
Hi, I just tested this and I still can't remove the role. I'm not getting and console or api request errors, everything goes smooth but when I refresh the page, the roles I "deleted" are still there.

**Comment by karel-rehor** [comment]
I've been sniffing out chronograf to influx-meta communications with a proxy.  I also noticed this behavior. 
2018/03/13 14:12:23 Chronograf 1.2.0~n201803070832 (git: ca9713ed1f8b5e179d457f02ad8c991ecd06bc8c)

I'm unable to remove users from roles in chronograf, however it works with curl.
``` 
curl -v -d '{"action":"remove-users","role":{"name":"test-role","users":["tucnak"]}}' http://admin:changeit@ip-172-31-16-140.us-west-1.compute.internal:8091/role
```

To reproduce in the UI 

1. Open InfluxDBAdmin
1. Click on Users tab
1. Highlight a user
1. In the roles drop down Uncheck an existing role 
1. Click Apply in the drop down control

A notification appears "Failed to update user: No fields to Update" 
The Roles field holds the value 'none' for a couple of seconds and then the old role is returned.

**Comment by karel-rehor** [comment]
Note that when removing a user from role in the role tab, the removal works.  However, the InfluxDBAdmin page has to be reloaded manually in order for the change to appear in the UI. 

Also - The post body from this control is. 

```
{"action":"remove-permissions","role":{"name":"test-role","permissions":{"":null}}}
```
I was expecting something like the following to the `/role` endpoint. 
```
{"action":"remove-users","role":{"name":"test-role","users":["tucnak"]}}
```
In any event it works.  But the message is inconsistent.  Is this by design?

**Comment by russorat** [comment]
thanks for the update @karel-rehor and @pootzko . I am able to reproduce this bug in the latest build so we will add this to the next sprint.

**Comment by russorat** [comment]
love it!
