### ISSUE TITLE
Update repos with latest Chronograf packages

### ISSUE THREAD

**Issue by erimar77** [influxdata/chronograf#1903]
Hi, the current packages available for Chronograf via the InfluxDB repository are 1.3.4.0, can the latest version (1.3.6.1) be pushed out?  Thanks!

**Comment by jaredscheib** [comment]
Hi @erimar77, thanks for writing. Could you provide a link to the repo you'd like to see this update?

**Comment by erimar77** [comment]
Here you go:
https://repos.influxdata.com/ubuntu/pool/stable/c/chronograf/
