### ISSUE TITLE
Interval selection not working as expected

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1905]
Using the absolute time range selector and selecting the past year gives this query:
`SELECT mean("total") AS "mean_total" FROM "telegraf"."autogen"."processes" WHERE time > '2016-08-21T19:44:11.850Z' AND time < '2017-08-21T19:44:11.850Z' GROUP BY time(1s)`

The group by time should not be 1s

**Comment by nhaugo** [comment]
We also need to test this against very small time ranges, e.g. a 5 second window should drop into the ms range, this should be tested.

**Comment by jaredscheib** [comment]
May be related to https://github.com/influxdata/chronograf/issues/1871

**Comment by nhaugo** [comment]
@timraymond does this fix the large time scale problem, i'm getting reports of it not working with only two days worth of data.

**Comment by timraymond** [comment]
@nhaugo It should fix the large time scale problem. I'm not sure about small time ranges... we may need a separate investigation card to repro and fix it.

**Comment by nhaugo** [comment]
connect #1925
