### ISSUE TITLE
The API should support CRUDA operations for Chronograf users

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1907]
Get the information for a user which consists of 
Auth scheme
Provider
Org
Name

**Comment by jaredscheib** [comment]
Only admin and superadmin can do this.

**Comment by jaredscheib** [comment]
Let's remember to look at what fields can actually be updated on a User. As of right now, any field can, but it's likely that only Roles, Permissions, and possibly Username should be updateable by an Admin or Superadmin, or something like that.
