### ISSUE TITLE
The API should support CRUDA operations for Chronograf Organizations

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1909]
Teams are separate from oauth orgs in that they are a group of users and chronograf assets, orgs from oauth may map to these, but they are different resource.

No nesting/sub teams

**Comment by jaredscheib** [comment]
I believe this should say: `Chronograf Organizations are separate from OAuth organizations in that they are a group of users and Chronograf assets. OAuth Organizations may map to these, but they are a different resource and should be captured for now as metadata on the User`

cc @nhaugo

**Comment by jaredscheib** [comment]
And to be sure, can a user belong to multiple Chronograf Organizations?

**Comment by jaredscheib** [comment]
- [ ] disallow update OrganizationID on a role
