### ISSUE TITLE
The API should respect a user's role when performing CRUD operations

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1914]
Operations attempting to update, create or delete a data source should be forbidden for users with a viewer role type, or for users not part the Chronograf Organization

View should be read only
Editor, Admin and Superadmin are readwrite

**Comment by jaredscheib** [comment]
- [x] refactor /me to use Chronograf User service CRUD so that roundtrip can be demonstrated

**Comment by jaredscheib** [comment]
Changed this issue to be respecting CRUD operations for all Chronograf resources, which as of #2132 has been completed.

What remains is:
- [ ] w/r/t Organizations
- [ ] w/r/t Superadmin
