### ISSUE TITLE
Design for read only version of dashboard selection page

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1916]

**Comment by alexpaxton** [comment]
![screen shot 2017-08-28 at 10 38 16 am](https://user-images.githubusercontent.com/2433762/29785594-095ea6cc-8bdd-11e7-8e81-79e0b60b8b2f.png)

- [ ] Do not render `Create Dashboard` button
- [ ] Add " in [OrgName]" to table heading using current Organization's name
