### ISSUE TITLE
Design for read only version of dashboard view

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1917]

**Comment by alexpaxton** [comment]
![screen shot 2017-08-28 at 10 31 59 am](https://user-images.githubusercontent.com/2433762/29785379-35af955c-8bdc-11e7-98b4-71793729bb03.png)

**Do not render:**
- [ ] `Add Cell` button
- [ ] `Rename` button
- [ ] Cell context menu (caret) on each cell
- [ ] `Manage` button in Template Control Bar
- [ ] Disable cell resizing
- [ ] Disable cell dragging

**Comment by nhaugo** [comment]
There is still a button for create a new dashboard on an empty dashboard list screen

**Comment by jaredscheib** [comment]
This view will only be visible if you are _not_ a superadmin and only a Viewer – did you test it by having a different machine log into your superadmin version?

**Comment by jaredscheib** [comment]
Confirmed that this does show up incorrectly.
