### ISSUE TITLE
Single stat broken on fresh config

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1920]
• Start from empty chronograf-v1.db 
• Go to dashboards
• Create new dashboard
• Create line graph (maybe not required)
• Create second graph with single stat
• Notice single stat is 0

**Comment by jaredscheib** [comment]
Dupe of https://github.com/influxdata/chronograf/issues/1493

**Comment by nhaugo** [comment]
Closed in favor of #1493
