### ISSUE TITLE
Safari styles slightly bonkers

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1923]
- [ ] check out the left and right sides of the tabs for Queries and Display Options
- [ ] check out the right side of the OptIn component
- [ ] gradient effect of OptIn is messed up -- might be related to the previous one

<img width="1440" alt="screen shot 2017-08-22 at 4 36 39 pm" src="https://user-images.githubusercontent.com/6403018/29592316-289258ec-8758-11e7-9707-1b07a3466b2b.png">

**Comment by nhaugo** [comment]
@jaredscheib can you ensure that all issues listed were fixed in the PR

**Comment by jaredscheib** [comment]
yep, all three are resolved.

**Comment by jaredscheib** [comment]
by the PR.
