### ISSUE TITLE
[Feature Request] Allow user to plot bars over a specific tag and display one or more selected instants of time within each group of bars

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1924]
When I use a query similar to ``SELECT mean("temperature") AS "mean_temperature" FROM "gts-device-10000027"."autogen"."sensors.onewire" WHERE time > :dashboardTime: GROUP BY time(10m), "id"`` and select the visualization type "Bar", data is plotted over time and compares the sensors per instant of time.

![image](https://user-images.githubusercontent.com/1226918/29611497-ffb5f3a6-87fd-11e7-9425-3b2611941c44.png)

What I would like to be able to is plotting the bars over the id tag and compare specific selected instants of times within each group of bars.

![image](https://user-images.githubusercontent.com/1226918/29611512-0ca224f4-87fe-11e7-8b9d-a8deed0646c6.png)

**Comment by goller** [comment]
Hey @core-process , thanks for writing in ! That sounds cool... to be clear your x-axis is the sensor id and within a particular sensor id, time progresses left to right?

**Comment by core-process** [comment]
@goller yes! :-)

**Comment by core-process** [comment]
:-(
