### ISSUE TITLE
[Feature Request] Highlight active legend item

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1931]
In case the content of the legend exceeds a certain height, the legend becomes scrollable. When the user hovers over a particular data point the corresponding item in the legend is highlighted.

__Current behavior__: In case the highlighted item is not within the viewport of the legend, the user has to scroll manually to the particular item.

__Expected behavior__: The highlighted item should be visible automatically, e.g., by scrolling it into the viewport.

![screenshot at 2017-08-24 20-58-52](https://user-images.githubusercontent.com/1226918/29684008-b2af12f4-8910-11e7-9b35-f34aa3f75064.png)

**Comment by nhaugo** [comment]
This might create a jarring experience as the order could be quickly sorted and resorted. I'll leave this open to see if there is any other community input on it.

**Comment by jaredscheib** [comment]
The current idea is to create a special box/label just above all the other labels, such as with a border, that shows the currently highlighted line's label, so as to avoid the jarring/scrolling effect by having a fixed, stationary place to see what's being focused on.

**Comment by nhaugo** [comment]
Also highlight the series in the chart when hovering over the legend

**Comment by core-process** [comment]
:-(
