### ISSUE TITLE
Error contacting source influx remote

### ISSUE THREAD

**Issue by krysjoseoctanio** [influxdata/chronograf#1935]
From bash if I can connect with curl, but from the web always comes the error "Error contacting source"

Pre-built package installed : chronograf_1.3.7.0_amd64.deb

The operation system is ubuntu 16.04

![screenshot](https://user-images.githubusercontent.com/9655339/29751352-84e8e4d8-8b4c-11e7-8390-e1f948e61df6.png)
![screenshot1](https://user-images.githubusercontent.com/9655339/29751353-885060ba-8b4c-11e7-8c12-29fbf45e9b19.png)

**Comment by goller** [comment]
Hi @krysjoseoctanio , do you mind running chronograf with debug logs and sending it's server logs?

Here's how:

```sh
chronograf --log-level=debug
```

**Comment by krysjoseoctanio** [comment]
Hello, here the logs

Aug 29 12:07:13 n1016 chronograf[31768]: time="2017-08-29T12:07:13+02:00" level=info msg="Response: OK" code=200 component=server remote_addr="X.X.X.X:52775" response_time="49.91µs"
Aug 29 12:07:21 n1016 chronograf[31768]: time="2017-08-29T12:07:21+02:00" level=info msg=Request component=server method=POST remote_addr="x.X.x.x:52775" url=/chronograf/v1/sources
Aug 29 12:07:21 n1016 chronograf[31768]: time="2017-08-29T12:07:21+02:00" level=error msg="Error message Error contacting source" component=server http_status =400
Aug 29 12:07:21 n1016 chronograf[31768]: time="2017-08-29T12:07:21+02:00" level=info msg="Response: Bad Request" code=400 component=server remote_addr="1X.x.x.x:52775" response_time=1.361006ms
Aug 29 12:07:23 n1016 chronograf[31768]: time="2017-08-29T12:07:23+02:00" level=info msg=Request component=server method=GET remote_addr="x.x.x.x:52775" url=/chronograf/v1/me


The process:
 ps aux|grep chronograf
root      4811  0.0  0.0  16212  1016 ?        S+   12:14   0:00 grep --color=auto chronograf
chronog+ 31768  0.0  0.1 368528 13208 ?        Ssl  12:04   0:00 /usr/bin/chronograf --log-level=debug --host 0.0.0.0 --port 8888 -b /var/lib/chronograf/chronograf-v1.db -c /usr/share/chronograf/canned

**Comment by nhaugo** [comment]
Connect #1653, closing as dupe

**Comment by handrix** [comment]
my chronograf log like this:
time="2017-09-15T06:49:48Z" level=info msg="Response: OK" code=200 component=server remote_addr="172.17.0.1:47516" response_time="104.567µs"

you can input connection string like172.17.0.1:<influxdb port>, don't use localhost:<influxdb port>
