### ISSUE TITLE
A additional options to Y axis control configuration

### ISSUE THREAD

**Issue by SveLil** [influxdata/chronograf#1936]
As a user, I want to visualize three different values in the same graph to show correlation between them.
All three values have different scales, if put into the same graph, I currently would only get three straight lines.

For each query, I want to be able to assign it to the left or right Y axis or to no axis at all.

Example:
Left Y axis is temperature, min: -15°C max: 40°C
Right Y axis is humidity, min: 20% max 80%
No Y axis for pressure, min: 850 max 1100

**Comment by snenkov** [comment]
Why is this closed? Does such a feature exist already?

**Comment by bigFinCanntx** [comment]
BUMP

**Comment by bigFinCanntx** [comment]
> Why is this closed? Does such a feature exist already?

BUMP

**Comment by luismanson** [comment]
This is an used feature
