### ISSUE TITLE
[Issue/Feature Request] Chronograf horizontal scaling?

### ISSUE THREAD

**Issue by szibis** [influxdata/chronograf#1937]
As far as I know, Chronograf uses BoltDB as internal Database. 

From BoltDB doc we can read:
```
Bolt uses an exclusive write lock on the database file so it cannot be shared by multiple processes.
```

Is there any plans to scale this horizontal? I would like to integrate this on multiple instances on auto-scaling and forget about chronograf management, same as other web tools on this scaled instances. 

Why not add pluggable backends like mysql, redis, postgre or any other network accessible DB?

**Comment by nhaugo** [comment]
This has been discussed but is not in the current roadmap. We would likely accept a community submission for this if someone wanted to take a crack at it.

**Comment by Damoun** [comment]
Hi,

Since github.com/boltdb/bolt is not maintened anymore and in read-only mode, will you use the fork https://github.com/etcd-io/bbolt or move to another solution ?

Thanks

**Comment by russorat** [comment]
We are looking at ways to address this in a future release but don't have a concrete timeline. I will leave this open for others to comment on.

**Comment by nhaugo** [comment]
@Damoun we don't intend to leverage any additional functionality out of the key value store, so we actually prefer to use the version that isn't changing. We will stick with bolt unless a security vulnerability forces us to change.
