### ISSUE TITLE
As a user I can create, update, or delete an Organization

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1938]
- Only Super Admins can CRUD an organization

### Create Org

<img width="768" alt="screen shot 2017-08-28 at 10 54 34 am" src="https://user-images.githubusercontent.com/2433762/29786274-5d0829cc-8bdf-11e7-8271-9733ed866b75.png">

- Only Super Admins can see the `Create Organization` button inside the dropdown
- Clicking `Create Organization` button displays the Create Org modal
- After creating an org, that org becomes the "current" organization

![image](https://user-images.githubusercontent.com/2433762/29786818-79cae9f8-8be1-11e7-836a-53c4e272c559.png)

### Update Org

- Only the super admin can see the `Manage` button
- Clicking `Manage` opens the Manage Org Modal for the "current org"
- User can save changes or delete the org
- Deleting may need a second click to prevent accidental deletions

![image](https://user-images.githubusercontent.com/2433762/29786912-c177a160-8be1-11e7-8bf6-7a8f32d19735.png)

**Comment by jaredscheib** [comment]
It seems that between this and #1909, one of them is about basic CRUD operations for Chronograf Organizations, and the other is about implementing authorization based on a User's Role and Organization.

**Comment by jaredscheib** [comment]
TODO:
[ ] Add SuperAdmin as role type in backend
