### ISSUE TITLE
Refresh interval - Flip to Paused when selecting long time ranges

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1946]
When you flip to a time range which is greater than an hour, the refresh interval should automatically reset to PAUSED.   For large, complex dashboards, having it refresh over a longer time range is really something the user should be forced to request this because having a dashboard with a 30 day range shouldn't refresh every 15 secs.

**Comment by jaredscheib** [comment]
Thanks! @nhaugo had some thoughts on this.

**Comment by nhaugo** [comment]
I am still seeing issues with slow queries on some dashboards. Until we can fix those it is hard to come up with a best fit solution for this problem

**Comment by russorat** [comment]
this has been fixed
