### ISSUE TITLE
Chronograf reports an error when when trying to create a user/role on a meta node which is not currently the leader.

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1948]
It looks like the redirect to leader actually works, but the chronograf server reports a 400 back to the ui. Even though a new user/role is created.

To reproduce:
• Set up chronograf with a InfluxEnterprise backend
• Add a meta node which is not the leader
• Go to the admin panel
• Go to the user tab
• Create a user
• Get an error message
• Reload and go back to user tab
• Notice that user was actually created.

**Comment by jaredscheib** [comment]
Basically, Chronograf server needs to wait for redirect and issue a 200 when successful
