### ISSUE TITLE
Persistent 400 error in console around AutoRefresh

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1955]
I get this on repeat while using Chronograf:

<img width="1440" alt="screen shot 2017-08-30 at 6 13 13 pm" src="https://user-images.githubusercontent.com/6403018/29901809-fdd96f3e-8dae-11e7-98b5-14aa88b86c9a.png">

**Comment by 121watts** [comment]
@jaredscheib what query is from the status page is causing this specific 400.

**Comment by jaredscheib** [comment]
Just investigated this as well and it seems due to the current `fill` implementation work. I'll re-open if I find it persists on `master`.
