### ISSUE TITLE
Could not connect to Kapacitor. Check settings.

### ISSUE THREAD

**Issue by guiguan** [influxdata/chronograf#1959]
Followed official tutorials and spawned `chronograf`, `influxdb` and `kapacitor` as follows:

```
docker network create influxdb

docker run --name=influxdb --restart=always -d \
--net=influxdb \
-p 8086:8086 \
-v $PWD/influxdb/data:/var/lib/influxdb \
influxdb

docker run --name=chronograf --restart=always -d \
--net=influxdb \
-p 8889:8888 \
-v $PWD/chronograf/data:/var/lib/chronograf \
chronograf --influxdb-url=http://influxdb:8086

docker run --name=kapacitor --restart=always -d \
--net=influxdb \
-p 9092:9092 \
-h kapacitor \
-e KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086 \
-v $PWD/kapacitor/data:/var/lib/kapacitor \
kapacitor
```

Then feed `telegraf`'s demo cpu data into `influxdb` as follows:

```
brew install telegraf
telegraf -config /usr/local/etc/telegraf.conf
```

Then when tried to config `kapacitor` in `http://localhost:8889/sources/0/kapacitors/8/edit`, I got `Could not connect to Kapacitor. Check settings.` (See screenshot)
![screen shot 2017-09-03 at 5 04 36 pm](https://user-images.githubusercontent.com/940189/30001227-bd9ff040-90ca-11e7-8d92-67bed77da8aa.png)

Any idea?

**Comment by nhaugo** [comment]
In the kapacitor config in chronograf change "http://influxdb:9092" to "http://kapacitor:9092" you need to set the container name not the network name. If this doesn't work for you feel free to follow up on https://community.influxdata.com we try to keep GitHub to bugs and feature and questions on community, thanks.
