### ISSUE TITLE
[Feature Request] Timezone support in data exploration.

### ISSUE THREAD

**Issue by SamuelToh** [influxdata/chronograf#1960]
I have been looking through the documentation and also the user interface itself. I believe there is no way for me to ask Chronograf to display my influx data in **UTC**, it is currently displaying them as the machine time.

For people who are familiar with Grafana. You can actually do this in Grafana. See screenshot below.

![image](https://user-images.githubusercontent.com/8707446/30008340-041b73ae-9162-11e7-8c51-24621f237bdc.png)

**Comment by BlueArcherX** [comment]
^ Nice.  First day Influx user here and came looking for answers about time zones.  Can't wait.
