### ISSUE TITLE
Chart Line Colors Inconsistent

### ISSUE THREAD

**Issue by ByronAP** [influxdata/chronograf#1962]
When you create a dashboard using multiple graphs for multiple metrics across multiple hosts the line colors are inconsistent between the graphs (host-1 chart-1 = red, host-1 chart-2 = blue, hos-1 chart-3 = green) making it hard to easily distinguish hosts. We need a way to set the colors based on the line data set name so that host-1 (in this example ) is consistent.

**Comment by nhaugo** [comment]
See also https://github.com/influxdata/chronograf/issues/2058#issue-262115162

**Comment by Astraithious** [comment]
Would love to see this option as I have vastly superior flexibility with grafana using influxDB than I do with chronograf

**Comment by drolfe** [comment]
+1
