### ISSUE TITLE
Create "Super dashboards" 

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#1967]
This is probably heavily dependent on permissions and authorizations, but the idea is that as an administrator, I could create a variety of dashboards to give access to select information.

I could then aggregate some or all of those dashboards into "super dashboards".

Example:
I create dashboard X with access to CPU usage information and network throughput information.
I create dashboard Y with access to temperature sensor, light sensor data
I create dashboard Z with access to Humidity data, pressure data 

I can then create a Dashboard A that has Dashboard X and Z on it, rather than recreating those 2 dashboards inside Dashboard A. 
I could create Dashboard B with dashboards X, Y and Z on it for the "supervisory view".

Being able to create different aggregate views as Super Dashboards would be very helpful in creating custom dashboards for different types of users.

**Comment by lukevmorris** [comment]
Can super dashboards include super dashboards?

**Comment by davidgs** [comment]
I would like to say yes, but at some point you're going to run in to a problem with too many levels of inclusion/recursion. Keeping it simple (at first) probably points to only allowing Super Dashboards to include sub-dashboards and not other Super Dashboards. But that's just my $0.02

**Comment by nhaugo** [comment]
I feel like it would be easier to just copy an existing cell into the dashboard. Otherwise how would chronograf deal with spacing issues?

**Comment by alexpaxton** [comment]
@nhaugo yeah I concur, we'd have to find a way to resolve conflicting X&Y coords in a non-janky manner. Being able to copy from one dash to another sounds like a natural flow
