### ISSUE TITLE
Google Oauth with org doesn't allow for another attempt to login if logged in with wrong domain initially

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1970]
Steps to repro
• Set up google oauth with a domain
• Try to log in with good user/pass under a different domain
• Try to log in again

We should also verify github orgs and other providers work as expected
Also verify google oauth with domain works if the proper domain is used, but the incorrect username password

**Comment by timraymond** [comment]
@nhaugo Cannot reproduce following the above. I tried two accounts with different domains and it worked. Can you post the (redacted) flags/ENVs?
