### ISSUE TITLE
[Feature Request] Allow template variables in cell titles

### ISSUE THREAD

**Issue by n9986** [influxdata/chronograf#1973]
This could enable creating rich titles for cells based on the currently selected value for the template variable.

For example, if I have a temperature monitoring dashboard for various sources that I filter using a template variable called `:source:` I could also use it in a cell title like so:

```
Average temperature at :source:
```

So, if I select "Living Room" from the dropdown, the cell title can read: "Average temperature at Living Room"

**Comment by nhaugo** [comment]
See also #2108

**Comment by russorat** [comment]
broken in master

![kapture 2018-07-11 at 11 17 38](https://user-images.githubusercontent.com/4805997/42591641-1a58aac2-84fc-11e8-90de-f98cfab525b9.gif)

**Comment by russorat** [comment]
spoke to @ischolten and there is still a bug with empty values.
