### ISSUE TITLE
[Feature Request] Sort databases by name in DE

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1985]
Sort databases by name in Data Explorer to improve user experience.

![screenshot at 2017-09-10 19-08-35](https://user-images.githubusercontent.com/1226918/30251219-a183e9de-965b-11e7-9d9c-9c4608a8f6d0.png)

**Comment by jaredscheib** [comment]
Cool – thanks @core-process! Good idea. Sorting (and filtering) would probably be good for all query builder columns.

**Comment by core-process** [comment]
Awesome, thanks!

**Comment by seb-koch** [comment]
Does this include sorting the database drop down for the TICK scripts? If not i am happy to open a new FR.
![screen shot 2017-11-07 at 11 00 35](https://user-images.githubusercontent.com/19778637/32487796-f2426e50-c3aa-11e7-840f-92bdda733424.png)

**Comment by goller** [comment]
Hi @seb-koch , no, this doesn't include the dropdown for TICKscripts.  Do you mind creating another issue?
