### ISSUE TITLE
Fix unary operators in query parser

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#1987]
It seems Chronograf has an issue with unary operators and the location of spaces similar to one that was fixed for the CLI.
See: https://github.com/influxdata/influxdb/issues/8174

Example using Data Explorer:

    SELECT mean("usage_system") AS "mean_usage_system" 
    FROM "telegraf"."autogen"."cpu" 
    WHERE time > now() - 1h 
    GROUP BY time(10s)

AND

    SELECT mean("usage_system") AS "mean_usage_system" 
    FROM "telegraf"."autogen"."cpu" 
    WHERE time > now()-1h  
    GROUP BY time(10s)

AND

    SELECT mean("usage_system") AS "mean_usage_system"
    FROM "telegraf"."autogen"."cpu" 
    WHERE time > now()- 1h
    GROUP BY time(10s)

All Yield -- success!

However...

    SELECT mean("usage_system") AS "mean_usage_system" 
    FROM "telegraf"."autogen"."cpu" 
    WHERE time > now() -1h  
    GROUP BY time(10s)

Yields: 
```received status code 400 from server: err: error parsing query: found -1h, expected ; at line 1, char 103```

**Comment by russorat** [comment]
connect #3971
