### ISSUE TITLE
Query builder equality toggle not obvious 

### ISSUE THREAD

**Issue by rbetts** [influxdata/chronograf#1988]
In actuality: 

Luke taught me to find the "!=" button. I'll leave this open as clicking the "!=" button toggles to "=!" which is probably not intended. 

Original report:

When using the query builder to filter on a tag, after selecting the radio button for a tag, I'd expect the query builder to filter on equality -- instead it filters to exclude that tag from the query. 

I've attached a link to a video showing what I mean. I'd expect the result to be `"location" = 'FraminghamMA'`

Here's a screenshot: https://files.slack.com/files-pri/T02GAR81Y-F729G3YR4/screen_shot_2017-09-11_at_16.09.51.png

Here's a screencast: https://drive.google.com/open?id=0BzdseDrf_hRmOTd0SXJKdENDNHM

**Comment by jaredscheib** [comment]
Thanks, @rbetts!

This might be related to the recent Burning Ham.

**Comment by davidgs** [comment]
Not to pile on, but this bit me as well. Both the default to '!=' and then the odd '=!'. I think both are problematic.
