### ISSUE TITLE
Dashboards should be sorted lexicographically in dropdown

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#1991]
For the dashboard dropdown, located at the top left of the  `http://localhost:8888/sources/1/dashboards/x` page, it looks like dashboards are being sorted by their internal `"id"` rather than lexicographically.

<img width="441" alt="screen shot 2017-09-12 at 16 31 56" src="https://user-images.githubusercontent.com/501993/30334666-2da87812-97d8-11e7-8011-7e6646e8950c.png">

Notice the first dashboard (which has `"id"=1"`) should be further down the list.

**Comment by 121watts** [comment]
@e-dard this should be resolved by https://github.com/influxdata/chronograf/pull/2104
