### ISSUE TITLE
Chronograf endpoints for IoT

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#1993]
It would be hugely useful to add some alerting endpoints to Chronograf for services like Salesforce and ZenDesk, among others. 

Use case: set a deadman alert on a sensor that creates a trouble ticket in Salesforce or Zendesk so that when a sensor goes offline, a ticket is created in the system. Other higher level integrations with Salesforce would also be possible. IoT deployments are looking explicitly for analytics AND actions.

**Comment by nhaugo** [comment]
You can issue a webhook via an alert, I have seen that used for zendesk in the past.

**Comment by ebb-tide** [comment]
This would be a good issue to have documentation or a guide for.
