### ISSUE TITLE
Automatically cycle between dashboards (in presentation mode?)

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1995]
I can imagine a use case where you have a dashboard on display in your office. You have a few different dashboards that you care about. You might want them to cycle automatically, spending maybe 30 seconds on each.

Maybe we have a checkbox on the dashboard index to include a dashboard in this automatic cycle. Maybe the cycle only happens in presentation mode?

**Comment by pstatho** [comment]
+1 seems like the obvious next improvement for dashboards

**Comment by MaxDiOrio** [comment]
This.  We do this for Grafana, which has a built in playlist generator and let it rotate on our TV's.

Would be nice to have this and be able to pick the datasource.  So for example our Kubernetes clusters.  We have 6 clusters, and I want to cycle through the same dashboards for each cluster

The other thing that would be very important is having the datasource name (or Kubernetes cluster name) on the dashboard, so I know what I'm looking at.
