### ISSUE TITLE
Apostrophe in alert rule name prevents rule creation

### ISSUE THREAD

**Issue by erimar77** [influxdata/chronograf#1997]
Creating a new alert with an apostrophe in the name will prevent the rule from being saved.  

<img width="836" alt="apostrophe_chronograf" src="https://user-images.githubusercontent.com/6336162/30497323-0f5050fa-9a18-11e7-8aa2-7d7321e8c25e.png">

Chronograf Version: 1.3.7-0

**Comment by nhaugo** [comment]
Do we want to fix this or provide a better error message?

**Comment by nhaugo** [comment]
Kapacitor does not allow this, but we should provide a better error message.

**Comment by nhaugo** [comment]
I take it back, the backend panics on this. @goller any chance this is magically fixed in your incoming fixes?

**Comment by goller** [comment]
Hi @erimar77, fixed! 

It will be included in 1.3.11

**Comment by goller** [comment]
Hi @erimar77, fixed! 

It will be included in 1.3.11
