### ISSUE TITLE
Alert Rules save duplicates on error

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#1998]
If one goes to create an Alert Rule, creates a query, and selects, say, a threshold, and then fills in the log form, but uses a bad path (say, removing the root slash to make it not an absolute path), this results in duplicate Alert Rules being made, as many as when the save button is clicked.

I'm seeing this on 1.3.8.

**Comment by nhaugo** [comment]
@cryptoquick I cannot recreate this, are you still able to?

**Comment by cryptoquick** [comment]
@nhaugo yep, just tested it, it still happens.
