### ISSUE TITLE
Enterprise data sources should not have connection errors when the meta node address is empty

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2000]
Showing features or listing errors from Influx Enterprise should be driven by the a meta node existing in the source, not by the data source type. Thus if a meta node url is removed from a source it should be treated as though it was an OSS source.

**Comment by nhaugo** [comment]
block on reproduction

**Comment by 121watts** [comment]
Investigated a bit.  Looks like if I connect to an enterprise source via chronograf and do not supply the meta node, the chronograf server saves it as enterprise (which i think it should).  However, if I then startup an OSS at the same address the Chronograf server still thinks it's an Enterprise instance.

**Comment by nhaugo** [comment]
See also https://github.com/influxdata/chronograf/issues/2164

**Comment by nhaugo** [comment]
Add a checkbox to enable/disable connection to the meta node. In the source config screen show or hide the meta node box.

**Comment by nhaugo** [comment]
If the user does not add a meta node or they remove it, the front end should patch the source type to no longer be of type enterprise.

**Comment by 121watts** [comment]
@desa `PATCH` to sources with `metaUrl` as an emptyString

**Comment by goller** [comment]
@121watts I would love to see that field be an array rather than a string

**Comment by desa** [comment]
@goller @121watts Just opened the PR above which does both of the things that you have requested.
