### ISSUE TITLE
Add gauge graph option for dashboard cells

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2007]
For presentations of dashboards, a gauge graph and other such visualization types are powerful and would be a great addition to Chronograf.

<img width="242" alt="screen shot 2017-09-19 at 11 33 19 am" src="https://user-images.githubusercontent.com/6403018/30608813-5c3d6e2a-9d2e-11e7-8d15-5bcff345417e.png">

This was requested offline by a customer recently for use in presentations to upper management, for instance.

**Comment by nhaugo** [comment]
This will need settings for min and max and three levels of thresholds.
