### ISSUE TITLE
url field does not persist

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2009]
In the alert creation page, switching to another tab removes text entered in another tab, even if the rule has been saved with the entry values.
![url field does not persist even when rule saved](https://user-images.githubusercontent.com/10937678/30613790-2dcba376-9d3e-11e7-9ea2-adb23ac35e68.gif)

**Comment by jaredscheib** [comment]
Interesting catch. This may end up being addressed / related to https://github.com/influxdata/chronograf/issues/1769.

**Comment by jaredscheib** [comment]
It should should persist

**Comment by nhaugo** [comment]
It needs to b

**Comment by nhaugo** [comment]
Fixed by #1610
