### ISSUE TITLE
Legend gets in the way

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#2024]
The legend gets in the way, especially when the cell is near the bottom of the window.

![screen shot 2017-09-26 at 10 52 48](https://user-images.githubusercontent.com/501993/30854239-02a2874e-a2a9-11e7-8ddf-41932d7467ae.png)

I can't hover over series lines to see which series they belong to, because the legend it drawn over the top.

**Comment by nhaugo** [comment]
This is still a problem when the graph is at the bottom of the screen

**Comment by nhaugo** [comment]
![sadlegend](https://user-images.githubusercontent.com/1003269/30943368-6a783754-a3a5-11e7-86ba-66bd339713b3.gif)
