### ISSUE TITLE
Missing empty alert rule `Create Alert Rule` state

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2025]
When you navigate to `Alert Rules` at http://localhost:8888/sources/{id}/alert-rules, the empty state (when there are 0 alert rules) should show the conventional blue button for `Create alert rule`.

**Comment by nhaugo** [comment]
@jaredscheib don't see what is missing here, there is a blue build rule button.

**Comment by jaredscheib** [comment]
Yes, but in every other table in the app we have two in these scenarios. That way the table doesn't look cut off, and instead it contains an extra blue button that would in this case say `Create a rule` and have some accompanying text that says "Looks like you haven't created any rules yet. Want to try creating one?" or something to that effect. @alexpaxton will know what I'm talking about.

**Comment by nhaugo** [comment]
I see, so the button in the middle. Unfortunately this now makes less sense with the split rules vs scripts section of the create screen. Also I suspect this will all change with #2074
