### ISSUE TITLE
Unclear how to edit an alert rule

### ISSUE THREAD

**Issue by markherring** [influxdata/chronograf#2027]
Clicking on the name it isn't clear that this opens an edit window. 

Idea: Would be great to have a button that says edit.

**Comment by jaredscheib** [comment]
Totally agreed -- good catch, @markherring! Thanks.

**Comment by nhaugo** [comment]
Not sure I agree, the current way is consistent with dashboards and data sources. @alexpaxton thoughts?

**Comment by alexpaxton** [comment]
We used to have a more explicit `Edit` button and when I switched to the "Click the name of the thing to edit" paradigm it didn't cause any problems. This would be the first instance of an issue with the paradigm and it has been in place for a while, so I am thinking leave it alone until we put time into user testing it or hear more feedback from other sources
