### ISSUE TITLE
Link to alert rule from alert history page

### ISSUE THREAD

**Issue by lvierengel** [influxdata/chronograf#2028]
It would be supes cool if I could click into my alert rule from this page instead of going back to the Alert Rule Index. 

<img width="1217" alt="screen shot 2017-09-26 at 1 52 27 pm" src="https://user-images.githubusercontent.com/12039058/30883785-3411ceca-a2c2-11e7-8956-edf83894fb68.png">

**Comment by jaredscheib** [comment]
Great idea @lvierengel -- thanks!

**Comment by nhaugo** [comment]
Add kapa id to rule output.
Deal with case where it isn't present
Add link where we have the task id

**Comment by ebb-tide** [comment]
started work in feature/alert-history-links

**Comment by russorat** [comment]
- [ ] discuss/document edge cases
 - [ ] break into smaller issues
