### ISSUE TITLE
As a new user, it's unclear that query is being built in Data Explorer and other query builders

### ISSUE THREAD

**Issue by chrisoulam** [influxdata/chronograf#2030]
Nothing happens as you build query until its fully qualified

<img width="1680" alt="screen shot 2017-09-26 at 2 00 38 pm" src="https://user-images.githubusercontent.com/32312260/30884104-35d5e538-a2c3-11e7-8973-127cd114fe77.png">

**Comment by lukevmorris** [comment]
THIS IS AN EXCELLENT POINT

**Comment by jaredscheib** [comment]
Great point, @chrisoulam -- thanks for opening an issue!
