### ISSUE TITLE
Inconsistent visual UI for toggling Group by Measurement name

### ISSUE THREAD

**Issue by melinamurray** [influxdata/chronograf#2031]
When selecting Group by Measurement in Alert Rule Builder, the button turns green when toggled. However, in Data Explorer and Dashboard, the same action just changes the shade of grey. It was unclear to me whether or not I had successfully toggled that Group by.
<img width="1266" alt="screen shot 2017-09-26 at 3 09 23 pm" src="https://user-images.githubusercontent.com/32313305/30886836-7f63eb5a-a2cd-11e7-9b95-edba2dd92fd5.png">
<img width="1245" alt="screen shot 2017-09-26 at 3 09 15 pm" src="https://user-images.githubusercontent.com/32313305/30886913-fb4606f4-a2cd-11e7-8c73-1194c5a7bb22.png">

**Comment by jaredscheib** [comment]
Great point @melinamurray -- thank you!
