### ISSUE TITLE
Unclear whether alert rule is saved when clicking Save Rule

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2034]
In working with a new user to Chronograf just now, they were unclear whether their alert rule had saved when they clicked Save Rule.

Maybe make button grey, in addition to notification? Only enable the button when there are changes? Or take user back to list of alert rules?

The Connect/Update to sources buttons could possibly also use something like that to more clearly indicate that they've been triggered and successful.

**Comment by nhaugo** [comment]
@alexpaxton can we revisit the save button and rule naming, more often than not i end up making a rule called "Untiled rule". Also "Save" should probably take you back to the rule selection screen for consistency with the rest of the app.

**Comment by alexpaxton** [comment]
This page has its own naming/saving paradigm for unknown reasons. Seems like this can be broken down into a few different pieces:

- The click to name component is not obvious enough / not used elsewhere. Probably should follow the same pattern as the dashboard (click `Rename` to enter name edit mode) or try a different solution
- I'm assuming the confusion over the save button comes from unexpected behavior. @nhaugo I agree we should have it return you to the index view, as that seems expected.
- Only enable when there are changes -- this is a good move. Makes it more clear
