### ISSUE TITLE
Message component in Rule Builder unclear as to what it's for

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2035]
In walking a new Chronograf user through the app, they found that the message component in Rule Builder was not clearly a text input, and that it was unclear that it should be used for adding a message for your alert rule.

Maybe add instructions to Rule Builder experience?

**Comment by nhaugo** [comment]
Agreed, the background of the text edit does is not different from non editable fields.

**Comment by alexpaxton** [comment]
I think the message field deviates from the editable field UI pattern too much. I think the easy fix would be to re-style it to look more like other editable fields. If that doesn't work out we might need clearer contextual cues

**Comment by jaredscheib** [comment]
Agreed with that approach @alexpaxton. And what if it contained instructional placeholder text like `Add a message to your alert here...`?
