### ISSUE TITLE
As a new user, it's unclear what are Tags within query builder

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2036]
Database, Measurement, and Field have explicit labels, but Tags don't. And yet Tags are referred to throughout the rest of the Chronograf app. It's unclear what those "sub-measurement" togglables are.
<img width="1281" alt="screen shot 2017-09-26 at 6 37 56 pm" src="https://user-images.githubusercontent.com/6403018/30891766-df47fba8-a2e9-11e7-9829-e21e323e5873.png">

**Comment by nhaugo** [comment]
This feels like a documentation issue. Most users I have talked to get and like the location of tags in the query builder.

**Comment by nhaugo** [comment]
@jaredscheib I wouldn't mind discussing further, but I don't understand the course of action to take so I am going to close, but feel free to keep the conversation going.

**Comment by jaredscheib** [comment]
Basically, the word `Tag` or `Tags` is nowhere to be found in the UI, and I think it would be good for self-documenting purposes to have that word associated with the Tags in the UI somehow. Then new users (and users in general) can explicitly know that the things they are selecting (which I would otherwise think of as `sub-measurements` possibly), are actually Tags.

I think the location and UI are good, so no changes suggested there.

For example, the placeholder text that currently says `Filter within cpu` in the above image, could say `Filter within cpu Tags`. May not be the best solution – I'm sure we could come up with others – but that should concretely communicate what I mean. The word `Tag` or `Tags` is nowhere to be found in the UI.

Context:
A new user I was working with didn't understand what the sub-measurement units were, and since Tag is a concept at the level of Database, Measurement, and Field, it seems like it would be useful to provide an explicit label in the UI somehow, to help clarify what the concept of those things are in the builder, without having to refer to documentation.
