### ISSUE TITLE
As a new user, it's unclear that you can scroll up and down within DBRP, Field, and Measurement in the query builder

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2037]

**Comment by nhaugo** [comment]
@jaredscheib i don't know what this means. What section of the app?

**Comment by nhaugo** [comment]
@alexpaxton should we show the scroll bar when scrollable? The scrollbar shows up when you start scrolling.

**Comment by alexpaxton** [comment]
I have the scrollbars set to auto-hide, so I can see what it may not be immediately obvious to a new user. My impression is that this is not a show stopper or else we'd be hearing a lot more about it. That being said, the decision to auto-hide assumed that users understood scrolling well enough without the visual cue. I can turn off auto-hide to make this clearer

**Comment by jaredscheib** [comment]
For what it's worth, I've heard this from two different new users so far. I agree that it would be particularly useful to get some UX research/testing going to really confirm whether this is the case for most users. Maybe some other visual indication that there are more items to be scrolled to, could be useful, if not showing the scrollbars?
