### ISSUE TITLE
Persist time ranges with a dashboard

### ISSUE THREAD

**Issue by rbetts** [influxdata/chronograf#2038]
I open the same dashboard a couple of times a day; I reset the time range from the default of `past hour` to my desired setting `7 days` each time.  I'd prefer that chronograf remember this configuration for me.

<img width="800" alt="screen shot 2017-09-27 at 12 31 03" src="https://user-images.githubusercontent.com/158141/30925426-d2c4250a-a37f-11e7-8380-d9d851817319.png">

**Comment by nhaugo** [comment]
Needs to be remembered by dashboard
