### ISSUE TITLE
Hoverline line should always find the nearest point

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2039]
The user should not need to be hovering over the actual line for the graph to select the point, it should be visible on the nearest line to the cursor.
![sadscroll](https://user-images.githubusercontent.com/1003269/30926738-018a89f2-a36b-11e7-855a-f10d497fee39.gif)

**Comment by nhaugo** [comment]
@121watts can you show me the behavior with the old code for this, or go over the odd behavior it caused.

**Comment by 121watts** [comment]
@nhaugo for sure.  We can go over it.  The old code is: 

https://github.com/influxdata/chronograf/blob/d7ae615e37168b2fbc8a339dd31d74a8f6d33724/ui/src/external/dygraph.js

And we are currently using this logic:

https://github.com/danvk/dygraphs/blob/64f1c4dfd7425931fcd1bd9949157c0ba6958656/src/dygraph.js#L1503
