### ISSUE TITLE
SHA256 hash/checksum of Windows binary does not match that published.

### ISSUE THREAD

**Issue by i-am-david-fernandez** [influxdata/chronograf#2048]
The `SHA256` hash of the Windows binary of version 1.3.8.2 (available at https://dl.influxdata.com/chronograf/releases/chronograf-1.3.8.2_windows_amd64.zip from both the [GitHub](https://github.com/influxdata/chronograf/releases) and the [InfluxCloud](https://portal.influxdata.com/downloads) pages does not match the hash of the downloaded zip file (at least, not for me):
  - Expected: `f97fca5e8a96003233ed624e1ddf5a1c1be528c9b49441a91cab067f44763cc5`
  - Calculated: `1237366f2cf439985a7e12ae805efa21453d6c24b647c8afe19335d59101f5d1`

I was alerted when my download manager reported that its check failed, and I have tried with a variety of other tools (Cygwin commandline tool and a shell extension) to confirm, and all give the same `SHA256`. I have tried re-downloading a number of times through different means (first repeating with my download manager and then with Cygwin wget) with the same results each time.

As you can perhaps understand, I refuse to use this release while it does not pass this fundamental integrity check.

On a separate but peripherally-related note, it would be nice if all the Influx tool downloads used/published the same hash method (there's currently a mix of `SHA256` and `MD5`; `SHA256` would presumably be preferred by most).

**Comment by nhaugo** [comment]
Thanks for the heads up @i-am-david-fernandez we reran the CI build for the release which changed the fpm date. We have updated the shas
