### ISSUE TITLE
Source indicator should state port to differentiate multiple sources on same host

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2056]
As mentioned in #1996, the source indicator does not give the port, only the host. So if I have two InfluxDB sources running on localhost, for example, it is not clear which one I am currently connected to.

**Comment by lukevmorris** [comment]
@jaredscheib this has been open since 1996?

**Comment by jaredscheib** [comment]
Al Gore actually filed the issue via Dot Matrix printer connected to a tube.
