### ISSUE TITLE
Possibility to change the colors of chart lines

### ISSUE THREAD

**Issue by tstaals** [influxdata/chronograf#2058]
Possible a duplicate of #1962 but im not completly sure.

At this point, most of my graphs have the same color unless I change chart types, in my particular case all data is based on data collected from the mqtt consumer.

I would be nice, to have the option to select the color for the charts lines, so I can better visualize them.

**Comment by nhaugo** [comment]
Hi @tstaals,
They are close enough that I am going to link your comment into the other issue and close this as a dupe. You should give it a thumbs up to help us prioritize.

Thanks
