### ISSUE TITLE
Change formatRPDuration() to handle weeks and months

### ISSUE THREAD

**Issue by 121watts** [influxdata/chronograf#2059]
With this change to the backend:
https://github.com/influxdata/influxdb/pull/8840/files

We need to modify this function: 
https://github.com/influxdata/chronograf/blob/ebefee271158fc96c7ba51335e0cd93f444631e2/ui/src/utils/formatting.js#L129

To return if no regex match is made on the duration

**Comment by nhaugo** [comment]
@121watts what is the effect of this?
