### ISSUE TITLE
Generic OAuth: Confusing Documentation

### ISSUE THREAD

**Issue by jcmcken** [influxdata/chronograf#2065]
The generic OAuth provider documentation states:

```text
The generic OAuth2 provider is very similar to the Github provider, but, you are able to set your own authentication, token, and API URLs. The callback URL path will be /oauth/generic/callback. So, if your Chronograf is hosted at https://localhost:8888 then the full callback URL would be https://localhost:8888/oauth/generic/callback.
```

This isn't actually true if you set ``GENERIC_NAME``, in which case the callback URL includes the generic name in the URL ([cf](https://github.com/influxdata/chronograf/blob/8a0498162817b1850d05fe5c2a9032828a10b98e/server/server.go#L218)).

**Comment by stevebang** [comment]
Fixing this in the Chrono 1.4 docs -- unfortunately, this also frustrated @trucaliber in https://github.com/influxdata/docs.influxdata.com/issues/1365.

**Comment by stevebang** [comment]
Also, found that @austinbutler encountered this issue, based on his posting in the InfluxData community (https://community.influxdata.com/t/oauth-with-internal-only-domain/1376).

**Comment by russorat** [comment]
connect #2509 #2677

**Comment by russorat** [comment]
This issue was moved to influxdata/docs.influxdata.com#1384
