### ISSUE TITLE
As a User I can see Kapacitor Logs

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2073]
- [ ] Add "Logs" button to each item in index view (Opens TICKscript editor with logs visible)

![image](https://user-images.githubusercontent.com/2433762/31154520-7de4c8c8-a85c-11e7-92ef-c4f793044319.png)

- [x] Add toggle in page header of editor to show/hide logs
- [x] When toggled, show logs in lower half of page with resizer
- [ ] Move `Batch/Stream` toggle and `Database` dropdown into top half (aka editor half)
- [ ] Replace `Save` with `Save & Exit` and `Validate TICKscript`
  - These both effectively save the TICKscript
  - Hence the name, `Save & Exit` takes you back to the index view
  - `Validate TICKscript` saves (causing validation to happen) and doesn't exit the page
  - Disable save buttons unless changes have been made since last save
- [ ] Logs table is filterable
- [ ] Logs table has sortable headers
- [ ] If logs are visible and there are unsaved changes, show and indicator of this state and tell the user they need to save to see updated logs
- [ ] If a user edits a `Builder Rule` via the TICKscript editor, show a flash message that reads "Depending on your changes you may not be able to edit this TICKscript using the Builder"

![image](https://user-images.githubusercontent.com/2433762/31154671-89971d1e-a85d-11e7-97fe-985a86e6cc5c.png)

**Comment by alexpaxton** [comment]
I have a pretty fleshed out branch for this issue. Been working from a dummy JSON file Michael sent me from his kapacitor logs. I need help writing the code to get real kapacitor logs, the reducer, etc. UI needs a little more polish but I want to see it with actual content before making any more changes

**Comment by nhaugo** [comment]
• No such task ID state
• Display for empty state
• When do purge from the dom
• Axios does not handle chunked http, do we buffer in the chronograf backend and poll that, or find a different javascript lib for chunked http.

**Comment by nhaugo** [comment]
Check the kapacitor version connected to a source and warn the user in the logging section if not 1.4 >

**Comment by nhaugo** [comment]
I get 403 errors from the proxy when oauth is turned on

**Comment by cryptoquick** [comment]
Confirmed, TICKScript logging doesn't work with OAuth turned on.
An error is returned from Chronograf proxy:
```ERRO[0035] Invalid principal                             component=auth method=GET remote_addr=[::1]:56288 url=/chronograf/v1/sources/1/kapacitors/1/proxy?path=/kapacitor/v1preview/logs?task=chronograf-v1-428661e5-8c31-4588-812e-0ce6c2efda09```

**Comment by cryptoquick** [comment]
No `set-cookie` header on the request. Will get a frontend fix for that ASAP.
