### ISSUE TITLE
FreeBSD Support ?

### ISSUE THREAD

**Issue by Onepamopa** [influxdata/chronograf#2081]
Will there be FreeBSD support?

I tried building but got the following:
cd ui && yarn --no-progress --no-emoji
yarn install v1.1.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.15: The platform "freebsd" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@skidding/react-codemirror@1.0.1" has incorrect peer dependency "react@>=15.5 <16".
warning "@skidding/react-codemirror@1.0.1" has incorrect peer dependency "react-dom@>=15.5 <16".
warning "react-codemirror@1.0.0" has incorrect peer dependency "react@>=15.5 <16".
warning "react-codemirror@1.0.0" has incorrect peer dependency "react-dom@>=15.5 <16".
warning "sass-loader@3.2.3" has incorrect peer dependency "node-sass@^3.4.2".
[4/4] Building fresh packages...
error /root/chronograf/ui/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /root/chronograf/ui/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Unexpected platform or architecture: freebsd/x64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
gmake: *** [Makefile:83: .jsdep] Error 1

**Comment by nhaugo** [comment]
We have no plans on doing official FreeBSD builds, but it looks like you might be able to install the phantomjs port https://svnweb.freebsd.org/ports/head/lang/phantomjs/

Some more info on phantomjs and freebsd
https://stackoverflow.com/questions/35228267/freebsd-phantomjs-installation-issue

If this doesn't work for you would you mind taking the issue to https://community.influxdata.com/

I'd like to see if this will work, but I like to keep general questions off of github.

Thanks

**Comment by Onepamopa** [comment]
So you removed the old administration "panel" and didn't provide the new one for FreeBSD.
At least make the old one available, since you don't plan to provide chronograf for FreeBSD....

**Comment by fntlnz** [comment]
@Onepamopa The problem you are having is only related to compiling chronograf on FreeBSD as I can see. Not strictly because of Chronograf's code but because of some compile time dependencies used to build assets, so as long as you don't build assets on FreeBSD you are fine. 

Here's what I get on FreeBSD using a chronograf binary with assets built on linux.

![image](https://user-images.githubusercontent.com/3083633/45329774-5e668680-b562-11e8-824c-376319715243.png)
