### ISSUE TITLE
Copy for creating new retention policy creates bad RPs

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2089]
Retention polices cannot be less than an hour right now.  The copy shows it can be 5 minutes.
Additionally, if a bad value is placed into the field the response is says it cannot reach the server, but, in reality it is a bad value for the duration.

![badrp](https://user-images.githubusercontent.com/1922921/31349138-97e0d85e-ace7-11e7-840e-5aaa9b1db203.gif)

**Comment by nhaugo** [comment]
This only happens on create, a proper error message is shown on edit.

**Comment by nhaugo** [comment]
We should not allow less than one hour
