### ISSUE TITLE
Clicking on Update Alerta Config with no values seems to break DOM

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2091]
I added a new kapacitor then clicked on the Update Alerta Config button with no fields. I get these errors:

![image](https://user-images.githubusercontent.com/1922921/31349330-69a8f92a-ace8-11e7-8bd4-4713de077ab3.png)

**Comment by 121watts** [comment]
We should prevent endpoint editing and creation if a required field is not supplied.  Need to do this check for all endpoints.

**Comment by nhaugo** [comment]
@nhaugo to get list of required values
