### ISSUE TITLE
Errors when selecting log scale

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2094]
I selected log scale for a graph that only had one point and I'm getting this error message over and over in the console:

![image](https://user-images.githubusercontent.com/1922921/31349770-429d8f9c-acea-11e7-86c5-b9233ca4bb60.png)

![image](https://user-images.githubusercontent.com/1922921/31349789-596c2e54-acea-11e7-8849-7ae91456ecc4.png)

**Comment by nhaugo** [comment]
Don't calculate range on log scale + 1 point
