### ISSUE TITLE
Extend UsersStore to more efficiently retrieve a User by username & provider

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2100]
As part of #1914, we refactored `/me` to use a UsersStore.All to get all users and then iterate over them to find the matching `me`. However, this was simply to ensure that the app still worked, and for the API to actually function. But it is a very inefficient way to retrieve the user.

We should refactor the retrieval of a user into something much more efficient. One possibility is to store the user with a key of `scheme:provider:username`.

**Comment by jaredscheib** [comment]
As of #2132, this was partly completed. The part that remains is:
- [ ] introduce some kind of cache that maps a user's name + provider + scheme to its ID for constant time lookup.

**Comment by desa** [comment]
After a user goes through an auth flow, we redirect them to /me where we do a find or create on their user record based on their name, auth provider, and auth scheme.

This find or create looks up a user by iterating through the list of users until it finds one who’s name, provider, and scheme matches. As you can imagine, this is a rather slow operation as the number of users increases.

The task we have is to add an index/cache for efficiently looking these users up.
