### ISSUE TITLE
Auto-Refresh & GroupByTime default value

### ISSUE THREAD

**Issue by lipoteFR** [influxdata/chronograf#2101]
Bonjour,

J'aimerai pouvoir mettre par defaut les valeurs ci dessous dans le "DataExplorer" :
    auto-refresh:OFF 
    time-range : 6h
    group by : 10m 
Where can i tune default values for DataExplorer tab ?
Merci
Léo

**Comment by nhaugo** [comment]
Auto refresh and persisted time range was handled by #2038 which is part of 1.3.10. I'll check on adding group by persistence.
