### ISSUE TITLE
As a user I can create comparative queries

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2102]
The user should be able to select a query and see the same query for some other time frame overlaid on the same x axis.

**Comment by alexpaxton** [comment]
Thinking about adding back in a 4th column to the Query Builder for "query options". Might be aiming too far in the future and this area will feel empty until we add more options.

Here's a rough mockup:
![screen shot 2017-10-12 at 5 17 34 pm](https://user-images.githubusercontent.com/2433762/31524913-8308d788-af71-11e7-9ac8-77b8aff78eea.png)

See how it fits in the whole builder:
![screen shot 2017-10-12 at 5 17 27 pm](https://user-images.githubusercontent.com/2433762/31524919-8d4788e8-af71-11e7-8bed-79ed4433db1a.png)

Not sure what options should be in the dropdown, I figure we have some standard options then as users request more fine grained control we can add that in. 

@nhaugo whatcha think?

**Comment by nhaugo** [comment]
@alexpaxton to create a mock with Timeshift, GroupBy, Fill and source in a single panel
