### ISSUE TITLE
Add support for Gitlab as an OAuth Provider

### ISSUE THREAD

**Issue by elleryq** [influxdata/chronograf#2106]
I had tried via generic OAuth 2.0 provider support, but I cannot make it succeeded.

Gitlab OAuth documentation: https://docs.gitlab.com/ce/api/oauth2.html

----

Here are my trying steps:

1. Add applicatoin in gitlab admin area.  Copy "applicatoin id" and "secret" as GENERIC_CLIENT_ID/GENERIC_CLIENT_SECRET.
2. Fill GENERIC_AUTH_URL/GENERIC_TOKEN_URL/GENERIC_SCOPES/TOKEN_SECRET:
  - GENERIC_AUTH_URL=http://gitlab_server/oauth/authorize?redirect_uri=http%3A%2F%2Fchronograf_server%3A8888%2Foauth%2Fgeneric%2Fcallback&response_type=code
  - GENERIC_TOKEN_URL=http://gitlab_server/oauth/token?redirect_uri=http%3A%2F%2Fchronograf_server%3A8888%2Foauth%2Fgeneric%2Fcallback&grant_type=authorization_code
  - GENERIC_SCOPES=read_user,api
  - TOKEN_SECRET=mysupersecret
3. Launch chronograf, click "Login with Generic" in browser.  Browser will redirect to gitlab login page.  After logined, it redirect back to chronograf login page.

----

Chronograf log

```
chronograf_1     | time="2017-10-11T08:09:49Z" level=error msg="Unable to get principal identifier Get : unsupported protocol scheme \"\"" component=auth method=GET remote_addr="192.168.9.2:42396" url=/oauth/generic/callback?code=the_code&state=the_state
...
chronograf_1     | time="2017-10-11T08:09:49Z" level=error msg="Invalid principal" component=auth method=GET remote_addr="192.168.9.2:42396" url=/chronograf/v1/me
```

**Comment by elleryq** [comment]
I still get the same error.

**Comment by russorat** [comment]
@elleryq we made some changes in 1.4.3 which included updating the OAuth lib we were using in order to support Okta. Could you try configuring this again with the latest version to see if it works?

**Comment by elleryq** [comment]
@russorat It works now.

The following is my steps
1. Add applicatoin in gitlab admin area. Fill callback url with "http://your_chronograf_server:8888/oauth/generic/callback".  After added, copy "applicatoin id" and "secret" as "--generic-client-id <application id>" / "--generic-client-secret <secret>".
2. Set these arguments:
  * --generic-auth-url=http://gitlab_server/oauth/authorize?redirect_uri=http%3A%2F%2Fchronograf_server%3A8888%2Foauth%2Fgeneric%2Fcallback&response_type=code
  * --generic-token-url=http://gitlab_server/oauth/token?redirect_uri=http%3A%2F%2Fchronograf_server%3A8888%2Foauth%2Fgeneric%2Fcallback&grant_type=authorization_code
  * --generic-scopes=api
  * --token-secret=mysupersecret
  * --generic-api-url=http://gitlab_server/api/v3/user
3. Launch chronograf, click "Login with Generic" in browser. Browser will redirect to gitlab login page. After logined, it redirect back to chronograf purgatory page.

But how to make oauth users enter main screen?

**Comment by russorat** [comment]
@elleryq thanks for verifying. to get out of the purgatory page, you will need to add the user's email to the org and set them to have something other than member permissions. You can follow the instructions on this page https://docs.influxdata.com/chronograf/v1.5/administration/managing-chronograf-users/
