### ISSUE TITLE
No hover position circles on when hovering graphs on second row of a dashboard

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2109]
In the below gif you will see hover position circles over the top two graphs, but when the lower graph is hovered it has no hover circles, however, the top graphs still do.
![sadballs](https://user-images.githubusercontent.com/1003269/31473105-43c89010-aea7-11e7-876d-b1caad106ddc.gif)

**Comment by 121watts** [comment]
@nhaugo cannot reproduce on my machine:

![kapture 2017-10-24 at 14 52 45](https://user-images.githubusercontent.com/7582765/31969869-0b5e7e32-b8cb-11e7-8f71-ea475b4cffb3.gif)

**Comment by 121watts** [comment]
@nhaugo i cannot repro on my machine

**Comment by goller** [comment]
@121watts I reproduced this.  To see this you need to have the graph near the bottom, the legend will flip to the top of the graph... at that point there is no dot.
