### ISSUE TITLE
add an env variable to control log level

### ISSUE THREAD

**Issue by chenlei123** [influxdata/chronograf#2115]
Hi,
     I found there is no method to control the log level, is there any way to control log level with env

**Comment by jaredscheib** [comment]
Hi @chenlei123,

I believe you're looking for the env var `LOG_LEVEL`, or `--log-level`/`-l` via as a runtime flag. Valid options are `debug`, `info`, and `error.

You can see this by running `./chronograf --help`: `-l, --log-level=choice[debug|info|error]    Set the logging level (default: info) [$LOG_LEVEL]`.
