### ISSUE TITLE
Client posting system metrics, put host appears down

### ISSUE THREAD

**Issue by BnMcG** [influxdata/chronograf#2118]
Hi,

I'm experimenting with the TICK stack on docker at the moment, and enjoying it so far! The only snag I've run into is that I can see a list of hosts:

<img width="1143" alt="screen shot 2017-10-15 at 10 41 17" src="https://user-images.githubusercontent.com/2544180/31583519-65da337a-b195-11e7-8201-76c355a83e7f.png">

But they appear down, even when I know this is not the case. What is it that triggers Chronograf to think hosts are up/down? Here's an example of metrics being posted:

<img width="1152" alt="screen shot 2017-10-15 at 10 42 16" src="https://user-images.githubusercontent.com/2544180/31583524-89f28730-b195-11e7-9066-cef388058eec.png">

And the connection to InfluxDB seems fine:

<img width="1148" alt="screen shot 2017-10-15 at 10 42 48" src="https://user-images.githubusercontent.com/2544180/31583526-9c7ef37a-b195-11e7-857d-9b5e222e725c.png">

The only thing I can think of is I'm not using the default "autogen" retention period. Is that likely to be an issue?

I've tried restarting the container running Chronograf with no luck.

Chronograf version is 1.3.9, using the official Docker image.

**Edit**: Additionally, you can see no hosts are being displayed, whereas I think Chronograf should be providing me with default dashboards for CPU, etc?

**Comment by goller** [comment]
Hi there, yeah, you are totally right that it is a retention policy issue.  Here are the offending lines of code :

https://github.com/influxdata/chronograf/blob/master/ui/src/hosts/apis/index.js#L9

Each query assumes the default retention policy.  

One workaround for the moment would be to  change your policy to be the default, but, we really should change the code to support non-default rps.

Btw, I see that you are plotting Minecraft server! Did you see that telegraf has a Minecraft plugin now?

Chris

**Comment by BnMcG** [comment]
Hi Chris,

I did see that! I only posted the top of the dash as an example, but further down...

![image](https://user-images.githubusercontent.com/2544180/31585976-80cbb08c-b1c2-11e7-8b54-1cd8fe9b77ca.png)

If I changing the default retention policy's value while keeping the same name will fix it, I'm happy to try that as an intermediate fix. 

If I have some time this week I might see if I can get more familiar with Chronograph's code and submit a PR for this 😄
