### ISSUE TITLE
Front-end Support for Insecure Skip Verify for kapacitor connections

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2139]
As mentioned in https://github.com/influxdata/chronograf/issues/1653#issuecomment-338076999

**Comment by karel-rehor** [comment]
Any idea when this will be merged and in a nightly build?  I would like to mention this in a Kapacitor security document, when configuring TLS with a test certificate.

**Comment by 121watts** [comment]
@karel-rehor just pulled this off our backlog. Has been prioritized for `1.4.3`.  Should see this in our nightly in the next few days.
