### ISSUE TITLE
Spike on 2073 open questions

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2145]
• What is the UX for no task ID state
• What is the display for empty state
• When do we purge from the dom
• Axios does not handle chunked http, do we buffer in the chronograf backend and poll that, or find a different javascript lib for chunked http.

**Comment by 121watts** [comment]
- [x] What is the UX for no task ID state
- [x] What is the display for empty state
- [x] When do we purge from the dom
- [x] Axios does not handle chunked http, do we buffer in the chronograf backend and 
- [x]  Axios does not handle chunked http, do we buffer in the chronograf backend and poll that, or find a different javascript lib for chunked http.

**Comment by desa** [comment]
@121watts https://github.com/influxdata/chronograf/pull/2171
