### ISSUE TITLE
Find all places where the edit widget is shown

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2146]

**Comment by jaredscheib** [comment]
- [ ] DashboardPageContents -> `+ Create Dashboard`

**Comment by alexpaxton** [comment]
On the configuration screen the edit/delete/add config options in the dropdown are passed in as props, so it looks like our proposed fix for draggability could also work here

**Comment by alexpaxton** [comment]
## Query Templates Dropdown (Items to hide)

- [ ] Create Database
- [ ] Drop Database
- [ ] Create Retention Policy
- [ ] Drop Retention Policy
- [ ] Create Continuous Query
- [ ] Drop Continuous Query
- [ ] Create User
- [ ] Create Admin User
- [ ] Drop User

Assuming `Create Admin User` is visible to **SuperAdmins** only
