### ISSUE TITLE
Time-series is not displayed when selected on rule creator

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2147]
• Go to rule builder
• Select a time-series
• The text reads "Send alert when '' is greater than..."

![sadseries](https://user-images.githubusercontent.com/1003269/31948761-b12ad304-b8a5-11e7-889f-f5cefae43eff.gif)

**Comment by 121watts** [comment]
So by time series do you mean the field value that supposed to go in that grey box?
