### ISSUE TITLE
Queries with template variables are not editable with the query editor

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2161]
• Create a cell
• Add a query
• Add a template variable to query
• Save
• Open query
Notice lack of ability to edit the query in the editor

**Comment by goller** [comment]
@121watts do you have that query that was causing problems?

**Comment by 121watts** [comment]
@goller `SELECT mean("numMeasurements") AS "mean_numMeasurements" FROM :db:."monitor"."database" WHERE time > :dashboardTime: GROUP BY :interval: FILL(null)`will do the trick.  Really any query with a template variable in the place of a field, tag, will return an empty `queryConfig`
