### ISSUE TITLE
Expand possibilities of AlertNode message

### ISSUE THREAD

**Issue by absolutejam** [influxdata/chronograf#2163]
EDIT: Posted my Kapacitor issue here by accident - edited!

Trying to set up an alert to Sensu, and when I use `{{ .Name }}` to substitute with my alert name (eg. `cpu_check_avg_15m`), it uses the name in Kapacitor, which is a randomly generated Chronograf one.

**Comment by nhaugo** [comment]
@absolutejam there is a workaround for this. If you generate a rule using the rule builder, then click `Edit TICKScript` copy the script. Then click `Write TICKscript` paste the script there. You can then name the script whatever you want in the top left corner. You will need to select the database and retention policy, even though it is specified in the rule itself (side effect of the editor). Then delete the initial copy.

The new rule will still be editable by the rule builder if you need to tune it, but will have a name specified by you.
