### ISSUE TITLE
As a user I can update a user's Chronograf Organization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2169]
A superadmin should be able to see all users and update their Chronograf Organization. This needs to include Users that have not been assigned to an Organization yet. An Admin cannot do this.

**Comment by jaredscheib** [comment]
Pushing this back for now. Instead, an Admin will simply manually Create that user in their Organization in order to add them to their organization.

**Comment by russorat** [comment]
decided not to fix in 1.x branch
