### ISSUE TITLE
Logout link missing base path

### ISSUE THREAD

**Issue by pmyjavec** [influxdata/chronograf#2175]
When running Chronograf 1.3.9.0 behind a reverse proxy (Nginx), where  base path is required, it seems the logout link does not include the configured base path, resulting in a 404 for users. 

Generated: `https://www.example.com/oauth/logout`
Expected: `https://www.example.com/chronograf/oauth/logout`

Here is the running configuration:

```
BASE_PATH=/chronograf
PREFIX_ROUTES=true
PUBLIC_URL="https://www.example.com/chronograf"
GH_CLIENT_ID="{{ chronograf_github_client_id }}"
GH_CLIENT_SECRET="{{ chronograf_github_client_secret }}"
GH_ORGS="influxdata"
TOKEN_SECRET="{{ chronograf_token_secret }}"
```

Everything else seems to be working ok!

**Comment by cryptoquick** [comment]
@nhaugo @goller the frontend uses links for logout produced from the backend. I'm thinking this was an oversight with the combination of basepath and logout.

**Comment by museghost** [comment]
I have same problem with the basepath. The logout path missed the basepath.

Could you please make a fix for that ?
