### ISSUE TITLE
Ensure tooltip is positioned correctly within cell

### ISSUE THREAD

**Issue by combizs** [influxdata/chronograf#2184]
Running Chronograf v1.3.10.0 in Chrome 64.0.3245.0 on an OS X El Capitan v10.11.5

First time running Chronograf after brew installation.

Steps to reproduce:

1. Navigate to 'Host List' and select any host to load cells/graphs, then move cursor so that it will not fall on any cell.

2. Move the cursor into a cell [**far left cells of screen**: left-to-right, **far right cells of screen**: far right-to-left, or **bottom bordering cells of screen**: down-to-up].

- The chart tooltip will be incorrectly placed only when it enters that cells first pixel.
- If user moves cursor anywhere else in that cell, the tooltip will correct its position, however, the tooltip would go through a 'flicker' state.
- Other edge cases also present an incorrect tooltip position, but do not cause a 'flicker' state as mentioned above.

![screen shot 2017-10-31 at 1 08 58 am](https://user-images.githubusercontent.com/749396/32213366-2b491ba0-bdd8-11e7-9998-790b0886c6eb.png)

**Comment by jaredscheib** [comment]
Thanks for reporting this, @combizs!
