### ISSUE TITLE
FR: regex support for alert creation

### ISSUE THREAD

**Issue by tanji** [influxdata/chronograf#2185]
Regular expressions are not currently supported when creating alerts. That could be useful when monitoring specific host groups.

**Comment by goller** [comment]
Hi @tanji thanks for writing in!  I totally think we should add this.  Right now I've just finished up a major PR for kapacitor that will help get A LOT more features for chronograf:

https://github.com/influxdata/kapacitor/pull/1625

However, it'll take a bit longer to get those changes into chronograf.

**Comment by tanji** [comment]
Awesome. Looking forward to the changes!

**Comment by mpetersen42** [comment]
@goller Any updates/plans?  RegEx would be useful for monitoring host groups, process instances, etc.  I see the PR has been merged for awhile now.
