### ISSUE TITLE
Add support for batch user CRUD actions on Chronograf users

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2189]
Server will receive an array of users. Currently this is implemented in the client as sending an individual request for each user.

- client
  - [ ] refactor batch Chronograf admin table action functions to use new API & send all users as one request
- server
  - [ ] mux – add routes & service methods for batch crud actions on Chronograf /users

**Comment by jaredscheib** [comment]
@danielnelson Might you have some insight about REST standards for batch operations like this, to be able to add 100 users to an organization at once, to delete a bunch of users, etc.?

**Comment by danielnelson** [comment]
Who creates/deletes 100 users at a time, this this something that needs to be super fast?  That said, I would just create a resource that you POST the users to add/remove too, making sure the operation is done atomically.

**Comment by jaredscheib** [comment]
Thanks. So RESTfully speaking, how do you DELETE a set since it can't have a request body?

**Comment by desa** [comment]
@danielnelson is there a common pattern for naming the resource for bulk actions?

**Comment by danielnelson** [comment]
I think DELETE can have a body, but you can use POST or PUT since you probably don't have a reasonable url for the DELETE to apply to.

> there a common pattern for naming the resource for bulk actions?

No common pattern that I know of, and I should mention that I would steer away from general purpose bulk actions for all operations.  Only add them if you must for performance reasons.

**Comment by desa** [comment]
@jaredscheib hmm, this seems like we're veering into some non-standard ways of doing things. What was the reason we decided to go this route instead of having the front end handle this?

**Comment by jaredscheib** [comment]
Seems to me like it's way easier to send a single request to the server with a collection of all users to delete, for example, rather than to have the client send that many number of individual requests and track possibly failed state on any of them. Maybe @cryptoquick has an opinion on this? Consider an example where we want to delete 1000 users. Sending 1000 AJAX requests seems problematic, compared to 1 request with all of the users to delete.

**Comment by jaredscheib** [comment]
We aren't going to pursue this for now. If/when we do, on the UI side be sure to revisit @lukevmorris's comments on variable names and code structure from #2180.
