### ISSUE TITLE
As a UI user, I should not be able to manually navigate to routes I don't have authorization for

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2193]
A user cannot navigate via the UI to the various routes that they are not authorized for, but a user can still navigate to those routes manually by typing them in directly to their browser URL bar. The functionality on those pages will not work, but it would be more elegant if they simply can't visit those routes and are redirected back to their current page or root upon such an attempt.

Solution is to authorize client React router routes based on role authorization.

**Comment by lukevmorris** [comment]
- [ ]prevent manual navigation to a client route that a user doesn't have access to, such as `admin-chronograf` if they are not an `admin`

**Comment by nhaugo** [comment]
Redirect back to current page, or status page instead of just throwing errors
