### ISSUE TITLE
Queries in all tabs are executed on window load

### ISSUE THREAD

**Issue by alexspiers** [influxdata/chronograf#2195]
On the "Data Explorer" page

1. Enter any query that returns results
2. Open new tab
3. Enter a destructive query like "DROP DATABASE test; CREATE DATABASE test;"
4. Navigate to first tab
5. Refresh the page
7. All queries in all tabs are executed, resulting in the database being dropped and recreated

Is this the expected behavior? I can't imagine this being so but if it is then the page clearly needs more obvious warnings to inform that use that all queries in all tabs will be run on every page load!

OS version: Ubuntu 16.04
Chronograf Version: 1.3.8-2
Prebuilt package from https://dl.influxdata.com/chronograf/releases/chronograf_1.3.8.2_amd64.deb

**Comment by nhaugo** [comment]
Hi @alexspiers due to a number of issues, this being one, we removed tabs from the data explorer in 1.3.9 >
