### ISSUE TITLE
On upgrade to 1.4.0, handle Users bucket migration

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2197]
Should we delete and recreate the Users bucket? If so, we could store (if doesn't already exist) a key in Bolt with the version of Chronograf to determine whether this action has already happened or not.

**Comment by goller** [comment]
Is it possible to simply use a different bucket?  For example, perhaps UsersV2?  If that bucket exist then you know migration has occurred.

**Comment by jaredscheib** [comment]
Ah yes, good call! We'll do that.
