### ISSUE TITLE
On migration to 1.4.0, all existing resources become owned by Default Organization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2198]
What happens to existing Chronograf resources upon upgrade to 1.4.0?

Some ideas:

1. Do we make them all belong to the Default organization?

1. Do we make them belong to a hidden organization (that only a superadmin would be able to see)? And if so, do we need a page or interactive wizard to allow a Superadmin to see what resources belong to which organizations and mutate that ownership?

1. On first user, do we force them to create an Organization and then automatically add existing resources to that Organization?

cc @nhaugo

**Comment by goller** [comment]
@jaredscheib I think we should add the resources to the default organization.

**Comment by nhaugo** [comment]
1) yes
2) no
3) no, they should be in the default org

**Comment by jaredscheib** [comment]
@nhaugo Can a superadmin change the ownership of a resource?

**Comment by jaredscheib** [comment]
I believe that as part of solving this, we need to inject the new Organizations logic into the creation of Layouts from the `/canned` folder.

**Comment by jaredscheib** [comment]
@desa just spoke with @nhaugo – I forgot that all new members are SuperAdmins until a SuperAdmin sets Default roles per organizations, so upon upgrade, the experience is the same as it is now: all users (who are Superadmins until someone changes it away from that) will be able to see the resources migrated to be owned by the Default organization because they will all be SuperAdmins.
