### ISSUE TITLE
Redirect to proper page based on role, sources, and whether using auth

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2199]
1. If you are a Member or Viewer of an Organization that has no sources, such as if you simply authenticate and land as a `member` of the `Default` organization, what do you see / what page do you land on? (You can't create sources in that role, so the current create source page is irrelevant.)

1. Does a superadmin need to add a source to the Default organization?

1. If the default organization has a source, where should users land? The status page?

1. As a superadmin, am I signed into the Default Organization? And then what sources do I see?

cc @nhaugo

**Comment by nhaugo** [comment]
1) empty status page
2) it should behave as it does today, you add a source before being let in the first time
3) status page
4) The flow should be like it is today

**Comment by jaredscheib** [comment]
As of b77a1a3 we've implemented the redirect fix for this, but decided to send unauthorized users to `/limbo` for now.

It seems like a page that tells them that they've authenticated but, if they're only a `member` of the `Default` organization, tells them that they don't have access to anything, would be appropriate. Alternately, we could make newly authenticated users a `viewer` in the `Default` org, and then take them to the status page if the Default org has sources. But if the Default org doesn't have any sources, then there will be nothing to see on the Status Page.

Thoughts @nhaugo @alexpaxton on creating a new limbo page that communicates the state that they're in, if they've authenticated into an Organization that has no sources, or where they have insufficient access to see anything? An empty status page does not seem exactly right to me, having now implemented it.
