### ISSUE TITLE
Change Organizations to []string on resources

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2200]

**Comment by desa** [comment]
Creating issue for https://github.com/influxdata/chronograf/pull/2142#discussion_r148063857

**Comment by jaredscheib** [comment]
This change will should probably happen in the client and server in the same PR.

**Comment by jaredscheib** [comment]
In client and server.

**Comment by russorat** [comment]
@desa something for the 2.0 apis?

**Comment by desa** [comment]
yeah this'll be in there I believe.
