### ISSUE TITLE
RFC: consider different name for superadmin

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2205]
- Owner? Doesn't quite feel right to me either.
- Superuser?
- Ruler?
- Champion?

cc @goller @desa

**Comment by nhaugo** [comment]
I think owner is fine. Fits with other web applications way of doing things.

**Comment by jaredscheib** [comment]
Sounds good. We will do this in a PR soon but hasn't been done yet so re-opening.

**Comment by jaredscheib** [comment]
Dupe of more detailed #2207. Closing.
