### ISSUE TITLE
Change 'member' role name to 'guest'

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2206]
This is the name of the role with no authorization – you simply receive it once you've authenticated. It is also the default role for new organizations created.

**Comment by jaredscheib** [comment]
This change will need to happen in the client and server in the same PR.

**Comment by nhaugo** [comment]
To me "guest" indicates temporary membership not reduced priveleges

**Comment by russorat** [comment]
So here's my take on this: the technically "correct" word to use would be "unauthorized", but as some have mentioned, this might be confusing to some and unfriendly to others. 

"guest" is more correct than member when you think of it as being a guest at a "members only" club, not so much like guest wifi access. A guest is someone known by a registered member of the club, and they were probably invited or told about the club by a member, but they do not have access to the parts of the club that are members only. So in that way, they do have a reduced set of privileges.

So I vote for "guest" as well.

**Comment by nhaugo** [comment]
I'm good with guest, @desa @jaredscheib can we get a work estimate on this. I worry about introducing this past 1.4 since it would probably create a need for migrations.

**Comment by desa** [comment]
@nhaugo should be pretty easy, just have to track it town everywhere it shows up. Maybe a half day tops.

**Comment by jaredscheib** [comment]
I actually think we should keep `member`. If I'm a `guest`, I would expect to be "welcomed in" and "have access" to some things. But that's not what a `member`/`guest` gets. They simply go to purgatory. After much consideration, I think `member` is more appropriate.

**Comment by ebb-tide** [comment]
I know this issue is closed- but couldn't guest / member be simply "authenticated"?
you are "a guest" => you are "authenticated" 
the purgatory could say you are authenticated, contact your admin for privileges.
