### ISSUE TITLE
Refactor SuperAdmin/Owner into interface & add userResponse test for SuperAdmin field

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2207]
See https://github.com/influxdata/chronograf/pull/2142#discussion_r148394697

This involves removing the `SuperAdmin` bool from the `chronograf.User` and instead having an interface for determining whether someone is a super admin or not.

Something like
```go
type Owner interface {
PromoteTo()
DemoteFrom()
Is()
}
```

ALSO:
- [ ] add test to verify that if a user is a SuperAdmin that that info comes back correctly to the client as part of userResponse

**Comment by desa** [comment]
See https://github.com/influxdata/chronograf/pull/2142#discussion_r148406521

**Comment by desa** [comment]
Additionally, See https://github.com/influxdata/chronograf/pull/2142#discussion_r148409879

SuperAdmin on users response should be omit empty

**Comment by jaredscheib** [comment]
This change will need to happen in the client and server in the same PR.

**Comment by glinton** [comment]
I believe this is still an issue

**Comment by sranka** [comment]
The implementation and associated refactoring might come with side-effects that are quite hard to predict or test, it is better to avoid this now. This issue can become a part of a functional request anytime later on though.

**Comment by sranka** [comment]
From the linked comments, I see 2 code pointers for architectural improvements:

1. https://github.com/influxdata/chronograf/pull/2142#discussion_r148409879
   * User's SuperAdmin status should be visible/changeable only to SuperAdmin's
   * STATUS: both `NewUser` and `UpdateUser` calls an extra [setSuperAdmin](https://github.com/influxdata/chronograf/blob/master/server/users.go#L342) function that validates that only superAdmin can change/setup user's superAdmin status. #2601 is a referenced issue related to superAdmin status, this also already repaired ... it really makes sense that a "non-superAdmin" can't create new "superAdmin" users, an error message (introduced in #2602) clearly indicates it.
   * Users are visible to administrators, only administrators (or superAdmins) can then actually see the user's superAdmin status.
1. https://github.com/influxdata/chronograf/pull/2142#discussion_r148406521
   * `SuperAdminKey` is no longer used in context
   * STATUS: already resolved, no such code is therein anymore

I don't know about any other motivation why to do such refactoring, all referenced comments are already resolved.
