### ISSUE TITLE
As a user I can see currently saved tasks

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#221]
• The configured kapacitor's rest api should be queried to get the defined tasks
• The tasks listed should show
- ID
- Type
- Status 
- Executing
  ![kaparules copy](https://cloud.githubusercontent.com/assets/1003269/19282523/8cd1cc0a-8fa3-11e6-9905-931b3b4c5d9c.png)

**Comment by nhaugo** [comment]
This should be a representation of kapacitor's status, not just the generated rules

**Comment by nhaugo** [comment]
@alexpaxton can we get a design pass for this. 
We want to fetch all kapacitor tasks, display them and allow the users to enable and disable.
There should be some sort of visual cue to the user that a task is editable within chronograf or not.

**Comment by alexpaxton** [comment]
**Mockup:**
<img width="1251" alt="screen shot 2017-04-10 at 3 05 28 pm" src="https://cloud.githubusercontent.com/assets/2433762/24884714/a6ea9118-1dff-11e7-9a01-ec2f02bb3167.png">
- All the rules appear in the same table
- `Type` column added for indicating where the alert came from
- Rules created outside Chronograf cannot be clicked on

@121watts can I get some copy feedback copy master?

**Comment by nhaugo** [comment]
I wouldn't worry about type. Eventually we will have the text editor for other rules. So when editing the user will just get the editor that works.

**Comment by nhaugo** [comment]
To test, rules created by other peoples chronograf's
