### ISSUE TITLE
Set default role on user if not specified in create request

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2224]
currently, with these https://github.com/influxdata/chronograf/pull/2220/ and https://github.com/influxdata/chronograf/pull/2219 the client has to be explicit about the roles they’re adding on the user, but they can hit `/organiations/id` to see the default org. Once the two are merged, we can have the server fill in that info if it was not specified by the client.

- [ ] if no roles are found on create, retrieve the default role for the organization and add it to the users roles.

**Comment by jaredscheib** [comment]
Could you confirm that this has been implemented @desa ?

**Comment by jaredscheib** [comment]
Closing as our client now always sends a role on create, and server will reject a create if there are no roles, which is sufficient.
