### ISSUE TITLE
Expose some organization routes to admins

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2225]
- [x] Expose GET `/organizations` to Admins. Route should return their current organization and the default organization
- [x] Expose PUT `/organizations/:id` to Admins
- [x] Expose GET `/organization/:id` to Admins

**Comment by jaredscheib** [comment]
@desa What would a PUT for an Admin do? Not sure that should be possible.

GET to the other two makes sense, and the organizations/:id should return a 404 if it's not their own organization, I think.

**Comment by desa** [comment]
Put can modify the DefaultRole for the organization and the Name of the organization.

**Comment by jaredscheib** [comment]
@nhaugo Should an Admin be able to modify an Organization in any way, such as DefaultRole or changing its Name? Or only Superadmins?

**Comment by desa** [comment]
@jaredscheib Should Admins of an org be able to delete it?

**Comment by jaredscheib** [comment]
@desa No, I don't think so.

**Comment by nhaugo** [comment]
Yes admins should have full permissions of the org's properties, but not able to rename.

**Comment by jaredscheib** [comment]
@desa no delete or rename

**Comment by desa** [comment]
@jaredscheib fixed
