### ISSUE TITLE
Ensure unique user by name && provider && scheme

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2226]
OAuth2 providers will ensure uniqueness, but you could create a duplicate user when whitelisting.

**Comment by nhaugo** [comment]
This seems to work on the backend but not the front end, adding a user a second time will add them to the list and update the number of users for the org. However on reload the dupe is missing. An error should be shown and the user should not show up in the list

**Comment by nhaugo** [comment]
This also appears to update the user, thus someone with admin perms who adds a "dupe" user with less perms will update that user to the new lesser perms

**Comment by jaredscheib** [comment]
- [ ] cc @desa on the server, a Create for a user that already exists is effectively being treated as an Update -- this should be rejected instead.
- [ ] additionally, on the client, allow submission of duplicate but show error notification and don't optimistically update

**Comment by desa** [comment]
looking into that now.
