### ISSUE TITLE
As a user, I should not be able to delete myself

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2227]
Currently, the only user left can delete themselves. They are not logged out, but rather their valid JWT (if using client) ensures that they will be created anew within 10 seconds due to the heartbeat. They will be a superadmin, and a member of the default organization.

Should the only user be able to delete themselves temporarily in this way? Either via the API and/or via the UI?

And if I do delete myself (and thus all users), should the bolt ID for new users start back at `0`? Currently it does not.

cc @nhaugo

**Comment by nhaugo** [comment]
A single user should not be able to delete themselves from the default org, or remove their own superadmin status if they are the only superadmin

**Comment by desa** [comment]
Will implement that a super admins cannot delete themselves.
- [ ] put user on context

**Comment by desa** [comment]
I've just made it so that a user cannot delete themselves. Is that behavior sufficient? It seems easier to reason about that than to have a special case where we check to see if they are the last user or super user.

**Comment by jaredscheib** [comment]
Seems fine to me for now @desa -- thanks

**Comment by jaredscheib** [comment]
@alexpaxton Let's be sure to update the UI to reflect this change.

**Comment by nhaugo** [comment]
This seems to work in the backend but no warning is given in the front end and it is not clear that it did not remove the user until they refresh

**Comment by jaredscheib** [comment]
After discussion:

The current behavior prevents an Organization from being left without an Admin, so for now:
- [ ] remove `Remove` button for self within any organization

**Comment by jaredscheib** [comment]
After trying the removal, I went with disabling the button instead, as it felt clearer as to what was going on.
