### ISSUE TITLE
Handle display of superadmin status of other users to admins in UI

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2228]
If a superadmin also has a role in an organization, should an admin be able to see their superadmin status?

And if not, what happens when an admin attempts to delete a superadmin? On client and server side?

cc @nhaugo

**Comment by nhaugo** [comment]
Superadmin concept does not need to be represented in the org, an admin should be able to remove the superadmin. The superadmin could alway readd themselves to the organization.

**Comment by jaredscheib** [comment]
@nhaugo Do we care whether an Admin can see that a user is a Superadmin in the JSON response from the server?

**Comment by nhaugo** [comment]
I would not go out of my way either way.

**Comment by jaredscheib** [comment]
In that case, the delete functionality is covered in #2238, which makes this issue simply about what @alexpaxton wants to do in terms of if or how to display the superadmin status of other users to Admins. Seems to me like it might simply be easier to hide the SuperAdmin column from an Admin in the Users table, rather than displaying and disabling the toggle.

**Comment by jaredscheib** [comment]
In discussion, we decided to just leave it as not showing the column for now. I'll confirm that this is the case and close this issue if so.

**Comment by jaredscheib** [comment]
Confirmed that it doesn't show for Admins.
