### ISSUE TITLE
Disallow or fill in null organization on create Chronograf user

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2236]
On `multitenancy` +
 `multitenancy_default_org`,
 I am able to perform a `POST` to `http://localhost:8888/chronograf/v1/users` with body `{"name":"jim","provider":"asf","scheme":"oauth2","superAdmin":false,"roles":[{"name":"member","organization":null}]}`, which returns a `201`. I should not be able to create a user with a `null` organization.

**Comment by desa** [comment]
if null add default role in current org

**Comment by jaredscheib** [comment]
Let's go with, if null, add to current org with default role.
