### ISSUE TITLE
Deleting a user as an admin/superadmin should simply remove them from that admin's current organization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2238]
Currently if a superadmin deletes a user, that user's JWT is still valid and within 10 seconds they will have successfully recreated their user under a new ID thanks to the client heartbeat that hits the `/me` endpoint.

Current thoughts are:

Deleting a user as a superadmin should force a user to reauthenticate, by deleting their JWT.

Deleting a user as an admin should simply remove them from the organization.

Thoughts, @nhaugo?

**Comment by nhaugo** [comment]
Start with "Deleting a user as an admin should simply remove them from the organization." and we will figure out if we need to be more aggressive.

**Comment by jaredscheib** [comment]
@desa ^^

**Comment by jaredscheib** [comment]
@nhaugo And if a superadmin deletes a user, shall we redirect that user to be logged out?

**Comment by nhaugo** [comment]
1) only the context of the current org
2) next time they check into /me and it fails it should just do its thing
3) see above

**Comment by jaredscheib** [comment]
Probably on the UI side would be good to rename any `Delete` copy to `Remove` then as well, @alexpaxton

**Comment by desa** [comment]
@jaredscheib as of https://github.com/influxdata/chronograf/pull/2316
I think that all user request, including those for super admins, will be in the context of their current organization.

**Comment by jaredscheib** [comment]
If a user is only part of one org, and they are removed from it, they'll be a user with no roles in any orgs, and the next time they authenticate they'll be re-added automatically as a member in the Default org.
