### ISSUE TITLE
A user should be able to edit the name when creating a query in a dashboard cell

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2254]
The natural flow of adding a graph to the dashboard is to first click `+ Add Cell`, then immediately click the `Add Graph` button to bring up the query editor.

Right now, I don't see a way for a user to update the title of the dashboard cell when they are in the query editor screen. That means that the user will first need to create the query, then select and rename the cell to reflect the query. It would be useful if the user had the ability to edit the name of the cell before closing the query editor. Options might be clicking on the name of the cell in the query editor or adding an option for the cell title in the configure tab.

In addition to this, we might also consider automatically populating the Title of the cell with the name of the y-axis for the query when no name is chosen.

**Comment by nhaugo** [comment]
Fixed in 1.3.9.0 https://github.com/influxdata/chronograf/pull/2002
