### ISSUE TITLE
Add ability to duplicate or clone Cells and Queries on dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2256]
As a user, there are many times when I want to create very similar graphs on the same dashboard. It would be nice if there was an option in the cell drop down to duplicate the current graph to use it as a starting point for editing. This would keep the same query, cell dimensions, and visualization options and create a new cell that the user can then edit.

The new name would be `Copy of <original dashboard name>`.

**Comment by e-dard** [comment]
💯 I just ran into this.

**Comment by russorat** [comment]
this is sweet!
