### ISSUE TITLE
Legend sometimes hides the data i am trying to look at

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2257]
See attached gif. When there isn't enough room for the legend outside of the graph, the popup covers the data I am trying to look at. It would be better for the legend to either be clipped or show somewhere else on the screen so I could still see my data.

![kapture 2017-11-03 at 14 52 57](https://user-images.githubusercontent.com/4805997/32397406-dce1402e-c0a6-11e7-8e78-fa644f8ec34a.gif)

**Comment by nhaugo** [comment]
This was fixed in 1.3.9.0 https://github.com/influxdata/chronograf/pull/2040
