### ISSUE TITLE
If my role has changed in my me, I should be redirected to Purgatory or wherever appropriate

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2264]
I was a superadmin. Another superadmin deleted me. My me came back as that I was only a member of the Default organization, and yet the app did not change. Only when I refreshed did I go to limbo.

**Comment by cryptoquick** [comment]
that's a pretty metaphysical title, @jaredscheib 🤔

**Comment by jaredscheib** [comment]
haha
