### ISSUE TITLE
When creating a new query on a dashboard, the query editor should be highlighted by default 

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2265]
Right now, when a user starts to create a new graph on a dashboard, there is nothing highlighted (typing does nothing). If they are copying and pasting a query or are comfortable enough to start typing right away, we should highlight the query editor for them.

**Comment by cryptoquick** [comment]
Easily done with a ref to the component and focus method call on componentDidMount.

**Comment by chnn** [comment]
Just made a pass at this... ends up being much trickier due to a bug in codemirror and/or react-codemirror, which provides textbox in the query editor.

Going to punt on this for now.

**Comment by russorat** [comment]
@Delmer814  timebox this to .5 days to see if it is possible.
