### ISSUE TITLE
Dashboards intermittently show "No Results"

### ISSUE THREAD

**Issue by mekazu** [influxdata/chronograf#2269]
This is what my graph looks like for Past hour:

![image](https://user-images.githubusercontent.com/683513/32421420-5a281a60-c2e8-11e7-85e2-45b31bffe780.png)

When I zoom to say 15 mins in it usually shows No Results:

![image](https://user-images.githubusercontent.com/683513/32421428-78ecc716-c2e8-11e7-9834-d8813eb3b520.png)

By downloading the CVS I can see that there is definitely some results.

This issue only seems to occur for cells of a dashboard that have more than one query. In the cases that I've tested if I remove all but the first query then the graph is displayed correctly. Working hypothesis: It might be caused when one of the multiple queries of a cell has no data - in this case the bug would be that it's displaying No Results if ANY (rather than all) of the queries return no results,

It's obvious that there's an error somewhere but it's showing No Results instead of something helpful like 'An error occurred' and it's not obvious where to look for errors. I can't see anything interesting in the influxdb or chronograf console output, nor in the browser console.

Everything is running on Windows 10:

- Telegraf v1.4.3 (git: release-1.4 b473b6a6596078f142a623ca38ff7030b7acec8f)
- Chronograf 1.3.10.0 (git: 2eca970c8a2158ca89575c28e673c8baa6886767)
- influxdb-1.3.7_windows_amd64.zip
- kapacitor-1.3.3_windows_amd64.zip

When the issue occurs it occurs the same way with Firefox, Google Chrome and Edge.

This issue is intermittent, although it appears to be related to what data is available to be displayed or filtered out. Sometimes this is an issue, but as time goes by and different stats are generated, it goes away, and later comes back again.

**Comment by 121watts** [comment]
@mekazu.  Thanks for writing in.  This should be resolved now!
