### ISSUE TITLE
Export to CSV not exporting all series

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2271]
I have the following graph on my dashboard with 3 series being displayed. When I export it, the CSV only contains two columns: time and count. I was expecting the CSV to contain a column for time and then a distinct column for each of the series in the graph.

Graph image:
![image](https://user-images.githubusercontent.com/4805997/32454652-b22e41c6-c2d4-11e7-99aa-8b1ced6bfc97.png)

Exported Output
```
time,count_tweet_id
11/6/2017 9:16:55.000000000 AM,6
11/6/2017 9:17:00.000000000 AM,5
11/6/2017 9:17:05.000000000 AM,7
11/6/2017 9:17:10.000000000 AM,3
11/6/2017 9:17:15.000000000 AM,5
11/6/2017 9:17:20.000000000 AM,4
11/6/2017 9:17:25.000000000 AM,4
11/6/2017 9:17:30.000000000 AM,8
11/6/2017 9:17:35.000000000 AM,7
11/6/2017 9:17:40.000000000 AM,5
```

Expected Output
```
time,count_tweet_id_bitcoin,count_tweet_id_btc,count_tweet_id_btcusd
11/6/2017 9:16:55.000000000 AM,6,3,2
11/6/2017 9:17:00.000000000 AM,5,3,5
11/6/2017 9:17:05.000000000 AM,7,2,5
```

**Comment by russorat** [comment]
@cryptoquick in the query I was using, i am grouping by a tag: `SELECT count("tweet_id") AS "count_tweet_id" FROM "telegraf"."autogen"."tweets" WHERE time > now() - 15m GROUP BY time(10s), "lang" FILL(null)`

this could be "working as designed" but it wasn't what i was expecting as output. 

I think i am using the latest build, but it would be good to verify.

**Comment by nhaugo** [comment]
Each series should be a combination of the tags with the columns (except time), so the following
```json
{
            "series": [
                {
                    "name": "tweets",
                    "tags": {
                        "keyword": "ripple",
                        "lang": "en"
                    },
                    "columns": [
                        "time",
                        "count_tweet_id"
                    ],
                    "values": [
                        [
                            1512069345000000000,
                            1
                        ],
                        [
                            1512069360000000000,
                            3
                        ],
                        [
                            1512069375000000000,
                            2
                        ],
                        [
                            1512069390000000000,
                            2
                        ],
                        [
                            1512069405000000000,
                            1
                        ]
                    ]
                }
            ]
        }
```
Would create a column 
count_tweet_id_ripple_en

**Comment by russorat** [comment]
https://github.com/influxdata/chronograf/issues/3125

**Comment by russorat** [comment]
blocked until changes to https://github.com/influxdata/chronograf/issues/1686 are completed

**Comment by russorat** [comment]
❤️ this!
