### ISSUE TITLE
Review all error messages for consistency and specificity, and ensure logging is sufficient

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2272]
>Sounds good. Only question is why we return 'unknownErrorWithMessage' consistently in the case that DefaultOrg store returns an error, instead of more explicitly what the issue is? Is that consistent with errors returned elsewhere when store accessors fail?
>
>And I understand correctly, if ever a request does not contain an org in context, the Default will be used, yeah? Would we rather return an error if an org is missing? Or do we do this as well?
>
>And, this slows for renaming of Default org. Seems ok to me but we may revisit this in the future.

https://github.com/influxdata/chronograf/pull/2219#issuecomment-342222311

**Comment by desa** [comment]
- [ ] Add logging

**Comment by jaredscheib** [comment]
Let's do this for all of multitenancy, including the specific case above.
