### ISSUE TITLE
Add limbo page or something

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2278]

**Comment by jaredscheib** [comment]
A "limbo" page that tells them that they've authenticated but, if they're only a `member` of the `Default` organization, tells them that they don't have access to anything, would be appropriate. Alternately, we could make newly authenticated users a `viewer` in the `Default` org, and then take them to the status page if the Default org has sources. But if the Default org doesn't have any sources, then there will be nothing to see on the Status Page.

Thoughts @nhaugo @alexpaxton on creating a new limbo page that communicates the state that they're in, if they've authenticated into an Organization that has no sources, or where they have insufficient access to see anything? An empty status page does not seem exactly right to me, having now implemented it.

**Comment by alexpaxton** [comment]
I have a design for this, just needs to be wired up: #2287
