### ISSUE TITLE
[Feature Reuqest] Highlight mandatory fields for TICK scripts instead of just greying out save button

### ISSUE THREAD

**Issue by seb-koch** [influxdata/chronograf#2289]
Right now for Chronograf 1.3.3 the mandatory fields are very unremarkable and hard to spot for first time users. Me and my colleague both failed independently to save our first scripts because we firstly missed to enter a name and secondly missed to select a database.

*Suggestions*
1. Highlight the input for the script name
2. Highlight the drop down for the database selection
3. "ID your TICK script" seems odd as a field descriptor, smth like "Enter the script name" is more clear
4. Color input field placeholder text white instead of darkgrey to avoid it from blending in too much.

*Rough proposal*
![screen shot 2017-11-07 at 11 12 48](https://user-images.githubusercontent.com/19778637/32488473-ff56524e-c3ac-11e7-82ee-1b1c495dc3ea.png)

**Comment by goller** [comment]
Hey there @seb-koch , we've updated the interface to make it more clear:

![ticker](https://user-images.githubusercontent.com/1922921/33450392-419f1f06-d5d1-11e7-991f-713955e2f8c6.gif)

(ignore the kapacitor logging thing :)

Look better?
