### ISSUE TITLE
Chronograf API removes alert endpoints that are of the same kind

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2296]
This is a part of the multiple alert endpoints story
I am able to pass multiple alert endpoints that are of different kinds (that have different name fields), but not multiple alert endpoints of the same type. 

![kapture 2017-11-07 at 17 07 56](https://user-images.githubusercontent.com/10937678/32526457-3ac22426-c3de-11e7-8d23-bd986162696a.gif)

**Comment by goller** [comment]
@ebb-tide do you mind attaching the request payload to this issue?

**Comment by goller** [comment]
We should be past this now.  Closing!
