### ISSUE TITLE
Superadmin cannot see all users at once, only those in their current organization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2297]
As part of this, make `SuperAdminContext` in server more clearly into `ServerContext` and indicate which user type is making the request.

This also means that on a GET to /users, even for a superadmin we need to filter all users' roles to contain only the role for the current organization.

**Comment by jaredscheib** [comment]
Maybe this should actually be implemented under the /organizations/:id/users route, and keep /users to be all users across organizations.

**Comment by desa** [comment]
So the `/users` routes will remain for super admins only, but `/organizations/:id/users` will be for admins.

Making that change would be more work than having `/users/:id` function like `/organizations/:id/users` and then introducing new routes that are explicitly for super admins like `/super/users` or something of the sort.

It'd also be a minimal revert. I don't feel particularly strongly about it either way. One argument for making the proposed changes to `/users` to be scoped to an org, even for super admins, is that it would be consistent with the way that every other route works, which is that it does filtering by your current org. And this way, if we need special things for super admins, we can add a set of superadmin only routes.

**Comment by desa** [comment]
@jaredscheib I haven't implemented a way for super admins to see all of the user. Should that be a part of https://github.com/influxdata/chronograf/pull/2316

**Comment by jaredscheib** [comment]
For now, there's not a need for superadmins to be able to see all users. Let's make it so that if this changes in the future, the API won't change. We'd simply open /users up to respond with all users for a SuperAdmin, if ever we needed that again. Sounds good?
