### ISSUE TITLE
As a superadmin, I can no longer get any sources

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2299]
#2249 seems to have introduced a bug that we missed. I am a superadmin and a member of the Default org, and I can POST a new source successfully, but a GET right after a successful POST still returns an empty array (`[]`) for `sources`.

Building a server off of df8a834b, which is the commit prior to the merge of #2249, confirms that the regression was introduced there.

**Comment by desa** [comment]
Hmm, this is peculiar. I think I've found the source of the issue. Are you supplying a `Role` on your source request?

**Comment by desa** [comment]
I think I've solved it https://github.com/influxdata/chronograf/pull/2304
