### ISSUE TITLE
UI SideNav should disambiguate role in current org from superadmin status

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2300]
I am a `member` of `Default` but it shows `superadmin` here, which I also am.

<img width="263" alt="screen shot 2017-11-07 at 10 10 39 pm" src="https://user-images.githubusercontent.com/6403018/32534005-8961fcc6-c408-11e7-8344-90a696209d42.png">

**Comment by alexpaxton** [comment]
Completed via commit `0e0b336` in `multitenancy_ui_superadmin_admin_panel`
