### ISSUE TITLE
rpm package has missing dependencies

### ISSUE THREAD

**Issue by lfarkas** [influxdata/chronograf#2302]
the rpm package has a missing dependencies. it's try to add user with useradd but do not depend on it. which is not a problem in most case but in case of a kickstart install this cause a problem since it happened that shadow-utils(which contains useradd) installed after this package.

so the spec file should have to modified and add these lines:
Requires(post): /usr/sbin/useradd

**Comment by goller** [comment]
@lfarkas could find!  I've just created PR: https://github.com/influxdata/chronograf/pull/2303

We are currently using fpm to generate our RPM packages.  I would MUCH rather us use real spec files.  Is this something you know how to do and would be interested in ?

**Comment by lfarkas** [comment]
the same bug was fixed in the latest influxdb : https://github.com/influxdata/influxdb/issues/8951

**Comment by lfarkas** [comment]
yes i made a lot's of spec file...

**Comment by goller** [comment]
Ok, this should be in our next release, 1.3.11

If you have any bandwidth we'd love your help for a spec file!
