### ISSUE TITLE
Write documentation for multitenancy

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2306]
- [x] Go through all of multitenancy and document behaviors
  - [x] review all comments and turn them into documentation
- [x] express any assumptions or default behaviors that may be unexpected

Additional running list:
- [x] sources are visible to `viewer` and above, i.e. not `member`
- [x] #2311 + #2198 – on migration, all resources become owned by Default org. all newly authenticating users are SuperAdmins until a SuperAdmin changes this setting. if someone changes this setting, and they have left the Default role in the Default Organization as `member`, then all of those Default Organization resources will become invisible to newly authenticating users and any current users (probably all) who are only `member`s in the Default organization. any users whom you want to be able to see those original pre-upgrade resources will need to be made into at least `viewer` in the Default organization, and, likewise, the Default role for the Default Organization should be changed to at least `viewer` if you want newly authenticating users to be able to see those as well

Add all of this to  https://github.com/influxdata/docs.influxdata.com/blob/db-chrono-1.4/content/chronograf/v1.4/administration/multi-tenant.md

**Comment by ebb-tide** [comment]
break into issues for the docs repo

**Comment by stevebang** [comment]
Docs have been created for the new functionality (multi-organization/multi-user). @jaredscheib, if there's nothing new here, let's close this.
