### ISSUE TITLE
Add super admin as admin in newly created organization

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2307]
Currently, if a SuperAdmin creates an Organization, they will not have a Role within that Organization, and thus they cannot switch into that Organization or add other members to it.

Possible solutions are:
1. When a SuperAdmin creates an Organization, they automatically gain a Role in that Organization – this seems weird because this may be undesirable;
1. SuperAdmin can change into any organization without having a Role in that organization – this seems like it would be possibly strange UX on the client side as you'd be able to sign into an Organization without having a Role in it, and so you'd see it listed under your User submenu with an indication that you're `not a member`;
1. Give SuperAdmins a view where they can see all Users, regardless of which Organization they are signed into, and have the ability there to add/remove Users from Organizations – this could be weird UX if the expectation is that your experience of Chronograf should be strictly within the context of the Organization you're currently signed into; on the other hand;

**Comment by nhaugo** [comment]
when an org is created, superadmin should be added as an admin

**Comment by jaredscheib** [comment]
ok thanks, will do.
