### ISSUE TITLE
Add ability to switch orgs while in Purgatory

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2308]

**Comment by alexpaxton** [comment]
![screen shot 2017-11-08 at 4 50 13 pm](https://user-images.githubusercontent.com/2433762/32583790-47a10bd6-c4aa-11e7-8b32-5a5be598de81.png)

**Comment by jaredscheib** [comment]
via @nhaugo: This is low priority or may not ever be necessary. Defer to #2321 instead.
