### ISSUE TITLE
Make sure user goes to Purgatory if their me changes and/or they're no longer part of what was their current organization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2309]
Should they go to Purgatory if they're still members of other orgs and have the opportunity to switch, while receiving a notification of what happened?

Should they simply be logged out?

Somehow they'll have to be able to switch organizations.

**Comment by alexpaxton** [comment]
![screen shot 2017-11-08 at 5 20 27 pm](https://user-images.githubusercontent.com/2433762/32583778-3cec3828-c4aa-11e7-8d71-2305670588a9.png)

**Comment by jaredscheib** [comment]
@alexpaxton at the `Check remaining orgs` step, just send them to Purgatory instead. Checking remaining orgs is a technical pain and easier to just send them to Purgatory for now.

**Comment by alexpaxton** [comment]
Purgatory is cool, just want to keep the user in the loop so hopefully we can still send notifications to affected user(s) when this scenario takes place
- [ ] Display "You were removed from org x" notification to user when they are removed and returned to purgatory

**Comment by jaredscheib** [comment]
Closing in deference to simply logging the user out for now, as they'll receive a 403.
