### ISSUE TITLE
Design for Org Selection page

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2313]
![screen shot 2017-11-08 at 5 37 02 pm](https://user-images.githubusercontent.com/2433762/32584065-7af8c310-c4ab-11e7-9069-ce50681e5b54.png)

When a user authenticates and are a member of more than 1 organization they get to choose which one they want to log in to.

The concept of a "default" org is designed to streamline this process, but is icing on the cake. May implement later in time depending on constraints

**Comment by jaredscheib** [comment]
via @nhaugo: This is low priority or may not ever be necessary. Let's start with #2321 instead for now.
