### ISSUE TITLE
Redirect URL not populated for Generic Provider authorization request

### ISSUE THREAD

**Issue by sidgod** [influxdata/chronograf#2314]
Generic OAuth2 provider does not include HTTP parameter redirect_url=<callback URL> while calling authorize API as configured for Chronograf. Does chronograf support setting redirect url along with other configurations of Generic Provider ?

**Comment by goller** [comment]
Hi there @sidgod , sorry I didn't respond sooner, but, thanks for writing in!

Yes, the generic oauth2 does support redirect url.  

The format of the redirect is:
```sh
$PUBLIC_URL + $BASE_PATH + "/oauth/generic/callback"
```
$BASE_PATH is optional

**Comment by sidgod** [comment]
But is that parameter redirect_url posted to autorization endpoint ? I don't think that happens today ?
