### ISSUE TITLE
derivative scale issues in MySQL canned dashboard

### ISSUE THREAD

**Issue by tanji** [influxdata/chronograf#2315]
Right now, the query per second values in the mysql dashboard are wrong - they are scaled to the dashboard interval value. That's because `derivative` or `non_negative_derivative` must be used with a unit for the indicated value to be relevant.

![image](https://user-images.githubusercontent.com/971260/32606702-99d855b0-c556-11e7-9ae2-e9f9f30bd219.png)

**Comment by phemmer** [comment]
The time unit parameter of the `derivative()` function is the per-unit-rate you want the value displayed at. Meaning if you want foo/second, you'd do `derivative(foo,1s)`.
`derivative(foo, :interval:)` (if it worked) would be exactly the same as `difference(foo)`.

`derivative(max(foo),...)` is also not likely to give you what you want as that's going to calculate the rate between the 2 maximum points in each interval. You likely want to use `derivative(last(foo),...)`

**Comment by tanji** [comment]
@phemmer I gave the `derivative (max())` example because that's what you guys use in the canned mysql dashboard... I don't use it in mine, for what it's worth :)

**Comment by goller** [comment]
@tanji good point... do you have better queries?  

Would be great to make these queries better:
https://github.com/influxdata/chronograf/blob/master/canned/mysql.json

At the very least, should we add `1s`?

**Comment by tanji** [comment]
The queries are good in themselves, it's just that the displayed values are plain wrong. So, you need `1s` for sure, for the dashboard to return meaningful values.

**Comment by goller** [comment]
@tanji I've updated the dashboard in #2483.  Thanks again for the request! (Also, thank you @phemmer !)
