### ISSUE TITLE
Add role field to source creation when using auth

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2323]
Sources are now authorized by minimum role, so we need to add a `Role` field to the Manage Sources UI, with a default value of Viewer. Should simply be on the source object like `role: "viewer"` in the request body.

Be sure to send this value along with the POST request as well. Note that the server will make this default to Viewer if it's not included, so be sure to test it by changing the Role and check the server response.

This should only be a visible `isUsingAuth` (which is available at redux.`me.isUsingAuth`) is `true`.

Question for @nhaugo to clarify: can an `Editor` can set the minimum role for a new source that they create, such as to make a new source only be visible to `Editor`s and above?

**Comment by nhaugo** [comment]
only admins can change org info

**Comment by jaredscheib** [comment]
via convo with @nhaugo just now: for now, let's keep it at the original spec that Editors can add and update sources. no need to differentiate between Admin and Editor on this page.
