### ISSUE TITLE
Add Organizations to be set to only allow users via whitelist, and to reject others via 403

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2324]
We want to allow a SuperAdmin to determine that users cannot automatically authenticate into their instance and become a user, and instead new users can only happen via whitelisting.

@desa Thoughts on this from a technical perspective? The question is whether to do this as a CLI option or in the UI, and I'm wondering if doing it via the UI would mean that we'd have to actually add a new Role type of something like 'none', which might be a huge pain? Or maybe Orgs could just get a new field that selecting 'None' in the UI generates a special request?

**Comment by jaredscheib** [comment]
@nhaugo There will be a CLI option to make all newly authenticating users simply `member`s of the `Default` org, so they'd be stuck in Purgatory. Is that behavior sufficient? Or do you want us to block their authentication unless they've been whitelisted?

**Comment by nhaugo** [comment]
3. I want an option for users to get properly 403 rejected even if they are accepted by the provider.

**Comment by jaredscheib** [comment]
Ok thanks, so let's get @alexpaxton on the design for this to start.

**Comment by desa** [comment]
Opened https://github.com/influxdata/chronograf/pull/2347
