### ISSUE TITLE
Fix SuperAdmin toggle wiring when creating new user & incorrect status after created

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2326]
When you create a user, it shows that new user as having superadmin, and shows the superadmin at the top as toggled off. Upon refresh, it is correct.

This is at least partly (if not fully) because the SuperAdmin bool is not actually being sent in the POST request to create the user. It just needs a `superadmin: true|false` (bool) on the user model sent in the request body.

**Comment by 121watts** [comment]
also, the Chronograf `UserRow`super admin toggle doesn't toggle.  Will fix both.  PR incoming!
