### ISSUE TITLE
A POST to /users to create the same user from within different orgs should both be successful and additive

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2331]
In light of the revised Create User scheme: if the client submits a `POST` to `/users` to create a user within OrgB for a user that already exists with the same email::provider::scheme and is a member of OrgA, that should be a successful POST request and that user should now be a part of both orgs.

I'm not sure the server is currently working this way. Please confirm.

**Comment by desa** [comment]
This is how it currently works 👍

**Comment by jaredscheib** [comment]
Awesome - thanks
