### ISSUE TITLE
Remove PUT when a Dashboard Page loads because conflicts with Authorization

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2356]
Seems unnecessary and like a waste of bits over the wire. Plus it now will give a 404 for Viewer role users who cannot write data.

**Comment by 121watts** [comment]
@jaredscheib i only remember the issue vaguely.  but this was the solution to keep the template variables and their corresponding values in sync with the dashboard.

**Comment by nhaugo** [comment]
For 1.4.0 lets just remove the PUT for viewers, which means they will not be able to update template variables. Then for 1.4.1 we can come up with a solution that temporarily updates them for the session.
