### ISSUE TITLE
Windows hosts do not show up in host lists

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2360]

**Comment by cryptoquick** [comment]
I was able to confirm that windows hosts do indeed show up in the hosts lists in master as well as the multitenancy branch.

![screenshot 2017-12-06 08 50 09](https://user-images.githubusercontent.com/285690/33670667-d4c8f1e0-da62-11e7-8235-398acff264e1.png)
![screenshot 2017-12-06 08 50 01](https://user-images.githubusercontent.com/285690/33670669-d4e598b8-da62-11e7-8caf-e84cb5ea3045.png)
