### ISSUE TITLE
Trying to test #2364 i removed a user from google and all users from google were removed

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2370]
Reproduction steps
• Step up google oauth
• Do not specify a domain restriction
• Log in via gmail
• Log in via non-gmail google account
• Add github oauth
• login via github
• Remove a single google user 
• All google based users are gone

**Comment by jaredscheib** [comment]
Can you give repro steps? I just tried it via the UI and can't repro, and we're not sure how that would happen based on the code.

**Comment by desa** [comment]
Just gave this a try.  So far I've been unable to reproduce the issue.
