### ISSUE TITLE
[Feature Request] Multi Tenancy by Group of TickScripts

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#2372]
Use Case: We have different business units share a single Kapacitor instance. It would be really helpful if we can assign permission base on Group. Example:  We have Group1 only able edit/enable/disable an assigned set of TickScripts, while Group2 have permission on a different set of scripts.

**Comment by goller** [comment]
@nathanielc do you have ideas around multitenancy for kapacitor?

**Comment by nathanielc** [comment]
@goller We don't have anything set in stone yet, but @danyli78 ideas make sense. Assigning task ownership to groups and assigning users to groups. Seems pretty straightforward.
