### ISSUE TITLE
[Feature Request] Integration with Gitlab/Versioning for TickScripts

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#2373]
Use Case: We store all of our TickScripts in Gitlab repo, it would be great if Chronograf keep history version of the scripts or have some integration with Git vendors (e.g, gitlab). e.g, where you save a script and it auto upload to your git repo. Grafana also have a similar feature where they keep history of dashboard version and revert if needed.

**Comment by goller** [comment]
Hi @danyli78 I like this idea.  

@desa added loading tickscripts from directories for the upcoming kapacitor release (1.4).  However, I think it would be great if kapacitor itself could be integrated with gitlab.   

I'm imagining kapacitor exposing an API for the versions.  @nathanielc What do you think of that idea?

**Comment by nathanielc** [comment]
@goller Hmm, seems like integrating directly with git (or even gitlab/github) is too narrow. What about the ability to simply add labels to tasks? This way you could add a version label and manage the versioning externally to Kapacitor but still be able to query Kapacitor for the version it running.

**Comment by goller** [comment]
@nathanielc arbitrary labels would be fantastic.  There are several that I would add to the chronograf generated tickscripts (basically the variables I used to create 'em).

**Comment by nathanielc** [comment]
@goller You can already supply variables to TICKscripts. But yeah, since Chronograf does some DAG manipulation that can't be done with those vars.

**Comment by nathanielc** [comment]
Actually now that I think of it you could hack the vars to be labels for now.

```
// Unused var, but declares the version of the script
var version string

// Rest of script below
```

Then `kapacitor show task_name ` would display the version info.

**Comment by amittestkiwi** [comment]
Any update or solution yet.
