### ISSUE TITLE
View the logs on the host 

### ISSUE THREAD

**Issue by pshah** [influxdata/chronograf#2378]
the tickscript logs data to a log file for debugging purposes. We have a bunch of hosts which post data to an external endpoint. the payload is logged before being sent. 
A feature to show the list of hosts , and an ability to see the logs for each of them.

**Comment by goller** [comment]
Hey there @pshah, sorry for not writing back sooner!  It got buried in all the github issues :)

Actually, @cryptoquick just finished this !

https://github.com/influxdata/chronograf/pull/2188

It'll be in the next chronograf release.

However, you'll need to upgrade to the very latest kapacitor release candidate. At the moment that is rc1: https://dl.influxdata.com/kapacitor/releases/kapacitor-1.4.0~rc1_darwin_amd64.tar.gz
