### ISSUE TITLE
As a viewer, i shouldn't see any configure kapacitor buttons in the chronograf ui

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2381]
i can still see the buttons on the status page and the alerts page.

**Comment by jaredscheib** [comment]
I don't think a Viewer is restricted from interacting with Kapacitor. Thoughts, @nhaugo? Should a Viewer be able to configure a Kapacitor via the Chronograf client? They can't add a Source.

**Comment by nhaugo** [comment]
As you mentioned, they should not be able to manipulate the source, however, in the editor that can set "per script settings"

**Comment by jaredscheib** [comment]
Looks like the original issue here was solved by https://github.com/influxdata/chronograf/issues/2421. Closing until further notice.
