### ISSUE TITLE
Unhandled promise rejection when logging into Chronograf from Firefox

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2382]
Browser: Firefox Quantum 57.0 (64-bit)
repro steps: With multi tenancy turned on, attempt to Oauth2 authenticate with Github. You will see this error screen.

<img width="1548" alt="screen shot 2017-11-15 at 2 26 33 pm" src="https://user-images.githubusercontent.com/4805997/32863748-65e1abfc-ca11-11e7-9d2a-657245325cb2.png">

`Unhandled promise rejection 
TypeError
columnNumber: 4
fileName: "http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js"
lineNumber: 10469
message: "oldNode.parentNode is null"
stack: "replaceChildWithTree@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:10469:4\ndangerouslyReplaceNodeWithMarkup@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:10908:8\ndangerouslyReplaceNodeWithMarkup@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:10294:6\n_replaceNodeWithMarkup@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16278:6\n_updateRenderedComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16268:8\n_performComponentUpdate@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16218:6\nupdateComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16139:8\nreceiveComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16041:6\nreceiveComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8401:6\n_updateRenderedComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16248:8\n_performComponentUpdate@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16218:6\nupdateComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16139:8\nreceiveComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16041:6\nreceiveComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8401:6\n_updateRenderedComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16248:8\n_performComponentUpdate@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16218:6\nupdateComponent@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16139:8\nperformUpdateIfNecessary@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:16055:8\nperformUpdateIfNecessary@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8433:6\nrunBatchedUpdates@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8020:6\nperform@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:9321:14\nperform@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:9321:14\nperform@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:7959:13\nflushBatchedUpdates@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8042:8\ncloseAll@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:9387:12\nperform@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:9334:12\nbatchedUpdates@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:18538:15\nenqueueUpdate@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:8070:6\nenqueueUpdate@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:17508:4\nenqueueSetState@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:17693:6\nReactComponent.prototype.setState@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:2119:4\nhandleChange@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:22478:10\ndispatch@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:22863:8\nresizeLayout/</<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:11179:8\nqueryStringConfig/</<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:11215:8\nerrorsMiddleware/</<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:10440:8\nrouterMiddleware/</</<@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:30692:19\nthunkMiddleware/</<@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:30725:75\ndispatch@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:23596:19\nerrorsMiddleware/</<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:10424:12\nrouterMiddleware/</</<@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:30692:19\nthunkMiddleware/</<@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:30725:75\nbindActionCreator/<@http://116ce917.ngrok.io/vendor.65d9516bc210504b8e65.dev.js:23502:13\n_callee$@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:20865:16\ntryCatch@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:380:38\ninvoke@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:671:23\ndefineIteratorMethods/</prototype[method]@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:432:17\nstep@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:1024:23\nstep/<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:1035:14\nrun@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:1935:23\nnotify/<@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:1948:29\nflush@http://116ce917.ngrok.io/app.eb770d4ad777f9141617.dev.js:2395:10\n"
__proto__: Object { stack: "", … }`

**Comment by jaredscheib** [comment]
This may have been resolved -- are you still experiencing it, @russorat?

**Comment by russorat** [comment]
@jaredscheib tested on firefox 57.0.2 (64-bit) and i'm no longer seeing this issue. thanks.
