### ISSUE TITLE
Add Azure to OAUTH

### ISSUE THREAD

**Issue by Andy--Rose** [influxdata/chronograf#2387]
Please add Azure to supported Oauth providers. 

Andy Rose
The Trade Desk

**Comment by goller** [comment]
Hey @Andy--Rose , thanks for writing in!

@kevinhogan111 did you end up figuring out the right settings for this?  Or does chronograf need direct support for azure?

**Comment by kevinhogan111** [comment]
We weren't able to able to find the right settings to get this working.  The error I kept getting was: `level=error msg="Unable to exchange code for token oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_resource\",\"error_description\":\"AADSTS50001: Resource identifier is not provided.`

We think chronograf may need something similar to `bmorton` mentions in their comment from March 24rth here: https://github.com/golang/oauth2/issues/112

**Comment by goller** [comment]
@kevinhogan111 what command-line options did you try?

**Comment by tyauvil** [comment]
@goller I do believe that Chronograf is going to need Azure specific configuration, specifically the `resource` parameter.

This discussion on adding Azure to the bitly/oauth2_proxy should be relevant: https://github.com/bitly/oauth2_proxy/pull/170

**Comment by goller** [comment]
@tyauvil great! I'm on it.

**Comment by kevinhogan111** [comment]
test acct configs we were playing around with: 

GENERIC_TOKEN_URL=https://login.microsoftonline.com/400951d9-1fca-4414-b6b3-568f8270d6f9/oauth2/token

GENERIC_AUTH_URL=https://login.microsoftonline.com/400951d9-1fca-4414-b6b3-568f8270d6f9/oauth2/authorize?resource=72ce7825-90bc-46c0-92f9-5a10a88699ca

GENERIC_CLIENT_ID=8137cbaa-afa2-47f8-acb3-66f4c3071b96

#TOKEN_SECRET=iJmjMxtkk/YhE/UQD7CN+gQL6yGIKpbd3wPSKFd84Ns=

PUBLIC_URL=http://h6u3t2z47mznemxn.influxdata.com

GENERIC_CLIENT_SECRET=iJmjMxtkk/YhE/UQD7CN+gQL6yGIKpbd3wPSKFd84Ns=

**Comment by goller** [comment]
Ok, I have a PR #2400 up for review.  I've added another option to allow override for oauth api url responses.  The default is `email` but azure is `userPrincipalName`.

I'm thinking about making azure specific options, but, PR #2400 rounds out the generic oauth feature.
