### ISSUE TITLE
Issue 403 Forbidden if user's current organization no longer exists

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2393]
If I delete my current organization, I get a `500 (Internal Server Error)` with message `"Unknown error: organization not found"` upon the next `GET` on `/me`. If I was signed into that organization and deleted it, I can't load the app again due to this same error.

- [ ] fix current organization on context in this case (presumably that's the problem)
- [ ] confirm that currentOrganization is also not persisted to the database

**Comment by desa** [comment]
This can be handled by the client

Server can be friendlier and return

* better status code
* better error message
