### ISSUE TITLE
Disallow creating an organization by the same name as one that exists

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2402]
If an organization is created by the same name as one that already exists, but are removed from the UI and an error notification occurs. Instead, the original should not disappear and the user should receive an error notification (as is done throughout the rest of the app). Alternately, we could establish a new pattern of simply disabled `Enter` key and `Confirm` unless organization name is new, unique, and valid.

**Comment by nhaugo** [comment]
See also #2226
