### ISSUE TITLE
Complete dygraphs millisecond PR & re-depend upon dygraphs as dependency

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2413]
- [x] write unit test for https://github.com/danvk/dygraphs/pull/777
- [x] test Chronograf against new dygraphs master as dependency, instead of our fork
- [x] publish new dygraphs package on npm
- [x] update Chronograf to depend on newly published dygraphs

**Comment by lukevmorris** [comment]
Pending PR: https://github.com/danvk/dygraphs/pull/893
