### ISSUE TITLE
On sources config, viewers should not be able to switch the active kapacitor

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2422]

**Comment by jaredscheib** [comment]
The `<Authorized>` wrapping the `<Dropdown>` in `kapacitorItems` in `InfluxTable` should be refactored to have a `replaceWithIfNotAuthorized` that simply shows some kind of `<span>`. `requiredRole` remains `EDITOR_ROLE`. It'd be good to have designs and/or the UI for this done by @alexpaxton.

**Comment by alexpaxton** [comment]
![screen shot 2017-12-11 at 4 56 49 pm](https://user-images.githubusercontent.com/2433762/33861862-d562b074-de94-11e7-94ff-4ebc1a560910.png)

Created a branch for this - `2422-disallow-viewer-switch-kapacitors`
If there is no additional work I can create a PR

**Comment by jaredscheib** [comment]
Yep. Viewers can only see the active one but not change it. Editors and above can change, add. etc. Looks good to me – PR away~
