### ISSUE TITLE
Improve copy for better UX within Purgatory

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2431]
Upon first login, if a user successfully authenticates but is only a `member` in the Default organization, I don't think they will understand:
- [ ] what `Authenticated in 1 Organization oauth2/github` means
- [ ] what `Default` means
- [ ] what `Member` means
- [ ] what `don't have access` as member means
- [ ] how to contact administrator -- provide link? email?
- [ ] Purgatory says `Log in` but everywhere else that a user switches organization we use the terminology `Switch to` (and the user is already "Logged in" if they've authenticated successfully, it seems to me)
<img width="1440" alt="screen shot 2018-01-12 at 6 41 24 pm" src="https://user-images.githubusercontent.com/6403018/34902033-395cb5a6-f7c8-11e7-9e83-56c7f7586655.png">

**Comment by russorat** [comment]
let's wait to get additional feedback from users before we start optimizing this page. de-prioritizing for now.

**Comment by makrste** [comment]
I think this will be really useful. I have the following use case: 

1. A user is logged in that has only `member` role in chronograf but `admin` role in the main product. 
2. This user then navigates to chronograf but can't do anything and lands in purgatory. 
3. The user clicks on `Log out` and gets redirected to the `/login` page of chronograf.
4. User clicks on `Login with Provider` again, but the session still exists, so the user is redirected directly to purgatory. 

I think at least another `CUSTOM_LINK` is required which would enable the user to directly log out from the Identity provider and end the session.
