### ISSUE TITLE
Hide ability to change permissions on data sources per org

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2434]
Either:
The UI for this in the configuration should be hidden, all data sources the user creates or migrates should be given the most permissive role possible (i'm guessing member). (Don't worry about data sources created in the multitenancy branch)

Or
Tear out the data sources tied to roles entirely

**Comment by jaredscheib** [comment]
After discussion:

Make the Required Role for all sources `Viewer`, and don't allow that to be changed. That way `Member` still means something -- they don't have access to sources. But all users in an organization who are Viewers and above will see all sources. Don't tear out the feature.

**Comment by jaredscheib** [comment]
- [ ] remove the UI for setting a role on a source, and hard-code it to viewer behind-the-scenes
- [ ] make role on sources JSON omitempty & empty string on resource; leave the other code around it for now
