### ISSUE TITLE
When user email is shorter than SuperAdmin status label, make nav width equal to SuperAdmin status label on one-line

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2436]
Seems like keeping the width of the user nav to be a one-line SuperAdmin label would look nicer:
<img width="294" alt="screen shot 2017-11-29 at 4 08 56 pm" src="https://user-images.githubusercontent.com/6403018/33406014-b5e5f6f8-d51f-11e7-8981-a0c773093678.png">

Thoughts @alexpaxton ?

**Comment by nhaugo** [comment]
I'm not sure this belongs in the menu bar at all, it is not relevant to the user unless they are in the config screen. Can we find somewhere to put it there and remove this from the menu?
