### ISSUE TITLE
Exponential / scientific notation in chart axis labels for canned layouts

### ISSUE THREAD

**Issue by duffyjp** [influxdata/chronograf#2439]
![screen shot 2017-11-30 at 8 35 48 am](https://user-images.githubusercontent.com/382216/33436198-0aae2342-d5aa-11e7-9d78-8300b6ef8c63.png)

Mac High Sierra
```bash
🍕  ~ 14:13$ brew list chronograf
/usr/local/Cellar/chronograf/1.3.10.0/bin/chronograf
/usr/local/Cellar/chronograf/1.3.10.0/homebrew.mxcl.chronograf.plist
🍕  ~ 14:13$ brew list telegraf
/usr/local/Cellar/telegraf/1.4.4/.bottle/etc/telegraf.conf
/usr/local/Cellar/telegraf/1.4.4/bin/telegraf
/usr/local/Cellar/telegraf/1.4.4/homebrew.mxcl.telegraf.plist
```

**Comment by goller** [comment]
Hi @duffyjp, thanks for writing in!

Here is an animated gif about how to turn on log scaling and change the units:
![exponential](https://user-images.githubusercontent.com/1922921/33446520-e94d0026-d5c5-11e7-8817-fbe5f9bfb9ce.gif)

Does this give you what you need?

**Comment by duffyjp** [comment]
I'm actually seeing this occur right in the canned charts. It looks like for very very small values. See the Disk chart for this idle server:

![screen shot 2017-12-01 at 3 22 18 pm](https://user-images.githubusercontent.com/382216/33504042-8d7c2268-d6ab-11e7-9d33-c39f3754baa6.png)

**Comment by goller** [comment]
@duffyjp Ah! Just checked... looks like we don't support it in layouts yet.  We really should add it.

(I'll change the title of this issue to mention that we need log scale support in canned dashboards)

**Comment by russorat** [comment]
connect #2962
