### ISSUE TITLE
Alert creation for boolean values fails due to conversion problem

### ISSUE THREAD

**Issue by wieki** [influxdata/chronograf#2455]
When creating a rule that tries to compare to a boolean value, the threshold value is converted to a string value, i.e. in my case events are provided that determine if a service is up or down, this value is represented by TRUE or FALSE. When you create a rule in Chronograf that looks like: "Send Alert when last is equal to FALSE". The FALSE value is regarded as a string which make the rule fail, without apparent warning expect in the log, where are conversion error appears:

```E! error evaluating expression for level CRITICAL: mismatched type to binary operator. got boolean == string. see bool(), int(), float(), string(), duration()```

Preferable behavior would be to parse TRUE and FALSE to boolean values and use them accordingly.

I'm running Chronograf 1.3.10 in the provided Docker container.

**Comment by goller** [comment]
Hi @wieki , good point!  I whipped up pull request #2456 

It checks for the `TRUE` or `FALSE` literal and interprets them as booleans.  If the PR review goes well, it should be in the next release.
