### ISSUE TITLE
Building kapacitor rule without kapacitor loads "forever"

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2458]
- [ ] when a kapacitor instance is not configured, display a message to the user and point them to the kapacitor configuration page

It hangs on "Loading Rules..."
<img width="955" alt="image" src="https://user-images.githubusercontent.com/1922921/33495636-d765b8ae-d68c-11e7-9fc1-01ff220729ea.png">

**Comment by russorat** [comment]
💯 💯 🌈
