### ISSUE TITLE
Docs endpoint doesn't seem to respect base_path and prefix_routes

### ISSUE THREAD

**Issue by austinbutler** [influxdata/chronograf#2459]
I have NGINX configured to server Chronograf at /chronograf and so I have set `BASE_PATH=/chronograf` and `PREFIX_ROUTES=true`, but when I load /chronograf/docs I see "Loading" with a spinner on the page, with the following in the console and it never loads.

```txt
ReDoc initialized!
GET https://192.168.60.3/swagger.json net::ERR_RESPONSE_HEADERS_TRUNCATED
```

I would expect it to request /chronograf/swagger.json instead, and indeed if I request that URL manually it loads the Swagger JSON.

Note that everything else works fine in the main Chronograf UI at /chronograf.

**Comment by goller** [comment]
hm yup, we've had several issues with basepath... 

Looks like we need to add basepath here: 
https://github.com/influxdata/chronograf/blob/master/server/mux.go#L72
