### ISSUE TITLE
Polish on Viewer version of empty state on Dashboards page

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2464]
how a Viewer sees the empty state of a Dashboards page:
<img width="1306" alt="screen shot 2017-11-30 at 8 59 56 pm" src="https://user-images.githubusercontent.com/6403018/33499361-7926cd1c-d689-11e7-8cd5-dd92a1a34471.png">

**Comment by alexpaxton** [comment]
** Viewer sees:**
![screen shot 2017-12-01 at 4 17 31 pm](https://user-images.githubusercontent.com/2433762/33509065-682e8e3a-d6b3-11e7-8957-571ff83d8a7f.png)
(Vertically centered, spacious)

**Editor+ sees:**
![screen shot 2017-12-01 at 4 18 42 pm](https://user-images.githubusercontent.com/2433762/33509074-77b2c0ba-d6b3-11e7-9487-cf9fa9badb9b.png)

**Comment by jaredscheib** [comment]
looks great!
