### ISSUE TITLE
Create CRUD and Auth flow API integration tests

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2487]
> What do you think about – in future work – creating a sequence where we simulate what a user who upgrades will experience, and thus try creating users and organizations, changing superadmin-first-user-only, having other users log in, etc.?

Related https://github.com/influxdata/chronograf/pull/2446#pullrequestreview-80396985
Related to #2239 as well.

TODO:

- [ ] Add Users tests
- [ ] Add Organizations tests
- [ ] Add Servers tests
- [ ] Add Layouts tests
- [ ] Add Sources tests
- [ ] Add Me tests
- [ ] Add Dashboards tests

**Comment by jaredscheib** [comment]
Be sure to cover all of the bullet points in #2239.

**Comment by desa** [comment]
@russorat (aka savage) I'm less concerned with this now than when I opened the issue originally. These parts of the codebase are pretty untouched. It might be worthwhile to hold off until there's active development in this area again.

**Comment by desa** [comment]
@russorat I'm not sure what the plan for integration testing will be in 2.0. This will likely require the coordination of multiple parties. How should I proceed?
