### ISSUE TITLE
Gauge Issues and Polish

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#2491]
- Gauge numbers disappear at widths below 1130px, see below:
![screenshot 2017-12-05 14 10 35](https://user-images.githubusercontent.com/285690/33631577-3b633afa-d9c8-11e7-946b-b80c4f782ad4.png)
- Noticed that multiple series don't get displayed, which makes some sense, but isn't obvious at first
- Also, you need to use a fill to previous to get anything
- Stays zero with linear fill, which is strange
- None fill has a decent value, however, which is also strange...?
- Add Gauge Controls button to upper right so it can be clicked more easily

Feel free to add more items here as this feature gets more use.

Connect #2410

**Comment by russorat** [comment]
Also, noticed that the text format changes after a hard refresh, then updates after the first interval.

![kapture 2018-01-11 at 13 14 01](https://user-images.githubusercontent.com/4805997/34847809-6d840b74-f6d1-11e7-97ae-5375b68fee4e.gif)

**Comment by russorat** [comment]
connect #2695

**Comment by russorat** [comment]
@alexpaxton what's left to do on this one? i think this is all fixed.
