### ISSUE TITLE
FuseBox & TypeScript Part II

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#2498]
Let's take what we learned from the spike on TypeScript, #2275 , and apply them towards a more gradual rollout of the language throughout our codebase. This starts with adding the Fuse Box build, which should be good to go and simple enough to carry over as a replacement for Webpack and Babel. (To be clear, Fuse Box replaces Webpack, and tsc, the TypeScript compiler, replaces Babel).

This will be an ongoing, Chronograf team-wide project. I'd prefer there to be many small PRs, rather than one big branch. There are several areas of the codebase that we can split up on, and we can streamline our PR process for the refactors, as opposed to more thorough PRs for new features or bugfixes. That said, PR review should be just as diligent as we should be with any PR review, since code will be changed, and we'll need to validate that it worked the same as before.

All that sound good, team?

**Comment by jaredscheib** [comment]
So simply adding Fusebox as the first issue? And then have a second step being adding a single instance of use of TypeScript?

**Comment by goller** [comment]
@cryptoquick I think it would be great to start with fusebox.  Will there be some need to change how the build wraps up `ui/build` ?

**Comment by cryptoquick** [comment]
@goller We actually have most of the work done to add tsc and Fuse Box to the repo, but yep, that was the last part we were working on. Let's connect on this at some point today, to discuss the best solution.

**Comment by jaredscheib** [comment]
Closed by #2824.
