### ISSUE TITLE
Cannot Get Alert History Page to show for custom alerts

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#2500]
I created I TICKscript manually and added the `|influxDBOut` section to my alert just like its in the Chronograf rules. I have it writing data to the `chronograf.autogen.alerts` measurement like any other Chronograf rule.

When I navigate to the alert history section I do not see any of my alert events. I can see them in the `alerts` measurement.

It there a check or something that prevents alert history events from custom rules showing up?

**Comment by alexpaxton** [comment]
Lucky number 2500

**Comment by goller** [comment]
@nathanielc here is the offending line of code:

https://github.com/influxdata/chronograf/blob/7f54f987d37f99b3c447a1183049cc7de97e43f3/ui/src/alerts/apis/index.js#L6

which is

```javascript
export const getAlerts = (source, timeRange, limit) =>
  proxy({
    source,
    query: `SELECT host, value, level, alertName FROM alerts WHERE time >= '${timeRange.lower}' AND time <= '${timeRange.upper}' ORDER BY time desc ${limit
      ? `LIMIT ${limit}`
      : ''}`,
    db: 'chronograf',
})
```

Do you mind trying out that query and we'll see what is going on?

**Comment by mehtasagar** [comment]
Hello, I am facing the same issue. Is there any update about the suggested solution or any other fix for it ?

**Comment by russorat** [comment]
@mehtasagar could you add your InfluxDBOut node definition here and we can help figure out why it's not showing up for you?

**Comment by mehtasagar** [comment]
@russorat  Thanks for your response. Here is my influxDBOut node definition: 
    |influxDBOut()
        .database('chronograf')
        .measurement('alerts')
        .tag('threshold', 'Sandbox')
        .tag('alertName', 'cpu_usage')

Kindly let me know if you need more info.

**Comment by rolandjitsu** [comment]
I'm also having the same issue with the following tick script:
```tick
// https://docs.influxdata.com/kapacitor/v1.5/working/alerts
// https://www.influxdata.com/blog/combining-kapacitor-and-continous-queries/
// https://www.influxdata.com/blog/batch-processing-vs-stream-processing/
batch
    // Select the cpu_p measurement from our fbit database
    |query('SELECT mean(cpu_p) FROM "fbit"."autogen"."cpu"')
        .period(10s)
        .every(10s)
        .groupBy(time(10s))
    |alert()
        .crit(lambda: "mean" > 0.5)
        // .message('{{ .Time }}: CPU usage over 0.5%')
        // Send alerts to the `cpu` topic
        .topic('cpu')
    |influxDBOut()
        .create()
        .database('chronograf')
        .measurement('alerts')
        .tag('alertName', 'CPU ALERTS FROM FUBAR')
        .tag('triggerType', 'custom')
```

**Comment by hflamboauto1** [comment]
Same issue here .. no history for batch :(((((( is this fixed now?

**Comment by shumintao** [comment]
is this fixed now?

**Comment by ajshsu** [comment]
For me, I found that the issue was not writing the measurement used for the alert into the `value` field in `chronograf.autogen.alerts` 

Looking at the tick scripts generated by Chronograf, the trigger also takes the measurement value and saves it under value using an `eval` node.

```
trigger
    |eval(lambda: float("cpu"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)`
```
Adding the eval node is what worked for me.

**Comment by himanshuganatra** [comment]
@ajshsu This did not work for me, below is my `influxDBOut()`

`trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)`
