### ISSUE TITLE
As a Viewer I should see current template variables values when viewing a Dashboard

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2510]
Stopgap RBAC guard logic was added to DashboardPage in #2480 to prevent Viewers from making a PUT request when a dashboard loads, which was otherwise resulting in a logout event because Viewers would receive a 403 Forbidden upon a PUT request.

We need a way to Viewer users to get the current values of template variables, without having to write to a dashboard.

**Comment by russorat** [comment]
#3253
