### ISSUE TITLE
improve the "adding org that already" experience 

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2515]
It would be better to notify the user that the org already exists and then allow them to change it instead of removing it altogether.

![kapture 2017-12-07 at 17 00 55](https://user-images.githubusercontent.com/4805997/33777704-b4f029da-dbfa-11e7-8e66-e40aaaade44b.gif)

**Comment by jaredscheib** [comment]
This is related to https://github.com/influxdata/chronograf/issues/2471.

I agree that a nicer UX is merited. So you'd rather the new entry remain and go back into editing mode?

cc @alexpaxton

**Comment by russorat** [comment]
as a user, i'm used to seeing a warning and then allowing me to edit the offending field, not having to start over from scratch.

**Comment by alexpaxton** [comment]
I am imagining something where the error appears inline with the form, and it stays focused on the field so the error can be corrected
