### ISSUE TITLE
.undefined for y-axis on some graphs

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2516]
Not sure why, but i noticed that the y-axis in some of my dashboard graphs were showing .undefined.

Even after updating the graph to another name, and then selecting the "auto" toggle again, it went back to undefined.

Opening the query editor and pressing enter in the query window corrected the issue.

![screenshot at dec 08 09-35-58](https://user-images.githubusercontent.com/4805997/33777892-65ccdfa0-dbfb-11e7-8780-d803a321efe8.png)
![screenshot at dec 08 09-35-19](https://user-images.githubusercontent.com/4805997/33777894-65e540c2-dbfb-11e7-94fb-d02de14c0022.png)
![screenshot at dec 08 09-34-17](https://user-images.githubusercontent.com/4805997/33777895-65fd7bf6-dbfb-11e7-88a4-72f1af007a4f.png)

Fixed after pressing enter in the query window:
![screenshot at dec 08 09-41-15](https://user-images.githubusercontent.com/4805997/33778068-f6712aac-dbfb-11e7-9ce2-a1e971f1def9.png)

**Comment by 121watts** [comment]
This appears to be a bug with the parsing / saving of `queryConfigs` from a query string that contains a template variable in the `tagValue` location of the query string.  

### Repro Steps
1. Using the `telegraf` database create a list of `tagValue` type template variables from `tagKey` `cpu`:

![screen shot 2017-12-12 at 2 59 26 pm](https://user-images.githubusercontent.com/7582765/33913078-32709124-df4d-11e7-9b47-aac024c4a860.png)

3. Build a dashboard cell with this query: `SELECT mean("usage_user") AS "mean_usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND "cpu"=:cpu: GROUP BY :interval: FILL(null)`

4. Save the cell
5. Reopen the Cell Editor and see a queryBuilder with no measurements or fields listed and a jacked up y-axis title.

### Notes
Inspecting the network tab, the initial POST to `/queries` validation returns with a full queryConfig, AST etc.  When checking out the `PUT` `dashboards/<dashboardID>/cells/<cellID>` the full queryConfig and query string get sent but the endpoint returns an empty `queryConfig`.
