### ISSUE TITLE
as a user, i would like to quickly jump between sources when building queries

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2517]
feedback from a user: When i'm building queries in the query builder, and i have multiple sources of data, sometimes i need to jump to a different source to find the information i'm looking for. It would be convenient to be able to jump between sources without leaving the query builder page.

**Comment by lukevmorris** [comment]
@russorat Just to clarify -- this is in the Data Explorer?

**Comment by russorat** [comment]
They were talking specifically about the data explorer, but I could see it being useful in the hostlist page as well.

**Comment by russorat** [comment]
now part of #4021

**Comment by russorat** [comment]
this is in 1.7
