### ISSUE TITLE
Upon first login as non-first superadmin to remote cluster instance, navigating to Organizations tab and then Data Explorer fails

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2521]
Repro:
1. Login as non-first user on a fresh install
1. Navigate to Admin/Chronograf
1. Try to navigate to Data Explorer
1. Check console:
<img width="1440" alt="screen shot 2017-12-08 at 12 42 20 pm" src="https://user-images.githubusercontent.com/6403018/33784371-79f650dc-dc15-11e7-8a2e-5927af7cb6b4.png">

**Comment by jaredscheib** [comment]
This may have been related to https://github.com/influxdata/chronograf/issues/2527.

**Comment by nhaugo** [comment]
May be dupe of #2606
