### ISSUE TITLE
Unable to switch organizations from Manage Sources page

### ISSUE THREAD

**Issue by ono760** [influxdata/chronograf#2523]
When clicking on an organization, if there's no source attached to it, we get asked to select source. But if I don't want to select a source and instead decide to go back and select another organization, I am not able to go back/forward to select another org. Closing/refreshing browser (Chrome) doesn't help. I need to be in incognito mode to accomplish this.

**Comment by nhaugo** [comment]
As a temporary fix lets add a "switch org" button that logs the user out and dumps them to purgatory

**Comment by alexpaxton** [comment]
![screen shot 2017-12-11 at 4 34 09 pm](https://user-images.githubusercontent.com/2433762/33861197-66e05aaa-de91-11e7-95e8-03031caa8b17.png)

Created a branch with this UI on it, just needs to be wired up:
`switch-orgs-from-manage-sources`

**Comment by lukevmorris** [comment]
@alexpaxton @nhaugo if there are no orgs to switch to, should we hide the button and force the user to add a source?

**Comment by jaredscheib** [comment]
that would be consistent with current behavior. but we could also offer a "Logout".

**Comment by jaredscheib** [comment]
Switch Orgs is intended here to take you to Purgatory. we could keep it that way and add a logout to purgatory.
