### ISSUE TITLE
Edit home page on chronograf

### ISSUE THREAD

**Issue by leomag** [influxdata/chronograf#2525]
Perhaps editing the home page chronograf, I would like to place a dashboard there.

Also, interesting to edit the menu itself, remove something from the menu.

**Comment by goller** [comment]
Hey there @leomag, thanks for writing in!  I like the idea of editing the homepage a lot.

Regarding menus, this isn't exactly what you want, but, you can add more menu items to the user menu.  Do you mind adding another issue for menu customization?

From the CLI or env: 

```      --custom-link=                          Custom link to be added to the client User menu. Multiple links can be added by using multiple of the same flag with different 'name:url' values, or as an
                                              environment variable with comma-separated 'name:url' values. E.g. via flags: '--custom-link=InfluxData:https://www.influxdata.com
                                              --custom-link=Chronograf:https://github.com/influxdata/chronograf'. E.g. via environment variable: 'export
                                              CUSTOM_LINKS=InfluxData:https://www.influxdata.com,Chronograf:https://github.com/influxdata/chronograf' [$CUSTOM_LINKS]

```

**Comment by leomag** [comment]
Thank you, @goller, for the answer!
And yet, what on editing the main page, how it is possible to place there a dashboard?
Looked at what you wrote, you can visually show how to add additional menu items? :)
Issue of edit the menu created.
