### ISSUE TITLE
Query editor does not work after using query template

### ISSUE THREAD

**Issue by hoavxtech** [influxdata/chronograf#2527]
**Environment**: Nightly Chronograf on Ubuntu 16.04 64-bits
**How to reproduce**: Click Data Explorer -> Click on the drop down "Query Template" -> select SHOW DATABASES
The result table is empty. It should list all existing databases. The issue also happens with other query templates

**Comment by goller** [comment]
@hoavxtech thank you for reporting this!  I've just created a fix in PR #2528

**Comment by goller** [comment]
@hoavxtech we've just made the fix and it'll be in the next release!
