### ISSUE TITLE
Improve help tooltip for "Public" flag

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2532]
@stevebang seems like this text is referencing true/false, yet the button is a toggle. Should we use something like on/off instead of true/false in the help text?

![screen shot 2017-12-11 at 10 08 31 am](https://user-images.githubusercontent.com/4805997/33846348-49d31b04-de5b-11e7-872d-d3111581dcaa.png)

**Comment by stevebang** [comment]
Typical users would not think T/F, so on/off would be create less cognitive friction. Administrators might be fine with that terminology. Maybe something like this:

"When set to off, administrators must add a user before being allowed to authenticate."

If you can avoid saying Admin (or any role label), that would be better. Roles and groups can be distinct.

Also, I noticed here and elsewhere that you center-align the text -- I think the text should be left-aligned for easier readability. Centering is typically only useful for headings.

**Comment by jaredscheib** [comment]
Thanks!
