### ISSUE TITLE
Delete & Remove confirmations inconsistent

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2533]
Sometimes the confirmation is on the left, and sometimes the confirmation is on the right. We should standardize this across the app.

![kapture 2017-12-11 at 10 23 30](https://user-images.githubusercontent.com/4805997/33846852-59e343dc-de5d-11e7-9bc8-9001909f0483.gif)

**Comment by jaredscheib** [comment]
I think it would also be good to require a deeper confirmation for deleting an organization, since that will cause all of its associated user roles and resources to be deleted as well. It's quite easy to do this, currently.

**Comment by alexpaxton** [comment]
https://github.com/influxdata/chronograf/issues/3011
