### ISSUE TITLE
Alert Handlers: Add support for adding an arbitrary number of post headers. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2534]
Kapacitor can handle an arbitrary number of post headers with user defined key:value pairs Chronograf should as well.

**Comment by nhaugo** [comment]
@alexpaxton can you sync with @ebb-tide on the design needs for this

**Comment by whyou5945** [comment]
@nhaugo hey, has this function be ready already? How can I add multi header keys on chronograf?
