### ISSUE TITLE
Refactor Alert Handler Configuration Page.

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2535]
- [x] Enable linking to individual configuration panels so that links from the rule builder can go to appropriate panel. 
- [x] Remove promise pattern to async await (as cryptoquick mentions below), remove refs
- [x] Address the console error: (addressed in https://github.com/influxdata/chronograf/pull/2702)
![screen shot 2018-01-04 at 4 17 06 pm](https://user-images.githubusercontent.com/10937678/34625386-55c3ac7e-f20d-11e7-886d-dfb8ebd51cb3.png)

**Comment by cryptoquick** [comment]
Let's also refactor Kapacitor Rules to async/await, if that sounds good.

**Comment by russorat** [comment]
Acceptance testing complete.
