### ISSUE TITLE
Alert Handlers: dropdown should indicate which alert handlers are configured

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2536]
Show configured alert configs either separately or with checkmark to indicate their configuredness in dropdown.

**Comment by ebb-tide** [comment]
I can't decide if it is helpful or distracting to have an icon preceding the handler name. This circle is too large obvs, perhaps a smaller one? should the text be bold instead? need @alexpaxton !!  :)
![Screen Shot 2018-01-02 at 11.03.40 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59aef2da98edd80012b225b8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454f16b7191a379ee0c2b52415b4ebc30254d58eeb9cb74fce36f34985619e8d63e0a20923817f9ed864dbd02bd768b4ed3b6badc4ac7fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae54457a5103263e774366e0a.png)

**Comment by ebb-tide** [comment]
![Screen Shot 2018-01-02 at 3.02.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59aef2da98edd80012b225b8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454f16b7191a37bf112294f5f575ecc3c4a4356bcbbd671f3e57862804e0eea82380b20c33b44f9bcd01dbc06ec208a1985b0ea8c4bd2f42f67b6d5db1063474f4dcbed5727a19141c95df74ee14c56ad163266e77f2431.png)

**Comment by russorat** [comment]
#2409
