### ISSUE TITLE
Default role is not meaningful if Organization is not Public

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2537]
We should maybe disable or hide the Default Role dropdown if Public is toggled on:
<img width="254" alt="screen shot 2017-12-11 at 10 57 46 am" src="https://user-images.githubusercontent.com/6403018/33849454-7a75641a-de65-11e7-87f2-8fdeafe23e65.png">

**Comment by nhaugo** [comment]
The default role should be what is auto selected for users in the user config screen
