### ISSUE TITLE
SuperAdmin should not be logged out when trying to switch into another organization where they don't have a role

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2539]
As a SuperAdmin, try to switch into an organization where you are not a member, and you'll be logged out due to a 403 Forbidden, with message `user not found`. This is a jarring UX. What should happen instead?

**Comment by jaredscheib** [comment]
My vote currently is that we don't put a `Switch to` button next to any organizations that they're not a user in.

**Comment by nhaugo** [comment]
Option 1 please

**Comment by jaredscheib** [comment]
Upon further reflection, this would be the first time that a SuperAdmin _can't_ do something. If they can't switch into _any_ organization, even one where they don't have a role, then they can't effectively manage that organization.

I think that instead of my first suggestion above (removing `Switch into`), we should instead give that SuperAdmin an Admin role in any organization that they switch into where they previously didn't have a role.

**Comment by desa** [comment]
>If they can't switch into any organization, even one where they don't have a role, then they can't effectively manage that organization. 

I think the point of super admins is to manage the application, not specific organizations. There will be at least one administration, either an Admin or a SuperAdmin, that is a member of any organization. They should be perfectly capable of managing that organization.

**Comment by jaredscheib** [comment]
Hm, I can see that perspective too. I'll stick to the current story and leave this to a larger discussion.
