### ISSUE TITLE
As a User I can set a suffix or prefix on a single-stat visualization

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2547]
![screen shot 2017-12-11 at 3 43 17 pm](https://user-images.githubusercontent.com/2433762/33860134-18fba93e-de8c-11e7-8a7c-d9b665190967.png)

Seems useful. Needs a separate key on `colors` instead of repurposing the y-axis suffix/prefix

**Comment by alexpaxton** [comment]
Probably needs #2567 to be worth developing

**Comment by cryptoquick** [comment]
+1 would like to prefix with $ 😸

**Comment by russorat** [comment]
- [ ] ability to add prefix and suffix to single stat graph
- [ ] ability to add prefix and suffix to line + single stat graph
- [ ] ability to add prefix and suffix to guage (#2779 )
