### ISSUE TITLE
Allow users to setup their timeout in Chronograf 

### ISSUE THREAD

**Issue by ono760** [influxdata/chronograf#2551]
It should be allowed for users to increase the Chronograf login duration on a HOSTED InfluxCloud account. As a user, I get automatically signed out after an hour, which prevents me from just leaving a dashboard open all day on my spare monitor as I'd like to.

**Comment by nhaugo** [comment]
@jaredscheib Is this something we could access via the UI like the "all users are superadmin"

**Comment by jaredscheib** [comment]
Yep, it could be refactored to work that way, just like `all users are superadmin`. Most of the work is already done. Should be straightforward on the server and client.
