### ISSUE TITLE
currentOrganization / organizations state is out of sync

### ISSUE THREAD

**Issue by 121watts** [influxdata/chronograf#2570]
Updating the organizations in the chronograf reducer does not update the `me: currentOrganization` in the admin reducer.  This causes components using the `currentOrganization` to have stale state until the next call to `/me`

**Comment by jaredscheib** [comment]
Per offline discussion, I don't think this introduces any bugs currently, so this is more something to be aware of. Maybe could be re-labeled as a chore.
