### ISSUE TITLE
Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2585]
Using the latest pull from master, i see this error in the console when I try to change the retention policy time in the ui.

<img width="828" alt="screen shot 2017-12-14 at 1 42 47 pm" src="https://user-images.githubusercontent.com/4805997/34016096-77f982b2-e0d5-11e7-8bc5-2aa6df1838f7.png">

![kapture 2017-12-14 at 13 49 22](https://user-images.githubusercontent.com/4805997/34016134-a615d10a-e0d5-11e7-82ef-eb131f84f7c8.gif)

**Comment by lukevmorris** [comment]
`formatting.js`: `formatRPDuration` assumes that duration comes back like `288h0m0s`. So we submit `12d` (and update redux optimistically) and formatDuration fails. And then we receive the confirmation from the server with `288h0m0s`, and correct behavior resumes.
