### ISSUE TITLE
Side navbar doesn't work sometimes

### ISSUE THREAD

**Issue by ono760** [influxdata/chronograf#2589]
When clicking on the side navbar in Chronograf, `sidebar--item`, sometimes nothing happens and I see the error on screenshot.  Using Chrome/Firefox I see the same behavior sometimes. Kind of difficult to reproduce. A page refresh must be performed in order for side navbar to work. 

<img width="1679" alt="screen shot 2017-12-14 at 4 37 51 pm" src="https://user-images.githubusercontent.com/14097441/34021484-057cd7d8-e0ef-11e7-8eb4-cdb70f75e840.png">

**Comment by nhaugo** [comment]
Probably a dupe of #2606

**Comment by ono760** [comment]
Yup, looks like a dup. Will close this one.
