### ISSUE TITLE
Add ability to drill down to another dashboard, page or visualization in cells

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#2594]
For dashboard creators, it would be nice to be able to define a cell of any kind and also define a behavior for pulling up more detail. This could be something like when the user clicks on the cell. But it could lead the user to another dashboard, or a modal of a more complete visualization (in the case of a gauge or single stat), or a link out to some other site.

This would make dashboards more than a single view experience. Dashboard creators could create experiences where if a user clicks on a specific cell, they'll be taken to an all new dashboard that gives much more information and detail about that specific cell.

**Comment by goller** [comment]
For the backend, we'd update the links associated with the cell to be a more sophisticated structure.

Currently, it is:
```json
{
    "links": {
        "self": "/chronograf/v1/dashboards/1/cells/1"
    }
}
```

Probably a change to something like this:
```json
{
    "links": [
        {
            "type": "self",
            "href": "/chronograf/v1/dashboards/1/cells/1"
        },
        {
            "type": "drilldown",
            "href": "someuri",
            "name": "User facing name",
        },
    ]
}
```

**Comment by nhaugo** [comment]
@pauldix can you provide some examples of this

**Comment by afausti** [comment]
@russorat I've stored an URL in a field like this:

<img width="377" alt="Screen Shot 2019-03-12 at 3 11 30 PM" src="https://user-images.githubusercontent.com/13968086/54239761-5b306100-44d9-11e9-92f5-f2a6ea171151.png">

is it difficult to turn that into an actual link?

I've also tried to store a string with the corresponding HTML and Markdown codes but that didn't work either. 

If you agree that this is something useful to have, I am happy to contribute a PR but would need some guidance like where in the code this should go, suggestions on the mechanism to turn that into a link, etc.

**Comment by afausti** [comment]
@russorat I've managed to [enable Markdown content in table cells](https://github.com/lsst-sqre/chronograf/commit/d1ac4304b0294f2e5cf24755e2ad6febb11f956e). It is working fine for my use case but to make it more generally useful we should have an option in "Table control" to enable/disable that.
What do you think? I am happy to try and contribute a PR.

**Comment by russorat** [comment]
@afausti thanks! We'd be happy to take a look at your PR.
