### ISSUE TITLE
Admin without SuperAdmin status cannot create new users if `All New Users Are SuperAdmin` is enabled

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2601]
This is a known issue and will be addressed after 1.4.0.

It's not clear what should be the behavior.

All New Users Are SuperAdmin was added so that the upgrade from pre-1.4.0 to 1.4.0 would be seamless – all users have all powers. This actually gives them additional powers, including now having the ability to lock everyone else out of the application, for example, since they have all of the powers of a SuperAdmin, which in a organization-less and individual user-less world, didn't exist. It's not clear what we should do.

Here are some options:
1. don't show individual user SuperAdmin toggles if SuperAdminNewUsers is enabled (partial solution; doesn't solve toggle case & users being created between the toggle time)

2. add conditional logic to allow Admins to create users even if toggle is on, and those users won't be SuperAdmin, but then arbitrary users who authenticate in will have more capabilities that someone who was added explicitly (full solution, but weird because arbitrary person who authenticates will have higher status than the Admin - i could pick a new email address and auth in and have a higher status than someone who's already using the app and is an Admin of an Organization)

3. whenever switch gets toggled, upgrade every user to superadmin (full solution; seems like a bad idea from a security standpoint)

4. lock the global config toggle off if it has been toggled off and there is more than one user (full solution; but this probably needs a way to be reversed)

1 & 4 prob need to be implemented together

5. change the setting to be "All users are SuperAdmins", which creates a bypass on the backend but doesn't mutate any users so that if it's switched back off, they're all back to what they were, and we add a global config option; maybe we add a more sophisticated confirmation scheme post-1.4.0 that requires multiple superadmins to confirm, but for 1.4.0 a simple confirmation dialogue is sufficient

6. if the setting is on, there is either 1) no creating users and no UsersPage, or 2) users but no roles, and everyone has un-demotable SuperAdmin status. this would need to be thought through further, but it seems promising. maybe it also couldn't be toggled back on, if it was ever toggled off.

**Comment by nhaugo** [comment]
Lets remove "All new users are super users" toggle from the app and make the only behavior be as if this was set to off.
Then add two command line options for chronograf:
1) `--list-users` this will show a list of all users with their id
2) `--promote-user <user id>` this will promote the provided id to a super admin
Both of these will require that chronograf not be running since bolt will be locked, which is good. These cli options should only be needed if someone gets themselves into a bad state.
