### ISSUE TITLE
Navigation does not work on first load.

### ISSUE THREAD

**Issue by noahcrowley** [influxdata/chronograf#2606]
When using a browser which has never accessed Chronograf, only the first click on the navigation brings you to a new page. Subsequent clicks have no effect.

**Comment by jaredscheib** [comment]
Sounds like a localStorage bug. Anything in the console? I'm gonna guess an error related to `rawText` being undefined.

**Comment by noahcrowley** [comment]
After the first click the console shows `TypeError: q is undefined`, subsequent clicks give a  `TypeError: oldNode.parentNode is null`.

**Comment by nhaugo** [comment]
@noahcrowley can you add your gif

**Comment by jaredscheib** [comment]
And what file is the TypeError being issued from? A screenshot of the whole console would be helpful.

**Comment by noahcrowley** [comment]
![chronograf-first-nav-issue](https://user-images.githubusercontent.com/626257/34129599-af82963e-e412-11e7-9401-30b49eeba43b.gif)

<img width="978" alt="screen shot 2017-12-18 at 4 36 10 pm" src="https://user-images.githubusercontent.com/626257/34129607-b5642d88-e412-11e7-8daf-d93dcdf10b5b.png">

Can be reproduced in a private browsing session.
