### ISSUE TITLE
Cell editor UI does not display correctly in Firefox Quantum

### ISSUE THREAD

**Issue by noahcrowley** [influxdata/chronograf#2607]
<img width="1392" alt="chronograf-cell-edit-firefox" src="https://user-images.githubusercontent.com/626257/34127811-72867dfa-e40c-11e7-9aae-82797e590620.png">

Tested on macOS and Windows.

**Comment by nhaugo** [comment]
@noahcrowley we made a bunch of changes to this in 1.4.0.0, can you test on latest?

**Comment by noahcrowley** [comment]
Still having issues
![jan-03-2018 20-54-59](https://user-images.githubusercontent.com/626257/34547365-a4ea942a-f0c8-11e7-934b-2cb9d408eda1.gif)
