### ISSUE TITLE
No error in first-time configuration modal when incorrect URL is used

### ISSUE THREAD

**Issue by noahcrowley** [influxdata/chronograf#2609]
When setting up Chronograf, no error is shown if the user inputs an incorrect URL and the InfluxDB instance cannot be reached.

![chronograf-config-no-error](https://user-images.githubusercontent.com/626257/34129794-6de9bba2-e413-11e7-97b2-bb394ff598b0.gif)

<img width="978" alt="chronograf-config-no-error-console" src="https://user-images.githubusercontent.com/626257/34129802-72e28f08-e413-11e7-9d16-aa189ea8cb6f.png">

**Comment by jaredscheib** [comment]
It does show a notification that source couldn't be connected to there – are you wanting it to prevent even adding the source in the first place?

**Comment by noahcrowley** [comment]
Sorry, to clarify, this is only an issue when you are adding your first source. 

In the gif, I have just created a new TICK stack and am visiting Chronograf for the first time. When I enter the wrong URL and click "Add source", nothing happens. There is no way to proceed from "Connection Details" until a correct URL is used. After that, the user is taken to the status page and sees the connection error.
