### ISSUE TITLE
Template variables not populating in Template Variable Manager despite successful proxy request

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2631]
<img width="1440" alt="screen shot 2017-12-20 at 2 18 54 pm" src="https://user-images.githubusercontent.com/6403018/34231415-d330e016-e590-11e7-87f2-2edfc6c51dd1.png">
<img width="837" alt="screen shot 2017-12-20 at 2 19 05 pm" src="https://user-images.githubusercontent.com/6403018/34231416-d34bef5a-e590-11e7-96cf-bb22185e9e52.png">

**Comment by russorat** [comment]
i don't think this is relevant anymore since the redesign
