### ISSUE TITLE
As user I should see the dashboards lazy load in the data

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2637]
Chronograf should only run the queries for the cells which are currently visible to the user.

**Comment by ischolten** [comment]
@russorat We are currently executing queries on onScroll. We can instead do it at the end of the scroll. What are your thoughts?

**Comment by nhaugo** [comment]
I think "on onScroll" is better, that way people can see the data as they scroll by

**Comment by russorat** [comment]
i agree, onScroll seems better

**Comment by russorat** [comment]
Lookin' great! 🌻
