### ISSUE TITLE
It's possible to remove the super admin status of every super admin

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2638]
This can create a state where there are no super admins in the application.

The fix is to prevent users from removing their own super admin status

![remove_every_users_super_admin_status](https://user-images.githubusercontent.com/1477539/34232325-a4b387a8-e594-11e7-9d2f-0dacd1e49251.gif)

**Comment by jaredscheib** [comment]
Does this need to be handled in the UI in the same PR?

**Comment by desa** [comment]
That would be ideal. Disabling the toggle if it's for yourself. I'm working on a PR right now.
