### ISSUE TITLE
500 internal server error after updating to latest code after using an older MT DB

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#2644]
Browser spins perpetually, server gives 500 ISE every time.

My old database, which gives the errors, should help to reproduce the bug: 
[chronograf-v1.db.zip](https://github.com/influxdata/chronograf/files/1577609/chronograf-v1.db.zip)

**Comment by jaredscheib** [comment]
As I recall, the `organizations` response from the server is an empty array in this case.

**Comment by desa** [comment]
@jaredscheib shouldn't be an issue for users that are coming from a pre multitenancy branch since they don't have a concept of organizations.

**Comment by jaredscheib** [comment]
True. We should verify that the migration from 1.3.10.0 to 1.4.0 is fine. And do we need to account for beta users, @nhaugo?

**Comment by jaredscheib** [comment]
Spoke with @nhaugo -- we aren't concerned with `beta` migrations. Closing this issue since `1.3.10.0` --> `1.4.0` should be fine, and we'll discover if it's not in our QA testing in the next couple of days.
