### ISSUE TITLE
TICKscript logs are pushed aside by long queries in the TICKscript editor

### ISSUE THREAD

**Issue by cryptoquick** [influxdata/chronograf#2645]
The logs do not show on a 1080p monitor.

![screenshot 2017-12-20 20 14 03](https://user-images.githubusercontent.com/285690/34239087-5953de74-e5c2-11e7-812b-95822a76755d.png)

**Comment by alexpaxton** [comment]
Whoa that looks mad broken

**Comment by cryptoquick** [comment]
@alexpaxton I figured it out
it's because I had a long query
so... to test, you just have something long in the field, haha
