### ISSUE TITLE
Create a Homebrew recipe

### ISSUE THREAD

**Issue by toddboom** [influxdata/chronograf#266]
Not a blocker for the `1.1-alpha` release, and might also be a slow process since we'll need to get approval from the Homebrew maintainers. We had previously been using `brew cask` to install the old Chronograf binary, but installing from the OSS repo is preferable and more widely used.

Based on previous experience, @gunnaraasen might be the best person to handle this.

**Comment by mytototo** [comment]
Hi @toddboom @gunnaraasen. Any news about this? Can we install the v1.1.0 from Homebrew?

**Comment by hasselrot** [comment]
Any news on this?

**Comment by goller** [comment]
Hey there @mytototo and @hasselrot, 
@gunnaraasen reached out to brew but they want us to get our release out first before we can do betas.

We plan another another few two week release cycles before we move ourselves out of beta, so this is several weeks off.

**Comment by hasselrot** [comment]
@goller Thanks for the update!

**Comment by nhaugo** [comment]
https://github.com/Homebrew/homebrew-core/pull/13494
