### ISSUE TITLE
Filestore ID collisions are possible

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2660]
As resources can be added via the file store and user's can specify IDs, it is possible to end up in a situation where two resources share the same ID.

If two elements share IDs, the resource stored in bolt will take precedence to the one on the filesystem.

At the very least this behavior should be documented.

**Comment by jaredscheib** [comment]
And to add to the story, Bolt generates IDs without regard to the IDs of those in the filestore, so if a user creates an `organization` via file with `id` of `2`, and Bolt has incremented only to `1`, then it would create a next organization with id `2`, right?

**Comment by desa** [comment]
yup
