### ISSUE TITLE
Confirm experience is unclear for Remove-ing a Chronograf user

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2668]
On behalf of @stevebang. He would click `Remove` and then thought that the X meant `delete`, and was unclear what the green checkmark meant.

Also, when hovering over the green checkmark button, the alt text says `Save`.

Note from me:
An explicit `Confirm` text button to the side, which @alexpaxton had created at some point, would be clearer.

**Comment by alexpaxton** [comment]
https://github.com/influxdata/chronograf/issues/3011
