### ISSUE TITLE
Disabled SuperAdmin toggle is unclear and misleading

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2669]
On behalf of @stevebang.

He thought that it was hard to tell what the setting was, with the disabled SuperAdmin toggle. He suggested that it should be a "disabled green" when on, to indicate that it's toggled on but disabled.

Additionally, he didn't realize that he could click the toggle for other SuperAdmins since his own, at the top of the list, was disabled. This inference was due to: 1) the disabled look being hard to distinguish from the `off` state for other users below; 2) the fact that for the first user (himself), it was disabled and thus he didn't think to try clicking the others, when combined the fact that it's hard to distinguish, visually.

**Comment by alexpaxton** [comment]
I believe this was taken care of during some PR relating to the providers tab
