### ISSUE TITLE
long lines in the tickscript editor push log view off the screen

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2671]
As a user, when i paste in a tick script or write one myself, long lines shouldn't push the log viewer off the screen. We should have a max width for the editor vs the log viewer and allow the user to resize if needed.

![kapture 2018-01-04 at 10 26 42](https://user-images.githubusercontent.com/4805997/34578462-e502dea2-f139-11e7-90c6-062f9f510d6c.gif)

**Comment by jaredscheib** [comment]
Is this a dupe of https://github.com/influxdata/chronograf/issues/2645?

**Comment by russorat** [comment]
yup
