### ISSUE TITLE
tickscript logviewer text overlaps

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2673]
![screen shot 2018-01-04 at 4 46 39 pm](https://user-images.githubusercontent.com/4805997/34590964-fb8e60e4-f16e-11e7-9176-849861677396.png)

```
// Dataframe
var data = stream
    |from()
        .database('telegraf')
        .retentionPolicy('autogen')
        .measurement('cpu')
        .where(lambda: "cpu" == 'cpu-total')
    |log()
```

**Comment by 121watts** [comment]
This is a problem with `InfiniteScroll` requiring a fixed row height.  The height of the `KapacitorLogRows` are hard coded to 87px.  We need to update `InfiniteScroll` to be able to handle arbitrary row heights.

**Comment by alexpaxton** [comment]
@121watts I like this idea of expandable items in the logs. There's something similar in chrome dev tools when viewing the console, so I'm assuming the concept will be familiar to users

**Comment by cryptoquick** [comment]
One way to deal with this is to truncate logs in the list view, but the interface should allow for a side view to inspect an error for further information. If specific fields are desired to show on the logs, they should be able to be starred, so they show first.

**Comment by ebb-tide** [comment]
start with an expandable and scrollable within the log entry list.  consider adding a log pause button in another issue.

**Comment by alexpaxton** [comment]
![screen shot 2018-02-02 at 6 06 41 pm](https://user-images.githubusercontent.com/2433762/35762003-7cb8ea04-0844-11e8-8545-e645c427cec7.png)

I built some basic expand/collapse functionality:
- Logs can be `expanded: true || false`
- The expanded state persists when more logs are loaded
- When expanded, can accommodate about 10 items before scrolling kicks in
- Expanded height is `250px`

To-do:
- [ ] Figure out how to have the `InfiniteScroll` component factor in the height of expanded log items

**Comment by alexpaxton** [comment]
- [ ] Sort fields and tags alphabetically so they are always in the same order
- [ ] Play/Pause button

**Comment by alexpaxton** [comment]
![screen shot 2018-02-05 at 2 12 30 pm](https://user-images.githubusercontent.com/2433762/35832386-f60ecc72-0a81-11e8-92d1-f9f68c4b76e6.png)

- No more infinite scroll
- Limited to 200 most recent messages
- Messages have variable height, key/value lists scroll after `300px`

**Comment by russorat** [comment]
😋 looks good!
