### ISSUE TITLE
saving TICKscript shouldn't take you back to the /alert-rules

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2674]
Incrementally building a tickscript is annoying since you need to save the script in order to view it, but doing so seems to jump back to the list of tickscripts. the save button should keep the user in the edit script page and we should have a separate way to go back to the list of scripts.

![kapture 2018-01-04 at 16 51 08](https://user-images.githubusercontent.com/4805997/34591047-7d7069cc-f16f-11e7-98ff-face99bf1bcb.gif)

 - [ ] The user should be able to click a "Save" button which would stay on the current page but load / update the script in Kapacitor and the log viewer would show logs from the updated script.
 - [ ] The user should be able to click a "Return" button which would return the user to the list of scripts page. If the user has unsaved changes in their script, they should be prompted warning them that they will lose their changes if they return.

**Comment by russorat** [comment]
@ebb-tide updated original comment with requirements

**Comment by nhaugo** [comment]
Ensure the close button takes you back to the kapacitor rules list

**Comment by alexpaxton** [comment]
Ended up splitting the `Save` button into two buttons: `Save` and `Exit`. Additionally we made the `Save` button disabled unless changes have been made, that way you see it light up when you've started typing. If there are unsaved changes the `Exit` button requires a second click. It has a little text letting the user know the changes will be discarded.

**Comment by russorat** [comment]
love it! 🔥 🔥 🔥 🔥 🔥 🔥
