### ISSUE TITLE
Dashboard data explorer is slow with lots of time series

### ISSUE THREAD

**Issue by mikeb01** [influxdata/chronograf#2675]
We have ~1 million time series spread across 7 databases.  When using the data explorer the UI becomes sluggish.  Especially when selecting a database or using the key filter.

**Comment by goller** [comment]
Hi @mikeb01 , thanks for writing in!

Do you mind opening the browser tools and showing us the load times for queries running?  I'm wondering if it is the size of the query, time to run the query, or large amount of data on the page.
