### ISSUE TITLE
Contributing.md: Dependency management?

### ISSUE THREAD

**Issue by Zanadar** [influxdata/chronograf#2676]
The `CONTRIBUTING.MD` for chronograf says that `gdm` is used for dependency mgmt, but it looks like that’s wrong… there are a `Gopkg.lock` and a `Gopkg.toml` in there. So I’m assuming the project uses `dep`?  If so, I can make a PR to fix that in the doc.

**Comment by goller** [comment]
Hi @Zanadar , thanks for writing in! Yes, you are totally correct.  A PR would be greatly appreciated :)

**Comment by Zanadar** [comment]
@goller Quick followup: 
When I run `dep ensure` in the root of the repo, it vendors a bunch of files that seem to not have been previously committed.  I'm assuming this is correct (although would necessitate an additional PR) but I though I would clarify this issue before adding language to `Contributing.md` that might lead folks use, eg `dep ensure -add whatever/dependncy.`

**Comment by goller** [comment]
@Zanadar that's a really good point.  It's been a while since we have done a dep ensure, so, it's likely we have new updates.

**Comment by duffyjp** [comment]
Is that why I'm getting this error trying to run `make`?

```
🐌  chronograf 15:17$ make
go build -o chronograf -ldflags "-s -X main.version=1.3.8.0-771-gd899b8b -X main.commit=d899b8b0" ./cmd/chronograf/main.go
cmd/chronograf/main.go:8:2: cannot find package "github.com/influxdata/chronograf/server" in any of:
	/Users/duffyjp/.gvm/gos/go1.7.5/src/github.com/influxdata/chronograf/server (from $GOROOT)
	/Users/duffyjp/.gvm/pkgsets/go1.7.5/global/src/github.com/influxdata/chronograf/server (from $GOPATH)
cmd/chronograf/main.go:9:2: cannot find package "github.com/jessevdk/go-flags" in any of:
	/Users/duffyjp/.gvm/gos/go1.7.5/src/github.com/jessevdk/go-flags (from $GOROOT)
	/Users/duffyjp/.gvm/pkgsets/go1.7.5/global/src/github.com/jessevdk/go-flags (from $GOPATH)
make: *** [chronograf] Error 1

**Comment by jaredscheib** [comment]
Thanks for reporting that @Zanadar -- I just updated it.
