### ISSUE TITLE
Using generic oauth config with github as the provider causes issues in the callback

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2677]
- [x] Generic OAuth options should be able to be configured to work with Okta
 - [x] Generic OAuth options should be able to be configured to work with Github
 - [x] Generic OAuth options should be able to be configured to work with Google
 - [ ] ~~Generic OAuth options should be able to be configured to work with Heroku~~

ERRO[0012] Unable to get principal identifier Get : unsupported protocol scheme ""  component=auth method=GET remote_addr=[::1]:56776 url=/oauth/github/callback?code=

export LOG_LEVEL=debug
export TOKEN_SECRET=<redacted> 
export GENERIC_CLIENT_ID=<redacted>
export GENERIC_CLIENT_SECRET=<redacted>
export GENERIC_AUTH_URL=https://github.com/login/oauth/authorize
export GENERIC_TOKEN_URL=https://github.com/login/oauth/access_token
export AUTH_DURATION=12h
export GENERIC_NAME=github
export PUBLIC_URL=http://localhost:8888

**Comment by jaredscheib** [comment]
See https://github.com/influxdata/docs.influxdata.com/issues/1384 for the solution. Generic OAuth works for GitHub but has not been adequately documented.

In short, in addition to the above settings, the user would need to add the following two environment variable settings in order to get it to work:
```
GENERIC_API_URL=https://api.github.com/user
GENERIC_SCOPES="user:email read:org"
```

@desa and I were able to authenticate and use Chronograf via Generic OAuth with GitHub as my provider once I added those env vars.

**Comment by jaredscheib** [comment]
@russorat @nhaugo Do we also care about `Auth0`?

**Comment by jaredscheib** [comment]
The Provider name for an Org Mapping or User would be the value of `GENERIC_NAME`, which by default is `generic` or can be overridden by the user's configuration.

**Comment by jaredscheib** [comment]
one idea of how to get Generic to work with Heroku, and other similar cases that may arise, is to allow for a `GENERIC_CUSTOM_HEADERS` env var, or something to that effect. if we do this, i think we'd also want to more clearly pass through the error by adding error handling for the generic AJAX requests, as filed in https://github.com/influxdata/chronograf/issues/2912. thoughts on this, @nhaugo @goller @russorat?

**Comment by russorat** [comment]
related https://github.com/influxdata/chronograf/issues/2964

**Comment by russorat** [comment]
we can remove heroku from this issue.

**Comment by russorat** [comment]
Verified this is working with Okta. Basic instructions are as follows:

```
1. Follow the instructions here: https://developer.okta.com/authentication-guide/implementing-authentication/auth-code
to create a new web app for okta

2. the callback url should be something like http://localhost:8888/oauth/okta/callback
3. Under allowed grant types in the Okta app, the only thing that should be checked is Authorization Code

4. To get Okta working on the latest version of chronograf, you will need to set the following ENV variables.

export GENERIC_NAME="okta"
export GENERIC_CLIENT_ID="<Located at the bottom of the Okta App Page>"
export GENERIC_CLIENT_SECRET="<Located at the bottom of the Okta App Page>"

// The root server url can be found in the Okta Authorization Servers Page
// You may need to create one if you don't already have one
export GENERIC_AUTH_URL="https://dev-553212.oktapreview.com/oauth2/default/v1/authorize"
export GENERIC_TOKEN_URL="https://dev-553212.oktapreview.com/oauth2/default/v1/token"
export GENERIC_API_URL="https://dev-553212.oktapreview.com/oauth2/default/v1/userinfo"

export PUBLIC_URL="http://localhost:8888"
export TOKEN_SECRET="secretsecretsecret"
// The following scopes need to be provided
export GENERIC_SCOPES="openid,profile,email"

5. Finally, start chronograf normally
```

**Comment by jaredscheib** [comment]
Could you substitute in dev-###### for those values?
