### ISSUE TITLE
5 second timeout apparently still sometimes insufficient in server integrations test

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2679]
On https://github.com/influxdata/chronograf/pull/2409#pullrequestreview-87024884 it's noted that CircleCI is failing on `TestPipelineJSONDeadman` intermittently. This is due to the 5 second timeout in the server_test.go integrations test. This was already an issue before, when it was set to 100ms, and apparently it remains an intermittent issue.

This begs the question: can we ensure that an arbitrary timeout is not a source of any problems?

Related to #2625.

**Comment by desa** [comment]
@jaredscheib I think it might be a slightly different issue. `TestPipelineJSONDeadman` isn't in the `integrations` package.

**Comment by jaredscheib** [comment]
Hm,  thought when I looked at the Circle server logs, it seemed related. Maybe not though. If you've solved it and it's unrelated, feel free to close this issue.

**Comment by desa** [comment]
I'm inclined to leave it open until we're certain that it's not causing issues.
