### ISSUE TITLE
When an organization is deleted, should deleting all of its resources & user roles should be an atomic transaction?

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2683]
Low priority, but it's possible that upon deleting an organization, one of its dependent destroys could fail (deleting a resource owned by that organization, or removing a user's role from within that organization), and orphaned data is left in the database that belongs to that organization.
  
cc @desa.

**Comment by desa** [comment]
The fix for this would be to put all of the operations in a single bolt db transaction. This would require a little bit of refactoring of the bolt implementations of each resource.
