### ISSUE TITLE
Launch Basic Docs

### ISSUE THREAD

**Issue by toddboom** [influxdata/chronograf#269]
Prior to the `1.1-alpha` release, we should have some basic docs in place on `docs.influxdata.com`. These don't need to be as in-depth as other products, but should give people a quick overview and help with the getting started experience. We'll flesh these out as we get closer to a final release and solidify layouts for screenshots and such.

Currently, @rkuchan is taking point on this, so consider this issue just a placeholder to make sure they're ready to go on the launch date.

**Comment by nhaugo** [comment]
This was completed prior to launch
