### ISSUE TITLE
Chronograf is overwhelms server when influx is down; should have some backoff

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#2692]
My influx was down for a moment and the browser sends requests to the server as fast as it can.  

I think chronograf should pause between failures or do some sort of health check.

![overload](https://user-images.githubusercontent.com/1922921/34783166-6b8879d6-f5f0-11e7-9c3e-7daa1476aaaf.gif)

**Comment by russorat** [comment]
i think we fixed this.
