### ISSUE TITLE
Removing filestore Organization causes users to not be able to login

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2694]
## Repro steps
1. Add a filestore organization
2. Have user join filestore organization
3. Remove organization file from filestore and restart server
4. Try to auth back into application
5. Sadness

When a user hits `/me` we retrieve all organizations that they have roles in. Since the user was not removed from the filestore organization, they still have a role in that organization. The lookup for this org will cause the server to respond with a 500.

**Comment by jaredscheib** [comment]
I think an in-memory representation of all files, as captured at process runtime, would allay this and other problems, such as that (it's my understanding that) we also access the filestore every time a request to /me is made. This seems cumbersome and potentially error-prone, as in this case.
