### ISSUE TITLE
Gauges malfunctioning on Mac OS X/Safari and Chrome

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#2695]
Mac OS Version: 10.13.1 (17B1003)
Safari Version 11.0.1 (13604.3.5)

Resizing a cell with a gauge in it results in the gauge outside the cell, and the gauge type does not display properly in the query builder. 
![safariscreensnapz039](https://user-images.githubusercontent.com/2071898/34796232-d20393ee-f622-11e7-91d3-2553820e3c97.png)
![safariscreensnapz038](https://user-images.githubusercontent.com/2071898/34796233-d20e83da-f622-11e7-9a46-76fbd3a94eec.png)

Seems to work just fine on Chrome though

**Comment by russorat** [comment]
Noticed some strangeness with zooming and the guage in chrome as well. this happened after adding the guage, then adding some additional cells to the dashboard and resizing them.
this is release 1.4.0.1, not build from source.

![screen shot 2018-01-11 at 11 48 54 am](https://user-images.githubusercontent.com/4805997/34844205-9484d4b2-f6c5-11e7-9637-7627ac737df3.png)

**Comment by russorat** [comment]
LGTM
