### ISSUE TITLE
Chronograf only showing black screen in Internet Explorer 11

### ISSUE THREAD

**Issue by philippa1812** [influxdata/chronograf#2697]
Hi, I have installed Chronograf on my Ubuntu Server which hosts InfluxDB and it is up and running. However when I try to connect to Chronograf via web browser the screen is just black. I dont know whats the problem, any ideas how to solve this?

**Comment by jaredscheib** [comment]
Hi @philippa1812, thanks for writing in. Could you tell us what operating system and web browser (including version) you're using? Additionally, could you open the developer console in your browser when you're trying to access Chronograf, and tell us if you see any errors in the console, as well as any failed requests in the Network communication? Finally, would you mind sharing your server logs report?

**Comment by philippa1812** [comment]
@jaredscheib 

- Operating System: Windows 7
- Web Browser: Internet Explorer 11.0.9600.18738

The network communication seems fine but I get the following error in the developer console: 
"SCRIPT438: The object does not support the "find" property or method
File: ui.js, Line: 25, Column: 1"

**Comment by philippa1812** [comment]
I just tried with Google Chrome and it works!

**Comment by jaredscheib** [comment]
Thanks for the further info, @philippa1812. Good to know that this is a bug within IE. Glad you got it working in Chrome!

**Comment by simonmurdock** [comment]
I ran into this issue today. Worked around it by opening IE developer tools and forcing the edge rendering engine.

**Comment by jfcg** [comment]
Same problem here with v1.6.2, on Edge
![chronograf-hata](https://user-images.githubusercontent.com/1410597/47228862-f744b900-d3ce-11e8-9646-94c2db492b4d.jpg)

**Comment by russorat** [comment]
this is resolved by upgrading your browser. closing for now.

**Comment by suvvenndu** [comment]
> I ran into this issue today. Worked around it by opening IE developer tools and forcing the edge rendering engine.

@simonmurdock , Can you please share , how did you force edge rendering engine on IE?
