### ISSUE TITLE
Logarithmic Scale UI Bugs

### ISSUE THREAD

**Issue by phi1010** [influxdata/chronograf#2705]
The logarithmic scale still has some UI issues:

The secondary scale shows too many labels (both K/M/B and K/M/G modes):
![grafik](https://user-images.githubusercontent.com/772292/34921863-d909c1c8-f987-11e7-9b3f-0ca75668c357.png)

The scale doesn't use the logarithmic base 1024 when switching to K/M/G, making the scale much more difficult to read:
![grafik](https://user-images.githubusercontent.com/772292/34921874-fe5cd56e-f987-11e7-83e0-607f79412100.png) ![grafik](https://user-images.githubusercontent.com/772292/34921876-0ac7d1b4-f988-11e7-84f7-f4e7f19943c5.png)

Version: pre-built Chronograf 1.4.0-0 on CentOS 7.2

**Comment by goller** [comment]
@phi1010 thanks for writing in!

@121watts what do you think?

**Comment by 121watts** [comment]
@phi1010 thanks for writing in!  KMG uses base two.  I'll have to take a look at the y2 axis label issue.
