### ISSUE TITLE
Unable to use Chronograf - session timing out

### ISSUE THREAD

**Issue by varadskarmarkar** [influxdata/chronograf#2737]
I'm following along the Getting Started guide at  https://docs.influxdata.com/chronograf/v1.4/introduction/getting-started/#chronograf-setup.

At first I got to "Welcome to Chronograf" screen and clicked "Add source" but I'm not able to advance any further. I have a brief view of the localhost:8888/sources page before it redirects me to /login with a message that "Your session has timed out. Log in again to continue". How do I fix this?

**Comment by nhaugo** [comment]
Hi @varadskarmarkar are you using oauth? If so can you share what settings you are using.

**Comment by varadskarmarkar** [comment]
No oauth. It's set up on my ubuntu instance for development purposes. I'm running it on localhost:8888 and I was actually briefly able to access it but now it's again down. It's just inconsistent. Which settings do you need to know in order to debug it?

**Comment by nhaugo** [comment]
Whatever your cli/env vars are and the log output. There should be no session to time out if you are not using oauth2.

**Comment by varadskarmarkar** [comment]
@nhaugo  Where should the logs be? The director /var/log/chronograf is empty. And I didn't set any variables, I only downloaded the .deb file, unpacked it, and then started chronograf. From there, I completed my initial set up through the web GUI at localhost:8888. 

So I'm not sure how to debug this. I also upgraded my chronograf distribution, although that didn't help.
