### ISSUE TITLE
Graphs do not have enough variety of colors

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2738]
![screen shot 2018-01-30 at 2 28 15 pm](https://user-images.githubusercontent.com/2433762/35594955-e9d21f48-05c9-11e8-9480-74b3797d516c.png)

User would have to hover over a line and locate it in the legend to know the series name. The lack of colors reduces the utility of coloration as a whole

**Comment by alexpaxton** [comment]
![screen shot 2018-02-28 at 2 18 02 pm](https://user-images.githubusercontent.com/2433762/37307993-dc5c327c-25f9-11e8-8d73-5f57ebda04d2.png)

First pass at some different colors. This design unintentionally produces a rainbow aesthetic in which it is difficult to differentiate between the various shades of each color. Need to tinker with this more

**Comment by alexpaxton** [comment]
![screen shot 2018-03-19 at 7 08 26 pm](https://user-images.githubusercontent.com/2433762/37670850-92ac662c-2c27-11e8-9d47-c79e4852cdec.png)
![screen shot 2018-03-19 at 7 12 11 pm](https://user-images.githubusercontent.com/2433762/37670857-96199d48-2c27-11e8-9704-2c4a391ff95d.png)

Here's a couple screenshots of some experimentation. I have a function that generates palettes based on number of lines. It uses HSL color so I can incrementally shift Hue. I'm following some data viz principles which essentially state that maximum diversity between colors comes from a low saturation / low value color moving towards a high saturation / high value color.

I found this old color generator I made a ways back so I've been repurposing the code from there
http://influxdata.github.io/design.influxdata.com/graph-colors/index.html

**Comment by alexpaxton** [comment]
Goals:

- Palette has differentiation between each color
- Palette supports as many colors as possible before having to repeat
- Palette adds more color "points" as necessary

**Comment by russorat** [comment]
@alexpaxton i don't think this is working on single stat
![kapture 2018-04-05 at 16 30 08](https://user-images.githubusercontent.com/4805997/38396775-acc54b04-38ee-11e8-92b3-de31891361fe.gif)

**Comment by alexpaxton** [comment]
@russorat I have a fix in mind, I can tackle tomorrow

**Comment by russorat** [comment]
looks good! thanks!

**Comment by drolfe** [comment]
Hi, 

This is great, something I've been looking for, however after upgrading to chronograf 1.5.0-0,  I see only the "Nineteen Eighty Four" line color option ?

Is there something I need to config to enable the other color options?

I've looked at the docs and community forum and couldn't find anything on this feature

Thanks in advance

**Comment by alexpaxton** [comment]
Just submitted a PR to fix the issue: https://github.com/influxdata/chronograf/pull/3564
