### ISSUE TITLE
Save Alert Rule returns user to Status/Home page (regression?) and not to Alert rules list

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#2740]
Testing against:
2018/01/31 17:28:28 Chronograf 1.2.0~n201801310832 (git: f550e2f98db1d95ebc3c433f59507fd52b6231a2)

Browser is Chrome 63
OS is Ubuntu 16.04

After clicking the "Save Rule" button on the Create new alert form, the Status/Home page loads. 

I was expecting to be returned to the list of Alert Rules located through the Alerting/Create Icon.  

I'm currently reviving Chronium Selenium tests, and from the story/test code it appears that returning directly to the rules list was the way it behaved previously. 

![savealertrule01](https://user-images.githubusercontent.com/25881301/35635081-9c8370f4-06ad-11e8-9fb4-821e149417c3.png)
![savealertrule02](https://user-images.githubusercontent.com/25881301/35635090-a5a9ad2e-06ad-11e8-8c29-e27ca622c460.png)
![savealertrule03](https://user-images.githubusercontent.com/25881301/35635101-ab9b3d24-06ad-11e8-9f3d-656a7111f0e4.png)

**Comment by nhaugo** [comment]
Not really a dupe but will be fixed by https://github.com/influxdata/chronograf/issues/2674
