### ISSUE TITLE
Change Alerting > Create to Alerting > Manage

### ISSUE THREAD

**Issue by stevebang** [influxdata/chronograf#2749]
In the Alerting menu in Chronograf 1.4, there are two options: History and Create. When you click Create, the page titled "Build Alert Rules or Write TICKscripts" appears. 

Since users can create or edit TICKscripts and alert rules here, and not just create, the menu option should be: Alerting > Manage.

**Comment by alexpaxton** [comment]
Ah this is awesome. I agree "Create" is a little misleading

**Comment by russorat** [comment]
LGTM
