### ISSUE TITLE
Support Kapacitor batch queries to allow historical analysis

### ISSUE THREAD

**Issue by love2558** [influxdata/chronograf#2759]
I want to compare the current data with the data from 5 minutes ago.
so,I create the alert rules, the rules are as follows:
```
var db = '_internal'
	var rp = 'monitor'
	var measurement = 'database'
	var groupBy = []
	var whereFilter = lambda: TRUE
	var name = 'greateralert'
	var idVar = name + ':{{.Group}}'
	var message = ' {{.ID}} {{ index .Fields "value" }} {{.Time}}'
	var idTag = 'alertID'
	var levelTag = 'level'
	var messageField = 'message'
	var durationField = 'duration'
	var outputDB = 'chronograf'
	var outputRP = 'autogen'
	var outputMeasurement = 'alerts'
	var triggerType = 'relative'
	var shift = 5m
	var crit = 6

	var data = stream
		|from()
			.database(db)
			.retentionPolicy(rp)
			.measurement(measurement)
			.groupBy(groupBy)
			.where(whereFilter)
		|eval(lambda: "numMeasurements")
			.as('value')

	var past = data
		|shift(shift)

	var current = data

	var trigger = past
		|join(current)
			.as('past', 'current')
		|eval(lambda: float("current.value" - "past.value"))
			.keep()
			.as('value')
		|alert()
			.crit(lambda: "value" > crit)
			.stateChangesOnly()
			.message(message)
			.id(idVar)
			.idTag(idTag)
			.levelTag(levelTag)
			.messageField(messageField)
			.durationField(durationField)
			.post('http://xxxxxxxx')

	trigger
		|eval(lambda: float("value"))
			.as('value')
			.keep()
		|influxDBOut()
			.create()
			.database(outputDB)
			.retentionPolicy(outputRP)
			.measurement(outputMeasurement)
			.tag('alertName', name)
			.tag('triggerType', triggerType)

	trigger
		|httpOut('output')
```
But the result is not what I want,It can't be compared to the past, and it always starts when the rules are created.
For example，The current time is 10:15, and I create the alert rule，It can only compare 10:20 minutes with 10:15 minutes instead of 10:15 and 10:10.the result is not what I want！
do you understand what I mean？

**Comment by love2558** [comment]
when I create and enable alert task,the task should start to work，Not after 5 minutes or longer

**Comment by goller** [comment]
@love2558 thanks for writing in!  I think I understand what you are saying.  You would like an alert to compare to its historical data immediately rather than waiting to fill its window.  In your case it fills its window after 5 minutes.

@nathanielc @desa To get immediate historical results, would the alert need to be a batch rather than a stream?

**Comment by nathanielc** [comment]
@goller Yes, you need to use batch in order to be able to query the historical data when the task first starts.

**Comment by goller** [comment]
@love2558 Ok, I'm going to change the title of this issue to be "Support kapacitor batch queries"

**Comment by love2558** [comment]
OK,thank you for your answer! so,chronograf UI don't support kapacitor batch queries,I need to edit the TickScript in order to change the queries type, right?

**Comment by goller** [comment]
@love2558 for the moment, yes.  That'll be the workaround.

**Comment by love2558** [comment]
@goller  OK,thank you!

**Comment by nhaugo** [comment]
@love2558 does this not do what you are looking for?
![batch](https://user-images.githubusercontent.com/1003269/35886988-b941c7c4-0b47-11e8-9fb7-ad9b389e4cf6.gif)

**Comment by love2558** [comment]
@goller @nathanielc @nhaugo sorry,I don't know how to write the TickScript in batch queries type,I need to compare current data with historical data，It's too hard.could you give me a demo?

**Comment by love2558** [comment]
@goller @nathanielc @nhaugo I wrote a TickScript, but it seems to be a problem. Can you give me some advice?
```
var message = 'batch alerting {{.Time}} {{ index .Fields "value" }}'
var current = batch	
		|query('''
			select mean(nummeasurements) from "_internal"."monitor"."database" where time > now() - 1m
		''')
			.every(1m)
		|eval(lambda: "mean")
                       .as('value')
		
var past = batch	
		|query('''
			select mean(nummeasurements) from "_internal"."monitor"."database" where time > now() -24h - 1m and time < now() -24h 
		''')
			.every(1m)
		|eval(lambda: "mean")
                       .as('value')

var trigger = past
    |join(current)
        .as('past', 'current')
    |eval(lambda: float("current.mean" - "past.mean"))
        .keep()
        .as('value')
    |alert()
        .crit(lambda: "value" > 0)
        .stateChangesOnly()
        .message(message)
        .post('http://xxxxx')
```

**Comment by love2558** [comment]
I need to compare the current data with yesterday's data for the same time period,Thank you very much!

**Comment by desa** [comment]
@love2558 I've made a couple adjustments to the tickscript you have above

```
var message = 'batch alerting {{.Time}} {{ index .Fields "value" }}'

var current = batch
    |query('select mean(nummeasurements) as value from "_internal"."monitor"."database"')
        .period(1m)
        .every(1m)
        .align()

var past = batch
    |query('select mean(nummeasurements) as value from "_internal"."monitor"."database"')
        .period(1m)
        .every(1m)
        .align()
        .offset(24h)
    |shift(24h)

var trigger = past
    |join(current)
        .as('past', 'current')
    |eval(lambda: float("current.value" - "past.value"))
        .keep()
        .as('value')
    |alert()
        .crit(lambda: "value" > 0)
        .stateChangesOnly()
        .message(message)
        .post('http://xxxxx')
```

**Comment by love2558** [comment]
@desa Thank you very much!
