### ISSUE TITLE
cannot shut down Chronograf while viewing tickscript logs

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2769]
if you try to "control+c" chronograf while on the screen displaying the tickscript logs, the command line just hangs. Even after clicking "Exit", the following page fails to load, but chronograf still doesn't exit. I'm thinking the backend might be hanging on the http streaming connection or something and not accepting the interrupt.

![image](https://user-images.githubusercontent.com/4805997/35887907-c88e21a2-0b4a-11e8-93e1-85b1eaa9eacf.png)

**Comment by goller** [comment]
@russorat you are totally right.  We'd need to change ditch from our older usage of graceful and use the newer go shutdown process here:

https://github.com/influxdata/chronograf/blob/master/server/server.go#L392

**Comment by russorat** [comment]
seeing this even when we aren't in the log viewer as well

![image](https://user-images.githubusercontent.com/4805997/38003105-d851fe58-31ea-11e8-80f6-e9f0d60b0072.png)
