### ISSUE TITLE
if source becomes no longer available and no other source- error should not say "switching to other source"

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2783]
Error currently reports that it `successfully connected to another source` when it has not. And still looks like it is connected to source that is no longer available. 

![kapture 2018-02-07 at 16 01 06](https://user-images.githubusercontent.com/10937678/35948275-b928b5f2-0c20-11e8-93e8-b4dc62c2a6b3.gif)

**Comment by Nzyme1** [comment]
Getting the same error.  Influxdb working fine taking in data from telegraf and displaying it with grafana but not luck with Chronograf for some reason.

**Comment by iowelinux** [comment]
same here

**Comment by acastanet** [comment]
Same problem, Chronograf work fine (test with external influxDB server)

**Comment by acastanet** [comment]
Found solution for me 
- save your database
- upgrade all Influx  TICK stack 
- if error : 
http://installfights.blogspot.fr/2017/03/how-to-upgrade-influxdb-0100-to-122-in.html
and http://monblog.system-linux.net/blog/2014/03/03/corriger-e-sub-process-usrbindpkg-returned-an-error-code-1/comment-page-1/
- start influxd : read the notice and import

Bye

**Comment by jiangli226** [comment]
when installing on WSL (windows Ubuntu), I am still getting the same issue with connecting to influxDB.
I can verify the DB is working as expected
