### ISSUE TITLE
Support PagerDuty v2 as part of Kapacitor v1.5 update

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#2786]
Kapacitor v1.5 will support PagerDuty v2 interface.  There are some changes required in terms of the parameters to configure this.  Chronograf should support the PagerDuty v2 setup -- and prep for PagerDuty v1 deprecation by Kapacitor v1.6.

Please see: https://github.com/influxdata/kapacitor/issues/1795

- [x] leverage the services endpoint to determine what configs are available
- [x] only show the configs that are returned from the services endpoint  in alertTabs
- [x] add a pagerduty v2 config option to the Kapacitor config option of chronograf
- [x] add a deprecation warning to the UI for pagerduty v1 so users know they will need to update
- [x] update kapacitor dependency to v1.5

**Comment by nhaugo** [comment]
@timhallinflux is pagerduty finally removing support for v1? If not I don't know why we would replace v1 this instead of just adding v2.

**Comment by russorat** [comment]
@nhaugo 

https://v2.developer.pagerduty.com/v2/docs/v1-rest-api-decommissioning-faq
```
WHAT’S HAPPENING?
On April 24, 2018, at 22:00 PDT (UTC+7), our v1 REST API is entering a decommissioning period. Starting on that date, you will no longer be able to generate v1 REST API keys, but the v1 REST API will remain operational.

On October 19, 2018, at 22:00 PDT (UTC+7), the v1 REST API will be decommissioned and no longer operational.
```

**Comment by russorat** [comment]
1.5rc1 is out so lets test and verify with that: https://github.com/influxdata/kapacitor/releases/tag/v1.5.0-rc1

**Comment by russorat** [comment]
does this impact how we identify versions? https://github.com/influxdata/kapacitor/issues/1826#issuecomment-382847348

**Comment by russorat** [comment]
- [ ] the line should start with "PagerDuty v1 is being deprecated... "

![image](https://user-images.githubusercontent.com/4805997/39211135-924e53ee-47bf-11e8-865b-66b3a6585064.png)

**Comment by russorat** [comment]
this is working. thanks!!!

**Comment by russorat** [comment]
in rc2, the service-key config has been updated to be routing-key. we will need to update this.

**Comment by jaredscheib** [comment]
I've fixed the error display bug (https://github.com/influxdata/chronograf/issues/3385) in #3386.

**Comment by mkarlesky** [comment]
@timhallinflux @nhaugo @russorat

This issue is closed, and plans have long been laid. But for clarity and correctness, PagerDuty deprecated their v1 REST API. Both their v1 and v2 Events API continue to be supported with no plans to stop supporting v1. Unless I'm mistaken, alerts in Chronograf and Kapacitor rely on the PagerDuty Events APIs and not the REST API.

From [PagerDuty documentation on API differences](https://v2.developer.pagerduty.com/docs/getting-started):
> If you are using a custom monitoring tool, library, or script that has not yet been updated to v2, you can still use the Events API v1. There are no plans as of 2017 to deprecate the Events API v1 in the foreseeable future.

From the [PagerDuty REST API v1 Decommissioning FAQ](https://v2.developer.pagerduty.com/docs/v1-rest-api-decommissioning-faq):
>In July 2016, PagerDuty released REST API v2 and announced plans to decommission the REST API v1. This is separate from our Events API which will not be affected.

>This change only affects REST API v1. You can continue to use Events API v1 as you do today.
