### ISSUE TITLE
[data explorer] Be able to set custom group by time interval

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/chronograf#280]
The group by time interval in a query is a very large performance indicator for how the query performs. It doesn't appear there's a way to set a custom group by interval, but this would be good (both for the InfluxDB instance and the user's browser) for viewing larger periods of time.

**Comment by rickychilcott** [comment]
👍 In the older version of chronograf, it was possible to do this, and very large and very small values would be helpful such as 1s, 5s, or 90s, could be very valuable

**Comment by 121watts** [comment]
This should be solved now with templates and auto scaling group by time intervals
