### ISSUE TITLE
self-sign cert verification error on meta node

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#2801]
I am getting this error when trying to connect via https to InfluxDB Enterprise.

The Admin UI is just keep spinning....

On Chronograf v1.4.0.1

```
time="2018-02-12T22:41:37Z" level=error msg="Error message Get https://influxdb-meta1-primary.use1.test.io:8091/role: x509: certificate signed by unknown authority" component=server http_status =400
```

**Comment by goller** [comment]
Hi @danyli78 , I see the bug.  I'm working on a PR right now!

**Comment by goller** [comment]
@danyli78 my pr #2818 should fix this problem.
