### ISSUE TITLE
Refactor CellEditorOverlay

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2802]
The `CellEditorOverlay` component has become very large and unwieldy as we've added to it over time. There are a ton of handlers that cover everything from query editing to customizing all the cell types and the CEO state trickles down into all the various subcomponents. 

I have a proposed solution which is:
- Move most of CEO state into redux
  - `axes`, `colors`, `workingCellType`, `workingCellName`, etc
- Subcomponents get state from redux, and only the state they care about
  - For example, `AxesOptions` gets `axes` from redux instead of being passed down
  - `SingleStatOptions` gets `singleStatColors` from redux
- Move event handlers into their associated components
  - For example, CRUD operations for gauge thresholds would exist in `GaugeOptions` instead of being passed down
- Saving a cell aggregates the CEO state into the right format before sending to the server

**Comment by russorat** [comment]
@alexpaxton what's left to do here?

**Comment by alexpaxton** [comment]
@russorat nothing!
