### ISSUE TITLE
All Users page: button should be "delete" not remove

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2813]
The button on the far right of the screenshot should say Delete instead of Remove.

![image](https://user-images.githubusercontent.com/4805997/36181941-152ff792-10dc-11e8-85dd-3533251b4ae1.png)

**Comment by russorat** [comment]
![image](https://user-images.githubusercontent.com/4805997/37994079-4263ae52-31c5-11e8-88e2-69f41045ccb8.png)

**Comment by alexpaxton** [comment]
I was able to reproduce the issue, looks like the `removeUser` action is being called with an undefined payload.

I looked at `AllUsersTableRow.js` where the action is called from and I was able to fix by doing this:
```
  // const wrappedDelete = _.curry(onDelete, user)
  const wrappedDelete = () => {
    onDelete(user)
  }
```

I looked up what `_.curry` does and I'm not sure it is working as intended

**Comment by russorat** [comment]
great!
