### ISSUE TITLE
Data Explorer not correctly parsing timeout errors

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#2815]
At the bottom of the QueryEditor, we see `[object Object]`

**Comment by russorat** [comment]
![image 1](https://user-images.githubusercontent.com/4805997/36832103-0db58306-1cdf-11e8-96f7-459cd88a8768.png)

**Comment by 121watts** [comment]
@russorat do you have repro steps.  I tried shutting down influxdb and still getting the expected error

**Comment by russorat** [comment]
🥇
