### ISSUE TITLE
Host Groups in Chronograf

### ISSUE THREAD

**Issue by aund** [influxdata/chronograf#2822]
Hello,

Really enjoying playing with the TICK stack. We use Xymon on a large scale just now to monitor over 2000 endpoints. One of the nice things about it, is it allows for a nested html structure to group hosts by, so that not all 2000 endpoints are on the initial dashboard and you can navigate by an intuitive top level structure. E.g. Location/Service/Host

Are there any plans to introduce something similar for Chronograf to make navigation a bit easier. I know there's a text filter but would be nice to have something else to navigate by if you don't necessarily know the name of the host you are interested in.

Thanks

**Comment by russorat** [comment]
connect #682 

Hi @aund thanks for the request. We will investigate this as part of a larger redesign of the host list page.
