### ISSUE TITLE
Display group of dashboard using tabs

### ISSUE THREAD

**Issue by gianarb** [influxdata/chronograf#2823]
Hello!

Time to time you have more than one dashboard under the same group. Currently, my use case is a group of dashboards like:

* Kubernetes Ingress
* Docker Container
* Kubernetes Infra

These dashboards have two environments, I switch between these envs using template variables. So all good but I would like to group them and switch between these dashboards from inside a dashboard. How I imagine it is a set of labels between dashboard title and the actual graphs:

![2018-02-19-10-21-49_1905x95](https://user-images.githubusercontent.com/1630267/36370370-ee7d5dc4-155e-11e8-9cfc-094bf0a5a99b.png)

The image takes part at "The worst screen award" but it's the best one.

**Comment by russorat** [comment]
@gianarb to confirm, are you asking to maintain the value of the template variable between dashboards? So you don't have to select the environment each time you jump to a new dashboard?

**Comment by gianarb** [comment]
Share the value of the template variables is a side effect for sure. But the important part for me it's about having these tabs to fast move between grouped dashboards. But yes the template variables need to be the same

**Comment by vit1251** [comment]
Yep. This very important feature and I already want to ask to implement that. I have more than 100 different systems with different one metrics name and parameters and sometimes loading and handling each one on one dashboard is very abused for me. Will be greate like in Jenkins separate this for different tab name.

**Comment by vit1251** [comment]
Any updates?

**Comment by russorat** [comment]
this will be considered for 2.0. Follow https://github.com/influxdata/influxdb/issues/16538 for updates
