### ISSUE TITLE
Query editor unusable with large number of measurements

### ISSUE THREAD

**Issue by miracle2k** [influxdata/chronograf#2826]
I have a large number of measurements in my database (should we around 200.000), and the query editor seems to try to load all of them at once, which blocks for a long time, rendering the interface unusable.

Would it make sense to limit the number of items loaded here, or doing the filtering server side?

**Comment by russorat** [comment]
@miracle2k thanks for the report. Is there a specific reason you have so many measurements in a single DB? Have you considered splitting into different databases or retention policies within the same database?

**Comment by miracle2k** [comment]
I'm logging price movements for a large number of markets and assets. Each is stored as a separate measurement. I could shard it across databases if that was necessary, but researching led me to believe that InfluxDB itself doesn't have a problem with that amount of measurements. 

An easier workaround might be to just not send more than X measurements, and ignore the rest completely. It is preferable to be able to just use other measurements by manually typing them into the query window, than not being able to use the UI at all due to the browser blocking.

**Comment by russorat** [comment]
yep you're right, no issues with influxdb handling everything in a single db. the limitations are more in how you query the data. For example, you can't group by measurement names, so comparing different markets and assets might become challenging. See an example here: https://docs.influxdata.com/influxdb/v1.4/concepts/schema_and_data_layout/#don-t-encode-data-in-measurement-names

At any rate, limiting the number of results returned is valid, so we will keep this open and consider it for a future release.

Thanks!

**Comment by alexpaxton** [comment]
@russorat We might be able to repurpose the infinite scroll component here

**Comment by jaredscheib** [comment]
The server work for this story has mostly been completed in https://github.com/influxdata/chronograf/pull/2832. I've closed that PR until the client work for this story is completed on the same branch.

Remaining to do for this story:
- [ ] define client pagination UX
- [ ] design client pagination UX
- [ ] implement pagination in the client using the pagination API created in the branch in https://github.com/influxdata/chronograf/pull/2832
