### ISSUE TITLE
Clicking a host makes browser unresponsive

### ISSUE THREAD

**Issue by gillesbroes2016** [influxdata/chronograf#2841]
![image](https://user-images.githubusercontent.com/22746754/36546168-ff15a464-17ea-11e8-80c9-bb866e0231e3.png)

When you click on a host, it doesn't load and makes the browser unresponsive.

TICK-running in docker.

All images are image:latest

Thanks for any help!

**Comment by russorat** [comment]
@gillesbroes2016 thanks for the report. Could you provide any steps you took so we could try and reproduce the issue on our side?

**Comment by gillesbroes2016** [comment]
Hi

I simply deployed the TICK-stack in Docker using the following config:

---

version: '3'

services:

  # FRONT
  chronograf:
    image: chronograf:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == dockermgtA
    volumes:
      - chronograf-data:/var/lib/chronograf
    ports:
      - "8888:8888"
    networks:
      - influx
    depends_on:
      - kapacitor
      - influxdb

  # MIDDLE
  kapacitor:
    image: kapacitor:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == dockermgtA
    volumes:
      - kapacitor-data:/var/lib/kapacitor
      - /etc/kapacitor/config:/etc/kapacitor
    ports:
      - "9092:9092"
    networks:
      - influx
    depends_on:
      - influxdb

  # BACK
  telegraf:
    image: telegraf:latest
    deploy:
      mode: global
    volumes:
      - /etc/telegraf:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - influx
    depends_on:
      - influxdb

  # DATABASE
  influxdb:
    image: influxdb:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == dockermgtA
    volumes:
      - influxdb-data:/var/lib/influxdb
      - /etc/influxdb/config:/etc/influxdb
    ports:
      - "8086:8086"
    networks:
      - influx

networks:
  influx:

volumes:
  chronograf-data:
  kapacitor-data:
  influxdb-data:

---

After this I go to the Chronograf webpage, and I add a source for influxdb.
When I click the host tab, and then one of the hosts (all of them produce the issue), the issue occurs.

I tried Firefox, Chrome & IE with the same result.

Thanks for looking into this.

**Comment by russorat** [comment]
could be related to #2862

**Comment by russorat** [comment]
Looks good!
