### ISSUE TITLE
TICKscript saved in TICKscripts section shows in Alert Rules listing and not in TICKscripts section

### ISSUE THREAD

**Issue by stevebang** [influxdata/chronograf#2843]
Chronograf 1.4.1.3: Build Alert Rules or Write TICKscripts (page)

1. Create an alert rule using the alert rule builder and save the alert rule.
2. Click the Edit TICKscript button and then copy the generated TICKscript.
3. Click the Write TICKscript button in the TICKscripts section.
4. Give an ID to TICKscript, select the database, and then paste the generated TICKscript into the editor.
5. Click Save New TICKscript button.

The new TICKscript ID does not appear in the TICKscripts section, but appears as an alert rule with the name assigned in the name variable. 

Two issues with this behavior 
* duplicate named alert rules are allowed -- should we say a rule by that name exists? (
* expected TICKscript ID doesn't appear in the TICKscripts listing -- expected? Confusing to users?

**Comment by russorat** [comment]
- duplicate named alert rules are allowed -- should we say a rule by that name exists?
  - see #2836 
- expected TICKscript ID doesn't appear in the TICKscripts listing -- expected? Confusing to users?
  - we can track that in this issue
