### ISSUE TITLE
Changing dashboard visualization from Dygraph go non-Dygraph causes Dygraph error

### ISSUE THREAD

**Issue by ischolten** [influxdata/chronograf#2844]
Changing dashboard visualization from Dygraph go non-Dygraph causes Dygraph error.
![screen shot 2018-02-22 at 1 26 26 pm](https://user-images.githubusercontent.com/5751863/36565024-121c7176-17d4-11e8-9e3f-8a7a4b9f09df.png)

**Comment by russorat** [comment]
@ischolten in what scenario would a user run into this issue?
