### ISSUE TITLE
Y axis labels are not maintained after refresh

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2845]
I tried adding a y-axis label and it works when i save, but disappears after i refresh the page. 

![label_disappears](https://user-images.githubusercontent.com/4805997/36571648-9cd70390-17ec-11e8-9617-d7058402c4ea.gif)

**Comment by alexpaxton** [comment]
Might be related to https://github.com/influxdata/chronograf/issues/2567

**Comment by russorat** [comment]
LGTM
