### ISSUE TITLE
Dashboard to inspect InfluxDB itself

### ISSUE THREAD

**Issue by miracle2k** [influxdata/chronograf#2847]
I thought it would be nice there was a dashboard to see what influxdb is doing, via the `_internal` database of my InfluxDB instance. I was wondering why this doesn't come canned. Researching it, I noticed that there is apparently a precanned template that works with a telegraf input plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb).

I am curious to understand what the benefit of using telegraf for this is. Also, are there plans in general to support importing dashboard templates independently of telegraf?

**Comment by russorat** [comment]
@miracle2k thanks for the report. We like to keep github issues specific for feature requests and bug reports. the first part of this question looks like something that might be better suited for https://community.influxdata.com/.

We do have plans to make improvements to the pre-canned dashboards to make them more discoverable and flexible. Although it's not documented, you can add your own layouts to Chronograf today. For cloning dashboards and graphs, see #2266. For exporting, see #1155
