### ISSUE TITLE
Add ability to define multiple slack nodes in Kapacitor

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2855]
connect https://github.com/influxdata/kapacitor/issues/1696

- [x] ensure that the latest changes hasn't broken the existing slack config in chronograf
- [x] add the ability to configure multiple slack integrations in chronograf

**Comment by jaredscheib** [comment]
Blocked until all of the TypeScript conversion work that @ischolten was doing for #2786 is separated out as its own PR, submitted, and merged into master.

**Comment by alexpaxton** [comment]
![screen shot 2018-04-04 at 10 13 54 am](https://user-images.githubusercontent.com/2433762/38323492-3ad847dc-37f2-11e8-8bb9-eb21c679efba.png)

If the user configures the slack endpoint, a second slack endpoint appears. If the user configures the second endpoint a third appears. This pattern allows for as many slack configs as necessary with as little changes to UI as possible

**Comment by alexpaxton** [comment]
### Changes:

- `Configure` --> `Configured`
- Green checkmarks are no longer necessary, as the list only shows configured endpoints
- `Add an Endpoint` dropdown shows full list of endpoints that can be configured
- Selecting an endpoint from the dropdown adds it as a tab in the list
- Some can be added multiple times

![screen shot 2018-04-23 at 12 07 06 pm](https://user-images.githubusercontent.com/2433762/39148379-062fde92-46f1-11e8-81b6-9be92384b2d0.png)
![screen shot 2018-04-23 at 12 07 46 pm](https://user-images.githubusercontent.com/2433762/39148385-094cb258-46f1-11e8-97a7-2e0089009475.png)

- Dropdown in *Alert Rule Builder* uses `li.dropdown-header`s to delineate more clearly the two sections in the menu
- If there are multiple Slack endpoints (for example) then Slack shows up twice in the menu

![screen shot 2018-04-23 at 12 32 40 pm](https://user-images.githubusercontent.com/2433762/39149067-ceae1c70-46f2-11e8-942a-7ca4216be084.png)

**Comment by alexpaxton** [comment]
Spent some more time experimenting with the design. Considering that we may redesign much of the kapacitor config UI in the future it is more strategic to do something really simple for now. Essentially, users will be able to create multiple "configs" within the same tab for an endpoint. If there are multiple configurations each one requires a nickname.

![screen shot 2018-04-26 at 11 27 58 am](https://user-images.githubusercontent.com/2433762/39324866-8355f20c-4945-11e8-8b56-88bd21ad18dc.png)
![screen shot 2018-04-26 at 11 29 02 am](https://user-images.githubusercontent.com/2433762/39324871-874cff40-4945-11e8-9cc7-6b514612afc0.png)

Nicknames are exposed in this dropdown:
![screen shot 2018-04-26 at 11 36 16 am](https://user-images.githubusercontent.com/2433762/39325047-0f89a66a-4946-11e8-8e65-4b183e115ab7.png)

**Comment by russorat** [comment]
looks good!

**Comment by russorat** [comment]
- [ ] parse error when trying to save a second slack node without filling in an id. error should be shown to the user.
- [ ] alert builder, when switching to a different slack node, does not update the script (see below)
![kapture 2018-05-16 at 14 32 38](https://user-images.githubusercontent.com/4805997/40145277-11508272-5916-11e8-8c23-2ccac82a8c3d.gif)
