### ISSUE TITLE
add maxInterval to .stateChangesOnly() in the AlertBuilder

### ISSUE THREAD

**Issue by cxcv** [influxdata/chronograf#2861]
Alerts are only sent once, but it would be greate to resend them after a given time.
This is possible in tick script with the  `.stateChangesOnly(60m)`  statement, but the Chronograf-generated tickscript has no variable to define "`60m`". I would really like to have this feature in the rule generator.
Also, somehow  `.stateChangesOnly()` is added twice to the tickscripts which looks like a mistake.

**Comment by russorat** [comment]
@cxcv thanks for reporting. I wasn't able to reproduce the multiple stateChangesOnly() issue. Maybe your script has multiple alert nodes in which case, you would need one for each node?

We will consider adding this for a future release.

**Comment by cxcv** [comment]
@russorat thanks for considering this. regarding the malformed tickscript, I can reproduce this as follows:
- create a new rule, let's say for system with field load5
- view the tickscript - looks ok
- edit this rule and change the field to load15
- now the script is different

To my understanding, the visual editor is parsing the previously generated script and I assume the stateChangesOnly somehow is left on the stack. When the script is generated again, the default block is prepended resulting in doubling this line.

Here's the generated script from run two:
```
...

var trigger = data
    |alert()
        .crit(lambda: "value" > crit)
        .stateChangesOnly()
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .stateChangesOnly()

...
```

**Comment by nhaugo** [comment]
@russorat can we break this into two issues, one for the bug and one for the feature request.

**Comment by russorat** [comment]
opened one for the bug. let's keep this one for the feature request.

**Comment by jacobrandall** [comment]
Would the addition of this feature allow us to create a "global" (or otherwise reusable) default value for `maxInterval`? It seems that currently we have to set `maxInterval` in each individual tick script. It would be very useful to be able to 1) set it via environment variables and config file as well as 2) have it be the default and be able to override it in the individual tickscripts.
