### ISSUE TITLE
Docker dashboard hangs the browser

### ISSUE THREAD

**Issue by m0nhawk** [influxdata/chronograf#2862]
When I try to open canned Docker dashboard it hangs the browser.

The URL in this form:

https://localhost/sources/0/hosts/localhost?app=docker

In logs there are tons of requests to InfluxDB and no errors.

**Comment by russorat** [comment]
Hi @m0nhawk, thanks for reporting. I am seeing something similar using minikube. We will investigate.

![image](https://user-images.githubusercontent.com/4805997/36824781-00705bba-1cb9-11e8-8a56-7716bce1c8e4.png)

**Comment by russorat** [comment]
sweet!
