### ISSUE TITLE
Implement OAuth Token Refreshing

### ISSUE THREAD

**Issue by gianarb** [influxdata/chronograf#2889]
Hello!

Jenkins has a very nice integration with OAuth that makes my life very comfortable. It supports oauth providers as Chronograf and currently I am using the GitHub integration.

The nice thing about Jenkins is that the login page is able to detect if you are logged on GitHub, and if you are it won't ask you to press any button. It will just log you in.

This is very nice and I would love to have it in Chronograf because right now at some point I am checked out because my token expired but in reality it should be able to check that my GitHub token is still good.

**Comment by russorat** [comment]
connect #3938
