### ISSUE TITLE
In the alert rule builder, when i go to configure a alert node for Kapacitor, i lose all my changes without warning

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2897]
for a user building an alert rule, they go through the configuration part, then realize they didn't configure an alert node, and they click the button to configure, they lose all their work without a warning. this would add a warning asking them to save before leaving the alert builder.

**Comment by jaredscheib** [comment]
cc @ebb-tode

**Comment by russorat** [comment]
actually this is fixed. my bad.
