### ISSUE TITLE
click on measurement name to collapse it

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2899]
- [x] clicking on a measurement name in the data explorer should collapse the list of tag keys

![kapture 2018-02-28 at 23 37 04](https://user-images.githubusercontent.com/4805997/36832433-5489ea3c-1ce0-11e8-8575-7da9b7c4bdc4.gif)

**Comment by alexpaxton** [comment]
🙀

**Comment by russorat** [comment]
so good!
