### ISSUE TITLE
Unable to get hosts

### ISSUE THREAD

**Issue by tanji** [influxdata/chronograf#2902]
I currently monitor 75 hosts with influxdb and since reaching this number the chronograf Hosts page won't load anymore.
```
chronograf    | time="2018-03-01T10:13:47Z" level=error msg="Error message Timeout waiting for Influx response" component=server http_status =408 
chronograf    | time="2018-03-01T10:13:47Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="172.18.0.1:38104" response_time=1m0.003458942s status=408 
```
Seems that the request to influxdb takes more than 1 minute. Is it possible to increase this timeout or make the query faster?

**Comment by tanji** [comment]
This query in particular seems really slow:

```
363958                          SHOW SERIES FROM /^apache$|^consul_health_checks$|^consul_consul_fsm_register$|^consul_memberlist_msg_alive$|^consul_raft_state_candidate$|^consul_consul_http_GET_v1_health_state__$|^consul_raft_state_leader$|^consul_serf_events$|^cpu$|^disk$|^diskio$|^docker$|^docker_container_blkio$|^docker_container_net$|^elasticsearch_indices$|^haproxy$|^influxdb_database$|^influxdb_httpd$|^influxdb_queryExecutor$|^influxdb_write$|^kubernetes_node$|^k
ubernetes_pod_container$|^kubernetes_pod_network$|^kubernetes_system_container$|^system$|^mem$|^memcached$|^mesos$|^mongodb$|^mysql$|^net$|^netstat$|^nginx$|^nsq_channel$|^nsq_server$|^nsq_topic$|^phpfpm$|^ping$|^postgresql$|^processes$|^procstat$|^rabbitmq_node$|^redis$|^riak$|^varnish$|^win_cpu$|^win_mem$|^win_net$|^win_system$|^win_websvc$/ telegraf 8m20s  running
```

Also, the huge problem is, chronograf will actually retry this everytime, i have 10 of those queries running right now, which is really bad

**Comment by russorat** [comment]
@tanji thanks for reporting this. we are in the process of redesigning the hosts page to improve performance (#682) although usually the slowdown shouldn't happen with only 75 hosts. Our internal monitoring has well over 1000 hosts displayed on that page in only a few seconds. Can you confirm which version of Chronograf you are running?

**Comment by tanji** [comment]
I am running the latest version released on quay.io: 1.4.2.1
But the problem is InfluxDB (1.4.3), I think, not chronograf. If as you say this query should complete rapidly. We have 90G of timeseries though, so if this query scans our whole DB it's not gonna be fast no matter what.

**Comment by tanji** [comment]
@russorat I think I found the issue, there were too many series in InfluxDB because of docker virtual ethernet cards being registered, causing a whooping 350K `net` series to clutter my database.

While I clean those series I have a few thoughts about this issue though: I think the initial `SHOW SERIES` regular expression query might be inefficient for people that inadvertently or not have a large number of series.
Maybe it would be worth to do a `SHOW SERIES FROM ...` for each measurement instead of using the regex. However that could be counter-productive with a small number of series, so I guess this needs to be benchmarked.

**Comment by russorat** [comment]
@tanji great i'm glad you were able to dig in a little deeper. We are working through and designing ways for users to have more control over the queries that are used to build the host list page. We will make sure we consider this use case in #682 .
