### ISSUE TITLE
Add support for Kafka Alert Node as part of Kapa 1.5

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2904]
Here are the options for the Kafka config page:

```
[[kafka]]
  # Configure Kafka
  enabled = false
  # ID is a unique identifier for this kafka cluster.
  id = "localhost"
  # Brokers is a list of host:port addresses of Kafka brokers.
  brokers = []
  # Timeout on network operations with the brokers.
  # If 0 a default of 10s will be used.
  timeout = 10s
  # BatchSize is the number of messages that are batched before being sent to Kafka
  # If 0 a default of 100 will be used.
  batch-size = 100
  # BatchTimeout is the maximum amount of time to wait before flushing an incomplete batch.
  # If 0 a default of 1s will be used.
  batch-timeout = 1s
  # Use SSL enables ssl communication.
  # Must be true for the other ssl options to take effect.
  use-ssl = false
  # Path to CA file
  ssl-ca = ""
  # Path to host cert file
  ssl-cert = ""
  # Path to cert key file
  ssl-key = ""
  # Use SSL but skip chain & host verification
  insecure-skip-verify = false
```

**Comment by jaredscheib** [comment]
This addresses the Kafka config but not configuring a specific alert endpoint handler.
Are all of these options for the global config?
If so, are there any handler-specific options?
And which options, if any, do we want to provide handler-specific overrides to global config options for?

**Comment by jaredscheib** [comment]
This also appears blocked on https://github.com/influxdata/chronograf/issues/3292.

**Comment by russorat** [comment]
1. Initial docs are here https://github.com/influxdata/docs.influxdata.com/blob/refactor/alert-handler-docs/content/kapacitor/v1.5/event_handlers/kafka.md

I think there are things you can build without #3292 so I don’t think this is blocked

**Comment by jaredscheib** [comment]
Thanks. I asked about being blocked because in #3292 it says:
> required for #2786 and #2904

**Comment by russorat** [comment]
- [ ] verify kafka topic and template can be set via the UI.

![kapture 2018-05-21 at 16 42 46](https://user-images.githubusercontent.com/4805997/40335041-81782006-5d16-11e8-8e41-c5781ce9416f.gif)
