### ISSUE TITLE
Recommended Backup Strategy

### ISSUE THREAD

**Issue by pmyjavec** [influxdata/chronograf#2915]
Hi all,

Please advise if there a recommended way to perform backups on-demand? I understand a backup of sorts if performed during an upgrade; However, how do I safely go about performing backups against a running instance of Chronograf with many writes occurring to the DB?

Thanks

**Comment by russorat** [comment]
hi @pmyjavec please open a post in https://community.influxdata.com for discussions like this. we like to keep the issues list for specific feature requests or bug reports.
