### ISSUE TITLE
Boolean graph

### ISSUE THREAD

**Issue by think-free** [influxdata/chronograf#2916]
I have sensors with boolean values (true|false). (Presence, open window, thermostat on/off, ...)
I can't find a way to graph them. Seems that chronograf only accept numerical values.
Any way to have a graph from that values ?

**Comment by russorat** [comment]
@think-free thanks for the question. in the future, this would be better suited for https://community.influxdata.com, as we like to keep issues for bug reports and feature requests. 

Until we complete #2718 or #1686, you would need to convert the booleans to a numerical format using an aggregate function like `count`. You might be able to have two queries on the same graph, one for true, one for false, using the tabs in the graph query editor, but i don't know if that solves your use case.
