### ISSUE TITLE
Presenting application uptime using the http_response plugin

### ISSUE THREAD

**Issue by zielot** [influxdata/chronograf#2918]
I would like to create a dashboard that provides more or less what the Pingdom uptime monitoring dashboard provides. What I am thinking to start is that I would like  a basic green-light/red-light visualization for each application which indicates whether the application is up. 

I have configured multiple http_response plugins to hit given URLS (some of which are available only within the company firewall. This is working fine and I see the data in InfluxDb and I am able to query the data using the query builder. 

For the first green/red light I am thinking that when the below query is less than 5 the light should turn red, otherwise green

SELECT count("http_response_code") FROM "telegraf"."autogen"."myservice" WHERE time > now() - 5m and "http_response_code"=200

Is there a way that if a result is above a threshold I can display some graphic and/or text (e.g. "UP") and if not display some other text?

**Comment by russorat** [comment]
Hi @zielot thanks for the question. In the future, this would be a better topic for https://community.influxdata.com as we like to keep issues for bug reports and features.

As for the Up/Down indicator, i suggest you check out the new threshold options on the single stat graph type in 1.4.2. You can configure it to change the background which might give you what you are looking for.

If you have additional questions, please open a new topic in https://community.influxdata.com. If you have bug reports or feature requests after using the new single stat features, please open them here.
