### ISSUE TITLE
.stateChangesOnly() is added twice to the tickscripts

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2921]
to reproduce:
build a new alert rule and save
open the tick script for that alert rule and notice that there is a .stateChangesOnly() on the alertnode
open the alert rule in the editor, change the threshold, save
open the tick script and see that there is a second stateChangesOnly() function on the alertnode

originally reported in #2861

**Comment by russorat** [comment]
sweet!

**Comment by shkrid** [comment]
It's removes stateChangesOnly() after edit old scripts via UI

**Comment by russorat** [comment]
@shkrid all of them or just the extra?

**Comment by bthesorceror** [comment]
Cannot reproduce in the latest master, @shkrid please let us know if you still experience this after upgrading.
