### ISSUE TITLE
Linear gauges

### ISSUE THREAD

**Issue by davidgs** [influxdata/chronograf#2925]
Something like the following: 
![image axd](https://user-images.githubusercontent.com/2071898/37044849-90b9d64c-2132-11e8-8df3-a4fc080abf74.png)

With the ability to have them either horizontal or vertical, would be great!

**Comment by aldas** [comment]
(Vertical) linear gauge would be really nice with min-max range.  I tried to use line graph + single stat but it is quite ugly hack
![linear_graph](https://user-images.githubusercontent.com/2320301/45589757-2e3d3000-b934-11e8-98c1-814d1530ccdf.png)
