### ISSUE TITLE
Update Alert Node Config for OpsGenie V2

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2929]
connect https://github.com/influxdata/kapacitor/issues/1708

- [x] the stuff from https://github.com/influxdata/chronograf/issues/2786
- [x] Add an OpsGenie v2 config option for the Kapacitor config page
- [x] Add a warning in the UI indicating that OpsGenie v1 is deprecated
- [x] Clicking enter after entering the API key should immediately change to the redacted input
- [x] Update Kapacitor to new rc tag

**Comment by jaredscheib** [comment]
Blocked until all of the TypeScript conversion work that @ischolten was doing for #2786 is separated out as its own PR, submitted, and merged into master.
