### ISSUE TITLE
Add ability to set template variables and date ranges via url parameters

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2934]
this would allow users to create deep links into dashboards by setting the template values in the url.

- [x] users can use url parameters to set template variables for deep linking to a dashboard
- [x] when a user updates a template variable in the ui, the url should also be updated. the url should always represent the state on the page so the user can copy and paste it.
- [x] if a user adds an invalid value, a notification should be shown and the default option should be chosen
- [x] users can use url parameters to set the time range for deep linking to a dashboard (customer request)

what happens when there is an invalid value?
 - notify the user that the value provided was not in the possible values

- url params take precedence over what's stored in the db
- changing the variables should change the url
- clicking the back button should go to the previous page (#3213)

**Comment by russorat** [comment]
required for #682

**Comment by russorat** [comment]
this might solve this issue as well: https://github.com/influxdata/chronograf/issues/2245

**Comment by desa** [comment]
@russorat what happens if the user does not specify all of the template variables required?

**Comment by russorat** [comment]
the idea is that the url parameters take precedence over defaults or anything stored in the bolt db. if there is a value in the url, use it, otherwise, we should keep the same default behavior as we have today.

**Comment by desa** [comment]
After discussing this with @jaredscheib @ischolten @goller and @kelwang I think this issue can be solved entirely in the frontend

**Comment by jaredscheib** [comment]
Let's take care of #3524 first.

**Comment by jaredscheib** [comment]
- [ ] url should always reflect all template variables
- [ ] filter out invalid template variables, except for `present`
- [ ] overwrite url for viewer with dashboard's selections, show error
- [ ] if user supplies a invalid value for a tempvar, show error and set to / use current dashboard value

**Comment by jaredscheib** [comment]
- [ ] differentiate and persist zoomed time range in URL as separate from dashboard time range to make this zooming experience continuous

**Comment by jaredscheib** [comment]
- [x] fix zoomed time range from URL queries
- [ ] ensure dashboard names are still being received and/or handled properly in DashboardPage render method -- since refactoring to remove `getDashboardsAsync`
- [ ] overwrite url for viewer with dashboard's selections, show error
- [ ] sync url params upon dashboard switch via switcher
- [ ] clicking browser Back button should take user to last actual location, unrelated to url tempvar changes
- [ ] convert components to typescript
- [ ] add tests
- [ ] update changelog
