### ISSUE TITLE
Improve configuring fine grained auth

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2938]
- [x] users will select multiple options, but they are cleared before the user can save them
- [ ] unsetting permissions doesn't always clear them out of influxdb. for example, set read and write, save, check influx and see all privileges are set, then uncheck them, save, and see there is no change in influx.

**Comment by jaredscheib** [comment]
@russorat was the first checkbox resolved by #3048? and is the second resolved by #1902? it seems that this issue merits revision or further specification.

**Comment by russorat** [comment]
@jaredscheib spoke with @121watts about this yesterday. he should have assigned it to himself.

**Comment by russorat** [comment]
look good! thanks!
