### ISSUE TITLE
Host is empty when open page with low version chrome(49) browser.

### ISSUE THREAD

**Issue by FavorMylikes** [influxdata/chronograf#2949]
Here shows up I have only one host, but I can't see it.

![image](https://user-images.githubusercontent.com/16064851/37199488-c95c764e-23bc-11e8-8ded-d34c745ba804.png)

I checked html code, It looks like all items be hidden because overflow style, when I open this page with new chrome browser or edge. It works well.

Is it a BUG?

**Comment by russorat** [comment]
@FavorMylikes thanks for the report. Is there a specific reason you aren't using the latest browser? we will most likely tackle this in #682 .

**Comment by FavorMylikes** [comment]
It is not chrome browser actually.

It named sogo browser, a localized browser that using in china, but use chrome kernel with low version for some compatible reason.

It has about only 10% market in here. 

If this problem is not important, that will be ok if it can't be solved I thinnk.
