### ISSUE TITLE
Template variables no longer stores all data

### ISSUE THREAD

**Issue by ChristianTrolleMikkelsen** [influxdata/chronograf#2950]
Hi

After upgrading from 1.3.8.3 to 1.4.2.1 yesterday our template variables on the dashboards only "remember" 1 value.
Recreation of or editing of the variables do not fix it.
When we edit/create a variable we can see ALL the variables and the variable work. However a refresh in the browser causes the variable to only contain 1 value.

A workaround right now is to use the CSV type but we have a lot of dashboard, so its a quite an issue :).

**Recreate:**

1. New dashboard
2. Add variable which maps to Tag values (which must have multiple values).
3. Check that the variable contains multiple values.
4. Refresh in browser (Chrome)
5. Check that the variable now only contains 1 value.

**Note:**
Some of our tag values contains whitespaces, this was an issue in chronograf a long time ago.

**Comment by russorat** [comment]
hi @ChristianTrolleMikkelsen, thanks for the report. We're investigating and will update here within the hour.

**Comment by russorat** [comment]
@ChristianTrolleMikkelsen Myself and a developer have tried to reproduce this on the latest build (1.4.2.3) and can't seem to. Are there any other details you might be able to provide about what you are seeing to help us investigate?

![kapture 2018-03-09 at 12 04 37-2](https://user-images.githubusercontent.com/4805997/37227436-1acf3186-2392-11e8-8261-81f1a49102c6.gif)

**Comment by ChristianTrolleMikkelsen** [comment]
I'll try upgrading to 1.4.2.3, test and get back. We are on 1.4.2.1, so hopefully its fixed :)

**Comment by ChristianTrolleMikkelsen** [comment]
I do not know if it matters but we're on Debian on Azure and we do scriptet in place upgrades.

**Comment by russorat** [comment]
@ChristianTrolleMikkelsen thanks for following up. I noticed that there is a message indicating that a new chronograf version was detected and settings were cleared when you are reloading the page. That shouldn't be showing. Could you give a little more information about your upgrade process?

**Comment by ChristianTrolleMikkelsen** [comment]
Sure :).
I used the same script as always:

sudo systemctl stop chronograf
...
wget https://dl.influxdata.com/chronograf/releases/chronograf_1.4.2.1_amd64.deb -q
sudo dpkg -i chronograf_1.4.2.1_amd64.deb
...
sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/chronograf
sudo sed -i "s/8888/80/g"  /lib/systemd/system/chronograf.service
...
sudo systemctl start chronograf

Right on top the existing installation (im guessing this i wrong... ?)
The ... is there to symbolize parts of the scripts which do not concern Chronograf.

**Comment by russorat** [comment]
i found a way to reproduce this (or something similar). It looks like clicking the pencil once doesn't save the change, but clicking the pencil twice does. We will work on fixing this.

![kapture 2018-03-21 at 15 55 48](https://user-images.githubusercontent.com/4805997/37741916-a2394ffc-2d20-11e8-98bb-e5e7d43fc158.gif)

**Comment by russorat** [comment]
looks good!
