### ISSUE TITLE
Add Map Graph Type

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2955]
- [ ] Decide on format for geo coordinates
 - [ ] Keep all points on the graph but indicate the latest point somehow (possibly trails)
 - [ ] view window can be set or calculated automatically

**Comment by russorat** [comment]
@ebb-tide could you add / update the list of items associated with this issue from your initial investigation?

**Comment by ebb-tide** [comment]
- We will be using data from OpenStreetMap: https://www.openstreetmap.org/copyright
- with Leaflet react components for interaction and indicators
- We should determine how large a geographical area, and at what resolution we can reasonably embed in to Chronograf.
Further init requirements could be:
- [ ] time slider that can control 'highlighted' region of trail
- [ ] hoverTime is also? indicated on trails (synced with dygraph hovering)
- [ ] zoom controls on map to zoom in/ double click to zoom back
- [ ] if authorized, set view window from dashboard page- not from mapOptions
- [ ] hoverLegend that shows which trails passed by hovered lat long at what time.
- [ ] customizable colors for trails
- [ ] toggle visibility for trails 
- [ ] ability to draw regions or lines on map that persist
- [ ] staticLegend
- A second iteration of maps could allow users to input their mapbox API credentials to get customizable maps of their own- I'm not sure of the licensing ramifications here.

**Comment by aurimasniekis** [comment]
Any progress on this?

**Comment by marcowira** [comment]
Any updates? Would absolutely love to be able to use maps in Chronograf

**Comment by marcowira** [comment]
@ebb-tide  - Any thoughts on using MapBox as a solution for mapping? I ask because it affords a lot of UI customization ability and I hear from friends that their mapping solution is really awesome to work with being developer focused. Thoughts? (ps. I'm affiliated with Mapbox in anyway)

**Comment by zamashal** [comment]
@ebb-tide any updates?

**Comment by russorat** [comment]
We are in the process of bringing a lot of our visualization capabilities into the https://github.com/influxdata/vis library. This will allow us to add new graph types much easier than we have in the past, which will make this easier to build. So no update for the 1.x line, but definitely something we want to enable with the new vis library in 2.0.

**Comment by zamashal** [comment]
> We are in the process of bringing a lot of our visualization capabilities into the https://github.com/influxdata/vis library. This will allow us to add new graph types much easier than we have in the past, which will make this easier to build. So no update for the 1.x line, but definitely something we want to enable with the new vis library in 2.0.

@russorat Just to make sure I understand, is the vis library something that will be integrated with Chronograf's UI? Or is it going to be a stand-alone UI?
