### ISSUE TITLE
dashboard changes vanish mysteriously.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/chronograf#2958]
This might be pilot error, this might be the lack of an apparent "save dashboard". 

I have 4 graphs and 2 dials. Of the graphs of "line + value", 1,2,4 do not have compare on.
Add COMPARE 1d to 3 graphs. 
all 4 now have compare.

click dashboards, come back to this dashboard.
Now only the LAST one twiddled as COMPARE 1d, (It's also lost its fill under the line at some stage.)

**Comment by bunnyevans** [comment]
Also, 
change 3 to have COMPARE, reload page, 4 lost its compare.

change 2 to have COMPARE, look at 1 but do not change, reload and no one has compare.

**Comment by russorat** [comment]
@bunnyevans thanks for the issue. I'm having a little trouble understanding what you are trying to say. Could you possibly add a screenshot or two highlighting what issue you are seeing?

**Comment by bunnyevans** [comment]
Okay, let's try again! I do like the compare graph, I just cant get it to stick!
(I'm not seeing a SAVE button, or an option to change the colours.)

bunny:~ % go/bin/chronograf

Note, the colour under the lines has disappeared, no way to get that back either.

b1 - before
b2 - add COMPARE 1d to all of them.
b3 - reload that same screen note compares disappearing.
b4 - go to dashboard, come back here, another one disappeared.

![b4](https://user-images.githubusercontent.com/37229871/37553397-a5881abc-2a0a-11e8-9b09-5812c600d165.PNG)
![b1](https://user-images.githubusercontent.com/37229871/37553398-a5ae4ca0-2a0a-11e8-9de9-048b1560c697.PNG)
![b2](https://user-images.githubusercontent.com/37229871/37553401-a5d51f1a-2a0a-11e8-8ef1-165809f1a3ca.PNG)
![b3](https://user-images.githubusercontent.com/37229871/37553402-a5fa6612-2a0a-11e8-876d-761a5e58ae07.PNG)
