### ISSUE TITLE
New annotations don't show up unless you refresh the dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2959]
- [ ] annotations should be refreshed at the same interval as the graphs on the page.

I noticed that when I have a script pushing new annotations into chronograf, they won't show up on my dashboard unless i refresh the page. The annotations should be refreshed on each interval as well.

**Comment by nhaugo** [comment]
![dumpster-fire](https://user-images.githubusercontent.com/1003269/37932087-73f4a576-30fc-11e8-86ef-5d3d62855313.gif)

**Comment by russorat** [comment]
amazing! 🐇
