### ISSUE TITLE
Alert Status Page alerting time not converted to local time

### ISSUE THREAD

**Issue by vicochan** [influxdata/chronograf#2960]
Alarm Status Page alarm time is standard UTC time and does not convert to local time，Can I modify the configuration?
![image](https://user-images.githubusercontent.com/20240490/37262648-79121f0c-25df-11e8-8447-f11eb5203967.png)

**Comment by russorat** [comment]
Hi @vicochan , currently there is no way to configure that in Chronograf. We will consider this when we tackle #1960

**Comment by hydrandt** [comment]
Is this (and #1960) still far away? If so, I will add information about this into the docs and make a PR with that, so that others don't have to figure this all out by themselves :-)

**Comment by russorat** [comment]
@hydrandt thank you! this is still a few releases out. If you'd like to submit a PR, we'd be happy to review.  Thanks!

**Comment by sdicataldo** [comment]
Samu issue, are there any update about this feature?
Have an alert history with "wrong" time, it is not really user friendly, and limiteta a lot the chronograf usage.

**Comment by lukevmorris** [comment]
We should offer some configuration option in header of the page. When UTC is selected, the histogram timestamps and the alerts table time stamps will switch to UTC. When local is selected, render timestamps as local throughout the page.

**Comment by lukevmorris** [comment]
When toggling between UTC and local, this setting should apply globally. That is, when the feature becomes available on dashboards:
- If you toggle from local to UTC on Status Page, then navigating to a dashboard will show UTC timestamps
- If on a dashboard you toggle from UTC to local, Status Page will thereafter render local times
- Clearly indicate in the alert list which timezone is selected
