### ISSUE TITLE
Chronograf configuration should support oauth orgs that will override mappings to add users as superadmins

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2963]
this could be auth0 only if needed

this would override all other mapping behavior
only configurable via the command line.

**Comment by jaredscheib** [comment]
So would usage look like this, for example, with all of these ENV vars:
```
MAPPINGS_OVERRIDE_SCHEME=oauth2
MAPPINGS_OVERRIDE_PROVIDER=github
MAPPINGS_OVERRIDE_PROVIDER_ORG=pineapples
MAPPINGS_OVERRIDE_CHRONOGRAF_ORG=Default
MAPPINGS_OVERRIDE_ACCESS=superadmin
```
with no default values for any of those, and all of them required for it to work?

**Comment by jaredscheib** [comment]
Or @desa suggests something more specific and simpler, unrelated to mappings, like:
`AUTH0_SUPERADMIN_ORGANIZATION=pineapple_team`

**Comment by lukevmorris** [comment]
I agree with something simple like `AUTH0_SUPERADMIN_ORGANIZATION=pineapple_team`
