### ISSUE TITLE
Cronograf /sources/2/hosts summary causes high influxDB CPU

### ISSUE THREAD

**Issue by sgreszcz** [influxdata/chronograf#2977]
I noticed that when recently upgrading Cronograf to 1.4.2-3 that I was getting really slow response times when accessing the "hosts" (/sources/2/hosts) summary screen in Cronograf.

After some investigation, I can see that having that page open causes about 80% CPU on my 8-CPU InfluxDB server.

https://pasteboard.co/HbSEP7S.png

https://pasteboard.co/HbSEY9Y.png

https://pasteboard.co/HbSF5MK.png

**Comment by russorat** [comment]
@sgreszcz thanks for opening an issue. You definitely shouldn't be seeing a spike for such a small number of hosts. Do you mind giving us a little more information about the size of the data being stored in Influx? What's the cardinality fo your data?

**Comment by sgreszcz** [comment]
Is there a quick way to dump this information from Influx - I do have the graphs set in Grafana for _internal and the default Telegraf monitoring in Cronograf.

**Comment by sgreszcz** [comment]
_Internal Metrics: https://pasteboard.co/HbT5q24.png

Telegraf InfluxDB Metrics: https://pasteboard.co/HbT6rRD.png

cpu:                                                            
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz
                       Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz, 2700 MHz

              total        used        free      shared  buff/cache   available
Mem:          15651        1405        2830         153       11415       13704
Swap:          8191           0        8191

**Comment by jaredscheib** [comment]
This _may_ be solved by the upcoming https://github.com/influxdata/chronograf/pull/2832. It might be an issue with high cardinality on hosts that returns a large response.

**Comment by sgreszcz** [comment]
Interesting that I don't have any latency responses with the dashboards I'm building in Grafana.  It might be the way that the default Telegraf system/docker/elastic performance monitor queries are built in Cronograf.

**Comment by russorat** [comment]
will be addressed as part of #682 and #2962
