### ISSUE TITLE
Select dropdown selections should not be cleared

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2980]
![kapture 2018-03-14 at 10 15 10](https://user-images.githubusercontent.com/4805997/37419024-c7d98f2a-2770-11e8-9d09-5c710330bc5a.gif)

**Comment by jaredscheib** [comment]
Is this only desired in the Permissions multiselectdropdown? or all multiselectdropdowns in the Users and Roles tabs? it's also not clear from the image or the story as to where this multiselectdropdown is, in the gif.
