### ISSUE TITLE
Rapid Fire Notifications

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2987]
**Problem:**

Some notifications fire extremely fast and spam the notifications center

**Proposed solution:**

If notification fires and it is the same as the previous notification, group them together with some text below the message `Fired 4 times`. This will help expose parts of the code that are executing rapidly without spamming the notifications center

**Comment by russorat** [comment]
![kapture 2018-03-14 at 16 36 58-small](https://user-images.githubusercontent.com/4805997/37436620-f757a842-27a5-11e8-815f-fc61756bf6a8.gif)

**Comment by russorat** [comment]
🌮
