### ISSUE TITLE
Query fails if host tag contains char \

### ISSUE THREAD

**Issue by iatalay** [influxdata/chronograf#3000]
Can you please look at the following issue?

[#3881](https://github.com/influxdata/telegraf/issues/3881)

[data-explorer](https://pasteboard.co/HbOvbpb.png)
[host-list](https://pasteboard.co/HbOtVwo.png)

**Comment by russorat** [comment]
@iatalay thanks for the report. we will tackle this as part of #682

**Comment by russorat** [comment]
might be related to https://github.com/influxdata/chronograf/issues/2994

**Comment by Anderen2** [comment]
Same issue occurs when a metric with host set to "=" is inserted (don't ask), all links in the apps column is then broken, even for the hosts with sane hostnames.  

Looking at the browser console I see that it complains about "val.apps is undefined". 

Removing all series where the host-tag was set to "=" fixes the issue.
