### ISSUE TITLE
Host list empty if custom db name is used

### ISSUE THREAD

**Issue by pierrick-openIT** [influxdata/chronograf#3008]
Hi everyone,
when i use a custom db name other than "telegraf", my host list name is empty.

Telegraf : 1.5.3
InfluxDB: 1.4.2

Regards

**Comment by russorat** [comment]
@pierrick-openIT thanks for the issue. we will tackle this as part of the host list redesign in #682

**Comment by pierrick-openIT** [comment]
Hi , you are welcome. There is a warkound before the redesign of the host list ?

**Comment by jaredscheib** [comment]
Hi @pierrick-openIT, could you open your Network tab in your Developer Console and tell us some more information about the two `/proxy` requests (both `POST`s to `http://localhost:8888/chronograf/v1/sources/{sourceID}/proxy`), which happen after the `GET` to `http://localhost:8888/chronograf/v1/env`:
1. what is the value of `db` on each of these request payloads to proxy? in other words, does this value match your custom telegraf db name?
1. what is the value of `query` on each of these request payloads to proxy?
1. what is the response Status Code to these requests to proxy?
1. what is the response body to these requests to proxy?

Thanks!

**Comment by nhaugo** [comment]
The telegraf database does not support non autogen rps

**Comment by russorat** [comment]
- [ ] add the ability for a user to define a retention policy in the add connection UI
- [ ] leverage that rp for any telegraf related queries

**Comment by jaredscheib** [comment]
remaining to do:
- [ ] write server/influx_test.go for receiving custom rp and relaying that in a query to influxdb
- [ ] pass that test, where chronograf server includes custom rp in proxied query to influxdb
- [ ] include rp value on source in host page proxy query

**Comment by pierrick-openIT** [comment]
Hi, bug still present ? I'm using now 
influxDB 1.7.2
chronograf 1.7.5
telegraf 1.9.1

**Comment by jchalos** [comment]
Problem still exists, is there a documented workaround for this?  It is closed as a retention policy issue, but it appears to be with the default database name.

chronograf 1.7.12
telegraf 1.11.4
influx 1.7.7
kapacitor 1.5.3

**Comment by VVilaplana** [comment]
Still not working (influxdb 1.7.9, chronograf 1.7.17, telegraf 1.13.2, kapacitor 1.5.4)
