### ISSUE TITLE
Replace old confirmation pattern with new one

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3011]
Old:
![screen shot 2018-03-19 at 11 37 22 am](https://user-images.githubusercontent.com/2433762/37615223-fbebcb14-2b69-11e8-89a9-f727b14824d4.png)

New:
![screen shot 2018-03-19 at 11 40 01 am](https://user-images.githubusercontent.com/2433762/37615339-46b29132-2b6a-11e8-9a21-29a3b6ed481e.png)

**Comment by alexpaxton** [comment]
I should add that this is intended to cover the entire UI - time to standardize our smattering of patterns

**Comment by russorat** [comment]
the hover text disappears when if you wait too long. if you time it right, it's annoying.

![kapture 2018-04-06 at 15 11 24](https://user-images.githubusercontent.com/4805997/38446430-dea7ad4c-39ac-11e8-928c-3b5bc4062f82.gif)

**Comment by alexpaxton** [comment]
I believe this got taken care of via https://github.com/influxdata/chronograf/pull/3126

**Comment by russorat** [comment]
@alexpaxton the issue still exists

**Comment by alexpaxton** [comment]
I'm taking a look -- I see it happening on the `Current Org` page as well as the `All Orgs` page. Looks like the table is re-rendering quite often and causes the confirm button to reset. Tentatively I think the solution is to limit the re-rendering of the table

**Comment by alexpaxton** [comment]
- [x] fix flickering confirmation in Current Org table
- [ ] fix flickering confirmation in All Orgs table

**Comment by russorat** [comment]
great!
