### ISSUE TITLE
spike How do we want to create ids for pre canned dashboards

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3013]
When we move layouts to be actual dashboards, we need to figure out how to create dashboard ids for them.

**Comment by jaredscheib** [comment]
May be related to https://github.com/influxdata/chronograf/issues/2660

**Comment by alexpaxton** [comment]
I like the idea of using names as ids so you have something like:
```
/sources/1/dashboards/premade-telegraf
```

Then if you clone that dashboard it could retain the original in its id:
```
/sources/1/dashboards/premade-telegraf-copy-2
```
Something like this makes the URL a little more meaningful

**Comment by desa** [comment]
@russorat More over, which organizations own them?

**Comment by russorat** [comment]
@desa just so i have all the context, could you elaborate on what you think the flow will be here? the flow that i was envisioning would be a user is logged in when these dashboards are being created. if so, they would be the org that the user is logged in with.

**Comment by desa** [comment]
Right now layouts (pre-canned dashboards) are global to the the application and the organization you're signed into determines which source we use. But changing these to be full-fledged dashboards is a bit different, since they'll end up needing to be owned by a particular organization.

**Comment by jaredscheib** [comment]
I believe the current idea is to convert them into JSON objects that live in the client, so they're templates that can be turned into the same dashboard that would be owned by the current organization upon being generated in such a way. Is that correct, @russorat?

**Comment by russorat** [comment]
this isn't an issue anymore since the user will choose the dashboards to create and they will have ids generated when they are created
