### ISSUE TITLE
Add tslint to the project

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3015]
We need to add tslint to the project to prevent `debugger`, `console`, etc. statements from making their way into the codebase and especially into production, now that we've added TypeScript to the project.

I added a `console.log` within a `.tsx` file, and webpack didn't say there were any issues. I actually also committed them and only happened to realize they were still there, but I could have just as easily merged that code in.

**Comment by 121watts** [comment]
we will also probably need `tslint-config-prettier` so prettier handles the code formatting and tslint handles the linting.
