### ISSUE TITLE
tickscript editor shows task already exists error the second time you save a new script

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3019]
to reproduce:
1. create a new tick script and set the name and db
2. paste the following into the script (could be any tickscript)
```
stream
    // Select just the cpu measurement from our example database.
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_user" < 50)
        // Whenever we get an alert write it to a file.
     .log('/tmp/alerts.log')
```
3. click save
4. on the same window, make a change to the script and click save again, notice the error

![kapture 2018-03-20 at 11 40 38](https://user-images.githubusercontent.com/4805997/37675921-bd775752-2c33-11e8-985d-952b6086592c.gif)

**Comment by alexpaxton** [comment]
This bug makes me nuts

**Comment by russorat** [comment]
great!

**Comment by russorat** [comment]
- [ ] this shouldn't save if the first time you save is an error
![kapture 2018-04-09 at 16 42 08](https://user-images.githubusercontent.com/4805997/38528601-4ce90f2a-3c15-11e8-9602-76cd7aea08b4.gif)

**Comment by russorat** [comment]
dope!
