### ISSUE TITLE
Notifications [Regression] - Entering Invalid Values for Retention Policy Duration in InfluxDB Admin fails to trigger notification 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3043]
$ chronograf --version
2018/03/23 16:30:16 Chronograf 1.2.0~n201803220833 (git: 599a93fd9b4ae87cad4e927961912002b458d9c9)

1) Open the InfluxDB Admin Page
2) Choose a database
3) Click Add Retention Policy
4) Add a Name
5) In the duration field add an invalid value like "invalid_value" 
6) Click the green check icon 

The new retention policy simply disappears.  There is no notification as to what went wrong.  

**Expected Behavior**

Previously there was a notification "Failed to create retention policy."   This should be restored or even better a message such as "Invalid Duration Value" might appear.

**Comment by russorat** [comment]
@alexpaxton is this expected as part of the notifications refactor?

**Comment by alexpaxton** [comment]
I just checked out the code for this feature -- doesn't look like there's a catch for that error. If the duration is invalid the server returns a 400 error, but for some reason it isn't displayed in the UI. Doesn't look like much work to add it in
