### ISSUE TITLE
Host list "bounces" when scrolled to the bottom - Chrome Stable

### ISSUE THREAD

**Issue by brennentsmith** [influxdata/chronograf#3050]
It appears that there is a bug in the scrolling code of the Host List. When scrolled to the bottom, the UI list "bounces" uncontrollably until the list is scrolled up. It appears to be some JS logic tweaking the heights of the objects.  

Chrome: 65.0.3325.162
MacOS: 10.13.13
Chronograf Version: 1.4.2-3
From Deb Package

Video of the issue: https://ookla.d.pr/nIoZDG

**Comment by russorat** [comment]
@brennentsmith thanks for the report. we are going to redesign that page in #682 and will tackle it there.
