### ISSUE TITLE
Host List "skips" when scrolled quickly in Firefox

### ISSUE THREAD

**Issue by brennentsmith** [influxdata/chronograf#3051]
In Firefox, if the host list is scrolled quickly, it appears to skip past a boundary and create a large div at the bottom, rather than bounding the list at the bottom. However, if it is scrolled slowly, the host list works as expected.

Firefox: 59.0.1 (64-bit)
MacOS: 10.13.13
Chronograf Version: 1.4.2-3
From Deb Package

Video of issue: https://ookla.d.pr/fgqwKV

**Comment by russorat** [comment]
@brennentsmith thanks for the report. we are going to redesign that page in #682 and will tackle it there.
