### ISSUE TITLE
how to build chronograf from source without downloading from the network

### ISSUE THREAD

**Issue by williamh** [influxdata/chronograf#3056]
Hello,

I am a packager for Gentoo linux. My employer wants to use Chronograf, so I am working on packaging it and making it available to the Gentoo community.

Can you please tell me whether there is a way I can build chronograf from source without the build process fetching anything from the internet?

I know the vendor directory does this for Go by storing all of the dependencies there, but I'm not at all familiar with nodejs, so I have no idea how that portion works. It looks like yarn is attempting to download things from the net. If so, is there any way around that similar to what the vendor directory does for Go?

Your help would be greatly appreciated.

**Comment by lukevmorris** [comment]
Hi @williamh, that's great to hear!

JS package managers like `yarn` and `npm` install dependencies to `node_modules/` (found under the `ui/` directory in our project). This is analogous to the `vendor/` directory for Go dependencies. The only difference (as I understand it) is that it's standard in Go projects to check in dependencies, and standard in JS projects to gitignore `node_modules/`. Is there a way to set up a pre-build step that runs `yarn` to fetch those dependencies and effectively vendors them for the start of the build process?

By the way, our Marketing team would love to send you some InfluxData swag as a thank you for your efforts. If you're interested, send me a quick email (found in my github profile), and we can sort that out.

**Comment by williamh** [comment]
Hi @Lukevmorris, for the moment, it looks like the best way for me to do this is going to be to manually populate the ui/node_modules directory, tar that up and store it on our infrastructure for each chronograf release. The issue is we don't currently allow downloads in the unpack or build phase of our packages.

So, I need to know if there is a make target which will populate the dependencies?

Thanks,

William

**Comment by lukevmorris** [comment]
@williamh Yep -- we have:

`make .jsdep` runs `yarn` and populates `ui/node_modules/`
`make .godep` runs `go get` and populates `vendor/`
`make dep` runs both `.jsdep` and `.godep`

Then given a state where all dependencies are fetched, you can run `make build` to put it all together.

**Comment by lukevmorris** [comment]
@williamh I'll try to get you an answer to that question, but in the meantime I wanted to direct your attention to some prior art in case it's helpful. It looks like there is an [ebuild for Grafana](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-apps/grafana-bin/grafana-bin-5.0.3.ebuild) that solves for a similar problem. I think it's just fetching the tarball of a release (with JS dependencies included), and you could probably do the same with ours: https://dl.influxdata.com/chronograf/releases/chronograf-1.4.3.0_linux_amd64.tar.gz. We list all our release builds here in case you need something different: `https://portal.influxdata.com/downloads`

**Comment by lukevmorris** [comment]
Ok, I think this is what I was imagining:

```
git clone git@github.com:influxdata/chronograf.git
cd chronograf
make dep
tar czf chronograf-1.4.3-js.tar.gz ui/node_modules/
```

Then if you host `chronograf-1.4.3-js.tar.gz`, you can consume it in the build process as follows:

```
// fetch chronograf source
// cd into chronograf project
// fetch chronograf-1.4.3-js.tar.gz
make build
```

**Comment by lukevmorris** [comment]
Another approach might be to reference the flat list of dependencies in `ui/yarn.lock`. Each line in that file is a direct or transient dependency, and includes a line like:
```
resolved "https://registry.yarnpkg.com/lodash-es/-/lodash-es-4.17.5.tgz#9fc6e737b1c4d151d8f9cae2247305d552ce748f"
```

In theory you could grab a list of all JS dependencies with `grep resolved ui/yarn.lock` and then iterate+curl to populate `ui/node_modules` yourself. Once those are in place, you should be able to run `make build`.

**Comment by williamh** [comment]
I noticed something else while looking at this.

It looks like the js dependencies are baked into the *_gen.go files. Is this correct? If so, I may be able to create the *_gen.go files running "make build" manually, then save them to a local archive for the distro, and when someone wants to install chronograf, drop them into place and run "go build" manually to build the binaries. What do you think?

**Comment by russorat** [comment]
i'm going to resolve this for now. if you have any other questions, feel free to reopen.
