### ISSUE TITLE
Template variables only allows choosing TAG VALUES from single measurement

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3062]
It would be good if all `TAG VALUES` for a given `TAG KEY` could be used as template variables, regardless of their measurement. This could be achieved by allowing the `FROM` in the template variable chooser for `TAG VALUES` to be optional, or to have a special value that means all measurements are queried. The associated query would then be:

```
SHOW TAG VALUES WITH KEY =  "foo"
```

**Comment by russorat** [comment]
this can now be accomplished using the custom meta query in #3637
