### ISSUE TITLE
As a user I would like to have an optional grid layout in a dashboard

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3063]
I'm using Chronograf for creating a [RED](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/) style dashboard.

With RED you monitor three things for each metric: the rate, error rate and duration distribution. Usually you visualise them side by side, so naturally you end up with a 3 x N grid for `N` metrics.

However, in reality not all metrics have useful ways of capturing the duration (D) dimension, or in some cases even the error (E) dimension.

Because the three columns are important to easily understand what part of the metric you're looking at, it's nice that when you say have a `rate` for something and a `duration`, but not an `error`, that you can place the `rate` and `duration` cells in columns 1 and 3. With Chronograf this is currently not possible.

Further, if you have a `rate` and `error`, but not a duration, then with Chronograf, the `duration` of the next metric (row in the dashboard) will pull itself up on column 3 so you will end up with different metrics in the same row.

The way I have gotten around this issue is by using "padding cells" to provide spaces, and keep everything where it should be.

What I really want though are essentially invisible spaces that cells won't move into. I think the generic implementation of this is a grid system where the user places cells in discrete locations, and cells do not attempt to move themselves to reduce gaps.

**Comment by alexpaxton** [comment]
Seems like this should be pretty easy to change -- the grid layout library has "compaction" options for reducing gaps, which can be disabled
