### ISSUE TITLE
Query and Title text isn't persisted unless text box "submitted"

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3065]
I've noticed that unless you explicitly "submit" the input form that is used for a cell's title or a cell's query, that it won't be persisted.

This seems kind of obvious (that you have to press return when you make changes to the free text field), but because there is a nice green ✅ box in the query editor one often ends up clicking that after editing the query. Or, more rarely, after editing the cell's title.

Any changes that were made will not be persisted.

To reproduce (on Chrome, at least) edit a cell and make a change to the query. Then click the green checkmark to say you're happy. The changes to the query will not be persisted.

**Comment by russorat** [comment]
- [ ] leave the ceo title always editable

**Comment by russorat** [comment]
Woot!
