### ISSUE TITLE
As a user I would like new cells to be as close in size to existing cells as possible

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3066]
In some ways, this is more noticeable when you're thinking about your dashboard in a grid system (I talked about that a bit in #3063.

When you add a new cell it's a certain default size. If though you want all your cells to be a certain width and height that differs from this default size, then you find yourself resizing each and every cell you add to the dashboard.

As a user I would like it if Chronograf was a bit smarter about the size of cells when they're added to the dashboard. For example, the median width and height of a cell in the dashboard could be tracked, and new cells would be assigned this median width and height. That way, it's more likely that when you add a new cell to the dashboard it's already the correct size.

The median would be preferable to the mean as it would guarantee that the width and height of the cell would be the same as some of the existing cells, and it would prevent a single incorrectly sized cell in the dashboard affecting the width and height of any newly created cells.

**Comment by russorat** [comment]
i run into this a lot as well. and with some of the features enabling larger dashboards, something like this makes a lot of sense.

**Comment by russorat** [comment]
Looks good!
