### ISSUE TITLE
As a user I would not like my new cell to be near my mouse cursor 

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3067]
I have a large dashboard with around 30 or so cells. I'm currently building this out. Chronograf's header (with the buttons to add cells and template variable etc) floats on the page and follows me down the dashboard. However, when you add a new cell, the cell is inserted right at the top of the dashboard. 

When you're building out a large dashboard this means a bunch of scrolling up to the top of the page to find the new cell, and then a bunch of dragging of said cell all the way down to where you were when you actually clicked the `+ Add Cell` button.

It would be cool if the cell was either (a) inserted near where the mouse cursor is when you click the `+ Add Cell` button (though this might disrupt existing cells); or (2) inserted at the _bottom_ of the dashboard; or (3) inserted at the margin of the page closest to the current scroll position, either the top or bottom depending on if you're more than halfway down the page. Further, if your dashboard doesn't extend beyond the fold then cells are just added to the top of the dashboard.

I think (2) is more preferable since you build out dashboard from top to bottom, but there could be an issue with cells being added "below the fold" I guess? (3) would probably satisfy my need and when you're starting a dashboard, cells would still get added to the top of the page as they currently do.

**Comment by russorat** [comment]
fixed in 1.4.4
