### ISSUE TITLE
adding time(1ms) in the CEO breaks everything

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3070]
discovered by @ebb-tide

**Comment by ebb-tide** [comment]
![screen shot 2018-03-27 at 11 45 08](https://user-images.githubusercontent.com/10937678/37988393-a9b7bf2c-31b5-11e8-8e52-0a351cf9f9cd.png)

**Comment by bthesorceror** [comment]
Changes to how we poll seem to have fixed this issue, cannot reproduce it in master anymore.

**Comment by russorat** [comment]
it still makes things super slow, but doesn't crash everything which is good.
