### ISSUE TITLE
Visualization of trace data

### ISSUE THREAD

**Issue by fntlnz** [influxdata/chronograf#3092]
As a user, I would like to be able to visualize traces like http request flows, profiling data, application flows, directly into Chronograf.

I imagine this to be something like the Chrome's integrated tracer - `chrome://tracing/`. 

![image](https://user-images.githubusercontent.com/3083633/38095201-218765aa-3370-11e8-97f6-25d2ed3bfd45.png)

This would make really easy to correlate data related to the same context but propagated in different moments.

**Comment by leodido** [comment]
This is how the pprof tool renders flamegraphs ...

![screenshot_20180330_131257](https://user-images.githubusercontent.com/120051/38136073-4ca3f31e-341c-11e8-8cd6-28802da152fd.png)

**Comment by russorat** [comment]
this would be cool. do you have any ideas around how the data might be formatted in Influx? I assume we would look at the data coming from telegraf's trace plugins.
