### ISSUE TITLE
build error on freebsd.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/chronograf#3105]
Tried to rebuild it today according to the DIY instructions and got this:

```
go build -o chronograf -ldflags "-s -X main.version=1.4.3.0-213-g0204873d5 -X main.commit=0204873d" ./cmd/chronograf/main.go
# github.com/influxdata/chronograf/vendor/github.com/influxdata/ifql/parser
vendor/github.com/influxdata/ifql/parser/types.go:307:11: undefined: strings.Builder
gmake: *** [Makefile:25: chronograf] Error 2
```

**Comment by russorat** [comment]
thanks for the report. we are looking into this.

**Comment by ebb-tide** [comment]
hi @bunnyevans. Please try updating to go version 1.10. We have changed our [CONTRIBUTING.md](https://github.com/influxdata/chronograf/blob/master/CONTRIBUTING.md) file to reflect this change. Let us know how it works out for you!

**Comment by bunnyevans** [comment]
That works. Had to update mumble*bsd a bit first.
