### ISSUE TITLE
User permissions rendered out of layout bounds in Chrome 65

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3114]
Reviewing and updating selenium tests, I came across long permission sets overflowing the layout in the InfluxDBAdmin User tab.  
See Screenshot 
![permissionslistingtoowide01](https://user-images.githubusercontent.com/25881301/38256242-1b83ec86-375e-11e8-8ef2-9a51cf167e8f.png)

Currently using 

$ chronograf --version
2018/04/03 16:40:55 Chronograf 1.2.0~n201804020832 (git: 0204873d510e52debfff51fb1a64b27a2c4414fe)

**Comment by karel-rehor** [comment]
I see a similar issue with users in the Roles tab. 

See screenshot

![usersoverflowsroleslayout01](https://user-images.githubusercontent.com/25881301/38259113-802189e0-3764-11e8-941b-5d9a67531ce3.png)

**Comment by alexpaxton** [comment]
@russorat I think this could be solved by using the tag list component (featured in chrono admin all users table) instead of the current multi-select dropdown. Would also make the two admin pages more consistent with each other

**Comment by 121watts** [comment]
@alexpaxton @karel-rehor This should be taken care of in #3112

**Comment by russorat** [comment]
yep i don't see the overflow anymore. thanks!
