### ISSUE TITLE
Custom date picker reset time after a few seconds

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3119]
![kapture 2018-04-03 at 16 34 06](https://user-images.githubusercontent.com/4805997/38280968-218ae450-375d-11e8-8ae7-87c498be738a.gif)

**Comment by bthesorceror** [comment]
I think this was fixed by a PR that @121watts pushed yesterday. #3118

**Comment by russorat** [comment]
yep, not seeing this anymore!
