### ISSUE TITLE
Switching from a line graph to either single stat or gauge breaks the UI

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3121]
<img width="252" alt="screen shot 2018-04-03 at 8 49 59 pm" src="https://user-images.githubusercontent.com/2433762/38289031-ff4ca4ec-3788-11e8-835f-ca9e647b96ff.png">

Looks like the gauge options is trying (and failing) to make use of line graph colors

**Comment by russorat** [comment]
awesome!
