### ISSUE TITLE
Add precision to single stat indicators (single stat, single stat line, gauge)

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#3124]
![screenshot 2018-04-04 09 04 09](https://user-images.githubusercontent.com/1477539/38319669-410469b6-37e7-11e8-8f3b-0f5891622f5b.png)

**Comment by russorat** [comment]
could we also fix #930 as part of this?

**Comment by russorat** [comment]
- [ ] add the same precision control as seen in the table graph to the gauge graph
- [ ] add the same precision control as seen in the table graph to the single stat graph
- [ ] add the same precision control as seen in the table graph to the single stat + line graph

**Comment by russorat** [comment]
can we get these to show on the same line? 

![image](https://user-images.githubusercontent.com/4805997/42587497-bb9f500a-84ef-11e8-8e77-23210cb278fb.png)

**Comment by russorat** [comment]
i'm using the following query as a way to test this feature. The expected display should be `0.123456789` when the decimal places are set to unlimited. When it is set to 4, the value `0.1234` should be displayed.

`SELECT mean("usage_user")-mean("usage_user")+0.123456789 AS "mean_usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: GROUP BY time(:interval:) FILL(0)`

![image](https://user-images.githubusercontent.com/4805997/42593595-c534bbb6-8501-11e8-981c-b160d88d9df3.png)

**Comment by russorat** [comment]
also, seeing this `toFixed` error

![image](https://user-images.githubusercontent.com/4805997/42593731-1d8560c2-8502-11e8-8fbf-b54ca5d92d42.png)
