### ISSUE TITLE
Query getting data for "Hosts" dashboard causes memory consumption problem

### ISSUE THREAD

**Issue by rzakbrodalko** [influxdata/chronograf#3135]
Dear Chronograf Developers,

I've an InfluxDB installation with Telegraf agent configured to use PID as a tag for procstat measurements.  I have connected a few servers, therefore there is more than 500000 series in the database index.

The database itself works well so far and I'm really happy with it (that's the good part of the news). Recently, I've installed Chronograf in order to use it as configuration and management console. After installation one of the default components: "Hosts" dashboard just pushed my server to the limit (memory limit in fact) using the following query (many times):
```
SHOW SERIES FROM /^apache$|^consul_health_checks$|^consul_consul_fsm_register$|^consul_memberlist_msg_alive$|^consul_raft_state_candidate$|^consul_consul_http_GET_v1_health_state__$|^consul_raft_state_leader$|^consul_serf_events$|^cpu$|^disk$|^diskio$|^docker$|^docker_container_blkio$|^docker_container_net$|^elasticsearch_indices$|^haproxy$|^influxdb_database$|^influxdb_httpd$|^influxdb_queryExecutor$|^influxdb_write$|^kubernetes_node$|^kubernetes_pod_container$|^kubernetes_pod_network$|^kubernetes_system_container$|^system$|^mem$|^memcached$|^mesos$|^mongodb$|^mysql$|^net$|^netstat$|^nginx$|^nsq_channel$|^nsq_server$|^nsq_topic$|^phpfpm$|^ping$|^postgresql$|^processes$|^procstat$|^rabbitmq_node$|^redis$|^riak$|^varnish$|^win_cpu$|^win_mem$|^win_net$|^win_system$|^win_websvc$/ telegraf
```
I think that this specific feature should be reengineered for example to use query like this by default:

`SHOW TAG VALUES WITH KEY="host";`

Which is much faster and "resource friendly". Or maybe it should be configurable in order to allow user to specify the exact query the best suitable for his configuration.

As for now I'm not able to use Chronograf on my infrastructure.

Thank you in advance for any support.

**Comment by russorat** [comment]
@rzakbrodalko thanks for the issue. we agree this needs to change. we are working on revamping that page in starting in the coming sprint and you can track the progress in #682 . Stay tuned!
