### ISSUE TITLE
Chronograf install and config with certificate and AAD

### ISSUE THREAD

**Issue by eaidland** [influxdata/chronograf#3152]
Hi!
I've followed these instructions for Ubuntu 16.04 LTS:

1. Download and install Chronograf
wget https://dl.influxdata.com/chronograf/releases/chronograf_1.4.0.0_amd64.deb
sudo dpkg -i chronograf_1.4.0.0_amd64.deb
2. Start Chronograf
sudo systemctl start chronograf
3. Connect to Chronograf
4. Works
5. Stopped Chornograf
sudo systemctl stop chronograf
6. sudo nano /etc/default/chronograf
7. Added:
HOST=0.0.0.0
PORT=8888
TLS_CERTIFICATE=/etc/ssl/certs/apache-selfsigned.crt
TLS_PRIVATE_KEY=/etc/ssl/private/apache-selfsigned.key
TOKEN_SECRET=<some_info>
LOG_LEVEL=info

PUBLIC_URL=http://IP_TO_CHRONOGRAF:8888/oauth/generic/callback
GENERIC_NAME=Azure AD
GENERIC_CLIENT_ID=<client_id>
GENERIC_CLIENT_SECRET=<client_secret>
GENERIC_SCOPES=openid email name
GENERIC_AUTH_URL=https://login.microsoftonline.com/<tenant>/oauth2/authorize
GENERIC_TOKEN_URL=https://login.microsoftonline.com/<tenant>/oauth2/token
GENERIC_API_URL=https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration
GENERIC_API_KEY=userPrincipalName
8. Started Chronograf
sudo systemctl start chronograf

Why isn't the settings implemented? The service doesn't run on https nor do I get the login from Azure Ad.

What have I missed in settings/startup?

Running this command starts the service with https
sudo TLS_CERTIFICATE=/etc/ssl/certs/apache-selfsigned.crt TLS_PRIVATE_KEY=/etc/ssl/private/apache-selfsigned.key systemctl start chronograf

Thanks!

**Comment by russorat** [comment]
@eaidland thanks for the issue. Could you take a look at this PR and the related issues? https://github.com/influxdata/chronograf/pull/2526 . in order to get this functionality, you would need to build off master. We expect this to go into a release this week.

**Comment by eaidland** [comment]
I'm no AD expert, but we use Azure Active Directory and register Apps with keys. When the users go to the Grafana page they're met with standard business Azure AD login.

**Set up oauth2 with Azure Active Directory**
Log in to portal.azure.com and click “Azure Active Directory” in the side menu, then click the “Properties” sub-menu item.

Copy the “Directory ID”, this is needed for setting URLs later

Click “App Registrations” and add a new application registration:

Name: Grafana
Application type: Web app / API
Sign-on URL: https://<grafana url>/login/generic_oauth
Click the name of the new application to open the application details page.

Note down the “Application ID”, this will be the OAuth client id.

Click “Settings”, then click “Keys” and add a new entry under Passwords

Key Description: Grafana
Duration: Never Expires
Click Save then copy the key value, this will be the OAuth client secret.



Grafana settings:
[auth.generic_oauth]
enabled = true
name = Azure AD
allow_sign_up = true
client_id = <client_id>
client_secret = <client_secret>
scopes = openid email name
auth_url = https://login.microsoftonline.com/<tenant>/oauth2/authorize
token_url = https://login.microsoftonline.com/<tenant>/oauth2/token
api_url =
team_ids =
allowed_organizations =
