### ISSUE TITLE
Ability to change queries depending on template variable

### ISSUE THREAD

**Issue by Lootvoet** [influxdata/chronograf#3153]
Use case: I currently have 2 (almost) identical dashboards, where one shows default data and the other one shows the same data, but cumulative. It would be useful to be able to change the query depending on the template variable.
Eg: when the template variable 'cumulative' is selected, show the data cumulative (only show query 2), otherwise only show query 1. This way it would be unnecessary to use two different dashboards to represent the same data.

**Comment by russorat** [comment]
@Lootvoet thanks for the issue. would something like https://github.com/influxdata/chronograf/issues/2441 solve this?

**Comment by Lootvoet** [comment]
@russorat Yes, this should solve my issue. Thanks.
