### ISSUE TITLE
TypeError on layouts dashboards

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3158]
![image](https://user-images.githubusercontent.com/4805997/38527798-8547679e-3c11-11e8-8357-4e481e650af3.png)

**Comment by jaredscheib** [comment]
@russorat Can you add repro steps? I haven't been able to repro. Loading from master, I am able to visit Hosts Page, a specific Host page, and a specific host tag, without any problems.

**Comment by russorat** [comment]
i was checking in 1.4.4.x branch. i will check master.

**Comment by russorat** [comment]
i'm able to repro in master. select the system app dashboard on the host list page:

![kapture 2018-04-10 at 13 37 03](https://user-images.githubusercontent.com/4805997/38582385-603f00e8-3cc4-11e8-8de8-45309d24f2ef.gif)

**Comment by russorat** [comment]
thanks!
