### ISSUE TITLE
Make vertical page tabs into generic component that ties into the router

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3163]
If you are on any tab other than the first and refresh the page, you have to navigate back to where you were. It is also impossible to link directly to a tabbed page with a specific tab in view.

Currently there are vertical tabs on the `InfluxDB Admin` and `Chronograf Admin` pages but the vertical tabs pattern will eventually extend to other pages such as `Configuration`, `Dashboards`, and potentially `Tasks` so we need a reusable solution.

Here's an example:
![vert-tabs--dbs](https://user-images.githubusercontent.com/2433762/38531057-f5f4f784-3c22-11e8-83f8-51a6c9ab29fc.png)
![vert-tabs--users](https://user-images.githubusercontent.com/2433762/38531058-f72af108-3c22-11e8-8e96-9372181daf22.png)
![vert-tabs--queries](https://user-images.githubusercontent.com/2433762/38531059-f83f5ed0-3c22-11e8-9e78-11b35a4e210f.png)

**Comment by jaredscheib** [comment]
@ebb-tide implemented something along these lines in the Kapacitor Endpoints Config area of the app, heads up. that functionality might be reusable or extensible to this case.

**Comment by russorat** [comment]
love it!
