### ISSUE TITLE
Name provided to TICKscript replaced by Identifier 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3166]
I'm pretty sure this must be reported somewhere, but I have been unable to find it in current open issues.

When saving a new TICKscript with a name, the TICKscript appears in the Manage Tasks page's TICKscripts table listed by its identifier in the "name" column and not by the "name" the user assigned to it. 

Further when opening the script again, the Identifier appears in place of the name.

![tickscriptname01](https://user-images.githubusercontent.com/25881301/38564695-f2072044-3cdf-11e8-818d-bc9e092af290.png)
![tickscriptname02](https://user-images.githubusercontent.com/25881301/38564697-f222344c-3cdf-11e8-9bf1-98f13094497d.png)
![tickscriptname03](https://user-images.githubusercontent.com/25881301/38564698-f23b9734-3cdf-11e8-8cda-c062be76e2a6.png)
![tickscriptname04](https://user-images.githubusercontent.com/25881301/38564699-f2548bea-3cdf-11e8-8aa4-71c90329adb3.png)
![tickscriptname05](https://user-images.githubusercontent.com/25881301/38564700-f26f3a1c-3cdf-11e8-8e3c-f25aca6d7c24.png)

I've just written an automated test for creating a TICKscript and the last assertion is that the script should be found in the Manage Tasks page by "name". 

```
$ chronograf --version
2018/04/11 10:26:28 Chronograf 1.2.0~n201804100832 (git: 7faec8b6be473720206f974dcb95df39aefe032b)
```

**Comment by russorat** [comment]
goot find. this is probably a side effect of https://github.com/influxdata/chronograf/issues/3019

**Comment by 121watts** [comment]
@russorat we are POSTing the arbitrary id to the backend.  But, it seems like the backend is overwriting the user assigned id if the Tickscript cannot be parsed into an 'AlertRule'.

**Comment by odarriba** [comment]
I'm seeing the same issue in 1.4.4.2 :( any news about this?

```root@metrics:~# chronograf -v
2018/05/10 15:09:06 Chronograf 1.4.4.2 (git: cc398c105f97f2b13aa5f38d1ff1d2c5cae2d5af)```

**Comment by russorat** [comment]
@odarriba i'm reopening this so we can find a better solution.
