### ISSUE TITLE
TICKscript with same body of existing script gets renamed to same name as existing script

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3167]
I would like to use the body of an existing script in the TICKscript editor as a basis on which I can make modifications for something slightly different.  This is an approach for a beginner, in which he can feel certain that the basis already works.  However... 

1. In the Manage Tasks page click the "Write TICKscript" button. 
2. Paste in copy of TICKscript to the TICKscript editor. 
3. Give the TICKscript a name. 
4. Select a database (e.g. telegraf.autogen)
5. Click Save - the TICKscript is saved apparently with the chosen name. 
6. Return to the Manage Tasks page. 

There are now two TICKscripts with the same name (e.g. cpu_alert) 

See screenshots 

![tickscriptsamebody01](https://user-images.githubusercontent.com/25881301/38566635-6ea5007c-3ce4-11e8-9ca9-fa3162ae5c5b.png)
![tickscriptsamebody02](https://user-images.githubusercontent.com/25881301/38566636-6ec0ac6e-3ce4-11e8-9049-5b2914a6fabb.png)
![tickscriptsamebody03](https://user-images.githubusercontent.com/25881301/38566638-6ed97168-3ce4-11e8-896b-e08f8f3ccc6d.png)
![tickscriptsamebody04](https://user-images.githubusercontent.com/25881301/38566639-6ef25ce6-3ce4-11e8-9bc2-9b1fd04ad8dc.png)

I would expect that even though the body of the script is the same, that the name would be different.  Especially in the use case, when using an existing script as a basis for deriving something slightly different. 

```
$ chronograf --version
2018/04/11 10:26:28 Chronograf 1.2.0~n201804100832 (git: 7faec8b6be473720206f974dcb95df39aefe032b)
```

**Comment by russorat** [comment]
related to https://github.com/influxdata/chronograf/issues/2836 and https://github.com/influxdata/chronograf/issues/2843
