### ISSUE TITLE
When editing TICKscript and saving more than once console returns error 'ID 1 not found'

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3174]
$ chronograf --version
2018/04/11 10:26:28 Chronograf 1.2.0~n201804100832 (git: 7faec8b6be473720206f974dcb95df39aefe032b)

When writing a TICKscript through the TICKscript editor in Manage Tasks...

1) I add a name in the name text box and a script fragment in the code editor then choose a database
2) I click save - The console reports an invalid task type - I see that the Name text box is now replaced with a label containing the chosen name 
3) I add a simple task to the script 
4) I click save again - The console now reports 'ID 1 not found'.

How to incrementally write and save a script if the name and ID are being confused? 

![tickeditorid1notfound01](https://user-images.githubusercontent.com/25881301/38612164-21ee600a-3d86-11e8-85c2-d11e648bab20.png)
![tickeditorid1notfound02](https://user-images.githubusercontent.com/25881301/38612165-220700ba-3d86-11e8-9557-78054686c7ba.png)
![tickeditorid1notfound03](https://user-images.githubusercontent.com/25881301/38612166-2221fd5c-3d86-11e8-9bbc-14a52b77f5bd.png)
![tickeditorid1notfound04](https://user-images.githubusercontent.com/25881301/38612167-223e3698-3d86-11e8-9c45-8f7a2dc18f66.png)

**Comment by russorat** [comment]
thanks @karel-rehor ! this is addressed here: https://github.com/influxdata/chronograf/issues/3019#issuecomment-379927377
