### ISSUE TITLE
GroupBy(:interval:) not showing auto in the ui

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3176]
![kapture 2018-04-11 at 9 41 02](https://user-images.githubusercontent.com/4805997/38630699-861db202-3d6c-11e8-819a-eaefed7f6d5b.gif)

**Comment by jaredscheib** [comment]
I'm not able to reproduce on current master: 
![group by repro](https://user-images.githubusercontent.com/6403018/39160594-f9bd6dd4-4720-11e8-962d-9bdc59a8eddf.gif)
