### ISSUE TITLE
DB user without permissions is able manage users including admin user

### ISSUE THREAD

**Issue by gshif** [influxdata/chronograf#3178]
1. Setup database cluster to use basic password authentication (for data nodes). This will require creation of admin user. Create an admin user by running the following command:
curl --fail -XPOST "http://<data node>:8086/query" --data-urlencode "q=CREATE USER test_admin WITH PASSWORD 'test_admin' WITH ALL PRIVILEGES"

2. In addition to admin user create a user with no privileges
curl --fail -XPOST "http://`pcl host data-0 -c litmus`:8086/query" --data-urlencode "q=CREATE USER no_admin WITH PASSWORD 'no_admin'"

3. Login to to one of the data nodes, run influx -username=no_admin -password=no_admin
try running any commands, such as create/drop db, create/drop user, etc. 'The user is not authorized' error message will be always displayed.

4. Using REST API (i used python's requests modules) or Chronograf's UI, create a data source with user name and password of a user with no permissions - no_admin user. Get to the Users view and delete an admin user/ or add/remove permissions from admin user, Add a role from a role screen. Add users to the created role, etc. User with no CreateUserRole permission should not be able to do the above actions. 

I used chronograf 1.4.3.0 and influxdb 1.5.2rc2

**Comment by russorat** [comment]
@gshif thanks for the issue. does the influxdb database behave correctly? we don't have any backdoors into influxdb, so if the user defined in the chronograf source doesn't have permissions to perform an action in the db, the calls should fail. do they?

**Comment by gshif** [comment]
@russorat, yes, the database behaves correctly (see step3 in my original post). 
 What makes it more interesting is that when I run an API call to get all the users for that data source, the user that does not have any permissions comes back with correct set of permissions, i.e. none. At the same time, the 'permissions' end point for a data source returns all of the permissions:
In the example below data source 9 is created with user 'no_admin' that has no permissions.
```
a=requests.get('http://35.166.94.84:8888/chronograf/v1/sources/9/users')
a.text
u'{"users":[{"links":{"self":"/chronograf/v1/sources/9/users/no_admin"},"name":"no_admin","permissions":[],"roles":[]}]}\n'
```
Here is the output of the permissions for the above data source:
```
a=requests.get('http://35.166.94.84:8888/chronograf/v1/sources/9/permissions')
a.text
u'{"permissions":[{"scope":"all","allowed":["NoPermissions","ViewAdmin","ViewChronograf","CreateDatabase","CreateUserAndRole","AddRemoveNode","DropDatabase","DropData","ReadData","WriteData","Rebalance","ManageShard","ManageContinuousQuery","ManageQuery","ManageSubscription","Monitor","CopyShard","KapacitorAPI","KapacitorConfigAPI"]},{"scope":"database","allowed":["NoPermissions","ViewAdmin","ViewChronograf","CreateDatabase","CreateUserAndRole","AddRemoveNode","DropDatabase","DropData","ReadData","WriteData","Rebalance","ManageShard","ManageContinuousQuery","ManageQuery","ManageSubscription","Monitor","CopyShard","KapacitorAPI","KapacitorConfigAPI"]}],"links":{"self":"/chronograf/v1/sources/9/permissions","source":"/chronograf/v1/sources/9"}}\n'
```
But at the same time the same user with no permissions cannot do other restricted for this user actions, such as create/drop database, which is correct.

Here is the excerpt from the DB Commands for a user with no permissions.
```
root@ip-10-0-131-20:/home/ubuntu# influx -username=no_admin -password=no_admin
Connected to http://localhost:8086 version 1.5.2rc2-c1.5.2rc2
InfluxDB shell version: 1.5.2rc2-c1.5.2rc2
> show users
**ERR: error authorizing query: no_admin not authorized to execute statement 'SHOW USERS'**
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> drop user test_admin
**ERR: error authorizing query: no_admin not authorized to execute statement 'DROP USER test_admin'**
```

**Comment by russorat** [comment]
ok. so this request is to ensure that those parts of the chronograf app respect the permissions of the user in the source. makes sense.
