### ISSUE TITLE
Support a configuration file

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/chronograf#318]

**Comment by fdhex** [comment]
What is the accepted way of configuration currently? Is it mandatory to go on the GUI and click on the config? I'd like to package a preconfigured chronograf with Kapacitor but the lack of settings is a bit of an issue.

**Comment by goller** [comment]
Hi @fdhex, thanks for writing in!  Yes, currently, options controlling behavior of the server are provided on the command line or through environment variable.

Options controlling InfluxDB and Kapacitor are set through the UI.  However, I think it would be a nice feature to a default influx and kapacitor through the CLI/env/file.  @jackzampolin asked for just that to support his TICKstack on Kubernetes package: https://github.com/jackzampolin/tick-kube

I've added this as issue #883

Ok, here is a not great workaround... you use the Chronograf REST API.  It's entirely documented in our swagger file here: https://github.com/influxdata/chronograf/blob/master/server/swagger.json

To get you started, here are some curl commands to create an influxdb datasource and a kapacitor.
### Adding an influxdb 
curl -X POST -H "Content-Type: application/json"  -d '{
  "name": "My Influx",
  "url": "http://localhost:8086"
}' "http://locahost:8888/chronograf/v1/sources"

**Comment by goller** [comment]
Whoops... hit return too fast... more edits incoming

**Comment by fdhex** [comment]
Sadly I don't have jq installed on my stemcell started BOSH vm's, but that's a good workaround, I can probably get around that with some grep's and make it work. We're already doing some rest calls to configure InfluxDB db's at startup anyway so that makes sense for now, thanks!

**Comment by goller** [comment]
Hey @fdhex, to be clear, we definitely want to support your use case.  @timraymond and I spent some time thinking about it yesterday and I think we'll have a good method for you soon.

**Comment by russorat** [comment]
you can now do this using `.src` files as described in https://github.com/influxdata/chronograf/issues/2659#issuecomment-354164604
