### ISSUE TITLE
Reboot/Shutdown system

### ISSUE THREAD

**Issue by AntonBarwald** [influxdata/chronograf#3187]
Hi,

Is it possible to do a shutdown/reboot graphically with a button in Chronograf ?

**Comment by russorat** [comment]
@AntonBarwald that isn't possible today. is there a specific use case you are trying to solve here? i'm curious why you'd like to shut down chronograf.

**Comment by AntonBarwald** [comment]
@russorat The case is that I was monitoring a Raspberry and it needed a reboot. Then it would be great to reboot it from the same UI. It would be even better if you could do server commands with Chronograf as the UI (start services, reboot/shutdown, and so on ...) 

Perhaps there is a better way to do this that I have not thought of?
