### ISSUE TITLE
As a user I would like the template variable bar to follow me

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#3188]
The template variable bar lives directly under the main dashboard header. It appears when you click on `Template Variables`.

When you have a dashboard with many cells, and you're exploring different dimensions of data via changes to template variables, it's annoying that the template variable bar is fixed to the top of the page and does not follow you down the page.

The result is that when focussing on cells "below the fold", one has to scroll back to the top of the dashboard page to change some variables, and then scroll back down to the cells of interest.

When the `Template Variables` bar is active I think it should be float along with the main dashboard header bar.

**Comment by russorat** [comment]
thanks! we will figure out how to make this experience better.

**Comment by alexpaxton** [comment]
This shouldn't be too hard to accomplish
