### ISSUE TITLE
Exit button in TICKscript editor sometimes <div> sometimes <button> 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3189]
I've had to wrap using the Exit button in the TICKscript page to catch a SerenityManagedException, which gets thrown when Serenity/Selenium can't find the Exit button using css = "button.btn-default".  Sometimes, apparently at the start of a test run the button is rendered using css =  "div.btn-default".  

Other than that it sometimes occurs that div is used for the Exit button at the start of a test run, I've not been able to determine any reason why the change from &lt;div&gt; to &lt;button&gt; or from &lt;button&gt; to &lt;div&gt;.  Manual checks show the css to be "button.btn-default" always but pausing automated test runs and checking the tagname and class can show "div.btn-default".  

Shouldn't the Exit button always use the same styling, i.e. tagname.class?  What might determine the change?

The workaround is to catch failure with one approach and then try the other.  And from the end user perspective this is not noticeable.  However it seems inconsistent and it would be nice to know what determines which tagname will occur.

**Comment by russorat** [comment]
@alexpaxton do you know the reasoning here?

**Comment by alexpaxton** [comment]
When changes are detected in the TICKscript the `Save` button lights up and the `Exit` button becomes `ConfirmButton` component rather than a plain HTML button. Looks like the `ConfirmButton` has a `<div>` as the outermost element so it can contain a button and a tooltip

**Comment by alexpaxton** [comment]
@karel-rehor I can add a specific CSS class to the exit button so it can be more reliably detected in both cases
