### ISSUE TITLE
When writing then saving batch style TICK scripts, all attempted saves - including invalid scripts - persist on backend 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3195]
```
$ chronograf --version
2018/04/13 14:38:05 Chronograf 1.2.0~n201804130832 (git: 69d00c8784bb087b1272123c7a7ecb6b232063b4)
```
In the TICKscript editor 

1) Click the 'batch' button. 
2) Choose the telegraf.autogen database 
3) Enter some invalid batch TICKscript 
4) Click save - the console reports the error
5) Repeat steps 3 and 4 a few times
6) Finally save a valid script
7) Return to the Manage Tasks page 

There are now several 'batch' scripts listed.  It seems every save attempt, including of invalid versions, persist a TICKscript on the Kapacitor backend.

Expectation: 

Only 1 version of the script should be saved, and it should be the final (valid) one on exit. 

Or

The Save button after the initial save should be "update" and the

Screenshots: 
![scriptssavedonerror01](https://user-images.githubusercontent.com/25881301/38735417-0eacb56a-3f29-11e8-8047-3917b82b18f5.png)
![scriptssavedonerror02](https://user-images.githubusercontent.com/25881301/38735418-0ec82b7e-3f29-11e8-8b29-97aaaa38f4cf.png)
![scriptssavedonerror04](https://user-images.githubusercontent.com/25881301/38735420-0ee3cee2-3f29-11e8-96bd-d3099e977a88.png)
![scriptssavedonerror05](https://user-images.githubusercontent.com/25881301/38735421-0f0219c4-3f29-11e8-9ca3-b8f7e5c129a6.png)
![scriptssavedonerror06](https://user-images.githubusercontent.com/25881301/38735422-0f1fdbda-3f29-11e8-99b9-6ebd48e208d5.png)

**Comment by russorat** [comment]
@karel-rehor why are you using such an old version of chronograf? Chronograf 1.2.0? i can't reproduce on the latest build

**Comment by karel-rehor** [comment]
This is pulled from the **Nightly Build** 

https://dl.influxdata.com/chronograf/nightlies/chronograf_nightly_amd64.deb

In the ID string is the token n201804130832 - which I understand is the build from 2018-04-13 08:32.  Github commit 69d00c8784bb087b1272123c7a7ecb6b232063b4 by Brandon Farmer on 2018-04-13 at 02:23 according to my local gitk.  

Most likely this issue is fixed by a more recent commit.  I'll check it shortly. 

I've asked previously (I think in an e-mail to Nathan Haugo) why the nightly build --version command always returns Chronograf 1.2.0 but with a recent time stamp, but got no response.

**Comment by karel-rehor** [comment]
I've managed to recreate this in the latest nightly build  2018-04-15 08:32
```
$ chronograf --version
2018/04/16 10:46:51 Chronograf 1.2.0~n201804150832 (git: ea2cff99bc9c3d6a2ac0713948f9870a9d3c1484)
```
![tsbatchsave01](https://user-images.githubusercontent.com/25881301/38799132-d777d3a8-4163-11e8-9227-ca772a4a6b12.png)

This was after 4 attempts to save an invalid script, however only two scripts were saved.  The difference seems to be in the change of the following block. 

```
var data = batch
    |query('''
        SELECT mean(usage_idle)
        FROM "db"."rp"."measurement"
    ''')
        .period(5m)
        .every(7m)
        .groupBy(time(1m), measurement)
    |eval(lambda: "usage_idle")
        .as('value')
```
Which returned an error message

```
batch query is not allowed to request data from "db"."rp"
```

Despite this error message it appears the script was saved as "ef68f7e1-0dbe-43dd-b670-61ea87307435"

Changing this to the following:
```
var data = batch
    |query('''
        SELECT mean(usage_idle)
        FROM "telegraf"."autogen"."measurement"
    ''')
        .period(5m)
        .every(7m)
        .groupBy(time(1m), measurement)
    |eval(lambda: "usage_idle")
        .as('value')
```
Resulted in a valid TICKscript being saved.  This time as "f6bc4df7-6c12-45bb-a209-fe61d619247a".

Note this test is against an Influx Enterprise deployment as described here: 

https://github.com/influxdata/bonitoo-selenium#starting-enterprise-cluster

**Comment by russorat** [comment]
related: https://github.com/influxdata/chronograf/issues/1998

**Comment by russorat** [comment]
i don't see this in latest master. if this is still happening, please reopen.
