### ISSUE TITLE
'NoPermissions' permission is deprecated, but still shows up under available cluster permissions

### ISSUE THREAD

**Issue by gshif** [influxdata/chronograf#3201]
The documentation for chronograf 1.3 mentions 'NoPermissions' permission is deprecated, but still shows up under available permissions in chronograf 1.4.3. Should it be removed from the list of available permissions (at least I did not find docs for 1.4.3 mentioning it)?

**Comment by russorat** [comment]
We should remove this from the list.

**Comment by russorat** [comment]
i still see lots of mentions of NoPermissions in the code so keeping this for now
