### ISSUE TITLE
XML Parsing Error: no root element

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3207]
From chronograf 1.4.4.0:

![image](https://user-images.githubusercontent.com/1922921/38828684-641ab2a4-417c-11e8-8c8e-304b0327d5e7.png)

**Comment by russorat** [comment]
@goller are you still seeing this error? how can we reproduce?

**Comment by goller** [comment]
Hey @russorat I was running it firefox

**Comment by tbstenbock** [comment]
Just sharing I had exact same error message from console window saying `no root element found` and in my case I didn't have any default retention policy (I had retention policy but not as default). In my use-case I disabled auto-create for both database and retention policy. Soon as I changed my retention policy to be default then the host started to show up in the hosts list in Chronograf. It is strange there is a correlation between these unrelated settings. The host should be there as long as measurements where done - regardless of retention policy is default or not.

**Comment by goller** [comment]
@tbstenbock thanks for writing in!  I figured out the problem I had so long ago and have patch #3888 up.  I'm not entirely sure though it fixes your problem like it fixes mine.  

Do you mind trying the PR out and seeing if it fixes your stuff?  If not, maybe it'll uncover a deeper issue.
