### ISSUE TITLE
FeatureRequest: add AutoRefresh Interval to AlertHistory

### ISSUE THREAD

**Issue by rdxmb** [influxdata/chronograf#3220]
AlertHistory is a very great overview to see if there are any problems within the infrastructure.
However, there is no automatic reload for that site (like it is in the Host List). It would be great to have that for a standalone-monitoring of the actual alerts.

**Comment by marcbihlmaier** [comment]
wontfix? It's a pity.

**Comment by rdxmb** [comment]
not stale, please
