### ISSUE TITLE
Threshold for single stat not triggering

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3223]
This for chronograf 1.4.4.0.

I have a metric where I want the background of the single stat to change if it is not a value.  

In this case I want any value but 1 to be red.  I configured 3 thresholds, 0, 1, 2 and it doesn't seem to be using the color associated with 1.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/1922921/38891548-5719a2a8-424a-11e8-9e82-9d982ed622bb.png">

**Comment by alexpaxton** [comment]
I believe the thresholds will assign a color only if it exceeds a threshold. So in this case, it won't turn blue until the value is `> 1` and a value of `1` exactly will fall in the first threshold's range of `0 - 1`

This issue makes me think the UI doesn't truly reflect how the thresholds are working and there is a better design out there

**Comment by bthesorceror** [comment]
@alexpaxton do you think the check should be >= rather than >?

**Comment by russorat** [comment]
@goller i think this is fixed in master. if you still see strange behavior, please reopen.

**Comment by goller** [comment]
Right on!
