### ISSUE TITLE
Unable to edit TICKscripts 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3236]
Chronograf Nightly Build **n201804180832**

```
$ chronograf --version
2018/04/18 13:04:05 Chronograf 1.2.0~n201804180832 (git: 364f8e884ddb57a6f2f59d853b8eb63600405526)
```
Browser **Chrome 65**.

With an enterprise installation using the following: 

https://github.com/influxdata/bonitoo-selenium#starting-enterprise-cluster

And with an InfluxDB connection (http://172.17.0.2:8086 "selenium:changeit") with a Kapcitor connection (http://172.17.0.2:9092).

1) Open the page Alerting > Manage tasks 
2) Click the button *Write TICKscript* - the TICKscript page editor loads 
3) Provide a name
4) Choose the database telegraf.autogen 
5) Click on the CodeMIrror textarea to give it focus 

The editor is not enabled.  I cannot type or copy-paste anything into it.  

*Expected* 

I expected that the above sequence of steps would enable the CodeMirror editor and that I could begin working with a TICKscript code. 

I see that in commit 1f4609c9e741378a918c7a5fa223b64fd42f7ba0 react-codemirror was replaced with react-codemirror2. 

Does anything beyond the above 5 steps need to be done to activate the Code Mirror 2 editor?

Up until this change it seems to have been working fine.

**Comment by russorat** [comment]
@karel-rehor if you are still seeing this, please feel free to reopen
