### ISSUE TITLE
Separate out `kapacitors` field from `source` in client

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3246]
Kapacitors and Sources are two different concepts that are conflated in the Chronograf client. They are separate in the server. This conflation makes it confusing to switch between client and server code, muddies the separation of the concepts, and even has bearing on our implementation of configuring the two connection types in the Chronograf client.

I think our client and server types should be consistent, and we should remove the `kapacitors` field from `source` in the client. It is added in the `LOAD_KAPACITORS` reducer.

This would also allow for the client to more easily disambiguate the configuration of the two in the UI.

And realistically, Kapacitor can be used without other sources besides InfluxDB, and it could even be useful to allow Chronograf to be used for Kapacitor without a connection to a source.

**Comment by alexpaxton** [comment]
I 100% endorse this message

**Comment by jaredscheib** [comment]
The conflation of the two concepts in the UI has probably also caused our users to conflate the concepts. Neither is dependent upon the other to exist.
