### ISSUE TITLE
Single stat not rendering

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3249]
I believe it only happens when there is an error in the query.

![image](https://user-images.githubusercontent.com/4805997/38962416-02fce47c-4322-11e8-89d9-d8e6deb20fe1.png)

**Comment by bthesorceror** [comment]
@russorat Should this just be changed to show a better error message?

**Comment by russorat** [comment]
Looks like this is fixed in master. Yes, we should show a better error message in this case, or for single stat, we should show 0 and highlight that the query is broken somehow in the UI (i think there is another issue open for that).
