### ISSUE TITLE
Error when selecting table graphs

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3250]
![image](https://user-images.githubusercontent.com/4805997/38962635-0be7d62c-4323-11e8-8641-b9dc1e141f4c.png)

**Comment by alexpaxton** [comment]
I think @ebb-tide said she was working on something related to this issue

**Comment by bthesorceror** [comment]
@russorat please verify this is still occurring.

**Comment by russorat** [comment]
yes this is still happening. to reproduce, create a new dashboard, click the table graph type, open the CEO, and click on the visualizations tab.

**Comment by bthesorceror** [comment]
@ebb-tide is currently working in this component.

**Comment by ebb-tide** [comment]
resolved By Pr #3282
