### ISSUE TITLE
Error in data explorer

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3251]
![image](https://user-images.githubusercontent.com/4805997/38962952-8afff7b8-4324-11e8-8288-ae2d86446a5d.png)

**Comment by bthesorceror** [comment]
Going to show a better error message in the case when invalid (not number) is attempting to be rendered in the line graph.

**Comment by russorat** [comment]
`The data returned from the query can't be visualized with this graph type. Try updating the query or selecting a different graph type.`
