### ISSUE TITLE
Viewer permissions should be able to select different template variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3253]
- [ ] viewer selections should not be persisted in the dashboard

specify the desired behavior when a viewer comes back to the dashboard. 

to reproduce, enable auth, ensure you have viewer only permissions, and try to change a tamplate variable on a dashboard.

![image](https://user-images.githubusercontent.com/4805997/38963095-2132c5bc-4325-11e8-8912-b8b9c4b889cb.png)

**Comment by russorat** [comment]
Still happening in master.

**Comment by russorat** [comment]
this is still happening in master:

![image](https://user-images.githubusercontent.com/4805997/39387062-5dae237a-4a2c-11e8-8c24-0c8fff1bc632.png)

**Comment by russorat** [comment]
- [ ] verify that if the auth credentials expire, the user is taken back to the login screen instead of a blank screen (cc @stevebang )

**Comment by bthesorceror** [comment]
For the time being we are disabling the drop downs for view accounts since trying to change the value would log out the user anyway.

**Comment by russorat** [comment]
- [ ] store the last used template variable value in the user's browser

**Comment by russorat** [comment]
is this solved by #3635 ?
