### ISSUE TITLE
CSV in template variable does not stay / gets change 

### ISSUE THREAD

**Issue by games130** [influxdata/chronograf#3263]
Version:  Chronograf 1.4.4.0 (git: fb799eca135d2d6f7f6864c64e74c843ea00f970)

I have set 2 template variable as shown in the screenshot below. One is **CSV** and the other is **Tag Value**.

![image](https://user-images.githubusercontent.com/32865575/38973163-dd1e9128-43d6-11e8-9b4e-82ad569f029c.png)

After saving, it is working fine.
![image](https://user-images.githubusercontent.com/32865575/38973179-f1e9acc8-43d6-11e8-87cd-832534021a1c.png)

Problem is when you re-login to chronograf / exit the dashbard (example go to data explorer) and go back to the dashboard, the **CSV** values are replaced by the **Tag Value**
![image](https://user-images.githubusercontent.com/32865575/38973196-089786f2-43d7-11e8-8bfa-d3703587e315.png)

**Comment by nomicflux** [comment]
Confirming that I have seen this behaviour in 1.4.4.1 as well.  In addition, the tag values themselves don't appear to be saved after re-login since at least 1.4.0.1.

**Comment by russorat** [comment]
@games130 @nomicflux thanks for the report. we will look into this and fix.

**Comment by russorat** [comment]
not seeing this anymore. thanks!
