### ISSUE TITLE
Auth0 Unable to get principal identifier Not a member of the required organization

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3277]
`ERRO[0141] Unable to get principal identifier Not a member of the required organization  component=auth method=GET remote_addr=[::1]:62208 url=/oauth/auth0/callback?code=qqvAlPHzW4xny41g&state=xxx`

trying to configure 1.4.4.1 or 1.4.3 with Auth0 and seeing this error, no matter what organization i set for the user.

To reproduce, follow the steps here to set up Auth0: https://docs.influxdata.com/chronograf/v1.4/administration/managing-security/#creating-an-auth0-application

Notice you can't log in.

It works when AUTH0_ORGS is not set.

**Comment by jaredscheib** [comment]
Documentation could possibly be improved, or at least clarifying that the org must exist in both `AUTH0_SUPERADMIN_ORG` and `AUTH0_ORGS`. cc @russorat
