### ISSUE TITLE
Initial Dashboard cell has no default heading, but other new cells do 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3278]
Chronograf **nightly build**

**n201804190831**

```
$ chronograf --version
2018/04/20 13:42:56 Chronograf 1.2.0~n201804190831 (git: e2d6ab87accba848ba7491804efe83bdb753d40a)
```
Browser **Chrome 65**

*Scenario*

1) Open the dashboards page 
2) Click "Create Dashboard" - the Dashboard management control opens with a default cell. 

The default cell has no header - Previously was "Untitled Cell" 

3) Click "Add Cell" - a second cell is added 

The second cell _has_ a default header "Untitled Line Graph" 

*Question* 

Why does the initial cell have no default header value?

It seems difficult to discern on first glance, that the header field even exists without a default value. 

Is this an intended feature change? 

*Screenshots*

![initialcellnoheading01](https://user-images.githubusercontent.com/25881301/39049416-aecb4868-44a1-11e8-9c2f-7e60cbcf1f21.png)
![initialcellnoheading02](https://user-images.githubusercontent.com/25881301/39049417-aee5c800-44a1-11e8-968e-f5c0c988619a.png)

**Comment by alexpaxton** [comment]
I actually just merged a fix for this in https://github.com/influxdata/chronograf/pull/3273

**Comment by russorat** [comment]
@karel-rehor can you confirm @alexpaxton's change fixes this?

**Comment by karel-rehor** [comment]
Verified fixed in 

```
$ chronograf --version
2018/04/24 10:29:49 Chronograf 1.2.0~n201804230831 (git: d3edc42627aef6b061f32f5067e8a396038bd815)
```

**Comment by karel-rehor** [comment]
closing
