### ISSUE TITLE
Multiple build errors

### ISSUE THREAD

**Issue by grimreaper** [influxdata/chronograf#3285]
(1) Several build dependencies are not documented: 

(a) It seems in order to build this project it must live under a directory called `src` which must be set as the `GOPATH`. This is mentioned as an assumption of the documented but not a requirement of the build.
(b) Before running `gmake` you must run `dep ensure -v` (or without `-v`).
(c) Only GNU make is supported. In particular `bmake` is not supported.

(2) After completing the above steps the following errors are shown
```
∴gmake
go build -o chronograf -ldflags "-s -X main.version=1.4.3.0-713-gd3edc4262 -X main.commit=d3edc426" ./cmd/chronograf/main.go
# chronograf/vendor/github.com/influxdata/chronograf/canned
vendor/github.com/influxdata/chronograf/canned/bin.go:20:11: undefined: AssetNames
vendor/github.com/influxdata/chronograf/canned/bin.go:23:18: undefined: Asset
# chronograf/vendor/github.com/influxdata/chronograf/dist
vendor/github.com/influxdata/chronograf/dist/dist.go:39:13: undefined: AssetInfo
vendor/github.com/influxdata/chronograf/dist/dist.go:59:18: undefined: Asset
vendor/github.com/influxdata/chronograf/dist/dist.go:74:11: undefined: Asset
vendor/github.com/influxdata/chronograf/dist/dist.go:83:14: undefined: AssetDir
vendor/github.com/influxdata/chronograf/dist/dist.go:84:14: undefined: AssetInfo
gmake: *** [Makefile:25: chronograf] Error 2
gmake 0.63s user 1.81s system 193% cpu 1.262 total; max RSS 25948Ki
```

**Comment by grimreaper** [comment]
ref #9 #7

**Comment by grimreaper** [comment]
If anyone runs into this in the future, you need to `go get` the repo, not just `git clone`. The Makefile does not properly initialize itself unless `go` was the one to do the clone.

I am leaving this open as there are things to better document or fix, even though I am now unblocked.

**Comment by grimreaper** [comment]
okay... and now I found this in the README: which I did read, just missed this earlier.

**Comment by shuLhan** [comment]
I would like to reopen this issue. In my opinion, Chronograf should be able to build from source cloned from git.

**Comment by grimreaper** [comment]
for visibility

**Comment by russorat** [comment]
@shuLhan @grimreaper thanks for submitting, but with `go` projects (which Chronograf and the other components of the TICKstack are), `go get` is the standard way to do this. we will not be addressing this issue.

If after following the instructions in the [contributing guide](https://github.com/influxdata/chronograf/blob/master/CONTRIBUTING.md#getting-the-source), you cannot get Chronograf to build, please reopen this issue.
