### ISSUE TITLE
Enhancement Request accessing Chronograf UI Admin Tool Bar w/ non admin user.

### ISSUE THREAD

**Issue by nwante** [influxdata/chronograf#3287]
**Versions being used:**
Chronograf Version="1.3.10.0" 
Influx enterprise version "1.3.8-c1.3.8"

I have two users currently configured, one is root, which is an admin user (all permissions etc). I then have another user that is not an admin user called nathan that just has read permissions.
![screen shot 2018-04-23 at 10 06 51 am](https://user-images.githubusercontent.com/21242788/39131901-94111e78-46de-11e8-803b-45e5cf6963ef.png)

The users etc all were added just fine, no problems. I am logged into chronograf with my nathan user that only has read permissions, the data source, logging in and everything is working just fine. I noticed that when I click the "Admin" crown on the left tool bar with a non admin user it just sits there and loads indefinitely. My request would be that if you are not an admin user it should present you with some sort of error message saying that you are not an admin user cannot access admin tool bar, or something like that. Aside from that everything appears to be working just fine.
![screen shot 2018-04-23 at 10 12 48 am](https://user-images.githubusercontent.com/21242788/39132110-0d9b79be-46df-11e8-8121-96387a37b42b.png)

**Comment by russorat** [comment]
@nwante thanks! yes i agree this should be fixed.
