### ISSUE TITLE
Kapacitor alert rule builder not showing grouped_by metrics

### ISSUE THREAD

**Issue by stefanhorning** [influxdata/chronograf#3288]
Since updating to Chronograf 1.4.4.1 (no sure from which version), I can no longer see metrics previews in the alert builder when using the 'Group By' query.

Either it shows nothing or it continues to show just one line in the graph instead of one per tag. In other places such as the data exlorer this query would still display as expected. Also I noticed some JS errors in the browsers console indicating issues while loading the data.

**Screenshot to proof data is there and group-by works in Data Explorer:**

![data-explorer-groupedby-tag](https://user-images.githubusercontent.com/1150445/39134322-abfb8536-4716-11e8-9c17-13a16464829a.png)

**Screenshots of failing to load metrics data in Alert Rule view when applying group-by on the same metrics:**

1. Group by not applied:
![chronograf-alert-builder-groupby-failing-to-load](https://user-images.githubusercontent.com/1150445/39134478-00ffb5f2-4717-11e8-9417-3df3d34049f6.png)

2. After refresh failing to load data alltogether:
![alert-rula-after-refresh-loading](https://user-images.githubusercontent.com/1150445/39134547-241279d0-4717-11e8-960b-fd7fecba8477.png)

Previously behaviour was analog to the one in other views (like the one in DataExplorer). Making this a regression of the chart viewer in the Alert Rule view.

Chronograf is running on an Ubuntu 16.04 server instance, using the influxdata ubuntu repo.

**Comment by russorat** [comment]
@stefanhorning thanks for the report, we will investigate and fix!

**Comment by stefanhorning** [comment]
Just confirmed that this was still working fine with 1.4.3-1
