### ISSUE TITLE
Warning: DataExplorer.childContextTypes is specified but there is no getChildContext() method on the instance

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3298]
I'm seeing this on master when browsing to data explorer

![image](https://user-images.githubusercontent.com/4805997/39212283-1dec0038-47c3-11e8-991e-329f0d5a69c5.png)

**Comment by bthesorceror** [comment]
This was fixed with https://github.com/influxdata/chronograf/pull/3302
