### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3306]
![image](https://user-images.githubusercontent.com/4805997/39220026-16646c5e-47e3-11e8-842b-4be02c737a27.png)

**Comment by russorat** [comment]
Seems to only happen when adding a template variable in a regex in the where clause

**Comment by bthesorceror** [comment]
@russorat does that query return anything, might just need to return a default on line 6 of an empty array.

**Comment by russorat** [comment]
yes the query is returning data.

**Comment by ebb-tide** [comment]
for the record, the query was returning 'data', but because the query had an error, the result was of the form: {error:"errortext"} rather than {results:{values:[]}}

**Comment by russorat** [comment]
<img width="1440" alt="screen shot 2018-04-26 at 3 59 01 pm" src="https://user-images.githubusercontent.com/4805997/39336197-116554c8-496b-11e8-8406-3119ef9a767f.png">
