### ISSUE TITLE
Feature Request: text input template variable

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3308]
I'd like a template variable type that allows me to input text that is substituted into the query.

For example, I'd like a query like:

```sql
select "message" from logs where message =~ /:input:/
```

... with `:input:` as my variable.  I'd like to search with different text in an ad-hoc way.

**Comment by alexpaxton** [comment]
This sounds awesome

**Comment by russorat** [comment]
As a user, i would like to have an option to enter free text into a template variable

- [ ] add a new template variable type called "Text Input"
- [ ] by default, it would always be an empty string
- [ ] the UI should show an open text box below the name of the template variable

example queries:
`SELECT severity,appname,facility,message,timestamp FROM "telegraf"."autogen"."syslog" WHERE time > now() - 5m AND "appname"=~/:APP_NAME:*/`

**Comment by alexpaxton** [comment]
- [ ] In the tempvar dropdown replace the dropdown with a text field when type is "Text Input"
