### ISSUE TITLE
Add the ability to define a custom icon for Generic OAuth Providers

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3319]
It would be nice if i could give Generic OAuth implementations the same type of icon as the built in ones like github.

![image](https://user-images.githubusercontent.com/4805997/39327124-ef75feea-494b-11e8-8966-8a5df61487cc.png)

**Comment by alexpaxton** [comment]
We have an auth0 icon, I just crated an Okta icon

**Comment by russorat** [comment]
Is there a way someone could add a flag to set their own? like `--generic-icon` or something? It will be tough for us to add icons for all OAuth providers.
