### ISSUE TITLE
Syntax error on GROUP BY auto

### ISSUE THREAD

**Issue by lardissone** [influxdata/chronograf#3322]
I'm using latest version as today in homebrew (--versions says: `2018/04/27 12:58:58 Chronograf  (git: )`).

In Data Explorer when I start browsing from database to measurements and values, I get grouped by default as Auto, but in the syntax I get `GROUP BY :interval:`.

Here's an example:
![chronograf](https://user-images.githubusercontent.com/59826/39372587-2f402ec2-4a1b-11e8-8b76-c65ec8931ecd.gif)

**Comment by russorat** [comment]
@lardissone  i believe we are addressing this in #3176 . cc @jaredscheib can you confirm?

**Comment by jaredscheib** [comment]
this is partly addressed by #3345, but it was also addressed by https://github.com/influxdata/chronograf/pull/3120 where that syntax was updated.
