### ISSUE TITLE
Make the font size of line + single-stat values configurable

### ISSUE THREAD

**Issue by wiigor** [influxdata/chronograf#3326]
I have a monitor for people to see when they enter a building, but they cannot see the values as they are too small. I would like to have an option to configure the font size of the value that is displayed in a line + single-stat visualisation

The current sizes of values and headers seem to be based on a single person sitting in front of a monitor. As opposed to a whole group standing around it at a distance of several meters.

So my request is for being able to edit the size of the header and value to suit specific situations. I edited the css manually for my specific situation, for me this worked:

![20180516_072701](https://user-images.githubusercontent.com/1317887/40100780-7d5cc600-58e5-11e8-9744-899c3684ee8f.jpg)

**Comment by wiigor** [comment]
If it would by by entering custom css per panel it would also work for me. Thanks a lot.

**Comment by alexpaxton** [comment]
@wiigor would you be able to provide a screenshot of what you are trying to accomplish?

**Comment by wiigor** [comment]
Hi alex good day, I added a picture of what I needed, but couldn't reach by configuration. So I just editted the css and recompiled it.
