### ISSUE TITLE
Negative values in Gauge not showing properly

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3328]
Ask @bthesorceror about repro steps.

![image](https://user-images.githubusercontent.com/4805997/39439378-3c48553e-4c5c-11e8-9bdb-06b192076ef0.png)

**Comment by bthesorceror** [comment]
The problem was that you could not set the minimum threshold to a negative number with the keyboard, you have to use the up and down buttons. Making a PR to allow entering in negative numbers.
