### ISSUE TITLE
Dashboards with the same name are both highlighted in the menu

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3334]
- [ ] we should use dashboard ID to determine what to highlight

![image](https://user-images.githubusercontent.com/4805997/39455307-96b439ec-4c94-11e8-941d-8d8a86df9889.png)

**Comment by jaredscheib** [comment]
![screen shot 2018-06-08 at 12 52 39 pm](https://user-images.githubusercontent.com/6403018/41178473-29ab4330-6b1c-11e8-8647-e87102d2eac9.png)
![screen shot 2018-06-08 at 12 52 44 pm](https://user-images.githubusercontent.com/6403018/41178475-29cf3b14-6b1c-11e8-9668-ef9b0dbfc254.png)

**Comment by chnn** [comment]
@jaredscheib is working in a related area of the codebase at the moment, so I'm going to mark this as blocked for now.

I did spend some time investigating the issue. As I see it, at the root of this issue are some larger system design choices around how dashboard data is loaded and stored. In particular, I think we could do a better job [normalizing](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape) our redux store as well as making the status of asynchronously loaded values in the store queryable.

I'll implement a quick fix for the immediate issue at hand once @jaredscheib is done, and then consider a larger refactor.
