### ISSUE TITLE
"Group By" only works if 'auto' not selected

### ISSUE THREAD

**Issue by smbunn** [influxdata/chronograf#3335]
![chronograf](https://user-images.githubusercontent.com/4195873/39459435-a48ebbc6-4d4f-11e8-83a7-f659e0a22543.jpg)
I just updated Chronograf today to the latest version (via 'sudo apt-get upgrade') on my Ubuntu 16.04 machine.  My dashboard immediately stopped showing data. 
I hit 'configure' on one of my charts and saw an error that said "saw an ':' when was expecting a value"
I tracked this to the colon on the Group By command in the query.  Changed Group By from auto (the default) to 1 minute and all my charts popped back again..

**Comment by russorat** [comment]
@smbunn in the latest chronograf, we updated the `:interval:` template variable to not include `time()` function. Your queries should have been migrated automatically when upgrading (cc @lukevmorris). To fix this query, you can update the query to be `GROUP BY time(:interval:)` assuming you are on the latest version 1.4.4.1.

Let me know if that resolves this issue.

**Comment by russorat** [comment]
closing based on my last comment.
