### ISSUE TITLE
new template variables don't always load

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3339]
From master (
![template](https://user-images.githubusercontent.com/1922921/39485478-7ab3f2aa-4d3e-11e8-96b3-81e026591b2a.gif)
dd1d902 ):

When I try to select tag values or tag keys many times I get "loading" that never ends.  Sometimes if I switch to another template type and go back to the original type the values load... but not always.

**Comment by russorat** [comment]
closing this in favor of https://github.com/influxdata/chronograf/issues/3348
