### ISSUE TITLE
Table not rendering data

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3340]
My query just returns a single field (no tags) and a single line. (master on commit dd1d902 )

<img width="970" alt="image" src="https://user-images.githubusercontent.com/1922921/39486389-8ea0f6a2-4d41-11e8-842f-9bf8b884cd43.png">

```json
{"results":[{"statement_id":0,"series":[{"name":"socket_listener","columns":["time","message"],"values":[[1525174448000,"panic: runtime error: invalid memory address or nil pointer dereference\\n"]]}]}]}
```

**Comment by russorat** [comment]
i think this is also related to #3336
