### ISSUE TITLE
Support subqueries in select.go (query AST)

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3350]
https://github.com/influxdata/chronograf/blob/master/influx/queries/select.go#L293

example:
`select sum(rate) from (SELECT difference("usage_user") AS "rate" FROM "telegraf"."autogen"."cpu" WHERE time > now()-15m GROUP BY *) WHERE "rate" > 0 GROUP BY cpu`

required for #1686

**Comment by ebb-tide** [comment]
@desa and I looked at this and concluded that it was not possible to update the queryAST generator to handle subqueries. Chronograf depends on Kapacitor which needs a ~1.1.x version of Influx to work with, and can not upgrade for a reason, so Chronograf can not update its own dependency on Influxdb. We decided on another way to deal with groupby's.

**Comment by russorat** [comment]
`can not upgrade for a reason`

for future reference, what is that reason?

**Comment by desa** [comment]
@russorat I couldn't find a specific issue for it, but it's related to InfluxDB not having an interfaced logger which makes it hard to use as a library. We could resolve the issue, but it'd be a bit of work.
