### ISSUE TITLE
YAxisLabels in Dashboard Graph Builder not showing until graph is redrawn 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3351]
Chronograf **Nightly Build** 

Build **n201805010837**

```
chronograf --version
2018/05/02 13:11:14 Chronograf 1.2.0~n201805010837 (git: dd1d90275a072323725a105c8fd12074f398a1b7)
```

*Use Case* 

1) Open Dashboards 
2) Set the refresh rate to a longer value, like 60s 
3) In the intital graph click *Add Data* - the graph builder loads 
4) Select telegraf.autogen > cpu > usage_idle.  The curve for usage_idle data is drawn in the preview graph at the top of the view. 

However the label for the y-axis is not shown.  The user needs to wait until the next data refresh for the axis label to appear. 

*Expected Behavior*

That the default Y-Axis label will appear within a second of the data field being selected.  Looking back at nightly tests, this has completed within 0.86s.  

http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/job/chrono-selenium/119/Chronograf_Automated_Test_Report/  

(see test: Show Legend Window Of A Dashboard - Filter Fields)

N.B. - a number of Selenium tests use assertions that the Y-Axis label is present before continuing.  So this issue leads to some new test failures. 

Screenshots: 

![yaxislabel01](https://user-images.githubusercontent.com/25881301/39520701-ee45680c-4e0b-11e8-837e-e7046140b5ab.png)
![yaxislabel02](https://user-images.githubusercontent.com/25881301/39520702-ee5d863a-4e0b-11e8-95aa-004a282d988a.png)
![yaxislabelfromnightlytest20140428](https://user-images.githubusercontent.com/25881301/39520704-ee75e18a-4e0b-11e8-9cd7-a8471f6fabb7.png)

**Comment by russorat** [comment]
@bthesorceror is this related to #3336 ?
