### ISSUE TITLE
Not able to integrate Jira tickets into News Feed section - Cross-Origin Resource Sharing (CORS) issue

### ISSUE THREAD

**Issue by francopeapea** [influxdata/chronograf#3358]
Trying to integrate Jira API into chronograf homepage, I face the problem that it wasn't able to return anything because of CORS

Jira Cloud doesn't allow set the header to disable CORS

<img width="630" alt="screen shot 2018-05-03 at 9 36 14 am" src="https://user-images.githubusercontent.com/16282981/39590341-7a3a8ad2-4eb5-11e8-907d-8379089ce2aa.png">

In Chrome it shows an 415 Error
In Firefox shows the same as the picture

**Comment by russorat** [comment]
@francopeapea thanks for reporting. sending this to the dev team to see if there is a way to fix this in our AJAX handler.

**Comment by russorat** [comment]
@francopeapea i'm not sure it's something we can help with. Check out this issue from JIRA: https://community.atlassian.com/t5/Answers-Developer-Questions/Integrating-Jira-Cloud-to-a-web-application-leads-to-CORS-error/qaq-p/510782

it has some potential solutions to the problem depending on your environment.

**Comment by francopeapea** [comment]
The problem actually after a couple of more days of troubleshooting and testing, is that the request isn't looking for any application/json content type, It's actually looking for text/plain
