### ISSUE TITLE
Template variables missing in variable drop down of Dashboard page

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3372]
Chronograf **nightly build**

build **n201805040829**

```
$ chronograf --version
2018/05/04 14:04:30 Chronograf 1.2.0~n201805040829 (git: 638f291bc20ee56474e66751f4ebb420296aa70e)
```

browser **Chrome 65**

using the enterprise test cluster described here: 

https://github.com/influxdata/bonitoo-selenium#starting-enterprise-cluster

*Use Case* 

1) Create a new dashboard 
2) In the first cell add data from telegraf.autogen.cpu > usage idle 
3) Click Template variables 
4) Click the Manage button - the template variables dialog pops up 
5) Enter the variable "host" 
6) Choose the type "CSV"
7) Add values "'cluster_node_1', 'cluster_node_2', 'cluster_node_4'" 
8) Save and close dialog 
9) Edit the the graph configuration so that the query contains "...WHERE... ...and host=:host:..."
10) Save the new query
11) Click on the Variable drop down ":host:" in the manage bar. 

There are no items in the drop down select. 

Nothing exceptional was seen in the console log. 

*Expected Behavior*

Previously the drop down contained values provided in the "Definitions/Values" field of the Template Variables dialog. 

*Screenshots* 

![templatevariablesmissing01](https://user-images.githubusercontent.com/25881301/39629854-ca60af70-4fad-11e8-8551-28170f1496d9.png)
![templatevariablesmissing02](https://user-images.githubusercontent.com/25881301/39629855-ca7c4abe-4fad-11e8-9dfb-5a7e096e7414.png)
![templatevariablesmissing03](https://user-images.githubusercontent.com/25881301/39629856-caa1a912-4fad-11e8-9b3b-5b7c20825eee.png)
![templatevariablesmissingprevtest](https://user-images.githubusercontent.com/25881301/39629858-cabc4c36-4fad-11e8-8b1e-c72b87391ee3.png)

**Comment by bthesorceror** [comment]
This is related to the bug in disabling template variables and is fixed with https://github.com/influxdata/chronograf/pull/3375
