### ISSUE TITLE
Confirm text for TagItems is mistakenly always about removal from organizations

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3380]
<img width="469" alt="screen shot 2018-05-04 at 4 30 54 pm" src="https://user-images.githubusercontent.com/6403018/39656968-a898b90e-4fb8-11e8-9a27-7ba5f71cfcf0.png">

This is mistaken in:
- [ ] OpsGenie config
- [ ] Kafka config

**Comment by russorat** [comment]
Just to clarify this issue: we would like to use the same component as we use on the all users page, but on that page, we want it to say "Remove user from organization" and on these Kapacitor components, they should say "Delete <text>".

**Comment by russorat** [comment]
seeing this in master:
![image](https://user-images.githubusercontent.com/4805997/39768757-13c793e2-529f-11e8-8447-9240817f9402.png)

**Comment by russorat** [comment]
great thanks!
