### ISSUE TITLE
Not running after install

### ISSUE THREAD

**Issue by DedovR** [influxdata/chronograf#3397]
After install Chronograf I got a message
`Failed to restart chronograf.service: No such method ‘RestartUnit’
See system logs and ‘systemctl status chronograf.service’ for details.
WARNING: systemd not running.`

Log is empty, ‘systemctl status chronograf.service’ return error
`Failed to get properties: No such interface ‘’`

OS: Ubuntu 16.04.3 LTS

**Comment by russorat** [comment]
@DedovR thanks for reporting! was this on 1.4.4.2 or master?

**Comment by DedovR** [comment]
Version 1.4.4.2, I use commands from https://portal.influxdata.com/downloads.

**Comment by russorat** [comment]
thanks we will investigate. seems like that WARNING is coming from: https://github.com/influxdata/chronograf/blob/master/etc/scripts/post-install.sh#L69 

While we investigate, do you know of anything unique to your system setup that might cause that to fail?

**Comment by DedovR** [comment]
The problem seems to be in starting of systemd service.
Maybe systemd version will help:

`$ systemd --version`
`systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN`

**Comment by russorat** [comment]
@DedovR can you verify systemd is running? if not, you will need to start it before doing this.

**Comment by DedovR** [comment]
systemd is really not running. We have server with 3 years of uptime, and still /sbin/init is a root process.

**Comment by russorat** [comment]
@DedovR right now, you need systemd running in order to use that command. if you use a different tool for running backend services, you will need to modify the startup script to handle that.

closing this for now. if you have a specific feature request, feel free to re-open and we will consider it. If you are looking for support on setting up or using, please use https://community.influxdata.com.

**Comment by DedovR** [comment]
@russorat, thank you for your time.
