### ISSUE TITLE
Chronograf continues notifying about host list page after being logged out

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3409]
I'm not sure why, but after being logged out for inactivity in chronograf, it seems to keep trying to make requests and displaying an error.

![kapture 2018-05-09 at 12 53 51](https://user-images.githubusercontent.com/4805997/39836426-2dc6e2ae-5388-11e8-8f1d-3eb28882ed67.gif)

**Comment by jaredscheib** [comment]
It doesn't necessarily appear to be making requests -- it could be a notifications issue post-logout.
