### ISSUE TITLE
When moving over data the legend feels like it "sticks" when the mouse goes over the legend

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3411]
At first I'm moving the legend by moving over each point under the legend.  Next, I do the same but happen to go through the legend and the legend doesn't move.  Before I figured out what was happening, I assumed that chronograf was very laggy.

![legend](https://user-images.githubusercontent.com/1922921/39872959-4425c61c-542f-11e8-9f2d-312346af9d24.gif)

**Comment by russorat** [comment]
we have improved this in recent releases so closing this for now.
