### ISSUE TITLE
Speed up or disable the query to populate the quick switch between layouts

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3414]
In order to populate this dropdown, we re-run this query:
`{"query":"show series from /^apache$|^consul_health_checks$|^consul_consul_fsm_register$|^consul_memberlist_msg_alive$|^consul_raft_state_candidate$|^consul_consul_http_GET_v1_health_state__$|^consul_raft_state_leader$|^consul_serf_events$|^cpu$|^disk$|^diskio$|^docker$|^docker_container_blkio$|^docker_container_net$|^elasticsearch_indices$|^haproxy$|^influxdb_database$|^influxdb_httpd$|^influxdb_queryExecutor$|^influxdb_write$|^kubernetes_node$|^kubernetes_pod_container$|^kubernetes_pod_network$|^kubernetes_system_container$|^system$|^mem$|^memcached$|^mesos$|^mongodb$|^mysql$|^net$|^netstat$|^nginx$|^nsq_channel$|^nsq_server$|^nsq_topic$|^phpfpm$|^ping$|^postgresql$|^processes$|^procstat$|^rabbitmq_node$|^redis$|^riak$|^varnish$|^win_cpu$|^win_mem$|^win_net$|^win_system$|^win_websvc$/","db":"telegraf"}`

for customers with a large number of hosts, this blocks their browser for a long time. in addition, since you can't scroll this list ( #3075 ), it isn't really helpful. 

So we need to speed up this query and fix #3075. If that's not possible, then we should disable this quick switch feature.

![image](https://user-images.githubusercontent.com/4805997/39880956-1eae0034-5434-11e8-979c-44c91aed994e.png)

**Comment by goller** [comment]
@russorat ages ago I took a run at this problem.  In the end the query would need to be broken up ... here's how:

1. Break up the query into, say, sets of 10 measurements and run the queries concurrently. 
-or-
2. run the query with the `LIMIT` and `OFFSET` keyword and page through the results.
https://docs.influxdata.com/influxdb/v1.5/query_language/schema_exploration/#show-series

If I remember correctly, it was a lot slower over all, but, each individual query was faster.  It would probably make the page "feel" faster as data would load in.

**Comment by jaredscheib** [comment]
Thanks @goller! Also, it seems like that switcher, if there are hundreds or thousands of hosts, is not super practical anyway. Maybe some deeper rethinking would be good?

**Comment by russorat** [comment]
We should just disable the drop down and the query for layouts and not try to optimize (since we are converting these to dashboards very soon). for user with small host lists, it isn't a huge issue if the user needs to click the back button and select another host.

When we redesign the host list page in #682 , we will address this in more detail.

**Comment by russorat** [comment]
to whomever picks this up, please chat with @nhaugo as he has some ideas to speed this up.

**Comment by russorat** [comment]
- [ ] switch to a simple "show tags" query
- [ ] only populate when someone clicks the dropdown
- [ ] fix #3075
