### ISSUE TITLE
TICKscript log viewer not working

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3415]
I'm unable to get the logs for a tickscript to display in the latest build, and there are no console warnings. this was working in 1.4.4.2

![image](https://user-images.githubusercontent.com/4805997/39881133-d98c4bcc-5434-11e8-8953-5a4acc67293f.png)

```
var name = 'High CPU Alert'

var db = 'telegraf'

var rp = 'autogen'

var measurement = 'cpu'

var groupBy = []

var whereFilter = lambda: TRUE

var idVar = 'something'

var message = 'this is a test'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var crit = 50

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "usage_user")
        .as('value')
        .quiet()
    |log()
```

**Comment by russorat** [comment]
This doesn't work with base_paths enabled.

**Comment by russorat** [comment]
🦄

**Comment by w4tsn** [comment]
Hey there! I'm having this issue now with Chronograf v1.7.5 and kapacitor 1.5.1 docker versions. When opening a tickscript in the editor it shows the error 'Could not collect kapacitor logs'. No BASE_PATH configured. As far as I know, this feature did not work for me from the beginning. Could be a misconfiguration. I'm struggling to debug this and I couldn't find anything regarding this in the docs.

How do I troubleshoot this? What is causing this issue? Any ideas?
