### ISSUE TITLE
Add Logviewer to Chronograf

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3420]
This issue is to track all the enhancements we will need to support viewing logs in Chronograf.

**Comment by russorat** [comment]
initial thoughts from @nhaugo 

<img width="1819" alt="wireframe-logs" src="https://user-images.githubusercontent.com/4805997/40028412-8ac5e6f8-5793-11e8-9bef-22c7b1555e7a.png">

log panel: `SELECT "message", "appname", "host" FROM "telegraf"."autogen"."socket_listener" WHERE time > now() - 1m`
total: `SELECT count("message") AS "count_message" FROM "telegraf"."autogen"."socket_listener" WHERE time > :dashboardTime: GROUP BY time(:interval:) FILL(null)`
errors: `SELECT count("message") AS "count_message" FROM "telegraf"."autogen"."socket_listener" WHERE time > :dashboardTime: AND "severity"='error'`
info: `SELECT count("message") AS "count_message" FROM "telegraf"."autogen"."socket_listener" WHERE time > :dashboardTime: AND "severity"='informational'`

**Comment by alexpaxton** [comment]
@russorat / @nhaugo would the search bar just affect the table?
