### ISSUE TITLE
Add ability to filter template variables from other variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3424]
As a user, i would like to be able to select a specific region (us-east) and have the other template variables update and only show values relevant to us-east. This would allow different teams to use the same dashboard but with different variables selected.

This might come as part of a larger redesign to template variables.

- [ ] support this behavior in the custom meta query option. For example, a query like this should work: `SHOW TAG VALUES ON "telegraf" FROM "influxdb" WITH KEY = "host" where "cluster_id" =~ /:Cluster_Id:/`

may need #3727 for this to work properly.

**Comment by candlerb** [comment]
I have another use case for this.  I am collecting SNMP data, and I want

~~~
:agent_host:
SHOW TAG VALUES ON telegraf FROM interface WITH KEY=agent_host

:ifDescr:
SHOW TAG VALUES ON telegraf FROM interface WITH KEY=ifDescr WHERE agent_host=:agent_host:
~~~

That is: the list of available interfaces depends on the device which has been selected.  This makes it easier to drill down to a specific interface.

**Comment by russorat** [comment]
you should be able to do this via #3637 and #3727
