### ISSUE TITLE
layouts broken when setting a custom database and rp

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3435]
with auth, and basepaths enabled,
to repro, set up a new source with a custom telegraf database name and retention policy. then try to go to a system layout and notice it is blank. there are no errors in the console log.

**Comment by bthesorceror** [comment]
Cannot reproduce

**Comment by jaredscheib** [comment]
If this comes up again, let me or @ischolten know as we may be able to help determine why, since we implemented custom rp on InfluxDB connections.
