### ISSUE TITLE
Invalid Query in Data Explorer fails to generate an error message 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3438]
**Nightly Build**

build time **n201805140829**

Browser **Chrome 66**

```
chronograf --version
2018/05/14 14:51:23 Chronograf 1.2.0~n201805140829 (git: c55276ccb46f4e0f2eda4414e1915a139eac5304)
```

*Use Case*

1) Open data explorer
2) Choose the telegraf database
3) Enter a Garbage string into the query editor, e.g. "bad query"
4) Press [Enter] 

The data explorer seems to reload and the string remains however there is no message, as in the past, that the query resulted in an error in Influx. 

Console log clearly shows the expected error. 

*Expected Behavior*

That an error would be caught and that the user would be notified.

*Screenshots* 

![badquery01](https://user-images.githubusercontent.com/25881301/39999475-77409092-5789-11e8-99b5-cbed2e4db42f.png)
![badquerypreviousrun](https://user-images.githubusercontent.com/25881301/39999639-e233e3e0-5789-11e8-833f-877786d45baa.png)

*Logs* 
[localhost-1526303210425.log](https://github.com/influxdata/chronograf/files/2000843/localhost-1526303210425.log)

**Comment by russorat** [comment]
@ebb-tide i still see this in master. was this checked in?

**Comment by russorat** [comment]
looks good!
