### ISSUE TITLE
Sort order of TICKscript names in Manage Tasks is inconsistent 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3455]
build **nightly build** 
build time **n201805150830**
browser: **Chrome 66**

```
$ chronograf --version
2018/05/15 16:33:16 Chronograf 1.2.0~n201805150830 (git: a23052f41fe43d444240075ede2b032a1e4c2a8c)
```

*Use case* 

1) Create a small number of new alerts with names like {rule_enabled, rule_not_enabled, etc.}
2) Create a small number of new TICKscripts with similar names using underscores, but also beginning with different letters of the alphabet.  e.g. {stream_tick, stream_tick_2, stream_tick_3, TEST_SCRIPT_1, TEST_SCRIPT_2}
3) Check these in the Manage Tasks page 

In the Alert Rules table the sort order seems to be alphanumeric. 
*However* in the TICKscript table the order is only loosely alphanumeric.  Scripts with names like 'stream...' are listed above scripts with names like 'rule...' 

*Screenshots* 

![sortordermanagetasks01](https://user-images.githubusercontent.com/25881301/40065506-464686e8-5862-11e8-8206-b9b0ecd19401.png)
![sortordermanagetasks02](https://user-images.githubusercontent.com/25881301/40065507-4663c640-5862-11e8-9db3-b7cf5f106738.png)

**Comment by russorat** [comment]
- [ ] sort each section alphabetically.
