### ISSUE TITLE
Add _Internal to Template Variable DB Dropdown

### ISSUE THREAD

**Issue by dp1140a** [influxdata/chronograf#3463]
Currently the _internal DB is not part fo the DB dropdown when creating a template variable for tag values.  Please add the _internalDB as an option.

**Comment by russorat** [comment]
this was fixed as a side effect of the work on template variables https://github.com/influxdata/chronograf/issues/3631


![image](https://user-images.githubusercontent.com/4805997/42535158-7d767468-8443-11e8-9de2-f7f85ef8bc1f.png)
