### ISSUE TITLE
New TICKscripts enabled by default 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3479]
build **Nightly build**

build time **201805170830**

Browser **Chrome**

```
$ chronograf --version
2018/05/17 16:31:59 Chronograf 1.2.0~n201805170830 (git: e5cf079e9ed38694a7bac3f1b9aa7d2348532c7b)
```
*Use Case*
1) Create a new and valid TICKscript in the TICKscript Editor
2) View the TICKscript in the manage alerts page 

I see that the new TICKscript is listed as "Enabled" by default.  

*Expected Behavior*

I know from working with CLI Kapacitor, that when a new task is defined by a TICKscript it is "Disabled" by default.  This gives the user the chance to test the task *before* enabling it.  

I would expect *Enabling* an Alert Task should be done explicitly.  This could be done either in the Manage Tasks table with existing controls or with a checkbox "Enable on creation" OR "Enable/Disable" in the TICKscript Edit page.

**Comment by russorat** [comment]
when a user saves, it is automatically enabled. we should do this when we have https://github.com/influxdata/chronograf/issues/2797
