### ISSUE TITLE
Switching visualization type causes error

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#3480]
![kapture 2018-05-17 at 10 09 33](https://user-images.githubusercontent.com/10937678/40192882-796282d0-59ba-11e8-980b-453cb552faba.gif)

**Comment by russorat** [comment]
@ebb-tide does this need to be cherry picked to the 1.5 branch?

**Comment by ebb-tide** [comment]
No this was introduced by typescriptifying that was merged in after the
branch was cut.
