### ISSUE TITLE
Export / Import Dashboards from Chronograf UI

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3488]
As a user, i would like to download a dashboard as a file and share it with another user of chronograf.

- [x] a viewer role or higher should be able to download a file containing all the information needed for a dashboard.
- [x] an editor role or higher should be able to import that file to create a new dashboard.
- [x] if the import fails for some reason, an error should be shown to the user and no new dashboard is created.
- [x] the version of chronograf that created the export and a dashboard spec version should be in the exported file.

related: https://github.com/influxdata/chronograf/issues/1155

**Comment by madisonleavo** [comment]
Similar use case as linked #1155: I will be using puppet to distribute a few custom dashboards to many machines. And JSON/structured files are just easier to deal with, version, etc!

**Comment by alexpaxton** [comment]
@russorat should we include chronograf version in the dashboard json?

**Comment by alexpaxton** [comment]
<img width="1552" alt="screen shot 2018-05-22 at 2 41 30 pm" src="https://user-images.githubusercontent.com/2433762/40570042-ae05c77c-603b-11e8-802c-01ecca0d45de.png">

Clicking `Import` should open an overlay with a drag & drop area similar to the `Write Data` modal

Notifications should fire when the upload is successful or fails

After uploading the user should stay on the dashboards index view
