### ISSUE TITLE
Add "Dynamic Source" option to source selector when creating dashboard cells

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3502]
It's currently not clear that your cells will "float" to the current source, and that once you choose a source from the selector for a cell, that that cell stays on that source in lock-step. There's also no clear way (and it's not currently possible anymore as of #3500) to set a cell to float with the current source. Adding an explicit `Dynamic Source` option to the source selector would clear up this confusion and users the ability to allow a cell to float in this way, rather than only always being fixed to a specific source.

cc @timhallinflux

**Comment by russorat** [comment]
@alexpaxton can we add this to the #3717 ?

**Comment by russorat** [comment]
can we tackle this in #4021 ?

**Comment by alexpaxton** [comment]
Designs for the (potentially) edge case of a dashboard with one or more Dynamic Source cells built with Flux and the user switches to a legacy (InfluxQL) source:

1. Show error state in cell:
![screen shot 2018-08-02 at 1 59 09 pm](https://user-images.githubusercontent.com/2433762/43611028-c4481808-965c-11e8-88c9-e960e4bb6b36.png)

2. Show error tooltip in CEO with suggestions to resolve:
![screen shot 2018-08-02 at 1 57 24 pm](https://user-images.githubusercontent.com/2433762/43611100-f0b7ae94-965c-11e8-8256-e277200a7003.png)

This last mockup I would not consider a requirement but more a topic for discussion. What if dynamic cells had an icon (or other indicator) to distinguish them at-a-glance from other cells?
![screen shot 2018-08-02 at 2 01 54 pm](https://user-images.githubusercontent.com/2433762/43611146-0f761762-965d-11e8-8385-d59db5e28e51.png)

**Comment by alexpaxton** [comment]
![screen shot 2018-08-02 at 2 12 27 pm](https://user-images.githubusercontent.com/2433762/43611509-2aaec5dc-965e-11e8-8c96-4ca86b1a248e.png)


If the user sets a cell to `Dynamic Source` reveal the current source in a tooltip when hovering the dropdown. Also reveal a radio button set with `Flux | InfluxQL`

If the current source is legacy and the user clicks `Flux` show the error tooltip above as a warning

**Comment by jaredscheib** [comment]
@alexpaxton this seems like a good example of where components may have states beyond what we use for `RemoteDataState` currently. in this case, this component may have its own states and use a union of them all, such as:
```
import {
  RemoteDataState,
} from 'src/types'

enum ComponentState {
  Incompatible = 'incompatible',
}

type AllStates = RemoteDataState | ComponentState

interface State {
  loading: AllStates
}

constructor(props) {
  super(props)
  this.state = {
    status: ComponentState.Incompatible
  }
}
```

**Comment by jaredscheib** [comment]
additionally, from that last mockup it looks like the Flux / InfluxQL element is toggleable, but my impression is that it's just meant to be presentational?
