### ISSUE TITLE
Branch 1.5.0.x - pre-release test shows TICKscript sort order not respected 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3503]
build from branch **1.5.0.x** located here:

http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chronograf-1.5.0.x/

browser **Chrome 65**

Jenkins/JBehave/Serenity/Selenium results: 

http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/job/chrono-selenium-release/Chronograf_Automated_Test_Report/

Actual server/page location:

http://ec2-13-56-14-109.us-west-1.compute.amazonaws.com:8888/sources/1/alert-rules

```
 chronograf --version
2018/05/22 15:11:53 Chronograf 1.4.3.0 (git: 975b95d2b670d105b33c0a1276f9e63ac6724ef8)
```

_Please note that on our local build of Chronograf branch 1.5.0.x we have not yet set up the release stamp_

alternately see the time stamp at the bottom of this page
http://ec2-13-56-14-109.us-west-1.compute.amazonaws.com:8888/sources/1/manage-sources

*Use case*

1) Create a number of (12) TICKscripts some whose names begin with upper case letters and others with names beginning with lower case, also include other characters such as dashes 
2) Check the sort order of the TICKscript table in the page alert-rules. 

The sort order is not by alpha 

*Expected behavior* 

That the sort order would be by alpha 

*Note on github branches* 

This use case is passing in nightly builds 

http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chronograf-serenity/Chronograf_Automated_Test_Report/

*Note on previous issue*

This was fixed last week as #3455.  Was this fixed merged into the release?

*Screenshot*
![chrono1 5 0-tisksortorder01](https://user-images.githubusercontent.com/25881301/40365067-128f6cf8-5dd4-11e8-82e7-c1b361dffd19.png)

**Comment by russorat** [comment]
see linked issue
