### ISSUE TITLE
Alterting Rules

### ISSUE THREAD

**Issue by eohan01** [influxdata/chronograf#3521]
If I have a Deadman script sending e-mails.  How can I suppress the e-mail for a while,  withing the script vs disabling the rule, so that inboxes do not get the alert every xx minutes

I would like to alter once and then in 30 minutes alert again or escalate

But as it stands now, i get an email, slack, "handlers" etc every xx miniutes.

**Comment by russorat** [comment]
@eohan01 are you using `.stateChangesOnly()` on your alert node? https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/#statechangesonly

If you have additional questions, it's better to ask in https://community.influxdata.com. If you have a specific feature request or bug report, feel free to reopen.
