### ISSUE TITLE
Small Y axis values don't scale

### ISSUE THREAD

**Issue by candlerb** [influxdata/chronograf#3530]
This is from the default system dashboard:

![image](https://user-images.githubusercontent.com/44789/40577726-1d53cf36-6102-11e8-9294-ded72512bc04.png)

Maybe it's going from 0.02000% to 0.02001% over that range; maybe it's 0.01500% to 0.02499%. I can't tell.

I think small values should be auto-scaled, either to exponential format (2.35e-2) or possibly to milli/micro/nano as appropriate (e.g. 23.5m).

Having said that: when the graph shows percent, milli-percent would be a rather strange unit (1 x 10<sup>-5</sup>)

**Comment by russorat** [comment]
we will see what we can do here to be a little smarter. until then, you should be able to manually set the y-axis in the graph control.

**Comment by jarmokivekas** [comment]
I've run into similar tick markers with data values in the range [-1000, -1400]. The tick logic is fine when looking at the entire time span, but the ticks don't get more accurate when zooming in.

Past 6-h view, ticks ok:

![screenshot from 2018-09-03 21-56-44](https://user-images.githubusercontent.com/3074453/44999246-6b183700-afc4-11e8-987a-729086498735.png)

When zooming in, the tick accuracy is not increased:

![screenshot from 2018-09-03 21-56-54](https://user-images.githubusercontent.com/3074453/44999247-6ce1fa80-afc4-11e8-9b2d-4299858e8e40.png)
