### ISSUE TITLE
Deadman  {{index .tags "tagname"}}  not working any more

### ISSUE THREAD

**Issue by eohan01** [influxdata/chronograf#3542]
This was closed in issue #3528 

But Quite frankly I believe it is a bug the
```
{{ index .Tags "hostname" }}
{{ index .Tags "service" }}
{{ index .Tags "host" }}
```
are not available if **grouped** in the group by, or **not grouped** in the group by.
This use to work in pre 1.5.0 Kapacitor and Chronograf
and i have checked, they are still tag fields in the InfluxDB database

Here is my Chronograf generated Deadman tick script

I have a group by but the text of the e-mail sent still contains no values for

hostname
host
and service

I am having a rough time trying to use the {{ index .Tags "fieldname"}} to extract the tag values to be incorporated in the e-mail body or subject
```
var db = 'telegraf'

var rp = 'autogen'

var measurement = 'mongodb'

var groupBy = ['host', 'hostname', 'service']

var whereFilter = lambda: ("host" == 'wwwww.homedepot.com') AND ("hostname" == 'xxxxxxx.homedepot.com') AND ("service" == 'yyyyy')

var period = 1m

0s

var name = 'MongoDB Deadman'

var idVar = name + ':{{.Group}}'

var message = ' Level: {{.Level}} hostname: {{ index .Tags "hostname" }} host: {{ index .Tags "host" }}  service:  {{ index .Tags "service" }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'deadman'

var details = 'Level: {{.Level}} 
hostname: {{ index .Tags "hostname" }}
service:  {{ index .Tags "service" }}
host:     {{ index .Tags "host" }} 
ID:       {{.ID}}
Name:     {{.Name}} 
TaskName: {{.TaskName}}
Group:    {{.Group}}
Tags:     {{.Tags}} 
Level:    {{.Level}} 
Time:     {{.Time}} 
Fields:   {{ index .Fields "hostname" }} {{ index .Fields "host" }}'

var threshold = 0.0

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)

var trigger = data
    |deadman(threshold, period)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .details(details)
        .email()
        .to('<email>')

trigger
    |eval(lambda: "emitted")
        .as('value')
        .keep('value', messageField, durationField)
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')
```

**Comment by russorat** [comment]
@eohan01 thanks for opening! let me try your script pre and post 1.5 and get back to you with what i see.

**Comment by IdrisGawr** [comment]
Hi! Any update?

**Comment by nicksanders** [comment]
Hi, any update? I'm seeing the same issue with Kapacitor 1.5.1

**Comment by arcturial** [comment]
Any update? seem to be having the same issue. I am unable to determine which tags have not received metrics

**Comment by ajayanaj** [comment]
I'm also facing the same issue, the "groupby" tag seems not identified by the deadman switch.
From the alert perspective it's triggering alert but without any details which means no use with the alert. 
We are using kapacitor version : 1.5.2
Please prioritise this issue.

**Comment by UnAfraid** [comment]
I have the same issue with deadman switch
Using Kapacitor OSS 1.5.3 (git: HEAD e6bc51b8447de450c3f6fc0f6e47b6a0987ce5b6)

**Comment by llmuculusll** [comment]
same issue

**Comment by deLayzi** [comment]
Hello, 

I am also having the same issue, {{ index .Tags "host" }} is null

In fact, it looks like the whole map for {{.tags}} is returning a null map 

 | tags map[] | fields map[emitted:0]

| tags {{.Tags}} | fields {{.Fields}}

I am running in container version 1.5.3

**Comment by qhualaupies** [comment]
Same here.

**Comment by ashishkaransingh** [comment]
Still this issue

**Comment by galuque** [comment]
Same issue. Happens with stream tasks only.
