### ISSUE TITLE
On Threshold, "more than" and "less than" need additional language

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#355]
If the user has "more than" or "less than" when creating a threshold type alerting rule, it should show the textbox and the words "times during the last" instead of what's there now, which is "during the last". In general all alerting rules creations should read like complete english sentences.

Also, the textbox should be 3 characters wide since users will almost certainly be entering numbers < 1,000.

**Comment by jademcgough** [comment]
Old issue, I don't think this is valid anymore. Moving it to delivered for @nhaugo to verify.
