### ISSUE TITLE
Icons for selecting previous and next month in date picker seem unrelated to concept

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3561]
![screen shot 2018-06-01 at 10 41 22 pm](https://user-images.githubusercontent.com/6403018/40871242-f9cb4d2e-65ec-11e8-9ffe-ecc02e8e1d35.png)

I think I'd expect a left and right arrow rather than the two icons presented.

**Comment by russorat** [comment]
![image](https://user-images.githubusercontent.com/4805997/41252706-d37df0c6-6d72-11e8-9b1c-1553daa66153.png)
