### ISSUE TITLE
Dashboard: Populating template variables using DISTINCT field values

### ISSUE THREAD

**Issue by regel** [influxdata/chronograf#3563]
Chronograf version 1.5.0.0 - running in Docker (installed using docker pull) on Mac.
Browser: Version 66.0.3359.181 (Official Build) (64-bit)

With 1.5, we can use template variables based on tag keys, and tag values, not on field values.

The only alternative seems to run the command in the CLI, and then use returned values in CSV to create the template variable (in Definition/Values screen).

> select DISTINCT("field") from measurement
name: measurement
time distinct
---- --------
0    a
0    b
0    c

**Comment by russorat** [comment]
@regel sorry it's taken a little time to respond to this issue. could you describe the use case you have for adding field values to a template variable?
