### ISSUE TITLE
/etc/default/chronograf file seemingly being ignored

### ISSUE THREAD

**Issue by aolgin** [influxdata/chronograf#3568]
Hi,

I'm running into a similar issue to #2134 (originally posted this in there but figured it may be better to just open a new issue) where I set variables in the /etc/default/chronograf file, and they just do not work. I'm able to get it running when I pass them as flags in a command, and if I specify environment variables in my docker-compose file, they will also work, but just purely putting the variables and their values in /etc/default/chronograf fails for me.

For reference, I'm using the following variables/flags: TOKEN_SECRET, PUBLIC_URL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_DOMAINS, LOG_LEVEL.

Also, I'm using Chronograf 1.5.0.0 (git: 2315266)

When using only the /etc/default/chronograf file and running the service, there's no login page and I'm taken right into my chronograf instance without having to go through any form of authorization.

Any advice on what to do? I'm happy to provide more input to help troubleshoot this issue.

**Comment by russorat** [comment]
@aolgin what OS are you using?

**Comment by aolgin** [comment]
Sorry, forgot to add that in! I'm using Centos 7.5

**Comment by russorat** [comment]
and could you remove the secrets and attach your `/etc/default/chronograf` file?

**Comment by aolgin** [comment]
```
PUBLIC_URL=http://localhost:8888
TOKEN_SECRET=example
AUTH_DURATION=720
GOOGLE_CLIENT_ID=example.id
GOOGLE_CLIENT_SECRET=example.secret
GOOGLE_DOMAINS=example.com
```

**Comment by aolgin** [comment]
Hm...looking at this some more, it might just be some docker issue. I'm able to get it working using that config file shown earlier when just booting up a centos 7.5 VM with VirtualBox, but whenever I try to install with docker, those values just don't seem to take hold. Using the [TICK Sandbox](https://github.com/influxdata/sandbox), as well as a fresh centos docker container that I've installed Chronograf on, I can only get the auth working when I explicity add those environment variables in the docker-compose.yml.

**Comment by russorat** [comment]
@aolgin this seems like a documentation issue about how to configure the tick stack with docker? or do you still think there is an issue with chronograf?

**Comment by aolgin** [comment]
It no longer appears to be an issue with Chronograf, but more with Docker and its handling of environment variables.
