### ISSUE TITLE
Each cell making multiple of the exact same request to proxy for time series data when using template variables

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3576]
This is unnecessary. Only one request needs to be made to proxy for a graph's time series data.

It also makes debugging confusing, probably hurts performance, and results in a lot of wasted data transmission over the wire.

Repro steps:
Add a deep equal check to the query that `executeQueries` is running in AutoRefresh. Or just look at the corresponding requests in the Network tab in devtools.

**Comment by 121watts** [comment]
@jaredscheib I'm unable to reproduce this. mayhaps send me the dashboard you're using that you see on?
![kapture 2018-06-13 at 8 02 49](https://user-images.githubusercontent.com/7582765/41359889-56ba9156-6ee0-11e8-9f1c-a1b0f79a8887.gif)

**Comment by jaredscheib** [comment]
@121watts It happens when using template variables – got 3 of the same query just now in testing:
<img width="1440" alt="screen shot 2018-06-15 at 4 42 33 pm" src="https://user-images.githubusercontent.com/6403018/41493348-2e27e054-70bb-11e8-8fb4-8b1a152d1a54.png">
<img width="1440" alt="screen shot 2018-06-15 at 4 42 39 pm" src="https://user-images.githubusercontent.com/6403018/41493349-2e56c8b0-70bb-11e8-9287-555a55ac8e24.png">
<img width="1440" alt="screen shot 2018-06-15 at 4 42 44 pm" src="https://user-images.githubusercontent.com/6403018/41493350-2e8670a6-70bb-11e8-8459-790b5210f5c4.png">
