### ISSUE TITLE
Add support for influxdb with LDAP enabled

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3578]
influxdb enterprise 1.6 will allow LDAP and we will need to understand what we need to update in the influxdb admin page to support that.

- [x] add the ability to determine if the user has LDAP enabled. Investigate which (if any) of the options will work
- [ ] Disable the users management page when the user has LDAP enabled
- [ ] On the roles page, remove the column for adding roles to users

Possible ways to determine if ldap is enabled:
> The best way without any changes is to `GET /ldap/v1/config` on a meta node, parse the TOML, and find top-level enabled=true.
> I guess the next best way would be SHOW USERS. I think you'll get an LDAP error (not allowed when LDAP enabled). Or the /users endpoint on a meta node, will either show no users even though you're logged in, or it will mention an LDAP error.

**Comment by bthesorceror** [comment]
Authentication method is now added to sources [unknown, ldap, basic, shared]

**Comment by 121watts** [comment]
what do we want to do if the method is "unknown"?

**Comment by 121watts** [comment]
Connecting to enterprise with LDAP enabled works.  However, hitting the proxy does not.  All other `links` seems to be working.  Just not the `proxy` link.  

`{"code":400,"message":"received status code 401 from server: err: authorization failed"}`
