### ISSUE TITLE
DevTools failed to parse SourceMap warning in console

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3581]
The devtools console shows a consistent warning: `DevTools failed to parse SourceMap: http://localhost:8888/grammar.js.map`.

This file is part of the `rst-selector-parser` node module. I briefly looked into the issue and attempted to resolve it by adding the following object to webpack's `noParse` list, but it did not resolve the issue:

```
      path.resolve(
        __dirname,
        '..',
        'node_modules',
        'rst-selector-parser',
        'grammar.js.map'
      ),
```

**Comment by russorat** [comment]
is this still happening?
