### ISSUE TITLE
Mantain Compare references

### ISSUE THREAD

**Issue by educastella** [influxdata/chronograf#3592]
If you are using a compare reference in a Dashboard, once you get out this Dashboard this reference is lost. I want to keep a compare with the day before.

**Comment by russorat** [comment]
@educastella thanks for the issue. just so i understand, could you maybe add a screenshot of where you are using "compare" in the app?

**Comment by jaredscheib** [comment]
Compare is in the Data Explorer and CEO.

**Comment by educastella** [comment]
Yes, if you set Compare to 12h and then jump to another Dashboard then this compare reference is lost.

**Comment by educastella** [comment]
I have checked that If there is more than one graph and you set this compare option it only remains the last one set.
