### ISSUE TITLE
Preserve zoomed range for dashboard when switching away and back

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3597]
Blocked on (and will go nicely with) #3545.

It would be straightforward and probably useful to preserve a dashboard's zoomed range when switching away from it and returning to it in that zoomed state. This can happen via the zoomedTimeRange in redux, and should work well and easily via temp vars url queries.

This is blocked until the above issue is implemented because it would be confusing for users who don't realize that they're zoomed into a graph and how to zoom out.

**Comment by karel-rehor** [comment]
@jaredscheib  I was starting a selenium test for the "zoomedLower" and "zoomedUpper" in the Dashboard URLs.  However, I noticed that these arguments are apparently ignored when pasted into the address bar.  

Is this correct?

Here are some screenshots of how chronograf (`nightly build 201807311829 (git: 375c9896e80a0f89d14a651b510fc17fd23e6a3b)`) is currently behaving . 

![zoomedinurlindashboard01](https://user-images.githubusercontent.com/25881301/43523465-be3de480-959c-11e8-9220-1266df5bc93d.png)
![zoomedurlindashboard02](https://user-images.githubusercontent.com/25881301/43523466-be5e5580-959c-11e8-83f1-8b6f9b460fc5.png)
![zoomedurlindashboard03](https://user-images.githubusercontent.com/25881301/43523467-be7bc3ae-959c-11e8-96bc-fdf7e4028922.png)
![zoomedurlindashboard04](https://user-images.githubusercontent.com/25881301/43523468-bea1c900-959c-11e8-9d31-eb30917d38d9.png)

**Comment by jaredscheib** [comment]
Thanks for reporting this, @karel-rehor. Could you share which version of Chronograf you're using?

Depending on the version, it's possible that a recent refactoring of template variables in the URL bar, to make them nested within a single URL query param key, _may_ have brought about changes to this functionality. See https://github.com/influxdata/chronograf/issues/3779 for more context.

**Comment by karel-rehor** [comment]
@jaredscheib  I just checked this again and the issue is still present in nightly build **201808030043 (git: ee8473a6...)**

```
$ chronograf --version
2018/08/03 14:51:58 Chronograf 1.4.3.0~n201808030043 (git: ee8473a62e10b09d17bd1a3bdbd533699d84cd2c)

```

**Comment by jaredscheib** [comment]
Thanks for the update, @karel-rehor.

cc @chnn @russorat – what karel is bringing up, sounds like a separate but related issue here that may have been broken with the recent temp vars url query param changes.

**Comment by karel-rehor** [comment]
In the current nightly build, `201811152152`, I see that pasting in the URL with the zoomed values now behaves as should be expected. 

```
$ chronograf --version
2018/11/28 16:16:16 Chronograf 201811152152~nightly (git: 590040153ccf513d477936404fed384033ddfdfb)
```

The issue mentioned Aug 1 is no longer encountered.
