### ISSUE TITLE
List of dashboards performance question

### ISSUE THREAD

**Issue by gianarb** [influxdata/chronograf#3602]
The average request per sec for 30 requests on chronograf api `/chronograf/v1/dashboards` takes `2.88 [#/sec]` so, from my experience it doesn't look cached in anyway and it can be an easy improvement to cache it in some place and probably also having a look about why the backend takes so long to look up them and if it is a reasonable amount of time for 25 dashboards (our current number)

```
$ ab -c 3 -n 30 http://chronograf.internal/chronograf/v1/dashboards
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking chronograf.internal (be patient).....done


Server Software:        
Server Hostname:        chronograf.internal
Server Port:            80

Document Path:          /chronograf/v1/dashboards
Document Length:        366343 bytes

Concurrency Level:      3
Time taken for tests:   10.426 seconds
Complete requests:      30
Failed requests:        0
Total transferred:      10993860 bytes
HTML transferred:       10990290 bytes
Requests per second:    2.88 [#/sec] (mean)
Time per request:       1042.626 [ms] (mean)
Time per request:       347.542 [ms] (mean, across all concurrent requests)
Transfer rate:          1029.73 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       82   89   9.1     86     124
Processing:   865  928  64.4    910    1117
Waiting:       94  101  13.9     97     164
Total:        951 1017  69.8    993    1242

Percentage of the requests served within a certain time (ms)
  50%    993
  66%   1014
  75%   1033
  80%   1052
  90%   1150
  95%   1155
  98%   1242
  99%   1242
 100%   1242 (longest request)
```

**Comment by jaredscheib** [comment]
Thanks @gianarb! Additionally, when even a single dashboard page loads, it _reloads_ **all dashboards** _again_. I wrote up an issue for solving this here: https://github.com/influxdata/chronograf/issues/3594.

**Comment by nhaugo** [comment]
@desa is this being addressed in the redesign of the dashboards api, i.e. a way to list the dashboards with the minimum amount of info needed for the UI.

**Comment by nhaugo** [comment]
Please see solution proposed in https://github.com/influxdata/chronograf/issues/3594

**Comment by jaredscheib** [comment]
#3594 proposes an API change, and it's possible that there are Bolt methods that would allow the Bolt query to take less time as well, such as by retrieving a particular field rather than an entire blob, though I'm not familiar with Bolt enough to say -- thoughts @desa?

**Comment by desa** [comment]
@gianarb would it be possible to get a copy of the chronograf database from the cluster? I'd like to use it to do some profiling.
