### ISSUE TITLE
When switching to dashboard that hasn't loaded before, loading state could be smoother

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3606]
I think the most conspicuous aspect is the Template Variable Manager text displaying momentarily. We could easily refactor that to not display that text until it confirms that there truly are no template variables, and otherwise is blank or says `Loading...`
![dashboard_loading](https://user-images.githubusercontent.com/6403018/41178899-a349e376-6b1d-11e8-954d-26935ec00afe.gif)

**Comment by gianarb** [comment]
I don't know if it can be helpful but I have NEVER realized until now that I am seeing this video about the fact that icon was clickable!

**Comment by jaredscheib** [comment]
good to know @gianarb -- thanks!

cc @alexpaxton
