### ISSUE TITLE
Add option to display separators in single stat

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3608]
- [ ] add an option to single stat, single stat + line, gauge to hide or show separators, similar to legend
- [x] this should use the user's browser locale, locale would not be changeable

**Comment by russorat** [comment]
We have a few different options here:

- option 1: enable locale formatting on all numbers. users will upgrade and start seeing separators in all their numbers (bad UX).
- option 2: allow the user to toggle on or off locale formatting. If your browser locale is `en-US` numbers will show 1,000.01 and if it's `es-ES` they will show 1.000,01. The user has no way to set the preferred locale (other than changing browser settings). (User can enable separators but has no control over how they are displayed in the app).
- option 3: add a way for the user to set their preferred locale in the app, add an option to use that locale to format numbers in each component. (we have no user settings page in the app today. many users don't know or care about their locale).

@josephxsxn are you ok with option 2?

**Comment by 121watts** [comment]
![screen shot 2018-07-05 at 4 33 44 pm](https://user-images.githubusercontent.com/7582765/42352769-63804e1a-8071-11e8-90b6-db14d99fcca9.png)

**Comment by russorat** [comment]
i don't really know how to test this. setting languages in my browser doesn't seem to do anything.

![image](https://user-images.githubusercontent.com/4805997/42588709-74f399e6-84f3-11e8-88de-db274eeed0e1.png)
