### ISSUE TITLE
Chronograf dashboard template parameter as URL

### ISSUE THREAD

**Issue by jaideepsinghPanwar** [influxdata/chronograf#3620]
We are using chronograf dashboard for showing custom graphs at runtime. For that we have used template variable so it take  value dynamically. But when we try to pass the template variable in URL it is not working.

[chronograf_dash.zip](https://github.com/influxdata/chronograf/files/2089025/chronograf_dash.zip)

**Comment by russorat** [comment]
this was fixed as part of #2934
