### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by nodejscss** [influxdata/chronograf#3621]
How can I put the chronograf dashboard or the panel  into a iframe tag like as grafana's share do?

<iframe src="http://10.10.10.112:3000/d-solo/i8lJlpIiz/sheng-wu-zhi-yao-han?orgId=1&panelId=2&from=1528696095997&to=1528717695997" width="450" height="200" frameborder="0"></iframe>

Please help me.

Thank you.

**Comment by russorat** [comment]
@nodejscss we don't have a supported way to embed chronograf dashboards into an iframe today. The feature request is on the backlog and you can follow it here https://github.com/influxdata/chronograf/issues/1654 . Also, this issue will allow deep links into dashboards which might help your use case: https://github.com/influxdata/chronograf/issues/2934

**Comment by jaredscheib** [comment]
You can also use Presentation mode, available via the URL query `?present=true`, with an embedded dashboard, on a remote page.

**Comment by nodejscss** [comment]
@russorat 
@jaredscheib 

I test the url param like : http://10.10.10.109:8888/sources/2/dashboards/1?present=true&autorefresh=every5s&timerange=past5m 

And the present=true param do work, but, the autorefresh and timerange param do NOT work.

How can I fix that?

Than you very much.

**Comment by jaredscheib** [comment]
@nodejscss This is not currently possible, but as @russorat mentioned you can track #1654 for progress on embedding refreshing graphs from Chronograf elsewhere.
