### ISSUE TITLE
Add ability to accept map type for template variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3627]
As part of template variables redesign, we are adding a map type, which will allow users to map an arbitrary list of key -> value pairs for template variables. We need to update the backend to support this type.

- [ ] Add the ability to select a Map type from the template variable type list
- [ ] Add the ability for a user to upload a CSV containing a list of values in the format:
```
key1,value1
key2,value2
key3,value3
```
- [ ] If the file is invalid and cannot be parsed, an error should be displayed to the user
- [ ] if there are duplicate key values, the user should be warned that n number of records had duplicate keys
- [ ] blank spaces should be ignored
- [ ] a preview of the data to be uploaded should be displayed and the user should be able to select a default value ( see #3635)

[template-variables-config--v5.pdf](https://github.com/influxdata/chronograf/files/2092143/template-variables-config--v5.pdf)

**Comment by russorat** [comment]
- [ ] break api work into story, check with goller

**Comment by chnn** [comment]
Blocked on #3639 (for CSV upload functionality)
