### ISSUE TITLE
Ability to add annotations endpoint to alert rule builder

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3628]
the alert rule builder should have an endpoint for adding annotations into influxdb. This would add an InfluxDBOut node to the script that is preconfigured to write data in the correct format for annotations.

**Comment by russorat** [comment]
blocked by #3650

**Comment by chnn** [comment]
Going to hold off on this for now while we consider more broadly how to display programmatically-generated annotations in the UI.

For reference, it's possible to write alerts as annotations visible in the UI today with the following snippet of TICKscript:

```
trigger
    |eval(
        lambda: "message",
        lambda: unixNano("time"),
        lambda: unixNano("time"),
        lambda: string(unixNano("time")) + '-' + string(mod(float(count()), 100000.0))
    )
        .as('text', 'start_time', 'modified_time_ns', 'id')
        .tags('id')
        .keep('text', 'start_time', 'modified_time_ns')
    |default()
        .field('deleted', FALSE)
    |influxDBOut()
        .database('chronograf')
        .retentionPolicy('autogen')
        .measurement('annotations')
```
