### ISSUE TITLE
SetState being called on unmounted FilterArgs

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/chronograf#3638]
`FilterArgs` state is being set after unmount.

<img width="1148" alt="screen shot 2018-06-11 at 5 01 22 pm" src="https://user-images.githubusercontent.com/4994741/41263087-8bbce932-6d99-11e8-85eb-2c87718c6a90.png">

When quickly hovering over a `filter` FuncNode in the builder a setState error is being logged for an associated unmounted `FilterArgs` component.

**Comment by lukevmorris** [comment]
I feel blamed

**Comment by russorat** [comment]
what's blocking this?
