### ISSUE TITLE
Cannot delete source in master

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3640]
![kapture 2018-06-11 at 18 02 08](https://user-images.githubusercontent.com/4805997/41264461-abd61d12-6da1-11e8-8ca0-0ce0c5868d16.gif)

**Comment by karel-rehor** [comment]
I've also come across this in latest nightly build:

```
$ chronograf --version
2018/06/13 14:47:13 Chronograf 1.5.0.0~n201806130027 (git: f68b39378f20197df69476d7a89098d040547fe3)
```
Adding a regression test to catch this in Selenium
