### ISSUE TITLE
Chronograf View

### ISSUE THREAD

**Issue by eohan01** [influxdata/chronograf#3641]
Could we have a button to either disable the Message filed in the Manage tasks view of Chronograf Alerts, or could you limit that to one line of text that gets cut off.   This field makes the panel only show a couple of rules per page because if the Message Field is large it wraps and limits the view.

We may end up with Hundreds of Alert Rules and to edit/change rules we have to scroll a lot just to get at the rule we want to change

**Comment by russorat** [comment]
@eohan01 thanks for opening this issue. we will take a look.
