### ISSUE TITLE
InfluxDB showing no longer available while db is running 

### ISSUE THREAD

**Issue by jiangli226** [influxdata/chronograf#3642]
![image](https://user-images.githubusercontent.com/947126/41301789-782d2fc8-6e9b-11e8-97cb-a5ec0c11a77d.png)

I have attached my debug log as below. I only installed InfluxDB and chronograf on my Windows Ubuntu. And started influxdb as "influxd -config /etc/influxdb/influxdb.conf" by root

![image](https://user-images.githubusercontent.com/947126/41302411-f7bf3258-6e9c-11e8-9c3e-e640850181c0.png)

I started my chronograf by running a root
chronograf --bolt-path=/root/chronograf-v1.db --log-level=debug

**Comment by jiangli226** [comment]
DEBU[0017] Request                                       component=server method=POST remote_addr=[::1]:49563 url=/chronograf/v1/sources/3/proxy
DEBU[0017] query                                         command=SHOW DATABASES component=proxy db= host=localhost:8086 rp=
ERRO[0017] Error message received status code 405 from server: err:   component=server http_status =400
INFO[0017] Response: Bad Request                         component=server method=POST remote_addr=[::1]:49563 response_time=1.456ms status=400
DEBU[0017] Request                                       component=server method=POST remote_addr=[::1]:49563 url=/chronograf/v1/sources/3/proxy
DEBU[0017] query                                         command=SHOW DATABASES component=proxy db= host=localhost:8086 rp=
ERRO[0017] Error message received status code 405 from server: err:   component=server http_status =400
INFO[0017] Response: Bad Request                         component=server method=POST remote_addr=[::1]:49563 response_time=1.174ms status=400
DEBU[0017] Request                                       component=server method=POST remote_addr=[::1]:49563 url=/chronograf/v1/sources/3/proxy
DEBU[0017] query                                         command=SHOW DATABASES component=proxy db= host=localhost:8086 rp=
ERRO[0017] Error message received status code 405 from server: err:   component=server http_status =400
INFO[0017] Response: Bad Request                         component=server method=POST remote_addr=[::1]:49563 response_time=1.25ms status=400
DEBU[0017] Request                                       component=server method=POST remote_addr=[::1]:49563 url=/chronograf/v1/sources/3/proxy
DEBU[0017] query                                         command=SHOW DATABASES component=proxy db= host=localhost:8086 rp=
ERRO[0017] Error message received status code 405 from server: err:   component=server http_status =400
INFO[0017] Response: Bad Request                         component=server method=POST remote_addr=[::1]:49563 response_time=1.874ms status=400
DEBU[0017] Request                                       component=server method=GET remote_addr=[::1]:49563 url=/chronograf/v1/sources
INFO[0017] Response: OK                                  component=server method=GET remote_addr=[::1]:49563 response_time=278µs status=200
DEBU[0017] Request                                       component=server method=GET remote_addr=[::1]:49563 url=/chronograf/v1/sources
INFO[0017] Response: OK                                  component=server method=GET remote_addr=[::1]:49563 response_time=251µs status=200
DEBU[0017] Request                                       component=server method=GET remote_addr=[::1]:49563 url=/chronograf/v1/sources
INFO[0017] Response: OK                                  component=server method=GET remote_addr=[::1]:49563 response_time=672µs status=200
DEBU[0017] Request                                       component=server method=GET remote_addr=[::1]:49563 url=/chronograf/v1/sources
INFO[0017] Response: OK                                  component=server method=GET remote_addr=[::1]:49563 response_time=753µs status=200
DEBU[0017] Request                                       component=server method=POST remote_addr=[::1]:49563 url=/chronograf/v1/sources/3/proxy
DEBU[0017] query                                         command=SHOW DATABASES component=proxy db= host=localhost:8086 rp=
ERRO[0017] Error message received status code 405 from server: err:   component=server http_status =400
INFO[0017] Response: Bad Request                         component=server method=POST remote_addr=[::1]:49563 response_time=1.477ms status=400

**Comment by jiangli226** [comment]
Issue fixed after upgrading all the packages. This seems to be a bug in old influxDB

**Comment by thiagosm89** [comment]
I'm having the same problem. Can you help me?

It is my docker-compose.yml:

`version: '2'
services:
  influx:
    image: influxdb:latest
    hostname: influx
    ports:
      - "8000:80"
      - "8083:8083"
      - "8006:8006"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influx
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influx
    environment:
      - INFLUXDB_URL=http://influx:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}


networks:
  metrics:
    driver: bridge

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
`
![image](https://user-images.githubusercontent.com/8418871/111540768-52b93380-874e-11eb-8093-102a09cb165c.png)

**Comment by Waynedejager1** [comment]
I am having the same issue now in 2021 - i see this thread seems closed so not sure my post here will achieve anything ?
I ma running chronograph version 1.8.0 
Any suggestions or help please?

**Comment by GFLEMING133** [comment]
Same problem -- any ideas here? Even which service in the background is failing so I can go troubleshoot with at least somewhere to start?

**Comment by jGsch** [comment]
You have to be sure that chronograph is asking on the http port of influxdb (not on the bind adress) like here :

```bash
  influxdb-beta:
    image: influxdb:1.8
    ports:
      - ${INFLUXDB_PORT_BETA}:${INFLUXDB_PORT_BETA}
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME_BETA}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD_BETA}
      - INFLUXDB_BIND_ADDRESS=127.0.0.1:${INFLUXDB_PORT_BETA}
      - INFLUXDB_HTTP_BIND_ADDRESS=:${INFLUXDB_HTTP_PORT_BETA}

  chronograf-beta:
    image: chronograf:${CHRONOGRAPH_IMG_TAG}
    ports:
      - ${CHRONOGRAPH_PORT_BETA}:${CHRONOGRAPH_PORT_BETA}
    depends_on:
      - influxdb-beta
    environment:
      - INFLUXDB_URL=http://influxdb-beta:${INFLUXDB_HTTP_PORT_BETA}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME_BETA}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD_BETA}
      - PORT=${CHRONOGRAPH_PORT_BETA}
  ```
