### ISSUE TITLE
Fill, compare and group by time are not accessible when schema explorer can not parse the query

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#3643]
In both the data explorer and the dashboard cell editor build the query by using the query builder ui:

`SELECT mean("usage_user") AS "mean_usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: GROUP BY time(:interval:) FILL(null)`

Manually convert it to:
`SELECT non_negative_derivative(max("usage_user"), 1s) AS "mean_usage_user" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: GROUP BY time(:interval:) FILL(null)` 

Controls for fill, group by and compare to disappear

As a bonus if you ^Z the query back to the original the controls do you show up until you press enter

**Comment by russorat** [comment]
probably a side effect of #3176
