### ISSUE TITLE
Many graphs and icons not showing up in chronograf nightly

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3644]
(Nightly on June 12th)

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/1922921/41305328-37bc02c4-6e38-11e8-92d9-1505b5404ed6.png">

<img width="931" alt="image" src="https://user-images.githubusercontent.com/1922921/41305392-67308f5c-6e38-11e8-9704-17d338a73f86.png">

**Comment by russorat** [comment]
i believe this has been addressed in the latest nightly.
