### ISSUE TITLE
Update annotations api to include template variable scopes

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3650]
As part of https://github.com/influxdata/chronograf/issues/3143, we want to scope annotations to the template variables that are selected on the dashboard. This would enable a team to add an annotation to a specific host or service instead of global.

as part of this, we will need to update the annotations api to support the additional data storage. This issue is to cover that design and update for the API.

**Comment by russorat** [comment]
- [ ] the dashboard should be able to make a single request to return global and scoped annotations
- [ ] the dashboards should be able to request only global annotations or only scoped annotations (a user may want to disable global annotations)
- [ ] by default, the api should return only global variables (don't change existing behavior)

**Comment by chnn** [comment]
Closing in favor of #3905
