### ISSUE TITLE
Zooming in far enough to return no results in a dygraph is difficult to recover from. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#3677]
There is a point one can zoom in far enough in a dygraph that there are no points in the interval one is querying, and the graph displays no results. The problem is that this state is very difficult to recover from. Double click to zoom out is not available, Refreshing does not work because the zoomed time range parameters are in the url, and the time range dropdown no longer works. The only way to return the getting results is to edit the url, and refresh. 
![kapture 2018-06-14 at 11 04 06](https://user-images.githubusercontent.com/10937678/41429832-18beef6c-6fc3-11e8-8e91-51a8ffa7e5bb.gif)

**Comment by karel-rehor** [comment]
I've encountered this while preparing annotation tests... 
```
$ chronograf --version
2018/07/10 08:18:35 Chronograf 1.4.3.0~n201807100044 (git: 4f2378a8a0147a1187d86fd78747ade306663f8d)
```
A user could fall into this situation with a stray mouse action.
