### ISSUE TITLE
Flux Editor: Cannot collapse implicit yield 

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3681]
I'm not sure why, but i can't disable the implicit yield when map is the final function.

![kapture 2018-06-14 at 14 03 56](https://user-images.githubusercontent.com/4805997/41438350-d93e9d7e-6fdb-11e8-969a-4703e9a5e737.gif)

**Comment by OfTheDelmer** [comment]
I tried a similar query with a `filter` before the range and it does toggle. I'll review `ExpressionNode` rendering conditions to see what's up. We do special handling when func nodes are clicked that don't have both a filter and range before them in the expression.
