### ISSUE TITLE
Add the ability to insert functions in the builder between existing functions

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3682]
- [ ] Provide a way for the user to insert a function between two other functions in the builder

<img width="598" alt="screen shot 2018-06-14 at 1 17 17 pm" src="https://user-images.githubusercontent.com/4805997/41439229-df54688a-6fde-11e8-812b-30f979754fe2.png">

**Comment by alexpaxton** [comment]
I have a design in mind for this

**Comment by russorat** [comment]
@alexpaxton please add your mock to this
