### ISSUE TITLE
Problems with basepath on 1.5.0.1

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/chronograf#3687]
Hello,

I'm having two problems with basepath after upgrading to 1.5.0.1. Previously I was using 1.4.4 without issue in this regard.

Problem 1: basepath "/whatever/chronograf-something" is considered invalid and service does not start.

Problem 2: basepath "/whatever/chronograf" service starts, but can't access it properly, just get "404 page not found".

I'm using CentOS 7 with systemd, basepath set via BASE_PATH in an EnvironmentFile.

Thanks

**Comment by russorat** [comment]
@voiprodrigo thanks for the issue. Just to clarify, you've set your basepath to be `BASE_PATH=/whatever/chronograf-something`?

**Comment by voiprodrigo** [comment]
To be exact: BASE_PATH="/whatever/chronograf-something"

**Comment by voiprodrigo** [comment]
I reverted to 1.4.4 and both cases work fine again.

Please also see comments in https://github.com/influxdata/chronograf/commit/2ce7d8e3eea9e2319271df34118647bf3826186f#diff-91bbeda7eb98a7adc57b9e47e2cf5c2b

**Comment by russorat** [comment]
thanks for the link. I connected this issue and your comment so we can review.

**Comment by jaredscheib** [comment]
This was changed in 1.5.0, but we revert that aspect to make it so that hyphens or any valid URL path will work.

**Comment by voiprodrigo** [comment]
(Sorry to comment on closed issue) 

Thanks for addressing the hyphen situation, but regarding this:

> Problem 2: basepath "/whatever/chronograf" service starts, but can't access it properly, just get "404 page not found".

Any hints? I assume it's a different root-cause, as the behaviour is different. 

Thanks.

**Comment by voiprodrigo** [comment]
I managed to get it working again. But this seems to be an unexpected change in basepath handling.
I have an Apache in front of chronograf. If the ProxyPass is set to http://localhost:8888, it fails with 404 (it worked  before). I changed the ProxyPass to forward to http://localhost:8888/<basepath>, and now it's ok.

**Comment by russorat** [comment]
@voiprodrigo i'm not sure i understand completely. 

The expected behavior is that when basepath is enabled, accessing just the standard localhost:8888 should return a 404. accessing localhost:888/basepath should work. I'm not familair with ProxyPass specificially, but if forwarding to just localhost:8888 was working before, it was unintentional and incorrect. Forwarding to /basepath is the correct solution.
