### ISSUE TITLE
Is there way to access google oauth secured chronograf API with script.

### ISSUE THREAD

**Issue by Tejeshna** [influxdata/chronograf#3688]
Hi , 
I'm basically trying to automate creation of dashboard for our micro services using a script ,Created a user in chronograf and used it's credentials to login but din't succeed . Any help would be appreciated.

**Comment by russorat** [comment]
@Tejeshna thanks for the issue. When you say "automate creation", do you mean automatically importing a pre-defined dashboard? Here are some comments to help with that: https://github.com/influxdata/chronograf/issues/2659#issuecomment-354164604

in the next version of chronograf, we will have buttons in the UI to export and import dashboards. it's already in the nightly if you want to try it out? #3488

**Comment by Tejeshna** [comment]
Hi @russorat , I need to create dashboard from script using chronograf API  instead of creating from chronograf UI.  Basically i need automate creation of dashboard.
