### ISSUE TITLE
Problem connecting to influxdb

### ISSUE THREAD

**Issue by FloriHe** [influxdata/chronograf#3695]
Hello,
I'm having a problem connectimg to my source (influxdb) via chronograf. I'm having chronograf_1.3.0 and influxdb 0.10.0+dfsg1-1 installed, both services are running on my remote vm. I can connect to my chornograf dashboard via `http://{public-ip}:8888` . But when I try to connect to my influxdb source with the settings `localhost:8086, InfluxDB, telegraf` I always get the error: `Unable to connect to source`. The command:

    chronograf --log-level=debug

gives

    ERRO[0000] listen tcp 0.0.0.0:8888: bind: address already in use  component=server
    2018/06/15 23:28:22 listen tcp 0.0.0.0:8888: bind: address already in use

I can wipe out the listening on 8888 by restarting the service and even also restart influxdb, but nothing changes. Any ideas?

**Solved:**
I made a mistake during the installation of influxdb

**Comment by nocibambi** [comment]
@FloriHe I have the same issue. Maybe do you remember of how did you solve it? :wink:
