### ISSUE TITLE
Add the ability to configure colors and display for log level

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3713]
as a user, i would like to be able to customize the colors and display for the log level.

- [x] allow the user to map log levels to colors (crit -> green, warn -> yellow, etc)
- [x] allow the user to customize the log level display. Allow dot only, dot + text, text only options. - this was completed by #3815 

these colors should also be used for the histogram display #3511 

hovering over the dot should display a tooltip with the name of the level.

stored in the boltdb per org
anyone with editor permissions can make this change

**Comment by alexpaxton** [comment]
![config-severity-colors](https://user-images.githubusercontent.com/2433762/41678315-99b1310a-747f-11e8-9e93-6836efb23a37.gif)

Here's my WIP UI for this story. I have it on a branch called `logs-viewer/options-overlay`. I have built out some of the UI in favor of using mockups here in the interest of speed. A dev can pick up the branch and replace my mock data with data from the server

**Comment by alexpaxton** [comment]
![severity-colors-saving-ux](https://user-images.githubusercontent.com/2433762/41735444-90f79c6a-753e-11e8-9c19-e14476f4af94.gif)

I have the UI & design for this feature in a good place, just needs to be "plugged in" to the backend

**Comment by ischolten** [comment]
Blocked on #3777. Need to know the schema of the data from the backend.
