### ISSUE TITLE
Add the ability to reorder the columns in the log viewer

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3714]
as a user, i would like the ability to configure the location of the columns in the log viewer.

- [x] allow the user to reorder the columns in the log viewer
- [x] allow the user to hide or show columns
- [x] allow the user to rename the columns in the log viewer
- [x] anyone with editing permissions should be allowed to update
- [x] severity should be one column with formatting based off of severityFormat
- [x] allow filtering on severity, regardless of format

by #3766 these settings should persist after refresh.
store in the boltdb per org

**Comment by ischolten** [comment]
Blocked on #3777. Need to know the schema of the data from the backend.
