### ISSUE TITLE
Add the ability to use Flux to build a dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3717]
When the user is creating a new cell, and they have added Fluxd as a connection in Chronograf, they should have the option to select that source in the CEO. once selected, the user should see an updated query editor which allows them to build Flux queries. the visualization options should be limited to just line or table, much like we show today in the yield UI.

this means that we need a way for the user to add fluxd as a source (not connected to an influx source).
We will also need to disable things like annotations on this graph type

**Comment by nathanielc** [comment]
Curious why we would need to disable annotations for Flux graphs? Are annotations somehow tied to the data source?

**Comment by russorat** [comment]
@nathanielc yes, annotations are written to the chronograf db for that data source.

**Comment by russorat** [comment]
multiple yields issue: https://github.com/influxdata/platform/issues/281

**Comment by alexpaxton** [comment]
![screen shot 2018-06-20 at 12 05 54 pm](https://user-images.githubusercontent.com/2433762/42851501-e5462928-89e1-11e8-894c-6b6a6cec98bf.png)

- Ignore the `Flux | InfluxQL` toggle
- Check the source for the cell and if that source has Flux as a service then display a 3 column Flux builder in place of the regular query builder
- 3 columns would be `Explore | Build | Script`
- Limit the builder to only allow a single query (might be referred to as a `body` or `expression`)
- The query can have any number of yields

**Comment by ischolten** [comment]
- [ ] ability to select the source and flux connection on the flux builder page
