### ISSUE TITLE
Single Stat: The value from 2nd query in the color of the first query

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3748]
This is a single stat with multiple queries. The value from the purple line is being displayed in green. The color of the text should match the color of the line it is being pulled from.

![image](https://user-images.githubusercontent.com/4805997/41736731-333b7ebc-7542-11e8-8eb3-913fbec0aa9a.png)

**Comment by alexpaxton** [comment]
We could go a step further and let the user choose which series to assign to the single stat
