### ISSUE TITLE
Incorrectly combining conditionals

### ISSUE THREAD

**Issue by bengerman13** [influxdata/chronograf#3752]
I'm running the official Chronograf docker image tagged 1.4.1, image ID ce2a487f24e2
I created a query for a visualization on a dashboard:
```
SELECT mean("used_percent") AS "mean_used_percent" FROM "telegraf"."autogen"."disk" WHERE time > :dashboardTime: AND "fstype"!='nfs' AND "fstype"!='nfs4' GROUP BY :interval:, "device", "host" FILL(null)
```
Whenever I reload the page, Chronograf 'corrects' this to
```
SELECT mean("used_percent") AS "mean_used_percent" FROM "telegraf"."autogen"."disk" WHERE time > :dashboardTime: AND ("fstype"!='nfs' OR "fstype"!='nfs4') GROUP BY :interval:, "device", "host" FILL(null)
```
It looks like Chronograf is attempting to simplify  `"fstype"!='nfs' AND "fstype"!='nfs4'`, but replacing it with `("fstype"!='nfs' OR "fstype"!='nfs4')` is incorrect.

**Comment by russorat** [comment]
@bengerman13 i agree, this isn't working as expected. While we address the issue, you can adjust your query to be `"fstype" !~ /^nfs$|^nfs4$/` as a workaround.

**Comment by bengerman13** [comment]
Thanks @russorat !
