### ISSUE TITLE
Enhance BRBot to not be random

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3757]
- [ ] brbot should use a round robin algorithm to assign PRs

**Comment by jaredscheib** [comment]
- [ ] generate random order list from
- [ ] respond to @brbot with next name from that list
- [ ] cycle through list; and once complete, generate new random order

nice-to-have ideas:
- [ ] brbot can be instructed to skip a person, who will be added to end of list
- [ ] if a person is skipped twice, they'll be considered out for the cycle
- [ ] brbot will report when a cycle is complete, and that a new cycle is beginning

**Comment by russorat** [comment]
https://github.com/rawlbot/slack-bot
