### ISSUE TITLE
Option in Alert Rule Builder to build alerts that send periodic alerts until state is changed

### ISSUE THREAD

**Issue by akhillb** [influxdata/chronograf#3760]
Is it possible to create a rule using the Alert Rule Builder which keeps sending me alerts until the state is changed? I created a basic rule to send alerts for disk usage crossing a certain threshold, but it sends the alert when it reaches critical and there are no alerts until the alert is fixed. The workaround I followed was to edit the tick script to remove `stateChangesOnly()` from the TICK script and add a `window` node in order to get the alerts for a certain period. Is there an option to do this from the Alert builder itself?

**Comment by russorat** [comment]
@akhillb there is no way to do this in the alert rule today. I will leave this open as a feature request.

**Comment by sawo1337** [comment]
Can someone provide a way to change the default rule template so this can be included by default until implemented on the live release? I think this would be a matter of just a single line of code added to the default rule template?

**Comment by russorat** [comment]
@sawo1337 i think you just want to remove this line: https://github.com/influxdata/chronograf/blob/9d8a49ba0ef8131cdce22d73718859f55f434db2/kapacitor/triggers.go#L118
