### ISSUE TITLE
Chronograf keeps querying old sources when switching sources

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3763]
If a user is switching between different sources, and they have a refresh interval selected, there are still requests pending from the previous source, then those requests continue to be made when a new source is selected. 

This can result in many extra calls to a previous source. Somewhere in the app, we are not cancelling requests properly leading to us making requests to sources that are no longer selected.

So in the gif below, you can see that when I start, i am connected to source 2. Then I switch to source 4, and then to a dashboard where the cells are only calling source 4, but the requests from source 2 are still pending (and blocking source 4 requests), and the app is still making new requests to source 2.

The expected behavior would be that as soon as I switch sources, any existing requests to the previous source are cancelled, and only requests to the new source are made (unless the dashboard contains references to the old source).

![kapture 2018-06-25 at 11 57 13](https://user-images.githubusercontent.com/4805997/41869912-5e9f407c-786f-11e8-8f54-7ca03b41869c.gif)

**Comment by russorat** [comment]
this might be a setInterval issue

**Comment by ischolten** [comment]
The portion of this issue related to aborting no longer relevant requests would be addressed by #3686
