### ISSUE TITLE
Breaking change in Github OAuth from 1.4.2.5

### ISSUE THREAD

**Issue by ar7z1** [influxdata/chronograf#3772]
I use chronograf with Github OAuth.

I've upgraded from chronograf v1.4.2.3 to the latest version (1.5.0.1) and could not login.
After several hours of debugging, I've finally found the problem. :-)

To reproduce the issue you need chronograf v1.4.2.3 or earlier and two verified emails in your github account. For example, `bbb@example.com` and `zzz@example.com` (primary).

When you login into chronograf v1.4.2.3 via github, chronograf will use `bbb@gmail.com` as email because of [this implementation](https://github.com/influxdata/chronograf/commit/01c2a1ee93897a801485062693d1fbce58dfe063#diff-f24ed568889f7e6fe59c54b6448fac29R194):
```
func primaryEmail(emails []*github.UserEmail) (string, error) {
 	for _, m := range emails {
		if m != nil && m.Primary != nil && m.Verified != nil && m.Email != nil {
 			return *m.Email, nil
 		}
 	}
	return "", errors.New("No primary email address")
}
```
`bbb@example.com` - is the first email with `m.Primary != nil && m.Verified != nil` (`primary` is false but `!= nil`). 

User list in chronograf contained only `bbb@example.com` user and everything worked.

When I've upgraded chronograf, the `primaryEmail` function [changed](https://github.com/influxdata/chronograf/pull/3168/files?utf8=%E2%9C%93&diff=unified#diff-aa8dd2cb8f097cac2fafa435fa5f5c6bR178):
```
func primaryEmail(emails []*github.UserEmail) (string, error) {
 	for _, m := range emails {
		if m != nil && getPrimary(m) && getVerified(m) && m.Email != nil {
 			return *m.Email, nil
 		}
 	}
	return "", errors.New("No primary email address")
}

func getPrimary(m *github.UserEmail) bool {
	if m == nil || m.Primary == nil {
		return false
	}
	return *m.Primary
}
...
```

Chronograf now selects `zzz@example.com` (primary email). But this email doesn't exist in the list of users and it is not allowed to access.

**Comment by ar7z1** [comment]
I think we can close this issue because `primaryEmail` now works correctly but this issue can help to save some debugging time for others.

**Comment by russorat** [comment]
@ar7z1 thanks! see this PR for more information about this change: https://github.com/influxdata/chronograf/pull/3389

**Comment by ar7z1** [comment]
@russorat thanks! I've already seen #3389, but my issue is different. :-)
