### ISSUE TITLE
Chronograf Admin page doesn't render

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3774]
On the `logs-viewer/options-overlay` branch, enable auth and then try to visit the Chronograf Admin page:
<img width="1440" alt="screen shot 2018-06-26 at 1 55 23 pm" src="https://user-images.githubusercontent.com/6403018/41938718-a66f4940-7948-11e8-8c3b-eaa71c5ef23b.png">

**Comment by 121watts** [comment]
@alexpaxton i think this might have something do to with you bud

**Comment by alexpaxton** [comment]
that branch needs a rebase, I believe this issue is fixed in master

**Comment by jaredscheib** [comment]
@thachnv92 What version or SHA of Chronograf are you using / building from? And are there any circumstances that seem to give rise to this? I'm able to run the server with auth and visit the Chronograf Admin page successfully when building from the head of `master`.
