### ISSUE TITLE
Create integration tests for template variables synced with URL query params

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3779]
Integration tests are needed to prevent regression of features introduced in #3556:

### URL synced from UI
1. When a user creates a new dashboard, the default dashboard time range should appear as a URL query param, e.g. `http://localhost:8888/sources/4/dashboards/11?lower=now%28%29+-+15m`
1. When a user changes the time range of a dashboard to any possible relative time, the URL query param should update accordingly to match the newly selected time range value, e.g. `?lower=now%28%29+-+5m`, `?lower=now%28%29+-+6h`, etc.
1. When a user changes the time range of a dashboard to an absolute time from relative, the URL query params should update accordingly to match the newly selected time range values (with both `lower` and `upper` URL query params
1. When a user changes the time range of a dashboard to a different absolute time from another absolute time, the URL query params should update accordingly to match the newly selected time range values
1. When a user changes the time range of a dashboard to a relative time from an absolute time, the URL query params should update accordingly to match the newly selected time range value, e.g. only the new `lower` value should remain, and not `upper` anymore
1. When a user clicks to zoom into a narrower time range on a graph, the URL query params for `zoomedUpper` and `zoomedLower` should appear
1. While a zoomed time range is already selected and already present in the URL query params, selecting a new zoomed time range should update the URL query params for `zoomedUpper` and `zoomedLower` to the new values

### overrides with valid values
1. When a dashboard is loaded with URL query param override values for a relative value (just `lower`) that is not currently selected, the dashboard's selected time should reflect this new value and the dashboard should load according to that time range
1. When a dashboard is loaded with URL query param override values for an absolute value for dashboard time range (`lower` and `upper`) that is not currently selected, the dashboard's selected time should reflect this new value and the dashboard should load according to that time range
1. When a dashboard is loaded with URL query param override values for an absolute value for dashboard _zoomed_ time range (`zoomedLower` and `zoomedUpper`), the dashboard's selected time should reflect this new value and the dashboard should load according to that zoomed time range

### overrides with invalid values
1. When a dashboard is loaded with a relative time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to use the default time range value for that dashboard
1. When a dashboard is loaded with an absolute time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to use the default time range value for that dashboard
1. When a dashboard is loaded with an absolute _zoomed_ time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to remove that invalid _zoomed_ time range

## template variables
1. When a user adds a new template variable to a dashboard, it should appear as a URL query param in the format `tempVarKey=currentTempVarValueSelected`
1. When a user changes the selected value for a template variable on a dashboard, the URL query param key-value pair for that tempVar should be overwritten accordingly
1. When a user who loads a dashboard with URL query param values for tempVar values that are valid but not currently selected, the currently selected template variable values should be updated and the dashboard should load with those updated selections
1. When a user who loads a dashboard with URL query param values for tempVar values that are invalid (don't exist in that template variable's values), an error notification should appear, and the dashboard should load with its currently selected value for those template variables, and the URL query params should be overwritten to reflect the valid, current selection

## unrelated URL query params
1. any URL query param that is not `upper`, `lower`, `zoomedUpper`, `zoomedLower`, or any current template variable value, should remain intact and unaffected by all of the changes above

**Comment by OfTheDelmer** [comment]
We recently resolved an issue in #3847 where navigating to a dashboard and replacing the dashboard URL with one including synced query params caused a `404`. 

Integration tests for syncing URL query params should include scenarios where base path is set is the env. 

When an admin exports a base path environment variable,

```shell
export BASE_PATH="/basepath"
```

and a user navigate to a dashboard like  `http://localhost:8888/basepath/sources/4/dashboards/11` the expected behavior would sync the URL in the [manner outlined above](https://github.com/influxdata/chronograf/issues/3779#issue-336052548) with a pathname prefixed with the provided `BASE_PATH` env var value.

**Comment by jaredscheib** [comment]
cc @karel-rehor ^^ -- thanks!

**Comment by jaredscheib** [comment]
Additionally, @chnn recently introduced a breaking change to the shape of URL query param that will need to be considered in these tests.

For @karel-rehor to write these integration tests correctly, would you mind @chnn sharing:
1) what was changed;
2) what format can now be expected of temp vars vs time ranges;
3) as of which version of Chronograf this has become the case?

**Comment by jaredscheib** [comment]
Thanks! :)

**Comment by karel-rehor** [comment]
# Coverage of Dashboard URLs concerns - 3779

I've copied the original summary and added notes about where each point should be covered in the jbehave story.  

The JBehave story tests for dashboard urls can be found at [github](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story).



# Original request follows with notes of where issue is covered

Integration tests are needed to prevent regression of features introduced in #3556:


## time range

### URL synced from UI
1. When a user creates a new dashboard, the default dashboard time range should appear as a URL query param, e.g. `http://localhost:8888/sources/4/dashboards/11?lower=now%28%29+-+15m`
   * &#x2714; [_dashboard_urls.story:line 20 - Scenario: verify url for default dashboard_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L20-L23)
1. When a user changes the time range of a dashboard to any possible relative time, the URL query param should update accordingly to match the newly selected time range value, e.g. `?lower=now%28%29+-+5m`, `?lower=now%28%29+-+6h`, etc.
   * &#x2714; [_dashboard_urls.story:line  25 - Scenario: verify url for relative time_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L25-L31)
1. When a user changes the time range of a dashboard to an absolute time from relative, the URL query params should update accordingly to match the newly selected time range values (with both `lower` and `upper` URL query params
   * &#x2714; [_dahsboard_urls.story:line 33 - Scenario: verify url for absolute time_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L33-L42)
1. When a user changes the time range of a dashboard to a different absolute time from another absolute time, the URL query params should update accordingly to match the newly selected time range values
   * &#x2714; [_dashboard_urls.story: line 44 - Scenario: verify url after readjust absolute time_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L44-L53)
1. When a user changes the time range of a dashboard to a relative time from an absolute time, the URL query params should update accordingly to match the newly selected time range value, e.g. only the new `lower` value should remain, and not `upper` anymore
   * &#x2714;[_dashboard_urls.story:line 72 - Scenario: verify url after change from absolute time to relative time_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L72-L79)
1. When a user clicks to zoom into a narrower time range on a graph, the URL query params for `zoomedUpper` and `zoomedLower` should appear
   * &#x2714;[_dashboard_urls.story: line 55 - Scenario: verify url after zoom_ - *Currently Enabled*](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L55-L61)
1. While a zoomed time range is already selected and already present in the URL query params, selecting a new zoomed time range should update the URL query params for `zoomedUpper` and `zoomedLower` to the new values
   * &#x2714;[_dashboard_urls.story:line 63 - Scenario: verify url params after second zoom_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L63-L70)

### overrides with valid values
1. When a dashboard is loaded with URL query param override values for a relative value (just `lower`) that is not currently selected, the dashboard's selected time should reflect this new value and the dashboard should load according to that time range
   * &#x2714; [_dashboard_urls.story:line 83 - Scenario: Dashboard URL relative time change last hour,](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L81-L90)
   * &#x2714; [line 92 - Scenario: Dashboard URL relative time change last day_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L92-L101)
1. When a dashboard is loaded with URL query param override values for an absolute value for dashboard time range (`lower` and `upper`) that is not currently selected, the dashboard's selected time should reflect this new value and the dashboard should load according to that time range
   * &#x2714; [_dashboard_urls.story: line 112 - Dashboard URL relative time change last month, dashboard_urls.story:](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L112-L120)
   * &#x2714; [line 122 - Dashboard URL absolute between three and two weeks ago_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L122-L131)
1. When a dashboard is loaded with URL query param override values for an absolute value for dashboard _zoomed_ time range (`zoomedLower` and `zoomedUpper`), the dashboard's selected time should reflect this new value and the dashboard should load according to that zoomed time range
   * &#x2714; [_dashboard_urls.story: line 133 - Dashboard URL absolute with zoom between 18 and 16 days ago](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L133-L139)
   * &#x2714; [line 141 - Dashboard URL unzoom](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L141-L149)

### overrides with invalid values
1. When a dashboard is loaded with a relative time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to use the default time range value for that dashboard
   * &#x2714; [_dashboard_urls.story:line 103 - Scenario: Dashboard URL relative time invalid_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L103-L110)
1. When a dashboard is loaded with an absolute time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to use the default time range value for that dashboard
   * &#x2714; [_dashboard_urls.story:line 151 - Scenario: Dashboard URL with invalid absolute value,](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L151-L157)
   * &#x2714; [line 159 - Scenario: Dashboard URL with lower later than upper_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L159-L163)
1. When a dashboard is loaded with an absolute _zoomed_ time range that is not valid, an error notification should be displayed to the user that they entered an invalid value, and the URL query params should be overwritten to remove that invalid _zoomed_ time range
   * &#x2714;[_dashboard_urls.story:line 165 - Scenario: Dashboard URL with invalid zoom values_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L165-L171)

## template variables
1. When a user adds a new template variable to a dashboard, it should appear as a URL query param in the format `tempVarKey=currentTempVarValueSelected`
   * &#x2714;[ _dashboard_urls.story:line 231 - Scenario: verify url contains template variable_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L205-L234)
1. When a user changes the selected value for a template variable on a dashboard, the URL query param key-value pair for that tempVar should be overwritten accordingly
   * &#x2714;[ _dashboard_urls.story:line 236 - Scenario: verify template variable parameter is updated_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L236-L241)
1. When a user who loads a dashboard with URL query param values for tempVar values that are valid but not currently selected, the currently selected template variable values should be updated and the dashboard should load with those updated selections
   * &#x2714; [_dashboard_urls.story:line 253 - Scenario: Dashboard URL with Variable_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L253-L260)
1. When a user who loads a dashboard with URL query param values for tempVar values that are invalid (don't exist in that template variable's values), an error notification should appear, and the dashboard should load with its currently selected value for those template variables, and the URL query params should be overwritten to reflect the valid, current selection
   * &#x2714; [_dashboard_urls.story:line 255 - Scenario: verify failover with bad template variable_](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L243-L251)

## unrelated URL query params
1. any URL query param that is not `upper`, `lower`, `zoomedUpper`, `zoomedLower`, or any current template variable value, should remain intact and unaffected by all of the changes above
   * &#x2714; [_dashboard_urls.story:line 183 - Extra Params](https://github.com/influxdata/bonitoo-selenium/blob/85e060094515134ef320955d054f21ba283605f7/src/test/resources/stories/dashboards/manage_dashboards/dashboard_urls.story#L181-L203)
