### ISSUE TITLE
Chronograf still displaying host in "host list" when deleted from Influxdb

### ISSUE THREAD

**Issue by carlessanagustin** [influxdata/chronograf#3780]
__System info:__

```shell
# influxd version
InfluxDB v1.5.3 (git: 1.5 89e084a80fb1e0bf5e7d38038e3367f821fdf3d7)
# influx --version
InfluxDB shell version: 1.5.3
```

```shell
# chronograf -v
2018/06/27 14:16:57 Chronograf 1.5.0.1 (git: 4a97c338e67324f974b978c27f47cdbfe7800fba)
```

__Expected behavior:__

* In influx CLI

```sql
USE telegraf
SHOW SERIES WHERE "host" = 'this-is-not-ok-host' >> does list results(CORRECT)
DROP SERIES WHERE "host" = 'this-is-not-ok-host'
SHOW SERIES WHERE "host" = 'this-is-not-ok-host' >> does NOT list results(CORRECT)
```

* Browsing: `http://<domain name>/chronograf/sources/0/hosts`
NO host this-is-not-ok-host in list >> **CORRECT**

__Actual behavior:__

* In influx CLI

```sql
USE telegraf
SHOW SERIES WHERE "host" = 'this-is-not-ok-host' >> does list results(CORRECT)
DROP SERIES WHERE "host" = 'this-is-not-ok-host'
SHOW SERIES WHERE "host" = 'this-is-not-ok-host' >> does NOT list results(CORRECT)
```

* Browsing: `http://<domain name>/chronograf/sources/0/hosts`
Host keeps appearing in list >> **INCORRECT**

* Browsing: `http://<domain name>/chronograf/sources/0/hosts/this-is-not-ok-host`
No data >> **CORRECT**

__Additional info:__

1. After forcing Chronograf restart and its database recreation (`/var/lib/chronograf/chronograf-v1.db`) problem still persist.
2. Restarting Influxdb service solves the problem (any flush option available?)
3. RELATED ISSUE: https://github.com/influxdata/influxdb/issues/9985

**Comment by russorat** [comment]
@carlessanagustin thanks for opening this. See my comment in the related issue. I'll leave this open for now until we figure out what's going on.

**Comment by russorat** [comment]
follow https://github.com/influxdata/influxdb/issues/9985 for resolution
