### ISSUE TITLE
Data explorer crashes if the chronograf cannot connect to the selected source

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#3787]
Reproduction 
• Create a source
• Change the username/password to be invalid
• Go to data explorer
• Notice that "an error has occurred

**Comment by russorat** [comment]
I'm seeing this when I cannot connect to a source in data explorer. i think there is a bug in the notifications component.

![image](https://user-images.githubusercontent.com/4805997/42604159-2b93a448-8526-11e8-9892-343077171e26.png)
