### ISSUE TITLE
Dashboard Broken - CheckSource Component

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/chronograf#3818]
My dashboard actually exploded and I was able to capture it in real time here:

![dashboard-error](https://user-images.githubusercontent.com/15273162/42247057-e9cf4a6a-7ed3-11e8-9946-c500dcff60d0.jpg)

Error messages:
1. Cannot read property 'find' of null (in CheckSource component)
1. Can't call setState (or forceUpdate) on an unmounted component. (in CheckSource component)

**Comment by 121watts** [comment]
@AlirieGray do you have repro steps?  I am successfully loading my dashboards

**Comment by AlirieGray** [comment]
@121watts This happens when I load up http://localhost:8080/ after running yarn start:hmr

**Comment by russorat** [comment]
unrelated, but that image is hilarious 👍

**Comment by AlirieGray** [comment]
Seems to be an issue on my machine after testing again, closing issue
