### ISSUE TITLE
Log viewer should allow the user to chage the log level string

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#3827]
The strings on the left hand column should be editable
<img width="344" alt="screen shot 2018-07-05 at 1 58 08 pm" src="https://user-images.githubusercontent.com/1003269/42347914-40990834-805c-11e8-9dad-d3277a2f7a2b.png">

**Comment by 121watts** [comment]
The likely culprit:

https://github.com/influxdata/chronograf/blob/master/ui/src/logs/constants/index.ts
