### ISSUE TITLE
Template Variables are not remembered on refresh

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3830]
to reproduce, create a new template variable on a dashboard, refresh the page, and try to select a different value.

**Comment by chnn** [comment]
@russorat I can't reproduce on current `master`. Could you verify / let me know for what types of template variables this is happening?

**Comment by russorat** [comment]
not seeing this anymore

**Comment by russorat** [comment]
found it!

![kapture 2018-07-13 at 9 40 51](https://user-images.githubusercontent.com/4805997/42703263-f5930c42-8680-11e8-8157-ade575fc66c4.gif)
