### ISSUE TITLE
canned mysql dashboard not displaying read/write stats

### ISSUE THREAD

**Issue by PeterWeiler** [influxdata/chronograf#3850]
The canned mysql dashboard (/usr/share/chronograf/canned/mysql.json) uses **command_xyz** for field names.  The actual field names getting written to InfluxDB are **cmd_xyz**.  OS/software versions used:

> $ grep VERSION= /etc/os-release 
> VERSION="18.04 LTS (Bionic Beaver)"
> 
> $ telegraf --version
> Telegraf v1.7.1 (git: release-1.7 4be18c1e)
> 
> $ chronograf --version
> 2018/07/10 16:20:44 Chronograf 1.5.0.0 (git: 23152663e04ab91f52866e83385eaac2b1a0f4b4)
> 
> $ mysqld --version
> mysqld  Ver 5.7.22-0ubuntu18.04.1 for Linux on x86_64 ((Ubuntu))

**Comment by russorat** [comment]
@PeterWeiler thanks for the report. we will look into fixing this.

in the short term, you can manually edit the files in the [/canned directory](https://github.com/influxdata/chronograf/blob/master/canned/mysql.json) to reflect the new values.

**Comment by danielnelson** [comment]
I believe the fields are actually `com_xyz`, here is a partial example:
```
mysql,server=debian-stretch-mariadb.virt:3306 com_alter_server=0i,com_alter_table=0i,com_alter_tablespace=0i,com_analyze=0i,com_assign_to_keycache=0i,com_begin=0i,com_binlog=0i,com_call_procedure=0i,com_change_db=0i,com_change_master=0i,com_check=0i,com_checksum=0i,com_commit=0i,com_compound_sql=0i,com_create_db=0i,com_create_event=0i,com_create_function=0i,com_create_index=0i,com_create_procedure=0i,com_create_role=0i 1531263751000000000
```
