### ISSUE TITLE
Add nested template variables for CSV and Map type

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3853]
CSV nesting used to work, map type is an enhancement.

- [ ] add the ability for a user to use other template variables in the CSV template variable type. for example, i would be able to create a template variable for `:host:` and then a csv template variable for `and 1=1, and host = ':host:'`
- [ ] add the ability for a user to use other template variables in the Map template variable type. for example, i would be able to create a template variable for `:host:` and then a Map template variable for 
```
No Host,and 1=1
With Host, host = ':host:'
```

**Comment by chnn** [comment]
May be blocked on #3871
