### ISSUE TITLE
Sort logs histogram bars by severity level

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3857]

**Comment by chnn** [comment]
Should be able to just update this here:

https://github.com/influxdata/chronograf/blob/6eb2dd6bec16b38af7c06da1d903394bce9c7c4f/ui/src/shared/components/HistogramChartBars.tsx#L33-L45

Originally I had it sorted by severity level, but thought it looked more natural to put the largest sub-bars on the bottom of the stack.
