### ISSUE TITLE
canned ping dashboard not grouping on correct tag

### ISSUE THREAD

**Issue by PeterWeiler** [influxdata/chronograf#3859]
The canned ping dashboard (/usr/share/chronograf/canned/ping.json) uses **server** in the groupby clause; to group by destination, the correct tag is **url**. OS/software versions used:

>$ grep VERSION= /etc/os-release
>VERSION="18.04 LTS (Bionic Beaver)"
>
>$ telegraf --version
>Telegraf v1.7.1 (git: release-1.7 4be18c1e)
>
>$ chronograf --version
>2018/07/10 16:20:44 Chronograf 1.5.0.0 (git: 2315266)

**Comment by 121watts** [comment]
@PeterWeiler thanks for filing the issue!  ill take care of that right now.
