### ISSUE TITLE
Swagger file has errors

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#3865]
While working on https://github.com/influxdata/chronograf/pull/3842 I discovered that the [swagger in master](https://github.com/influxdata/chronograf/blob/6eb2dd6bec16b38af7c06da1d903394bce9c7c4f/server/swagger.json) has a ton of errors and doesn't fully render in the [swagger editor](https://editor2.swagger.io/#!/)

**Comment by jaredscheib** [comment]
This is being fixed in #3806 and was introduced accidentally in #3776.

**Comment by jaredscheib** [comment]
The rendering is fixed as of #3806. The other errors remain.
