### ISSUE TITLE
Add the ability to display the un-templated query being run

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3877]
as a user, i would like a way to view the actual query being run against the database so that i can debug my templated queries without opening up the console and looking at network requests.

maybe this could be an option in the cell menu dropdown and in the CEO?

 - [x] Update Cell Editor Bottom to use Code Mirror 
> - [x] In `Query Templates` drop down of Code Mirror add a button to `Show Raw Query` 
> - [x] Clicking `Show Raw Query` toggles text between `Show Raw Query` and `Hide Raw Query` in dropdown
 - [x] Code Mirror should use `replace` util template values in query text
- [x] Showing Raw Query should display the *un-templated* query text 
- [x] Showing Raw Query turns of editing in CodeMirror

------

- [x] **Remove** *`Query Templates` dropdown*
- [x] Replace with `Show Raw Query` button
- [x] Clicking `Show Raw Query` focuses on text field
- [x] onBlur reverts to regular edit mode
- [x] When in `Raw Query` mode disable the `Submit Query` button (to communicate that it is read-only)
- [x] When in `Raw Query` mode change button text to `Hide Raw Query`

-----

- [x] Prevent AutoRefresh from reset query editor text
- [ ] Only validate query when user hits `enter` or submits query
- [x] Submit query onBlur
- [x] Stay in read-only mode when you click the varmoji element

**Comment by alexpaxton** [comment]
- [ ] Only show `Show Template Values` button when query contains template variables
