### ISSUE TITLE
Hosts drop down selector is missing from Hosts page 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#3890]
build **nightly build**
build time **201807112358**

```
$ chronograf --version
2018/07/12 13:46:42 Chronograf 1.4.3.0~n201807112358 (git: f1cc308086f025dc9d7f76c2967c8afd5df5d184)

```

*Use Case*

When viewing hosts, for example in a cluster, as a user, I want to quickly switch to another host view. 

1) Open the hosts page 

The drop down list box containing the other hosts is no longer available. 

*Expected Behavior*

That I can switch between hosts using the drop down control as in the past. 

*Screenshots*
![hostsdropdownlistboxmissing01](https://user-images.githubusercontent.com/25881301/42631388-60e0f830-85da-11e8-969e-02052267d1d0.png)
![hostsdropdownlistboxprevbuild](https://user-images.githubusercontent.com/25881301/42631389-60f95150-85da-11e8-83af-2542046afbf2.png)

**Comment by bthesorceror** [comment]
Per Chris Henn, it looks like the query we are issuing to get hosts is returning an error.
