### ISSUE TITLE
Add influxdb 1.6 single value functions to data explorer and CEO

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3895]
https://docs.influxdata.com/influxdb/v1.6/query_language/functions/

unsupported functions (not all new) are:
- [ ] DISTINCT
- [ ] INTEGRAL
- [ ] MODE
- [ ] ABS
- [ ] ACOS
- [ ] ASIN
- [ ] ATAN
- [ ] CIEL
- [ ] COS
- [ ] SIN
- [ ] TAN
- [ ] CUMULATIVE_SUM
- [ ] DERIVATIVE
- [ ] DIFFERENCE
- [ ] ELAPSED
- [ ] EXP
- [ ] FLOOR
- [ ] LN
- [ ] LOG2
- [ ] LOG10
- [ ] NON_NEGATIVE_DERIVATIVE
- [ ] NON_NEGATIVE_DIFFERENCE
- [ ] ROUND
- [ ] SQRT

Open questions: 
- since we auto group by time, the functions that are not aggregates would need something like `mean` to be applied to the value before being sent in. what does that look like in the UI?
- with this many functions, what does the UI look like?
- what happens if the function is not supported in their version of InfluxDB?

![image](https://user-images.githubusercontent.com/4805997/42647682-8622e7a0-85b9-11e8-91a4-56efb115949c.png)

**Comment by russorat** [comment]
we should handle #1807 

we can use `SHOW FIELD KEYS ON "telegraf" FROM "measurement_name"` to get the field types, which should influence which functions are available.

**Comment by alexpaxton** [comment]
Proposed redesign:
![function-selector--v0](https://user-images.githubusercontent.com/2433762/43097626-7d770440-8e71-11e8-8101-f3ed1e557e37.png)

**Comment by alexpaxton** [comment]
@russorat with the new design we can support all the functions. Is there an easy way to tell which functions take args (and what those args are)? Should I just look at the docs?
