### ISSUE TITLE
master log viewer doesn't render in firefox

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3898]
This was master from about noon today (July 12th) :
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1922921/42657116-f24bfa66-85e6-11e8-92d5-9b93ced21611.png">

**Comment by brodo** [comment]
The log view in the tickscript editor also does not work in Firefox:

![Error-Message](https://user-images.githubusercontent.com/377911/43838741-82aeb810-9b1c-11e8-8db7-49b8c4d4a3e2.png)
