### ISSUE TITLE
Use precision in gauge labels

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3906]
<img width="260" alt="screen shot 2018-07-12 at 5 44 11 pm" src="https://user-images.githubusercontent.com/2433762/42666644-3ff2a940-85fb-11e8-9be2-665147f0a407.png">

Precision in labels should match the precision in the value

**Comment by russorat** [comment]
connect #839

**Comment by russorat** [comment]
- [ ] for the gauge labels, the minimum number of decimals should be 0, so regardless of what the user selects, if the value 50 is in the label, it is shown as 50 and NOT 50.000.
- [ ] for the gauge labels, the maximum number of decimals to show should be whatever the user selects
