### ISSUE TITLE
how to use JWT  for influxDb authentication

### ISSUE THREAD

**Issue by jaideepsinghPanwar** [influxdata/chronograf#3910]
I need to use JWT for influxdb authentication.How can i use it while querying database through URL.

**Comment by goller** [comment]
@jaideepsinghPanwar , there is no graphical way of setting this yet, but, you can create a new data source via the API using the "sharedSecret" key.

Here is an example JSON that I changed for you... it came from: https://github.com/influxdata/chronograf/blob/master/integrations/testdata/example.src

```json
{
  "id": "5000",
  "name": "My datasource",
  "username": "myusername",
  "sharedSecret": "place_shared_secret_here",
  "url": "http://localhost:8086",
  "type": "influx",
  "default": true,
  "telegraf": "telegraf"
}
```

Basically, POST that JSON to `/chronograf/v1/sources` and you should have a new source with a share secret.  Here is the swagger documentation for a specific source:
https://github.com/influxdata/chronograf/blob/master/server/swagger.json#L4043

**Comment by russorat** [comment]
@goller do you know of any reason we couldn't support this in the UI?  fyi @alexpaxton
