### ISSUE TITLE
using the text input variable as a viewer logs the user out

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3913]
to repro, log into chronograf as a viewer, then open a dashboard with a text input variable. click the text box of the template variable and notice that you are logged out.

fyi @chnn

**Comment by chnn** [comment]
We need to make this input readonly / `disabled` if a user is a viewer:

https://github.com/influxdata/chronograf/blob/5aaffbd68524044a642dfba90d474bbda915a698/ui/src/tempVars/components/TextTemplateSelector.tsx#L32-L41

**Comment by russorat** [comment]
@chnn a viewer should be able to enter values into the text input temp var. the values should only be saved in the user's local storage, not in the boltdb.
