### ISSUE TITLE
Updating the query in the query viewer sometimes doesn't update after confirming the update

### ISSUE THREAD

**Issue by jsternberg** [influxdata/chronograf#3916]
It can be seen with this example:

![kapture 2018-07-13 at 12 48 54](https://user-images.githubusercontent.com/1212129/42711688-6e8ba6ea-86ae-11e8-8379-53f29bfb287e.gif)

If you update a query such as modifying `''` to `""` as in the example and then click the green checkmark, it will sometimes not save for some reason. It appears to save only after the query has said that it succeeded in the UI.

**Comment by jsternberg** [comment]
More information about this. This works properly if I push `Enter` by itself which seems to cause the query to execute and save into the interface before I confirm the change.

**Comment by russorat** [comment]
this is still an issue in master.

**Comment by jaredscheib** [comment]
Blocked on UX design.
