### ISSUE TITLE
"No results" when cloning a cell

### ISSUE THREAD

**Issue by GillesC** [influxdata/chronograf#3935]
When a cell is cloned, and the query is altered, the cell shows "No results".
This issue is resolved when the cell is removed and a new cell is created with the same query.

Host: Raspberry Pi 3
Chronograf Version: 1.5.0-0

**Comment by russorat** [comment]
@GillesC could you post the original query and also the altered query from the new cell? If possible, could you also add a screenshot just so it's clear what you are seeing?

**Comment by russorat** [comment]
I'm not able to reproduce this on the latest build. cloning a cell works as expected. also editing the cloned query works as expected.
