### ISSUE TITLE
AUTH_DURATION not working with OAuth

### ISSUE THREAD

**Issue by tk512** [influxdata/chronograf#3938]
I am using Chronograf successfully with Google OAuth authentication, but the AUTH_DURATION does not seem to work when going to the main public URL directly e.g. https://mydomain.com

I am consistently logged out after around 20-30 minutes.  I then have to do the whole OAuth process again with selecting the account I want to log in with. It seems that if I go directly to a dashboard URL then I don't have to do this and auth duration works.

I am using:
2018/07/17 12:01:51 Chronograf 1.4.3.0-1930-g5601553 (git: 56015535)
And passing these environment variables:

```export GOOGLE_CLIENT_ID=....apps.googleusercontent.com
export GOOGLE_CLIENT_SECRET=...
export PUBLIC_URL=https://mydomain.com
export TOKEN_SECRET=....
export GOOGLE_DOMAINS=mydomain.com
export AUTH_DURATION=1080h```

**Comment by russorat** [comment]
connect #1095

**Comment by desa** [comment]
@tk512 thanks for reporting this. I've been trying to reproduce this and so far I've been unsuccessful. 

So far what I've tried is

1. Start up chronograf with an auth duration of `1080h`
2. Go to base chronograf page
3. Do oauth flow
4. Wait (so far it's been 45 minutes)

Would it be possible for you to provide detailed steps to reproduce this? Additionally, it would useful to see the logs chronograf logs around the time of the logout.

**Comment by tk512** [comment]
@desa Hi and thanks for the reply. The 4th step can just be followed by going to the base Chronograf page e.g. https://mydomain.com 

If you go to an individual page e.g. https://mydomain.com/sources/1/dashboards/1   then it works without sending you to the login page again.

But of course practically if I want to go back to the site I just type mydomain.com in the browser, and then it starts with the OAuth flow again.

**Comment by desa** [comment]
@tk512 when you go to the base page do you get redirected to the status page?

**Comment by tk512** [comment]
@desa Yes, I get redirected to /sources/1/status.

**Comment by desa** [comment]
I'll give the repro another try. But I suspect that things will not be much different.

I've got a few asks that will help me debug:
1. The logs from around the time that you get signed out.
2. Which browser you experience this behavior in
3. Do you see this behavior when you don't set the auth duration?

**Comment by tk512** [comment]
@desa 
Yes, that makes sense.
1. What logs do you think will make sense here - I don't actually see anything useful happening on the Chronograf log?
2. I am using Chrome
3. Yes, so it seems like AUTH_DURATION is probably not the issue here. Perhaps we can rename this ticket.

**Comment by desa** [comment]
> What logs do you think will make sense here - I don't actually see anything useful happening on the Chronograf log?

I'm looking to see if this is a front end thing or if there's anything server side that is happening. In particular I'm looking for things like `invalid principal`.
