### ISSUE TITLE
External UI Kit

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#3946]
### Overview
Create standardized atomic UI components for use in (ideally) any context. This will make it easier to manage sweeping changes to the UI as well as maintain visual consistency. The experience of working on the interface should be improved as it will be easier to create something that looks good without custom styles each time.

### NPM Package
- [x] Choose a name
- [x] Set up repo
- [ ] Set up package
- [ ] Set up build and tests
- [ ] Move components into repo
- [ ] Add package to Chronograf

### Checklist
- [x] Export all components from a single index file
- [ ] 12-Column Grid
- [ ] Icons
- [x] Dropdowns
  - [x] Standard
  - [x] Multi-Select
  - [ ] Autocomplete
- [x] Buttons
- [x] Radio Buttons
- [ ] Page
- [x] Page Header
- [ ] Page Contents
- [x] Overlays
  - [x] Overlay Wrapper
  - [x] Overlay Dialog
  - [x] Overlay Header
  - [x] Overlay Body
- [x] Forms
  - [x] Form Wrapper
  - [x] Form Element
  - [x] Form Divider
  - [x] Form labels, help text, and error messages
- [x] Text Input
- [ ] Text Area
- [x] Drag & Drop
- [x] Panels
- [ ] Toolbars
- [ ] Spinners

**Comment by chnn** [comment]
For forms, here are a couple behavioral requirements I have come across in the past:

- should be able to validate an input immediately as a user types
- should be able to validate an input debounced as a user types
- should be able to perform asynchronous validations
  - should be able to display the state of an in-progress asynchronous validation
- should be able to validate an input on focus out
  - should cancel debounce timers if they exist
- validations should be able to depend on other form inputs / controls
  - should be able to display a single error in multiple inputs / controls
- should be able to store input internally as different type then what is displayed in inputs
- should be able to use custom components for a input controls
- should be able to alter / tidy a user's input on focus out
- should be able to provide default values for inputs
- should be able to block the form's submit if any input is invalid
- should be able to render different controls dynamically
- should be able to gather all valid inputs to submit a form

My belief is that the nature of these requirements do not map well onto the compositional / component-oriented model provided by React. There's too many units in a design that necessarily need to communicate with many other units, so an attempt to construct compositional boundaries ends up requiring so much ceremony / boilerplate that the benefits of compositional design are negated.

I think we could provide more foundational reusable components that encapsulate purely-stylistic choices, but behavior should be left up to the form implementor.

**Comment by alexpaxton** [comment]
Stumbled upon some cool new patterns I'd like to standardize across all these reusable components.

### Get child components with a single import
- See `Dropdown` for an example. Child components are defined as `public static` inside the parent class, so usage looks like this: `<Dropdown.Item>` or `<Dropdown.Divider>`

### Self documenting components
As seen in the `Dropdown` and `Panel`, errors are thrown if the components are passed unexpected children

### Exposing async state
- Being able to show `Loading`, `Valid`, or `Error` states on many of these components will make then more useful when building asynchronous user experiences

**Comment by alexpaxton** [comment]
@chnn I can see eventually building specialized inputs, such as selecting a timestamp that prevents the user from entering an invalid value. I think you are right about the interplay between form elements and validating the form as a whole, it sounds tough to generalize any of that.

**Comment by alexpaxton** [comment]
https://github.com/influxdata/clockface
