### ISSUE TITLE
Can't find chronograf manage roles

### ISSUE THREAD

**Issue by hero9** [influxdata/chronograf#3953]
Hello!
Could you please tell how can I get the access to chronograf administration, where I can give roles for users.
Now in Admin tab I have only choice to manage Influxdb: 
![image](https://user-images.githubusercontent.com/22573860/42879841-e0b48e22-8ab3-11e8-8260-5044a39512cd.png)

Thanks in advance!

**Comment by russorat** [comment]
@hero9 thanks! you need to enable OAuth in order to manage users. Check out this guide: https://docs.influxdata.com/chronograf/v1.5/administration/managing-security/#chronograf-security
