### ISSUE TITLE
Custom OAuth2 authorization

### ISSUE THREAD

**Issue by hero9** [influxdata/chronograf#3959]
QUESTION.
Hey!
Could you please tell me how can I plug to chronograf my own token generator?
So, I wanna store it locally, without going to any online services.
Is it even possible?
Thanks in advance!

**Comment by russorat** [comment]
@hero9 thanks! We offer generic OAuth support via the following config options: https://docs.influxdata.com/chronograf/v1.6/administration/managing-security/#configuring-generic-authentication

This type of question is probably better for https://community.influxdata.com . If after doing some research and finding an issue with our generic ouath support, please let us know by opening an issue and we will investigate.
