### ISSUE TITLE
No CLI arguement to skip verification of self-signed certs

### ISSUE THREAD

**Issue by bulletlink** [influxdata/chronograf#3961]
There is currently no option to tell chronograf to skip verification of certificates when executing from CLI.

Everything works perfectly well when setting up a connection through chronograf front end by ticking the "unsecure ssl" tickbox. However there is no option to do this through CLI.

**Comment by russorat** [comment]
@bulletlink thanks! just so i'm clear, are you talking about a command line flag when running `./chronograf`? or something else?

**Comment by bulletlink** [comment]
@russorat that's right! something along the lines of the `--unsecureSsl` of flag when connecting to influxd with `influx --ssl --unsecureSsl`

**Comment by russorat** [comment]
@bulletlink thanks for clarifying. We will look into adding that option.

As a work around, you can also pre-define the source using `.src` files as described in this comment: https://github.com/influxdata/chronograf/issues/2659#issuecomment-354164604

**Comment by bulletlink** [comment]
@russorat perfect! Wasn't aware of that. Thanks
