### ISSUE TITLE
Can't download csv from dashboard cell

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3964]
On master, in Chrome, auth not enabled.

All three of these cells have `Download CSV` disabled.

The query for the graph whose dropdown is currently open is: `SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: GROUP BY time(:interval:) FILL(null)`.

<img width="1315" alt="screen shot 2018-07-19 at 2 53 52 pm" src="https://user-images.githubusercontent.com/6403018/42966890-21f538d6-8b64-11e8-9e2e-69674a48f896.png">

**Comment by russorat** [comment]
i am seeing this in master but not on the 1.6 branch.
