### ISSUE TITLE
Some overlap on the log viewer histogram

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3968]
![image](https://user-images.githubusercontent.com/4805997/42974292-74eee99a-8b6b-11e8-9abd-df6daea7a172.png)

**Comment by chnn** [comment]
I'm having trouble reproducing this. I tried Chrome, Firefox, and Safari—any special steps you can think of?

**Comment by russorat** [comment]
i'm on my laptop screen. maybe a smaller window size causes it?
