### ISSUE TITLE
Clicking histogram in log viewer should have same width for bars and the marker should be placed where i click

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3970]
as a chronograf user
with viewer permissions or higher
when i click on the histogram in the log viewer page 
i would like the bars to have a consistent width
i would like the time marker placed where I click and not moved to the center.

when you click on a column in the log viewer, the size of the bars change and the location of the click changes to be in the middle. this is a little jarring to the user.

the better behavior would be to keep the columns the same and place the time marker where the user clicks the mouse.

- [x]  bars should maintain a consistent width when clicked
- [x]  time marker (histogram overlay) reflects position clicked, no centering

**Comment by chnn** [comment]
we could also do something like: https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

rendering a histogram for the context would be prohibitively expensive, but we could still display a brushable time axis.
