### ISSUE TITLE
Add an onboarding step for detecting and importing pre-designed dashboards

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3983]
the goal of this issue is to add the ability for a user to import pre-existing dashboards into Chronograf when they use the add a source wizard described in #3981 

This card should be inserted directly after the user adds the connection to influxdb.

This card would display to the user all the pre-created dashboards available in Chronograf and allow them to select zero or more dashboards to be created in their organization.

If the user doesn't want to import and dashboards, they may skip this step. or jump out of the wizard altogether since all other fields are optional.

This card should also have the option for chronograf to run a query to detect the dashboards that are compatible and automatically select them. This query should scan their data and look for measurements that are compatible

The dashboards should be created as soon as the user selects to move to the next card. A notification should be displayed letting the user know that the dashboards were created.

There should be descriptive text at the top of the card to guide new users on what this is doing.

There should be an indicator of how many dashboards the user (or we) have selected to import.

These dashboards will need additional metadata. This should use the same "meta" section as found in the export dashboard feature (currently containing the sources and the chrono version). A proposed format might be:

```
{
  "name": "my-dope-dashboard",
  "version": "1.2.3",
  "description": "This is an awesome dashboard for my awesome app.",
  "author": "Chronogiraffe",
  "license": "Apache-2.0",
  "icon":"http://example.com/icon.png",
  "homepage": "http://example.com"
}
```

**Comment by ebb-tide** [comment]
Every item on this card has been completed as part of another card except the 

>This card should also have the option for chronograf to run a query to detect the dashboards that are compatible and automatically select them. This query should scan their data and look for measurements that are compatible
