### ISSUE TITLE
Missing vertical line on some graphs

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3986]
i'm not sure how to repro, but i noticed on one of my dashboards that the vertical line is not showing up on one of the graphs. some of the graphs work fine.

![screen shot 2018-07-23 at 10 49 59 am](https://user-images.githubusercontent.com/4805997/43094110-ec120de2-8e66-11e8-9972-50532befa5c9.png)

**Comment by ischolten** [comment]
This was due to the browser being zoomed in.
