### ISSUE TITLE
Change time dropdown "laggy" since header redesign

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3987]
user reported the time range drop down is laggy after an upgrade. Is it waiting for the queries to execute before it closes? When a user selects a new time range, the dropdown should close instantly while the queries refresh.

![kapture 2018-07-23 at 11 08 00](https://user-images.githubusercontent.com/4805997/43094844-e44abac6-8e68-11e8-9d14-7219ad82e8f8.gif)

**Comment by russorat** [comment]
disable that control until the queries have returned so we don't hammer the db

**Comment by 121watts** [comment]
we should probably wait until (this)[https://github.com/influxdata/chronograf/pull/3984] refactor of the dropdowns is completed.

**Comment by russorat** [comment]
this is still happening.

![kapture 2018-07-30 at 12 02 12](https://user-images.githubusercontent.com/4805997/43417818-e944ebfe-93f0-11e8-8990-180005a467cb.gif)

**Comment by stefanhorning** [comment]
Can confirm this issue since updating to 2.6.
Despite just being a small thing, this is really annoying when navigating dashboards.
