### ISSUE TITLE
Clean up yarn scripts by removing stale ones, adding linters, and adding type-checking

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3997]

**Comment by russorat** [comment]
how big is this list? what's the estimate of work here?

**Comment by jaredscheib** [comment]
@russorat this has already been solved in #3998. it was a follow-on to reviewing #3845 and took about 1 hour.

**Comment by jaredscheib** [comment]
by follow-on, i meant that in order to approve #3845, this work was important to take care of.

**Comment by jaredscheib** [comment]
Closed by #3845.
