### ISSUE TITLE
Setting an Organisation name to an already existing one causes duplication and unrecoverable behaviour

### ISSUE THREAD

**Issue by bulletlink** [influxdata/chronograf#4002]
I had 2 organisations under chronograf Admin -> all Orgs. 

I set the name of one of them to the same as the other one. This resulted in a double entry and I am unable to remove either of them. Changing the name of one of them also changes the name of the other one. It also shows both of them set as current. However, it lists my admin user as admin on the original one and viewer on the duplicate one.

After switching between them via the user menu, it allows me to switch between the two, with different permissions (admin on one, viewer on the other one)

When attempting to delete, i get the following console message:

`<ERRO[3208] Error message Unknown error while deleting organization: organization not found unable to delete an organization from the filesystem  component=server http_status =400`

If I restart the chronograf service, both of them appear again.

After several attempts, I managed to delete one and it disappeared from the list. However, this appeared again when I navigated back to the organisations tab.

A side note relating to this: The reason I changed the name was because i had an organisation that I wasnt using but was unable to delete it from the list (delete button was grayed out): I changed the name to the same as the organisation I was actually using, hoping to be able to delete the other one. Is there any reason I couldnt delete the original organisation?

**Comment by bulletlink** [comment]
@russorat I'm using v1.6. In my case the default one was renamed to something and i set a second organisation to the same name. I don't know if my deletion issue is related to the bug you reported.

To clarify: The default org was renamed e.g. "something". Then I created a second organisation and set it to the same name e.g. "something". From there, renaming either of them would rename both. I was also unable to delete the second org.

**Comment by russorat** [comment]
@bulletlink hummm i think i'm still having trouble reproducing exactly what you are seeing in the 1.6 line. Maybe investigating and fixing the related issue will uncover this behavior as well? We are planning a bugfix release next week.

![kapture 2018-07-24 at 9 47 13](https://user-images.githubusercontent.com/4805997/43153737-f857597a-8f26-11e8-86fe-7130d6f7bbb2.gif)

**Comment by bulletlink** [comment]
@russorat  ok great. In the meantime i will try and see if i can reproduce it myself again and try to give you a bit more insight.

**Comment by bulletlink** [comment]
@russorat I was able to reproduce this again today. It seems to be a bit more weird than I thought. Hope the gif is clear enough. Let me know if you need any more info.

![chrono org bug](https://user-images.githubusercontent.com/40271466/43196441-2ae0106c-9008-11e8-9e1c-25a6fed3406b.gif)
