### ISSUE TITLE
Changing source while importing dashboard

### ISSUE THREAD

**Issue by rozpuszczalny** [influxdata/chronograf#4010]
First of all, thanks for the export dashboard feature!

I've exported dashboard from my localhost chronograf instance and imported it on server. On localhost, there is a data source with id 1. On server, there is a multiple data sources and I'd like to use data source id 3. Unfortunately, to make dashboard work properly, I have to change data source in every single cell, since imported dashboard uses data source id 1.

It would be nice, if data source picker exists, while importing dashboard.

**Comment by russorat** [comment]
@rozpuszczalny thanks for opening this. i believe this is the same of https://github.com/influxdata/chronograf/issues/3980. can you confirm and close this in favor of #3980?
