### ISSUE TITLE
query parameter for dashboard AutoRefresh value

### ISSUE THREAD

**Issue by imrehg** [influxdata/chronograf#4012]
Now the AutoRefresh value is switched to "paused" (since #3401), and don't seem to have a query parameter to set it to anything else. This makes it more difficult, to e.g. use a dashboard in a "kiosk" setting, when there's no input tools to change that value. On the other hand, the displayed time interval is set by a query parameter (such as `?lower=now%28%29%20-%2012h` for "Past 12h"). Would be good to add a value so that a dashboard view could be properly shared by the URL alone.

**Comment by russorat** [comment]
@imrehg thanks for reporting this. we will look into how we can support this.

**Comment by jaredscheib** [comment]
seems like a great idea to me -- thanks @imrehg

**Comment by imrehg** [comment]
Any news on this? (prompted by StaleBot to re-ask, since the original feedback was positive)

**Comment by imrehg** [comment]
Again I just wonder if there are any news on this? (prompted by StaleBot to re-ask, since the original feedback was positive).

Or should I just look in the code where to possibly add this feature? Any comments/feedback on that (should/should not, if should, any advice)

**Comment by TCL735** [comment]
@imrehg This is done. Here is how it works:

- User selects a refresh rate in the dashboard: the selection is persisted for that dashboard and a query parameter is added to the url.
- A url with custom query parameters is used to directly navigate to a dashboard: the dashboard sets the refresh rate, persists it, and updates the refresh dropdown based on a valid query parameter for refresh. 

Keep in mind that this new feature does not apply to Hosts, Data Explorer, and the Cell Editor--query parameter for refresh will do nothing in them.
