### ISSUE TITLE
When importing dashboards, the cells show no results until re-configured

### ISSUE THREAD

**Issue by bulletlink** [influxdata/chronograf#4027]
When importing dashboards, the cells show no results. If i click on configure and apply without making any changes, the cells start working again. I don´t know if this is how imports are intended to work, but it appears that the cells don´t query data until they are re-configured.

![dashboard_import](https://user-images.githubusercontent.com/40271466/43256169-3b852bc2-90cc-11e8-8ce9-477503105afb.gif)

**Comment by russorat** [comment]
Closing in favor of #3980. Please follow that issue for resolution.
