### ISSUE TITLE
Firefox menu styles differ from Chrome

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4039]
<img width="214" alt="screen shot 2018-07-26 at 4 26 37 pm" src="https://user-images.githubusercontent.com/6403018/43293750-b9dd8284-90f0-11e8-8cc6-a20bcd2d5de5.png">

**Comment by sdomino** [comment]
Seems like this may have already been fixed. I fired up FF 61.0.1 and wasn't able to replicate the issue.

**Comment by jaredscheib** [comment]
Thanks @sdomino. After trying to repro, I see that it's only happening when I have the dev tools open. Closing.
