### ISSUE TITLE
For Untemplated Query: copy template variable values in in query

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4044]
follow on to #3877

as a chronograf user
with editor permissions or higher
when i view the untemplated query
i would like to be able to select and copy the untemplated query to run in the CLI
i would like to be able to see the substituted template variable values in the query.

The untemplated query should allow the user to:
- [ ] select and copy the untemplated query and paste it somewhere else (influx CLI)
- [ ] it should substitute all template variables into the query, not just :internal: and :dashboardTime:

**Comment by OfTheDelmer** [comment]
Currently we iterate over the code mirror template variable tokens in the editor and mark each with a span that displays the value which adds some highlighting to speed up recognition of the template value. 

Using the `replace` function from the `src/shared/apis/query.ts` would allow us to see the query's replaced values exactly as they would appear in a request using `fetchTimeSeries`.  We might want to separately add an `enhancement` issue to add code mirror template highlighting to the replaced values.

**Comment by russorat** [comment]
@OfTheDelmer based on your comment, what are the next steps here?
