### ISSUE TITLE
Single Stat can have a very large precision

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4047]
**Chronograf Version: 1.7.0**

I noticed in one of the cells I was looking at that the precision of the single stat was very high:

![](https://ucc36ba13a11ed8fbbab92f12400.previews.dropboxusercontent.com/p/thumb/AALvOn0vyPuRAAtIaIw_QdZvxqPEbhKGLQvDwlu19xDYEGElclCAyvezeiB1aN8uZg3D-9OxvTfgC8m8bUpyJJqMnioGX-ZBmCu-SXWe6J225pkgqkyZKBm6lxBhvfpz_-c5VjvjA-8xS8fQhcuZSIhJi2EW4acZ_NtopgxOxiRWd8hpb-EYYfl1nxX5kVC4y8ZnQbxaAQYJpet8Xv2eUhEZCmGRawkj6XTcg3EAG3Yu_A/p.png?size=2048x1536&size_mode=3)

It would be cool if it was possible to maybe set the precision inside the visualisation builder, or maybe just have a default maximum precision?

**Comment by russorat** [comment]
you can update that in the config settings for single stat. i believe for new graphs, the default should be 2.

**Comment by e-dard** [comment]
@russorat thanks. This is working great!
