### ISSUE TITLE
No indication of attempt to connect to Flux

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4049]
I clicked this button multiple times wondering whether anything had happened, before eventually a Timeout error came back. Something like a "request pending" state could smooth that out for me and other users.
![flux-connect-pending](https://user-images.githubusercontent.com/6403018/43419305-68f5eb10-93f5-11e8-9fb2-21a6b8006605.gif)

**Comment by russorat** [comment]
no longer relevent
