### ISSUE TITLE
When visiting Flux Editor without a Flux connection and adding a connection, I expect to return to Editor after successful add

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4057]
When I navigate to Flux Editor and don't have a connection to Flux currently, I'm prompted to Add a Connection. When I successfully add a connection, I expect to then be taken to the Flux Editor.

- [ ] take user back to flux editor after successful add, if that's where they originated from

![flux-redirect-back](https://user-images.githubusercontent.com/6403018/43423354-11aeadb8-9401-11e8-8a8a-4e361f2ab8bc.gif)

**Comment by russorat** [comment]
no longer relevant
