### ISSUE TITLE
Flux adding connection button colors don't imply different UX actions & states

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4060]
- [ ] seems like if I was successfully able to connect, then the Save Changes button would appear different
- [ ] seems like once I hit Save Changes, the button would become disabled or change color to indicate success, as it's not clear to me why it remains active
<img width="1198" alt="screen shot 2018-07-30 at 2 05 02 pm" src="https://user-images.githubusercontent.com/6403018/43423602-b3c9e8ce-9401-11e8-8936-008e5f03e12a.png">
<img width="1180" alt="screen shot 2018-07-30 at 2 05 16 pm" src="https://user-images.githubusercontent.com/6403018/43423603-b3f8d120-9401-11e8-8641-471e598bffcf.png">
<img width="1121" alt="screen shot 2018-07-30 at 2 05 08 pm" src="https://user-images.githubusercontent.com/6403018/43423604-b4171360-9401-11e8-862a-8c7628e165be.png">

**Comment by russorat** [comment]
no longer relevant
