### ISSUE TITLE
Side nav menu does not indicate where I am when I'm adding a Flux Connection

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4061]
Notice that there's no active menu item at the Add Flux Connection page:
![flux-sidenav-active-menu-item](https://user-images.githubusercontent.com/6403018/43423829-4895633e-9402-11e8-8466-f35a88648486.gif)

**Comment by alexpaxton** [comment]
I can think of two ways to solve this:

1. Stick this form into a modal, so the user doesn't have to navigate back to the Config page or Flux Editor page

2. Highlight the parent nav item (Config or Flux) depending on where the form was accessed from

Option 1 seems more elegant

**Comment by russorat** [comment]
no longer relevant
