### ISSUE TITLE
Template Selector Design & Component

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#4062]
Requirements:
- [x] Display list of dashboard templates in a grid of selectable cards
- [x] Display name and icon in each tile
- [x] Can be configured as Single-Select or Multi-Select
- [x] Component can expand to fill dimensions of parent it is placed in
- [x] Use the same image asset for `selected` and `unselected` state

Stretch Goals:
- [ ] Responsive

**Comment by alexpaxton** [comment]
![image](https://user-images.githubusercontent.com/2433762/43430624-b7e7c4f4-941e-11e8-8cfe-7a553c376e06.png)

**Comment by russorat** [comment]
completed
