### ISSUE TITLE
Template variable in query string not working

### ISSUE THREAD

**Issue by jaideepsinghPanwar** [influxdata/chronograf#4069]
I have created some template variables in dashboard and I need to access is it in query string. I have know it can be done with this http://localhost:8888/sources/22/dashboards/29?host=test but this seems to not work.Am I doing something wrong ,or is there some setting that i need to make before this is working.

**Comment by karel-rehor** [comment]
@jaideepsinghPanwar I've been setting up some tests for this feature.  Here is a sample URL that has been working for me.

http://localhost:8888/sources/1/dashboards/7?lower=now%28%29%20-%2015m&tempVars%5Bhost%5D=%27cluster_node_1%27

The argument you need is the tempVars array.  Decoded it looks like this 

```
http://localhost:8888/sources/1/dashboards/7?lower=now() - 15m&tempVars[host]='cluster_node_1'
```

**Comment by jaideepsinghPanwar** [comment]
I tried with your solution but that is not working for me. As you can see in image,I have selected one host from template variable dropdown and now when I try to change it by passing template variable from URL it still show result for the one that is selected in dropdown and not for the one in URL. 
Is there some specific permission that I need to give to user..

![chronograf_tempvar](https://user-images.githubusercontent.com/40162355/43563599-82effdce-9640-11e8-82ba-335c46944a02.PNG)
