### ISSUE TITLE
API for dashboard templates

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#4080]
### JSON representation

At the moment the JSON representation of a dashboard looks like:

```json
{
  "id": 12,
  "cells": [],
  "templates": [],
  "name": "Name This Dashboard",
  "organization": "default",
  "links": {
	"self": "/chronograf/v1/dashboards/12",
	"cells": "/chronograf/v1/dashboards/12/cells",
	"templates": "/chronograf/v1/dashboards/12/templates"
  }
}
```

The dashboard templates API  JSON will have `meta` and `dashboard` fields: 
notice the `id`, `name`, `organization`, `links`, of a dashboard is not a part of a dashboard template. 
```json
{
  "meta": {.... (see below)},
  "dashboard": {
      "cells": [],
      "templates": [],
}
```

the meta field will have at least these fields: 
```json
{
  "meta": {
     "id": 3,
     "name": "Telegraf",
     "templateVersion": "1.2.3",
     "chronografVersion": "1.7.0",
     "description": "This is an awesome dashboard for my awesome app.",
     "author": "Chronogiraffe",
     "license": "Apache-2.0",
     "icon":"http://example.com/icon.png", 
     "homepage": "http://example.com"
   },
}
```

### API endpoints:
`/GET` to dashboard templates endpoint that returns only the `meta` keys  of all available templates. 
`/GET` to dashboard templates/#id that returns all data associated with a specific template.

dashboard templates are stored on the filesystem. 

also see : #3983

### API future considerations........ 
/PUT to create a dashboard template from a specific dashboard description
/DELETE to delete a dashboard template from the filesystem. 
/PATCH to edit a dashboard template by id. 
/GET which returns dashboard templates filtered by a meta field, such as author, or license..

**Comment by desa** [comment]
I think this is good, although I think I'd suggest a few modifications. I think I'd bring the fields on meta up to the top level object. Specifically what I think I'd do is bring the data that doesn't feel like meta data up. Things like `id`, `name`, and `icon`. I'm open to debate on these, but ID at the very least feels like data that belongs on the object not a sub section of the object. 

```json
{
  "id": 3,
  "name": "Telegraf",
  "icon":"http://example.com/icon.png", 
  "meta": {
     "templateVersion": "1.2.3",
     "chronografVersion": "1.7.0",
     "description": "This is an awesome dashboard for my awesome app.",
     "author": "Chronogiraffe",
     "license": "Apache-2.0",
     "homepage": "http://example.com"
   },
   "dashboard": {...}
}
```

**Comment by jaredscheib** [comment]
Some questions:
1. Should this work support dashboards-v1?
1. Should this work support dashboards-v2?
1. If both of the above, how do we want to differentiate?
1. Will these dashboard templates allow for any features that are not currently available in either dashboards-v1 or dashboards-v2? For example, any of the entailments of layouts?
1. We had debated a while back whether these should be JSON objects kept in the Chronograf server, whether they should have corresponding files on the file system, or something else -- any strong opinions now?

**Comment by alexpaxton** [comment]
@jaredscheib 

Some general thoughts:

There will (ideally) be JSON files for the dashboard templates, which are available to use as a starting point when creating a new dashboard. In that light, the templates don't have to be the same shape as a normal dashboard, but likely a partial of it. For example, the templates could have IDs `0-9` but when a user decides to make a dashboard from template `8` the new dashboard gets a unique ID from the server. We could use the ID of the template in the metadata of the new dashboard as a way to refer back to which template it is based on

5. I vote for JSON objects, seems easy to locate for someone looking to add a new one via community PR
6. I believe it's all the apps listed on the main chronograf readme
9. Ideally yes. That way we can display to the user what "flavor" of dashboard they are looking it.

**Comment by jaredscheib** [comment]
1. yes.
2. yes.
3. needs more info.
4. the dashboard key will simply be the dashboard-v1 or the dashboard-v2, minus the dashboard id, name, organization, templates. it might just be cells. if there are even cells? would that be pointing to cell templates? also, meta will need to include extra possible properties going forward.
5. needs more info from @nhaugo.
6. unlimited.
7. probably fixed is safer.
8. needs more information. even though PUT is not what we're implementing currently, is "author" an owner (user) who can set permissions on that template in terms of modifying it, for example? if i'm in one organization and create a template, can others from other organizations see it? etc. it sounds like right now we just want instance-wide dashboard templates, and anyone can access them.
9. haven't considered yet.

**Comment by jaredscheib** [comment]
{
  "id": 3,
  "meta": {
     "name": "Telegraf",
     "icon":"http://example.com/icon.png", 
     "templateVersion": "1.2.3",
     "dashboardVersion": "1.7.0",
     "description": "This is an awesome dashboard for my awesome app.",
     "author": "Chronogiraffe",
     "license": "Apache-2.0",
     "homepage": "http://example.com"
   },
   "data": {...}
}
```

**Comment by ebb-tide** [comment]
Decisions:
- id's will not be hashes, unique id's assigned by backend.
