### ISSUE TITLE
Can't configure oauth for github enterprise.

### ISSUE THREAD

**Issue by gbialas** [influxdata/chronograf#4085]
I am trying to integrate Chornograf with Github enterprise. Choronograf is started using docker compose. 

Config is passed by environment variables: 

  environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      PUBLIC_URL: <my_tick_server>>
      GENERIC_CLIENT_ID: <CLIENT_ID>
      GENERIC_CLIENT_SECRET: <CLIENT_SECRET>
      GENERIC_NAME: github
      GENERIC_AUTH_URL: <my_ghe_server_addres>/login/oauth/authorize
      GENERIC_TOKEN_URL: <my_ghe_server_addres>/login/oauth/token
      GENERIC_API_URL: <my_ghe_server_addres>api/user
      GENERIC_SCOPES: ‘user:email read:org’
      TOKEN_SECRET: <seccret_tocker>
      AUTH_DURATION: 1h
      LOG_LEVEL: debug

When I start Chronograf, I see login page, with button to redirect to github. When I click it, I am redirected to my GHE site, asking If I am allowing this. When I allow, I am redirected back to Chronograf, but I am not authorized. 

In logs I see:

time="2018-08-02T13:59:31Z" level=info msg="Serving chronograf at http://[::]:8888" component=server
time="2018-08-02T13:59:31Z" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
time="2018-08-02T14:02:05Z" level=debug msg=Request component=server method=GET remote_addr="<SERVER_IP>:59550" url=/oauth/github/login
time="2018-08-02T14:02:05Z" level=info msg="Response: Temporary Redirect" component=server method=GET remote_addr="<SERVER_IP>:59550" response_time="520.76µs" status=307
time="2018-08-02T14:02:05Z" level=debug msg=Request component=server method=GET remote_addr="<SERVER_IP>:59550" url=/oauth/github/callback?code=269f66f8cdade8945769&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzMyMTkxMjUsImlhdCI6MTUzMzIxODUyNSwibmJmIjoxNTMzMjE4NTI1LCJzdWIiOiIvbm10TW5RYzB0SUlISkFLWDZNWHptcXo3OFpaNU8rTmc3cERUOGRwRk9JPSJ9.AWJyBCDky2h13E2BtW4BwxxOtMg_0iA2C9nlQACU4iI
time="2018-08-02T14:02:05Z" level=error msg="Unable to exchange code for token oauth2: cannot fetch token: 403 Forbidden\nResponse: Cookies must be enabled to use GitHub." component=auth method=GET remote_addr="<SERVER_IP>:59550" url=/oauth/github/callback?code=269f66f8cdade8945769&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzMyMTkxMjUsImlhdCI6MTUzMzIxODUyNSwibmJmIjoxNTMzMjE4NTI1LCJzdWIiOiIvbm10TW5RYzB0SUlISkFLWDZNWHptcXo3OFpaNU8rTmc3cERUOGRwRk9JPSJ9.AWJyBCDky2h13E2BtW4BwxxOtMg_0iA2C9nlQACU4iI
time="2018-08-02T14:02:05Z" level=info msg="Response: Temporary Redirect" component=server method=GET remote_addr="<SERVER_IP>:59550" response_time=26.969581ms status=307
time="2018-08-02T14:02:06Z" level=debug msg=Request component=server method=GET remote_addr="<SERVER_IP>:59550" url=/chronograf/v1/
time="2018-08-02T14:02:06Z" level=info msg="Response: OK" component=server method=GET remote_addr="<SERVER_IP>:59550" response_time="269.218µs" status=200
time="2018-08-02T14:02:06Z" level=debug msg=Request component=server method=GET remote_addr="<SERVER_IP>:59550" url=/chronograf/v1/me
time="2018-08-02T14:02:06Z" level=error msg="Invalid principal" component="token_auth" method=GET remote_addr="<SERVER_IP>:59550" url=/chronograf/v1/me
time="2018-08-02T14:02:06Z" level=info msg="Response: Forbidden" component=server method=GET remote_addr="<SERVER_IP>:59550" response_time="79.667µs" status=403

**Comment by dhaval-pandya** [comment]
Even I am facing the same issue with both GHE and GH with GitHub environment variables as well as Generic environment variables. did you find any resolution of it?

Appreciate Any help or direction

**Comment by russorat** [comment]
@gbialas @dhaval-pandya have you tried setting the `GENERIC_DOMAINS` option? https://docs.influxdata.com/chronograf/v1.7/administration/config-options/#generic-domains

**Comment by dhaval-pandya** [comment]
@russorat yes I tried GENERIC_DOMAINS as well. I got the same results 403 forbidden while it internally accessing /chronograf/v1/me 
I tried adding environment variables to chronograf, adding the same user as super-admin in influx and giving all the permission in chronograf to the user, still no luck.

do you have any pointer to look at?

here is the log

`INFO[1478] Serving assets                                component=server method=GET remote_addr=[::1]:55012 url=/src.6adc4720.css
INFO[1478] Response: OK                                  component=server method=GET remote_addr=[::1]:55012 response_time=20.348559ms status=200
INFO[1490] Response: Temporary Redirect                  component=server method=GET remote_addr=[::1]:55012 response_time=99.034µs status=307
ERRO[1498] Unable to exchange code for token oauth2: cannot fetch token: 403 Forbidden`

**Comment by livneniv** [comment]
same issue here, were you able to find anything?

**Comment by livneniv** [comment]
to provide bit more details, in my case i had set up  the environment with a custom domain and certificate.
when i look at the browser behavior i see the keys and tokens exchanged successfully, but than when redirected back to my server with the token, i'm getting 403 forbidden when accessing https://my.servername.com/chronograf/v1/me
any ideas?

**Comment by ceastman-ibm** [comment]
same issue here trying to utilize our GHE environment as well.

**Comment by j-sokol** [comment]
Hi guys, it works for me when using `Generic oauth2`.

Here is the working configuration. In systemd environment variables (`/etc/systemd/system/chronograf.service.d/override.conf`) I have:
Any arbitrary secret:
```
Environment="TOKEN_SECRET=xxx" 
```
Credentials from GH Enterprise:
```
Environment="GENERIC_CLIENT_ID=xxxx"
Environment="GENERIC_CLIENT_SECRET=xxx"
```

Oauth2 URLs to GHE:
```
Environment="GENERIC_AUTH_URL=https://github.domain.io/login/oauth/authorize"
Environment="GENERIC_TOKEN_URL=https://github.domain.io/login/oauth/access_token"

Environment="AUTH_DURATION=12h"
Environment="GENERIC_NAME=github"

Environment="GENERIC_API_URL=https://github.domain.io/api/v3/user"

Environment="PUBLIC_URL=https://chronograf.domain.io"
```
As we have set `GENERIC_NAME` variable to value of `github`, you need to set callback in GHE Oauth app (on GHE webpage) to `https://chronograf.domain.io/oauth/github/callback`.

In the example above, I'm running GHE on `https://github.domain.io` and Chronograf on `https://chronograf.domain.io`.

**Comment by SuhasAnand** [comment]
@russorat any updates on this ? Its failing for me too.. 

In addition to the above env I have also enabled INFLUXDB_USERNAME & INFLUXDB_PASSWORD

`INFO[0000] Running migration 59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620`

`INFO[0000] Serving chronograf at http://[::]:8888        component=server`

`INFO[0000] Reporting usage stats                         component=usage freq=24h reporting_addr=https://usage.influxdata.com stats=os,arch,version,cluster_id,uptime`

`DEBU[0006] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/`

I`NFO[0006] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/`

`INFO[0006] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=6.61768ms status=200`

`DEBU[0007] Request                                       component=server method=GET 
remote_addr=172.230.69.249:63783 url=/chronograf/v1`

`INFO[0007] Response: Moved Permanently                   component=server method=GET remote_addr=172.230.69.249:63783 response_time=128.601µs status=301`

DEBU[0007] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/

INFO[0007] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=316.763µs status=200

DEBU[0007] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/me

ERRO[0007] Invalid principal                             component=token_auth method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/me

INFO[0007] Response: Forbidden                           component=server method=GET remote_addr=172.230.69.249:63783 response_time=65.637µs status=403

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/oauth/generic/login

INFO[0008] Response: Temporary Redirect                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=172.444µs status=307

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/oauth/generic/callback?code=4f84f382be79091a1cb0&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTg0OTUyMzksImlhdCI6MTU1ODQ5NDYzOSwibmJmIjoxNTU4NDk0NjM5LCJzdWIiOiJlbm95a0xQeUVaNWlNQnRaUnJpMjZnZkNlRk44YVB3RmdSbHpyRWZBZXBZPSJ9.cAcdPB8INi2lW_iyWXtH1VCVxZqDw5oVBY6BWErZG10

ERRO[0008] Unable to get principal identifier json: cannot unmarshal object into Go value of type []*oauth2.UserEmail  component=auth method=GET remote_addr=172.230.69.249:63783 url=/oauth/generic/callback?code=4f84f382be79091a1cb0&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTg0OTUyMzksImlhdCI6MTU1ODQ5NDYzOSwibmJmIjoxNTU4NDk0NjM5LCJzdWIiOiJlbm95a0xQeUVaNWlNQnRaUnJpMjZnZkNlRk44YVB3RmdSbHpyRWZBZXBZPSJ9.cAcdPB8INi2lW_iyWXtH1VCVxZqDw5oVBY6BWErZG10

INFO[0008] Response: Temporary Redirect                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=195.251173ms status=307

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/login

INFO[0008] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/login

INFO[0008] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=2.4031ms status=200

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/src.07fe3051.css

INFO[0008] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/src.07fe3051.css

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63787 url=/src.a8562dfd.js

INFO[0008] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63787 url=/src.a8562dfd.js

INFO[0008] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=42.371979ms status=200

DEBU[0008] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/Roboto-Regular.f82a1950.ttf

INFO[0008] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/Roboto-Regular.f82a1950.ttf

INFO[0008] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=28.712192ms status=200

INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63787 response_time=352.807987ms status=200

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/worker.5a2f829b.js

INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/worker.5a2f829b.js

INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=20.0322ms status=200

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1

INFO[0009] Response: Moved Permanently                   component=server method=GET remote_addr=172.230.69.249:63783 response_time=71.275µs status=301

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/

INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=173.607µs status=200

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/me

ERRO[0009] Invalid principal                             component=token_auth method=GET remote_addr=172.230.69.249:63783 url=/chronograf/v1/me

INFO[0009] Response: Forbidden                           component=server method=GET remote_addr=172.230.69.249:63783 response_time=175.872µs status=403

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/auth-logo.63b44c2a.svg

INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/auth-logo.63b44c2a.svg

DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63787 url=/auth-bg.dfe11863.svg

`INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63787 url=/auth-bg.dfe11863.svg`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=572.518µs status=200`

`DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63783 url=/Roboto-Thin.cf3be4a0.ttf`

`INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63783 url=/Roboto-Thin.cf3be4a0.ttf`

`DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63789 url=/Roboto-Black.4c9983d4.ttf`

`INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63789 url=/Roboto-Black.4c9983d4.ttf`

`DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63791 url=/Roboto-Bold.95244466.ttf`

`INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63791 url=/Roboto-Bold.95244466.ttf`

`DEBU[0009] Request                                       component=server method=GET remote_addr=172.230.69.249:63790 url=/icomoon.05bfd89e.woff2`

`INFO[0009] Serving assets                                component=server method=GET remote_addr=172.230.69.249:63790 url=/icomoon.05bfd89e.woff2`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63790 response_time=1.186028ms status=200`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63783 response_time=39.033009ms status=200`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63787 response_time=76.018335ms status=200`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63789 response_time=41.943661ms status=200`

`INFO[0009] Response: OK                                  component=server method=GET remote_addr=172.230.69.249:63791 response_time=39.502529ms status=200`

**Comment by russorat** [comment]
@gbialas @dhaval-pandya @livneniv @ceastman-ibm  has anyone tried the solution from @j-sokol ?

**Comment by camccar** [comment]
I also have this issue

**Comment by russorat** [comment]
@camccar have you tried the solution from @j-sokol ?

**Comment by vteran93** [comment]
I also have the problem, but I am running locally with a self-signed certificate and my personal github account.

**Comment by sranka** [comment]
GHE enterprise can be configured with the help of https://github.com/influxdata/chronograf/issues/4085#issuecomment-492276993 , personal github works fine to me according to https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/#configure-github-authentication. The previous comment most likely shows a failure in TLS handshake with  https://github.com. The certificates can be trusted 
- in a certificate store (varies between OSs), SSL_CERT_DIR environment variable can point to certificate directory on Linux
- a file with trusted CA certificates can be set up with GENERIC_ROOT_CA env var
- certificate verification can be turned off with GENERIC_INSECURE=true environment variable
