### ISSUE TITLE
Bug OAuth 2.0 - Google

### ISSUE THREAD

**Issue by JulienChampseix** [influxdata/chronograf#4086]
Hi Teams,

I have installed chronograf version bellow : 

**chronograf -v**
`2018/08/02 09:17:58 Chronograf 1.6.0 (git: 805580e01ab2a12516b081d69556f328fcd9fa3f)`

I have set google Oauth 2.0 credentials on my google developpers console.

When i launch chronograf like that : 
`chronograf -r --host 0.0.0.0 --port 8888 --token-secret XXXXXX --google-client-id $GOOGLE_CLIENT_ID --google-client-secret $GOOGLE_CLIENT_SECRET --google-domains $GOOGLE_DOMAINS --public-url 'http://XXXXX.XXXXX.fr:8888' -b /var/lib/chronograf/chronograf-v1.db -c /usr/share/chronograf/canned --log-level debug`

I'm getting this error : 

```
DEBU[0279] Request                                       component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/oauth/google/login
INFO[0279] Response: Temporary Redirect                  component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 response_time=223.326µs status=307
DEBU[0286] Request                                       component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/oauth/google/callback?state=XXXX&code=XXXX
INFO[0286] found an extra id_token, but option --useidtoken is not set  component=auth method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/oauth/google/callback?state=XXXX&code=XXXX
INFO[0286] User julien@XXXXX.fr is authenticated  component=auth method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/oauth/google/callback?state=eXXXX&code=XXXX
INFO[0286] Response: Temporary Redirect                  component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 response_time=333.87906ms status=307
DEBU[0287] Request                                       component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/favicon.ico
INFO[0287] Serving assets                                component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 url=/favicon.ico
INFO[0287] Response: OK                                  component=server method=GET remote_addr=XXX.XXX.XXX.XXX:46553 response_time=2.241054ms status=200
DEBU[0288] Request                                       component=server method=GET remote_addr=XXX.XXX.XXX.XXX:42936 url=/chronograf/v1/
INFO[0288] Response: OK                                  component=server method=GET remote_addr=XXX.XXX.XXX.XXX:42936 response_time=247.682µs status=200
DEBU[0288] Request                                       component=server method=GET remote_addr=XXX.XXX.XXX.XXX:42936 url=/chronograf/v1/me
ERRO[0288] Error message This Chronograf is private. To gain access, you must be explicitly added by an administrator.  component=server http_status =403
INFO[0288] Response: Forbidden                           component=server method=GET remote_addr=XXX.XXX.XXX.XXX:42936 response_time=235.629µs status=403
```

As you can see i got this error : 
`ERRO[0288] Error message This Chronograf is private. To gain access, you must be explicitly added by an administrator.  component=server http_status =403`

So i can't sign as admin or user and i'm always redirect on the main login page of chronograf having the Google Login button (used for choose my right gmail account).

**Comment by JulienChampseix** [comment]
@russorat some can qualify this bug in influxdata team ?

**Comment by russorat** [comment]
@JulienChampseix i'm checking with the team. based on the logs, it looks like the OAuth part is working, but the email you entered doesn't have an account in Chronograf. Were you using this `chronograf-v1.db` with another auth enabled chronograf before this? When moving from a no-auth db to auth, the first user that logs in should be granted superadmin status, but that isn't happening here. Is there another email that you've used to log into this instance before?

**Comment by jaredscheib** [comment]
@JulienChampseix, as @russorat said, this behavior occurs when you are attempting to connect to an instance of Chronograf where your identity has not been added as a user. You'll need to ask whoever set up that instance, or any SuperAdmin or Admin, to add you as a user with your Google email, and then you should be able to access Chronograf as expected.

**Comment by jaredscheib** [comment]
Closing until we hear more information. Let us know if this does not resolve this issue, @JulienChampseix -- thanks!

**Comment by JulienChampseix** [comment]
@jaredscheib @russorat any news on this issue ? can you reopen it or tell me how to solve it ?

**Comment by JulienChampseix** [comment]
You can definitly close it. I found the section to put superadmin soon connected over Google Auth. Sorry for the noise and thanks for your support.

**Comment by jaredscheib** [comment]
Glad you figured it out, @JulienChampseix.

**Comment by disha1104** [comment]
Hi @JulienChampseix , I am facing the same issue, can you help with the fix?
