### ISSUE TITLE
Proposal: Web Page Cell Type

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#4094]
This will be required in order to convert the current Status dashboard to an editable dashboard. Intended to replace the current Getting Started widget in the status dashboard with a cell that can display a web page (in our case, the docs site). 

![screen shot 2018-08-02 at 2 56 26 pm](https://user-images.githubusercontent.com/2433762/43613658-0a3b1e5c-9665-11e8-8400-144fd57fd4b3.png)

This will take some API work to accomplish, so getting the proposal process started here.

As far as I know there would only be a single input to configure this cell type: `URL`

- [ ] Needs SVG icon

**Comment by russorat** [comment]
Things we might consider:
 - Page title as Cell title?
 - SSL considerations (hopefully not)
 - What do we display if the page 404s or fails to load?
 - Does the page get re-fetched at a regular interval? i think yes, but maybe that's handled by dashboard time
 - How do scrolls work?
 - Can you use template variables in the URL?
 - How to protect against malicious code?
 - Maybe some ability to match the styles of Chronograf (do we publish recommended CSS for the page or something?)

**Comment by russorat** [comment]
This issue was moved to influxdata/platform#2041
