### ISSUE TITLE
Convert Status Page dashboard to Editable Dashboard

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#4095]
We want chronograf 2.0 to ship with this dashboard included, so the dashboards index has something in it and the user can learn about dashboards by inspecting the pre-built Status Dashboard.

- [ ] Create RSS Feed cell type to replace newsfeed widget #4093 
- [ ] Create Web Page cell type to replace getting started widget with Docs website #4094 
- [ ] Replace Alerts in last 30 days widget with Table

Related to https://github.com/influxdata/chronograf/issues/4077

**Comment by russorat** [comment]
this is no longer needed
