### ISSUE TITLE
missing indication that the graphs on the page are still loading

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4098]
as a chronograf user
with viewer permissions or higher
when i change the time range on a dashboard in 1.6.1
i would like to have an indication that the graphs on the page are still loading.

![kapture 2018-08-03 at 8 45 16](https://user-images.githubusercontent.com/4805997/43652360-d64337a2-96f9-11e8-9e97-d66e73388fb6.gif)

**Comment by jaredscheib** [comment]
there used to be a triple dot, animated "loading" icon that would appear while loading
