### ISSUE TITLE
Dashboard URLs - copying relative time over absolute time fails to update graph or controls

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4111]
build **Nightly Build**

build time **201808040043**

Bowser **Chrome 68**

```
$ chronograf --version
2018/08/06 16:14:59 Chronograf 1.4.3.0~n201808040043 (git: 51d3e418b1eb0eefdd966a5fe5e239e5f4c89fe4)
```

_Use Case_

1. Create a dashboard and a graph with historic data of about a year old.
1. Set the time range for the graph to absolute values.  For example the lower calendar is 28 days in the past and the upper calendar is 14 days in the past. The graph is redrawn to show the new thresholds.
1. In the address bar paste in a URL with a relative value. e.g. ```http://localhost:8888/sources/2/dashboards/10?lower=now%28%29%20-%201h```
1. Press ENTER or use 'paste and go' to get the page to refresh. 

The graph fails to update as well as the current value in the time range control. 

_Expected Behavior_

That the graph will be updated when the page reloads.

_Screenshots_

![urlrelativeoverabsolute01](https://user-images.githubusercontent.com/25881301/43722012-a392cafa-9994-11e8-9aaa-51e0cbfc0657.png)
![urlrelativeoverabsolute02](https://user-images.githubusercontent.com/25881301/43722013-a3adeccc-9994-11e8-8bab-21cabfcecd26.png)
![urlrelativeoverabsolute03](https://user-images.githubusercontent.com/25881301/43722014-a3cd59ea-9994-11e8-9cb2-8f295f288f2c.png)

_Notes_

Not sure if this is a regression.  Only came across this sequence today, as previously I was testing first with relative values and then absolute ones, which seems to work as expected.

**Comment by bthesorceror** [comment]
@russorat only thing that I was seeing when I tried to reproduce was that there was a slight delay to the change. I think that the fix for spinners will make it more clear what is happening here.
