### ISSUE TITLE
Flux results in a table graph

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4115]
as a chronograf user
with editor or higher permissions
when i build a query with flux
i would like to display the results as a table graph

applies to data explorer and editing a query on a dashboard

for designs see https://github.com/influxdata/chronograf/issues/4138

**Comment by ischolten** [comment]
The flux table should still have the same left panel to click through the different tables but the table on the right should use the TableGraph component. The main thing is that the Table view of flux results in the DE, CEO, and in a dashboard cell should be the same.
