### ISSUE TITLE
Add tags to the annotation hover thingy

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4131]
as a chronograf user
when i hover over an annotation and view the name
then i would like to also see the tags associated with that annotation

**Comment by chnn** [comment]
Could probably use this design from a while back. 

<img width="762" alt="39221754-bbd78720-47ed-11e8-828b-9b73b250b9da" src="https://user-images.githubusercontent.com/638955/43931950-2c3e5460-9bf6-11e8-8a04-460591bdd0c6.png">


Thoughts @alexpaxton?

**Comment by alexpaxton** [comment]
@russorat thingy??

@chnn yeah I think something like that could work, we could pair on it and knock it out

**Comment by alexpaxton** [comment]
Presentational work done in `annotations/tag-list` branch

![annotation-tags](https://user-images.githubusercontent.com/2433762/44055729-2099c8bc-9efb-11e8-9c80-5c4754381577.gif)

Tag list is hardcoded into `AnnotationPoint` component
