### ISSUE TITLE
Ability to click to filter on annotation tags

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4132]
as a chronograf user
with viewer permissions or higher
when i hover over an annotation and see the tags and click on a tag
then i would like the annotations filter to be applied to the dashboard

**Comment by alexpaxton** [comment]
![annotation-tags](https://user-images.githubusercontent.com/2433762/43986626-b0bdc0f4-9cc8-11e8-8f7f-c00b046c4d3f.gif)

I have a mocked out UI on the branch `annotations/tag-list`

**Comment by alexpaxton** [comment]
See https://github.com/influxdata/chronograf/issues/4131

**Comment by chnn** [comment]
Closing in favor of #4131
