### ISSUE TITLE
Annotations: pressing enter should add the tag and move cursor to the next tag.

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4135]
when adding tags to an annotation, you should be able to add multiple tags without using the mouse.

**Comment by alexpaxton** [comment]
Save the user these couple clicks:
![annoation-tag-enter](https://user-images.githubusercontent.com/2433762/44056162-45b69160-9efc-11e8-8098-aa8bbe856d4a.gif)

Also, if when either input in a key/value pair is blurred, if both are blank then remove the tag. (Idea is to save the user the effort of deleting blank pairs.

We could also just filter out the blank pairs after the user clicks save, that way they don't need to think about it at all
