### ISSUE TITLE
Dashboards - lower resolution - button labels spill out of element boundaries 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4147]
bulid **Nightly Build**

buld time **n201808082330**

Browser **Chrome 68**

Resolution **1024 x 768**

```
chronograf --version
2018/08/09 10:22:57 Chronograf 1.4.3.0~n201808082330 (git: c19a6001b0002ddd519d6a6df79c882e28f6eb81)
```

*Use Case*

With resolution set to 1024 x 768

1. Click on dashboards
1. Click on create dashboard 

When the create dashboard page loads the labels "Add Cell" and "Template Variables" spill out of the button boundaries.  See screenshot below. 

*Expected Behavior* 

That in smaller resolution screens the labels will be shortened, but might still be available in full as hover text. 

*Screenshots*

![lowresbuttonlabels01](https://user-images.githubusercontent.com/25881301/43888314-9ee2fdc0-9bc1-11e8-9eff-b20784e45f4c.png)

**Comment by karel-rehor** [comment]
Related issue #4146

**Comment by alexpaxton** [comment]
Should be fixed by https://github.com/influxdata/chronograf/pull/4164
