### ISSUE TITLE
Y-Value's Format "Raw" setting doesn't seem to persist over dashboard reloads

### ISSUE THREAD

**Issue by imrehg** [influxdata/chronograf#4168]
When setting a graph's "Y-Value's Format" on a dashboard to `Raw`, if I navigate away to another dashboard and come back, the format is reset to `K/M/B`.

On the other hand, both `K/M/B` and  `K/M/G`  settings do seem to persist over dashboard reloads.

This is in Chronograf 1.6.1.

**Comment by icoma89** [comment]
I am observing the same behaviour on 1.7.3

**Comment by mattse** [comment]
I have the exact same issue. Can this be fixed? Seems like something simple.
