### ISSUE TITLE
Configuration - Connect button no longer redirects user to "hosts" view

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4170]
build **Nightly Build**
build time **n201808110012**
```
$ chronograf --version
2018/08/13 13:09:02 Chronograf 1.4.3.0~n201808110012 (git: 507cf7a36546ada10d43408fb348e564a7559ae7)

```

*Use Case*

I see that a lot of the configuration logic surrounding connections and configuration has been replaced with a three step wizard.  I've updated selenium tests accordingly.  However... 

1. create a new connection but not as 'default'
1. In the configuration page click the button 'connect' for the new connection 

The button text changes from 'connect' to 'connected' and its background color is now green. 

*Expected behavior*

In the past when the 'connect' button was clicked, the user was redirected to the 'hosts' page.  

The question now is, which is the correct behavior.  Should the hosts page be opened, or should the user stay on the Configuration page?

There are a few selenium tests that rely on the redirect behavior.

**Comment by russorat** [comment]
this is the desired behavior. we will have to update the tests.
