### ISSUE TITLE
Configuration - create new connection wizard ends with automatically connected to new connection

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4171]
Build **Nightly Build**
Build time **n201808110012**
```
$ chronograf --version
2018/08/13 13:09:02 Chronograf 1.4.3.0~n201808110012 (git: 507cf7a36546ada10d43408fb348e564a7559ae7)
```
*Use Case*

In the Configuration page...

1. Click Add Connection
1. Do not check new connection as Default Connection
1. Follow wizard to end, adding Kapacitor as required. 

After successful completion the new connection is automatically connected.  The previous connection is abandoned. 

*Expected behavior*

Previously the new connection was not automatically connected.  The user had to explicitly connect it after creation.  There are a number of Selenium tests based on the previous functionality. 

Which is the correct behavior now? 

*Screenshots*

![nondefaultconnection01](https://user-images.githubusercontent.com/25881301/44030154-36caff8e-9f00-11e8-855c-b99081ae9a28.png)
![nondefaultconnection02](https://user-images.githubusercontent.com/25881301/44030155-3707d8be-9f00-11e8-84fa-09a13c9e3019.png)
![nondefaultconnection03](https://user-images.githubusercontent.com/25881301/44030156-374511a2-9f00-11e8-8614-7fa9532c62c5.png)
![nondefaultconnection04](https://user-images.githubusercontent.com/25881301/44030157-37cb62ac-9f00-11e8-9667-545d8f5c994c.png)

**Comment by russorat** [comment]
this is working as designed. we should update the test
