### ISSUE TITLE
Log in Data Explorer doesn't work

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4178]
as a chronograf user
with view permissions or higher
when i select "log" scale in the line graph config
then i would like the scale of the graph to be a log scale.

**Comment by jaredscheib** [comment]
I'm seeing this in the CEO only when for the `timeSeries` y value range, the lower bound is less than `.1`, whether 0 or negative.

This is a known, open bug in dygraphs: https://github.com/danvk/dygraphs/issues/661 & https://stackoverflow.com/questions/32609202/dygraphs-using-valuerange-with-logscale (demoed at http://jsfiddle.net/85f1ga5e/).

It seems that to get this working, we'd need to either fix dygraphs, or create a dygraphs workaround, such as not allowing the selection of `Logarithmic` unless there's time series data with a range that supports the logarithmic option in dygraphs as-is.

**Comment by russorat** [comment]
@jaredscheib thanks for investigating. let's de-prioritize this for now.
