### ISSUE TITLE
improve the host list query using a where clause

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4186]
the current host list page query may be able to be improved by adding a where clause to the query to restrict the results to a specific timerange. We should investigate this as a short term fix until we redesign the page.

It's the final query `SHOW TAG VALUES WITH KEY = "host"`

this should have a where clause such as `where time > now() - 1h` to limit the scan.

Also, we may want to add a date picker to this page that impacts this time range.

**Comment by ebb-tide** [comment]
I though @nhaugo  did this?

**Comment by russorat** [comment]
yes. i see a `now() - 10m` on the query
