### ISSUE TITLE
Hide/show tabs, hide/show flux queries

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4187]
as a user of chronograf
with editor permissions or higher
when i am building a cell with multiple queries (flux or influxql)
then i would like a way to hide or show a specific query temporarily for debugging.

**Comment by alexpaxton** [comment]
I built the presentational part of this work on the branch `feature/show-hide-queries`
![toggle-tab-visibility-2](https://user-images.githubusercontent.com/2433762/44054742-4a7caa4e-9ef8-11e8-90d0-80c81766c01d.gif)

I added the prop `isQueryVisible` to the type `QueryConfig`. The toggle function is located in `CellEditorOverlay` next to `handleDeleteQuery`.

**Comment by russorat** [comment]
this is being added to the explorer in platform

**Comment by hraftery** [comment]
When will this be available for download, or is it only available for Flux (not InfluxQL)? We have 1.7.9 but I don't see it in the changelog for the latest (1.7.12). Is it in nightly?

**Comment by russorat** [comment]
@hraftery we have added this to the latest influxdb 2.0 alpha data explorer. we do not have plans to add it to the 1.x data explorer.

**Comment by hraftery** [comment]
Thanks @russorat , saves me looking! To give you a sense of how much I'm looking forward to this - I was actually expecting queries to be graphed separately in a data explorer and being able to combine them into a single graph to be by exception. When I'm exploring data I generally want to run a bunch of separate queries - some saved for future use, some ad hoc - so I can understand what's appearing in various formats across various measurements in various time slices. Only once I've finished exploring would I generally bother creating a graph, let alone one that combines multiple queries. I fully realise I could be the exception here!

**Comment by russorat** [comment]
thanks for the additional background. I agree, that sounds awesome. i've attached your comment to two new issues which I think will help enable that use case. Please comment on those issues if i've missed anything.
