### ISSUE TITLE
always scroll to and expand the measurement that is being queried

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4209]
as a chronograf user
with editor permissions or higher
when I have multiple influxql queries and click between the different queries' tabs,
I would like to always see the measurement that is in the query open and scrolled to in the middle window

**Comment by jaredscheib** [comment]
Where in the application is this desired? In the now-unified CEO/DE? Which are the same component now?

**Comment by russorat** [comment]
This would be in the unified DE/CEO, when a user selects a DB in influxql. If the query is able to be parsed by us, then the middle component should always scroll to the current measurement open.

in this example, it's the netstat measurement
![image](https://user-images.githubusercontent.com/4805997/45372286-714c7b80-b5a1-11e8-9d24-36ba8ed92110.png)
