### ISSUE TITLE
failed to parse InfluxQL query: found (, expected identifier at line 1, char 20

### ISSUE THREAD

**Issue by CoderOverflow** [influxdata/chronograf#4239]
Hi,

the influxQL can be executed in the command line window successfully, but cannot be saved in the tickscript.

 select data1 from (select sum(Bytes_Received_persec) as "data1" FROM "telegraf"."autogen".win_net where time > now() - 32m and time < now() group by time(1m)) where time < now() - 1m limit 30 offset 1
![hdfp0z3h 6ibknltg7b b o](https://user-images.githubusercontent.com/29338660/44251996-1dae7280-a22d-11e8-914a-0841c72bc6c4.png)

![c 833f_s d 7ip3fyyew8d8](https://user-images.githubusercontent.com/29338660/44251926-d3c58c80-a22c-11e8-9f68-70d3a1d82d87.png)

![mdn f 5 z0 a7 tcfdn s](https://user-images.githubusercontent.com/29338660/44251944-e50e9900-a22c-11e8-9af5-e8a65e4903da.png)

**Comment by russorat** [comment]
@CoderOverflow thanks for reporting! unfortunately, Kapacitor and tickscripts don't currently support subqueries (https://github.com/influxdata/kapacitor/issues/1198). 

Based on https://community.influxdata.com/t/kapacitor-and-subqueries/175 and https://community.influxdata.com/t/nested-queries-in-kapacitor/1380/8, there might be a way for you to rewrite the query to work.

I think https://community.influxdata.com would be a good place to open a question and see if anyone can help with a way to solve this.

Thanks!
