### ISSUE TITLE
logviewer not showing full textbox

### ISSUE THREAD

**Issue by Motzyy** [influxdata/chronograf#4240]
Just found out that the textbox for log messages is just as big as the columns of log.
So it can possibly happen that you don't have full access to the test as shown in picture one.

![bug](https://user-images.githubusercontent.com/31078765/44258727-f1382d80-a20f-11e8-818c-6dc155501a02.PNG)

If having enough log messages this won't be a problem anymore.

![bug2](https://user-images.githubusercontent.com/31078765/44258729-f1382d80-a20f-11e8-8cb9-60e8b1ba4a2d.PNG)

Guess this kinda buggy.

**Comment by russorat** [comment]
@Motzyy thanks for reporting! we will take a look!

**Comment by alexpaxton** [comment]
I can start working on a fix for this, I think I have a solution

**Comment by chnn** [comment]
I wonder if we could use [Portals](https://reactjs.org/docs/portals.html) for this.
