### ISSUE TITLE
spike: how can we load and visualize time series faster?

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#4242]
goal: improve the performance of loading and viewing timeseries data in chronograf

### possible bottlenecks

1. too many http requests
   - overhead of opening each connection
   - browser has a hard limit of 6 concurrent http requests
      
      <img width="1059" alt="max http concurrency example" src="https://user-images.githubusercontent.com/638955/44286359-ae7d5200-a21d-11e8-8479-9055086f70b4.png">

2. inefficient wire format
3. JSON and/or CSV format burdensome to parse in browser
4. slow render and rerender times in visualization component

### steps taken to address these bottlenecks

1. send all data over a single websocket connection
2. compression
   - run length encode times
   - send all other values as floats rather than doubles (easy lossy compression)
   - no attempt was made to use general purpose compression (e.g. DEFLATE, Snappy). test timeseries were generated with a random distribution, so little benefit to using these general purpose algos. may benefit for actual timeseries data (e.g. has many repeated values, dropouts, etc.)
3. send timeseries data in column format, each column an arraybuffer
4. replace our visualization component with a custom component that leverages a [polyline simplification algorithm](https://beta.observablehq.com/@chnn/running-ramer-douglas-peucker-on-typed-arrays)

this work is on the [`perf`](https://github.com/influxdata/chronograf/tree/perf) branch.

### test setup

- used `influx_stress` to generate 30 timeseries with ~1M points each
- created a faux-dashboard UI that allowed swithcing between our current implementation (fetch data over http, dygraphs) and a new experiemental implementation (fetch data over websocket, custom vis).
- benchmarked several metrics with ms timestamp precision and 5 trials each
- benchmarked using my 2 core MBP in SF. server was on east coast.

### results

16 graphs, 2200 values each, 5 trials:

|     | current implementation | experimental implementation | experimental improvement |
| --- | ---------------------: | --------------------------: | -----------------------: |
| serialize query results + send to browser | 931 - 1340 ms |  2365 - 2468 ms | slower! |
| parse data + first render | 9350 - 9395 ms | 286 - 316 ms | ~ 29x - 31x |
| redraw on resize | 1739 - 9102 ms | 44 - 151 ms | ~ 11x - 206x |

1 graph, 216,000 values, 5 trials:

|     | current implementation | experimental implementation | experimental improvement |
| --- | ---------------------: | --------------------------: | -----------------------: |
| first query back from influx until all graphs rendered |  2778 - 3218 ms | 1849 - 2229 ms | ~ 1.2x - 1.74x |
| redraw on resize |  150 - 220 ms | 15 - 20 ms | ~ 10x - 14x |

### conclusion

- new server implementation an improvement, but optimizations are marginal in light of query time from influx. do not recommend that we pursue this at this time. if we ever get more powerful or faster programmatic access to results from influxdb (e.g apache arrow files rather than JSON over HTTP, or a long lived “cursor” style result), it's worth revisiting 
- new visualization component was a drastic improvement
- new visualization component leveraged the fact that data was sent as array buffers, which required little to no decoding/deserialization step and could be rendered as visualizations with minimal reallocations. we don't receive data in this nice format unless we use something like the websocket based approach. we can, however, integrate this work with brandon's PR, so that parsing http requests into an array buffer can happen in a webworker (off the main rendering thread)

**Comment by jaredscheib** [comment]
thanks @chnn. a grpc api could also speed things up between ui server and flux/influx if/when they have grpc server.

**Comment by jaredscheib** [comment]
and would batching multiple client requests into one possibly help?
