### ISSUE TITLE
Reconcile ProtoboardCell and DashboardCell additions (i.e. Note)

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4256]
One of the comments on #4217 that we didn't put more work into for the purposes of time constraint was to make `ProtoboardCell` the same as `DashboardCell` to prevent drift. Since then, `DashboardCell` has been updated with a couple of fields related to the new `Note` feature. We should discuss reconciling this.

Thoughts, @desa ?

**Comment by desa** [comment]
Yeah, I'd make them the same so they don't drift.

**Comment by russorat** [comment]
can we combine with with https://github.com/influxdata/platform/issues/674 ?

**Comment by desa** [comment]
@russorat should work from my point of view.
