### ISSUE TITLE
Spike: investigate fanout queries to see how best to tackle #4248

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4262]

**Comment by OfTheDelmer** [comment]
Updating the initial search to incrementally build up results should be a day of work
    * We can set table data with the first nonempty interval of results that are found
    * We incrementally call concat with newer results until we reach either the count threshold or time limit by selecting consecutive intervals.
    * We might need to add follow up chores to improve  table rendering performance for untruncated messages

We should scope this task to rendering the initial results and discuss what changes should be made to scrolling fetches for more data.

**Comment by nhaugo** [comment]
> Currently the upper and lower bounds of each query exponentially expands from a fixed inner bound to a farther and farther outer bound, which means that we receive overlapping results in the UI.

This is a bug and can be separated out into its own issue. 

> We progressively yield and concatenate newer results until we reach either the (currently extant) count threshold or time limit.

👍 

> We set table data with the first nonempty interval of results that are found. Currently all data is gathered, and then the table is set with that data. This deletes all old data and then displays the new data. 

New data should be appended

> Will users who are debugging want to be able to customize how the log viewer queries?
Ideally not, the log viewer should be attempting to optimize this. The optimization should look for two things: 1) How long is the query 2) how much data is in the result
We should look for some "best" interval then just keep chunking on that.

If the query is too slow the time chunk size should be reduced, same if their is more data than we need to fill the screen.

> The current time threshold is 15 days. The UX around this is confusing because there is a DateTime picker for the Histogram and for the Logs, and it's not necessarily clear which one applies to which.

Having any time frame is weird. The system should just keep going back or forward indefinitely. If the data scrolls off the screen the query loop should be paused.
 
Queries should also be paused if the pause button is pressed.

**Comment by OfTheDelmer** [comment]
> > Currently the upper and lower bounds of each query exponentially expands from a fixed inner bound to a farther and farther outer bound, which means that we receive overlapping results in the UI.

> This is a bug and can be separated out into its own issue. 

There are two data fetching phases currently: search and fetch. The initial search phase, described above, is the one that increases it's outer bound farther and farther out. However, this search phase is just a `count` query.  Once a count is found count over a set threshold it provides the corresponding time bound to the next fetching phase that retrieves all the data in that interval. *This would cause a data overlap* if we just dropped a fetch inside the looping logic used to count logs, but should be avoidable in a refactor.

**Comment by jaredscheib** [comment]
Work tracked by #4248.
