### ISSUE TITLE
autorefresh has NO response

### ISSUE THREAD

**Issue by nodejscss** [influxdata/chronograf#4265]
The chronograf dashboard put in onsen ( https://onsen.io ) page like as
<html>
<body>
<template>
<ons-page>
<iframe src="http://10.10.10.100:8888/sources/7/dashboards/1?present=true&lower=now%28%29%20-%2015m#"></iframe>
</ons-page>
</template>
</body>
</html>
, that can autorefresh on the PC's browser and iOS and Android browser.

However, That can NOT auto refresh on the iOS and Android 's APP , which created using cordova ( cordova.apache.org ) . why ?

I do NOT know the reason. Please help me how to fix that.

Thank you.

**Comment by russorat** [comment]
@nodejscss thanks for the issue. I'm not familiar with those applications and I know we haven't tested them on there either. Seeing as they work properly on the desktop, i would assume it's a bug somewhere in onseen's app code that handles refresh. I recommend opening a ticket with them to see if they can help figure this out. If they come back with a change we can make to improve the performance in their app, we will consider implementing it.
