### ISSUE TITLE
Chronograf status misleading

### ISSUE THREAD

**Issue by Puneeth-n** [influxdata/chronograf#4267]
**docker image**: chronograf:1.6 telegraf:1.7.3

I have a `telegraf` docker container running that gets metrics from AWS MYSQL and AWS Elasticsearch. This `telegraf` container does not have a `system` and `cpu` inputs plugin enabled.

The metrics are collected correctly. However, `Chronograf` reports the status in the Host list page as Red. Isn't this however misleading?

**Comment by russorat** [comment]
@Puneeth-n i agree this is misleading. we have plans to update the host list page to be more configurable in the future. You can follow #682 for resolution.

**Comment by Puneeth-n** [comment]
@russorat Thanks
