### ISSUE TITLE
add all tags as columns in the logviewer

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4278]
as a logviewer user of chronograf
with editor permissions or higher
when i view the log viewer page
then i would like the ability to see all the tags and values i have in the syslog measurement, not just the syslog ones

we need to allow the ability to view all the tags in the syslog measurement in the log viewer table. the columns should show up along with the standard syslog tags and values.

One of the cool things about storing your logs in the same db as your metrics, is that you are able to use the same tags to filter the results and see only the logs you need. 

This would allow users to filter on additional tags from the syslog measurement. these tgs and values would show up just like the standard syslog ones and be able to be re-aranged, renamed, hidden/shown, just like all the other columns.

These would also be clickable and filterable so that users could build deep links into this page after #4277 is completed.

**Comment by russorat** [comment]
@JulienChampseix unfortunately i don't think this will make it into the 1.7 release. We have added a ton of improvements to the table graph component to make performance of showing logs on dashboards much better. Does that help at all?

**Comment by dominikkv** [comment]
+1

**Comment by maxlein** [comment]
+1
Also is it possible to use severity NAMES and application name in a table view? So listing tags in tables?  
This would be a huge benefit as we are looking at metrics and logs at the same time, and process id alone is not that usefull
