### ISSUE TITLE
Wire up Kapacitor Alert Endpoint Test buttons

### ISSUE THREAD

**Issue by pauldix** [influxdata/chronograf#428]
Kapacitor now has an API to test Alert Endpoints. The Sources -> Kapacitor screen should have test buttons for each of the Alert Endpoints that use this API: https://github.com/influxdata/kapacitor/pull/970

**Comment by jaredscheib** [comment]
Is https://github.com/influxdata/chronograf/issues/301 related to this?

**Comment by russorat** [comment]
- [ ] Correctly handle errors coming back from Kapacitor indicating that the test did not succeed and display the error message to the user. see SMTP endpoint for an example
 - [ ] Add "to" field for the SMTP config to allow for testing SMTP send

**Comment by russorat** [comment]
@ebb-tide tested every integration i could. the only issues i found are in the previous comment.  🍰

**Comment by ebb-tide** [comment]
needs backend support to add "to" field to SMTP config @goller

**Comment by goller** [comment]
@ebb-tide This would need to be added to kapacitor's smtptest.

@nathanielc Is it possible to add a `to` field to kapacitor's smtptest?

**Comment by nathanielc** [comment]
@goller The SMTP test options has a `To []string `json:"to"` field.

**Comment by russorat** [comment]
![image](https://user-images.githubusercontent.com/4805997/35947888-d8c05c82-0c1e-11e8-84c4-8f59c0113b03.png)
👏 👏 👏
