### ISSUE TITLE
Web worker node module errors in console

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4285]
Getting a lot of these in the console for various node module files: `worker.js:39 Uncaught Error: Cannot find module '../node_modules/lodash/sumBy.js`. Appears to be related to web workers.

**Comment by chnn** [comment]
may be fixed by https://github.com/influxdata/chronograf/pull/4315

**Comment by bthesorceror** [comment]
Cannot reproduce, appears to be fixed.
