### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by huyujie** [influxdata/chronograf#4289]
I installed tick stack in the same server with chronograf(1.3.10.0) ,kapacitor(v1.3.3).

when I play around in the kapacitor alert rules page and refresh again and again,I notice that the number of chronograf and kapacitor socket established grow up. 

I also notice that the similar question was resoloved in #942,with chronograf version is v1.2,maybe this is a different problem? @goller

**Comment by russorat** [comment]
@huyujie thanks! Could you try to reproduce with the latest 1.6.1 Chronograf?

**Comment by russorat** [comment]
@huyujie ok thanks! we will investigate.

**Comment by chnn** [comment]
@huyujie Could you provide some steps to reproduce this issue? I'm having trouble seeing it on my end. Are you on the _Alert Rule Builder_ page? Or the _TICKscript Editor_?

**Comment by russorat** [comment]
to repro:
1. connect chrono to a kapacitor
2. open the alert page that shows all the alerts / tickscript in kapa
3. run this command to monitor the open sockets: `watch "lsof -n -i | grep -e LISTEN -e ESTABLISHED | grep kapacitor | wc -l"`
4. refresh the page in chronograf and notice the number continues to increase.

**Comment by huyujie** [comment]
@chnn ok.
