### ISSUE TITLE
keep track of if the user selected untruncated log lines

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4293]
as a logviewer
with viewer permissions or higher
when i select that i want to see the logs untruncated
then that option is selected the next time i view those logs

we should store this for the user, not in the bolt db

**Comment by jaredscheib** [comment]
@russorat is storing this in localStorage sufficient? as of right now i don't believe we persist any user settings except on the user's `me`, which is not really the place to put this information, so this may be a bigger undertaking if persistence is desired on the server/db. cc @desa

**Comment by russorat** [comment]
storing in local storage is sufficient, not in the server.
