### ISSUE TITLE
meta query dropdown in the CEO/DE

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4300]
as a query builder
with viewer permissions or higher
when i use the data explorer or edit a cell
then i would like to view the meta query dropdown

![image](https://user-images.githubusercontent.com/4805997/44692136-637dee80-aa16-11e8-905b-7f17d82c4177.png)

**Comment by chnn** [comment]
Best to do this after https://github.com/influxdata/chronograf/issues/4299.

Adding query templates requires disabling certain visualization options. Visualization options aren't in the data explorer yet (#4299), but will be soon.

**Comment by jaredscheib** [comment]
so i have the meta query dropdown back, and the data explorer now looks like this. is this story just about getting the dropdown back? or also visualizing the potential results in the table in the case of `SHOW RETENTION POLICIES ON <db_name>`? or is there a different story for what to do once we have the dropdown back? <img width="761" alt="screen shot 2018-09-11 at 8 04 10 pm" src="https://user-images.githubusercontent.com/6403018/45394295-e2218100-b5fd-11e8-960a-62b0295c7244.png">

**Comment by russorat** [comment]
@jaredscheib good point. let's make a separate story for visualizing those.
