### ISSUE TITLE
Integration test panicking and not passing on Circle

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4310]
https://github.com/influxdata/chronograf/commits/flux/flux-editor-ceo

**Comment by desa** [comment]
@jaredscheib Just took a look and it seems like it's a typescript error. Am I looking at the correct thing?

https://circleci.com/gh/influxdata/chronograf/15142?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

![screenshot 2018-08-29 08 16 15](https://user-images.githubusercontent.com/1477539/44787031-eeb8ca80-ab63-11e8-8c79-04fef504376e.png)

**Comment by jaredscheib** [comment]
Apparently it eventually passed. It was a Go panic though. If I find it I'll let you know. Thanks~
