### ISSUE TITLE
Connection Wizard - able to set two connections as "Default" 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4322]
Build **Nightly Build**
Build time **n201808300221**
Browser **Chrome 68**
```
$ chronograf --version
2018/08/30 15:31:33 Chronograf 1.4.3.0~n201808300221 (git: 3e620a429cb93f0d9f847f530a82cbf000847b6d)
```
*Scenario*
1. With one connection already established, create a second connection in the Config tab and while doing so, set it as "default*
1. Now open the first connection. 
1. In the first wizard panel, set it as "default" and click "Update Connection" 
1. At the dashboard panel click "dismiss" 

Both connections are listed as default. 

*Expected Behavior*

Only one connection should be listed as "Default" 

*Screenshots*

![twodefaultconnections01](https://user-images.githubusercontent.com/25881301/44854942-388bd880-ac6a-11e8-9aac-8aa8e3b609d0.png)
![twodefaultconnections02](https://user-images.githubusercontent.com/25881301/44854943-388bd880-ac6a-11e8-954b-dd8edccc0ebe.png)
![twodefaultconnections03](https://user-images.githubusercontent.com/25881301/44854944-388bd880-ac6a-11e8-9492-e8046b974fc2.png)
![twodefaultconnections05](https://user-images.githubusercontent.com/25881301/44854945-39246f00-ac6a-11e8-9bec-54159225c0b5.png)

**Comment by karel-rehor** [comment]
Tagged as regression, when comparing how managing sources/connections behaved in the past.

**Comment by jaredscheib** [comment]
@russorat Do you want this to be resolved in just the client or both client and server? Is it supposed to be possible to have multiple default sources, such as possibly based on their architecture (1.x, 2.x)?

**Comment by jaredscheib** [comment]
Actually, in further investigating: when you refresh the page, the correct choice remains and the one that was formerly the default, is no longer the default. So if the desired behavior is that there be only 1 default, then this is just a problem on the ui.

**Comment by russorat** [comment]
there should only be one default.
