### ISSUE TITLE
Cannot visualize time series of constant value with logarithmic scale

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#4329]
Attempting to build a visualization in the CEO with a logarithmic scale for a time series of constant value throws the following error:

```
axis 0 of graph at [Dygraph [object HTMLDivElement]] can't be displayed in log scale for range [0 - NaN]
```

No visualization is rendered.

The error is due to a bug in [this method](https://github.com/danvk/dygraphs/blob/da2a028fc41e5573868358b3d9eda9826211d217/src/dygraph.js#L2417-L2596) in the Dygraphs charting library. In attempting to adjust the visible y-range of the the visualization to accommodate a constant value on a logarithmic scale, the method computes the log of 0.

**Comment by kyawthura18115** [comment]
Automobileengineeringservices@googlemail.com

**Comment by chnn** [comment]
I think it might be slightly different, as it's not for series whose y-value is below 0. I believe that we work around #4178 here: 

https://github.com/influxdata/chronograf/blob/bd1bd95f5450d840ce617389c6b8b7bbd1e80d36/ui/src/shared/components/Dygraph.tsx#L356-L359
