### ISSUE TITLE
Configuration Wizard - Connection Created despite clicking button "dismiss" 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4333]
Build **Nightly Build**
Build time **n201808310004**
Browser **Chrome 68**
```
$ chronograf --version
2018/08/31 16:30:28 Chronograf 1.4.3.0~n201808310004 (git: bd1bd95f5450d840ce617389c6b8b7bbd1e80d36)
```

*Use Case*
1. After creating an initial Influx Connection, open the configuration page and click "Add Connection".  The Wizard loads. Note that in the background there is still only the initial entry. 
2. Enter a URL in the Connection URL field.  Move the focus then to the password field. 

In the background the new entry appears. 

3. Click the button "dismiss" 

Returning to the Configuration page, the connection table now includes a new entry for the connection _just dismissed_

*Expected Behavior*

That the connection will be created when the wizard or the relevant step is explicitly completed (e.g. when clicking a button labled "Add Connection).  That when a procedure (potential transaction) is dismissed, then the state will be rolled back to what it was before the procedure/transaction was initiated. 

*Screenshots*
![connectioncreateddespitedismiss00](https://user-images.githubusercontent.com/25881301/44918731-00ed6100-ad3c-11e8-987f-0b607393eafe.png)
![connectioncreateddespitedismiss01](https://user-images.githubusercontent.com/25881301/44918732-0185f780-ad3c-11e8-9b12-d2759bf3f075.png)
![connectioncreateddespitedismiss02](https://user-images.githubusercontent.com/25881301/44918733-0185f780-ad3c-11e8-8be9-abe14932ed28.png)
![connectioncreateddespitedismiss03](https://user-images.githubusercontent.com/25881301/44918735-0185f780-ad3c-11e8-83f1-cc1fce36032b.png)

**Comment by ebb-tide** [comment]
The way sources are designed at the moment makes it so we can not get information about the source that we need without creating it, before user clicks `add connection` button. Future updates to sources resource will address this issue.
