### ISSUE TITLE
Ticks on y-axis misleading when viewing stacked visualization

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#4336]
<img width="422" alt="screen shot 2018-08-31 at 9 45 07 am" src="https://user-images.githubusercontent.com/638955/44925331-febae080-ad02-11e8-8552-5fe6d1b10586.png">

The y-axis ticks makes the purple series seem like it has a value of ~22, where the value is in fact 7.45.

**Comment by russorat** [comment]
@chnn what do you recommend instead? is there an example of how stacked data should be displayed that you have in mind?

**Comment by chnn** [comment]
Maybe the root issue is that stacked line charts in Chronograf look exactly the same as non-stacked line charts. Perhaps we could draw non-stacked line charts in the more traditional way—as lines with no filled area underneath. This would be my preference.

Another alternative would be to enforce a relative unit on the y-axis, like percentage. That way it's clear that the stacked areas represent a proportion of a whole.

Yet a third alternative would be to not draw y-ticks and rely on the hover legend, or only draw a tick at 0 and at the first series.
