### ISSUE TITLE
Simplify places in UI to specify a time period.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/chronograf#435]
Currently in the UI there are a total of 5 places a user can specify a time duration.

1. As the `Group by time` for an aggregate function on a field
2. As the `during the last X` for a threshold alert
3. As the `over X` for relative alerts
4. As the `compared to X before` for the relative alerts
5. As the `Create an alert if data is missing for X` in deadman alerts

Screenshots of each of these can be found below.

Of these 5 only 3 are needed. 1 is the same as both 2 and 3.

In summary each of the alert types should be as follows:

* the threshold alert should only have the option to select the `group by time`(1) if an aggregate function is picked, otherwise it has no meaning.
* the relative alert should have the `group by time`(1) option as well as the `compared to X before`(4) option. Again the `group by time` is only needed if an aggregate function was selected.
* the deadman alert is different. It should only have the `Create an alert if data is missing for X`(5) option. It should not even have the `group by time`(1) option. This is because the existance of data has nothing to do with the result of an aggregate function. So the deadman field selection should not allow an aggregate function to be selected.

Hopefully that is clear what should change.

In short remove 2 and 3 and prevent the selection of 1 in the deadman mode.

Screenshots of current UI elements in case it wasn't clear what each one was.

1. ![image](https://cloud.githubusercontent.com/assets/3771906/20148039/f5366d20-a667-11e6-9abf-8b21a1cc17b2.png)
2. ![image](https://cloud.githubusercontent.com/assets/3771906/20148048/01680f22-a668-11e6-9ba6-8b5edd2e8540.png)
3. ![image](https://cloud.githubusercontent.com/assets/3771906/20148053/0a714aac-a668-11e6-883c-137e9c268905.png)
4. ![image](https://cloud.githubusercontent.com/assets/3771906/20148060/15fd95ba-a668-11e6-93f5-4d9b4fe054e0.png)
5. ![image](https://cloud.githubusercontent.com/assets/3771906/20148063/1e982014-a668-11e6-8fa0-83bf02787edc.png)

**Comment by willpiers** [comment]
Removing the option labeled (1) for deadman would be a little tough. we could continue to allow it to be set in the UI and then just strip it from the query before sending it off, or the server can know to ignore it.

Removing (2) and (3) would be no problem

**Comment by goller** [comment]
@willpiers server is currently ignoring groupby for deadman

**Comment by nhaugo** [comment]
I think this issue can be closed, we resolved the important ones that @nathanielc pointed out. The only remaining redundancy is in the deadman, which as @goller points out, only the "values" section matters anyway. 

This is a bit confusing since we show the actual query in the "select a time series" section, if anything I think we should remove/hide that. If we decide that is a good idea I will open that under its own issue.
