### ISSUE TITLE
Configure Kapacitor - No Cancel button when editing Kapacitor

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4355]
Bulid **Nightly Build**
Build Time **n201809042321**
Browser **Chrome 68**

```
$ chronograf --version
2018/09/05 10:21:48 Chronograf 1.4.3.0~n201809042321 (git: 3f5850ddec306442efb363d8541a4e03f6b2bb2f)
```
*Use Case* 

1. Have an InfluxDB connection prepared with a kapacitor connection
1. Open Configuration page
1. Click on the kapacitor connection in the table and then the edit control (pencil icon).  The traditional Configure Kapacitor page loads.  There is an "Update" button, a "Reset" button, however there is NO "Cancel" button. 

*Expected Behavior*

Any transaction that can be initiated should also include the possibility to roll back to the previous state, preferably by retracing the steps that lead to the point from which the user wants to return.  

Not sure why this did not appear like an issue in previous releases, however the Wizard idiom, now used when creating Kapacitor connections, now makes this page seem like a different approach, with which the user may not/no longer be familiar.  So a familiar escape would be helpful. 

*Screenshots*
![editkapacitornocancel01](https://user-images.githubusercontent.com/25881301/45093018-6f089e00-b117-11e8-8b7c-1eaf48aa178f.png)
![editkapacitornocancel02](https://user-images.githubusercontent.com/25881301/45093019-6f089e00-b117-11e8-81e7-8f72e2d2d080.png)

**Comment by ebb-tide** [comment]
We've decided that we will not be making further changes to this page until a comprehensive redesign
