### ISSUE TITLE
Configure Kapacitor - after creating new kapacitor and closing wizard, InfluxDB connections are switched

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4356]
Build **Nightly Build**
Build Time **201809042321**
Browser **Chrome 68**
```
$ chronograf --version
2018/09/05 10:21:48 Chronograf 1.4.3.0~n201809042321 (git: 3f5850ddec306442efb363d8541a4e03f6b2bb2f)
```
*Use Case*
1. Have two Influx connections prepared, with 1 as default. 
1. With the influx connection that is currently NOT connected, initiate creating a new kapacitor connection with the kapacitor drop down
1. Provide a URL and Name and continue to the end of the wizard.
1. Click *View All Connections*.  The wizard closes. 

However, the connection that was originally connected is now marked as NOT connected, while the connection just edited IS NOW CONNECTED.  The user just wanted to add a Kapacitor Connection. 

*Expected Behavior*

That if a transaction is to lead to the creation of a new Kapacitor Connection, then it should not change the state of anything else.  It should not disconnect existing InfluxDB connections and connect new ones. 

*Screenshots*
![kapaconnectwizardchangedifluxdefault01](https://user-images.githubusercontent.com/25881301/45094179-d8d67700-b11a-11e8-9abf-848c41d51bf4.png)
![kapaconnectwizardchangedifluxdefault02](https://user-images.githubusercontent.com/25881301/45094180-d8d67700-b11a-11e8-8fd5-4d2aaf13a793.png)
![kapaconnectwizardchangedifluxdefault03](https://user-images.githubusercontent.com/25881301/45094182-d8d67700-b11a-11e8-83eb-7a82f75b1815.png)
![kapaconnectwizardchangedifluxdefault04](https://user-images.githubusercontent.com/25881301/45094183-d96f0d80-b11a-11e8-8d62-4d0ed7bec3e6.png)
![kapaconnectwizardchangedifluxdefault05](https://user-images.githubusercontent.com/25881301/45094185-d96f0d80-b11a-11e8-84d1-c0d4fe82f2af.png)

**Comment by ebb-tide** [comment]
check if we can detect if source has been edited by looking at props and navigate. accordingly. 
Change button copy to 'finish'. We should also check copy on rest of card.
