### ISSUE TITLE
Configure Kapacitor - no control to close the page and return directly to Connections view

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4357]
Build **Nightly Build**
Build time **201809042321**
Browser **Chrome 68**
```
$ chronograf --version
2018/09/05 10:21:48 Chronograf 1.4.3.0~n201809042321 (git: 3f5850ddec306442efb363d8541a4e03f6b2bb2f)
```
Related Issue #4355 

*Use Case*

1. Prepare an InfluxDB connection with associated Kapacitor Connection
1. Open the Configuration page
1. Click on the Kapacitor drop down for the InfluxDB connection 
1. Click the edit (pencil) icon.  The Configure Kapacitor Page loads. 
1. Make changes, e.g. change the name. 
1. Click "Update".  A notification appears that the connection has been updated.  O.K. However... 

Now that the user has finished editing, what is the most intuitive way to close this page and return to the Connections list? Yes, the connections tab can be clicked, but this does not feel like a final step in the updating kapacitor transaction. 

*Expected Behavior*

It would be nice to have a "Close" or "Update and Return" button, which would be more intuitive and obvious, than clicking once again on the tab in the left navigation bar.

**Comment by ebb-tide** [comment]
We've decided that we will not be making further changes to this page until a comprehensive redesign
