### ISSUE TITLE
A query in my dashboard is automatically transformed to a different query

### ISSUE THREAD

**Issue by fungiboletus** [influxdata/chronograf#4385]
Hei,

When I create a dashboard cell with the following request :
```
SELECT sum("abc") AS "sum" FROM "abc"."def"."ghi" WHERE time > :dashboardTime: AND "action"!='a' AND "action"!='b' AND "action"!='c' AND "action"!='d' AND "action"!='e' AND "action"!='f' AND "action"!='g' GROUP BY "action"
```

I can see correct results and I can save it and see the correct results in the dashboard.

However, everytime I reload the dashboard or edit the cell, I get this wrong request instead :
```
SELECT sum("abc") AS "sum" FROM "abc"."def"."ghi" WHERE time > :dashboardTime: AND ("action"!='a' OR "action"!='b' OR "action"!='c' OR "action"!='d' OR "action"!='e' OR "action"!=f' OR "g') GROUP BY "action"
```

I looked at the `POST` request when I save the cell, and it's the correct query that is posted.

Chronograf version : 1.6.1

**Comment by russorat** [comment]
@yellowiscool thanks for reporting. 

as a workaround, i believe you can rewrite the original query as: `SELECT sum("abc") AS "sum" FROM "abc"."def"."ghi" WHERE time > :dashboardTime: AND "action" !~ /^[abcdefg]$/ GROUP BY "action"`

**Comment by fungiboletus** [comment]
I guess the bug still exists.

**Comment by fungiboletus** [comment]
I guess the bug still exists.

**Comment by goller** [comment]
I'm following the bread-crumbs into the source:

https://github.com/influxdata/chronograf/blob/335248c0fde2b369fe86e65aaef6c6bc751ecb9a/influx/query.go#L255

**Comment by goller** [comment]
Ok, we found the bug... it's an ancient one!

The boolean logic was built in an era before we could express `!=`

PR incoming
