### ISSUE TITLE
Add overscan to progressive logs loading

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4394]
Talk to @bthesorceror for context.

**Comment by jaredscheib** [comment]
not able to replicate on my computer

**Comment by OfTheDelmer** [comment]
Looking into this I don't see much flickering when scrolling. We could add overscan of `100` but it's recommended to be as low as possible. Setting my monitor to 4k resolution I see issues when scrolling, but increasing overscan didn't help.

**Comment by jaredscheib** [comment]
@russorat could you verify that this is an issue? neither of us is seeing it anymore

**Comment by russorat** [comment]
this was suggested as a fix by @bthesorceror . if we don't see it, let's close.
