### ISSUE TITLE
Dashboard Annotations - Possible for Annotation Popup to conflict with Cell action dropdown

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4396]
Bulid **Nightly Build**
Build Time **n201809072259**
Browser **Chrome 68**
```
$ chronograf --version
2018/09/10 14:19:17 Chronograf 1.4.3.0~n201809072259 (git: 6e99afe5a4a5e7045ae63819c9e0c2a1dcf685f9)
```
*Use Case*
1. Create new dashboard and cell with data from telegraf.autogen > cpu > usage_idle
1. Create an annotation near the right edge of the cell. 
1. Close the annotation popup near the bulb of the annotation line by moving the pointer away from the cell.
1. Click on the pencil icon of the cell, but don't choose anything.  
1. Move the pointer off of the cell, so the actions menu disappears. 
1. Hover the pointer back over the cell.  The action menu dropdown reappears. 
1. Hover over the bulb of the annotation. 

The annotation popup appears and its controls in the layout conflict with controls in the action menu bar. 

See screenshot below. 

*Expected behavior*

That the popup just drawn should have z axis precedence over anything already shown or that perhaps only one action popup/menu/dropdown should be visible and active at a time. 

*Screenshots*

![annotatepopupanddbdropdown01](https://user-images.githubusercontent.com/25881301/45297356-63491d00-b505-11e8-830f-490058f996f2.png)

**Comment by karel-rehor** [comment]
I've added this as a blocker, because the Selenium tests run in a smaller view port and the graphs are narrower which means this conflict is difficult to avoid.  A work around is to specify the zIndex of the dash-graph-context elements and of the tooltip so that the tooltip comes out on top.  However this should be in the UI and not in the tests.

**Comment by AlirieGray** [comment]
Addressed the z-index in: https://github.com/influxdata/chronograf/pull/4503

Not sure if this is closed or not bc of the Selenium test issue?

**Comment by AlirieGray** [comment]
Closing this until otherwise notified
