### ISSUE TITLE
Alert rule get's created despite error message

### ISSUE THREAD

**Issue by stefanhorning** [influxdata/chronograf#4398]
With Chronograf 1.6.2 an alert rule get's created despite a error message due to syntax errors. Leading to two versions of the rule being saved (one before and one after the correction was made).

To reproduce:

1. Go to alert rule page and create hit 'Build Alert Rule'
2. Compile a query and handler config through the GUI.
3. In the message field write wrong statement inside `{{ }}`. For example put typo in `{{ intex .Tags "Foo"' }}`.
4. Hit save.
5. Error message appears, asking to fix that syntax error
6. Correct the typo and save again, now it works and leads you back to the list page
7. There you realize the first save already persisted the wrong rule and you have now two rules with the same name

**Comment by russorat** [comment]
thanks for reporting!

**Comment by ebb-tide** [comment]
This is a characteristic of kapacitor, where tasks/alert rules that have mal-formed messages can be saved as tasks, but will fail on execution. and can not be enabled. The solution we have come up with is the disable saving if messages have malformed Message Templates
