### ISSUE TITLE
Send to Dashboard from DE breaks if there are no dashboards

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#4443]

**Comment by russorat** [comment]
we should add an option to send to a new dashboard in the send to dashboard modal.

**Comment by ebb-tide** [comment]
- [ ] We should check for new dashboards every time send to dashboard is invoked. 
- [ ] There should be only one notification for all the dashboards cell is being sent to. and notification should include the names of the dashboards. 
- [ ] Possible extension to name the new dashboard you are creating on selection.
