### ISSUE TITLE
Custom links should be rendered irrespective of OAuth2 settings in Chronograf

### ISSUE THREAD

**Issue by Puneeth-n** [influxdata/chronograf#4473]
I think, the linked custom links in Chronograf should work irrespective of OAuth2 being enabled especially since Chronograf doesn't behave like a OAuth2 proxy.

Let me describe my use case. I have ELK, Jaeger-ui and Chronograf under different base paths. I would like to have all there services running under the same hostname but different paths.

`foo.bar.com/monitoring` => `chronograf`
`foo.bar.com/tracing` => `Jaeger`
`foo.bar.com/logging` => `elk`

Therefore, I have a central `oauth2 proxy` in my case https://github.com/bitly/oauth2_proxy that does authentication. Therefore, I don't necessarily need the OAuth2 authentication from `Chronograf`.

I would like to provide custom links in chronograf to kibana and jaeger. However, with the current implementation, it isn't possible.

I think, custom links should be modeled in similar lines to what `Jaeger` does. https://www.jaegertracing.io/docs/1.6/deployment/#ui-configuration

Ideally, It would be nice to have Chronograf as a central place for viewing metrics, traces and logs. However, There seems to be 
- No progress W.R.T integrating Jaeger with TICK stack https://github.com/influxdata/jaeger https://github.com/jaegertracing/jaeger/issues/272
- PR on pushing docker logs to TICK is pending merge https://github.com/influxdata/telegraf/pull/4360

Irrespective of when these above features are implemented, I strongly believe that custom links should not depend on whether OAuth2 in Chronograf is used or not because these custom links need to be secured, they will be secured.

**Comment by russorat** [comment]
@Puneeth-n thanks for reporting. this feature was specifically focused around our cloud offering which always has auth enabled. We will look to update where the links are stored in a future ui redesign. 

Another option that will be released in 1.7 chronograf will be a "Notes" cell type that allows markdown. You could possibly add a note cell to your dashboards with links to the other tools. It's not ideal, but might be better than nothing.

**Comment by Puneeth-n** [comment]
@russorat Thanks
