### ISSUE TITLE
Dashboard Annotations - Filter Tag value with wildcard 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4481]
Bulid **Nightly Build**
Build time **201809191749**
Browser **Chrome 69**
```
$ chronograf --version
2018/09/21 13:28:37 Chronograf 1.4.3.0~n201809191749 (git: 6fce4418a3a5acef9a683b1e01910a83ca21a970)
```

*Use Case*
1. Create two or more annotations. 
1. To one annotation add the tag "Fruit" -> "Kiwi" 
1. To the second annotation add the tag "Fruit" -> "Banana" 
1. Select Filter Annotations By Tags 
1. Select the key "Fruit" 

*Question*

Is it possible to use a wildcard in the text box _Value_ so that all annotations using the Key "Fruit" will be shown and so that other annotations with other keys (e.g. "Veggie") will be filtered out?

*Screenshot*
![filtertagwildcards01](https://user-images.githubusercontent.com/25881301/45881085-69af8280-bdaa-11e8-88a0-a089aab0a467.png)

**Comment by russorat** [comment]
@karel-rehor it's not very clear, but clicking on the `==` allows you to change it to `=~`, which allows you to use regular expressions in that list. so `.*` would work.
