### ISSUE TITLE
Dashboard Zoom - zooming is no longer synchronized between cells 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4492]
Bulid **Nightly Build**
Bulid time **201809220049**
Browser **Chrome 69**
```
$ chronograf --version
2018/09/24 10:22:43 Chronograf 1.4.3.0~n201809220049 (git: ee10dc61753bbe4976a29e205882823923576933)

```

*Use Case*
1. Create a graph with two cells 
   * telegraf.autogen > cpu > usage_idle 
   * telegraf.autogen > mem > used
1. Add an annotation, which will appear in both graphs. 
1. Zoom in on a smaller window of time around the annotation. 

The zoom works in the active cell, but is not synchronized with the second cell. 

Previously zoom in one cell was synchronized with other cells as applied from the URL:

e.g.
```
http://localhost:8888/sources/1/dashboards/9?lower=now%28%29%20-%2015m&zoomedLower=2018-09-24T08%3A18%3A18.656Z&zoomedUpper=2018-09-24T08%3A22%3A08.418Z
```

*Expected Behavior* 

That when one cell is zoomed, then all related cells in the Dashboard will also be zoomed. 

*Screenshots*
![zoom2cellsnosync01](https://user-images.githubusercontent.com/25881301/45942966-cdbd8b00-bfe4-11e8-89f3-47b297e72437.png)
![zoom2cellsnosync02](https://user-images.githubusercontent.com/25881301/45942967-cdbd8b00-bfe4-11e8-9403-ede679491c04.png)

**Comment by ebb-tide** [comment]
I can not reliably reproduce this. I have seen it when cells are not using dashboardtime in the queries such as when they use `WHERE time > now() - 1h` instead of `WHERE time > :dashboardTime:` . But I would argue that if a cell is not using dashboard time it should not be synced with other cells that are?

**Comment by karel-rehor** [comment]
I was not seeing this in nightly tests last week, and this morning (`build 201809282226 (git: 2b85390aa37c879651231635879ce6ebcc904dd9)`) it seems to be working manually as expected.  (unable to verify tests because renaming of graphs is currently not working). 

The test for this is based on `:dashboardTime:`, perhaps a use case should be added for explicit expressions such as `now() - 1h`.
