### ISSUE TITLE
Dashboard - removed field continues to appear in cell graph

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4495]
Build **Nightly Build**
Bulid Time **201809220049**
Browser **Chrome 69**
```
$ chronograf --version
2018/09/24 13:35:10 Chronograf 1.4.3.0~n201809220049 (git: ee10dc61753bbe4976a29e205882823923576933)
```
Note this is running against a dockerized cluster for influxdb-enterprise. 

*Use Case*
1. Create a dashboard cell graph with two measurements
   * telegraf.autogen -> cpu -> usage_idle
   * telegraf.autogen -> cpu -> usage_user 
1. Click on the context menu item edit -> configure
1. Toggle off the field *usage_idle* (preview graph fails to update - see issue #4494)
1. Click Save anyway 

When the dashboard reloads, both curves for both fields continue to be displayed. 

*Expected behavior*

That when a field is removed from a graph, then when the graph is redrawn then the curve for that field should be removed. 

*Screenshots*
![dashboardbuliderremovecurve01](https://user-images.githubusercontent.com/25881301/45950940-f2742b80-c001-11e8-8e9d-fb3f73707225.png)
![dashboardbuliderremovecurve02](https://user-images.githubusercontent.com/25881301/45950941-f2742b80-c001-11e8-8905-b6e1637b5f60.png)
![dashboardbuliderremovecurve03](https://user-images.githubusercontent.com/25881301/45950942-f2742b80-c001-11e8-8b33-96a2fc59d759.png)
![dashboardbuliderremovecurve04](https://user-images.githubusercontent.com/25881301/45950943-f30cc200-c001-11e8-86dc-f27b0befd18a.png)

**Comment by chnn** [comment]
Appears to be fixed on current master.
