### ISSUE TITLE
Many same alerts from Chronograf to one email

### ISSUE THREAD

**Issue by ondrejFuchs** [influxdata/chronograf#4506]
Chronograf 1.4.3
Kapacitor 1.4.1
+ Influxdb, grafana

Twenty devices sendind data about disk usage to influx. If I made alerts (threshold) greather then 85 and sending email. One device from twenty was upper then threshold and I receive about 60 mails since 3 second (I had to stop alerting).
Any idea about it?
Thanks for any response.

**Comment by russorat** [comment]
@ondrejFuchs could you provide the TICK script that is sending the alerts and describe the steps you took to create it? was it manual or did you use the alert rule builder?

**Comment by ondrejFuchs** [comment]
Thanks for response. I run kapacitor in docker with chronograf and i setup alerts from web GUI of chronograf. I cant find any *.tisk files in docker container. Where are save *.tick files? I cant find info about it.
