### ISSUE TITLE
 Chronograf (1.7.0) Cannot read property 'chunkSize' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4510]
try setting `foo = -1`

```TypeError: Cannot read property 'chunkSize' of undefined    at ae (http://localhost:8888/russ/src.7b465d21.js:3153:8305)    at go (http://localhost:8888/russ/src.7b465d21.js:3153:88915)    at Mo.<anonymous> (http://localhost:8888/russ/src.7b465d21.js:3153:101562)    at Mo.setGutterMarker (http://localhost:8888/russ/src.7b465d21.js:3153:65402)    at Ll.setGutterMarker (http://localhost:8888/russ/src.7b465d21.js:3153:165309)    at http://localhost:8888/russ/src.7b465d21.js:3574:3640    at Array.forEach (<anonymous>)    at i.value (http://localhost:8888/russ/src.7b465d21.js:3574:3583)    at i.value (http://localhost:8888/russ/src.7b465d21.js:3574:2792)    at xi (http://localhost:8888/russ/src.7b465d21.js:634:84238)```

![image](https://user-images.githubusercontent.com/4805997/46167704-65241780-c24b-11e8-9922-406ba02bb3fe.png)

**Comment by chnn** [comment]
Closed by #4524
