### ISSUE TITLE
Gitlab/Chronograf Authentication non-functional

### ISSUE THREAD

**Issue by exabrial** [influxdata/chronograf#4521]
When Chronograf calls back to GitLab, it receives the following response: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

I did a tcpdump and it appears Chronograf is submitting a `code` from a pervious request as a POST body to get said response. Everything else looks correct, so I'm unsure why this is happening. I'm happy to privately share tcpdumps of traffic with anyone willing to take a look at this issue. Thanks!

https://community.influxdata.com/t/chronograf-gitlab-impossible-to-get-authentication-working/6787

**Comment by russorat** [comment]
@exabrial i replied to the community post. let me know if that works for you.

**Comment by exabrial** [comment]
Thanks! It did. Looks like a doc or two needs updated.

**Comment by baskinsy** [comment]
Thanks I had the same issue, seems the docs need to be updated.
