### ISSUE TITLE
Template variable / query parsing issue

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4528]
Chronograf version: 8b0ae52e0652e34ae871119199e4c33617c351c6
InfluxDB version: 1.6.3

![screenshot 2018-10-02 15 50 07](https://user-images.githubusercontent.com/501993/46356552-e10ecd00-c65a-11e8-9031-1ae258b62a8a.png)

If I go to data explorer, select my db/rp and field I get the following query created:

```
SELECT mean("temperature") AS "mean_temperature" FROM "airvisual"."autogen"."reading" WHERE time > now() - 1h GROUP BY :interval: FILL(null)
```

With the following error message:

```
received status code 400 from server: err: error parsing query: found :, expected identifier, string, number, bool at line 1, char 120
```

If I change the `:interval:` template variable to `time(:interval:)` I get the same problem. If I change the `:interval:` to the following everything is fine:

```
SELECT mean("temperature") AS "mean_temperature" FROM "airvisual"."autogen"."reading" WHERE time > now() - 1h GROUP BY time(5m) FILL(null)
```

**Comment by russorat** [comment]
fixed in 1.7 release
