### ISSUE TITLE
Chronograf dashboard chart doesn't honour alias field when query doesn't have a "group by" clause

### ISSUE THREAD

**Issue by Injenia** [influxdata/chronograf#4535]
In Chronograf, I create a new cell in a dashboard.
I edit the cell and I write the following query as source
`SELECT "VALORE" as "MYALIAS" FROM "eventi_sensori"."autogen"."eventi_sensori" WHERE time > :dashboardTime: AND "TAG"='DPDCOD1APDK8_1_K_LIV_VASC001_MFCLR01'`
VALORE is my field name, but I'd like to show it with a different name, so I'm trying to use alias in order to accomplish my goal.
when I save my changes, in  chart's legend I actually view "MYALIAS" , but if I refresh page or I clone the cell, chart doesn't show anymore my field alias. If I open cell editor, I don't see my alias, but if I export the dashbaord, I can see it. 

If I add a "group by" clause to my query and I use alias only on aggregated field, it works correctly.

I need to show my alias also for not aggregated field or for query without "group by " clause.

**Comment by russorat** [comment]
@Injenia thanks for reporting! We will investigate.

**Comment by julienbrunet** [comment]
I confirm this bug in my Chronograf Version: 1.6.2

**Comment by chnn** [comment]
Hi @Injenia and @julienbrunet, I have just pushed a fix for this issue. It will be released in Chronograf 1.7, which is due out some time in the next month.

Thanks for reporting!
