### ISSUE TITLE
Ability to authenticate against internal GitHub instance

### ISSUE THREAD

**Issue by te4336** [influxdata/chronograf#4539]
We currently use Github Enterprise which is hosted On-Premise and not in the cloud. I have correctly configured Chronograf to connect and I get the login button but when I click on it I am redirected to the public version of Github instead of our internal corporate instance. Is there a command line flag that I can use to specify the instance of GitHub that it needs to authenticate against?

**Comment by russorat** [comment]
@te4336 we don't support that today. You might be able to configure generic oauth to do it. Have you tried that?
