### ISSUE TITLE
Dashboard - add second cell with first undefined throws TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4543]
Build **Nightly Build**
Bulid Time **n201810032156**
Browser **Chrome 64**

```
$ chronograf --version
2018/10/04 11:04:19 Chronograf Nightly~n201810032156 (git: 61ab25b2c0e8dd03966916ef15afdd13998dc166)
```

*Use Case*

User estimates that the new dashboard will require two or more cells and attempts to prepare the cells before defining their graph data.

1. Create a new dashboard 
1. Before clicking on _Add Data_ click on _Add a new cell to the dashboard_ 

The page is replaced with the error message "A Chronograf error has occurred. Please report the issue here."

The console log shows the following error. 

```
TypeError: Cannot read property 'constructor' of undefined
    at src.2838d359.js:3107
    at Array.forEach (<anonymous>)
    at src.2838d359.js:3107
    at n.render (src.2838d359.js:3105)
    at ia (src.2838d359.js:634)
    at aa (src.2838d359.js:634)
    at fa (src.2838d359.js:634)
    at Wa (src.2838d359.js:634)
    at Va (src.2838d359.js:634)
    at wi (src.2838d359.js:634)
```

*Expected Behavior*

That a second empty cell, with a button _Add Data_ will be created. 

*Screenshots*
![newcellfails01](https://user-images.githubusercontent.com/25881301/46464707-4c75ad80-c7c7-11e8-9620-8ebd0cc78319.png)
![newcellfails02](https://user-images.githubusercontent.com/25881301/46464708-4c75ad80-c7c7-11e8-8b51-43f26aaebeac.png)
![newcellfails03](https://user-images.githubusercontent.com/25881301/46464710-4d0e4400-c7c7-11e8-96b5-a2522505b532.png)

*Regression Note*

This was uncovered through Selenium tests, however the case is slightly different.  The Selenium case involves generating a dashboard without any cells over the API and then adding the first cell with the _Add Cell_ control.  The case defined above was used as a short cut to verify current behavior of _Add Cell_ control, when it was noted the Add Cell test is failing.

**Comment by AlirieGray** [comment]
I followed the steps above and was not able to reproduce this on master. Is this still an issue currently?

**Comment by karel-rehor** [comment]
Nightly Build **201810160023~nightly (git: a32e8f062a0ffd301789982c76fe52c324cfd96b)**

The current behavior is that when clicking on a new cell before defining data for the first cell, the graph builder loads for  the new cell.  This is sensible. 

Closing this defect.
