### ISSUE TITLE
Status Page - Cross-Origin Read Blocking preventing News Feed from loading 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4566]
Build **Nightly Buid**
Build Time **201810092353**
Browsers **Chrome 69**, **Firefox 62**

```
$ chronograf --version
2018/10/10 10:13:37 Chronograf 201810092353~nightly (git: 0a98597aa8936d59237313e3c252c3eadb68ef8c)
```

*Use Case*

1. Open status page

A notification message appears: _Failed to fetch JSON feed for News Feed from https://www.influxdata.com/feed/json_

And the News Feed fails to load. 

*Expected Behavior*

That the news feed should load.  And, that users should not need to reconfigure their browsers by switching off security features to get it to work. 

*Screenshots*
![nonewsfeed01](https://user-images.githubusercontent.com/25881301/46722501-e8932f00-cc75-11e8-80dd-736af351c640.png)
![nonewsfeed02](https://user-images.githubusercontent.com/25881301/46722503-e8932f00-cc75-11e8-81d2-d9854e6d6b25.png)

*Selenium test note*

This notification is interfering with automated tests, whenever they return to or otherwise access the status page.  The notification persists to other pages and prevents clicking on controls in that area of the new page.

**Comment by nhaugo** [comment]
Fixed the issue, I think we should not pop up an error message if this happens.

**Comment by russorat** [comment]
@nhaugo follow your request in #4579
