### ISSUE TITLE
Normalization problem

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#4576]
I create dashboard and receive metrics from telegraph on two nodes system.
First node is overload (i.e. 100% CPU usage) and second node always in idle (i.e. no CPU utilization).
Each chart set min = 0 and max = 100 value. As you can see on screen shot chronograf normalize second chart and it look like second node use around 50% CPU but actualt it around 4%. Could you explain this behavior.

![default](https://user-images.githubusercontent.com/110534/46886856-b693ef80-ce64-11e8-866d-b4e1c4c4882f.png)

**Comment by russorat** [comment]
@vit1251 we will investigate. Thanks!

**Comment by 121watts** [comment]
@vit1251 thanks for writing in!  It appears that the scale you're mentioning for node 2 being ~4% is on the `y2` axis.  This entirely our fault.  Chronograf automatically puts any query not in the first tab on the `y2` axis scale.  This has caused much confusion.  I have removed that unintuitive behavior [here](https://github.com/influxdata/chronograf/pull/4680) and that will be available in the nightly build and 1.7.

In the mean time, if you move any query in another tab to the first query tab and delimit them with a `;` i.e. `SELECT foo ...;SELECT baz ...` you should see all of the data in the scale that you are expecting.
