### ISSUE TITLE
Log Viewer - In smaller screen resolution not all columns are visible or accessible

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4578]
Build **Nightly Build**
Build Time **201810112144**
Browser **Chrome 69**

```
$ chronograf --version
2018/10/15 16:45:08 Chronograf 201810112144~nightly (git: 093a5af0339de24790c3c0704217c269b6355b97)
```

*Use Case*

User is opening Chronograf on a device with a smaller screen resolution e.g. 1044 x 768

1. Open Logs 
1. Click on the configuration cog wheel.  The dialog loads.  Verify that all 7 columns are visible. 
1. Cancel the configuration dialog. 

The logs main page loads with the table of log entries, however only 3 of the 7 columns are visible.  Furthermore, there is no horizontal scrolling mechanism, with which the columns might be brought into view. 

A smaller resolution can be emulated in an image editing application by creating a new image file with the desired dimensions (e.g. 1044 x 768) and then resizing the browser to match the image dimensions. 

*Expected Behavior*

That the columns should be somehow accessible. 

*Screenshots*
![narrowscreencolumnsnotseen01](https://user-images.githubusercontent.com/25881301/46958673-acf3cd00-d09a-11e8-94b6-e49353503897.png)
![narrowscreencolumnsnotseen02](https://user-images.githubusercontent.com/25881301/46958674-acf3cd00-d09a-11e8-8dec-46889bc3880b.png)

*Note on Selenium Testing*

Currently the default dimensions for AWS Windows nodes used in testing is 1044 x 768.  Furthermore, it will be helpful to have access to the Application column to filter out noise from the Chronograf application itself, which seems to be writing several messages to syslog a second.

**Comment by OfTheDelmer** [comment]
Scrolling horizontally with the track pad will show the other columns.
