### ISSUE TITLE
y2 axis must appear when a second query is present in dashboard cell

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4584]
connect #4583

as a query builder
with editor permissions or higher
when i have multiple influxql queries entered into a dashboard cell
then i would like to option to graph the second query to a second y axis

**Comment by timhallinflux** [comment]
y2 seems to have disappeared as part of 1.7.11
Example: 1.6.2
![Screen Shot 2019-05-10 at 4 31 57 PM](https://user-images.githubusercontent.com/23535264/57561570-3f163800-7341-11e9-9900-2b4c86170241.png)

Example:1.7.11
![Screen Shot 2019-05-10 at 4 31 31 PM](https://user-images.githubusercontent.com/23535264/57561577-463d4600-7341-11e9-93c5-9eb498073d4f.png)

**Comment by russorat** [comment]
I'd like to see the previous behavior restored in 1.7.12 and potentially config options for 1.8

**Comment by timhallinflux** [comment]
This was intentionally removed in the 1.7 edition.  We will revisit this as part of the InfluxDB 2.0 UI via the Giraffe library.   https://github.com/influxdata/giraffe

**Comment by 121watts** [comment]
We removed `y2` here: https://github.com/influxdata/chronograf/pull/4680
