### ISSUE TITLE
chronograf 1.6.2 fails to build

### ISSUE THREAD

**Issue by williamh** [influxdata/chronograf#4595]
On Linux/amd64, I get the following when I try to build chronograf:

william@linux1 chronograf $ go version
go version go1.11 linux/amd64
william@linux1 chronograf $ yarn --version
1.10.1
william@linux1 chronograf $ make
go generate -x ./server
go-bindata -o swagger_gen.go -ignore go -nocompress -pkg server .
server/swagger.go:3: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
make: *** [Makefile:60: server/swagger_gen.go] Error 1
william@linux1 chronograf $

**Comment by russorat** [comment]
is this the same issue as #4544 ?

**Comment by chnn** [comment]
@russorat Yep.

@williamh We rely on [go-bindata](https://github.com/jteeuwen/go-bindata) to build Chronograf, but currently don't install it automatically if it doesn't exist. For now, you can work around this by installing go-bindata
```
go get -u github.com/jteeuwen/go-bindata/...
```
and then running `make` again.

Closing in favor of #4544
