### ISSUE TITLE
Admin not visible. No chance to create users

### ISSUE THREAD

**Issue by andyhuber** [influxdata/chronograf#4617]
Hi guys.

I'm pretty new to the whole Tick stack. but so far its amazing. One thing though. I can't really see a "Chronograf admin" page when clicking the crown. The only thing I have there is. "InfluxDB admin". Is that a bug or am I doing something wrong? I wanna enable oAuth, but without being able to add users is that a bit hard. 
Can someone verify if thats a bug or am I doing something wrong?

**Comment by russorat** [comment]
@andyhuber thanks! Could you explain a little more about what you are trying to accomplish with a "chronograf admin" page?

**Comment by andyhuber** [comment]
@russorat Want I want is actually to enable oAuth for Chronograf. and according to the documentation I need to first setup all the tokens and keys (which works) but I have no chance to add a oAuth user anywhere. in the documentation it says I can press "the crown" and then chronograf admin. but that doesn't exist. Any idea why?

**Comment by russorat** [comment]
You should be looking for this page: 
![image](https://user-images.githubusercontent.com/4805997/47397868-2bc5b700-d6e6-11e8-8b75-d40ffe30d3c8.png)

if you aren't seeing that, you must be missing some configuration option for setting up OAuth. Try to double check the values you are setting with the docs and see if there is something you're missing: https://docs.influxdata.com/chronograf/v1.6/administration/managing-security#oauth-2-0-providers

**Comment by andyhuber** [comment]
@russorat thats exactly what I'm not seeing. I attached a screenshot of my configuration.
and how do I add the first user? as soon as I restart with this configuration I need to login. but how do I login if I can set a user first?
<img width="465" alt="screenshot 2018-10-24 at 07 00 54" src="https://user-images.githubusercontent.com/42995387/47407310-c19b2980-d75a-11e8-8ca6-36546f44de9b.png">

**Comment by andyhuber** [comment]
@russorat just as an additional information I tried to setup the whole TICK stack on 3 different machines following the guide and all 3 end up with the same issue that the Chronograf admin page is not visible in the menu. I also browsed through the bolt database and users are empty. Can that be an issue that there is by default no user set? Or maybe I just do the setup wrong? 🤷🏼‍♂️ The GitHub integration itself works in the log I can see that the user is authorized bit GitHub but doesn't exist in the local database.

**Comment by russorat** [comment]
@andyhuber thanks for the additional information. There is a bootstrap process that allows the first user to log in after OAuth has been enabled to become a superadmin (https://github.com/influxdata/chronograf/pull/2442 this also removed that command line option) . We will add that note to the docs (https://github.com/influxdata/docs.influxdata.com/issues/1914) .

So just to confirm, you see the login screen that says "Login with Github", you log in with your github credentials successfully, and you land on the status page, and the menu on the right side doesn't have the crown or the user icon at the end?

What version of Chronograf are you using? I'm not able to reproduce on my side with master so it's tough to troubleshoot.

**Comment by andyhuber** [comment]
@russorat no actually I'm not able to login. I end up again on the login page after successful login through GitHub but I can see in the logs that it says the user is authorized but missing in the local chronograf database. I'm running the latest version 1.6.2

Oct 24 17:04:41 instance-1 chronograf[12129]: time="2018-10-24T17:04:41Z" level=info msg="found an extra id_token, but option --useidtoken is not set" component=auth method=GET remote_addr="83.252.60.111:55050" url=/oauth/github/callback?code=<CODE REMOVED>&state=<STATE REMOVED>
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="User andy.huber@XXXXX is authenticated" component=auth method=GET remote_addr="83.252.60.111:55050" url=/oauth/github/callback?
code=<CODE REMOVE>&state=<STATE REMOVED>`
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="Response: Temporary Redirect" component=server method=GET remote_addr="83.252.60.111:55050" response_time=1.421953879s status=307
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="Serving assets" component=server method=GET remote_addr="83.252.60.111:55050" url=/
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="Response: OK" component=server method=GET remote_addr="83.252.60.111:55050" response_time=7.345627ms status=200
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="Response: OK" component=server method=GET remote_addr="83.252.60.111:55050" response_time="182.084µs" status=200
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=error msg="Error message This Chronograf is private. To gain access, you must be explicitly added by an administrator." component=server http_status =40
3
Oct 24 17:04:43 instance-1 chronograf[12129]: time="2018-10-24T17:04:43Z" level=info msg="Response: Forbidden" component=server method=GET remote_addr="83.252.60.111:55050" response_time="209.678µs" status=403`

**Comment by andyhuber** [comment]
@russorat Good news. I fixed it. it seems like the database was corrupted. What I did was remove the boltdb. installed the nightly build. started the service again. and the first user was created in the database. Maybe that should be mentioned in the documentation. Because I had everything running and then enabled oauth and that seems not to work. at least not how I did it.

**Comment by russorat** [comment]
@andyhuber great to hear! i will chat with the docs team to figure out the best way to doc this. can you think of anything you did that may have led to a corruption? You mentioned you installed a fresh chronograf on 3 machines. Do you think the boltdb was corrupted on all of them? or were you copying the boltdb to each new machine?

**Comment by andyhuber** [comment]
@russorat I think the main issue was (in retrospect) that you guys require some very high port (I don't remember > 50000 ) the exact one to be open for the oauth process. To reach some path "chronograf/v1/me" and that was not open for me in the first place and after that I guess it tried to add the user and it didn't work and from then on chronograf thought I already created an ouath user. But that's just speculation from my side. Because it was a fresh install on all 3 machines. I didn't copy the database. But thanks a lot for trying to solve it. You guys do an amazing job

**Comment by petetnt** [comment]
I upgraded from 1.4.0 to 1.7.3. and lost access to the Chronograf even though I was a super admin on the said older Chronograf instance. Same message pops up in the logs (`This Chronograf is private. To gain access, you must be explicitly added by an administrator`). We only had GitHub auth enabled on the instance.

**Comment by russorat** [comment]
@andyhuber thanks! please report any other issues you encounter so we can take a look!
