### ISSUE TITLE
custom charts

### ISSUE THREAD

**Issue by berlinguyinca** [influxdata/chronograf#4631]
Dear all,

I'm wondering if it is possible to extend the current charts/visualizations with custom ones? For example, I would love to plot OHLCV charts, etc coming from influxdb and don't seem to be able to find documentation regarding adding custom chart types.

thank you!

**Comment by 121watts** [comment]
Hey there @berlinguyinca!  Thanks for writing in.  

Adding custom data visualization types is on the roadmap.  Don't know when, but it's coming!

**Comment by John0x** [comment]
@121watts is there any news about this?
Being able to add custom charts would make us easily decide for influxdata.

**Comment by 121watts** [comment]
@John0x it's definitely still in the roadmap!  Can't give a definite date yet though.

**Comment by SorryGames** [comment]
> @John0x it's definitely still in the roadmap! Can't give a definite date yet though.

still in the roadmap? :smile:
