### ISSUE TITLE
Fix Flux feature detection

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#4637]
Currently, we enable Flux-related pieces of the UI in Chronograf if a user is using InfluxDB 1.7.

However, the latest InfluxDB also requires that a user has
```
[http]
flux-enabled = true
```
in their config for the Flux query endpoint to work. By default, this option is disabled.

We need to update our feature detection for Flux to check that a user has InfluxDB _and_ they have `flux-enabled = true`.

One way to do this would be to send a reconnaissance query when Chronograf boots up to the `/api/v2/query` endpoint. It will respond with a helpful error if a user does not have `flux-enabled = true`.

**Comment by ischolten** [comment]
Also allow flux for enterprise

**Comment by ischolten** [comment]
InfluxDB is changing the response status for when flux is not enabled. Will update the logic to use that instead of string matching once its ready

**Comment by trivita** [comment]
it looks like in 1.8.3 windows version 
this flag doesnt work at all, and btw if i set flux-enabled=true, the influxdb will hang for a while right after start
