### ISSUE TITLE
Add ability to send alert rule to multiple connected Kapacitors

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4638]
as a alert rule builder
with editor permissions or higher
when i build a new alert rule using the alert rule builder
then i would like the ability to send the alert rule to one or more kapacitor instances attached to my source.

if there is only one kapacitor instance, then automatically send it there.

**Comment by alexpaxton** [comment]
![image](https://user-images.githubusercontent.com/2433762/47464312-a8679c80-d79d-11e8-99ac-d8dab3d98153.png)

![image](https://user-images.githubusercontent.com/2433762/47464317-ae5d7d80-d79d-11e8-87de-5f0cfa87b982.png)
