### ISSUE TITLE
Add ability to send tick script to multiple connected kapacitors

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4639]
as a tick script builder
with editor permissions or higher
when i build a new tick script using the tick script builder
then i would like the ability to send the tick script to one or more kapacitor instances attached to my source.

if there is only one kapacitor instance, then automatically send it there.

**Comment by alexpaxton** [comment]
![image](https://user-images.githubusercontent.com/2433762/47464344-be755d00-d79d-11e8-8613-727527b6738f.png)

![image](https://user-images.githubusercontent.com/2433762/47464353-c3d2a780-d79d-11e8-9d38-63968ebe3941.png)

![image](https://user-images.githubusercontent.com/2433762/47464356-c6350180-d79d-11e8-8626-6bbeef5cf516.png)
