### ISSUE TITLE
Working with logging

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#4686]
Start experimenting with Syslog 1 message:

![default](https://user-images.githubusercontent.com/110534/47809620-6072e780-dd52-11e8-9a4d-28fd11f55e93.png)

How I can receive that message?

**Comment by vit1251** [comment]
@OfTheDelmer sorry, I can not answer bcz on moring I update on 1.7.3

**Comment by russorat** [comment]
please reopen if you see this on the latest chronograf.
