### ISSUE TITLE
TypeError: Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by schnoberts1** [influxdata/chronograf#4695]
Hi, 

[EDIT: I have a working system now, but I hope the illustration of the poor error handling will be construed as the defect I think it is]

I have a logstash deployment that consumes syslog and generates measurements into influx. This all works great. However, I also want to feed the syslog into influx for viewing in the log viewer in Chronograf. The problem I find is that I'm not entirely sure what Chronograf is expecting schema wise. I've looked at the Telegraf syslog module to work this out, but am failing as my syslog measurement results in the following JavaScript console log:

```
app.c626c8d812abadc2448d.js:210 TypeError: Cannot read property 'color' of undefined
    at n.cellRenderer (app.c626c8d812abadc2448d.js:239)
    at S (app.c626c8d812abadc2448d.js:32)
    at t.value (app.c626c8d812abadc2448d.js:32)
    at t.value (app.c626c8d812abadc2448d.js:32)
    at updateClassInstance (app.c626c8d812abadc2448d.js:210)
    at beginWork (app.c626c8d812abadc2448d.js:210)
    at a (app.c626c8d812abadc2448d.js:210)
    at o (app.c626c8d812abadc2448d.js:210)
    at E (app.c626c8d812abadc2448d.js:210)
    at b (app.c626c8d812abadc2448d.js:210)
br @ app.c626c8d812abadc2448d.js:210
app.c626c8d812abadc2448d.js:1 TypeError: Cannot read property 'color' of undefined
    at n.cellRenderer (app.c626c8d812abadc2448d.js:239)
    at S (app.c626c8d812abadc2448d.js:32)
    at t.value (app.c626c8d812abadc2448d.js:32)
    at t.value (app.c626c8d812abadc2448d.js:32)
    at updateClassInstance (app.c626c8d812abadc2448d.js:210)
    at beginWork (app.c626c8d812abadc2448d.js:210)
    at a (app.c626c8d812abadc2448d.js:210)
    at o (app.c626c8d812abadc2448d.js:210)
    at E (app.c626c8d812abadc2448d.js:210)
    at b (app.c626c8d812abadc2448d.js:210)
```
I am guessing this is a mismatch between the hardcoded expectations Chronograf has of the syslog measurement schema and what I'm generating but it's hard to tell as the error message and log are very hard to interpret. Here's my schema: 

```
name: syslog
------------
fieldKey	fieldType
facility_code	string
message		string
msgid		string
procid		string
severity_code	string
version		string

name: syslog
------------
fieldKey	fieldType
facility_code	string
message		string
msgid		string
procid		string
severity_code	string
version		string

```

So bug: Chronograf should present a correctly formatted message explaining the actual underlying root cause. 
Question: What schema is Chronograf hardcoded to assume? 

Thanks for you help, 

Andy

**Comment by schnoberts1** [comment]
BTW: Version: Chronograf: 1.6.1

**Comment by schnoberts1** [comment]
I am getting close with 
```
name: syslog
------------
fieldKey	fieldType
facility_code	integer
message		string
procid		string
severity_code	integer
version		integer
```

**Comment by schnoberts1** [comment]
... I realise that the logstash syslog_pri mappings don't match the versions in https://github.com/influxdata/go-syslog/blob/develop/rfc5424/syslog_message.go so I've fixed that and now I'm further. I note that hitting refresh repeatedly still causes errors, but there different so I'll put them under a different issue. Chronograf does seem pretty unstable. 

The only issue I have now is inferring the format of the Timestamp field from the code.

**Comment by schnoberts1** [comment]
...Timestamp needs to be epoch nanos, and now it's working and stableish. 
Even though it's working, the error handling really needs sorting out.

**Comment by russorat** [comment]
@schnoberts1 thanks! the initial version of our logviewer was designed to work with the Telegraf syslog input (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog). You can see an example of the schema it produces in the README file. 

I agree, the error handling needs to be better and we shouldn't assume a schema. We will be introducing this in future versions via https://github.com/influxdata/chronograf/issues/4278 https://github.com/influxdata/chronograf/issues/4573 and https://github.com/influxdata/chronograf/issues/4546

**Comment by schnoberts1** [comment]
Thanks.
