### ISSUE TITLE
Chronograf rules are getting deleted automatically within 2-3 days of running successfully.

### ISSUE THREAD

**Issue by satishverma17** [influxdata/chronograf#4711]
Chronograf rules are getting deleted automatically within 2-3 days of running successfully. None of the alert rule exists after this.

**Comment by nhaugo** [comment]
Alert rules are saved in kapacitor. Do they still exist on your kapacitor server?

**Comment by russorat** [comment]
@satishverma17 any update here?

**Comment by satishverma17** [comment]
It is removed from Kapacitor server as well. My next query is what makes it disappear from the server and list.

**Comment by russorat** [comment]
@satishverma17 are you running your kapacitor in a container or with an ephemeral data store? There's nothing in Chronograf to automatically delete kapacitor tasks.
