### ISSUE TITLE
Render chart in PNG image

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#4712]
Hello, Could you please provde direct link to render image to embede in Confluence or suggest Plugin for Confluence to provide report in Wiki page.

**Comment by russorat** [comment]
@vit1251 we don't currently have that capability and i'm not aware of any Confluence plugins for handling that. We will look into the feasibility of doing something like this in a future release.

**Comment by vit1251** [comment]
@russorat any updates? How about implement in chronograph API provide rendered PNG image with custom InfluxDB query?

**Comment by dpwiz** [comment]
An image export would be quite handy, regardless of Confluence.

**Comment by russorat** [comment]
@dpwiz thanks! we have no plans to support this in chronograf, but i have opened https://github.com/influxdata/influxdb/issues/15850 to continue the discussion for influxdb 2.0.
