### ISSUE TITLE
Difficult to differentiate Disabled toggle from Off toggle

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#4730]
The green SuperAdmin toggle does not appear to me like something I think is clickable in juxtaposition with the disabled toggle below it.

<img width="95" alt="screen shot 2018-10-29 at 12 26 39 pm" src="https://user-images.githubusercontent.com/6403018/48026562-39723800-e0fb-11e8-9232-2a7aedd0079d.png">

**Comment by russorat** [comment]
addressed in the platform designs
