### ISSUE TITLE
Protoboards don't load in 1.7.0

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#4760]

**Comment by heydonovan** [comment]
Would this be the same as the pre-canned dashboards recently released?

![dashboard](https://docs.influxdata.com/img/chronograf/v1.7/protoboard-select.png)

Cause if so, it's not working for me either (just upgraded). Here is the error:

<img width="1280" alt="screen shot 2018-11-07 at 2 31 11 pm" src="https://user-images.githubusercontent.com/918946/48159024-cce16f80-e299-11e8-8378-35a7ae705df4.png">
