### ISSUE TITLE
Connect to InfluxDB via a Unix Domain Socket

### ISSUE THREAD

**Issue by peterdey** [influxdata/chronograf#4773]
### Proposal:
Add support for connecting to InfluxDB over a Unix domain socket

### Current behavior:
InfluxDB supports a number of connection methods, including HTTP(S), UDP and Unix domain sockets.  Chronograf however can only connect via HTTP(S).

This is a similar feature request to:
- influxdata/telegraf#3366
- influxdata/kapacitor#1628

### Desired behavior:
Be able to connect to InfluxDB on the same host via a Unix domain socket, e.g.: ```unix:///var/run/influxdb.sock```

### Use case/Benefits:
- Improved security
- Reduce TCP overhead for hosts running the TICK stack on the same box and have limited resources

**Comment by peterdey** [comment]
Still a desired feature!  Would be great to be able to close off this port.

**Comment by hchokshi** [comment]
Can this be reopened?
