### ISSUE TITLE
Authorization headers not passed in 1.7.1

### ISSUE THREAD

**Issue by paulholden** [influxdata/chronograf#4774]
Since upgrading to **1.7.1** this morning, most of the UI fails to load - checking the browser console shows numerous "SyntaxError: Unexpected token < in JSON at position 0" errors

Here is the "Show Hosts" page failing:

![unable to get hosts](https://user-images.githubusercontent.com/1126541/48189767-d5d54e00-e338-11e8-9340-8218ae5561e8.png)

If I examine the requests (from the console _Network_ tab, and copying to a CURL command) I can see the source of the problem is that the _Authorization_ header is not being included, unlike the XHR requests which do include it

If I paste the CURL command into a terminal I receive back a "401 Unauthorized" response, but if I include the _Authorization_ header the request works fine

We use Apache as a reverse proxy sitting in front of Chronograf, for authorization. Everything was working fine prior to this upgrade (**1.6.2**)

**Comment by 121watts** [comment]
Hey there!  Thanks for writing in. This was a lot of great information in the bug report!

Are you using an OAuth provider?  What version of InfluxDB are you running?

**Comment by 121watts** [comment]
In the meantime would you humor me and re-add your username and password to the source you're trying to connect to under the configuration tab

<img width="1669" alt="screen shot 2018-11-08 at 3 13 06 pm" src="https://user-images.githubusercontent.com/7582765/48233164-21075500-e369-11e8-953b-ad6cdbcf220f.png">

The reason I'm recommending trying this is I was able to repro this by setting `auth-enabled=true` in my influxdb conf file and having the wrong password in Chronograf.

**Comment by russorat** [comment]
closing this for now. if you are still seeing this, please reopen

**Comment by paulholden** [comment]
Apologies @121watts & @russorat for the late response.

> Are you using an OAuth provider? What version of InfluxDB are you running?

No OAuth provider. Currently using InfluxDB version **1.7.4** where the issue persists.

> In the meantime would you humor me and re-add your username and password to the source you're trying to connect to under the configuration tab

I've re-configured the InfluxDB / Kapacitor connection in the Chronograf UI and it confirms the connection is working - however it hasn't fixed the rest of the UI (i.e. the _Show Hosts_ page as in my original description).

If I use my browser (Chromium) developer tools to examine the requests, and copy the failed one as a curl command I get the following (notice the missing _Authorization_ header):

```
curl 'https://{CHRONOGRAFURL}/chronograf/v1/sources/1/proxy' -H 'Origin: https://{CHRONOGRAFURL}' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/65.0.3325.181 Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: text/plain;charset=UTF-8' -H 'Accept: */*' -H 'Referer: https://{CHRONOGRAFURL}/worker.8eb1f386.js' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary $'{"query":"SELECT ...","db":"telegraf"}' --compressed
```

Executing that curl command results in a "401 Unauthorized" response. If I add the following:

```
-H 'Authorization: Basic cGhvbGRlbjp3ZWxkNjVtdXN0'
```

It returns correctly. It appears the absence of this header from the Chronograf request is the source of my problem.

We use Apache as a reverse proxy in front of Chronograf, which provides the authentication using ldap _AuthBasicProvider_). If I temporarily disable the authentication config in the Apache vhost then this fixes the problem in Chronograf - again, this seems to point back to the absence of the _Authorization_ header being the problem. As I mentioned, up to (and including) version **1.6.2** this same configuration worked great.

I don't appear to have permission to re-open this issue. Let me know if there's any further information I can provide.

**Comment by paulholden** [comment]
OK, I just found #4817 which describes pretty much identical symptoms as this task, and the explanation by @AJMaricq in [this comment](https://github.com/influxdata/chronograf/issues/4817#issuecomment-439531475) led me to try a different browser (Firefox).

Bizarrely, using this browser with Chronograf does work! So, I'm not sure why the version of Chromium I'm using fails, but at least I have a workaround 🙂

**Comment by peterdey** [comment]
I'm seeing this issue in Microsoft Edge 42.17134.1.0, after upgrading from 1.6.2-1 -> 1.7.4-1 (Ubuntu).

My Chronograf is also situated behind an Apache Reverse Proxy.

Issue presents when Basic authentication is enabled.  When disabled, the issue disappears.

POST Request to /chronograf/proxy just sits in (pending) and never completes.

![chronograf_nohosts](https://user-images.githubusercontent.com/5979944/50755086-0c353800-12ac-11e9-8a5e-55c92ecbf7ae.png)
![chronograf_nohosts_console](https://user-images.githubusercontent.com/5979944/50755087-0c353800-12ac-11e9-9e4e-99777af880bb.png)
