### ISSUE TITLE
Some protoboards have the db name hardcoded

### ISSUE THREAD

**Issue by lpic10** [influxdata/chronograf#4775]
Some (most?) protoboards dashboards do not work for me on chronograf 1.7 as they have the telegraf database name hardcoded as `telegraf` and retention period hardcoded as well.

A clear example is the system dashboard.

**Comment by paulholden** [comment]
You can edit the query behind all the dashboard tiles to correct the database/retention period (I also had the same problem with the System dashboard)

**Comment by lpic10** [comment]
Yes, that is correct, but part of the dashboards (eg. docker) correctly use the placeholders `:db:` and `:rp:` on the json files which makes them work by default
