### ISSUE TITLE
canned app groupby not working as expected in 1.7.2

### ISSUE THREAD

**Issue by pabigot** [influxdata/chronograf#4789]
I recently updated chronograf from 1.4.0.1 to 1.7.2.  Under 1.4.9 the canned system app used to display disk usage per path.  While in 1.7.2 it appears it's supposed to still do this, it does not: I get a single blue line that averages the usage across the paths.

Similarly, "groupbys" for ping don't appear to distinguish destination by url.

My guess is something's broken with groupbys, but I have no clue where, or whether it's just me.  The grouping is handled correctly when I use the explore feature and group by "path".

**Comment by russorat** [comment]
@pabigot what version of telegraf are you using to gather those metrics? the canned dashboards are designed to work with the latest versions of the corresponding telegraf plugins. i see a few changes some months ago, so it could be that the names of the tags changed.

Also, thank you very much for the PR that fixes a few issues with canned dashboards!

**Comment by pabigot** [comment]
I updated the entire TICK stack today; telegraf is at 1.8.3.  The field name remains `path` in both versions for disk; for ping it's still `url`, so there was no name change.

Re PR: you're welcome.

**Comment by pabigot** [comment]
Results from some fairly painful bisecting:

Grouping works at this commit:

c30d939c6 [Mon Sep 17 17:47:55 2018 -0700] Merge pull request #4472 from influxdata/bugfix/config-kapacitor-without-switching-source

The next commit:

9f8d3983e [Mon Sep 17 18:35:10 2018 -0700] Show flux results in table graph (#4461)

generates "A Chronograf error has occurred" in all system cells.  This was fixed by:

5bae044b1 [Fri Sep 21 16:19:06 2018 -0700] Refactor host page (#4488)

at which point grouping does not work.  Moving the patch for the host page immediately after 9f8d3983e produces a "working" chronograf but grouping has been lost.

The cause of the problem is not obvious to me.  [This branch](https://github.com/pabigot/chronograf/tree/repro-4789) in my fork shows the rebased transition from working to not working in its top three commits.

**Comment by chnn** [comment]
@pabigot I've got a fix for this in https://github.com/influxdata/chronograf/pull/4806, which should go out in the next Chronograf release (1.7.3) shortly. 

Thanks for the detailed report and investigation, it was very helpful.
