### ISSUE TITLE
Build warning: Could not load source file "../src/index.ts" in source map of "../node_modules/calculate-size/lib/index.js"

### ISSUE THREAD

**Issue by AdamSLevy** [influxdata/chronograf#4790]
I maintain the Arch Linux PKGBUILD for chronograf in the AUR. I am running into the following warning during the build process for version 1.7.2.

```
...
yarn run v1.12.3
$ GIT_SHA=$(git rev-parse HEAD) parcel build -d build --log-level 2 --no-source-maps --public-url '' src/index.html
⚠️  Could not load source file "../src/index.ts" in source map of "../node_modules/calculate-size/lib/index.js".
Done in 60.98s.
...
```

The build completes successfully and I have not noticed any issues when installing the package or running chronograf, but I would like to understand the above warning and bring it to the devs' attention.

Thank you

**Comment by russorat** [comment]
@AdamSLevy thanks for reporting. I think that's an issue with a 3rd party lib we are using. It should not negatively impact the build in any way.
