### ISSUE TITLE
 Chronograf (1.7.2) Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by stoinov** [influxdata/chronograf#4801]
Deployed the latest docker image with default settings. Connected t another default influx docker image. When I try to create a new DB through the UI, if I click `Edit` on the retention policy and then leave it as it is and click `Save`, I get the error below. I presume it's because of the `∞` symbol.
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at https://localhost/src.df1b5479.js:4587:1918
    at https://localhost/src.df1b5479.js:1348:309
    at r (https://localhost/src.df1b5479.js:1019:74)
    at https://localhost/src.df1b5479.js:1348:286
    at https://localhost/src.df1b5479.js:1300:142
    at https://localhost/src.df1b5479.js:1296:172
    at a (https://localhost/src.df1b5479.js:1300:115)
    at o (https://localhost/src.df1b5479.js:1348:250)
    at https://localhost/src.df1b5479.js:1366:237
    at e (https://localhost/src.df1b5479.js:1350:105)
```
When I edit already created DB with this retention I can save it just fine.

**Comment by 121watts** [comment]
@stoinov  thanks for writing in.  I'll be opening up a PR shortly to resolve this issue.
