### ISSUE TITLE
Notes should only display after the first data refresh has come back with no data

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4804]
as a dashboard viewer
with editor permissions or higher
when i open a dashboard with notes on cells configured to display when there is no data
then the notes should only display after the first unsuccessful query.

right now, a user sees a giant wall of text for a moment before the queries load.

**Comment by chnn** [comment]
I believe this was fixed and am having trouble reproducing the issue. Any special steps to see this?

**Comment by chnn** [comment]
Ah ok, I'm able to reproduce it by switching back and forth from a dashboard and the dashboards index. I will look into it.
