### ISSUE TITLE
Chronograf 1.7.3-1 Update caused Invalid principal / Forbidden with GitLab Auth

### ISSUE THREAD

**Issue by brad-deam** [influxdata/chronograf#4817]
- 64-Bit Red Hat Enterprise Linux Server release 7.5 (Maipo)
- Chronograf Version 1.7.3-1 
- Updated from 1.6.2 'yum -y localupdate chronograf-1.7.3.x86_64.rpm'
- Upon login (which correctly authenticates with GitLab) I am unable to query any databases using 'Data Explorer' or retrieve hosts on the 'Hosts' page:
![image](https://user-images.githubusercontent.com/40452846/48523344-00408180-e8cc-11e8-8d8e-fb25a9907bff.png)

Chronograf 'journalctl -u chronograf.server -f' shows the following when requesting either Data Explorer or Hosts page:
![image](https://user-images.githubusercontent.com/40452846/48523485-94124d80-e8cc-11e8-924d-9c070b8b471e.png)

Removing oAuth/GitLab Env VARs from the /etc/default/chronograf file (disabling the Auth) results in functionality being restored.

cat /etc/default/chronograf
REPORTING_DISABLED=true
STATUS_FEED_URL=http://<REDACTED>/json_feed
GENERIC_NAME=gitlab
GENERIC_CLIENT_ID=<REDACTED>
GENERIC_CLIENT_SECRET=<REDACTED>
GENERIC_AUTH_URL=http:// <gitlab-server>/oauth/authorize
GENERIC_TOKEN_URL=http:// < gitlab-server >/oauth/token
TOKEN_SECRET=<REDACTED>
GENERIC_SCOPES=api,openid,read_user
PUBLIC_URL=http://chronograf-server:8888
GENERIC_API_URL=http://gitlab-server/api/v3/user

Kapacitor connects with no issues and I am able to edit & save TICK scripts.

**Comment by russorat** [comment]
@brad-deam thanks for the report. if you can successfully log into Chronograf, that means the OAuth is working. we don't use the OAuth token for communicating with the database. Can you view your dashboards?

If possible, could you open your chrome javascript console and let us know if you see errors there? It would help us debug.
![image](https://user-images.githubusercontent.com/4805997/48567795-d038b480-e8b2-11e8-92d7-ab7bf428a62c.png)

**Comment by brad-deam** [comment]
Np :) Ignore the json_feed errors 👍 


Here's a series of screenshots with accompanying console logs:
![image](https://user-images.githubusercontent.com/40452846/48592111-c8ead700-e996-11e8-8c82-3a91b6987fc4.png)

![image](https://user-images.githubusercontent.com/40452846/48592164-0f403600-e997-11e8-87b4-ff057252230d.png)

We don't use any Chronograf dashboards, but I am unable to click into newly created dashboards:

![image](https://user-images.githubusercontent.com/40452846/48592247-60502a00-e997-11e8-9ef0-4b564ef0d3fe.png)

Loading Host List
![image](https://user-images.githubusercontent.com/40452846/48592342-deaccc00-e997-11e8-9e80-ee0bc06a909a.png)

Loading Data Explorer
![image](https://user-images.githubusercontent.com/40452846/48592385-13208800-e998-11e8-9bfb-a907a54ed481.png)

My User Setup:
![image](https://user-images.githubusercontent.com/40452846/48592441-4fec7f00-e998-11e8-8f19-1211d4b95e33.png)

![image](https://user-images.githubusercontent.com/40452846/48592466-68f53000-e998-11e8-9c5a-4c67bcf00e08.png)

**Comment by AJMaricq** [comment]
Hi, I can provide a little bit of perspective here as we recently had one of our team affected by this issue.  I'll preface this with what ended up fixing it for him:  Upgrading from Chrome 67 to Chrome 70 (69 also appears to be fine), though I'm unsure if this was the actual fix or merely instigated the action that fixed it.  For now, it at least appears tied to browser version.

We also use Gitlab-based oauth2, HTTPS, and formerly used Chronograf version 1.6.1 with our TICK stack all running on Ubuntu 18.04.  This worked without issue for all users involved.  We migrated our entire TICK stack setup over to a new server (same hostname), which involved upgrading our packages.  Chronograf was upgraded to 1.7.1 (and then later 1.7.3), and began exhibiting the same behavior as described in the issue.

What he noticed is that POSTs to `https://<chronograf-host>/chronograf/v1/sources/1/proxy` were not having the cookie header set with `session=`.  When he manually added the cookie header, the failing POSTs worked.  Strangely, none of the rest of our team (myself included) had this problem.  He noticed this problem didn't manifest on his desktop, with Chrome 69, and did on his laptop, with Chrome 67.  Upgrading to Chrome 70 on his laptop fixed the issue for him, so either some bad interaction was fixed in these later versions, or the process cleared some stale browser state, or something...

Attached example log:
```
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=GET remote_addr="<ip>:45708" url=/chronograf/v1/dashboards/1
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=GET remote_addr="<ip>:45708" response_time="146.331Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: No Content" component=server method=GET remote_addr="<ip>:45690" response_time=2.467221ms status=204
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=POST remote_addr="<ip>:45686" response_time=3.742787ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=POST remote_addr="<ip>:45704" response_time=3.79135ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=POST remote_addr="<ip>:45702" response_time=4.913855ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=POST remote_addr="<ip>:45706" response_time=5.083876ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=POST remote_addr="<ip>:45692" response_time=6.999136ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: No Content" component=server method=GET remote_addr="<ip>:45692" response_time=1.603338ms status=204
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=POST remote_addr="<ip>:45708" url=/chronograf/v1/sources/1/proxy
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=POST remote_addr="<ip>:45708" response_time="85.595Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=GET remote_addr="<ip>:45706" response_time=4.510212ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=POST remote_addr="<ip>:45708" url=/chronograf/v1/sources/1/proxy
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=POST remote_addr="<ip>:45708" response_time="427.595Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=POST remote_addr="<ip>:45696" url=/chronograf/v1/sources/1/proxy
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=POST remote_addr="<ip>:45696" response_time="58.297Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=POST remote_addr="<ip>:45698" url=/chronograf/v1/sources/1/proxy
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=POST remote_addr="<ip>:45698" response_time="348.034Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=error msg="Invalid principal" component="token_auth" method=POST remote_addr="<ip>:45718" url=/chronograf/v1/sources/1/proxy
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: Forbidden" component=server method=POST remote_addr="<ip>:45718" response_time="84.982Âµs" status=403
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=GET remote_addr="<ip>:45692" response_time=4.091735ms status=200
Nov 15 09:02:42 <chronograf-host> chronograf[18161]: time="2018-11-15T09:02:42-07:00" level=info msg="Response: OK" component=server method=GET remote_addr="<ip>:45692" response_time="939.675Âµs" status=200
```

Hope this helps!

**Comment by brad-deam** [comment]
@AJMaricq 
This fixed my issue! 

Our offline environment is running default Chrome 60 - a quick update to Chrome 70 and no issues. 👍

**Comment by russorat** [comment]
@AJMaricq thank you for the explanation! @brad-deam please let us know if you have any more issues

**Comment by peterdey** [comment]
I'm seeing this issue in Microsoft Edge 42.17134.1.0, after upgrading from 1.6.2-1 -> 1.7.4-1 (Ubuntu).

My Chronograf is also situated behind an Apache Reverse Proxy.

Issue presents when Basic authentication is enabled.  When disabled, the issue disappears.

POST Request to /chronograf/proxy just sits in (pending) and never completes.

![chronograf_nohosts](https://user-images.githubusercontent.com/5979944/50755086-0c353800-12ac-11e9-8a5e-55c92ecbf7ae.png)
![chronograf_nohosts_console](https://user-images.githubusercontent.com/5979944/50755087-0c353800-12ac-11e9-9e4e-99777af880bb.png)

**Comment by mqu** [comment]
hello, I am having same bug here, with Firefox, Chronograf 1.7.7-1, gitlab oauth2 and apache2 reverse proxy.

- when I unset Oauth2 authentification, I have no trouble,
- when Oauth2 is setup, no trouble with chromium vers 71, but many troubles with Firefox (many versions, 60.4)  : 
  - hosts not visible,
  - dashboard wont display,
- in web console, I have a 403 error for https://chronograf.my.domain/chronograf/v1/sources/2/proxy

**Comment by mqu** [comment]
some feedback : it's working as expected with Mozilla Firefox 64 and 65.

**Comment by jgalak** [comment]
Having the same issue with Firefox 60.5.1esr

**Comment by jgalak** [comment]
Having the same issue with Firefox 60.5.1esr and in MS Edge 42.17134.1.0
