### ISSUE TITLE
Tags Containing Leading 0s or other characters are mangled

### ISSUE THREAD

**Issue by dlouisroberts** [influxdata/chronograf#4818]
Details:
- Chronograf docker container latest (as of today, 11/15), built 6 days ago
- Connected to InfluxDB 1.7.0 (also docker container)
- Host OS: Ubuntu 18.04.1
- Browser: Google Chrome 70.0.3538.102

I have a measurement with a tag that is a randomly generated Globally Unique Identifier. When using the Influx CLI, queries display the tag correctly. Further, when exporting a .csv using Chronograf the tag displays correctly; however, in the Chronograf GUI, some values are converted to decimal notation, truncated, or otherwise altered. 

I've attached a screenshot of a subset of results of the `SHOW TAG VALUES` query showing that some tags are correctly formatted while others are mangled. 

![screen shot 2018-11-15 at 12 36 12 am](https://user-images.githubusercontent.com/33221565/48532472-81692b80-e86e-11e8-86c0-0ea3196f72da.png)

**Comment by russorat** [comment]
@dlouisroberts thanks for the report! we will investigate!
