### ISSUE TITLE
Flux builder and historical data

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/chronograf#4821]
Problem: Flux builder doesn’t work/can’t find measurements because it’s default query doesn’t look at all historical data. 

Using: InfluxDB v1.7.1 and Chronograf v1.7.3

Sampe dataset from https://docs.influxdata.com/influxdb/v1.7/query_language/data_download/

When I use InfluxQL I can successfully query the data and return this result. 

<img width="1310" alt="screen shot 2018-11-16 at 12 54 04 pm" src="https://user-images.githubusercontent.com/30506042/48649581-aec1f080-e9b8-11e8-94f3-cffa1f8a97cb.png">

When I try to use the Flux builder, the measurements, tags, and fields are empty. When I look at the Request payload I see this default query: 
``` from(bucket:"NOAA_water_database")
 |>range(start:-30d)
 |>group(by:["_field","_measurement"])
 |>distinct(column:"_field")|>group(none:true)
 |>map(fn:(r)=>({_measurement:r._measurement,_field:r._field}))
```

So when I use the flux builder no measurements, fields, tags are returned...

<img width="1311" alt="screen shot 2018-11-16 at 12 54 24 pm" src="https://user-images.githubusercontent.com/30506042/48649593-baadb280-e9b8-11e8-98d1-b21fd4712f53.png">

When I run 
``` influx -type 'flux' -execute 'from(bucket:"NOAA_water_database")
 |>range(start:-30d)
 |>group(by:["_field","_measurement"])
 |>distinct(column:"_field")|>group(none:true)
 |>map(fn:(r)=>({_measurement:r._measurement,_field:r._field}))' 
```
I don’t get any results as expected.

When I change the range, I get the expected results. This query works: 

 ``` influx -type 'flux' -execute 'from(bucket:"NOAA_water_database")
 |>range(start:-700d)
 |>group(by:["_field","_measurement"])
 |>distinct(column:"_field")|>group(none:true)
 |>map(fn:(r)=>({_measurement:r._measurement,_field:r._field}))' 
```

**Comment by russorat** [comment]
@Anaisdg thanks for the issue. i'm not sure i understand what the problem is. You initial InfluxQL query has no time range on it, which means it's querying for all time. Your Flux query has a time range, and it looks like there was no data found in the past 30d, which seems right. 

You would have had to manually edit the influxql query to remove the time range in order for that to work, just like you would have to manually update the flux query to get that to work.

Could you help me understand more about what you are expecting here?

**Comment by Anaisdg** [comment]
I wish the default query included a longer time range, so that I could use the flux builder on historical data. Unfortunately, I can't manually change the query. It looks like it just defaults to -30d. Even if I change the dates with the date picker, the measurements, tags, and fields don't populate in the flux builder. 

<img width="1452" alt="screen shot 2018-11-19 at 1 56 28 pm" src="https://user-images.githubusercontent.com/30506042/48731580-fc319e00-ec02-11e8-97b5-af35455ee44a.png">

**Comment by Anaisdg** [comment]
I'm expecting to have measurements, tags, and fields appear in the flux builder for historical data.

**Comment by russorat** [comment]
So it sounds like we need to update the meta queries to use the time range from the drop down you have selected. I don't want it to do for all time since it might return a massive amount of tags.

**Comment by bthesorceror** [comment]
I don't think its a good idea to have this tied to that dropdown, as it starts out at a small time range more people will see a screen that looks like they have no tags and no clear indication that this dropdown affects that.

**Comment by thatguydan** [comment]
30d is a bit arbitrary. I just lost 20 minutes trying to figure out why my measurements were not showing up in Chronograf before finding this thread. After realising the measurement list might be defined by the data window, I had expected changing the drop down would show more measurements. Perhaps update the dropdown to 30d and then update the meta list based on the data window?
