### ISSUE TITLE
Unfortunate UI with Flux Script Wizard

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/chronograf#4822]
Problem: UI problem. I can’t scroll down when using the Flux Script Wizard.

Using: Chrome

 If my browser zoom is set to 100% and full screen, and I try to use the flux script wizard this is what I see: 
<img width="1220" alt="screen shot 2018-11-16 at 12 54 51 pm" src="https://user-images.githubusercontent.com/30506042/48649847-a3bb9000-e9b9-11e8-8a0b-d8bc23c615a0.png">

I can’t scroll down to see/reach the Insert Script button. I have to zoom out. 

<img width="1281" alt="screen shot 2018-11-16 at 12 55 14 pm" src="https://user-images.githubusercontent.com/30506042/48649864-afa75200-e9b9-11e8-90a9-2cbe933e8445.png">

**Comment by bogski87** [comment]
> 
> 
> Same problem when pasting a long tickscript in the script editor. Impossible to scroll, have to zoom out. Latest Firefox stable.

same for me, using Firefox - I load the TICK editor, sometimes i can scroll down sometimes i cant. sometimes i can scroll down but then can't scroll back up.
