### ISSUE TITLE
Microsoft Graph as Generic OAuth provider

### ISSUE THREAD

**Issue by nilsonfh** [influxdata/chronograf#4823]
I am trying to use Microsoft Graph as Generic OAuth provider. I follow the instructions from https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent. The next Chronograf settings are used:

TOKEN_SECRET=**********
AUTH_DURATION=1h
PUBLIC_URL=http://localhost:8888
GENERIC_CLIENT_ID=**********************
GENERIC_AUTH_URL=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
GENERIC_CLIENT_SECRET=************
GENERIC_TOKEN_URL=https://login.microsoftonline.com/common/oauth2/v2.0/token
GENERIC_SCOPES="openid email"
GENERIC_API_URL=https://graph.microsoft.com/v1.0/users 

Microsoft Graph authorizes the connection, however, in the side of Chronograf I am getting this error : 
level=error msg="Unable to get principal identifier json: cannot unmarshal object into Go value of type []*oauth2.UserEmail"

**Comment by russorat** [comment]
@nilsonfh thanks for the issue. In general, it's pretty tough for us to debug something like this on our end since we haven't tested generic oauth on all providers. Have you seen this PR which has an example config in it? https://github.com/influxdata/chronograf/pull/2400

Looks like the only difference is they only use openid for generic scope instead of email. Could you try that?

**Comment by nilsonfh** [comment]
Finally it works. I keep "openid email" for generic scope (Microsoft  requires "openid"  and Chronograf  requires "email"). I add two extra environment variables:  USE_ID_TOKEN and JWKS_URL. The final configuration looks like this:
TOKEN_SECRET=*********************
AUTH_DURATION=1h
PUBLIC_URL=http://localhost:8888
GENERIC_CLIENT_ID="Application Id"
GENERIC_CLIENT_SECRET="Password from Application Secrets"
GENERIC_AUTH_URL=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
GENERIC_TOKEN_URL=https://login.microsoftonline.com/common/oauth2/v2.0/token
GENERIC_SCOPES="openid email"
GENERIC_API_URL=https://graph.microsoft.com/v1.0/users
USE_ID_TOKEN=true
JWKS_URL=https://login.microsoftonline.com/common/discovery/keys

Thanks for the help!

**Comment by russorat** [comment]
@nilsonfh awesome!
