### ISSUE TITLE
Column in table result right aligned

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4829]
When using the table results view on a large (27" 4K) monitor, the values column is right-aligned, and miles away from the time column.

![screenshot 2018-11-22 12 59 41](https://user-images.githubusercontent.com/501993/48904552-a48b7080-ee56-11e8-8470-03cd33ff41af.png)

Maybe the values column could be left aligned to make it easier to read the results?

**Comment by e-dard** [comment]
don't close

**Comment by vit1251** [comment]
Another one issue is date time nanoseconds values is hide and does not have any way to see this values. No column resize or similar controls.
