### ISSUE TITLE
Tickscript Dissaperad from manage task

### ISSUE THREAD

**Issue by amittestkiwi** [influxdata/chronograf#4833]
We had around 150 Tickscript in our chronograph task. kapacitor and cronograph both running on same RHEL 7 machine, last night all the tick script appered from the list and "kapacitor list task" showed no task. i am unable to find anything in logs.
what could be the reason and where can we find more detail.
chronograph is accessed via reverse proxy on different server and with port 8888 on same server.
servers are privately hosted datacenter and a vpn tunnel is used to access

**Comment by russorat** [comment]
@amittestkiwi Is it possible that chronograf is unable to connect to the kapacitor instance? Could you verify that you can get to the Kapacitor configuration page and view the endpoints?

![image](https://user-images.githubusercontent.com/4805997/49461377-64a68080-f7a8-11e8-9a1d-14c875b391af.png)

**Comment by amittestkiwi** [comment]
This may be the issue , we just restored it from out backup. 
On side not is there any way where we can store our script in github and then tick script in chronograf are configured according to that.
