### ISSUE TITLE
Timezone selection

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#4837]
I watch chronograf report from computer with one time zone, watching system write reporting in second timezone, influx work with third datacenter with another one timezone. 

How to determin what I see on chronograf and many be UI solution to fast switch timezone (timezone correction)?

**Comment by vit1251** [comment]
@stale you should help to promote issue. I already up that issue for example server in L.A. but developers in N.Y. and servers around.

**Comment by vit1251** [comment]
Look like some activity by issue is provided i.e. I see that in UI we have Timezone switcher but does not understand about backend. Could you please clarify system like Telegraf using UTC timezone to report metrics?

**Comment by russorat** [comment]
@vit1251 i'm a little confused here. Is the data being written into influxdb in UTC for all locations? If so, then all your developers will be looking at the time in UTC in chronograf, or they can select their local timezone to view the data.

Can you describe the additional capability you are looking for?

**Comment by vit1251** [comment]
@russorat I little confused by Python wrapper where we receive DtaeTime object in timezone. That's no more question.

**Comment by russorat** [comment]
thanks!
