### ISSUE TITLE
Stacked chart display seems off

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4843]
I have a stacked graph that stopped receiving any data for a while (reason not important). Then later on, data for one of the series started to come through.

Becuase there was still data for the other series from previous time periods, the new series did not get drawn at the correct place on the Y axis (`0`), but instead was drawn relative to it's previous stacked position.

To clarify, the purple series was originally `1`, and then went down to `0`, but it was drawn at relative position `6`, even though there were no other series for the time period.

![screenshot 2018-11-28 15 17 24](https://user-images.githubusercontent.com/501993/49161533-f46bab00-f320-11e8-958c-6c95358090b0.png)

**Comment by ischolten** [comment]
This seems to be an issue with the Dygraphs library. Issue created in the library: https://github.com/danvk/dygraphs/issues/950

**Comment by e-dard** [comment]
don't close
