### ISSUE TITLE
Chronograf log viewer hanging

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4851]
I went to refresh the log viewer and it just hangs.

I checked the server and no queries are running. No other server activity to speak of.

The browser console shows:

![screenshot 2018-11-29 10 43 11](https://user-images.githubusercontent.com/501993/49216827-e9b62200-f3c3-11e8-8a53-9a905cb67a84.png)

Network tab looked like this:

![screenshot 2018-11-29 10 47 47](https://user-images.githubusercontent.com/501993/49216949-41548d80-f3c4-11e8-9b7b-815d414a3c3d.png)

**Comment by bthesorceror** [comment]
@e-dard did you have any filters in place when this happened?
