### ISSUE TITLE
Error save annotations

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#4852]
How to fix? Any suggest why error is occure?

![image](https://user-images.githubusercontent.com/110534/49223381-a671a880-f3ef-11e8-93d3-50cd2aabdd74.png)

**Comment by vit1251** [comment]
How to set annotations over Python API or HTTP RESTful API?

**Comment by russorat** [comment]
@vit1251 annotations are saved to the database in the `chronograf` database. Can you confirm that you have write access to the influx instance you are connected to?

**Comment by vit1251** [comment]
@russorat I write metrics as you can see on screenshot at that instance. I upgrade instance a lont time without config update.

**Comment by russorat** [comment]
@vit1251 can you confirm that the user credentials you are using in your source connection have write permissions to the `chronograf` database?
![image](https://user-images.githubusercontent.com/4805997/49389364-f942ad00-f6da-11e8-939f-313a625d896a.png)

Could you also verify that there is a `chronograf` database using the explore page?
![image](https://user-images.githubusercontent.com/4805997/49389489-4fafeb80-f6db-11e8-8b2c-39269f8dfa60.png)

**Comment by vit1251** [comment]
@russorat access allow. Database exists.

Only one change is "autogen" was remove and create "weekly" with 8 day retention policy.

**Comment by russorat** [comment]
@vit1251 for annotations to work, the chronograf database will need an autogen retention policy.

**Comment by vit1251** [comment]
@russorat ok, but it look like InfluxDB design problem. Why reading data depend from my retention policy?

**Comment by russorat** [comment]
@vit1251 for sure, the issue is in on our side. I will leave this open as an enhancement request.

**Comment by alexanderfefelov** [comment]
@vit1251 same problem.

Chronograf 1.7.8, InfluxDB 1.7.5.

**Comment by vit1251** [comment]
@alexanderfefelov as say @russorat before right now InfluxDB use retention policy in query and it main problem. You may create "autogen" with you own retention policy but name should "autogen".

I belive that InfluxDB team unbind retention policy from select query and insert system or meke it optional.

**Comment by alexanderfefelov** [comment]
My retantion policy is `autogen`.

```
> show databases
name: databases
name
----
graphite
_internal
> use telegraf
Using database telegraf
> show retention policies
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        true
>
```

**Comment by vit1251** [comment]
@alexanderfefelov you does not have "chronograf" database. Telegraf is monitoring system. Chronograf is Web UI with annotation storage.
