### ISSUE TITLE
Installing on FreeBSD

### ISSUE THREAD

**Issue by bwmarrin** [influxdata/chronograf#4859]
I'm checking in to see if building on FreeBSD is supported - or, if it works.  If so, are there any instructions anywhere that help guide how to get Chronograf compiled on FreeBSD.

I see there's one issue, where it seems no FreeBSD support will ever exist, yet another issue where someone seems to have compiled it on FreeBSD.  

https://github.com/influxdata/chronograf/issues/3105
https://github.com/influxdata/chronograf/issues/2081

So, my question is.

Can Chronofraf run on FreeBSD?
Can Chronograf be compiled on FreeBSD?
Are there any instructions to accomplishing either of these (or both) ?

@bunnyevans  can you jump in perhaps and give point me in the right direction, it looks as though you were successful at getting things going on FreeBSD.

thanks!

P.S. If there's a way to build FreeBSD binaries, it would be cool if that could be added to your release script so pre-made binaries could just be downloaded :)

**Comment by bunnyevans** [comment]
I ended up using grafana because features.
It just built with the instructions here:

https://github.com/influxdata/chronograf/blob/master/CONTRIBUTING.md

**Comment by bwmarrin** [comment]
Thanks @bunnyevans  :) I was thinking I would look into grafana as an option, I guess this helps motivate that.

**Comment by nhaugo** [comment]
Hi @bwmarrin, I have chronograf compiling fine on freebsd. I will put the steps together tomorrow.

**Comment by nhaugo** [comment]
Hi @bwmarrin here is the process i used to compile chronograf on FreeBSD.

On a base FreeBSD 11.2-RELEASE, I installed the following ports
yarn-1.12.3
wget-1.20
npm-node10-6.4.1_1
node10-10.13.0
gmake-4.2.1_3
git-2.19.2

Then I ran the following commands
`wget https://dl.google.com/go/go1.11.2.freebsd-amd64.tar.gz`
`tar zxxvf go1.11.2.freebsd-amd64.tar.gz`
`export PATH=$PATH:$HOME/go/bin`
`export GOPATH=$HOME/src/go`
`mkdir src/go/src/github.com/influxdata`
`cd src/go/src/github.com/influxdata`
`git clone https://github.com/influxdata/chronograf.git`
`sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python`
`cd chronograf`
`gmake`

It would be great to know if this works for you, for reference, grafana also does not have supported FreeBSD packages. 

For reference here is my full set of ports installed
```
asciidoc-8.6.10_1                  =
autoconf-2.69_2                    =
autoconf-wrapper-20131203          =
automake-1.16.1_1                  =
bash-4.4.23_1                      =
bison-3.2.2,1                      =
boehm-gc-7.6.8_1                   =
c-ares-1.14.0_1                    =
ca_root_nss-3.40.1                 =
check-0.12.0_1                     =
curl-7.62.0                        =
cvsps-2.1_2                        =
desktop-file-utils-0.23            =
dialog4ports-0.1.6                 =
docbook-1.5                        =
docbook-sgml-4.5_1                 =
docbook-xml-5.0_3                  =
docbook-xsl-1.79.1_1,1             =
expat-2.2.6_1                      =
fontconfig-2.12.6,1                =
freetype2-2.9.1                    =
getopt-1.1.6                       =
gettext-runtime-0.19.8.1_2         =
gettext-tools-0.19.8.1_1           =
git-2.19.2                         =
glib-2.56.3_1,1                    =
gmake-4.2.1_3                      =
gperf-3.0.3_2                      =
help2man-1.47.8_1                  =
icu-63.1,1                         =
indexinfo-0.3.1                    =
iso8879-1986_3                     =
libX11-1.6.7,1                     =
libXau-1.0.8_5                     =
libXdmcp-1.1.2_2                   =
libXext-1.3.3_3,1                  =
libXrender-0.9.10_2                =
libatomic_ops-7.6.4                =
libedit-3.1.20170329_2,1           =
libffi-3.2.1_3                     =
libgcrypt-1.8.4_1                  =
libgpg-error-1.32_1                =
libiconv-1.14_11                   =
libidn2-2.0.5_1                    =
libltdl-2.4.6                      =
libnghttp2-1.35.0                  =
libpaper-1.1.24.4                  =
libpthread-stubs-0.4               =
libtool-2.4.6_1                    =
libunistring-0.9.10_1              =
libunwind-20170615                 =
libuv-1.24.0                       =
libxcb-1.13.1                      =
libxml2-2.9.7                      =
libxslt-1.1.32                     =
libyaml-0.2.1                      =
m4-1.4.18_1,1                      =
node10-10.13.0                     =
npm-node10-6.4.1_1                 =
p5-Authen-SASL-2.16_1              =
p5-CGI-4.40                        =
p5-Digest-HMAC-1.03_1              =
p5-Error-0.17027                   =
p5-GSSAPI-0.28_1                   =
p5-HTML-Parser-3.72                =
p5-HTML-Tagset-3.20_1              =
p5-IO-Socket-INET6-2.72_1          =
p5-IO-Socket-SSL-2.060             =
p5-Locale-gettext-1.07             =
p5-Locale-libintl-1.31             =
p5-Mozilla-CA-20180117             =
p5-Net-SSLeay-1.85                 =
p5-Socket6-0.29                    =
p5-Text-Unidecode-1.30             =
p5-Unicode-EastAsianWidth-1.40     =
pcre-8.42                          =
perl5-5.26.2_2                     =
pixman-0.34.0_1                    =
pkg-1.10.5_5                       =
pkgconf-1.5.4,1                    =
png-1.6.35                         =
python27-2.7.15                    =
python36-3.6.7                     =
readline-7.0.5                     =
ruby-2.4.5,1                       =
sdocbook-xml-1.1_2,2               =
texinfo-6.5_2,1                    =
w3m-0.5.3.20180520_1               =
wget-1.20                          =
xcb-proto-1.13                     =
xcb-util-0.4.0_2,1                 =
xcb-util-renderutil-0.3.9_1        =
xmlcatmgr-2.2_2                    =
xmlcharent-0.3_2                   =
xmlto-0.0.28                       =
xorg-macros-1.19.2                 =
xorgproto-2018.4                   =
xtrans-1.3.5                       =
yarn-1.12.3                        =
```

**Comment by bwmarrin** [comment]
@nhaugo awesome, thanks for the details.  I will give this a try and report back.  I'm also on 11.2, though I'm using jails but that shouldn't be an issue here, I don't think.

**Comment by marcotuna** [comment]
I face the same issue today and the method that @nhaugo explains works. I used FreeBSD 11.2-RELEASE inside a FreeBSD Jail. I will upload the binaries later for someone interested in using.

**Comment by schmitmd** [comment]
@nhaugo , do you think you'd be willing to make a port?  Maybe we should ask cheffo@freebsd-bg.org , who's the maintainer of the existing influxdb port?
