### ISSUE TITLE
Logs - connection to enterprise cluster - logs show empty page on first load 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#4862]
Build **Nightly Build**
Build Time **201812032144**
Browser **Chrome 70**

```
$ chronograf --version
2018/12/04 13:14:44 Chronograf 201812032144~nightly (git: 9e171f6df10cb16a6a852f3a9b07475d32aa2f68)
```
*Use Case*

1. Start a test environment cluster using the script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh)
1. Open a fresh browser instance with no cookies or storage items
1. Create a source 
1. Open the Logs page 

The page is blank.  The source shows the body is nearly empty except for a script element. 

```
<!DOCTYPE html>
<html> 
   <head> 
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Chronograf</title> 
    <link rel="shortcut icon" href="/favicon.fa749080.ico"> 
    <link rel="stylesheet" href="/src.6adc4720.css">
   </head> 
   <body> 
      <div id="react-root" data-basepath=""></div> 
      <script src="/src.12d045cc.js"></script> 
   </body> 
</html>
``` 

Clicking reload shows the page. 

*Expected Behavior*

That the logs page should load on the first click of the logs icon, without having to reload the page. 

*Note on reproducing*

This happens on all [nightly runs of Selenium tests](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium/Chronograf_20Automated_20Test_20Report/), however on local test runs happens only intermittently.  Reproducing is not straight forward.  I've managed to reproduce it locally in Chrome Incognito Mode or when first opening the browser after OS reboot.  However it does not happen when the cluster is simply restarted, or the browser simply reloaded.

It also does not seem to be reproducible in Firefox 63 "Private Window" mode. 

It is reproducible in Opera 57 "Private Window" mode.  

*Screenshots* 

![emptylogs01](https://user-images.githubusercontent.com/25881301/49442284-53ba3700-f7c9-11e8-9c24-dad24d2a122f.png)
![emptylogs02](https://user-images.githubusercontent.com/25881301/49442285-53ba3700-f7c9-11e8-8b84-15302eb3f938.png)

*Console Log*

```
src.12d045cc.js:716 TypeError: Cannot read property 'brighter' of null
    at src.12d045cc.js:4233
    at Array.forEach (<anonymous>)
    at src.12d045cc.js:4233
    at Array.map (<anonymous>)
    at k (src.12d045cc.js:4233)
    at value (src.12d045cc.js:4233)
    at zl (src.12d045cc.js:716)
    at Ol (src.12d045cc.js:716)
    at aa (src.12d045cc.js:716)
    at fa (src.12d045cc.js:716)
va @ src.12d045cc.js:716
src.12d045cc.js:4233 Uncaught (in promise) TypeError: Cannot read property 'brighter' of null
    at src.12d045cc.js:4233
    at Array.forEach (<anonymous>)
    at src.12d045cc.js:4233
    at Array.map (<anonymous>)
    at k (src.12d045cc.js:4233)
    at value (src.12d045cc.js:4233)
    at zl (src.12d045cc.js:716)
    at Ol (src.12d045cc.js:716)
    at aa (src.12d045cc.js:716)
    at fa (src.12d045cc.js:716)
``` 

*Regression Note*

These tests were stable and working roughly a month ago.

**Comment by OfTheDelmer** [comment]
@karel-rehor I wasn't able to access the script at this [link](https://github.com/influxdata/chronograf/issues/201812032144). Is there another link to that script?

**Comment by karel-rehor** [comment]
Sorry for the copy-paste error.  The script is here. 

https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh

A readme including how we use it is here:

https://github.com/influxdata/bonitoo-selenium

**Comment by karel-rehor** [comment]
I noticed that in the most recent nightly test results, this issue did not appear.  It seems to be happening intermittently.  Experience over the last week is that it occurs more often than not.
