### ISSUE TITLE
In table visualisation IP address gets interpreted as float

### ISSUE THREAD

**Issue by phaethon** [influxdata/chronograf#4868]
I have data, which has IP addresses as tag values. When I display a table in chronograf (e.g. with a query like `select sum(value) from dataset group by ipaddress`) the IP address is being shortened as to decimal places settings in the resulting table. E.g. if I have IP address 123.234.211.252 it gets displayed as 123.23 if decimal places are set to 2. 

Using chronograf 1.7.3, influxdb 1.7.1 on MacOS

**Comment by phaethon** [comment]
On additional note - if I set Decimal places to 'unlimited', then IP addresses are displayed properly. But then of course any float is displayed with all decimal places.

**Comment by russorat** [comment]
i believe we solved this in https://github.com/influxdata/chronograf/issues/4818

it's in the nightly and will be in 1.7.4 which should be out this week

**Comment by russorat** [comment]
1.7.4 is released. please reopen if you still see this issue after the upgrade
