### ISSUE TITLE
Alert rules and TICK script

### ISSUE THREAD

**Issue by Puneeth-n** [influxdata/chronograf#4879]
I am new to Chronograf

`chronograf:1.7`

I have a tick script that does some alerting. It is running and sending alerts. However, it it not showing up i the UI under the Alert rules. Am I missing something?

![screen shot 2018-12-12 at 5 38 05 pm](https://user-images.githubusercontent.com/5619473/49884576-77b6f180-fe35-11e8-9da0-1635c4efc8a2.png)

**Comment by gamefundas** [comment]
How did you solve this? I have bunch of scripts that were originally rules but then later after some edits to the script it stopped showing in the rules section.

**Comment by sranka** [comment]
Alert rule is a TICKScript with a pre-defined layout so that it can be viewed/edited by chronograf UI. A manual change in a TICKscript may cause it is no longer recognized by the chronograf as an alert rule.
