### ISSUE TITLE
IE11 promise is not defined error

### ISSUE THREAD

**Issue by theone3nu** [influxdata/chronograf#4884]
Promise is undefined error in IE11. Works fine in chrome.

<img width="1434" alt="screen shot 2018-12-14 at 7 13 13 am" src="https://user-images.githubusercontent.com/22262757/49978278-c8326a00-ff6f-11e8-953e-54829f15bc6b.png">

**Comment by theone3nu** [comment]
I have debugged and found that this error is coming from Worker class.

I am getting the error Promise is Undefined in IE11. When i am using Worker in my code

    const worker = new Worker('./worker.ts')
console.log('worker' , worker);
When i check logs in chrome and IE 11 chrome returns worker onMessage as function where as IE 11 returns null and i also see message Permission denied. I also gets this error in IE 11 Promise is Undefined.

I have imported import 'babel-polyfill' in the begning of the file. All other Promises are working fine except this Worker.

Can any one please help me how to fix this.

**Comment by timhallinflux** [comment]
This remains a problem for IE and Edge users.

**Comment by bthesorceror** [comment]
Need to implement the fix in the repo and release a new version.

**Comment by bthesorceror** [comment]
addressed in https://github.com/influxdata/chronograf/pull/5183
