### ISSUE TITLE
Checksum for Chronograph 1.7.4 Ubuntu & Debian does not match one published

### ISSUE THREAD

**Issue by jereksel** [influxdata/chronograf#4885]
Hi,

When downloading Chronograph 1.7.4 for Ubuntu and Debian I'm getting different checksum on my machine:
`7f6e11a157863cd126777687f99334fd12b5d6178c6d70bb19764291a40c0bea`
instead of published
`b0e84edea1219d4608742689da43d9b907ed01414c784854caf45638aaf50ad2`

**Comment by nhaugo** [comment]
Hi @jereksel 
Thanks for the heads up. Our build system reran the tag and updated the checksum. We decided to take the time to update a couple of security issues, namely the one go lang issue https://github.com/golang/go/issues/29233

So we have released a 1.7.5 which can be downloaded from our downloads page https://portal.influxdata.com/downloads 

We will update the repos asap.

**Comment by nhaugo** [comment]
1.7.5 has been released and should be used instead.
