### ISSUE TITLE
Unhandled promise rejection when opening data-explorer in IE11

### ISSUE THREAD

**Issue by theone3nu** [influxdata/chronograf#4887]
Works fine in chrome. But when i am trying to open in IE 11 getting the error Unhandled promise rejection when trying to click explore. 

<img width="1433" alt="screen shot 2018-12-16 at 2 08 13 am" src="https://user-images.githubusercontent.com/22262757/50047273-0cd91500-00d8-11e9-9596-30f5a40dc8c3.png">

**Comment by ppizzo** [comment]
Same issue here with Edge/Explorer on Windows and with Firefox, both on GNU/Linux and Windows. No problem with Firefox on Android.

I can only manage to get it working with Chrome/Brave, although sometimes logs appear at a very low rate (i.e. ~1/2 log line(s) per second)
