### ISSUE TITLE
Charts do not load when switching host

### ISSUE THREAD

**Issue by Valdm** [influxdata/chronograf#4896]
On a host, when switching host thanks to the menu at the top left the graphics associated with the host does not reload. The graphics of the previous host remain, and they are empty.

I have a fix for it, i will make a pull request soon.

**System :** Centos 7.5
**Chronograf version :**  1.7.4 (git: 49fd1ec13ca31a79ed17580491ab66ea0506e0da)
**Web Browser :** Chrome 70.0.3538.110

https://github.com/Valdm/chronograf/commits/bugfix/host-graphs-display

**Comment by 121watts** [comment]
hey there @Valdm.  I'm unable to reproduce the issue on one of our production instances.  Is this the action / feature you're describing?

![kapture 2019-01-03 at 14 01 15](https://user-images.githubusercontent.com/7582765/50663945-44611180-0f60-11e9-9a44-2aeb05622c45.gif)

**Comment by Valdm** [comment]
Hey,

This only happens when your hosts don't have the same "apps". For example, when you switching from an host which have an postgresql app , and switching to another which don't have any postegresql metrics the graphs don't disappear. It works the other way too. 

Am I understandable enough?

Have a good day.
