### ISSUE TITLE
Can't adjust column width in Explorer

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4897]
Hi, when displaying a table in the Explorer I'm seeing this sort of thing:

![screenshot 2018-12-18 13 55 38](https://user-images.githubusercontent.com/501993/50158702-c26cb980-02cc-11e9-969b-c7428f76bb80.png)

My browser is Firefox. I can't seem to adjust the column width to see the full timestamp. Is this a regression of #1123?

If I untick "Lock First Column" I can then see the timestamps, but I still can't adjust the column width.

**Comment by AlirieGray** [comment]
I tried with Firefox 64.0 and was unable to replicate

**Comment by russorat** [comment]
@e-dard what OS are you using for this?

**Comment by russorat** [comment]
closing this for now. if this is still an issue in the latest chronograf, please reopen
