### ISSUE TITLE
Log Viewer results timestamp mangled in Firefox

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4899]
![screenshot 2018-12-18 14 16 54](https://user-images.githubusercontent.com/501993/50159910-d6fe8100-02cf-11e9-9fe2-bd857f24fe5d.png)

The timestamp column is a bit mangled in Firefox. I don't know if this is a dupe of #4876.

**Comment by OfTheDelmer** [comment]
@e-dard what version of Firefox an Chronograf are you using? Working with Firefox 63 and 64 I could not reproduce this timestamp mangling.

**Comment by russorat** [comment]
closing since we can't reproduce this. please reopen if you are still seeing this in the latest version.
