### ISSUE TITLE
Log Viewer results display keeps moving

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#4903]
Browser Firefox.

When viewing log results for some time in the past (let's say 8am yesterday), as the log view keeps finding more matching results in more recent time windows the results display keeps "shifting" down, such that I can't read any results.

If I scroll down to something of interest, it's pushed off my screen as more results keep coming in.

My expectation would be that the results display behaves more like a pager, in that I scan scroll around as much as I want even when new results are added to the head or tail of the results set. When I scroll to the head of the results _then_ I expect the scrolling to become automatic and follow new results as they're added. The same goes for when I scroll to the tail of results—I would expect the scrolling to be automatic so I can view new results coming in.

**Comment by OfTheDelmer** [comment]
@e-dard I'm able to reproduce this. Scrolling as data is loaded causes the row position to shift.

**Comment by e-dard** [comment]
don't close
