### ISSUE TITLE
Horizontal scrollbar does not work in query results [table view]

### ISSUE THREAD

**Issue by broofa** [influxdata/chronograf#4904]
This issue occurs on Windows and MacOS, all latest browser versions (except Edge).

In Chronograf, run a query that generates enough results to fill the results table view (see screenshot).  When the table is scrollable (vertically), the horizontal scrollbar partially hidden.  More important, **it doesn't respond to click events**, so scrolling horizontally does not work.

<img width="418" alt="screenshot at dec 19 14-40-01" src="https://user-images.githubusercontent.com/164050/50252487-07abec80-039c-11e9-80bb-9e1083f2f7c5.png">

**Comment by courtarro** [comment]
This should be reopened. It's still true in the latest version of Chronograf.

I'll note that, in Chrome on Linux, holding shift and using the mouse wheel scrolls horizontally. But that's a workaround.
