### ISSUE TITLE
Custom meta query template variables not working as expected...

### ISSUE THREAD

**Issue by robcowart** [influxdata/chronograf#4912]
The following was experienced on Chronograf 1.7.3 and 1.7.4. No other versions were tested.

The following attempt to [filter template variables with other variables](https://docs.influxdata.com/chronograf/v1.7/guides/dashboard-template-variables/#filtering-template-variables-with-other-template-variables) is not working as expected...

The first variable is configured as follows:
```
SHOW TAG VALUES ON "telegraf" FROM "IF-MIB::ifEntry" WITH KEY="host"
```
![image](https://user-images.githubusercontent.com/10326954/50403487-3dd3dc80-079f-11e9-8f8d-4ed6b3defc3d.png)

The second variable is a customer meta query as follows:
```
SHOW TAG VALUES ON "telegraf" FROM "IF-MIB::ifEntry" WITH KEY="ifName" WHERE "host"=:host:
```
![image](https://user-images.githubusercontent.com/10326954/50403546-afac2600-079f-11e9-99cc-94726d40221e.png)

This appears to work as the resulting drop-down lists behave as expected.
![image](https://user-images.githubusercontent.com/10326954/50403607-234e3300-07a0-11e9-81fb-75c3cb926423.png)
![image](https://user-images.githubusercontent.com/10326954/50403614-37923000-07a0-11e9-9af9-7e6bac7699ae.png)

A graph is then configured to use these variables in a query.
```
SELECT derivative(max("ifHCInOctets"),1s) * 8  AS "Ingress Traffic Rate" FROM "telegraf"."autogen"."IF-MIB::ifEntry" WHERE time > :dashboardTime: AND "host"=:host: AND "ifName"=:interface: GROUP BY time(:interval:) FILL(null)
```
When selecting _Show Template Variables_ the correct values appear to be submitted.
![image](https://user-images.githubusercontent.com/10326954/50403682-e2a2e980-07a0-11e9-8123-9e49b519ed59.png)

However the graph reports that no results are returned.
![image](https://user-images.githubusercontent.com/10326954/50403702-0ebe6a80-07a1-11e9-9325-aac03b767dcb.png)

If the values are statically entered into the query, the query works.
```
SELECT derivative(max("ifHCInOctets"),1s) * 8  AS "Ingress Traffic Rate" FROM "telegraf"."autogen"."IF-MIB::ifEntry" WHERE time > :dashboardTime: AND "host"='rt1' AND "ifName"='eth0' GROUP BY time(:interval:) FILL(null)
```
![image](https://user-images.githubusercontent.com/10326954/50403726-4f1de880-07a1-11e9-9206-3b316608810a.png)

All indications are that the variables should work as configured, however no results are returned.

**Comment by russorat** [comment]
@robcowart i believe it has something to do with the quoting in the query. For template variables, custom meta query values are not automatically quoted, which might be causing this issue. It's tough to know since the "show template variables" command doesn't seem to be showing them properly.

**Comment by hoorayimhelping** [comment]
Reopening after a report in [our community Slack](https://www.influxdata.com/slack)

**Comment by robcowart** [comment]
@hoorayimhelping you should see my comments in the Slack thread.

**Comment by russorat** [comment]
I have filed this issue for the docs team to clarify: https://github.com/influxdata/docs.influxdata.com/issues/2643

**Comment by russorat** [comment]
I'm closing this issue for now. please track the progress in the docs issue https://github.com/influxdata/docs.influxdata.com/issues/2643
