### ISSUE TITLE
Version not updated for tag 1.7.5

### ISSUE THREAD

**Issue by hydrandt** [influxdata/chronograf#4913]
The release under tag 1.7.5 does not have the version number increased in the code, so from the UI it still seems like 1.7.4. Running `chronograf -v` produces 1.7.5 properly. Quite confusing :-)

I'll be happy to make a PR if you tell me the proper way to bump the version.

**Comment by russorat** [comment]
@hydrandt thanks for reporting. we plan to fix this in the next minor release which should be out in the next week.
