### ISSUE TITLE
Upgrading Chronograf from 1.3.10 to 1.7.5, facing issues

### ISSUE THREAD

**Issue by disha1104** [influxdata/chronograf#4915]
Hi,
I am trying to upgrade my entire TICK stack from older version to newer one. As a result of it, I am upgrading chronograf from 1.3.10 to 1.7.5 version, but I am facing issues. 
It is related to this: https://github.com/influxdata/chronograf/issues/2650
Since all my dashboards have only "**GROUP BY :interval**" in the query, hence it is giving me an **error "only tag and time dimensions allowed"**, is there a way to fix it??
Also, can someone list down the major changes/bug fixes in this version change that I need to take care of?

**Comment by russorat** [comment]
@disha1104 when you start the latest chronograf, it should migrate your existing queries to the new`GROUP BY time(:interval:)` format instead of the older style. it also creates a backup of the original db in a `backups` folder as well.

it would seem this process isn't running correctly. Is there anything special you did as part of the upgrade that may have blocked this process from running?

**Comment by disha1104** [comment]
Hi @russorat , nothing different, I have the TICK stack running, and I have just upgraded all the versions and deployed on Kubernetes.
Any dashboards created with newer versions is working correctly, but the older ones show no results.
Is there something I am missing?

**Comment by russorat** [comment]
`GROUP BY :interval:` will need to be changed to `GROUP BY time(:interval:)` for all your queries. we will investigate why that wasn't run automatically when starting the latest version.

**Comment by disha1104** [comment]
Yes, that I understood, do you have any documentation wrt to steps that needs to be followed in the upgrade process.
As per my understanding, it should be just a image tag change, correct me if I am wrong?
Does this have any dependency on the versions of Kapacitor/Telegraf/Influx?

**Comment by russorat** [comment]
@disha1104 everything should happen behind the scenes when you start the new version of chronograf. we will need to investigate why that didn't happen. it could be related to running in k8s but it's just a guess at this point.

**Comment by disha1104** [comment]
This seems to be working, I think there was some issue from our side.
But I have one more issue now, since I am upgrading from 1.3.10 to 1.7.5, there is RBAC introduced in chronograf after 1.4, hence, I am getting access denied, as default it is taking is member. Is there a way to change this config?

**Comment by russorat** [comment]
@disha1104 there shouldn't be any auth in chronograf unless you explicitly set those options via env vars or command line options. If you have, the default is for the first user that logs in to be a super admin. see https://docs.influxdata.com/chronograf/v1.7/administration/managing-security for more details.

**Comment by disha1104** [comment]
I referred to this link already.
So, while using 1.3.10.0 version, I am using Google Auth2.0, now when I upgraded it to 1.7.5, it is asking for authentication again and does not allow me to login saying I have member permissions.
Is there any way to create users from CLI for chronograf which have Google Auth2.0 enabled?

**Comment by russorat** [comment]
@disha1104 there is no version of chronograf that is 1.3.10, and auth wasn't introduced until 1.4. So i'm very confused about your setup. there is also no CLI for chronograf. Could you describe your setup between influxdb, chronograf, and google accurately with the proper version numbers? The more details, the better (with scrrenshots and config values) so that we can pinpoint where the issue is.

**Comment by disha1104** [comment]
@russorat sorry for the confusion. Let me share more details with you.
Service               Previous version                Upgraded version
Chronograf           1.3.10.0                              1.7.5
Kapacitor               1.4.1                                   1.5.2
Influx                       1.5.1                                  1.7.2
Telegraf                  1.5.3                                  1.9.1

In my previous chronograf version, I am using google authentication for my organisation like this: https://docs.influxdata.com/chronograf/v1.3/administration/security-best-practices/#google

Now, since I am upgrading to 1.7.5 version, and there is RBAC enabled, on authenticating with google, it says I can't access as I am a "member".
So, I wanted to know, if there is a way to change to change this default member settings? Also let me know if you need any more details.

**Comment by disha1104** [comment]
@russorat Any update on this? This is a blocker for me.

**Comment by russorat** [comment]
@disha1104 sorry for the delay. we won't have time to investigate this until after our next release.

if this is a critical blocker, a workaround might be to disable auth on the upgraded version temporarily, export your dashboards and anything else that needs to migrate, then start with a new bolt.db with auth enabled and import those dashboards again.

**Comment by disha1104** [comment]
Hi @russorat , no worries, so as a workaround, I didn't want to disable auth, but I somehow edited my existing "chronograf-v1.db" using some tool and made the default organisation change to "editor" instead of "member". So as of now, it is atleast working and I can login into updated version as editor with googleauth. But I am not able to create any admin/superadmin user.
Is there any workaround to create the same? Some API request or some setting?

**Comment by disha1104** [comment]
@russorat any update on this?

**Comment by russorat** [comment]
@disha1104 sorry no update. I have provided you a workaround if this is a critical blocker.

**Comment by disha1104** [comment]
@russorat okay let me try that way. So I have multiple dashboards, is there an option to import and export all dashboards at once? From Chronograf UI, I can just see an option to do that one by one.

**Comment by disha1104** [comment]
@russorat it worked, I did the installation from scratch with a new bolt.db and imported/exported all dashboards using a python script.
Thanks a lot.
