### ISSUE TITLE
Layouts should only be displayed when the measurement is present.

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#494]

**Comment by willpiers** [comment]
Sounds like we need to run a 
```javascript
`show series from /${measurements}/`
```
on the HostPage and filter out some cells from the layout(s)

**Comment by goller** [comment]
@willpiers does it help that a show series query has a where clause?
```[WHERE <tag_key> <operator> [ '<tag_value>' | <regular_expression>]]```
from https://docs.influxdata.com/influxdb/v1.1/query_language/schema_exploration/#show-series

**Comment by goller** [comment]
Here is another way: ` SHOW MEASUREMENTS WHERE "host" = 'ip-172-31-6-247'`

**Comment by willpiers** [comment]
Yeah @goller that actually is a better way to do it.
