### ISSUE TITLE
[data explorer] Don't query raw data by default

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/chronograf#502]
Querying for raw data (no function being applied to results) by default can severely impact InfluxDB and browser performance. For example, instead of having the default query for choosing `usage_user` being:

```
SELECT usage_user FROM telegraf."default".cpu WHERE time > now() - 15m
```

It should be:

```
SELECT mean(usage_user) FROM telegraf."default".cpu WHERE time > now() - 15m GROUP BY time(10s)
```

And the group by interval should be something either configurable, or automatically set depending on the width of the browser window.

For reference:

```
# RAW (returns 131,494 points, which is more than can even be rendered)
$ time influx -execute 'select usage_user from cpu where time > now() - 15m' -database telegraf 1>/dev/null

real	0m1.846s
user	0m0.984s
sys	0m0.122s

# AGGREGATE (returns 95 points)
$ time influx -execute 'select mean(usage_user) from cpu where time > now() - 15m group by time(10s)' -database telegraf 1>/dev/null

real	0m0.417s
user	0m0.006s
sys	0m0.000s

```

Grafana requires that an aggregation function is applied to every query; it would be great if Chronograf did something similar, since it can be a foot-gun if querying for large amounts of data (especially when paired with the auto-refresh).

**Comment by 121watts** [comment]
This should be done now :)
