### ISSUE TITLE
Chronograf doesn't authenticate with keycloak as generic provider

### ISSUE THREAD

**Issue by makrste** [influxdata/chronograf#5031]
Hi,

I am trying to secure the chronograf instance with keycloak.

I followed the published chronograf tutorial for “generic”: https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/#configuring-generic-authentication.

The keycloak client seems to be configured correctly according to the keycloak log which states that the client has been authenticated. I was able to confirm this by debugging keycloak as follows:
After clicking on the “Login with Generic” button in chronograf, I can see that the request comes through once, the code is generated for the chronograf client, BUT then another request comes in for the same client and keycloak complains that there already exists one code, which in turn invalidates the previous one.

When the token is validated in [chronograf: mux.go], the code to token step of the oauth fails because the code was already generated and the error states invalid grant.

Does anyone have some experience with this or has already managed to secure an instance with keycloak?  I will be happy to assist and debug this but I have no experience with Go, so please include some tips on how to do it.

Thanks in advance!

**Comment by russorat** [comment]
@makrste we haven't tested the generic oauth with keycloak. to help in debugging, could you add your configs for chronograf and keycloak and link to the instructions you followed to ensure keycloak was set up properly?

**Comment by macckoo** [comment]
I have managed to solve this, I had the `--useidtoken` config enabled and `openid` as scope. Keycloak therefore generated an id token but after debugging chronograf/mux.go I concluded that there is where all hell breaks loose, it seems the system starts to panic and doesn't process the id token: 

level=error msg="http: panic serving [::1]:39996: runtime error: index out of range"
level=error msg="goroutine 16 [running]:"
level=error msg="net/http.(*conn).serve.func1(0xc420269220)"
level=error msg="\t/usr/local/go/src/net/http/server.go:1726 +0xd0"
level=error msg="panic(0xe40bc0, 0x1c8dd40)"
level=error msg="\t/usr/local/go/src/runtime/panic.go:505 +0x229"
level=error msg="github.com/influxdata/chronograf/oauth2.(*JWT).KeyFuncRS256(0xc4205c2d50, 0xc420432a50, 0x0, 0x0, 0x0, 0x0)"
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/oauth2/jwt.go:148 +0x7fd"
level=error msg="github.com/influxdata/chronograf/oauth2.(*JWT).KeyFunc(0xc4205c2d50, 0xc420432a50, 0xc4202c4660, 0x5, 0xc4200de7e8, 0x
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/oauth2/jwt.go:84 +0xe3"
level=error msg="github.com/influxdata/chronograf/oauth2.(*JWT).KeyFunc-fm(0xc420432a50, 0x5, 0x1099520, 0xc42013e280, 0xc4202f7708)"
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/oauth2/jwt.go:74 +0x34"
level=error msg="github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go.(*Parser).ParseWithClaims(0xc42053b6f0, 0xc4204c76
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go/parser.go:97 +0x6dd"
level=error msg="github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go.(*Parser).Parse(0xc42053b6f0, 0xc4204c7680, 0x436,
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go/parser.go:20 +0x67"
level=error msg="github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go.Parse(0xc4204c7680, 0x436, 0xc42053b758, 0xc42053b
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/vendor/github.com/dgrijalva/jwt-go/token.go:89 +0x65"
level=error msg="github.com/influxdata/chronograf/oauth2.(*JWT).GetClaims(0xc4205c2d50, 0xc4204c7680, 0x436, 0xdde900, 0xc4203ae850, 0x
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/oauth2/jwt.go:213 +0x72"
level=error msg="github.com/influxdata/chronograf/oauth2.(*AuthMux).Callback.func1(0x10993a0, 0xc4203ae390, 0xc4205ce400)"
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/oauth2/mux.go:138 +0x108a"
level=error msg="net/http.HandlerFunc.ServeHTTP(0xc4205923a0, 0x10993a0, 0xc4203ae390, 0xc4205ce400)"
level=error msg="\t/usr/local/go/src/net/http/server.go:1947 +0x44"
level=error msg="github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter.(*Router).ServeHTTP(0xc42045ae00, 0x10993a0, 0xc420
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/vendor/github.com/bouk/httprouter/router.go:308 +0x48c"
level=error msg="github.com/influxdata/chronograf/server.(*MountableRouter).ServeHTTP(0xc4203f1380, 0x10993a0, 0xc4203ae390, 0xc4204585
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/server/mountable_router.go:58 +0x52"
level=error msg="github.com/influxdata/chronograf/server.AuthAPI.func2(0x10993a0, 0xc4203ae390, 0xc420458500)"
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/server/mux.go:427 +0x123"
level=error msg="net/http.HandlerFunc.ServeHTTP(0xc42045b200, 0x10993a0, 0xc4203ae390, 0xc420458500)"
 level=error msg="\t/usr/local/go/src/net/http/server.go:1947 +0x44"
level=error msg="github.com/influxdata/chronograf/server.FlushingHandler.func1(0x10993e0, 0xc42039c900, 0xc420458500)"
level=error msg="\t/root/go/src/github.com/influxdata/chronograf/server/prefixing_redirector.go:32 +0x96"
>msg="net/http.HandlerFunc.ServeHTTP(0xc4203f1640, 0x10993e0, 0xc42039c900, 0xc420458500)"
>msg="\t/usr/local/go/src/net/http/server.go:1947 +0x44"
>msg="github.com/influxdata/chronograf/server.Logger.func1(0x109aaa0, 0xc420408460, 0xc420458500)"
>msg="\t/root/go/src/github.com/influxdata/chronograf/server/logger.go:50 +0x34a"
>msg="net/http.HandlerFunc.ServeHTTP(0xc4205c2f60, 0x109aaa0, 0xc420408460, 0xc420458500)"
>msg="\t/usr/local/go/src/net/http/server.go:1947 +0x44"
>msg="github.com/influxdata/chronograf/server.Version.func1(0x109aaa0, 0xc420408460, 0xc420458500)"
>msg="\t/root/go/src/github.com/influxdata/chronograf/server/version.go:11 +0xc2"
> msg="net/http.HandlerFunc.ServeHTTP(0xc4205c2f90, 0x109aaa0, 0xc420408460, 0xc420458500)"
> msg="\t/usr/local/go/src/net/http/server.go:1947 +0x44"
> msg="net/http.serverHandler.ServeHTTP(0xc420265380, 0x109aaa0, 0xc420408460, 0xc420458500)"
> msg="\t/usr/local/go/src/net/http/server.go:2694 +0xbc"
> msg="net/http.(*conn).serve(0xc420269220, 0x109bf20, 0xc420374500)"
> msg="\t/usr/local/go/src/net/http/server.go:1830 +0x651"
> msg="created by net/http.(*Server).Serve"
> msg="\t/usr/local/go/src/net/http/server.go:2795 +0x27b"
> msg="Unable to exchange code for token oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",



 For future references:

----Chronograf Config----
   # The links below can be found under [HOST]/auth/realms/gp/.well-known/openid-configuration.
   # AUTHENTICATION #
   GENERIC_CLIENT_ID="[kEYCLOAK-CLIENT]"
   GENERIC_CLIENT_SECRET="[KEYCLOAK-CLIENT-PASSWORD]"
   GENERIC_AUTH_URL="[HOST]/auth/realms/gp/protocol/openid-connect/auth"
   GENERIC_TOKEN_URL="[HOST]/auth/realms/gp/protocol/openid-connect/token"
   TOKEN_SECRET="[RANDOM-STRING]"
   
   GENERIC_API_URL="https://[HOST]/auth/realms/gp/protocol/openid-connect/userinfo"
   JWKS_URL="https://[HOST]/auth/realms/gp/protocol/openid-connect/certs"
   PUBLIC_URL="[HOST]"
   CUSTOM_LINKS="SSO logout: `http://auth-server/auth/realms/{realm-name}/protocol/openid-connect/logout"
----Chronograf Config----

----Keycloak Config----
A new client in the primary realm, with a "[HOST]/oauth/*" `valid redirect URI` and `standard flow enabled`
----Keycloak Config----

**Comment by mintalicious** [comment]
Thx to @makrste for giving me an idea of how to configure Chronograf 1.10.0 with Keycloak 22.0.1 - I've got it working now. Here is my config which comes from a docker-compose.yml since I have it running in a Docker container:

```
      - GENERIC_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - GENERIC_AUTH_URL=${KEYCLOAK_URL}/realms/master/protocol/openid-connect/auth
      - GENERIC_TOKEN_URL=${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token
      - GENERIC_SCOPES=openid,profile,email
      - TOKEN_SECRET=${CHRONOGRAF_TOKEN_SECRET}

      - GENERIC_API_URL=${KEYCLOAK_URL}/realms/master/protocol/openid-connect/userinfo
      - JWKS_URL=${KEYCLOAK_URL}/realms/master/protocol/openid-connect/certs
      - PUBLIC_URL=${CHRONOGRAF_URL}
      - "CUSTOM_LINKS=Keycloak Logout:${KEYCLOAK_URL}/realms/master/protocol/openid-connect/logout"
```

And the .env file:

```
CHRONOGRAF_URL="https://<Chronograf host>"
CHRONOGRAF_TOKEN_SECRET="<random string>"
KEYCLOAK_URL="https://<Keycloak host>"
KEYCLOAK_CLIENT_ID="<Keycloak client id>"
KEYCLOAK_CLIENT_SECRET="<Keycloak client secret>"
```

I generated a token secret with `openssl rand -base64 256 | tr -d '\n'` as of the official Chronograf documentation.

For some reason I could not get access when I set `GENERIC_NAME=Keycloak` for labelling the login button in Chronograf.
This also sets the provider in Chronograf to `Keycloak` and not to generic, which prevents the user from getting access to the Chronograf UI and instead shows up a message like `Contact your admin for access.` after getting redirected from Keycloak.
I had to get back to the generic provider by again omitting the `GENERIC_NAME`, logging in and giving the second User with the same email address in Chronograf admin role.

![grafik](https://github.com/influxdata/chronograf/assets/10205162/ec443aef-6c00-42d6-9401-cf7b0a88690c)

and also giving me the SuperAdmin role in the tab `All Users`.
