### ISSUE TITLE
Support changing the pagerduty2 routing key in the alert rule builder 

### ISSUE THREAD

**Issue by sciurus** [influxdata/chronograf#5038]
The [pagerduty2 event handler](https://docs.influxdata.com/kapacitor/v1.5/event_handlers/pagerduty/v2/) can be used via the alert rule builder if you use the handler's default routing key. However, if you need to customize the routing key for your alert you have to edit the tickscript. This means you lose all the nice features of the alert rule builder.

Some other event handlers let you customize their destination without dropping down to tickscript. The email handler, for example, lets you configure the destination email address. It would be helpful if the pagerduty2 event handler let you customize the pagerduty2 routing key in a similar way.

Ideally it would be possible in the pagerduty2 event handler config to define a list of routing keys and assign identifiers to them. Then in the alert rule builder, it could be possible to choose from one of those identifiers.

However, simply exposing a text field in the alert rule builder where someone could type a routing key would be a huge improvement.

**Comment by nevins-b** [comment]
We ran into this recently as well. Even if there is now routing key set in the configuration we aren't able to supply one as part of alert creation.
