### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by LeaBloodForged** [influxdata/chronograf#5048]
Hi,
I have a question for you. 
Is there other languages than English available? 
Some people i work with want the full UI (buttons, ....) in French but i found nothing related to that.
Thank you for reading and waiting for your answer.
Wish you the best.

**Comment by russorat** [comment]
@LeaBloodForged thank you for your issue. we currently have no plans to offer multi-language support in the 1.x line.

**Comment by LeaBloodForged** [comment]
@russorat 
Hi,
Thank you for the reply. Is there any chance that it'll be a feature for 2.x line?
