### ISSUE TITLE
Creating template variables from tag values does not work

### ISSUE THREAD

**Issue by Omaiyma** [influxdata/chronograf#5049]
Unable to create a template variable using `SHOW TAG VALUES ON telegraf FROM spark_streaming WITH KEY application_name` 

The same works when we select TAG VALUES.

The reason I am using Create Template Variable is, I need to use 
`SHOW TAG VALUES ON telegraf FROM :sparkStreaming: WITH KEY application_name` 

![image](https://user-images.githubusercontent.com/46820356/51396590-5d93c180-1b0d-11e9-9f21-ef489a548cb9.png)

**Comment by russorat** [comment]
@Omaiyma my guess is that there is some sort of string quoting issue happening here. You may need to add single quotes around `spark_streaming` and `application_name` in this query.

**Comment by russorat** [comment]
i have added this issue for our docs team: https://github.com/influxdata/docs.influxdata.com/issues/2133
