### ISSUE TITLE
Data Explorer - Flux Script Wizard - with influxdb-data_1.7.3-c1.7.3_amd64.deb leads to browser then system crash

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5052]
build: **Nightly Build**
build-time: **201901162124**
browser: detected in Chrome 71, Opera, Firefox
```
$ chronograf --version
2019/01/22 14:10:15 Chronograf 201901162124~nightly (git: 17f5ec35abcfbb3f81073f47b596edf265c7f5bc)
```
OS: **Ubuntu 16.04**

*Use Case*

1. Setup a test enterprise cluster using the script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh)
1. Create an initial connection to node 172.17.0.2
1. Open Data Explorer
1. Switch to the Flux tab
1. Open the Script Wizard
1. Select a set of values - for example 
   * telegraf/autogen
   * mem
   * {available, used}
   * function mean()
   * (also checked typical telegraf, cpu, usage_idle, mean())
1. Click "insert script" 

In the first second or two the browser becomes unresponsive
In a few seconds the OS becomes unresponsive.  No mouse response, no Alt + F4, no CTRL+ALT+DEL.  The laptop has to be switched off then on again manually. 

*Expected Behavior*

That the web application should not cause the containing system app or OS to freeze or to become unresponsive. 

*Screenshots*

![flux_os_crash01](https://user-images.githubusercontent.com/25881301/51538744-5f81bb80-1e52-11e9-8fb1-ecc32ca74709.png)
![flux_os_crash02](https://user-images.githubusercontent.com/25881301/51538746-601a5200-1e52-11e9-91ad-32817edf1448.png)
![flux_os_crash03](https://user-images.githubusercontent.com/25881301/51538747-601a5200-1e52-11e9-94bc-c1115751b117.png)

**Comment by karel-rehor** [comment]
Regression/Selenium note: I came across this when investigating a failure of this test case.  Selenium runs fast enough, that this issue does not seem to appear as a hangup, only as an inconsistency in the generated script.  However, when checking this manually, it leads to a system hang.

**Comment by karel-rehor** [comment]
Double checked functionality of building script with schema e.g. bucket[telegraf.autogen]->measurements->cpu->usage_idle + Add Filter.  And then "Run Script".  This works OK.  Nice graph.  Nothing hangs.

**Comment by bthesorceror** [comment]
Likely related to #5070
