### ISSUE TITLE
High Availability Chronograf

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5062]
Allow for configuration option so that all Chronograf state (dashboards, users/orgs/permissions, data source connections, etc.) is persisted in a highly available mechanism.  This should allow for multiple instances of Chronograf to be deployed which each connect to the same persistent store.

The result is that users can configure a load balancer in front of the Chronograf instances and ensure that the UI is not a single point of failure.

**Comment by russorat** [comment]
+1

**Comment by timhallinflux** [comment]
https://github.com/Esity

**Comment by Esity** [comment]
Do we have any updates on this one?

**Comment by timhallinflux** [comment]
Still in plan for 1.8 -- planned for Q4.

**Comment by Esity** [comment]
Do we have any updates on this @timhallinflux 
Also commenting so this doesn't go stale

**Comment by russorat** [comment]
hi @Esity , still scheduled for 1.8 chronograf.

**Comment by Esity** [comment]
Do we have a more defined time line for 1.8?

**Comment by timhallinflux** [comment]
This has moved out to 1Q2020 as we are holding 1.8 InfluxDB until we have a couple of remaining items addressed for a production ready version of Flux.  But, we still plan to do this as part of the corresponding 1.8 Chronograf release.
