### ISSUE TITLE
Issue parsing query with template variables

### ISSUE THREAD

**Issue by afausti** [influxdata/chronograf#5066]
I am using Chronograf 1.7.0 and it looks like there's a bug in how queries with template variables are parsed.

Consider the following query:

```SELECT "pipe_tasks.ProcessCcdTime" FROM "squash-prod"."autogen"."pipe_tasks" WHERE time > :dashboardTime: AND "ccdnum"='56' AND "visit"='411371'```

It is syntactically correct and returns data.

Now I want to replace `ccdnum` and `visit` values with template variables. I have successfully created the  `:ccdnum:` and `:visit:` template variables from tag values in my dashboard. 

I would expect the following query to work: 

```SELECT "pipe_tasks.ProcessCcdTime" FROM "squash-prod"."autogen"."pipe_tasks" WHERE time > :dashboardTime: AND "ccdnum"=:ccd: AND "visit"=:visit:```

Chronograf says that the query is syntactically correct but does not return any value.

NOTE: when I use the "Show Template Values" button, the template variables are correctly replaced by the selected values. 

Then I tried single quoting the template variables like this:

```SELECT "pipe_tasks.ProcessCcdTime" FROM "squash-prod"."autogen"."pipe_tasks" WHERE time > :dashboardTime: AND "ccdnum"=':ccd:' AND "visit"=':visit:'```

The result is a parsing error saying:
```Error parsing query: found 411371, expected ; at line 1, char 245.```

NOTE:  when I use the "Show Template Values" button, the template variables are not replaced by the selected values in this case.

Strangely the following query seems to work:

```SELECT "pipe_tasks.ProcessCcdTime" FROM "squash-prod"."autogen"."pipe_tasks" WHERE time > :dashboardTime: AND "ccdnum"=':ccd:' AND "visit"=:visit:```

which is non-intuitive. Why should I single quote only one of the template variables to make it work?

**Comment by russorat** [comment]
@afausti i agree that it is confusing. template variables that are created from a predefined query in the UI do not need to be single quoted. template variables that are manual entered (csv, map, custom query) need to be single quoted because we can't make assumptions about the data being returned.

i have created https://github.com/influxdata/docs.influxdata.com/issues/2133 to update the docs.

**Comment by afausti** [comment]
@russorat thanks for the answer but that does not solve the issue I am reporting.

Note that if I single quote the template variables I've created it doesn't work:

`SELECT "pipe_tasks.ProcessCcdTime" FROM "squash-prod"."autogen"."pipe_tasks" WHERE time > :dashboardTime: AND "ccdnum"=':ccd:' AND "visit"=':visit:'`

The result is a parsing error saying:
`Error parsing query: found 411371, expected ; at line 1, char 245.`

**Comment by afausti** [comment]
@russorat you are right, in my previous query `:ccd:` is defined by a **custom meta query** while `:visit:` is defined by a **meta query**.

I didn't appreciate the difference between both until now. I think having a note in the documentation saying  "Note that template variables defined by custom meta queries must be single quoted, they are different from template variables defined by meta queries." will help to point the difference. 

Thank you!

**Comment by afausti** [comment]
@russorat another small thing, is there a reason why `:ccd:`  is expanded to 56 and not '56'? the result of the query is a tag value which is a string by construction, right?

**Comment by russorat** [comment]
@afausti it has to do with the fact that `:ccd:` is a custom meta query, which means we show the raw value returned, no quoting.
