### ISSUE TITLE
[1.7.5] centos7 systemd basepath config.  document is wrong

### ISSUE THREAD

**Issue by reedzhao** [influxdata/chronograf#5072]
So, I followed the instructions here:
https://docs.influxdata.com/chronograf/v1.7/administration/config-options/

It throws a straight error.
```
# systemctl start chronograf --basepath=/chronograf

systemctl: unrecognized option '--basepath=/chronograf'
```

Setting `BASE_PATH` in `/usr/lib/systemd/system/chronograf.service` does not work as well.
```
[Service]
...
Environment="BASE_PATH=/chronograf"
Environment="BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"
Environment="CANNED_PATH=/usr/share/chronograf/canned"
Environment="PROTOBOARDS_PATH=/usr/share/chronograf/protoboards"
EnvironmentFile=-/etc/default/chronograf
ExecStart=/usr/bin/chronograf $CHRONOGRAF_OPTS
...
```

Is there a canonical explanation of how to config basepath?

**Comment by russorat** [comment]
@reedzhao does manually running `chronograf --basepath=/chronograf` work on your system without `systemctl start`?

**Comment by reedzhao** [comment]
> @reedzhao does manually running `chronograf --basepath=/chronograf` work on your system without `systemctl start`?

Yes, it works.  I can visit chronograf on  `domain.com:8888/chronograf`
`chronograf --basepath=/chronograf`

**Comment by fredlemieux** [comment]
I have this problem too.  I've been trying to view Chronograf as a separate route (location /chronograf) using nginx.  It works if I run `chronograf --basepath=/chronograf`

But not run if I chronograf as a service 'sudo service chronograf start'
or if I set $BASE_PATH = /chronograf
or if edit the config file in `/etc/defaults/chronograf` using the settings above or in the settings in this thread: https://github.com/influxdata/chronograf/issues/845

It's really frustrating, I'm fairly new to all this so my apologies if I'm totally missing something.
