### ISSUE TITLE
 Chronograf (1.7.7) o is not a function. (In 'o(i.state.kapacitor)', 'o' is undefined)

### ISSUE THREAD

**Issue by mitch3ls** [influxdata/chronograf#5074]
What browser are you using (name and version)?

Safari 12.0.3 (14606.4.5)

What operating system are you using?

MacOS 10.14.3

Please describe what you were trying to do when you encountered this error:

I was trying to connect to Kapacitor after selecting the Docker dashboard preset in the initial configuration dialog. I am using [this](https://gist.github.com/cdelaitre/85949d8b697359a319e30a678e23d8bd) docker-compose stack 

```
http://localhost:8888/src.216c1ae9.js:4691:3999
pl@http://localhost:8888/src.216c1ae9.js:716:45576
dl@http://localhost:8888/src.216c1ae9.js:716:45324
xi@http://localhost:8888/src.216c1ae9.js:716:84394
wi@http://localhost:8888/src.216c1ae9.js:716:79947
ki@http://localhost:8888/src.216c1ae9.js:716:79563
Le@http://localhost:8888/src.216c1ae9.js:716:90855
We@http://localhost:8888/src.216c1ae9.js:716:10446
Fn@http://localhost:8888/src.216c1ae9.js:716:30802
Si@http://localhost:8888/src.216c1ae9.js:716:85579
Rn@http://localhost:8888/src.216c1ae9.js:716:30545
Rn@[native code]
```

**Comment by russorat** [comment]
fixed by https://github.com/influxdata/chronograf/issues/5060
