### ISSUE TITLE
On restart always have "Current source does not have an associated Kapacitor Instance"

### ISSUE THREAD

**Issue by imrehg** [influxdata/chronograf#5081]
Using Chronograf 1.7.5, and setting up Kapacitor. I'm passing these env vars:
```
INFLUXDB_URL=http://influxdb:8086
KAPACITOR_URL=http://kapacitor:9092
```
On each restart, I'm getting "Current source does not have an associated Kapacitor Instance"

![screenshot_2019-02-13_12-10-10](https://user-images.githubusercontent.com/38863/52711388-98acd780-2f89-11e9-8bf6-7d6230fa3a55.png)

When I navigate to the source management, it seems like there's a Kapacitor already set up like this:

![screenshot_2019-02-13_12-09-55](https://user-images.githubusercontent.com/38863/52711429-afebc500-2f89-11e9-8d5b-f646a5daf85f.png)

But in fact that didn't take effect, I have to go to the dropdown, and reselect that Kapacitor instance, even if that looks like selected in the first place. After this, Chronograf shows my alerts and all

![screenshot_2019-02-13_12-10-45](https://user-images.githubusercontent.com/38863/52711479-d0b41a80-2f89-11e9-878b-e45712688872.png)

Because of this, on every Chronograf restart I have to manually intervene, even if it looks like what I'm doing is a non-operation, since I enable the setting that already appears enabled.

Any ideas about this, am I missing anything?

**Comment by OfTheDelmer** [comment]
This should have been partially or fully resolved by changes made in https://github.com/influxdata/chronograf/issues/5061

It corrected an issue where the Tasks page was not finding a selected Kapacitor and incorrectly displaying an empty page.
