### ISSUE TITLE
InfluxDB2 - Data Explorer - Percentile function does not take parameter 'Columns' 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5085]
Build **Nightly**
Build time **2019-02-14T09:16:51Z**
```
ts=2019-02-14T15:25:37.522458Z lvl=info msg="Welcome to InfluxDB" log_id=0Dc9eVSW000 version=nightly commit=dcfab169c build_date=2019-02-14T09:16:51Z
```
*Use Case*

1. After onboarding and generating data, open D-Explorer and click on the *Script Editor* button.

2. Start with a simple query like the following...
```
from(bucket: "test-data")
  |> range(start: timeRangeStart)
  |> filter(fn: (r) => r._measurement == "air_quality")
  |> filter(fn: (r) => r._field == "NO2")
```

3. Click the function 'percentile' to add it to the query.  The following statement is generated 

```
 |> percentile(columns: ["_value"], percentile: 0.99, method: "estimate_tdigest", compression: 1000)
```
4. Click submit. 

An error message appears. 

```
Error: failed to compile query: type error 9:6-9:102: function does not take a parameter "columns"
```
*Expected Behaviour*

Function statements generated from the UI should match the API and vice versa.  Any required parameters should have valid values, or should be highlighted, indicating the user needs to take action. 

*Screenshot*
![percentilefunctionnoparameter](https://user-images.githubusercontent.com/25881301/52798309-f881ac00-3077-11e9-8e73-02e18241d024.png)

**Comment by ischolten** [comment]
This seems to be an issue with the flux language. related flux issue: https://github.com/influxdata/flux/issues/1063
