### ISSUE TITLE
Support multiple axes per chart

### ISSUE THREAD

**Issue by andig** [influxdata/chronograf#5087]
Currently chronograf only supports a single query per graph (opposed to e.g. grafana). It would be great if chronograf allowed multiple queries per graph.

**Comment by andig** [comment]
This cab already be done using flux but would benefit from multiple axis, including right axes.

**Comment by russorat** [comment]
@andig you can add as many influxql queries as you like using tabs. we have limited axis configs but is there something else that is missing?

**Comment by andig** [comment]
Didn‘t even realize the tabs as resulting in a single chart. That makes perfect sense, so only axes would be missing afaiks.
