### ISSUE TITLE
Influxdb2 - Data Explorer Flux - Suggested join methods {left, right, cross.... } not implemented

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5089]
Build **nightly**
Buildtime **2019-02-18T07:08:51**
```
ts=2019-02-18T12:06:28.681294Z lvl=info msg="Welcome to InfluxDB" log_id=0Dh7qxIG000 version=nightly commit=cbef811c6 build_date=2019-02-18T07:08:51Z
```
*Use Case*

1. Create test data
2. Open Data explorer > Script editor 
3. Create a flux script using join 

```javascript
Smichov = from(bucket: "test-data")
  |> range(start: -4h)
  |> filter(fn: (r) => r._measurement == "air_quality")
  |> filter(fn: (r) => r.location == "Smichov") 
  |> filter(fn: (r) => r._field == "SO2")
  |> drop(columns: ["gps", "label", "location", "unitId" ])
  
Hlavni = from(bucket: "test-data")
  |> range(start: -4h)
  |> filter(fn: (r) => r._measurement == "air_quality")
  |> filter(fn: (r) => r.location == "Praha hlavni") 
  |> filter(fn: (r) => r._field == "SO2")
  |> drop(columns: ["gps", "label", "location", "unitId" ])
  
  
join(tables: {key1: Smichov, key2: Hlavni}, on: ["city", "_field", "_measurement", "_start", "_stop", "_time" ], method: "inner")
```
Note that when adding the `join` function the tooltip document suggests other types of joins are possible (e.g. left, right, cross, full)

4. Change the join method from "inner" to "left" and click *submit*.

An error message indicates that "left is not a valid join type".

*Question*

I realize that this is pre-beta.  Is there any idea of when the other join methods will be supported?  And, if they are not supported at next release. shouldn't the tooltip document reflect currently supported possibilities? 

*Screenshot*

![fluxdejoin01](https://user-images.githubusercontent.com/25881301/52956807-80292c80-3390-11e9-99b3-db365f448e0e.png)
![fluxdejoin02](https://user-images.githubusercontent.com/25881301/52956808-80292c80-3390-11e9-9913-d6c5be085763.png)
![fluxdejoin03](https://user-images.githubusercontent.com/25881301/52956809-80292c80-3390-11e9-94ef-b783c33042ad.png)

**Comment by russorat** [comment]
please follow this issue to see when other join types will be added: https://github.com/influxdata/flux/issues/84
