### ISSUE TITLE
Alert rule validation does not understand if/else constructs

### ISSUE THREAD

**Issue by tanji** [influxdata/chronograf#5090]
Since the introduction of https://github.com/influxdata/chronograf/pull/4479, we are unable to validate a previously working alert message template containing the following:

```{{ if eq .Level "OK" }}alert is under threshold{{ else }}alert is over threshold{{ end }}```

This is a valid template construct as documented in https://golang.org/pkg/text/template/ and it works as intended, therefore it should be accepted as valid.

**Comment by ebb-tide** [comment]
fix validation logic for this case.
