### ISSUE TITLE
Add basepatb for chronograf ubuntu

### ISSUE THREAD

**Issue by amitdhawan** [influxdata/chronograf#5091]
I'm not able to launch chronograf from https://localhost:8888/chronograf after setting the export BASE_PATH=/chronograf. Please help

**Comment by russorat** [comment]
@amitdhawan have you configured chronograf to run on https? otherwise you will need to use http.

if you would like us to look into this, we will need the version of the OS and chronograf, as well as any settings you've tried and what the error you are seeing is.
