### ISSUE TITLE
Script Wizard - Error to compile query:...: function does not take a parameter "except"

### ISSUE THREAD

**Issue by gitgia** [influxdata/chronograf#5093]
When using the Script Wizard (InfluxDB 1.74) following error appears:
Error: failed to compile query: type errror 10:6-10:59: function does not take a parameter "except".

![image](https://user-images.githubusercontent.com/41324844/53007165-fc764b00-3436-11e9-8e08-5a8d3848f975.png)

SCRIPT:
from(bucket: "cadvisor/autogen")
|> range(start: dashboardTime)
|> filter(fn: (r) => r._measurement == "cpu_usage_per_cpu" and (r._field == "value"))
|> window(every: autoInterval)
|> mean()
|> group(except: ["_time", "_start", "_stop", "_value"])

**Comment by 121watts** [comment]
@russorat looks like the fix for this is already in the `1.7.x` branch and ready for next release
