### ISSUE TITLE
Chronograf displays field incorrectly as numerical value.

### ISSUE THREAD

**Issue by perzizzle** [influxdata/chronograf#5097]
If I insert a field with value "2018-08-23-20-42-38011_9d5986d5-a220-4949-9d42-840864df16ec" and query it back with chronograf it displays "2018.00". If I use the api directly or login to the influx server and query the data directly the correct value is displayed.

> influx -username user -password password
> SELECT "filename" FROM "telegraf"."autogen"."measurementName"
1551133225012000000 2018-08-23-20-42-38011_9d5986d5-a220-4949-9d42-840864df16ec

It looks to me like this string is being interpreted as a numerical value and rounded.

**Comment by perzizzle** [comment]
I am running chronograf-1.7.3-1.x86_64 and influxdb-data-1.7.4_c1.7.4-1.x86_64. Below is a screenshot of a point with a similar problem that starts with "2017-08..."

![screen shot 2019-02-26 at 8 22 30 am](https://user-images.githubusercontent.com/8809436/53419543-b32a7c00-399f-11e9-94e9-08e29af24513.png)

**Comment by russorat** [comment]
could you update to the latest chronograf and reopen if the issue persists? we fixed this in chronograf 1.7.4 https://github.com/influxdata/chronograf/pull/4819
