### ISSUE TITLE
Dasboard - Visualizations - Edit Line Controls Title unresponsive  

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5099]
Build **Nightly**
Build Time **201902132151**
Browser **Chrome 71**
```
$ chronograf --version
2019/02/27 14:23:26 Chronograf 201902132151~nightly (git: 63e16b0e1323caad5d63d86bcde8fa1a4795c01f)
```
*Use Case*

After installing test enterprise cluster using the script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh) as described [here](https://github.com/influxdata/bonitoo-selenium#starting-enterprise-cluster) and creating initial organization and account. 

1. create new dahsboard 
1. click add data
1. Add measurements telegraf.autogen > cpu > usage_idle and telegraf.autogen > cpu > usage_user
1. Click visualizations
1. Click the field Line Controls > title. The slider 'auto' is disabled and the field is highlighted. 
1. Enter a string value. 

The field is not responsive.  Keystrokes do not result in characters appearing within. 

*Expected Behavior*

That the field should be able to receive values and that these changes will be reflected in the preview area as happened previously. 

*Screenshots*
![dboardedityaxislabel01](https://user-images.githubusercontent.com/25881301/53493943-ea328780-3a9c-11e9-8577-654ba6cf5e97.png)

**Comment by baskinsy** [comment]
I can confirm this on a new install with latest stable version.

`chronograf --version
2019/03/14 17:28:03 Chronograf 1.7.8 (git: 8b0a9deb922b5a1fd85ab3c9a2b135dab5348f8d)`
