### ISSUE TITLE
How to Get hot reloading for development Env

### ISSUE THREAD

**Issue by dominiclapointe** [influxdata/chronograf#5100]
Hi,

The application start successfully but when we change any tsx files we need to rebuild the application.
there is any way to have a host reloading or just to hit F5 to get changes.

we already tried with --watch in yarn and parcel.

 thank you

**Comment by alexpaxton** [comment]
@dominiclapointe we are no longer officially using yarn, just NPM now. If you build the frontend using `npm start` it should automatically offer hot reloading
