### ISSUE TITLE
Ability to configure dashboards with annotation filters

### ISSUE THREAD

**Issue by kfindeisen** [influxdata/chronograf#5102]
Chronograf version: 1.7.0

I'm working in a project that has multiple Chronograf dashboards used by different groups to look at different (though similar) datasets. We have annotations that are only relevant to a single group or a single dataset. While we can use tags to identify group- or dataset-specific annotations, any filters on these tags must be manually re-applied on each new session.

It would be helpful if we could include preset annotation filters in the dashboard definition, so that when annotation display is enabled, the annotations are automatically filtered to those appropriate for a particular dashboard. The user should be able to override any presets using the existing per-session UI.

**Comment by nferch** [comment]
@kfindeisen did you find a solution for this? I have a similar problem. Even if you could specify the state of the visibility of annotations with a HTTP parameter would allow the dashboard to be bookmarked.

**Comment by kfindeisen** [comment]
No, we never did find a solution. I didn't argue with the stalebot because we have other feature requests that are a higher priority for us, but it would certainly be nice to see this implemented.
