### ISSUE TITLE
Improve customization of post alert type

### ISSUE THREAD

**Issue by mgiammarco** [influxdata/chronograf#5103]
Hello,
using a tick script I can write:
.post().endpoint("xxx")
and
.post().captureResponse()

These settings are missing from Chronograf create alert page. 
So each time I need to personalize http post (always...) and debug it (always...) I cannot use anymore the chronograf visual alert creation.
Please add these options to alert creation menu.
Thanks,
Mario

**Comment by jregovic** [comment]
+1
