### ISSUE TITLE
Ability to alter shading under lines

### ISSUE THREAD

**Issue by Safrone** [influxdata/chronograf#5108]
Sometimes with many measurements overlapping the shading under the lines makes it hard to make out similarly colored lines below them.

one example: 

![Screenshot from 2019-03-13 15-51-46](https://user-images.githubusercontent.com/14047377/54310376-a1082a80-45a8-11e9-9eb0-4e0b7ac7b5d8.png)

Being able to remove or perhaps alter the alpha level of the shading beneath lines would make this data easier to read.

**Comment by russorat** [comment]
@alexpaxton fyi

**Comment by JoshWeepie** [comment]
@Safrone @russorat @alexpaxton  I agree 100%, literally the first feature we looked for when standing this up was the ability to remove line graph fill, and not seeing any option to do so was disappointing

**Comment by timhallinflux** [comment]
@chnn -- this is now part of https://github.com/influxdata/giraffe ? and should appear in InfluxDB Alpha 14?

**Comment by chnn** [comment]
@timhallinflux It was added in alpha 12, and will be deployed to the cloud environment on Thursday.

Connect https://github.com/influxdata/influxdb/pull/14128

**Comment by Safrone** [comment]
@chnn @timhallinflux Is this available now?

**Comment by montanaflynn** [comment]
I really want this as well, using Chronograf Version: 1.8.4 and cannot figure out how to disable the fill on a dashboard chart.

<img width="1616" alt="Screen Shot 2020-07-28 at 13 58 21" src="https://user-images.githubusercontent.com/24260/88630190-6f7afb00-d0da-11ea-97b3-86d1676f5264.png">
