### ISSUE TITLE
Chronograf (1.7.8) Table cell truncated view 

### ISSUE THREAD

**Issue by simoBates** [influxdata/chronograf#5117]
Dear,
I have an issue in the view of table based cells after updating from Chronograf 1.7.3 to 1.7.8.
In particular, when are represented a significant number of rows (for ex more than 500), at a certain row the view is "truncated" with no cells apart from those of the first column. 
I have the same behavior in the "explore" menu, both using influxQL and flux.
Resizing the cell in dashboard, change the specific row at which the view is truncated but the problem persist.

Softwares version:
influxDB 1.7.4
chronograf 1.7.3 - 1.7.8
kapacitor 1.5.2
chrome 73.0.36

![image](https://user-images.githubusercontent.com/25823488/54538008-c4a9e700-4993-11e9-8b92-082eb6d85e34.png)
![image](https://user-images.githubusercontent.com/25823488/54538052-dab7a780-4993-11e9-8c57-8499bff7c8bf.png)
![image](https://user-images.githubusercontent.com/25823488/54538207-25d1ba80-4994-11e9-97d5-ec064d3ece72.png)

Thank you  very much,
Simone

**Comment by afausti** [comment]
I have noticed the same issue in 1.7.8.

**Comment by russorat** [comment]
closed by https://github.com/influxdata/chronograf/issues/5124
