### ISSUE TITLE
Static Legend not showing with Flux Query

### ISSUE THREAD

**Issue by clancye** [influxdata/chronograf#5119]
**Environment:**
Chronograf 1.7.8
InfluxDB 1.7.4
Chrome Version 73.0.3683.75 (Official Build) (64-bit)

**What I'm trying to do:**
Add a static legend to a visualization of a flux query. "Show" is selected for the static legend.  

**What's actually happening:**
It appears as if the legend boxes are being created but nothing is inside of them (see red circle). I've included a screenshot of the InfluxQL query and the Flux query.
 [
![flux_vs_influxql_static_legend](https://user-images.githubusercontent.com/3912598/54557851-8102ad80-4992-11e9-8dc1-23e5752c2a66.PNG)
](url)

**Comment by bthesorceror** [comment]
Hi @clancye, thank you for reporting this. Would you have an example of the flux query you are using to help us reproduce this?

**Comment by russorat** [comment]
closing. please reopen if this is still an issue.

**Comment by vsedyshev-intermedia** [comment]
Same issue with next request:

![image](https://github.com/influxdata/chronograf/assets/121124346/67512729-67f6-4006-ad21-112958df8d34)

**Comment by vsedyshev-intermedia** [comment]
Same issue with next request:

![image](https://github.com/influxdata/chronograf/assets/121124346/c93e5fa0-12bc-4c67-b0f1-86b3e22e6f11)

Select CPU measurement, with two field "usage_system", "usage_user",
filter by cpu regexp (cpu0, cpu1, ...), some specific host and as summary
aggregate maximum value per each 1 min.

As result I expect two series: "usage_system", "usage_user" contain
_time (rounded by 1 min.), maximum cpu usage at same minute.

Example:
_time   usage_system  usage_user
10:01         1           2
10:02         3           4

And chart should contain two series: usage_system and usage_user.
