### ISSUE TITLE
DataExplorer - Bad Query error message reduced to failed with status code

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5120]
Build **Nightly**
Build time **201903182000**
```
$ chronograf --version
2019/03/19 10:10:46 Chronograf 201903182000~nightly (git: d9c46c6d284897147949210f1d55af5119aab1d4)
```
*Use Case*

After setting up a test cluster using the script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh) and described [here](https://github.com/influxdata/bonitoo-selenium#starting-enterprise-cluster)...

1. Open Data Explorer
1. In the query editor enter an invalid string like "Bad_Query" 
1. Click "Submit Query" 

The message in the editor returns "Request failed with status code 400" 

Previously this message was more explicit. 

"error parsing query: found bad_query, expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1"

*Expected Behavior*

That more informative message should be displayed. 

*Screenshots*

![BadQueryMessage01](https://user-images.githubusercontent.com/25881301/54595524-10f83400-4a33-11e9-9623-346cf81bcf4b.png)
![BadQueryMessagePrevious](https://user-images.githubusercontent.com/25881301/54595525-10f83400-4a33-11e9-9cbe-0d584650b63e.png)

**Comment by Mixermachine** [comment]
This issue is important for me.
I'm currently getting to know Chronograf and all I'm receiving is error 400 when I try to query one existing database.

**Comment by maxxxxpower** [comment]
I've just reverted to using grafana which gives me zero errors. No matter how I add a DB or build a query in Chronograf, I keep getting the 400 error with no idea why!

**Comment by drook** [comment]
Same stuff here. Valid requests keep getting 400 status. Even the working ones from grafana.
