### ISSUE TITLE
Can't use Flux import statements

### ISSUE THREAD

**Issue by chnn** [influxdata/chronograf#5123]
This is the 1.x variety of this issue: https://github.com/influxdata/influxdb/issues/11428

See these previous fixes:

https://github.com/influxdata/influxdb/pull/11457/files
https://github.com/influxdata/influxdb/pull/11474/files

**Comment by russorat** [comment]
is this an issue because the flux version is old?

**Comment by chnn** [comment]
@russorat nay, it is because we use an older method of substituting the values for template variables in 1.x. 


We just prepend them to the script:
```
```
