### ISSUE TITLE
Cannot use template variables in database, rp, or measurement name in influxql

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5127]
as a user
with editor
when i edit a query in a cell
then i would like the ability to use a template variable as the db, rp, or measurement name in the query.

right now, they are not replaced.

**Comment by timhallinflux** [comment]
This is particularly useful when you have multiple retention policies and you want to switch between them.

**Comment by timhallinflux** [comment]
tagged for 1.8

**Comment by timhallinflux** [comment]
There appears to be a workaround.
Using a template variable along with a regular expression appears to work.  As in 
`FROM :database:../queryExecutor/`
