### ISSUE TITLE
Working query is changed by Chronograf to a non-working query.

### ISSUE THREAD

**Issue by robcowart** [influxdata/chronograf#5131]
Chronograf 1.7.8 - Official docker container from Docker Hub

The following query is entered which works...

```
SELECT sum("bytes") AS "bytes" FROM "network_flow".."network_flows" WHERE time > :dashboardTime: AND "host"=':host:' AND ("interface_in"=':interface:' OR "interface_out"=':interface:') GROUP BY time(:interval:),"service" FILL(0)
```

![image](https://user-images.githubusercontent.com/10326954/54782887-3eee9b80-4c20-11e9-82a4-6c95aa00cd87.png)

However once the visualization is saved, Chronograf changes it to the following, which no longer works (refresh the page if it doesn't immediately stop working)...

```
SELECT sum("bytes") AS "bytes" FROM "network_flow".."network_flows" WHERE time > :dashboardTime: AND "host"=':host:' AND "interface_in"=':interface:' AND "interface_out"=':interface:' GROUP BY time(:interval:), "service" FILL(0)
```

![image](https://user-images.githubusercontent.com/10326954/54783064-b6242f80-4c20-11e9-942e-e502a75133f5.png)

Chronograf should not change the queries in any manner. They should be left as the user created them.

**Comment by robcowart** [comment]
Further testing shows that parentheses are always removed from the WHERE clause, and OR is always changed to AND in the where clause.

**Comment by chnn** [comment]
Hey @robcowart, I'm having some trouble reproducing this issue.

What I tried:

1. Run Chronograf 1.7.8 via the Docker Hub image
2. Created a new dashboard, created template variables
3. Created a new cell with the following query (attempting to be as similar to your query as possible):

   ```
   SELECT sum("usage_user") AS "usage_user" FROM "telegraf".."cpu" WHERE time > :dashboardTime: AND "host"=':host:' AND ("cpu"=':cpu-0:' OR "cpu"=':cpu-1:') GROUP BY time(:interval:), "host" FILL(0) 
   ```
4. Check the visualization
5. Save the cell and check the visualization on the dashboard
6. Open the cell and check the visualization

I wasn't able to see my query modified in any way.

Could you try to reproduce with the latest Chronograf and InfluxDB? (1.7.12 and 1.7.6) And if you are able to reproduce, could you post the steps you took?

**Comment by jwmynhier** [comment]
Reproduced on Chronograf 1.7.12 and InfluxDB 1.7.7 using Docker Hub 

1. Run Chronograf and InfluxDB via InfluxData's sandbox repository.
2. Create a new dashboard without template variables
3. Create new cell with the following query:
`SELECT mean("usage_system") AS "mean_usage_system" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND ("cpu"='cpu0' OR "host"='telegraf-getting-started') GROUP BY time(:interval:), "host", "cpu" FILL(null)`
4. Save the cell, check the visualization.
5. Refresh the page, the visualization has changed.
6. Check query in cell:
`SELECT mean("usage_system") AS "mean_usage_system" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND "cpu"='cpu0' AND "host"='telegraf-getting-started' GROUP BY time(:interval:), "host", "cpu" FILL(null)`

The keys to reproducing the issue seem to be:
- Use OR between comparisons of different fields ("cpu" and "host" above).
- Use one or more hard-coded comparisons ('cpu0' and 'telegraf-getting-started' above).

**Comment by jwmynhier** [comment]
From further testing, the opposite behavior is seen when using AND between != comparisons.
Query entered as in 3 above:
`SELECT mean("usage_system") AS "mean_usage_system" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND "cpu"!='cpu0' AND "cpu"!='cpu1' GROUP BY time(:interval:), "host", "cpu" FILL(null)`
Resulting query as in 6 above:
`SELECT mean("usage_system") AS "mean_usage_system" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND ("cpu"!='cpu0' OR "cpu"!='cpu1') GROUP BY time(:interval:), "host", "cpu" FILL(null)`

**Comment by chnn** [comment]
@jwmynhier Thanks, I'm able to reproduce the issue now.

I believe I have a fix and will push it shortly.

**Comment by WAFFO** [comment]
Hello this is still happening for me, but in the opposite direction.

Original:  
`... AND "httpstatus"!='203' AND "httpstatus"!='200'`

Changed to:  
`... AND ("httpstatus"!='203' OR "httpstatus"!='200')`

**Comment by chnn** [comment]
@WAFFO what version of Chronograf are you using?

**Comment by WAFFO** [comment]
Hello @chnn , I have updated to the latest version (`1.7.12`) and I am still seeing the changes happening upon exiting and returning to my dashboard.

**Comment by chnn** [comment]
Ah, the fix hasn't been released yet. I expect it to land in 1.7.13, which should be out sometime in the next two weeks.

**Comment by WAFFO** [comment]
Ah, my bad, I should have followed the paper trail and seen the change is for next release. Thank you!
