### ISSUE TITLE
 Unable to set default Retention Policy through UI 

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#5132]
I remove "autogen" retention policy and set "seven_days" retention policy and my application was crash by error message "Database does not exists". Could you provide set "seven_days" as default retention policy throuth chronograf UI.

**Comment by russorat** [comment]
@vit1251 you can set the default rp in the source connection to influxdb. 

<img width="665" alt="Screen Shot 2019-03-27 at 7 03 16 PM" src="https://user-images.githubusercontent.com/4805997/55124356-32a48b80-50c3-11e9-9ed1-b2cc0a3e57aa.png">

**Comment by vit1251** [comment]
@russorat how about different one retention policy? May be better add button on page admin database set default retention policy? Right now on admin dB page we can delete and create but no set default.

**Comment by russorat** [comment]
I'm not sure which page you are talking about. could you add a screenshot indicating where you'd like to set it?

**Comment by vit1251** [comment]
@russorat I talk about "InglixDB Admin" you may see on screenshot

![image](https://user-images.githubusercontent.com/110534/55184719-ea10cf00-51a3-11e9-821b-63fec3ab0a08.png)

**Comment by russorat** [comment]
That information comes from the database. for more information on setting that, please see https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#examples-1

**Comment by vit1251** [comment]
@russorat just implement button "SET DEFAULT" per each one retention policy items or fix error with no database exists when no default retention policy is set.

**Comment by russorat** [comment]
thanks!
