### ISSUE TITLE
top menu missing in tick script mode

### ISSUE THREAD

**Issue by rdxmb** [influxdata/chronograf#5141]
![tickscript](https://user-images.githubusercontent.com/30314040/55786738-20f4b800-5ab5-11e9-8003-0a6b79a065e1.jpg)

Chronograf Docker Image tag: `"1.7.8"`
FF 66.0.2, Kubuntu 18.04

Steps to reproduce:

- open Tickscript in alert-rules
- scroll down
- scroll up
-> menu to save is missing

workaround: scale the Browser-Window, so scrolling is not necessary

**Comment by timhallinflux** [comment]
Cannot reproduce with 1.7.12

**Comment by rdxmb** [comment]
Cannot reproduce with FF 67.0.3

**Comment by rdxmb** [comment]
can reproduce with Kubuntu 20.04 (focal) , FF 78.0.2 and Chronograf 1.8.4
no problems with Kubuntu 20.04 (focal) + Chromium Version 84.0.4147.89 (Official Build)

**Comment by sranka** [comment]
I can't reproduce this with chronograf 1.9.0 and FF 91.0.2 .
