### ISSUE TITLE
ID_token validation with jwks_uri can crash with some OIDC provider

### ISSUE THREAD

**Issue by GregoireW** [influxdata/chronograf#5147]
I'm using a certified openid solution provider and when I try to use this solution as oauth2 generic provider with id_token on chronograf, it ended with a failure.

The issue is that the openid connect specification state ( https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata )   
> 	The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.

So openId provider MAY NOT include this representation. but in the code:

https://github.com/influxdata/chronograf/blob/d353324b472545e956b75b8ebec04103266c384f/oauth2/jwt.go#L148

this representation is mandatory.  My provider do not give me this representation hence the failure.

**Comment by timhallinflux** [comment]
We should relax this restriction to match the spec.

**Comment by chnn** [comment]
Hey @GregoireW, thanks for reporting. I pushed a fix for this in #5227, which should make its way into a release sometime in the next few weeks.
