### ISSUE TITLE
Flux Wizard add Mean function - Error: failed to compile query: var "upperDashboardTime" 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5156]
Build: **Nightly Build**
Build Time: **201904200056**
Browser: **Chrome 73**

```
$ chronograf --version
2019/04/23 10:40:18 Chronograf 201904200056~nightly (git: 7596fdc6615c0609e720bc159403a8cf581776d3)
```

*Use Case* 

1. Setup a test TICK stack cluster using script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh).
2. Create initial connection 
3. Open Data Explorer
4. Open flux editor
5. Click on the Script Wizard 
6. Select {bucket: telegraf/autogen; measurement: cpu; field: usage_idle}
7. Click _Insert Script_

The curves from the data series are plotted in the preview area.

8. Click on script_wizard again 
9. Select the function `mean()`
10. Click _Insert Script_ 

An error message appears in the preview area 

```
Error: failed to compile query: var "upperDashboardTime" redeclared at 6:1-6:46
```
Note that this seems to be occurring with all aggregate functions, also checked with median and stddev, which also threw the same error. 

*Expected Behaviour*

That the mean function will be applied and the curves will be drawn. 

*Screenshots*
![ScriptWizardAddMean01](https://user-images.githubusercontent.com/25881301/56567738-d8112900-65b5-11e9-93e0-1952c7a7c652.png)
![ScriptWizardAddMean02](https://user-images.githubusercontent.com/25881301/56567739-d8a9bf80-65b5-11e9-9af8-a476b1737cfc.png)
![ScriptWizardAddMean03](https://user-images.githubusercontent.com/25881301/56567740-d8a9bf80-65b5-11e9-8d8e-ef5f0e25948e.png)

*Console log*

```
src.b3be065e.js:2660 POST http://localhost:8888/chronograf/v1/sources/2/proxy/flux?path=%2Fapi%2Fv2%2Fquery%3Forganization%3Ddefaultorgname 500 (Internal Server Error)
(anonymous) @ src.b3be065e.js:2660
L @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:5
t.(anonymous function) @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:2660
o @ src.b3be065e.js:2660
s @ src.b3be065e.js:2660
(anonymous) @ src.b3be065e.js:3264
(anonymous) @ src.b3be065e.js:3278
L @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:5
t.(anonymous function) @ src.b3be065e.js:5
i @ src.b3be065e.js:3278
Promise.then (async)
l @ src.b3be065e.js:3278
(anonymous) @ src.b3be065e.js:3278
D @ src.b3be065e.js:3278
n.executeTemplatedFluxQuery @ src.b3be065e.js:3278
(anonymous) @ src.b3be065e.js:3278
L @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:5
t.(anonymous function) @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:3278
D @ src.b3be065e.js:3278
n.executeQueries @ src.b3be065e.js:3278
setTimeout (async)
value @ src.b3be065e.js:3276
(anonymous) @ src.b3be065e.js:3278
L @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:5
t.(anonymous function) @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:3278
D @ src.b3be065e.js:3278
value @ src.b3be065e.js:3278
xi @ src.b3be065e.js:716
wi @ src.b3be065e.js:716
ki @ src.b3be065e.js:716
Ha @ src.b3be065e.js:716
enqueueSetState @ src.b3be065e.js:716
h.setState @ src.b3be065e.js:708
(anonymous) @ src.b3be065e.js:807
r.onUpdate @ src.b3be065e.js:807
(anonymous) @ src.b3be065e.js:807
(anonymous) @ src.b3be065e.js:807
Promise.then (async)
t.setState @ src.b3be065e.js:807
s.setAndPersistState @ src.b3be065e.js:3379
s.handleChangeScript @ src.b3be065e.js:3379
C.n.handleSubmitScript @ src.b3be065e.js:3852
(anonymous) @ src.b3be065e.js:3852
L @ src.b3be065e.js:5
(anonymous) @ src.b3be065e.js:5
t.(anonymous function) @ src.b3be065e.js:5
u @ src.b3be065e.js:3852
Promise.then (async)
s @ src.b3be065e.js:3852
(anonymous) @ src.b3be065e.js:3852
P @ src.b3be065e.js:3852
C.n.handleAddToScript @ src.b3be065e.js:3852
D.a.handleAddToScript @ src.b3be065e.js:3814
a @ src.b3be065e.js:716
f @ src.b3be065e.js:716
d @ src.b3be065e.js:716
C @ src.b3be065e.js:716
P @ src.b3be065e.js:716
I @ src.b3be065e.js:716
_ @ src.b3be065e.js:716
z @ src.b3be065e.js:716
In @ src.b3be065e.js:716
Ei @ src.b3be065e.js:716
We @ src.b3be065e.js:716
Fn @ src.b3be065e.js:716
Si @ src.b3be065e.js:716
Rn @ src.b3be065e.js:716
```

**Comment by bryanspears** [comment]
Happens to me in 1.7.10 as well.

**Comment by bthesorceror** [comment]
@karel-rehor I could not reproduce in the latest code in master, would you be able to try a nightly from this week and see if you are experiencing this issue still?

**Comment by karel-rehor** [comment]
Checked on nightly build.

```
$ chronograf --version
2019/05/27 13:23:25 Chronograf 201905210042~nightly (git: d18a1aca36e2909639638ebb34971edd477cb7a0)
```
Seems the issue is resolved. 
Closing

**Comment by karel-rehor** [comment]
`Chronograf 201905210042~nightly (git: d18a1aca36e2909639638ebb34971edd477cb7a0)` no longer has this issue.  Seems the UI flux functions have already been actualize.
