### ISSUE TITLE
Download CSV should be available for users with  read only permissions

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/chronograf#5169]
Download CSV should be available for users with  read only permissions

Current status:
* The "Download CSV" item is hidden in the menu (see the screenshot below) under the "edit pencil" icon. So the export requires to have Edit permissions for given user. 

![image](https://user-images.githubusercontent.com/8028110/57034911-0b585580-6c51-11e9-9fa9-4ac24c6ebaf8.png)

Desired status:
* CSV should be downloadable by users with read permissions, because the "Download CSV" falls under the category of reading the data.

**Comment by timhallinflux** [comment]
This is the correct/desired behavior.  Users with View only permission should not be able to download the CSV -- this is intentional.
