### ISSUE TITLE
Fields containing comma character should be escaped in the file produced by "Download CSV" 

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/chronograf#5170]
Fields containing comma character should be escaped in the file produced by "Download CSV" 

1.7.9

Steps to reproduce:
1/ create field in measurement, insert data containing "," in the field
2/ open chronograf, create cell to display tabular data
3/ Use Download CSV and Import the file into Excel (or Libreoffice Calc)

Result:
The tool will parse the line with the field as separator and reads field value as two values. This will break structure of the CSV.

Desired status:
The file exported from Chronograf should correctly escape the comma character (according to CSV specs) that is part of field value. 

---
See the "SVX,KZN" this is value of the field "Kam":

![image (1)](https://user-images.githubusercontent.com/8028110/57035549-a0a81980-6c52-11e9-9776-f8196d226667.png)

Same data in Excel, SVX, KZN have been parsed as two fields:

![image (2)](https://user-images.githubusercontent.com/8028110/57035603-c03f4200-6c52-11e9-8d73-d230b97d393d.png)

**Comment by lukevmorris** [comment]
Validate that this is working correctly in 2.x?
