### ISSUE TITLE
Map example with stray bracket

### ISSUE THREAD

**Issue by andig** [influxdata/chronograf#5176]
Running Chronograf 1.7.10, raising here as I suspect flux as root cause.

Adding `map` from the Chronograf UI seems to introdce a stray (or missing) bracket:

    |> map(fn: (r) => r._value * r._value), mergeKey: true)

gives:

    [object Object]

**Comment by timhallinflux** [comment]
Flux wasn't updated for the the 1.7.7 InfluxDB release and therefore the Chronograf 1.7.12 didn't get the corresponding update.  Flux is planned to be updated with InfluxDB 1.7.8 and Chronograf 1.7.13.
