### ISSUE TITLE
Date picker not working Chronograf

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#5178]
I couldn't get the date picker to pick a relative time range this morning. Here is a gif:

![date_picker_not_working](https://user-images.githubusercontent.com/501993/57069778-7d6e8000-6ccd-11e9-927b-9eeb26b1e952.gif)

It only lets me pick an absolute date range.

I also have this console output:

![Screenshot 2019-05-02 11 28 06](https://user-images.githubusercontent.com/501993/57069826-9d05a880-6ccd-11e9-9fb0-91536ba21f68.png)

**Comment by bthesorceror** [comment]
This is fixed for another customer issue, will be released with 1.7.12
