### ISSUE TITLE
Making the Chronograf log viewer more effective

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#5179]
__Proposal:__

Add several features to Chronograf to help improve the log viewing experience.

__Current behavior:__

Chronograf currently allows the user to browse logs within an arbitrary time range and scroll to load more logs.

__Desired behavior:__
To make the log viewing experience more effective I would like Chronograf to do the following:

- Provide a setting where I can specify if I want the logs ordered from top to bottom, or bottom to top. Currently they're ordered from bottom to top (newer log lines at the top). This is counter intuitive and not how people read and analyse log data.
- Allow logs to be downloaded. It should be possible to extract the contents of the log viewer as a raw text file or similar.
- Provide a URL to a specific log line. This allows other people to click the link and be taken to the log viewer with the correct time range, filters and position in the results. Papertrail does this, for example.

__Use case:__
Internally we use Chronograf to visualise our log data, which itself is stored in InfluxDB in some environments. It's harder to do our jobs without these features.

**Comment by e-dard** [comment]
Don’t close

**Comment by steenstra** [comment]
I would very much like this as well.

**Comment by alejandroleonb** [comment]
#MeToo

**Comment by cgwyllie** [comment]
Any chance that https://github.com/influxdata/chronograf/issues/5201 could be looked at as part of improving the log viewer?

We'd like to make more use of the Chronograf log viewer but at the moment it's a little too slow to be effective.

**Comment by mgcrea** [comment]
@kristinarobinson Guess this was closed to focus on 2.0?

Is there any plans to bring back the log viewer to InfluxDB2?
