### ISSUE TITLE
Sometimes syslog database selector is empty in Opera

### ISSUE THREAD

**Issue by alexanderfefelov** [influxdata/chronograf#5189]
Chronograf 1.7.11.
Opera  58.0.3135.132 on Win 10.0.17134

With the same installation Edge works fine.

![chronograf](https://user-images.githubusercontent.com/5790321/58141470-2c0e3c80-7c4c-11e9-9be6-8feeacfd3c4e.png)

**Comment by timhallinflux** [comment]
we haven't tested at all with Opera.  I ran through a number of manual tests tonight with the latest version of Opera and Chronograf 1.7.12.  I could not reproduce.

**Comment by russorat** [comment]
we do not have plans to support the opera browser in chronograf.

**Comment by alexanderfefelov** [comment]
Ok, thanks.
