### ISSUE TITLE
Y axis scale wrong on stacked chart

### ISSUE THREAD

**Issue by pardo-bsso** [influxdata/chronograf#5190]
Hi all.

This might be related to #4843 but we do not have gaps in the data.

We are using a stacked chart with the following query:

```sql
SELECT "ambientTemperatureSensor", "correctedInfraredSky" FROM "weather"."autogen"."weather" WHERE time > :dashboardTime:
```

and after a while the data for ambientTemperature in this case is displayed between -5..0 when the real value is around +12.

Chronograf version is 1.7.11

Is there anything we can do to help debugging this?

Thanks.

![stacked_chart_wrong_axis_scale](https://user-images.githubusercontent.com/940837/58175570-cdaa8380-7c76-11e9-90a2-4d0670aee542.png)

**Comment by pardo-bsso** [comment]
Hi @russorat , is there any kind of feedback on this?

Thanks.

**Comment by russorat** [comment]
@pardo-bsso sorry for the late response. We are working on an updated version of stacked graph in https://github.com/influxdata/giraffe/issues/43 for our 2.0 platform.

**Comment by pardo-bsso** [comment]
Hi, no need to apologize.
Thanks for all the effort.
