### ISSUE TITLE
SHOW FIELD KEYS and SHOW TAG VALUES sometimes don't render in query builder

### ISSUE THREAD

**Issue by nisley** [influxdata/chronograf#5192]

**Comment by nisley** [comment]
There are many more tag values under >span in the linked data explorer, but they aren't being displayed. In looking at the data with Jacob we saw that some of these values have a colon ( : ) in them. 

![image](https://user-images.githubusercontent.com/1389799/58345069-50b11280-7e0c-11e9-8072-1f1939cc1ef8.png)

**Comment by timhallinflux** [comment]
I've been seeing this kind of "failure" to load metadata recently (1.7.11) 
as well (both tags and fields).  Unclear as to why this is happening.

**Comment by lukevmorris** [comment]
Maybe related to large result set, or inability for server to correctly parse response from InfluxDB. Might not be able to tackle next sprint, but let's triage.
