### ISSUE TITLE
log viewer shows wrong timestamp

### ISSUE THREAD

**Issue by acris5** [influxdata/chronograf#5195]
![Capture1](https://user-images.githubusercontent.com/34268588/58489909-dfa78d00-8174-11e9-871c-1115d7e9fb54.PNG)
time in histogram matches time on host and on server(Moscow timezone), but in logs viewer it shows 3 hours smaller. "jump to" works erroneously too

**Comment by timhallinflux** [comment]
The timestamps are typically rendered based on the timezone reported by the browser.  
Couple of questions:
1) what browser are you using?
2) what version of Chronograf are you using?

**Comment by acris5** [comment]
I checked on Edge, Chrome and Firefox, issue persists on all these browsers
Chronograf Version: 1.7.11
