### ISSUE TITLE
Canned influxdb_database.json series/measurements queries should be grouped by database or summed

### ISSUE THREAD

**Issue by clheikes** [influxdata/chronograf#5200]
It currently just shows the database with the highest cardinality/measurments. 

[influxdb_database.json](https://github.com/influxdata/chronograf/blob/master/canned/influxdb_database.json)

I would have assumed it was the cardinality of the host with a query similar to this:
SELECT sum("max_numSeries") from (SELECT max("numSeries") AS "max_numSeries" FROM "telegraf"."autogen"."influxdb_database" WHERE time > now() - 24h GROUP BY time(1h), "database", "host" FILL(null)) group by time(1h), "host"

**Comment by timhallinflux** [comment]
The queries we use from a support perspective are:
```
SELECT max("numSeries") AS "Series Cardinality" FROM "telegraf".."influxdb_database" WHERE  AND time > :dashboardTime:  GROUP BY time(:interval:), "database" fill(null)
```
and
```
SELECT max("numMeasurements") AS "Measurements" FROM "telegraf".."influxdb_database"  AND time > :dashboardTime:  GROUP BY time(:interval:), "database" fill(null)
```

If you are on an OSS instance, host is overkill.  If it's an InfluxEnterprise, we would expect the cardinality to be the same if the number of nodes = RF.  So, adding host might be overkill.

But, adjusting the canned query seems appropriate.  I believe we've address this with the dashboards available here: http://docs.influxdata.com/platform/monitoring/influxdata-platform/monitoring-dashboards/

We should adjust this one.  Thanks for pointing this out!
