### ISSUE TITLE
Chronograf spam requests

### ISSUE THREAD

**Issue by totaki** [influxdata/chronograf#5201]
Hi. I try using ITC stack for collect and view logs for application and get problem. When i open Log Viewer, chorongraf start spam POST requests for get logs without delay

```
Firefox 68.0b6
Telegraf 1.10.4 (git: HEAD 3548ce47)
Chronograf 1.7.11 (git: 6594b2f0247ef13fd94357691b15923838bd48d2)
InfluxDB v1.7.6 (git: 1.7 01c8dd416270f424ab0c40f9291e269ac6921964)
```
![Снимок экрана от 2019-06-03 00-32-56](https://user-images.githubusercontent.com/6254062/58767746-871f2800-8598-11e9-821c-ad567b3dd647.png)
![Снимок экрана от 2019-06-03 00-36-56](https://user-images.githubusercontent.com/6254062/58767748-8ab2af00-8598-11e9-868d-ad273c9997a1.png)

**Comment by timhallinflux** [comment]
I think I've reproduced your result.  But, this is expected behavior depending on the query parameters set.  Specifically, you can "pause" the search using the pause/play button in the upper left hand portion of the screen. 
<img width="371" alt="Screen Shot 2019-06-26 at 12 59 33 AM" src="https://user-images.githubusercontent.com/23535264/60162115-b8f96800-97ad-11e9-9c7b-28d914ad5695.png">

You can then adjust the remaining query parameters on the screen.

**Comment by cgwyllie** [comment]
We also observe a similar request bombardment when loading the log viewer. For us, it results in a _very_ slow load time for all the log rows within the filter period.

At first I had assumed the size of messages was causing the delay, but I can build a table visualization showing recent syslog lines and it loads nearly instantly.

Happy to raise this as a separate issue specifically about performance if preferred.

@timhallinflux could you explain a little more about how the time parameters for viewer are expected to work and why this seems correct?

We see sending 100s of requests to load logs but logs load in gradually over the course of 40-120s maybe. No individual request seems slow, but it results in a very poor user experience trying to explore logs.

**Comment by odalet** [comment]
Hi, is-it possible to open this issue again, the performance issue is still there in v1.8:

![image](https://user-images.githubusercontent.com/79333/78054953-206ac680-7383-11ea-99b6-68637057d8f8.png)

This bombing of POST requests to chronograf/v1/sources/10000/proxy seems the cause for the slowness each time we refresh or change the query parameters!
