### ISSUE TITLE
Custom columns in log viewer

### ISSUE THREAD

**Issue by boardwalk** [influxdata/chronograf#5210]
I'm logging to Influx using the Telegraf syslog plugin. I'm including some extra fields via [STRUCTURED-DATA](https://tools.ietf.org/html/rfc5424#section-6.3), and they show up in Influx like so:

```
> select * from syslog limit 1;
name: syslog
time                appname facility facility_code host                 hostname             message                                                                                                     procid severity severity_code slog@4 slog@ersatsz slog@ersatsz_addr timestamp           version
----                ------- -------- ------------- ----                 --------             -------                                                                                                     ------ -------- ------------- ------ ------------ ----------------- ---------           -------
1560996602565788324 ersatsz user     1             ersatsz_prod_login   ersatsz_prod_login   ﻿Pong sent; id c2f3                                                                                          9      info     6                                 10.255.0.2:9000   1560996602565589000 1
```

Specifically I'd like to add a column for `slog@ersatsz_addr`, but generally it'd be nice to be add any additional fields that come back, and be able to filter on them (I can't seem to do something like `slog@ersatsz_addr == 10.255.0.2:9000` in the search box).

**Comment by timhallinflux** [comment]
We agree.  This is planned for the more generic v2 event viewer that we have planned.  But, unlikely to appear in the Chronograf v1.x line.

**Comment by boardwalk** [comment]
Great, good to know it's planned. Thanks!

**Comment by timhallinflux** [comment]
In the meantime, you can create a table cell which allows for full customization.

I realize, you'll lose the histogram at the top and the search bar...but, you might be able to mimic this functionality by defining a variable of type "text"

Then use the "text" variable in the query that populates the table cell.  Essentially, you can parameterize the query using the dashboard time (including upper) and the "text" variable to get very close to what the "fixed" log viewer provides.  Let us know if you need more  help with that in the meantime?
