### ISSUE TITLE
Custom Meta Queries return non-quoted values which causes issues in dashboard queries

### ISSUE THREAD

**Issue by samhld** [influxdata/chronograf#5213]
The return value of a Customer Meta Query's `WHERE` clause is not single quoted.  This is the only method of creating a template variable that does this...which means that, if a user is creating dashboard cells in a uniform way that is compatible with the other "regular" methods of creating template variables, any cells that refer to the result of a Custom Meta Query will return "No results".

**Comment by timhallinflux** [comment]
dup of https://github.com/influxdata/chronograf/issues/4912
