### ISSUE TITLE
Failed authorization to Influxdb connection with special characters in password

### ISSUE THREAD

**Issue by zke-github** [influxdata/chronograf#5226]
Hi All,

I am experiencing some problems while I getting access to Influxdb from Chronograf.

**Setup**:
Influxdb 1.7.4, Chronograf 1.7.10, Kapacitor 1.5

Authorization is enabled on Influxdb and Chronograf uses Okta/Oauth2 too. Everything work perfectly while I use simple password for Influxdb admin user, like a 'admin'.

If I change the password to something like this 'cQs&2cL+eQ&4#9yaT*cP', Influxdb starts reporting error 401 'authorization failed' in logs for any requests from Chronograf (Host List, Explore)

It seems to be Chronograf does not care about special characters in password when it sends request to Influxdb.

**Expected behavior**:
All Chronograf functionality is available

**Actual behavior**:
No access to Influxdb data, see above.

Thanks.

**Comment by russorat** [comment]
does this username/combo work when calling the DB directly via the API?

**Comment by zke-github** [comment]
This request does work perfectly:

curl -k -G https://influxdb:8086/query --data-urlencode "u=admin" --data-urlencode "p=cQs&2cL+eQ&4#9yaT*cP" --data-urlencode "q=SHOW DATABASES"
