### ISSUE TITLE
Could not show logs get from fluntbit.

### ISSUE THREAD

**Issue by zw963** [influxdata/chronograf#5230]
Hi, i get logs from fluent and insert into influxdb like this:

```
> select * from "nginx_reverse_proxy.app2"
name: nginx_reverse_proxy.app2
time                _seq byptes_sent datetime                   http_user_agent                                                      http_x_forwarded_for ipv4            referer request_url request_verb status_code
----                ---- ----------- --------                   ---------------                                                      -------------------- ----            ------- ----------- ------------ -----------
1562833645429267305 0    0           11/Jul/2019:16:27:25 +0800 Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0 -                    183.193.173.219 -       /posts      GET          499
```

And, i can see columns is present in Explore view like this:

![image](https://user-images.githubusercontent.com/549126/61035653-25a17300-a3fa-11e9-8eec-da183e51360a.png)

But when i switch to Log View, i could not see anythings, just a blank panel.

### My Version:

CentOS,  yum install, Chronograf Version: 1.7.12

Thank you!

**Comment by goller** [comment]
Hi @zw963 !  Would you try turning off the "mean" function while you are in the data explorer?  That should give you the logs you seek.

**Comment by zw963** [comment]
@goller , Thank you for reply, i am a very new guy for `influxdb` and `chronograf`, could you please give me some clue about how to turning off the "mean"?

**Comment by zw963** [comment]
Hi, thank you for help, i got show a table view in "Explore" now. please see screenshot.

![image](https://user-images.githubusercontent.com/549126/61102913-85ebef80-a4a2-11e9-8454-ec421d934f2f.png)

But, i could not get show content showed in "Log View" table, after switch to, still get a blank panel.

![image](https://user-images.githubusercontent.com/549126/61102981-d7947a00-a4a2-11e9-814c-c48d130fee61.png)

I think maybe the reason cause this is  because i use a regexp in fluentbit to parse **nginx** logs directly
into json, and Log View only support apache2 raw log format, right?

Thank.

**Comment by goller** [comment]
Hey there, so the log viewer supports logs that are RFC 5424 format.  I searched around and found this about how to format nginx logs as rfc 5424: https://gitlab.com/snippets/1721988

In this way you can have nginx send logs to telegraf that is configured with its syslog plugin:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/syslog/README.md

**Comment by zw963** [comment]
> Hey there, so the log viewer supports logs that are RFC 5424 format.  I searched around and found this about how to format nginx logs as rfc 5424: https://gitlab.com/snippets/1721988

Thank,  so, this is means chronograf is not work well with fluentd or fluentbit which centerolize logs and prefer collect logs into json format, and, my data with json format only can be used in table view, right?

**Comment by dp1140a** [comment]
I would like to add to this feature request that the LogViewer be able to consume and display some additional log types besides just syslog.   Perhaps allow other predefined logformats like apache format or other web logs.  In the future the ability to map and display any custom log format would be very useful

**Comment by zw963** [comment]
It is so cool to hear this. thank you.
