### ISSUE TITLE
How to add multi header keys on post alert handler with chronograf UI

### ISSUE THREAD

**Issue by whyou5945** [influxdata/chronograf#5232]
Hey, I wanna add two or more header keys while using post alert handler. But it seems I can only add one k-v pair? I know I can change the TICK script to solve this, but I wonder can I just add multi header keys on chronograf UI? Thanks a lot!

![image](https://user-images.githubusercontent.com/7150504/61216816-e4ce9480-a740-11e9-92a6-095b874b0505.png)

**Comment by russorat** [comment]
Seems like you can only add a single one in the UI builder. You can manually edit the resulting TICKscript to add additional headers if needed as a workaround.

**Comment by whyou5945** [comment]
@russorat I know I can edit the TICKscript but i still wanna use the UI builder. When will this function ready for work?

**Comment by whyou5945** [comment]
@russorat hey, sorry to trouble you again. So, have the newest UI support multi header keys already?

**Comment by russorat** [comment]
@whyou5945 no, the UI still only supports one header. We have no plans to update the existing alert rule builder in the 1.x line but would happily review a PR. For now, you will need to add additional header keys in the tickscript.
