### ISSUE TITLE
query.go imports wrong repo

### ISSUE THREAD

**Issue by IvoPo** [influxdata/chronograf#5243]
Tried to install the TICK stack today on ARMv7 ARCH via AUR and came across some "missing" package errors. 

[influx/query.go](https://github.com/influxdata/chronograf/blob/master/influx/query.go) imports 
"github.com/influxdata/influxdb/influxql"
and it should be
"github.com/influxdata/influxql"

**Comment by wiegvlieg** [comment]
This is correct i had the same problem. I fixed it by using:
`cd $GOPATH/src/github.com/influxdata
find . -type f -name "*.go" -exec sed -i 's-github.com/influxdata/influxdb/influxql-github.com/influxdata/influxql-g' {} +`
