### ISSUE TITLE
Improved Visualizations for Text Data

### ISSUE THREAD

**Issue by rbkaspr** [influxdata/chronograf#5253]
Type: improvement/new feature

I'm looking to use TICK to monitor an Elasticsearch cluster, and one thing that I've encountered when augmenting the dashboard that Chronograf ships with is the lack of a good visualization for single text values, the one I'm interested in being cluster health.  

Tables aren't a very good solution to this, as there's no real way to format the appearance of the table beyond decimal count and background/text coloring which only really seems to work for numeric types. What I think would be great for something like this is a variant of the single stat visualization that renders text (or extending the existing single stat viz to allow for text). Something like this should be able to be big and obvious to anyone using this tool to monitor a system. 

![text_stat](https://user-images.githubusercontent.com/40441876/62701108-7bdde380-b9b1-11e9-9d52-edc8f79806d0.png)

**Comment by russorat** [comment]
This is being completed here: https://github.com/influxdata/influxdb/issues/15314 and will be available in 2.0 soon.
