### ISSUE TITLE
Template variables need a source database

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5254]
Currently the template variables only leverage the currently connected source database.  However, if your dashboard cells are using a specific source -- (i.e. not a dynamic source), the template variables become significantly less useful.

The same control that dashboard cells possess -- to allow for the definition/selection of the data source should be added to template variables.

For backward compatibility, if this is missing -- the template variable defaults to the dynamic source (as it does currently).

**Comment by russorat** [comment]
@hoorayimhelping this is finished?
