### ISSUE TITLE
Build from source is not working

### ISSUE THREAD

**Issue by wiegvlieg** [influxdata/chronograf#5256]
I have followed all the steps to build Chronograf from source, but i could not get it working.
The steps from the README.md are the following.
1. Install Go (seems to work)
2. Install Node and NPM (seems to work)
3. Install yarn (seems to work)
4. Setup your GOPATH (seems to work)
5. Build the Chronograf package: 
`go get github.com/influxdata/chronograf`
`cd $GOPATH/src/github.com/influxdata/chronograf`
`make`
6. Install the newly built Chronograf package:
`go install github.com/influxdata/chronograf/cmd/chronograf`

However withs tep 5 and 6 somethings goes wrong.
This is my docker file:
```
FROM ubuntu:xenial

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    libc6-dev \
    make \
    pkg-config \
    wget \
    curl \
    bash \
    git \
    ca-certificates \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

# Install GO
ENV PATH /usr/local/go/bin:$PATH
RUN wget -O go.tgz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz; \
    tar -C /usr/local -xzf go.tgz; \
    rm go.tgz; \
    go version

# Install NodeJS v10
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -; \
    apt-get update && apt-get install -y nodejs
    
# Install yarn
ENV PATH /opt/yarn-1.17.3/bin:$PATH
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -; \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee "/etc/apt/sources.list.d/yarn.list"; \ 
    apt-get update && apt-get install -y yarn; \
    yarn --version; \
    yarn install; \
    yarn upgrade caniuse-lite browserslist

ENV GOPATH /root/go
ENV PATH $GOPATH/bin:$PATH
RUN echo $(go env GOPATH); \
    mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

# Install chronograf
ENV GO111MODULE auto
RUN go get github.com/influxdata/chronograf && \
    cd $GOPATH/src/github.com/influxdata/chronograf && \
    make
    
RUN go install github.com/influxdata/chronograf/cmd/chronograf

CMD ["/bin/bash"]
```
The last RUN command fails because the dependencies are missing. I tried also to manually add them with `go get` individually. But then I run in the next problem of #5243. After i try to resol all issues there is not a chronograf binary created in the $GOPATH/bin folder.

Any help would be appreciated as i want to run Chronograf with a tiny change in the source folder.

Kind Regards, Wieger

**Comment by hoorayimhelping** [comment]
@wiegvlieg 

Hi Wieger :wave: thanks for taking the time to write up a report.

I ran into a similar issue when trying to test local Chronograf changes - steps 5 and 6 in the building from source section do not work in a docker environment.

### The Fix
There is a script, [`etc/build.py`](https://github.com/influxdata/chronograf/blob/master/etc/build.py) that you can run inside your docker image that will mimic steps 5 and 6 and build the `chronograf` executable into `build/chronograf`.

You'll want to remove the lines from your dockerfile that install chronograf via go. Instead, after your docker image is built, from inside the image, run:

```sh
./etc/build
```
When that is finished, you should be able to run 
```sh
./build/chronograf
``` 
as normal.

**Comment by goller** [comment]
@wiegvlieg @hoorayimhelping I've found the issue and it relates to the way @wiegvlieg is building with go modules.

Here is a Dockerfile that works:

```dockerfile
FROM ubuntu:xenial

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    libc6-dev \
    make \
    pkg-config \
    wget \
    curl \
    bash \
    git \
    ca-certificates \
    apt-transport-https \
    && rm -rf /var/lib/apt/lists/*

# Install GO
ENV PATH /usr/local/go/bin:$PATH
RUN wget -O go.tgz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz; \
    tar -C /usr/local -xzf go.tgz; \
    rm go.tgz; \
    go version

# Install NodeJS v10
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -; \
    apt-get update && apt-get install -y nodejs

# Install yarn
ENV PATH /opt/yarn-1.17.3/bin:$PATH
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -; \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee "/etc/apt/sources.list.d/yarn.list"; \ 
    apt-get update && apt-get install -y yarn; \
    yarn --version; \
    yarn install; \
    yarn upgrade caniuse-lite browserslist

# Install chronograf
ENV GO111MODULE auto
RUN go get github.com/influxdata/chronograf

ENV PATH /root/go/bin:$PATH
WORKDIR /root/go/src/github.com/influxdata/chronograf
RUN make
ENV GO111MODULE on
RUN go install ./cmd/chronograf/...

CMD ["/bin/bash"]
```

With go nowadays you don't need to specify GOPATH.  Additionally, with go modules there `go build` and `go install` work a bit differently than before.

To mimic the behavior you want, you would set `GO111MODULE` to `auto` to download the source.  See `go help gopath-get` for a bit more information.

Try out this Dockerfile!
