### ISSUE TITLE
Data Explorer - influxQL dangling filter arguments cause Data Explorer to fail to render on reload

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5259]
Build: **Nightly**
Build Time: **201908132230**
```
$ chronograf --version
2019/08/15 10:38:22 Chronograf 201908132230~nightly (git: 663f7f2050efd475dbe97c8892be871de6f290df)
```

**Use Case**
Testing against cluster set up using script found here: https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh
1. Open Data Explorer
1. Click the database and retention policy 'telegraf.autogen'
1. In the Measurements and Tags filter add 'cpu'.  The tree is filtered so only the cpu node is visible.
1. Leave Data Explorer by opening the home page
1. Return to Data Explorer.  The page fails to render. 

The console log contains 

```
src.58b4dc9d.js:717 TypeError: Cannot read property 'split' of null
    at src.58b4dc9d.js:3396
    at Array.filter (<anonymous>)
    at Object.s.reset [as onResetTimeMachine] (src.58b4dc9d.js:3396)
    at d.c (src.58b4dc9d.js:4118)
    at new d (src.58b4dc9d.js:1911)
    at Tl (src.58b4dc9d.js:717)
    at ja (src.58b4dc9d.js:717)
    at $a (src.58b4dc9d.js:717)
    at oo (src.58b4dc9d.js:717)
    at uo (src.58b4dc9d.js:717)
```

**Expected behavior**

That values left in a control like Measurements and Tags filter should not affect later re-rendering of the page. 

N.B. checked filters in the Flux editor and this does not occur.  The page can still render and the previous values are lost. 

**Work around**

In developer tools > application > local storage delete the entry for data explorer and load the page again. 

**Regression**

This is likely a recent regression.  Automated tests have been covering this functionality for a year.  However the test suite was updated to a new driver in the last couple of days and the new driver has lead to some unexpected side effects, which are being addressed.

This issue has been verified by manual checking.    

**Screenshots**

![DataExplorerMeasurementFilterHang01](https://user-images.githubusercontent.com/25881301/63084770-3ccd0680-bf4c-11e9-9ba1-97eb48dc95d3.png)
![DataExplorerMeasurementFilterHang02](https://user-images.githubusercontent.com/25881301/63084771-3ccd0680-bf4c-11e9-882c-a9f4676fe3f7.png)
![DataExplorerMeasurementFilterHang03](https://user-images.githubusercontent.com/25881301/63084772-3d659d00-bf4c-11e9-8fac-47666e113509.png)

**Comment by desa** [comment]
not stale

**Comment by karel-rehor** [comment]
@hoorayimhelping 
I can't reproduce it in the latest nightly build. 
```
$ chronograf --version
2019/11/26 09:57:44 Chronograf 201911221414~nightly (git: adef73900cb049dddb88ab9388469772f04fd4dc)
```
Looks like it was fixed as a side effect.
