### ISSUE TITLE
Unable to see database in "Log Viewer" but database and syslog data showing in "Explore" panel

### ISSUE THREAD

**Issue by BrownieX** [influxdata/chronograf#5260]
I successfully got syslog messages into my inlfuxdb via the telegraf [[inputs.syslog]] plugin

I can see that be database is collecting syslog message data by querying the DB in the Explore panel. 

However, when I go to the "Log Viewer" panel my source database is not listed in the drop down. 

Does anyone know how to fix this issue?

**Comment by hvp004** [comment]
I am having similar problem. `syslog` measurement appear inside the telegraf database but Log viewer does not show the dropdown for telegraf database.

**Comment by eparizzi** [comment]
No comments on this? For an open source project the lack of response here is awful. 
This doesn't encourage us to pay for support....
