### ISSUE TITLE
Combine different chart types for richer visualization

### ISSUE THREAD

**Issue by afausti** [influxdata/chronograf#5273]
Hi, 

when making dashboards in Chronograf it is really nice that you can combine the results of multiple queries on the same chart. 

I have a situation where the results of the first query (laser) are better visualized as a line chart and the results of the second query (ruby) are better visualized as a bar chart.

Currently,  the visualization type (line or bar) is applied to all queries. It would be nice if I could configure the visualization type per query to build richer visualizations. 

![image](https://user-images.githubusercontent.com/13968086/63992466-c1696a00-caa0-11e9-99c3-452ba3282b31.png)

![image](https://user-images.githubusercontent.com/13968086/63992477-d1814980-caa0-11e9-8129-2cfcbc56e7be.png)

**Comment by gotjoshua** [comment]
I would love to reopen this issue.

Mixed bar chart with line/area chart (especially for accumulated data) is really important.

**Comment by orangecoding** [comment]
Huh? I just learned that this is not possible. I honestly thing this is a basic feature that is absolutely needed when using the dashboard for serious analytics.

**Comment by afausti** [comment]
I totally agree and we need this all the time, we have measurements that represent sensor data and measurements that represent events. It would be really useful if we could overlay both using different chart types.

@alexpaxton @russorat I think this is especially useful in the Explore tool when debugging stuff.

**Comment by afausti** [comment]
There was a recent request for this feature from one of our users at Rubin Observatory. Is this something that can be implemented in Chronograf? or should this be considered for the InfluxDB 2.0 UI?

**Comment by afausti** [comment]
@russorat should we remove the stale label and reopen this issue for Chronograf?

**Comment by afausti** [comment]
We still find this request relevant.
