### ISSUE TITLE
Feature request: display string values, support categorical data

### ISSUE THREAD

**Issue by natejgardner** [influxdata/chronograf#5277]
Many common use-cases require visualization of non-numeric data. For example, if I'm creating an industrial IoT dashboard, I might like a cell that displays the last part serial number that was produced by a particular machine, the name of the current operator, and the current machine status code (as text).

However, today, the only way to visualize these values is with tables. The tables always show timestamp, so to display any of the values I described, a table with tiny text visualizing a `LAST()` query is the only working option. Single stat would be preferable as a low-hanging fruit solution. However, ultimately support for discrete / categorical values among the visualizations would be the best. E.g. Gantt charts, colored timelines, indicator lights / dots, shapes / icons (e.g. it would be great to simply have an icon showing whether a value is currently increasing or decreasing). Chronograf already makes use of the status indicators in the host list tab. I should be able to make a similar visualization for my hypothetical industrial machines.

Further, these categorical charts could be combined with current numerical charts the same way Tableau works: create one series per category and display vertically. I.e. group by behavior should have an option to visually segment charts rather than overlaying them all on top of each other. This would make creating sparklines infinitely easier. Today, I have to manually (or via script) define each and every category ahead of time. If new categories appear in my data, I have to manually redefine the dashboard in order to visualize them. 

See this Tableau example: ![2-Month-Measure-Names-and-Measure-Values-in-Sparklines](https://user-images.githubusercontent.com/8813777/64732658-09708f80-d498-11e9-9630-53d41e32e26b.png)

And finally, one step further, the concept of dashboard groups would be very helpful. For example, if I arrange a set of visualizations and would like to repeat that set for every category in a particular tag, it would be great to be able to have a dashboard dynamically create groups of cells with the results of the group by statements in the underlying queries.

**Comment by thevlab** [comment]
this is a good request. Sometimes need to display serial number, software version, product ID, really hope this feature can be added.
