### ISSUE TITLE
Increase InfluxDB query timeout

### ISSUE THREAD

**Issue by nitper** [influxdata/chronograf#5280]
The InfluxDB query proxy has a timeout of 30 seconds - is there a way to configure it to be longer?

**Comment by Tanveer1811** [comment]
Yes try increasing the limit in influxdb.conf file
![QM](https://user-images.githubusercontent.com/56547715/66754157-fd228c80-eeb2-11e9-82aa-9b8c11b91261.png)

**Comment by nitper** [comment]
InfluxDB configuration is not the issue. Chronograf proxies all InfluxDB requests, and those requests have a timeout on the client (chronograf) side.

**Comment by givo** [comment]
Hi all,

I think it's important to give users the ability to configure Chronograf query timeout. I am receiving timeout errors when running a big query in Chronograf while running the same query using the python library works fine.

**Comment by sranka** [comment]
Impl note: Chronograf 1.9.0 has a fixed default dialer timeout: 30 seconds.

**Comment by rwb196884** [comment]
Do you mean `config.toml`? I don't have a `influxdb.conf`.
