### ISSUE TITLE
(Firefox) HTTP auth in URL causes in-page links to break

### ISSUE THREAD

**Issue by psidex** [influxdata/chronograf#5294]
I have Chronograf sitting behind NGINX, which is set up to use basic http auth:

```bash
server {
    auth_basic "Restricted";
    auth_basic_user_file /etc/apache2/.htpasswd;
     
    listen 80;
    server_name chronograf.example.com;

    location / {
       proxy_pass http://127.0.0.1:8888;
    }
}
```

If I visit the page

`http://user:password@chronograf.example.com`

All of the URLs on the page become prefixed with `user:password@`, not like Chronograf is serving them like that, but Firefox is doing it in the browser. This causes the links to become unusable, clicking them does nothing. This seems to be Firefox's fault, as in Chrome, this doesn't seem to happen.

[Example image](https://i.imgur.com/sTjNzdj.png) (hovering over the "Configuration" tab showing the URL)

Client:
- Windows 10
- Chrome 77.0.3865.90 (64-bit)
- Firefox 69.0.2 (64-bit)

Server:
- Debian 10.1
- NGINX 1.14.2
- Chronograf 1.7.14 - installed by adding `repos.influxdata.com` to apt lists and then apt installing `chronograf`

Honestly not sure if this is a Chronograf issue or a Firefox issue, I thought it would be worth reporting on here, though.

**Comment by keith6014** [comment]
i too am curious. Does chronograf even support nginx auth_basic ?
