### ISSUE TITLE
Auth0 Integration redirects to hostless URI

### ISSUE THREAD

**Issue by OfficeUnlimited** [influxdata/chronograf#5317]
Hello,
I tried to integrate Auth0 in a working Influx/Chrongraf setup. Whenever I enable Auth0, the browser is redirected to a wrong hostless Uri, where that should contain an Auth0 domain.

The location header of the redirect message contains for instance:
https:///authorize?access_type=online&client_id=_the_real_client-id&redirect_uri=https%3A%2F%2Fdashboards.officeunlimited.nl%2Foauth%2Fauth0%2Fcallback&response_type=code&scope=openid+email&state=some_state

It looks like the auth0 domain is not being fetched in the authorization url.

version: Chronograf 1.7.14 (git: 038fb2a1d4f22adaecd1cd23d01a28159e0d248f)

Chronograf is started from commandline only (TLS cert and port are fine):

/usr/bin/chronograf --cert=/etc/ssl/certs/wildcard_no_pass.pem --log-level=debug --auth0-domain=woip.eu.auth0.com --auth0-client-id=_the_real_clientID_ --auth0-client-secret=_the_real_secret_ --public-url=https://dashboards.officeunlimited.nl --token-secret=_some_real_token --port=443

This logged to screen upon connection:
DEBU[0058] Request                                       component=server method=GET remote_addr=10.0.0.35:52233 url=/chronograf/v1/
INFO[0058] Response: OK                                  component=server method=GET remote_addr=10.0.0.35:52233 response_time=460.832µs status=200
DEBU[0058] Request                                       component=server method=GET remote_addr=10.0.0.35:52233 url=/chronograf/v1/me
ERRO[0058] Invalid principal                             component=token_auth method=GET remote_addr=10.0.0.35:52233 url=/chronograf/v1/me
INFO[0058] Response: Forbidden                           component=server method=GET remote_addr=10.0.0.35:52233 response_time=60.344µs status=403
DEBU[0059] Request                                       component=server method=GET remote_addr=10.0.0.35:52233 url=/oauth/auth0/login
INFO[0059] Response: Temporary Redirect                  component=server method=GET remote_addr=10.0.0.35:52233 response_time=229.176µs status=307

Any ideas?

Best Regards,
Ronald

**Comment by OfficeUnlimited** [comment]
Please consider I enabled TLS and run Chronograf on 443. So this might have something to do with CORS maybe .. I am not into those web details so just guessing here.

**Comment by OfficeUnlimited** [comment]
This is what fiddler shows in the headers:

Location: https:///authorize?access_type=online&client_id=_the_real_client-id&redirect_uri=https%3A%2F%2Fdashboards.officeunlimited.nl%2Foauth%2Fauth0%2Fcallback&response_type=code&scope=openid+email&state=_some_state_

so it looks like the public Url is not fetched in orso ..

**Comment by OfficeUnlimited** [comment]
with Github the integration work, but I find Auth0 more suitable for my use case so I really would like this to work. I tried also without a public_url set in the config, but didnt work either. Kinda clueless now..

**Comment by OfficeUnlimited** [comment]
if was on my end, sorry to bother ...

**Comment by coinchirp** [comment]
For those that may in the future run across this issue, while Auth0 presents a domain with NO https:// prior to it this is actually required.

AUTH0_DOMAIN=https://example.auth0.com
