### ISSUE TITLE
Build Failed . Make file throws the error 

### ISSUE THREAD

**Issue by vvvprabhakar** [influxdata/chronograf#5318]
After running ```make```

```GO111MODULE=on go build -o chronograf -ldflags "-s -X main.version=1.7.11 -X main.commit=bb4f123b" ./cmd/chronograf/main.go
# github.com/influxdata/chronograf/dist
dist/dist.go:39:13: undefined: AssetInfo
dist/dist.go:84:14: undefined: AssetInfo
make: *** [chronograf] Error 2```

**Comment by glinton** [comment]
`AssetInfo` is provided by a generated file that `make` should be [generating](https://github.com/influxdata/chronograf/blob/69cf16a/Makefile#L61). 

Trace is as follows:
`make` starts on line 31 of that link, requires line 58, which requires line 61, which generates that file.

If you get `undefined: AssetInfo` try running `make dist/dist_gen.go`.

If you are still having problems building using `make` comment here (include output from `go version` and `node --version`) and i'll re-open
