### ISSUE TITLE
Debian Repos Out of Date

### ISSUE THREAD

**Issue by Alphasite** [influxdata/chronograf#5322]
The debian repo: https://repos.influxdata.com/debian/dists/xenial/stable/binary-amd64/Packages still contains the `v1.17.14` release and needs to be updated for `v1.17.15`.

**Comment by russorat** [comment]
@Alphasite thanks! I'll figure out how to keep that updated.

**Comment by russorat** [comment]
@Alphasite @desa i think these were updated. could you confirm?
