### ISSUE TITLE
Adding Authentication  & Configuring Roles 

### ISSUE THREAD

**Issue by vvvprabhakar** [influxdata/chronograf#5325]
Hi 

I am using chronograf from last two weeks 
I want to add sign in with google functionality 
I have seen this Doc
https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/
I did not get what to do 
I see some part of code regarding authentication and authorization in authenticated.js and authorised.js

Please help me in adding a some authentication and authorization 

Regards
Prabhakar

**Comment by russorat** [comment]
@vvvprabhakar thank you for opening this issue. We already have support for google: https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/#configure-google-authentication

If you are still having an issue and believe this is a bug, please open a new issue with the details. If you need help configuring, join us in the community slack and we can help you here: https://influxdata.com/slack
