### ISSUE TITLE
Run Selenium Suite Against master

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5328]

**Comment by desa** [comment]
@karel-rehor can you run your test suite against master some time this week? I'd like to cut a 1.7.16 release of chronograf.

**Comment by karel-rehor** [comment]
I've taken a moment to synchronize a couple of tests with new changes.  This uncovered a new defect #5330. 

There are still a couple of test synchronization issues to look at.

**Comment by desa** [comment]
@karel-rehor great! Thanks for catching this. I've just put this issue into our ready queue. Let me know if there are any others that you find.

**Comment by desa** [comment]
@karel-rehor can you run the test suite again. We've recently added a fix for #5330

**Comment by russorat** [comment]
this is being run against master.
