### ISSUE TITLE
Edit Dashboard Cell - Schema values not loaded into panels Measurement & Tags or Fields

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/chronograf#5330]
Build: __Nightly__
```
$ chronograf --version
2019/12/03 15:00:03 Chronograf 201911261811~nightly (git: dc03bbec5cf45a42282f8688e208c94520b918fa)
```

__Use Case__

Testing against an Enterprise test cluster configured using script found [here](https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/infrastructure/setup_test_environment_enterprise_version.sh)

1. Create a dashboard with an initial cell using telegraf.autogen cpu usage_idle data 
1. Save the dashboard 
1. Edit the dashboard and add a second cell using telegraf.autogen kernel entropy available data 
1. Save the cell 
1. In the first cell click ''configure" 

The schema navigation panels are not filled or updated to match the query in the edit text area. 

Even after deleting the second newer cell, when opening configure the cell, the schema panels are not updated. 

__Screencast of problem__
![EditDashboardNoNavInfluxQL01](https://user-images.githubusercontent.com/25881301/70058330-fd035b00-15de-11ea-860c-78fca82a12ec.gif)

__Regression__ 

Comparing this use case to an automated test run in September, the schema navigation panels were updated correctly. 

__Screencast of legacy functionality__

![LegacyEditClonedDashboardCell01](https://user-images.githubusercontent.com/25881301/70058415-27551880-15df-11ea-9344-d806cfd50863.gif)

__Note__ 

When working with a newly created dashboard and its first cell, configure can be opened several times and the schema navigation panels are filled as expected.

**Comment by TCL735** [comment]
/chronograf/v1/dashboards/:dashboardID/cells is giving back a response with nested queryConfig object that has only the rawText filled in. All other properties are empty/blank/false including areTagsAccepted, fields, and tags

**Comment by desa** [comment]
@121watts @goller does this change have anything to do with the BE changes you all mentioned last week.

**Comment by desa** [comment]
@121watts just did a git bisect and got to 

```
Author: Michael Desa <mjdesa@gmail.com>
Date:   Thu Nov 7 14:53:01 2019 -0500

    fix(data-explorer): always include upper dashboard time in query (#5309)

    Closes https://github.com/influxdata/chronograf/issues/5297

    Co-authored-by: Andrew Watkins <andrew.watkinz@gmail.com>

:100644 100644 fad260a186e8017d5ba9f836272cb9de97e1c3b4 d63ed7504998bd6455a1e4e327a23a75ff1f52a4 M	CHANGELOG.md
:040000 040000 057f8110e3d230fac2d0b0dfb9807c6793f8f21f 94ceb2eab491649342953293d7858e6c71869f3c M	ui
```

as the commit that introduced the issue
