### ISSUE TITLE
Cannot apply colourized thresholds to tables in Cloud and OSS 2.0 

### ISSUE THREAD

**Issue by 8none1** [influxdata/chronograf#5331]
What happens:  When you add thresholds or a different base colour to a table the selected colours are not applied to the table in the dashboard and when you go back in to check the configuration the changes have seemingly not been saved.

What I expected to happen:  Clicking the green tick or the blue Submit button would apply the new colours to the table and they would persist if I went back in to the configuration menu later on.

Steps to reproduce:
 1. Create a dashboard in 2.0 and add a table
 2. Configure the table
 3. Open the Customize Table menu
 4. Change the Base colour
 5. Add a new threshold with a different colour
 6. Click the green tick at the top
 7. Back at the dashboard notice that the colours are not applied
 8. Click back on Configure and notice that the changes you just made are not persistent

**Comment by russorat** [comment]
thanks @8none1 ! i think this has been partially resolved with https://github.com/influxdata/influxdb/issues/15904

If there is something still missing, let us know by opening an issue in the influxdb repo https://github.com/influxdata/influxdb and we will take a look.
