### ISSUE TITLE
Maybe log viewer have some error

### ISSUE THREAD

**Issue by LinkinStars** [influxdata/chronograf#5337]
When I insert data to syslog measurement with a severity tag that not standard. 
Just like 
`insert syslog,severity=error message="test"` (err is standard but error is not)
The log view show this 
![image](https://user-images.githubusercontent.com/19712692/71301235-b2a01d80-23d7-11ea-8539-2b17eea53d8e.png)

This tip is not very friendly. I didn't know it was caused by the nonstandard severity at the beginning.

The chronograf version is `1.7.14`

**Comment by russorat** [comment]
@LinkinStars thanks for reporting. This part of the app is designed to work with the schema from the Telegraf syslog input plugin: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/syslog

That being said, we shouldn't error like that so we will take a look. Thanks!

**Comment by desa** [comment]
Error boundary should be displayed in a reasonable place.
