### ISSUE TITLE
configuring Organization "Default" with src file does nothing

### ISSUE THREAD

**Issue by camccar** [influxdata/chronograf#5341]
When using Oath and including a `.src` file with organization set to `Default` The UI still ask for connection details. An example .src file,

```
{
"id": "1999",
"name": "telegraf",
"username": "telegraf",
"password": "secretpassword",
"url": "https://yoururl:8086",
"type": "influx",
"insecureSkipVerify": true,
"default": true,
"telegraf": "telegraf",
"organization": "Default"
}
```

I also see someone else on github that has the same problem.
https://stackoverflow.com/questions/54184287/chronograf-not-able-to-add-default-influxdb-connection-when-using-oauth-2-0

there doesn't seem to be a way with oath to avoid getting the start up screen asking for connection details because you can't configure the `Default` Organization

**Comment by camccar** [comment]
My problem was organization needs to be a lower case d

**Comment by glinton** [comment]
This seems to be resolved so i am going to close this. If this is still an issue, please comment and i'll re-open so we can address. Thanks
