### ISSUE TITLE
 Chronograf (1.7.16) Invalid size returned for cell 2 of value NaN

### ISSUE THREAD

**Issue by rcmonitor** [influxdata/chronograf#5347]
What browser are you using (name and version)?
* Vivaldi 2.8.1664.40 (Stable channel) (64-bit)

What operating system are you using?
* Windows 10 Enterprise LTSC 1809 build 17763.914 (to run browser to access Chronograf)
* centos-release-7-7.1908.0.el7.centos.x86_64 (to run TICK stack)

Please describe what you were trying to do when you encountered this error:
- Executing following query hand-written into Chronograf -> Explore:
```sql
SELECT COUNT(*) FROM "database_name"."two_hours"."measurement_name"
```
With this query I was trying to get number of rows in measurement, which seemed to be really hard to figure out.
```
Error: Invalid size returned for cell 2 of value NaN
    at i.value (http://host-name.fake:8888/src.a5ab7481.js:2848:1411)
    at i.value (http://host-name.fake:8888/src.a5ab7481.js:2848:2700)
    at r.value (http://host-name.fake:8888/src.a5ab7481.js:2852:2359)
    at f.value (http://host-name.fake:8888/src.a5ab7481.js:2923:12908)
    at f.value (http://host-name.fake:8888/src.a5ab7481.js:2923:11170)
    at Ba (http://host-name.fake:8888/src.a5ab7481.js:717:65834)
    at ja (http://host-name.fake:8888/src.a5ab7481.js:717:65629)
    at $a (http://host-name.fake:8888/src.a5ab7481.js:717:69008)
    at oo (http://host-name.fake:8888/src.a5ab7481.js:717:91055)
    at uo (http://host-name.fake:8888/src.a5ab7481.js:717:91442)
```

**Comment by russorat** [comment]
@rcmonitor thanks for reporting. we will look into addressing this in the UI. For now, i think switching your visualization type to "Table" might help?

![image](https://user-images.githubusercontent.com/4805997/72567992-eb62d380-386b-11ea-933c-c92b6e10af4c.png)

**Comment by rcmonitor** [comment]
My visualization type actually WAS set to `table`

**Comment by russorat** [comment]
@rcmonitor thanks! we will take a look.

**Comment by glinton** [comment]
@rcmonitor can you identify clear steps to reproduce this, I haven't been able to do so yet, thanks.

**Comment by glinton** [comment]
eureka! i've been able to reproduce this twice now (linux and windows using chrome), thanks to the many reports (#5350 #5299 #5209 #5180 #4914 #4830 #3801 #3364) of this issue (seemingly stumbled upon in different ways).

Steps to reproduce:
1. have data in influxdb. run the following with telegraf.
```toml
[[inputs.cpu]]
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
```
1. "explore" data and add a query
```
```

**Comment by sranka** [comment]
This issue is reproducible with 2 queries that produce the same column names, such as:
```
SELECT max("usage_guest_nice") AS "mean_usage_guest" FROM "telegraf"."autogen"."cpu"
```
The layer that transforms data then fails to merge such data and creates structures that contain undefined/null columns/data. It works fine, when different column names are used.
