### ISSUE TITLE
Send to dashboard doesn't work

### ISSUE THREAD

**Issue by glinton** [influxdata/chronograf#5351]
While exploring data, a user was unable to send the query to a dashboard
![image](https://user-images.githubusercontent.com/2653109/72565237-a8562f80-386e-11ea-83f4-60e839b07c71.png)
a workaround could be to copy the query, navigate to the desired dashboard, add a cell, then paste the query into that cell.

**Comment by e-dard** [comment]
Thanks @glinton.

**Comment by glinton** [comment]
I've found that I can reproduce this by going to "explore" -> selecting `show databases` from the "metaquery templates" dropdown. behavior is the same as the above screenshot, no errors in the js console.

**Comment by timhallinflux** [comment]
It appears that when selecting something from the metaquery templates...that somehow disables the ability to save the resulting cell to a dashboard.  Specifically, the modal Send to Dashboard window's green Send to Dashboard button does not become enabled even though a target dashboard and cell has been selected.

You can clear the issue by closing the query tab...and starting again.
