### ISSUE TITLE
Feature request: Add the possibility to hide the histogram in the log viewer

### ISSUE THREAD

**Issue by amaury10** [influxdata/chronograf#5355]
We are using chronograph log viewer in an embedded web browser with a small windows. It's difficult to display the log viewer with its big histogram eating 2/3 of the windows.

For small window display, make possible to hide the histogram, both using a button and url parameter.

![2020-01-21_0939](https://user-images.githubusercontent.com/5411296/72788319-fafa6780-3c31-11ea-9c23-5fc4c42b874c.png)

**Comment by russorat** [comment]
@amaury10 thanks for the issue. Looks like you'd just have to rip out the LogsGraphContainer here: https://github.com/influxdata/chronograf/blob/master/ui/src/logs/containers/LogsPage.tsx#L265

if you wanted to do a custom build for your use case.

**Comment by amaury10** [comment]
Hi,

Thank you for answering so quickly. I'll try to do the modification and rebuild.
Best regards,

Amaury LAURENT.

**Comment by timhallinflux** [comment]
create setting for hiding the histogram
