### ISSUE TITLE
Ping request over https is always trying to verify server certificate

### ISSUE THREAD

**Issue by UPC-PaalDriveklepp** [influxdata/chronograf#5357]
When adding a new connection, Chronograf requests /ping, and checks the response. If the response indicates support for flux, this is saved for later. If the server has a self-signed certificate, all requests must not verify the server's certificate. This seems to not work correctly for the initial /ping request, and the connection is saved as flux not supported. Tested flux-queries agains the same influxdb server using Grafana, and it works just fine.

To reproduce:
Run influxdb with https enabled, self-signed certificate, and flux-enabled=true in influxdb.conf. Then try to use chronograf with flux.

Result:
When trying to add a graph to a dashboard, the radio buttons next to the connection selection combo box says "The current source does not support flux".

**Comment by UPC-PaalDriveklepp** [comment]
This was influxdb 1.7.9 and chronograf 1.7.0.

**Comment by UPC-PaalDriveklepp** [comment]
`[http]
enabled = true
bind-address = ":8086"
auth-enabled = true
https-enabled = true
# The SSL certificate to use when HTTPS is enabled.
https-certificate = "/etc/ssl/influxdb-selfsigned.crt"
# Use a separate private key location.
https-private-key = "/etc/ssl/influxdb-selfsigned.key"
flux-enabled = true
pprof-enabled = true
pprof-auth-enabled = true
debug-pprof-enabled = false
ping-auth-enabled = false`

**Comment by glinton** [comment]
Have you tried with a more recent version of chronograf to verify this hasn't been resolved? the current release is 1.7.17 and can be downloaded at https://portal.influxdata.com/downloads/

**Comment by UPC-PaalDriveklepp** [comment]
> Have you tried with a more recent version of chronograf to verify this hasn't been resolved? the current release is 1.7.17 and can be downloaded at https://portal.influxdata.com/downloads/

Pretty sure I tried with multiple versions, including the newest one

**Comment by UPC-PaalDriveklepp** [comment]
If anyone wants to reproduce/debug this issue, it should be quite easy:
`sudo openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/influxdb-selfsigned.key -out /etc/ssl/influxdb-selfsigned.crt -days 36500 -subj "/C=NO/O=My Company Inc/CN=mycompany.com/emailAddress=mail@mycompany.com"`

`sudo chown influxdb:influxdb /etc/ssl/influxdb-selfsigned.*`

Then enable https and auth, and add certificate and key in influxdb.conf, as shown in previous comment.
