### ISSUE TITLE
.dashboard files in --resources-path don't load after upgrade to 1.8

### ISSUE THREAD

**Issue by glinton** [influxdata/chronograf#5364]
After upgrading to 1.8, pre-canned `.dashboard` files aren't loaded

**Comment by xe-nvdk** [comment]
Hi @glinton 
Greg, Do you know if this feature is working? I'm trying to run Chronograf with resources path, and the only thing that I can get is this... I already tried with a VM with Ubuntu Server, Docker, and Kubernetes. 

![image](https://user-images.githubusercontent.com/64545348/118307049-8ac7c300-b4c0-11eb-9d6a-16e3ca379218.png)

**Comment by glinton** [comment]
Last I knew, this was working. Where it says 1 Dashboard, but displays nothing, I'd investigate the ui (make sure the api really isn't returning the loaded dashboard). If you're still having trouble with it, I think opening a new github issue would be the next step.

**Comment by xe-nvdk** [comment]
I will do that, in fact I have several dashboards in the /usr/share/chronograf/resources directory and I'm using the environment variable pointing to that directory. Still, the only thing that I saw is that thing. 

Thank you.
