### ISSUE TITLE
Anonymous users should be automatically redirected to Chronograf's configured Identity Provider

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#5371]
In 1.7.16, a user without a session would be automatically redirected to Chronograf's configured Identity Provider for authentication:
![Kapture 2020-02-06 at 13 42 02](https://user-images.githubusercontent.com/1438089/73981457-1b3f4d00-48e7-11ea-8757-ca756680f71a.gif)

In 1.7.17, this behavior no longer occurs:
![Kapture 2020-02-06 at 13 44 51](https://user-images.githubusercontent.com/1438089/73981470-1da1a700-48e7-11ea-95d0-32b23a83903a.gif)

**Comment by desa** [comment]
cc @hoorayimhelping

**Comment by desa** [comment]
I suspect that this is related to https://github.com/influxdata/chronograf/pull/5340, but I'm not certain.

**Comment by glinton** [comment]
@lukebond, what about with IdP's that don't require re-logging in each time? It seems re-enabling this behavior would reintroduce the loop resolved in 5340.

**Comment by lukebond** [comment]
I think you meant @lukevmorris, @glinton? 😄
