### ISSUE TITLE
As a user, when I click log out, I should be automatically logged out of Chronograf's configured Identity Provider

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#5372]
Reproduced with 1.7.16.

![Kapture 2020-02-06 at 13 54 35](https://user-images.githubusercontent.com/1438089/73981981-45ddd580-48e8-11ea-807d-ab1e54161ee1.gif)

When I click log out, I expect to be dropped onto a login screen asking me for email/password. This doesn't happen because
- We kill the local browser session for Chronograf
- But the browser session for the Identity Provider is still active
- So when Chronograf redirects to IdP's login screen, IdP skips the login form and auto redirects the user agent back to Chronograf with an authenticated user profile

To avoid this, we should both kill the local browser session, as well as redirect the user agent to the IdP's standard logout path. In this way, IdP will no longer recognize the user, and will request that the user authenticate again by rendering a login form

**Comment by desa** [comment]
cc @hoorayimhelping

**Comment by desa** [comment]
I believe that this was solved in https://github.com/influxdata/chronograf/pull/5340 which is a part of the 1.7.17 release

**Comment by glinton** [comment]
@lukebond can you try with 1.7.17? I believe this was fixed in that version

**Comment by glinton** [comment]
We'll re-open if this is reproducible in 1.7.17 or newer, I have yet to reproduce.
