### ISSUE TITLE
 Bug  with vertical scaling of dashboard in mode present

### ISSUE THREAD

**Issue by kirill98402** [influxdata/chronograf#5373]
Reality: when you switch to the dashboard view mode with parameter in address bar «present =true» and when you try to scale the dashboard vertical, nothing happens. With horizontally scaling, the graph is scaled.
Expectation: when switching to the dashboard view mode with parameter in address bar «present =true» and when trying to scale the dashboard vertical, scaling should occur. With horizontally scaling, the graph is scaled.

How to test
1) Open chrongraf in localhost
2) Open dashboards panel
3) Insert parameter «present =true» in the address bar
4) Try to scale the dashboard vertical

Link for video with testing:
https://youtu.be/Bt_8RHX_V-E

**Comment by russorat** [comment]
@kirill98402 thanks for reporting. I can reproduce on my machine. I have also filed: https://github.com/influxdata/chronograf/issues/5382 for this.

The purpose of presentation mode is not to explore the dashboard, and is mainly used for tv screens or kiosks where a mouse isn't there.

**Comment by sranka** [comment]
It works fine with the current master (1.8.7), probably fixed together with  #5382
