### ISSUE TITLE
 Chronograf (1.7.14) Expected number or array but got string: 40.

### ISSUE THREAD

**Issue by dipukurianmathew** [influxdata/chronograf#5375]
What browser are you using (name and version)?

What operating system are you using?

Please describe what you were trying to do when you encountered this error:
creating an alerts using Kapacitor
```
Error: Expected number or array but got string: 40.
    at j (http://localhost:8888/src.d4e31fda.js:3173:1898)
    at W.parseArray_ (http://localhost:8888/src.d4e31fda.js:3173:31911)
    at W.start_ (http://localhost:8888/src.d4e31fda.js:3173:35574)
    at W.updateOptions (http://localhost:8888/src.d4e31fda.js:3173:36541)
    at d.value (http://localhost:8888/src.d4e31fda.js:3233:4878)
    at no (http://localhost:8888/src.d4e31fda.js:717:84207)
    at ao (http://localhost:8888/src.d4e31fda.js:717:85725)
    at http://localhost:8888/src.d4e31fda.js:717:98848
    at Object.exports.unstable_runWithPriority (http://localhost:8888/src.d4e31fda.js:713:3303)
    at Xo (http://localhost:8888/src.d4e31fda.js:717:98783)
```

**Comment by russorat** [comment]
@dipukurianmathew thanks for the issue. Could you try with the latest chronograf 1.7.17?

If it still exists, could you add what you were doing in alert builder when the error happened?

**Comment by dipukurianmathew** [comment]
The field we are using is a string . now we changed to ineger it is working now . but the real problem now is not alerting .

**Comment by dipukurianmathew** [comment]
updated the chronograf  .. below is the script i am using 

var db = 'telegraf'

var rp = 'telegraf_5yr'

var measurement = 'elasticsearch_os'

var groupBy = []

var whereFilter = lambda: TRUE

var name = 'Elastic_cpu'

var idVar = name

var message = '{{ .ID }} is {{ .Level }} value: {{ index .Fields "value" }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var details = 'The Elastic have high CPU'

var crit = 10

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "cpu_percent")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" > crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .details(details)
        .email()
        .to('test@domain.com')

trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')

**Comment by russorat** [comment]
@dipukurianmathew thanks. yes, strings are not supported in the Alert Rule Builder.

So were you able to get this working and alerts firing?

**Comment by dipukurianmathew** [comment]
The alerts are not generating . I am now using free version , is that matter ?

**Comment by sranka** [comment]
Works for me, so it is more likely a configuration issue of the email/SMTP handler, chronograf (1.9) comes with an alert testing functionality that helps with the troubleshooting of your SMTP configuration - #5771.
