### ISSUE TITLE
Can't submit query or run script

### ISSUE THREAD

**Issue by sdado96** [influxdata/chronograf#5386]
![influx_query](https://user-images.githubusercontent.com/60974206/74343296-2264d000-4dab-11ea-9f43-225fa521997a.PNG)
Hello,
It seems i can't submit query or run script from chronograf, I tried through a python script to send requests to my influx server and it is responding, so the problem is not the db.

When i submit a query, it starts to load undefinitely like in the image. 
When i try to run a script, i click on "Run Script" but nothing happened.
 I checked on the prompt which is executing the chronograf exe, and it seems that no request was made to the server.
Chronograf is connected to the influx server.
Influx version = 1.7.9
Chronograf version = 1.7.14

**Comment by russorat** [comment]
@sdado96 thanks for the issue. It's strange that you're not able to connect. Could you post the client config for the python script as well as the source configuration from Chronograf? Are you able to load any data in Chronograf at all? or is it just this query?

Also, it sounds like you are running Chronograf on Windows? Can you confirm and also give the browser name and version as well?

**Comment by sranka** [comment]
Defect, such as #5641 were causing this. It is all fixed in chronograf 1.9.
