### ISSUE TITLE
OAuth2.0 PKCE - code_challenge required

### ISSUE THREAD

**Issue by ladeak** [influxdata/chronograf#5394]
During authentication (to a private OAuth identity provider PingFederate) I get a login failure "code_challenge is required".

Does Chronograf support PKCE with OAuth?

Chronograf version 1.7.8
I have the following environment variables set:

Generic_Api_Url=<private>
Generic_Api_Key=<private>
Generic_Auth_Url=<private>
Public_Url=<private>
Generic_Client_Id=<private>
Generic_Client_Secret=<private>
Generic_Name='openidconnect'
Generic_Scopes='openid email'
Token_Secret=<private>
Generic_Api_Key=userPrincipalName

**Comment by russorat** [comment]
@ladeak thanks for the issue. We don't support PKCE with OAuth today, but would not be opposed to adding it. I'll leave this open as a feature request. 

If someone from the community wants to add it, we would be happy to review and merge.
