### ISSUE TITLE
Support Bitbucket OAuth support using e-mail endpoint

### ISSUE THREAD

**Issue by cosmonova** [influxdata/chronograf#5399]
Currently the Bitbucket Cloud cannot be used as OAuth client due to the e-mail field not found on default /user endpoint ( https://developer.atlassian.com/bitbucket/api/2/reference/resource/user )

Similar with the Github workaround, the e-mail can be obtained from ( https://developer.atlassian.com/bitbucket/api/2/reference/resource/user/emails )

**Code to be updated:**
https://github.com/influxdata/chronograf/blob/9d8a49ba0ef8131cdce22d73718859f55f434db2/oauth2/generic.go#L177

**Comment by russorat** [comment]
@cosmonova thanks for opening this. it's tough to support all of these different providers. We would gladly review a PR to address this from the community since we don't have a bitbucket cloud account to test it against.

**Comment by cosmonova** [comment]
@russorat I already have a fix by setting the GENERIC_API_KEY to handle the  jsonPath for the email. Ex:   GENERIC_API_KEY: values.[0].email . If this solutions is ok for you, I will update the tests and create the PR.

Thanks.

**Comment by russorat** [comment]
@cosmonova great! I'll find out. I'd say go ahead an open the PR anyway to help anyone else running into this issue.

**Comment by yurymkomarov** [comment]
what is the current status of the issue? Moving from one milestone to another worries me (

**Comment by sranka** [comment]
I see that bitbucket's https://developer.atlassian.com/bitbucket/api/2/reference/resource/user/emails is poorly documented. I created a new account to test how the response looks like:
```json
{
  "pagelen": 10,
  "values": [
    {
      "is_primary": true,
      "is_confirmed": true,
      "type": "email",
      "email": "pavel.zavora@bonitoo.io",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/user/emails/pavel.zavora@bonitoo.io"
        }
      }
    }
  ],
  "page": 1,
  "size": 1
}
```
Such a response is not recognized, an array response (bitbucket's values) is expected and then different names of `is_primary` and `is_confirmed` field.

**Comment by yurymkomarov** [comment]
does anybody will update documentation with usage example?

**Comment by sranka** [comment]
https://github.com/influxdata/chronograf/issues/5399#issuecomment-590526395 is still valid, we would gladly review your contribution to the docs. https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/#configure-chronograf-to-use-any-oauth-2-0-provider and https://developer.atlassian.com/cloud/bitbucket/oauth-2/ will help.

**Comment by yurymkomarov** [comment]
@sranka am I right that this changes were not released in latest docker image?

**Comment by sranka** [comment]
Yes, it will be part of the next (1.8.10) release, it is now available in the nightly build.

**Comment by yurymkomarov** [comment]
@sranka where I can find link to repository with nightly builds?

**Comment by sranka** [comment]
https://portal.influxdata.com/downloads/

**Comment by yurymkomarov** [comment]
@sranka i've got it, thanks. but there are some problems with bitbucket :/

i'm getting this errors:

`
time="2021-01-06T19:27:57Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/oauth/bitbucket/login
time="2021-01-06T19:27:57Z" level=info msg="Response: Temporary Redirect" component=server method=GET remote_addr="10.2.100.205:17142" response_time="191.148µs" status=307
time="2021-01-06T19:28:01Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url="/oauth/Bitbucket/callback?state=xxx"
time="2021-01-06T19:28:01Z" level=info msg="Response: Moved Permanently" component=server method=GET remote_addr="10.2.100.205:17142" response_time="81.75µs" status=301
time="2021-01-06T19:28:01Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url="/oauth/bitbucket/callback?state=xxx"
time="2021-01-06T19:28:02Z" level=error msg="Unable to retrieve primary email No primary email address"
time="2021-01-06T19:28:02Z" level=error msg="Unable to get principal identifier No primary email address" component=auth method=GET remote_addr="10.2.100.205:17142" url="/oauth/bitbucket/callback?state=xxx"
time="2021-01-06T19:28:02Z" level=info msg="Response: Temporary Redirect" component=server method=GET remote_addr="10.2.100.205:17142" response_time=338.535263ms status=307
time="2021-01-06T19:28:02Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/login
time="2021-01-06T19:28:02Z" level=info msg="Serving assets" component=server method=GET remote_addr="10.2.100.205:17142" url=/login
time="2021-01-06T19:28:02Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1
time="2021-01-06T19:28:02Z" level=info msg="Response: Moved Permanently" component=server method=GET remote_addr="10.2.100.205:17142" response_time="116.562µs" status=301
time="2021-01-06T19:28:03Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1/
time="2021-01-06T19:28:03Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1/me
time="2021-01-06T19:28:03Z" level=error msg="Invalid principal" component=token_auth method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1/me
time="2021-01-06T19:28:03Z" level=info msg="Response: Forbidden" component=server method=GET remote_addr="10.2.100.205:17142" response_time="71.525µs" status=403
time="2021-01-06T19:28:03Z" level=debug msg=Request component=server method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1/env
time="2021-01-06T19:28:03Z" level=error msg="Invalid principal" component=token_auth method=GET remote_addr="10.2.100.205:17142" url=/chronograf/v1/env
time="2021-01-06T19:28:03Z" level=info msg="Response: Forbidden" component=server method=GET remote_addr="10.2.100.205:17142" response_time="392.598µs" status=403
`

my chronograf configuration:
`
    LOG_LEVEL = "debug"

    INFLUXDB_URL  = "xxx:443"
    KAPACITOR_URL = "xxx:443"

    TOKEN_SECRET          = "xxx"
    GENERIC_NAME          = "Bitbucket"
    GENERIC_CLIENT_ID     = "xxx"
    GENERIC_CLIENT_SECRET = "xxx"
    GENERIC_AUTH_URL      = "https://bitbucket.org/site/oauth2/authorize"
    GENERIC_TOKEN_URL     = "https://bitbucket.org/site/oauth2/access_token"
    GENERIC_API_URL       = "https://api.bitbucket.org/2.0/user/emails"
    GENERIC_SCOPES        = "email"
    GENERIC_DOMAINS       = "xxx.com"
    PUBLIC_URL            = "https://monitoring.xxx.com"
`

what can be the problem? :/

**Comment by sranka** [comment]
GENERIC_API_URL =  "https://api.bitbucket.org/2.0/user"

**Comment by sranka** [comment]
@yurymkomarov I double-checked that it works fine with the following settings:

__Bitbucket OAuth Consumer Details__
Followed instructions in https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/ with
* Callback URL: http://localhost:8888/oauth/bitbucket/callback
* Permissions: Account read, email

__Chronograf Setup__
```
export TOKEN_SECRET=...
export GENERIC_CLIENT_ID=...
export GENERIC_CLIENT_SECRET=...
export GENERIC_AUTH_URL=https://bitbucket.org/site/oauth2/authorize
export GENERIC_TOKEN_URL=https://bitbucket.org/site/oauth2/access_token
export GENERIC_API_URL=https://api.bitbucket.org/2.0/user
export GENERIC_SCOPES=account
export PUBLIC_URL=http://localhost:8888
export GENERIC_NAME=bitbucket
```

**Comment by yurymkomarov** [comment]
@sranka , yeah. I've changed the GENERIC_API_URL and everything starts to work ) thx u )

**Comment by yurymkomarov** [comment]
@sranka hello ) what is ET of 1.8.10 public release? )
