### ISSUE TITLE
oauth2 / Unable to exchange code for token / certificate signed by unknown authority

### ISSUE THREAD

**Issue by whatyoudoiswhatyouare** [influxdata/chronograf#5402]
I configured Chronograf 1.7.12 (installed as k8s pod using helm stable/chronograf) to work with oauth2 provider Keycloak by following [this guide ](https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/#configure-chronograf-to-use-any-oauth-2-0-provider  )and the known conf from [this comment](https://github.com/influxdata/chronograf/issues/5031#issuecomment-454004428).
The login fails though (clicking the button "Log In with Generic" -> transports me again to same page /login):

```
[pod/chronograf-6cd88b459f-j2nx8/chronograf] time="2020-02-25T12:05:21Z" level=error msg="Unable to exchange code for token Post https://auth.DOMAIN/auth/realms/REALM/protocol/openid-connect/token: x509: certificate signed by unknown authority" component=auth method=GET remote_addr="1.2.3.4:59954" url=/oauth/REALM/callback?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODI2MzI5MjAsImlhdCI6MTU4MjYzMjMyMCwibmJmIjoxNTgyNjMyMzIwLCJzdWIiOiJVMVRBT1gyRWxYb1FJekp6bVZ3QzJEMUQwL1ZJcmNNT2NIZjZOOVRPRStrPSJ9.b25faRKE0PimfJfTVO65hktD_j1AOzXes0GhKKv8kCE&session_state=b28ec403-9aa9-45a3-8aae-b0e61da6c405&code=0ddf87ea-9953-448d-b51c-9136ad891308.b28ec403-9aa9-45a3-8aae-b0e61da6c405.f1117622-0e00-4e65-b226-6955a1254b9a
```

As I am using non-official TLS certificates though, I am suspecting this is the root cause. I investigated a bit and found that you can specify the `insecureSkipVerify` flag in Golang.
However, a much cleaner (and securer) approach would be to specify the root ca that can be used to validate against.

I think for Kapacitator there are both options, but for Chronograf..?

Any ideas how to solve this in the currently released version in config? Or does this need code change?

Thanks by the way for some really great apps.

Also, @makrste: thanks for the hints!

**Comment by russorat** [comment]
@whatyoudoiswhatyouare thanks for the issue. I was looking into it and it looks like it will require a code change based on this comment: https://github.com/google/go-github/pull/598#issuecomment-333039238

We would need to update: https://github.com/influxdata/chronograf/blob/master/oauth2/mux.go#L119 and add a command line flag for this.

If this is something you want to try, we would gladly review a PR. Otherwise, we will consider it for a future release.

**Comment by rafuz** [comment]
This is really useful for using Chronograf in R&D enterprise enviroments. I have a GitLab installation isolated from the Internet for privacy reasons (R&D) which is the oauth provider for many applications. Everything uses a private enterprise PKI for certificates.
