### ISSUE TITLE
ARM package does not work with armv5

### ISSUE THREAD

**Issue by tobi-tobsen** [influxdata/chronograf#5405]
According to [GoArm](https://github.com/golang/go/wiki/GoArm) Go should be able to compile for armv5.
However, none of the Packages provided on the download page for chronograf work for me (Synology DS 212+), while oddly,  the influxdb I got via 
`wget https://dl.influxdata.com/influxdb/releases/influxdb-1.7.10_linux_armhf.tar.gz`
works great on that hardware.

Can you please provide a similar package for chronograf as well?

- Full details of your operating system (or distribution) e.g. 64-bit Ubuntu 14.04.
Synology DS212+ (armv5 compatible) 
> Processor       : Feroceon 88FR131 rev 1 (v5l)
> BogoMIPS        : 1985.74
> Features        : swp half thumb fastmult edsp
> CPU implementer : 0x56
> CPU architecture: 5TE
> CPU variant     : 0x2
> CPU part        : 0x131
> CPU revision    : 1
> Hardware        : Synology 6282 board
> Revision        : 0000

- The version of Chronograf you are running
v1.8

- Whether you installed it using a pre-built package, or built it from source.
Prebuilt package I got via 
`wget https://dl.influxdata.com/chronograf/releases/chronograf-1.8.0_linux_armhf.tar.gz`

**Comment by russorat** [comment]
@tobi-tobsen thanks for opening this. So what happened when you tried to start `https://dl.influxdata.com/chronograf/releases/chronograf-1.8.0_linux_armhf.tar.gz` on your synology? Were there any errors?

**Comment by russorat** [comment]
This is what we use to build Chronograf. Could you take a stab at updating it with the additional build required? https://github.com/influxdata/chronograf/blob/master/etc/build.py#L87

**Comment by tobi-tobsen** [comment]
when I try to run it, it says 
> Illegal Instruction (core dumped)
which is a lie (core isn't dumped - at least I cannot find a relevant core file).

According to the Go wiki, it then has to be "armel" so it adds "GOARM=5" to the build options (https://github.com/influxdata/chronograf/blob/master/etc/build.py#L505).

Unfortunatley I havent got a machine to try it. Can you provide a binary build with this commandline?

**Comment by tobi-tobsen** [comment]
Something like this _should_ work: 
`GOOS=linux GOARCH=arm GOARM=5 go build HelloGoWorld.go`

**Comment by goller** [comment]
Hey @tobi-tobsen , I'm not sure why the InfluxDB with hardware floating point works, but, I bet this chronograf build with software floating point will work for you:

```sh
 wget https://dl.influxdata.com/chronograf/releases/chronograf-1.8.0_linux_armel.tar.gz
```

Would you give that a try and see if it is working?  In the mean time I'll try to see what is different in the influxdb builds.

**Comment by tobi-tobsen** [comment]
Thanks for providing that version!
Unfortunately, I still get "illegal instruction" when running the version you linked.

Maybe uname -a output helps in addition to the /proc/cpuinfo I pasted previously: 

Linux 2.6.32.12 #24922 Tue Apr 23 17:32:06 CST 2019 armv5tel GNU/Linux synology_88f6282_212+

**Comment by tobi-tobsen** [comment]
I used readelf trying to understand the differences between influxdb (which runs fine) and chronograf. The output of readelf -h looks almost identical: 
chronograf 1.8.0:
![chronograf_elf](https://user-images.githubusercontent.com/1068154/76164868-82545980-6152-11ea-8ce1-3247582a1635.png)

influxdb 1.7.10:
![influxdb_elf](https://user-images.githubusercontent.com/1068154/76164875-88e2d100-6152-11ea-9a40-a8ac04d5845d.png)
I am not sure why my version of elfread doesn't show the proper Flags (but `<unknown>`)

**Comment by tobi-tobsen** [comment]
Is there anything I can log to get to the root of this?

**Comment by tobi-tobsen** [comment]
I tried to find what others did with the same error. Apparently there was a similar issue on the Golang issue tracker and they solved it by making sure to rebuild runtime environment during compilation, since something was cached and then the linker did something wrong:
Here they suggest to compile with `GOARCH=arm GOARM=5 GOOS=linux go build -a` :
https://github.com/golang/go/issues/20127#issuecomment-297417860

Can you try this please @goller or @russorat ?

**Comment by sranka** [comment]
@tobi-tobsen https://dl.influxdata.com/chronograf/releases/chronograf-nightly_linux_armel.tar.gz and the next release of chronograf (1.8.10) provides correct ARM v5 build
