### ISSUE TITLE
[fronted bug] each refresh query the order time change automatically

### ISSUE THREAD

**Issue by zodman** [influxdata/chronograf#5407]
here small video of the action..

To reproduce click refresh query to 5sec. Click on time order after 5sec the order of result change automatically an then you lost the order of you want.

![](http://g.recordit.co/6znn7GsRtu.gif)

**Comment by ivankudibal** [comment]
Cannot reproduce with the latest nightly build, Here's the procedure.

1. open data explorer, http://ec2-52-52-145-20.us-west-1.compute.amazonaws.com:8888/sources/3/dashboards/3?refresh=10s&lower=now%28%29%20-%2015m#
2. SELECT mean("copyShardReq") AS "mean_copyShardReq" FROM "_internal"."monitor"."cluster" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)
3. set refresh interval to 5s, sort table by time
4. the query refreshes every 5s, data every 10s
