### ISSUE TITLE
Chronograf unable to connect to InfluxDB when ping authentication is enabled

### ISSUE THREAD

**Issue by Anubi85** [influxdata/chronograf#5423]
I'm running InfluxDB docker container on a raspberry pi and using Chronograf docker container on a mac to manage the database.
When I enable the http and ping authentication Chronograf is no longer able to connect to the InfluxDB container.
Cronograf returns "Error contacting Source". If I check the container log I see the following error: level=info msg="Failed to retrieve database version" error="{\"error\":\"unable to parse authentication credentials\"}\n"
From cli I can successfully connect with AUTH.
I try also a few REST call providing the username and password and everything works as expected. Even the /ping endpoint works properly when I provide the authentication information.
If I disable the ping authentication (keeping the http authentication enabled) Cronograf is able to connect to the InfluxDB container with no problem.

I attached my InfluxDB configuration.

[influxdb.txt](https://github.com/influxdata/chronograf/files/4334263/influxdb.txt)

**Comment by russorat** [comment]
@Anubi85 thank you for opening this!

**Comment by glinton** [comment]
@Anubi85 what version of influxdb are you running? I can't reproduce this with 1.7.7, but I think I've got a fix once I can reproduce it. My issue is that it seems my version of influx doesn't actually authenticate the ping route, even when configured and a user added.

If you are using the same version, consider adding steps to reproduce from scratch, thanks.

Excerpt from config:
```toml
[http]
  auth-enabled = true
  ping-auth-enabled = true
```
influxd output
```
GET /ping HTTP/1.1" 204
GET /query HTTP/1.1" 401
```

**Comment by Anubi85** [comment]
I'm using influxdb 1.7.10 (influxdb:latest docker image)
