### ISSUE TITLE
Alert Rule Builder Email Handler only on Critical

### ISSUE THREAD

**Issue by robomotic** [influxdata/chronograf#5433]
Hello folks,
really beautiful project, I really like it so far!
I have setup an alert rule with a check on a counter.
I am receiving emails with different levels (OK when the threshold is not crossed) and Critical when the threshold is crossed.
Is there a way to only send emails when is Critical, otherwise I keep receiving emails half hourly also when the condition is fine.
Cheers.

**Comment by russorat** [comment]
@robomotic thank you for the issue. You might need to manually edit the TICKscript generated by the alert builder to accomplish this. The docs are here: https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/

Could you post your TICKscript to provide more context?

**Comment by robomotic** [comment]
Hello there,
yes this is the TICK script auto generated from the Alert:

```
var db = 'devices'

var rp = 'day'

var measurement = 'sensor30m'

var groupBy = []

var whereFilter = lambda: TRUE

var name = 'Active Temperature Sensors'

var idVar = name

var message = '{{.ID}} is {{.Level}} value : {{index .Fields "value" }}'

var idTag = 'alertID'

var levelTag = 'level'

var messageField = 'message'

var durationField = 'duration'

var outputDB = 'chronograf'

var outputRP = 'autogen'

var outputMeasurement = 'alerts'

var triggerType = 'threshold'

var details = 'There are some missing devices reporting temperature.'

var crit = 10

var data = stream
    |from()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
        .groupBy(groupBy)
        .where(whereFilter)
    |eval(lambda: "temperature_counts")
        .as('value')

var trigger = data
    |alert()
        .crit(lambda: "value" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .details(details)
        .email()
        .to('robomotic@gmail.com')

trigger
    |eval(lambda: float("value"))
        .as('value')
        .keep()
    |influxDBOut()
        .create()
        .database(outputDB)
        .retentionPolicy(outputRP)
        .measurement(outputMeasurement)
        .tag('alertName', name)
        .tag('triggerType', triggerType)

trigger
    |httpOut('output')

```

I read the documentation on that page although it doesn't mention a filter condition on the alerts, I tried something like this:
```
var trigger = data
    |alert()
        .crit(lambda: "value" < crit)
        .message(message)
        .id(idVar)
        .idTag(idTag)
        .levelTag(levelTag)
        .messageField(messageField)
        .durationField(durationField)
        .details(details)
        .email()
    |where(lambda: "Level" != 'CRITICAL')
        .to('robomotic@gmail.com')

```
But it doesn't like to break the alert with the where condition:

invalid TICKscript: line 59 char 10: no method or property "to" on *pipeline.WhereNode

Any help appreciated.

**Comment by russorat** [comment]
@robomotic i just re-read your original message. I think what you might be looking for it `stateChangesOnly()` option: https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/#statechangesonly

Adding that to your `alert()` node should only send you emails when you go from OK -> CRIT for example.

**Comment by robomotic** [comment]
Yes I did try that but unfortunately those transitions could happen regularly in my case like 5 times a day and so would like to be able to see only critical is possible.
I am wondering if this would be a better approach?
1. Write a TICK stream script just to process the equal condition and output into a measurement (with say 24h retention)
2. Use the alert on this new measurement, which by definition will only create critical alerts

Cheers.

**Comment by russorat** [comment]
@robomotic so if you get 5 crits in a day, you don't want to be notified when each of them is resolved? From CRIT -> OK? 

You can do that using event handlers in Kapacitor. We don't see that pattern very often, but setting an event handler with a match expression option should do the trick.  https://docs.influxdata.com/kapacitor/v1.5/event_handlers/ . https://docs.influxdata.com/kapacitor/v1.5/working/alerts/#match-expressions

**Comment by robomotic** [comment]
Oh that is great I totally missed it,I will try it tomorrow.

**Comment by timhallinflux** [comment]
@robomotic I'm going to close out this issue since we haven't heard from you.  Please reach back out if you need something. I believe your questions was more about how to structure the Kapacitor TICKscript itself...and not an issue about Chronograf specifically (although you were using the TICKscript editor within Chronograf to explore this functionality).

You could also engage in more how-to questions via https://community.influxdata.com or via our community slack, if you are a slack user!  Thanks!!
