### ISSUE TITLE
Slow refreshes in Log Viewer

### ISSUE THREAD

**Issue by odalet** [influxdata/chronograf#5434]
This is a follow-up to issue #5201 as I suppose that opening a new issue may help it gain some traction. 

So, like other users, I observed really slow refreshes when opening or modifying settings in the Log Viewer panel.  I did a bit of exploration in the code and noticed that data was fetched by chunks of 30s here:

https://github.com/influxdata/chronograf/blob/d61b03f27a76ac59b79231e1057b56b22a9be576/ui/src/logs/constants/index.ts#L213-L216

That probably partly explains the bombing of requests that surely slow the refresh process. Is this 30s duration by design? Can't it be increased?

Another weird behavior is that the refresh process does not seem to honor the settings the user entered (unless I don't understand how it should work). In the example below, I wanted to retrieve logs  with severity **info** starting from **now** and for **1mn** back only (m is minute, not month?). Apparently the period is extended far more back in time. Why is that so?

![image](https://user-images.githubusercontent.com/79333/78113819-97927000-7400-11ea-8dd2-97a0d16ec032.png)

NB: 
* For these tests I'm using Chronograf 1.8 as part of the TICK sandbox on a Windows host.
* I also noticed minor code quality issues in https://github.com/influxdata/chronograf/blob/master/ui/src/types/logs.ts: there are duplicated type definitions and an invalid import (for it imports a type defined in the very same file) -> Issue #5435, PR #5436

**Comment by russorat** [comment]
@odalet thanks for the issue. The multiple time ranges on this page are not very clear what they are impacting. Basically, the top one only changes the range of the histogram at the top, and the second one jumps backward in time to a specific point, which you can then scroll forward or backward in time.

I'm not sure how those variables impact the refresh rate of the app, but we can investigate. We'd be happy to accept a PR for making the log viewer more performant.

**Comment by odalet** [comment]
@russorat Thanks for your involvement in this issue. I might have a deeper look into this; however, I'm not that an expert in TS/React/Go dev. Given I find some time, I'll still try to conduct some experiments.

On a side note, I managed to get far better performance (though less appealing visual) by crafting a simple hand made dashboard based on the same data. Hence, the perf issue is clearly a frontend thing: 
[chronograf-logs-dashboard.json.txt](https://github.com/influxdata/chronograf/files/4473705/chronograf-logs-dashboard.json.txt)

**Comment by geniousphp** [comment]
I'm not sure if my issue is related to this one, but I noticed too much requests to my influxdb because the log viewer is trying to fetch the logs history by bucket of 30s

Here is a sample of request
```
ts=2020-05-22T15:46:11.690983Z lvl=info msg="Executing query" log_id=0MvQ2ZpW000 service=query query="SELECT severity AS severity, timestamp AS timestamp, message AS message, facility AS facility, procid AS procid, appname AS appname, hostname AS hostname, host AS host FROM fluentbit.autogen.syslog WHERE time >= '2020-05-21T19:32:44.423Z' AND time < '2020-05-21T19:33:14.423Z' ORDER BY time DESC"
ts=2020-05-22T15:46:11.929540Z lvl=info msg="Executing query" log_id=0MvQ2ZpW000 service=query query="SELECT severity AS severity, timestamp AS timestamp, message AS message, facility AS facility, procid AS procid, appname AS appname, hostname AS hostname, host AS host FROM fluentbit.autogen.syslog WHERE time >= '2020-05-21T19:32:14.423Z' AND time < '2020-05-21T19:32:44.423Z' ORDER BY time DESC"
ts=2020-05-22T15:46:12.191828Z lvl=info msg="Executing query" log_id=0MvQ2ZpW000 service=query query="SELECT severity AS severity, timestamp AS timestamp, message AS message, facility AS facility, procid AS procid, appname AS appname, hostname AS hostname, host AS host FROM fluentbit.autogen.syslog WHERE time >= '2020-05-21T19:31:44.423Z' AND time < '2020-05-21T19:32:14.423Z' ORDER BY time DESC"
ts=2020-05-22T15:46:12.498971Z lvl=info msg="Executing query" log_id=0MvQ2ZpW000 service=query query="SELECT severity AS severity, timestamp AS timestamp, message AS message, facility AS facility, procid AS procid, appname AS appname, hostname AS hostname, host AS host FROM fluentbit.autogen.syslog WHERE time >= '2020-05-21T19:31:14.423Z' AND time < '2020-05-21T19:31:44.423Z' ORDER BY time DESC"
```

**Comment by fubhy** [comment]
I am experiencing the same issue. The browser is making close to 100 requests per second to fetch more logs. This definitely seems to be a frontend issue.

**Comment by e97317** [comment]
Hi again @russorat 

I did move my logs to chronograf and find it very cool to use, however, in the background, things seem a bit under optimized. 
I do see 100s of request sent to influx, exactly what is described by @geniousphp.... but, in my case, it goes back many hours back (actually it never stops sending request 30sec backward).

Even if i choose "last 5min" as you can see in my screen, I see chronograf requesting data back to many hours backward. You can even see that some lines (older than 5mins) are displayed.

![bug2](https://user-images.githubusercontent.com/64333014/100870805-845c0680-349f-11eb-8a93-7f5a7afd3819.png)

Here is also an example of request done by chronograf where you can see the time of the request and the time range requested (way outside the 5minutes).

**2020-12-02T12:05:56.838678Z**     info      Executing query {"log_id": "0Qp8OVgl000",   "service": "query", "query": "SELECT severity   AS severity, timestamp AS timestamp, message AS message, facility AS   facility, procid AS procid, appname AS appname, hostname AS hostname, host AS   host FROM telegraf.autogen.syslog WHERE time >= '**2020-12-02T05:23:20.668Z**'   AND time < '**2020-12-02T05:23:50.668Z**' ORDER BY time DESC"}
--

Let me know if you need more details. Thanks

**Comment by sranka** [comment]
this is still reproducible with 1.8.9 ... it is a pure UI issue that requires deeper investigation

**Comment by sranka** [comment]
There are two **independent** components on the Logs page, a histogram chart and a logs table.

The histogram part visualizes a summary of log data types for the last user-selected interval with its upper bound being the current time.

The logs table show particular Syslog measurements around user-selected time. Initially, it tries to load 1000 measurements fotr the last 30 seconds. If there is no enough data, it extends the interval (to the past by 30 seconds) and tries again. It can thus fetch empty chunks in an infitine loop until some data are available.

**Comment by sranka** [comment]
I used the following script to better control data load frequency to syslog measurement:

```
#!./node_modules/.bin/ts-node
import {ClientOptions, InfluxDB, Point} from '@influxdata/influxdb-client'
const username = 'admin'
const password = 'changeit'
const database = 'telegraf'
const retentionPolicy = 'autogen'
const bucket = `${database}/${retentionPolicy}`

const clientOptions: ClientOptions = {
  url: 'http://localhost:8086',
  token: `${username}:${password}`,
}

const influxDB = new InfluxDB(clientOptions)
const writeAPI = influxDB.getWriteApi('', bucket, 'ns', {maxBufferLines: 2})

function writeData(date = new Date()): void {
  const timestamp = date.getTime() * 1000000
  const point = new Point('syslog')
    .tag('appname', 'myapp')
    .tag('facility', 'console')
    .tag('host', 'myhost')
    .tag('hostname', 'myhost')
    .tag('severity', 'warning')
    .stringField('message', 'warning message here')
    .floatField('facility_code', 14)
    .floatField('severity_code', 4)
    .intField('procid', 12345)
    .intField('timestamp', timestamp)
    .floatField('version', 1)
    .timestamp(date)
  writeAPI.writePoint(point)
}

;(async function infiniteLoop(): Promise<void> {
  for (;;) {
    const date = new Date()
    console.log('writeData ', date)
    writeData(date)
    await new Promise(resolve => setTimeout(resolve, 1000))
  }
})()

function onExit(exitCode: number): void {
  writeAPI
    .close()
    .then(() => console.log('FINISHED'))
    .catch(error => {
      console.error(error)
    })
    .finally(() => {
      console.log('EXIT')
      process.exit(exitCode)
    })
}
process.on('exit', onExit)
process.on('SIGINT', onExit)
```
