### ISSUE TITLE
Alerts and scripts in the Chronograf admin panel disappeared

### ISSUE THREAD

**Issue by evgmoskalenko** [influxdata/chronograf#5437]
In the Chronograf admin panel disappeared alerts and alerts scripts

**Main Status page**

![chronograf_1](https://user-images.githubusercontent.com/7605506/78244403-3052e980-74ee-11ea-8544-21486ef35426.jpg)

**Alerting -> Manage Tasks**

![chronograf2](https://user-images.githubusercontent.com/7605506/78244405-321cad00-74ee-11ea-881d-4c54df024030.jpg)

**Alerting -> Alert History**

![chronograf_3](https://user-images.githubusercontent.com/7605506/78244863-1cf44e00-74ef-11ea-9828-2dcb1c70330b.jpg)

Could you tell me please what to be the reason?

**Versions:**
- Chronograf: 1.6.1
- Kapacitor: 1.5

**Comment by russorat** [comment]
@evgmoskalenko thanks! could you upgrade to the latest chronograf and see if the issue persists?

**Comment by sranka** [comment]
It can happen with a broken connection to kapacitor (from chronograf server). The newer chronograf versions shows this error notification:

![image](https://user-images.githubusercontent.com/16321466/122720997-6d7cd600-d270-11eb-9c0d-a2d541151ecc.png)

and also log the full error to the browser console.
