### ISSUE TITLE
Table views not displaying results correctly in 1.8.1

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5441]
Looks like the table graphs are only displaying one line of data, even though multiple lines are returned.

pinged offline with more context.

![image](https://user-images.githubusercontent.com/4805997/78709389-69150900-78c8-11ea-9ce9-44ac3dd96071.png)

**Comment by desa** [comment]
@russorat is this an instance of https://github.com/influxdata/chronograf/issues/4825
