### ISSUE TITLE
Remote Host Status not enabled on Host Lists/chronograf 

### ISSUE THREAD

**Issue by mkbahk** [influxdata/chronograf#5444]
Hi, guys.
I have installed influxdb, telegraf, chronograf and kapacitor multiple times to monitor our systems. This time I installed them on centos 7 and I had a problem where the status of remote hosts was not enabled in Host lists. Local host with influxdb install is enabled. Most of the default settings were used without modification. What parts should I check?

![host list](https://user-images.githubusercontent.com/30949880/79026410-b7c1ec00-7bc3-11ea-943d-9172cad75342.JPG)

=============================================
//Version installed
influxdb-1.7.10
chronogra-1.8.0
kapacitor-1.5.4-1
telegraf-1.14.0-1

=============================================
//uname-a
Linux deployer200 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

=============================================
//systemctl status influxdb  
Every 1.0s: systemctl status influxdb                                                                                                                                                                                                     Sat Apr 11 16:07:08 2020

● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-04-11 06:19:12 KST; 9h ago
     Docs: https://docs.influxdata.com/influxdb/
 Main PID: 233297 (influxd)
   CGroup: /system.slice/influxdb.service
           └─233297 /usr/bin/influxd -config /etc/influxdb/influxdb.conf

Apr 11 16:07:00 deployer200 influxd[233297]: [httpd] 101.55.53.200 - - [11/Apr/2020:16:07:00 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 09b785fc-7bc3-11ea-9465-f0d4e2e855d8 8786
Apr 11 16:07:04 deployer200 influxd[233297]: [httpd] 101.55.53.201 - - [11/Apr/2020:16:07:04 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0c48169d-7bc3-11ea-9466-f0d4e2e855d8 1296
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.206 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e11f498-7bc3-11ea-9468-f0d4e2e855d8 6485
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.204 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e11dce1-7bc3-11ea-9467-f0d4e2e855d8 7413
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.208 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e120c47-7bc3-11ea-946b-f0d4e2e855d8 6767
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.207 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e11f993-7bc3-11ea-9469-f0d4e2e855d8 9086
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.205 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e120541-7bc3-11ea-946a-f0d4e2e855d8 9175
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.203 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e1269c8-7bc3-11ea-946c-f0d4e2e855d8 7640
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.202 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e127c36-7bc3-11ea-946d-f0d4e2e855d8 10823
Apr 11 16:07:07 deployer200 influxd[233297]: [httpd] 101.55.53.209 - - [11/Apr/2020:16:07:07 +0900] "POST /write?db=telegraf HTTP/1.1" 204 0 "-" "Telegraf/1.14.0" 0e134bef-7bc3-11ea-946e-f0d4e2e855d8 7310

=============================================
// systemctl status telegraf of Remote Hosts
Every 1.0s: systemctl status telegraf                                                                                                                                                                                                     Sat Apr 11 07:10:27 2020

● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/usr/lib/systemd/system/telegraf.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-04-11 06:54:01 KST; 16min ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 145650 (telegraf)
   CGroup: /system.slice/telegraf.service
           └─145650 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

Apr 11 06:54:01 controller201 systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Starting Telegraf 1.14.0
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Loaded inputs: net netstat diskio processes system mem swap cpu disk kernel
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Loaded aggregators:
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Loaded processors:
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Loaded outputs: influxdb
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! Tags enabled: dc=kr-seoul-kdt host=controller201 rack=2A-1B
Apr 11 06:54:01 controller201 telegraf[145650]: 2020-04-10T21:54:01Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"controller201", Flush Interval:10s

![host list2](https://user-images.githubusercontent.com/30949880/79026427-c7413500-7bc3-11ea-8525-834f98795f2a.JPG)
[telegraf.conf.txt](https://github.com/influxdata/chronograf/files/4463576/telegraf.conf.txt)
[influxdb.conf.txt](https://github.com/influxdata/chronograf/files/4463577/influxdb.conf.txt)

**Comment by russorat** [comment]
@mkbahk thanks for the issue. That "dot" is populated from the following query for deltaUptime:
https://github.com/influxdata/chronograf/blob/master/ui/src/hosts/apis/index.ts#L55

https://github.com/influxdata/chronograf/blob/master/ui/src/hosts/components/HostRow.tsx#L21

It shouldn't have anything to do with local or remote hosts.

**Comment by timhallinflux** [comment]
@mkbahk just going through old issues here.  Did this resolve itself once those hosts reported in? or is this still a problem?
