### ISSUE TITLE
Chronograf error while "SHOW DATABASES"

### ISSUE THREAD

**Issue by Redblueflame** [influxdata/chronograf#5445]
Hi,
I currently have a problem with Chronograf and influxdb.
Seems like the link between InfluxDb and Chronograf is not working, as when going to the explore page, I'm getting this; 
![Screenshot](https://i.imgur.com/hD9qhBZ.png)
So no database displayed, but using the `influx` cli tool, I get that:
```
Connected to https://localhost:8086 version 1.7.10
InfluxDB shell version: 1.7.10
> SHOW DATABASES
name: databases
name
----
_internal
telegraf
```
Also, when I type a premade query, everything is stuck at a loading state, same for a predefined panel.

Note: In the InfluxDB logs, I still have the request appearing:
```
2020-04-13T17:00:50.769818Z     info    Executing query {"log_id": "0M96NzBl000", "service": "query", "query": "SHOW DATABASES"}
[httpd] 62.210.209.15 - telegraf_backup [13/Apr/2020:19:00:50 +0200] "POST /query?db=&epoch=ms&q=SHOW+DATABASES&rp= HTTP/1.1" 200 118 "-" "Go-http-client/1.1" 5421bc26-7da8-11ea-80af-d4ae52c72e18 659
```
But nothing appears on the panel.

**Versions**
Chronograf Version: 1.7.17
InfluxDB Version 1.7.17
Telegraf Version 1.14.0
OS: Debian 10 x64

**Comment by russorat** [comment]
@Redblueflame do you have auth turned on for influxdb?

**Comment by Redblueflame** [comment]
Hi @russorat !
Yes it is activated, and I filled the credentials in chronograf.
I forgot to mention that I use oauth2 with auth0 for authorization.

**Comment by timhallinflux** [comment]
@Redblueflame did you figure this out??

**Comment by sranka** [comment]
Works fine in Chronograf 1.8.9
