### ISSUE TITLE
Unable to get login screen using OAuth

### ISSUE THREAD

**Issue by kristinnardal2** [influxdata/chronograf#5447]
I am trying to set up OAuth for chronograf together with an Azure AD. I have followed the instructions to set it up from the [documentation](https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/#configure-azure-active-directory-authentication) to set this up and have seen that the environment variables are set properly.

The problem I have is that I never get to a login screen, I always go straight to the setup of sources. I have also tried setting `USE_TOKEN_ID` and `JWKS_URL` but it seems that no matter what I do I can't get the option to log in.

Am I missing some crucial step or have I just misconfigured it?

Currently I am setting these environment variables as following:
```bash
GENERIC_API_KEY=userPrincipalName
GENERIC_API_URL=https://graph.windows.net/<<tenant-id>>/me?api-version=1.6
GENERIC_AUTH_URL=https://login.microsoftonline.com/<<tenant-id>>/oauth2/authorize?resource=https://graph.windows.net
GENERIC_CLIENT_ID=<<client-id>>
GENERIC_CLIENT_SECRET=<<client-secret>>
GENERIC_NAME=AzureAD
GENERIC_SCOPES=openid
GENERIC_TOKEN_URl=https://login.microsoftonline.com/<<tenant-id>>/oauth2/token
JWKS_URL=https://login.microsoftonline.com/<<tenant-id>>/discovery/v2.0/keys
TENANT=<<tenant-id>>
TOKEN_SECRET=<<token-secret>> # generated with openssl
USE_ID_TOKEN=true
```

**Comment by russorat** [comment]
@kristinnardal2 thanks! I think you might be missing `export PUBLIC_URL=http://localhost:8888`? Everything else looks right.

**Comment by kristinnardal2** [comment]
@russorat I added `PUBLIC_URL=http://localhost:8888` and I still don't get to the login screen.

I have now tried using the same options but using flags instead of environment variables for all possible values and I get a login screen. There might be a bug with the environment variables not being used correctly.

**Comment by kristinnardal2** [comment]
I found the issue, `GENERIC_TOKEN_URL` had a lowercase `l` at the end.
