### ISSUE TITLE
Chonograf should fail to start if OAuth is partially configured

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5451]
as a user
when I set one or more of an authentication option for OAuth, but I fail to set all the correct variables,
then chronograf should refuse to start.

a specific example here is:
https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#github-specific-oauth-2-0-authentication-options

I set `--github-client-id` but fail to set `--github-client-secret`, then chronograf should fail to start.

**Comment by rbetts** [comment]
https://github.com/influxdata/chronograf/issues/5450

Closing as dupe.
