### ISSUE TITLE
Token subcommand is not available in chronoctl

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5454]
In the 1.8.2 release, we see that there was no `token` subcommand in `chronoctl`. This is particularly confusing since the code is there.

**Comment by glinton** [comment]
Found that this was caused by https://github.com/influxdata/chronograf/commit/6d6f36cfbcc01ffa01349bfa7ce5483935178863#diff-be314c62342f48850f48f1af424840c8R28 and not caught because we are ignoring the errors returned by the `AddCommand` call.
