### ISSUE TITLE
Chronograf (1.8.0) Dashboard table graph sorting

### ISSUE THREAD

**Issue by Cubone21** [influxdata/chronograf#5457]
When there is a dashboard with a table graph created, there is a problem with sorting in the table graph. The sorting is set to ascending by time by default. When the sorting is changed to either ascending or descending on any of the parameters in the table, it holds only up to the next refresh of the table, then it returns back to the default sorting.

![Screenshot 2020-04-21 at 08 49 50](https://user-images.githubusercontent.com/62006131/79834301-2154ae00-83ad-11ea-8ea6-dd69d57ecff6.png)

**Comment by ehujdur** [comment]
Also experiencing this in my project.

**Comment by geniousphp** [comment]
I confirm this issue with 1.8 version. Also, I can't set the ordering in the query. For example, when I add `ORDER BY time DESC`, it doesn't take effect even though it take effect when I run it directly via Influx CLI

**Comment by sranka** [comment]
I was using the following instructions to better reproduce this issue.
1. I was using [influxdb-client-js](https://github.com/influxdata/influxdb-client-js) write examples to seed some data

2. Tried the following queries
flux:
```
from(bucket: "my-bucket")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "temperature")
  |> group(columns: ["_measurement"], mode:"by")
  |> sort(columns: ["_time"], desc: false)
```

influxql:
```
SELECT * FROM "my-bucket"."autogen"."temperature" WHERE time > :dashboardTime: AND time < :upperDashboardTime: ORDER BY time DESC
```
3. Both queries return in the order of the query on the wire
4. Table chart always display data independently on query sorting -> this defect

**Comment by sranka** [comment]
There are actually more issues/side-effects related to table sorting (in the current master branch)
  1. If you edit the table and select custom sorting, the table soon gets refreshed with default sorting ... pausing the refresh helps
  1. Even if you pause the data refresh, the table options are not saved properly after you save it
  1. The stored table options does not seem to store ordering at all, only field

**Comment by thevlab** [comment]
The issue is still there. Any method to change the sorting to descending ?

**Comment by sranka** [comment]
@thevlab Can you please post a new defect with the exact instructions on how to reproduce it?
