### ISSUE TITLE
Add pagination to tasks page

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5460]
currently we fetch all the tasks the are available in kapacitor. For instances with large numbers of tasks this can take quite a bit of time. We should add some kind of pagination to allow for these types of operations.

**Comment by vfcastro** [comment]
It would be great. Currently, we have 2000+ tasks in Kapacitor, and the Chronograf page takes more than one minute to load.
Having a search field in that page would be also very conveniet, considering pagination.

**Comment by sranka** [comment]
The 1.8.10 implementation indeed gets all the tasks in a single request and shows them in a _TICKScripts_ section. The TICKScripts that are also recognized (by chronograf server) as Alert Rules are displayed with additional details in a separate _Alert Rules_ section. #5663 also demands a new flux rule to manage consider herein. 

Simple pagination is possible on the kapacitor side (https://docs.influxdata.com/kapacitor/v1.5/working/api/#tasks), filtering is however not implemented. A combination of paging and filtering would not be optimal to emulate in chronograf. We also have to think over UX with pagination and filtering, the 2 (3 with flux) tables will not look well.

**Comment by sranka** [comment]
I believe that an acceptable solution might be:
- display at most 100 tasks when the page is opened
- if there are more than 100 tasks, inform the user that the result is truncated ... and offer a link to show all of them
- add a filter to the top of the page to show tasks containing a specific string in the TICKscript body.

Chronograf server parses all the TICKscripts to determine whether they are also chronograf rules, this is IMHO the reason of why it takes more than a minute to load 2000+ kapacitor tasks. I will have to prove that my opinion is true, before coming up with a solution.

**Comment by sranka** [comment]
I saved a sample chronograf rule to a _tickscript.txt_ file and created >2000 tasks:
```
for i in test-{000..2199}
do
  sed "s/Slack/$i/" tickscript.txt > tickscript.last
  kapacitor define $i -tick tickscript.last -type stream -dbrp "telegraf"."autogen"
done
```
It then took 66 seconds to get the tasks to chronograf UI. 54 seconds (24.5ms per rule) were spent in the chronograf server to recognize whether each particular task is a chronograf rule, 12 seconds (5.5ms per rule) were spent in kapacitor. 

The proposed solution will improve the situation in the following way:
- the first page can be returned in 3 seconds ((24.5+5.5)*100 ms)
   - no filter is used, kapacitor is instructed to return only the first 100 tasks
   - **5%** of the original time
- it takes at most 14.5 seconds when a filter is used
   - all tasks are read (12 seconds) + filter is applied + at most 100 tasks are parsed (2.5 seconds)
   - **21%** of the original time

**Comment by timhallinflux** [comment]
I would go with this:
```the first page can be returned in 3 seconds ((24.5+5.5)*100 ms)
no filter is used, kapacitor is instructed to return only the first 100 tasks
5% of the original time```

@russorat ?

**Comment by sranka** [comment]
#5871 adds TICKscripts page that performs much better, it is paginated and allows filtering. #5872 further ensures that the old `Alert Rules` is no longer necessary to manage kapacitor's alert rules.

**Comment by sranka** [comment]
The existing alert rules page remains in chronograf. We can decide to remove it in the next version.
