### ISSUE TITLE
CentOS & Debian repo outdated for Chronograf & Kapacitor

### ISSUE THREAD

**Issue by nsteinmetz** [influxdata/chronograf#5470]
Hello,

Chronograf 1.8.x and Kapacitor 1.5.5 are not available on CentOS 7 and Debian 10 repositories :

* https://repos.influxdata.com/rhel/7Server/x86_64/stable/
* https://repos.influxdata.com/debian/dists/buster/stable/binary-amd64/Packages

Could you please update it ? For deployment it's easier to rely on CentOS/Debian repo than to fetch binary and deploy it ;-)

Thanks !

**Comment by russorat** [comment]
@nsteinmetz thanks for the nudge. I've opened prs to address this. They should show up in the next few days.

**Comment by nsteinmetz** [comment]
hi @russorat 

any news on this topic ?

Repos (at least Debian) is still not updated.

**Comment by russorat** [comment]
@nsteinmetz sorry, i'm following up to see what's taking so long here.

**Comment by russorat** [comment]
these packages have been added to repos.influxdata.com! thanks!

**Comment by nsteinmetz** [comment]
Thanks @russorat :+1:

**Comment by danielsreichenbach** [comment]
Sorry for yanking on the coffin but it looks like packages on <https://repos.influxdata.com> are not updating again. Currently this affects Chronograf where only version 1.8.4 is in the repo but that has a bug breaking any installation using OAuth, and 1.8.5 is not in the repos.
