### ISSUE TITLE
Chronograf (1.8.2) Log viewer does not fall back to point timestamp

### ISSUE THREAD

**Issue by richjyoung** [influxdata/chronograf#5472]
When viewing the logs in the log viewer where some entries do not specify a timestamp field, the timestamp column shows 01/01/1970, despite the log entries being ordered correctly based on the point time. Filtering with the graph still works, this seems to just be an issue with that column.

I use the tail input plugin with grok patterns to extract log events from formatted output, which does not insert a valid numeric timestamp field.

**Comment by russorat** [comment]
@richjyoung thanks! looking at this for the next release.
