### ISSUE TITLE
oauth validation broken

### ISSUE THREAD

**Issue by benschweizer** [influxdata/chronograf#5473]
PR#5458 introduced some oauth sanity checks which result in a failure:
```
ERRO[0000] Failed to validate Oauth settings: missing Google oauth setting[s]: client id, client secret  basepath=invalid component=server
```

I'm using GenericOAuth2 instead of GoogleOAuth, but both use the variable PublicURL.
Now, with the checks of PR#5458 (https://github.com/influxdata/chronograf/pull/5458/files#diff-91bbeda7eb98a7adc57b9e47e2cf5c2bR167), the GoogleOAuth providers gets activated and fails because of missing parameters:

````
	if s.TokenSecret != "" && s.GoogleClientID != "" && s.GoogleClientSecret != "" && s.PublicURL != "" {
		return nil
	} else if s.GoogleClientID == "" && s.GoogleClientSecret == "" && s.PublicURL == "" {
		return errNoAuth
	}
```

The check for PublicURL should probably be removed?

**Comment by glinton** [comment]
@benschweizer can you post your obfuscated configuration and the full output of that log.

**Comment by glinton** [comment]
Was able to reproduce, adding fix.

**Comment by glinton** [comment]
@nickidw I've reached out to learn more about the 1.8.5 release that would fix that issue. In the meantime, would it be possible to use the [nightly build](https://portal.influxdata.com/downloads/)

**Comment by nickidw** [comment]
I'm ok at the moment thanks, it's working on 1.7.17. If I experience errors I'll think about going to nightly build.
