### ISSUE TITLE
 Chronograf (1.8.4) n is undefined

### ISSUE THREAD

**Issue by kunom** [influxdata/chronograf#5474]
What browser are you using (name and version)?
Firefox 76.0

What operating system are you using?
Windows 10

Please describe what you were trying to do when you encountered this error:
I tried to switch a dashboard.

```
r@http://ha:4288/src.bb6c33a8.js:1824:429
value/<@http://ha:4288/src.bb6c33a8.js:4234:11871
mi@http://ha:4288/src.bb6c33a8.js:717:73830
hi@http://ha:4288/src.bb6c33a8.js:717:74057
ja@http://ha:4288/src.bb6c33a8.js:717:64606
$a@http://ha:4288/src.bb6c33a8.js:717:69008
oo@http://ha:4288/src.bb6c33a8.js:717:91057
uo@http://ha:4288/src.bb6c33a8.js:717:91442
Yo@http://ha:4288/src.bb6c33a8.js:717:98524
$o@http://ha:4288/src.bb6c33a8.js:717:97906
eu@http://ha:4288/src.bb6c33a8.js:717:99279
Mn@http://ha:4288/src.bb6c33a8.js:717:30667

```

**Comment by russorat** [comment]
@kunom thanks! were you able to get around this error or is it still happening?

**Comment by kunom** [comment]
@russorat Well, it happened again a few times, but no more since then.

It could have been a caching/partial reload issue where the frontend still ran 1.8.2 while switching the dashboard, but the backend already was lifted to 1.8.4.

**Comment by sranka** [comment]
`n is undefined` means that `activeDashboard === undefined` in
https://github.com/influxdata/chronograf/blob/15bf39703f3ed0b3ef439fe39eb943836d557573/ui/src/dashboards/utils/dashboardSwitcherLinks.ts#L30 

it is called from the DashboardPage, where it indicates that the dashboard definition is not yet available
