### ISSUE TITLE
Chronograf (1.8.4) Error in Flux when viewing raw data

### ISSUE THREAD

**Issue by Cubone21** [influxdata/chronograf#5476]
Creating new graph in a dashboard. Trying to view raw data in the flux editor. 

Tried:
from(bucket: "telegraf")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r.cpu == "cpu-total")

result: a table with data is visible

Then added a filter from another bucket:
from(bucket: "telegraf")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r.cpu == "cpu-total")
  |> filter(fn: (r) => r.level == "CRITICAL")

result: “No results”

Then deleted the new filter so the script is the same as before:
from(bucket: "telegraf")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r.cpu == "cpu-total")

result: UNEXPECTED ERROR - “A Chronograf error has occurred. Please report the issue“

After that it is no more possible to create any table with raw data and the View raw data switch has to be switched off and on to make it work again.

**Comment by russorat** [comment]
@Cubone21 thanks for the issue. We will investigate.
