### ISSUE TITLE
Unicode Escaping of Dashboards

### ISSUE THREAD

**Issue by jjathman** [influxdata/chronograf#5477]
We put our dashboards in to source control and to migrate them between environments we put them in the `/usr/share/chronograf/resources` folder of the server. In general this has worked fine, however if the query contains a `<` or `>` character (which is quite common) the dashboards will be broken as it seems to render these characters escaped as `&lt;` or `&gt;`. When looking at what Chronograf does on it's own I see that these characters get escaped as Unicode characters like `\u003c`. Can you help me understand why this is necessary? I wouldn't expect the need to escape these characters in JSON like this.

At the time we came up with this setup there was not a way of updating dashboards via the API, I see that does exist now but we would like to be able to use our existing automation if possible. Thank you!

**Comment by russorat** [comment]
@jjathman thanks for the issue. i'm not sure the background of why we use the `\u003c` format. 

Seems like a bug in how we interpret the dashboards IMO. Probably being a little aggressive

**Comment by sranka** [comment]
The dashboard files are processed as HTML templates using https://golang.org/pkg/html/template/ , environment variables are replaced in the template. The implementation (code of dashboard loading) must be changed to use https://golang.org/pkg/text/template/ .
