### ISSUE TITLE
consider uPlot instead of dygraphs

### ISSUE THREAD

**Issue by leeoniya** [influxdata/chronograf#5479]
Hey guys,

i was a dygraphs user for some time and submitted https://github.com/danvk/dygraphs/pull/948 to reduce the lib size, but it appears that dygraphs is no longer maintained. i decided to write an alternative in the same spirit and it turned out to be quite successful:

https://github.com/leeoniya/uPlot#performance

browsing some issues & feature requests in this repo, there seem to be quite a few that could be resolved by switching.

cheers!
Leon

cc @glinton @alexpaxton @hoorayimhelping @121watts @desa @ebb-tide

**Comment by russorat** [comment]
@leeoniya thanks for opening this and for the new library. we are leveraging the https://github.com/influxdata/giraffe library for graphs in our next version. maybe that is something we can collaborate and improve on or figure out a way to leverage your library in a new graph type. we don't have plans to change the graphing capability of chronograf right now.

**Comment by leeoniya** [comment]
sounds good, thanks!
