### ISSUE TITLE
Bool values are not shown on "Editor + Logs" tab in TickScript Editor

### ISSUE THREAD

**Issue by Pavel-Egorov** [influxdata/chronograf#5481]
When I open TickScript Editor and enable Editor + Logs tab if I have fields with boolean values then I cannot see value itself (just field name without value).

Chronograf version - 1.8.0
Browser - Google Chrome, 81.0.4044.138, Mac OS

**Comment by russorat** [comment]
@Pavel-Egorov thanks for reporting. looks like a bug on our side. if you want to submit a PR, we will take a look. Otherwise, we will look at it for the next release.

**Comment by Pavel-Egorov** [comment]
I think that I have no enough context, so I will wait for the next release. Thank you for reaction!

**Comment by sranka** [comment]
@Pavel-Egorov - I tried to reproduce this with Chronograf 1.8.5. Boolean variables are visible in the TickScript editor, Logs are visible as well. I am not sure what you mean by fields herein. Can you please be more specific where you expect the fields to be shown, a screenshot would help.

**Comment by Pavel-Egorov** [comment]
![image](https://user-images.githubusercontent.com/11914524/89284794-f8081700-d657-11ea-9aba-572461b77af2.png)

As you can see on attached screenshot values of "test" field aren't shown in Logs. I expect to see smth like "test: TRUE" there.

**Comment by sranka** [comment]
I see, thank you @Pavel-Egorov
