### ISSUE TITLE
Chronograf (1.8.4) "missing Google oauth setting" when not using Google

### ISSUE THREAD

**Issue by DouglasHeriot** [influxdata/chronograf#5482]
I use the Docker container with environment variables to specify configuration. I've been using OAuth against Okta successfully for a few months now.

I just updated from Chronograf 1.8.2 to 1.8.4. The container did not start properly, and logged:
```
level=error msg="Failed to validate Oauth settings: missing Google oauth setting[s]: client id, client secret" basepath=invalid component=server
```

It looks like this is related to #5481. I haven't yet had time to step through the logic and work out why it's giving me errors about Google.

Here are the environment variables I'm passing in:
```
PUBLIC_URL: "https://chronograf"
TOKEN_SECRET: "XXXX"
GENERIC_NAME: Okta
GENERIC_CLIENT_ID: "XXXX"
GENERIC_CLIENT_SECRET: "XXXX"
GENERIC_SCOPES: "openid,profile,email"
GENERIC_DOMAINS: example.com
GENERIC_AUTH_URL: "https://example.okta.com/oauth2/v1/authorize"
GENERIC_TOKEN_URL: "https://example.okta.com/oauth2/v1/token"
GENERIC_API_URL: "https://example.okta.com/oauth2/v1/userinfo"
```

**Comment by glinton** [comment]
If possible, use a nightly build, this was resolved in #5475  and is scheduled for the 1.8.5 release. Sorry for the inconvenience
