### ISSUE TITLE
Chronograf 1.8.0 Github Organizations support for Github Enterprise Organization

### ISSUE THREAD

**Issue by lt3215** [influxdata/chronograf#5483]
Hi folks,

I'm currently trying to stand up Chronograf in an enterprise environment and am trying to figure out how to set up verification of a user's organization. We are using Github with an enterprise domain, i.e. github.<company>.com and so had to use the GENERIC provider.

Is there a way to use GH_ORGS in combination with a GENERIC provider?

**Comment by russorat** [comment]
@lt3215 thanks for the issue. this user was able to get it working using the config: https://github.com/influxdata/chronograf/issues/4085#issuecomment-492276993

can you try that and let us know if it works?

**Comment by lt3215** [comment]
Thank you for responding @russorat 
I was able to get the authentication itself working.
The issue that I wanted to figure out was how to apply the check for a user's organization (via $GH_ORGS) since it is only using the GENERIC provider.
I have a similar setup to the one in that post, but that post does not appear to use GH_ORGS for added authorization.

**Comment by sranka** [comment]
#4085 shows an an example of a generic provider that works fine

**Comment by sranka** [comment]
@lt3215 the next chronograf 1.9 version can use [GitHub OAuth configuration]( https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/#configure-github-authentication) + GH_URL environment variable (or `--github-url` option) with your GitHub Enterprise URL (`https://github.domain.io`).

You can give it a try with chronograf nightly builds.
