### ISSUE TITLE
Log Viewer doesn't work in Firefox

### ISSUE THREAD

**Issue by ForsakenHarmony** [influxdata/chronograf#5484]
Was trying to figure out for at least 30 mins why my syslog input wasn't showing up

![](https://i.hrmny.sh/Qn6aiYx1WR.png)

Then opened it in chrome after seeing in issue about Opera incompatibility, which loaded fine first try

![](https://i.hrmny.sh/i8t2eE8b78.png)

Using [this version](https://hub.docker.com/layers/chronograf/library/chronograf/alpine/images/sha256-7b9fd4bfa461dd588069a6662e7a23eec428fbd0ed24382e7a80ec2dacbea40a?context=explore)

Sadly don't have any logs in the browser, Firefox just seems to fail loading, I'm guessing you catch the error internally somewhere

**Comment by russorat** [comment]
@ForsakenHarmony thanks for reporting. we usually recommend using the latest chrome, but i'm not sure why this would break in FF. we will take a look.

**Comment by ForsakenHarmony** [comment]
Hmm, after adding authentication to the influxdb server it seems to work 🤔

**Comment by sranka** [comment]
The latest FF 77.0.1. works the same way as Chrome. I tried it against the current code in the master branch and the latest 1.8.4 debian/alpine docker images.
