### ISSUE TITLE
 insecure-skip-verify support for chornograf cli

### ISSUE THREAD

**Issue by sinistram** [influxdata/chronograf#5486]
There is a checkbox in UI for skipping insecure verify.
![image](https://user-images.githubusercontent.com/8999567/82215508-32e39400-9920-11ea-9b74-0d6e41efb98c.png)

It will be greate to be able to set this flag when running chorongraf via [cli](https://docs.influxdata.com/chronograf/v1.8/tools/chronograf-cli/) like db url, username and password.

**Comment by russorat** [comment]
@sinistram thanks for the issue. is it possible for you to use `.src` files instead of command line flags? https://docs.influxdata.com/chronograf/v1.8/administration/creating-connections/#manage-influxdb-connections-using-src-files

**Comment by sinistram** [comment]
@russorat I did not now about src files. But unfortunately it does not solve my issue. I am using docker and as can I see in official chorongraf docker there is option only for /var/lib/chronograf volume connecting.

**Comment by russorat** [comment]
@sinistram you should be able to mount any volume you want using the `-v` option for docker. then all you need to do it set the ENV variable for RESOURCES_PATH: https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#resources-path

**Comment by sinistram** [comment]
@russorat  Thanks!
