### ISSUE TITLE
Chronograf(1.7.17) not recognizing the auth token not logging me as an admin user

### ISSUE THREAD

**Issue by naresh399** [influxdata/chronograf#5488]
I am using SSO proxy login, while i am logging in i am giving my username and password for the sso login and after that i m seeing the chronograf dashboard. Its not the oauth admin window its like usual chronograf window its not showing me that i am logged in.

**Comment by russorat** [comment]
@naresh399 thanks for the issue. i'm not sure i fully understand what you are experiencing. can you post a screenshot?

**Comment by naresh399** [comment]
Once I logged in with my username and password through SSO proxy I just directly login to the chronograf dashboard. The super admin with crown symbol , I don't see that. looks could not able to authorize the application after the SSO login.
<img width="76" alt="Screen Shot 2020-05-21 at 5 52 33 PM" src="https://user-images.githubusercontent.com/33295675/82610339-2fecdb80-9b8c-11ea-9966-81817fe4949d.png">

**Comment by sranka** [comment]
Chronograf can't extract the login information when deployed behind a SSO proxy. OAuth2 login is supported, see https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/ .
