### ISSUE TITLE
Cannot connect to chronograf WEB GUI from remote machine

### ISSUE THREAD

**Issue by ttrading** [influxdata/chronograf#5490]
I just installed chronograf 1.8.4 on a VM machine on my laptop. It is running on port 8888. OS is CentOS 8.

I cannot reach the WEB GUI from my hos laptop. The browser session times out. However, when I tunnel my traffic to port 8888 to the VM using putty, I can open a browser session to chronograf. This suggests me that chronograf only allows local connections.

firewall is disabled on the VM and the network connection is set to bridge mode on VMWARE. I am using default installation settings on chronograf. What can I do to fix this.

Thanks,

**Comment by russorat** [comment]
@ttrading thanks for the issue. chronograf is designed to allow remote connections, so i believe this is a networking issue between your host and the vm machine. 

This will be tough for us to debug, but verify the network settings in the VM hypervisor are set to share the network with the host machine or tunnel the connection.

**Comment by sranka** [comment]
Chronograf by default listens on `0.0.0.0` network interface, which usually means to listen on every available network interface. It does not contain any code to restrict client access. You can change a listening address (`--host` parameter in chronograf), but this seems to be a networking issue of your environment. The easiest path to resolve this is to change the VM networking mode to `host` so you could then access chronograf at localhost:8888. With a bridge networking, it should work fine as well, you only have to use the IP address that is assigned to your VM on the host machine. You should be aware that possible proxy settings in the (host) browser might also block the connection to the host machine then.

**Comment by timhallinflux** [comment]
@pierwill review for potential doc improvement?
