### ISSUE TITLE
Proxy does not make requests to appropriate kapacitor

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5493]
Issue is around having two kapacitors configured for a single source.

1. select the second kapacitor and click on an existing task there. Observe that you receive a 404.
1. select the second kapacitor and add a new task. Observe that the task is added to the first kapacitor.

Additionally, cannot delete second kapacitor source from db connection. I suspect that these are all related.

**Comment by sranka** [comment]
This is not a proxy issue. If I add two kapacitors, there are then two active kapacitors managed on the server side, the first  'active' one is then always chosen by the UI [implementation](https://github.com/influxdata/chronograf/blob/c647798c3d5e2bade9f8c050107c74a9674bd7a4/ui/src/shared/apis/index.ts#L97), the second one is then never used. The `active` kapacitor is in fact the first kapacitor returned by the underlying kapacitor store. From my POV, it is a design problem of an existing implementation, activation of a specific capacitor does not work properly. The client code would work if there would be at most one `active` kapacitor on the server side, or the activated one would be the first returned. 

There might be other parts in the UI that also depend on the order of returned kapacitors, such as https://github.com/influxdata/chronograf/blob/b74f110eda3f211a55f254c30b58522e64a102d4/ui/src/alerts/containers/AlertsApp.tsx#L73

**Comment by DarrenMendalka** [comment]
@desa  Quick question.  Was this release in the latest Chronograf.  I was looking at release notes and could not tell.  

https://docs.influxdata.com/chronograf/v1.8/about_the_project/release-notes-changelog/
