### ISSUE TITLE
Cannot scroll in tickscript editor in firefox

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5494]
The first is that there's no slider bar on the side when I try to edit the script:

![](https://user-images.githubusercontent.com/44617130/81620612-2bad0b00-93a1-11ea-8086-5747806961ff.png)

I was able to arrow down to line 60-whatever no problem. However, when I tried to arrow back up

![](https://user-images.githubusercontent.com/44617130/81620860-b2fa7e80-93a1-11ea-8d49-deeb153b56a2.png)

Firefox Version: 74.0

**Comment by sranka** [comment]
Also reproducible in Opera.
