### ISSUE TITLE
[macOS] Scrolling through a query results doesn't work on Explore tab

### ISSUE THREAD

**Issue by Pavel-Egorov** [influxdata/chronograf#5496]
There is an error when I try to scroll through query results with my touch pad, values are scrolled, but when I stop scrolling, all values are automatically scrolled back to the very beginning. Only manual scroll works as it shown on attached video. It makes pretty impossible to search through any large amount of data because manual scrolling is too much sensitive.

[Untitled.mov.zip](https://github.com/influxdata/chronograf/files/4688392/Untitled.mov.zip)

Environment:

- Mac OS;

- Google Chrome 83.0.4103.61;

- Chronograf Docker Image - 1.8.4:alpine

**Comment by russorat** [comment]
@Pavel-Egorov thanks for opening this. we will take a look.

**Comment by sranka** [comment]
It works fine on Ubuntu + Chrome (84.0.4147.105 64-bit), Android with Chrome (83.0.4103.106 32-bit).

**Comment by Pavel-Egorov** [comment]
It just works with latest Chronograf/Chrome versions (on Mac OS as well). It may be problem with previous version of Chronograf.
