### ISSUE TITLE
Issues running Chronograf behind a reverse proxy via nginx.

### ISSUE THREAD

**Issue by snenkov** [influxdata/chronograf#5498]
My goal is to run Chronograf behind a rever proxy via Nginx.
I have updated the DNS.
My nginx.config looks like this:

```
server {
    listen 80;
    listen [::];
    root /var/www/chronograf.baseurl.com;
    index index.html;
    server_name chronograf.baseurl.com www.chronograf.baseurl.com;

    location / {
         try_files $uri $uri/ =404;
         proxy_pass http://localhost:8888;

         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-Host $host;
         proxy_set_header X-Forwarded-Server $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

The `/lib/systemd/system/chronograf.service` file looks like this (I have not changed it at all):

```
# If you modify this, please also make sure to edit init.sh
[Unit]
Description=Open source monitoring and visualization UI for the entire TICK stack.
Documentation="https://www.influxdata.com/time-series-platform/chronograf/"
After=network-online.target

[Service]
User=chronograf
Group=chronograf
Environment="HOST=0.0.0.0"
Environment="PORT=8888"
Environment="BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"
Environment="CANNED_PATH=/usr/share/chronograf/canned"
Environment="PROTOBOARDS_PATH=/usr/share/chronograf/protoboards"
EnvironmentFile=-/etc/default/chronograf
ExecStart=/usr/bin/chronograf $CHRONOGRAF_OPTS
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

When I run the page www.chronograf.baseurl.com I simply see a white blanc screen (I run it via incognito Chrome).

Can anyone please help me debug. 

Generally speaking a guide for running Chronograf via Nginx would be useful in the docs.

**Comment by russorat** [comment]
@snenkov thanks for the issue. take a look at https://github.com/influxdata/chronograf/issues/845 and see if it helps you at all. My guess is you have to set basepath option in chronograf. If you get it working, please post your update if you can!

**Comment by timhallinflux** [comment]
@snenkov -- did that address your issue?  If so, I'll close this issue.

**Comment by neomn** [comment]
@timhallinflux same issue here but setting base_path and public_url doesn't work for me till now , i user chrono in a docker container

**Comment by neomn** [comment]
@timhallinflux  well it works now :) , 

.env file > 
BASE_PATH="/chronograf"

my gateway nginx conf >
upstream chronograf {
    server chronograf:8888;
}
server { 
     listen       80;
     listen       [::]:80;
     server_name  management.com;
        
     location /chronograf/ {
         proxy_pass http://chronograf/chronograf/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
     } 
 }
