### ISSUE TITLE
Template variable with slash in value. Query failed code 400

### ISSUE THREAD

**Issue by thornowly** [influxdata/chronograf#5500]
**Version**
InfluxDB shell version: 1.8.0
Chronograf 1.8.4

**Observations**
When creating a template variable, if the value selected includes a forward slash ( / ) the query using that variable in Chronograf will return "Request failed with status code 400".

I have a template variable to select interface names on a switch from the dashboard, if i select a standard interface name which includes a slash, such as TenGigabitEthernet1/0/7 i receive the error message. "Request failed with status code 400"
Selecting other interface names such as Vlan800, Port-Channel1 etc produce expected results.

**Relevant info**

**Template variables**
`SHOW TAG VALUES on "netmon" WITH KEY="source" WHERE source =source`
`SHOW TAG VALUES on "netmon" WITH KEY="name" WHERE source =:source:`

**Query**
```SELECT "rx_kbps","tx_kbps" FROM "netmon"."autogen"."Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "name"=~/:interface:/ AND "source"=~/:source:/ GROUP BY time(:interval:) FILL(null)```

When :interface: is substituted for a value with forward slash the query fails.

**Comment by russorat** [comment]
@thornowly thanks for the issue. my guess here is that the forward slash is breaking your query because it isn't a valid regex. I believe you will need to escape the forward slash in your variable before using it in a regular expression.

**Comment by thornowly** [comment]
The forward slash is part of the interface name returned by :interface:
Can that be escaped?

**Comment by russorat** [comment]
@thornowly i don't think so. But can you just use `==` instead of regex in the query?

**Comment by thornowly** [comment]
I can use == and hardcode the interface name for testing and it works however the interface name has to be selectable based on the regex expression.
I've had to roll back to Grafana.
