### ISSUE TITLE
Chronograf shows only 1 row on select *

### ISSUE THREAD

**Issue by jiteshk23** [influxdata/chronograf#5502]
PFA the below screenshots for issue description.

count(*) shows that there are 3293 points
<img width="1437" alt="Screenshot 2020-06-01 at 11 04 44 AM" src="https://user-images.githubusercontent.com/1957780/83379853-2704d100-a3fa-11ea-8d58-7e6ffabc4277.png">

but "select *" shows only one
<img width="1437" alt="Screenshot 2020-06-01 at 11 03 45 AM" src="https://user-images.githubusercontent.com/1957780/83379867-2f5d0c00-a3fa-11ea-947c-5d32f7951823.png">

$ ./chronograf --version
Chronograf 1.8.4 (git: 86f6051776e44a4adaba1ad9d9e3ac8d8b6c2a13)

$ uname -m
x86_64`

**Comment by russorat** [comment]
@jiteshk23 thanks for the issue. Can you try running the queries against you database directly using the `influx` cli tool? That would tell us if the issue is with chronograf or influxdb.

**Comment by jiteshk23** [comment]
@russorat I did that and I could see the data. In fact, as shown in the attached screenshots, a count(*) query when run in chronograf is showing ~3k rows, but a select query shows only 1 row.

**Comment by russorat** [comment]
@jiteshk23 sorry for the misunderstanding. In the screenshots, you are running the queries via chronograf. I am asking you to execute the queries directly against your influxdb instance using the CLI tooling `influx` or the REST API.

**Comment by jiteshk23** [comment]
@russorat I did try using the cli as well. The data is present in influxdb and does show up when I run a select query using the cli.

**Comment by russorat** [comment]
@jiteshk23 ok, thank you for confirming.

**Comment by sranka** [comment]
I can reproduce a similar situation, it happens only when using more tag values a measurement. Steps to reproduce:
1. Insert points in a measurement with varying values of a tag - in my case using the influxdb-client-js example add 3 points with 3 measurement keys, run it twice to get 6 points in a measurement and 3 different values of host
 [i1.ts](https://github.com/influxdata/chronograf/files/5016548/i1.ts.txt)
2. `SELECT count(*) FROM "my-bucket"."autogen"."mem"` returns 1 row showing 6 in the UI
3. `SELECT * FROM "my-bucket"."autogen"."mem"` shows only 2 values, but there are 6 returned on the wire (see [uiResult.txt](https://github.com/influxdata/chronograf/files/5016597/uiResult.txt) ) ... the table shows at most one value for a specific time

Select that targets a specific key returns correct data, such as `SELECT * FROM "my-bucket"."autogen"."mem" WHERE host="host1"`
