### ISSUE TITLE
1.8.4: Misplaced error message

### ISSUE THREAD

**Issue by vlastahajek** [influxdata/chronograf#5510]
After reproducing #5476, the error message is misplaced. See below.
Os: Windows 10
Browsers: Chrome 83.0.4103.97, Edge: 44.18362.449.0 
![image](https://user-images.githubusercontent.com/29980246/84532670-ebfe7980-ace6-11ea-803a-b5813739cd2c.png)

**Comment by sranka** [comment]
@vlastahajek  isn't this already fixed? If it is not, please provide the instructions of how to reproduce.
