### ISSUE TITLE
Chronograf nightly, no influxeditor menu

### ISSUE THREAD

**Issue by Tamas92** [influxdata/chronograf#5515]
I read on this site: https://www.influxdata.com/blog/introducing-flux-editor-in-chronograf/

That the flux editor is available in the nightly version. I installed on my Raspberry, but the menu is not visible. 

pi@raspberrypi:~ $ chronograf --version
Chronograf 202006170351~nightly (git: 94db028b1d127f2841c1f1df96a69c00075ecdc1)

Am I missed something?

**Comment by russorat** [comment]
@Tamas92 thanks for the issue. In order for the flux option to show up in chronograf, you also need to enable it in your influxdb instance. Please confirm that is the case https://docs.influxdata.com/flux/v0.65/introduction/installation#sidebar

if there is still an issue, could you add a screenshot?

**Comment by Tamas92** [comment]
Yes, it is enabled:

pi@raspberrypi:~ $ cat /etc/influxdb/influxdb.conf |grep -i flux-enable
   flux-enabled = true
![Screenshot 2020-06-26 at 23 37 12](https://user-images.githubusercontent.com/63238832/85903162-fa2fb800-b805-11ea-832a-6f1f79c56277.png)

I can see Flux here, but in the screenshots what I could see as fluxeditor there was a menu below the explore.

**Comment by russorat** [comment]
> I can see Flux here, but in the screenshots what I could see as fluxeditor there was a menu below the explore.

I'm sorry, i don't think i understand what you are trying to say. Is there any way you could help clarify?

**Comment by Tamas92** [comment]
https://www.influxdata.com/blog/introducing-flux-editor-in-chronograf/

I want to reach this:

![Screenshot 2020-07-07 at 20 44 14](https://user-images.githubusercontent.com/63238832/86827698-a0937d00-c092-11ea-9286-e2f14145b938.png)

**Comment by russorat** [comment]
@Tamas92 ah now i get it. That screenshot was from an older version of the editor and is no longer available in the latest version.

**Comment by sranka** [comment]
Closing, the current layout contains all required parts. 
![image](https://user-images.githubusercontent.com/16321466/96689326-8b610680-1382-11eb-8cd7-02f06dfe709b.png)

**Comment by djsomi** [comment]
> Closing, the current layout contains all required parts.
> ![image](https://user-images.githubusercontent.com/16321466/96689326-8b610680-1382-11eb-8cd7-02f06dfe709b.png)

Thanks for drawing the attention to gui change. I did not realized that this. Confed flux-enabled = true influxdb.conf, working fine now!
