### ISSUE TITLE
Alerts with kapacitor

### ISSUE THREAD

**Issue by guiguemolla** [influxdata/chronograf#5518]
I was creating an alert with the function of "!=" to choose all disk paths except those ones. The problem I had is that the filter was created this way but between the paths it was an `OR` instead of an `AND` in the TICK script (because in the "=" case is normal to be an "OR")

So I think this should be changed to "AND" in case of the "!=" because it doesn't make sense to put OR between "!="

Thank you so much

**Comment by russorat** [comment]
@guiguemolla thank you for the issue. we will take a look.

If you can, could you post a screenshot of what you are seeing so that we can make sure we understand and address it?

**Comment by guiguemolla** [comment]
I don't know exactly how can I make a Picture of it as is a realtion between 2 screens but let me try.
I want to do somthing like this in chronograf.
![chronograf1](https://user-images.githubusercontent.com/48988038/86356710-fa4c0f80-bc6c-11ea-8e29-5733cfd6c467.png)
Here as you see i'm trying to make an alert for kapacitor for all the devices EXCEPT those two.

But the tick script generated is like this:
![chronograf2](https://user-images.githubusercontent.com/48988038/86356743-0e900c80-bc6d-11ea-8bc9-20345ccf8a83.png)
So it makes that those same devices show in the alerts also. Why? Because the condition of them is an OR between them instead of an AND.

I know i'm not good at explaining things by text but I wish this time I could 
Thank you

**Comment by russorat** [comment]
Thank you for the update. I think I understand.

**Comment by timhallinflux** [comment]
when using `=` default to `OR` and when using `!=` default to `AND`
