### ISSUE TITLE
Chronograf: Create Template Variable should allow flux in addition to influxQL

### ISSUE THREAD

**Issue by andig** [influxdata/chronograf#5526]
__Proposal:__
When the query is in flux, template variables should be possible in flux, too.

__Current behavior:__
Template variables only support influxQL

__Desired behavior:__
optionally allow flux.

__Alternatives considered:__
n/a

__Use case:__
influxQL will be replaced by flux

**Comment by andig** [comment]
Thank you- thought this was part of the main repo meanwhile.

**Comment by timhallinflux** [comment]
![Screen Shot 2020-11-19 at 7 14 24 PM](https://user-images.githubusercontent.com/23535264/99753635-71a70200-2a9b-11eb-9c60-fd2fa81a1b59.png)

I'd suggest changing the text for the type option to include:
1) Custom InfluxQL Meta Query
2) Custom Flux Meta Query --- assuming that the Flux endpoint is available on the associated data source indicated.

**Comment by ivankudibal** [comment]
Grammar of how how to write the variable in Flux is not clear today:

1. |> filter(fn: (r) => r["host"] == v.linux_host)    is Flux Style
2. |> filter(fn: (r) => r["host"] == linux_host)      is Chronograf v1 Style (for set of system variables*)
3. |> filter(fn: (r) => r["host"] == :linux_host:)    influxql style

ad 1. looks good because of forward-compatibility
ad 2. values such as upperDashboard etc do not require v. prefix
ad 3. the least wanted option imo 

*) https://docs.influxdata.com/influxdb/v1.8/flux/guides/flux-in-dashboards/#template-variables-in-flux

**Comment by timhallinflux** [comment]
Option 1 is preferred.

**Comment by sranka** [comment]
InfluxDB v2 UI sends `v` variable as an `extern` value of every query, a similar approach could be used in chronograf. 

<details>
  <summary>V2 query API extern that defines `v` variable</summary>

```json
{
  "type": "File",
  "package": null,
  "imports": null,
  "body": [
    {
      "type": "OptionStatement",
      "assignment": {
        "type": "VariableAssignment",
        "id": {
          "type": "Identifier",
          "name": "v"
        },
        "init": {
          "type": "ObjectExpression",
          "properties": [
            {
              "type": "Property",
              "key": {
                "type": "Identifier",
                "name": "timeRangeStart"
              },
              "value": {
                "type": "UnaryExpression",
                "operator": "-",
                "argument": {
                  "type": "DurationLiteral",
                  "values": [
                    {
                      "magnitude": 7,
                      "unit": "d"
                    }
                  ]
                }
              }
            },
            {
              "type": "Property",
              "key": {
                "type": "Identifier",
                "name": "timeRangeStop"
              },
              "value": {
                "type": "CallExpression",
                "callee": {
                  "type": "Identifier",
                  "name": "now"
                }
              }
            },
            {
              "type": "Property",
              "key": {
                "type": "Identifier",
                "name": "windowPeriod"
              },
              "value": {
                "type": "DurationLiteral",
                "values": [
                  {
                    "magnitude": 1800000,
                    "unit": "ms"
                  }
                ]
              }
            }
          ]
        }
      }
    }
  ]
}
```
</details>

**Comment by sranka** [comment]
I split this issue, 'add Custom Flux Meta Query to define template variable value set' is now in #5693
