### ISSUE TITLE
Chronograf: template variable not parsed

### ISSUE THREAD

**Issue by andig** [influxdata/chronograf#5527]
__Steps to reproduce:__

Setup a `:loadpoint:` template variable in flux.

Run the following query:

```
from(bucket: "evcc")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement != "chargedEnergy")
  |> filter(fn: (r) => r.loadpoint == :loadpoint: or not exists r.loadpoint)
  |> map(fn: (r) => ({r with _value: if r._measurement == "pvPower" then -r._value else r._value}))
```

__Expected behavior:__
Show result

__Actual behavior:__
UI shows `[object Object]` once `:loadpoint:` is part of the query

__Environment info:__

* InfluxDB version: `Chronograf Version: 1.8.4`
* Other relevant environment details: Docker

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

**Comment by russorat** [comment]
thanks @Anaisdg ! Chronograf does not support template variables in Flux.

**Comment by Anaisdg** [comment]
@andig ^^^

**Comment by andig** [comment]
Well... they are available in the ui, together with the flux option plus mentioned in the docs. How would a user ever expect this? Plus dashboard variables are supported (unless I‘m confusing that with grafana).

So if that‘s the current status- they should be!

**Comment by timhallinflux** [comment]
dup of #5526 

Closing in favor of ^
