### ISSUE TITLE
add "field" filter on chronograf "explore"/"query builder" page

### ISSUE THREAD

**Issue by aldas** [influxdata/chronograf#5528]
We have measurements with 100+ (1800+ extreme case) fields and it is quite annoying to scroll on "fields" pane to check fields for to build needed query. 

Please consider adding field filter on chronograf "explore"/"query builder" page

![chronograf](https://user-images.githubusercontent.com/2320301/86209227-c2649f80-bb7a-11ea-9283-9f461f9721ce.png)

**Comment by russorat** [comment]
@aldas great suggestion! we will take a look. If you'd like to submit a PR, we'd be happy to review. Thanks!

**Comment by sranka** [comment]
The Fields header can be quite narrow for the new filter to fit in:
![image](https://user-images.githubusercontent.com/16321466/111266919-80598c00-862b-11eb-990d-f54351719df1.png)
It will rather appear at the top of the field list if there are more than 10 items to select from.
