### ISSUE TITLE
Save a dashboard and make it pre-canned?

### ISSUE THREAD

**Issue by peter-hartmann-emrsn** [influxdata/chronograf#5530]
After developing a dashboard I'd like to add it to the default deployment of a docker composition.

A dashboard can be created and exported, resulting into a json file - good.
The json file can be imported on another system - good.

What's unclear is how to add the json file to a deployment so that the dashboard is available without needing to import it first.

I tried putting it into the ```/usr/share/chronograf/canned``` directory but no luck.

The closest documentation I found is [here](https://github.com/influxdata/chronograf/blob/9d8a49ba0ef8131cdce22d73718859f55f434db2/docs/LAYOUT.md), but the mentioned new_apps.sh can't be found anywhere.

I'm posting this as an issue because I belief this needs better documentation.

**Comment by russorat** [comment]
@peter-hartmann-emrsn i'm pretty sure you can add those dashboards to the `--resources-path` with the extension `.dashboard` and they will be loaded. 

https://github.com/influxdata/chronograf/issues/1243#issuecomment-339671516
https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#resources-path

We definitely need to add that to the docs though.
