### ISSUE TITLE
When using flex in chronograf Safari complains about taking a ludicrous amount of memory

### ISSUE THREAD

**Issue by ruurd** [influxdata/chronograf#5533]
When I am using chronograf in Safari, for some reason it will start complaining about using a very large amount of memory. I also see that there is a workerXXXX.js that adds a proxy every time a panel is being refreshed. 

See the screenie.

**Comment by ruurd** [comment]
![Chronograf 2020-07-12 22-02-06](https://user-images.githubusercontent.com/190727/87255559-26953680-c48c-11ea-9240-a771ef868a9a.png)

**Comment by sranka** [comment]
This is was most likely a defect with older Safari versions, it is already fixed. Please see 
- https://forums.macrumors.com/threads/safari-website-wants-to-use-over-1gb-storage.2232083/ 
- https://bugs.webkit.org/show_bug.cgi?id=202137

Feel free to reopen if you still can reproduce it, and include Safari version pls.
