### ISSUE TITLE
Unable to post new rule via chronograf API and Bearer token

### ISSUE THREAD

**Issue by DangoDaikazoku** [influxdata/chronograf#5535]
Hello

We have a chronograph setup with our own OAUTH provider ( connected through generic auth )
I am writing an automated system to add alert rules to chronograf, but the post API doesn't work with the following, please guide

Post to:
http://chronograf-url/chronograf/v1/sources/1/kapacitors/1/rules

Header:
Authorization Bearer xxx-valid-token-XX

Body:
Valid JSON as defined in /docs

but I get a 403, removing authentication makes it work. Looking at the code it seems like it expects session=valid_session_identifer in cookie, but I don't have that. Please advise on what could be done

**Comment by DangoDaikazoku** [comment]
Open further inspection it seems to expect jwt token in cokkie session. Can we change this behavior ? How can I generate JWT token from a bearer token ?

**Comment by timhallinflux** [comment]
Need the ability to set the token type...JWT is the default.  But, obviously bearer is the other type.

**Comment by sranka** [comment]
@DangoDaikazoku 

Chronograf internally uses JWT in a `session` cookie to remember users that came in through OAUTH authentication, this JWT stuff is not meant to be used in tools. Chronograf however offers an extra `superadmin authentication` that is intended for tools.  I found no public documentation about it, I have to find out (create) instructions on how to use it.

**Comment by sranka** [comment]
The following node.js example creates JWT token and then gets chronograf dashboards (1.8.10)
```js
const jwt = require("jsonwebtoken");
const fetch = require("node-fetch");

function createToken(subject, issuer, secret) {
  const issuedAt = Math.trunc((Date.now() - 60_000) / 1000); // 1 minute clock skew
  const expires = Math.trunc((Date.now() + 300_000) / 1000); // 5 minutes expiration
  return jwt.sign(
    {
      exp: expires,
      iat: issuedAt,
      iss: issuer,
      nbf: issuedAt,
      sub: subject,
    },
    secret
  );
}

function getRequest(url, token) {
  console.log("GET:", url);
  fetch(url, {
    headers: {
      cookie: `session=${token}`,
    },
  })
    .then((res) => {
      if (!res.ok) {
        console.log("Request ERROR:", res.status, res.statusText);
      } else {
        console.log("Request SUCCESS");
      }
      return res.text();
    })
    .then((text) => {
      console.log(text);
    })
    .catch((e) => {
      console.log("Request FAILED:", e);
    });
}

console.log("=== Create JWT token ===");
const subject = "pavel.zavora@bonitoo.io";
const issuer = "github";
// tokenSecret must be the same secret that chronograf is started with
const tokenSecret = "Q4O1T8FTbErOnmx03mGeVH3pkvKtdKr6HEmzEpNBiVMynZ/qKDdOResI3OMx4Zg9kmIfAI9ihlIV3OV5+VRfZ+iB2knLuGagEmFpG/h51CRcQY58j2NpnxdBewz91E51RRfjDYvqMrISHZCjdeuw0338Xp5UnEg32utr0ThRN0Ucv2isRr4KYJNYuvUXrjKJzjh76394JwY+bzn20L/enR2rLEtJ40ePxwuEvsE0MBUGZy79ecLZPaolQ3lkPE6X3+iV/9suN0BkBNtbQe1sGv4P522jSm24fFhXaFjetQQ/dJGehbWzsBo8uVAWB2RO0+xU2LhHFN0k0LAESD6MWw==";
const token = createToken(subject, issuer, tokenSecret);
console.log(token);

console.log("=== Call chronograf API ===");
const chronografURL = "http://localhost:8888";
const url = `${chronografURL}/chronograf/v1/dashboards`;
getRequest(url, token);
```

**Comment by sranka** [comment]
The following steps are required to use `superadmin` authentication:

__Generate Superadmin RSA key__
```bash
openssl genrsa -out superadmin.key 4096
openssl rsa -in superadmin.key -RSAPublicKey_out -out superadmin.pub
sed -i 's/RSA PUBLIC KEY/PUBLIC KEY/g' superadmin.pub
```

__Start Chronograt with PUB_KEY_FILE__
```bash
export PUB_KEY_FILE=./superadmin.pub
# ... any other parameters, OAuth parameters including
chronograf
```

__Get dashboards with superadmin authentication__
```bash
BASEURL=http://localhost:8888
SNONCE=`curl -q ${BASEURL}/nonce | openssl dgst -sha256 -sign superadmin.key | openssl base64 -A`
curl -v -H "Authorization: CHRONOGRAF-SHA256${SNONCE}" ${BASEURL}/chronograf/v1/dashboards
```
