### ISSUE TITLE
Dashboard Annotations - Annotations should be bound to their respective dashboard only

### ISSUE THREAD

**Issue by tomklapka** [influxdata/chronograf#5539]
Bulid **Nightly Build**
Browser Chrome 83

`Chronograf 202007151705~nightly (git: 0babc528f0115bf1403f084f45b774858a4b94df)`

_Use Case_

Create new dashboard "Dashboard_1" and cell "Cell_1" with data e.g. from telegraf.autogen > cpu > usage_idle
Enable Annotations.
Create new annotation.
Delete dashboard with cell
Create another new dashboard "Dashboard_2" and "Cell_2" cell with data e.g. from telegraf.autogen > cpu > usage_idle
Enable Annotations.
There shouldn't be any annotation present, but instead there is the annotation from previously deleted dashboard.

_Expected behavior_

Annotations should be bound to their respective dashboard. When dashboard no longer exists, related annotations should be also removed. If not, please update the documentation to reflect actual behaviour: https://docs.influxdata.com/chronograf/v1.8/guides/annotations/

**Comment by sranka** [comment]
Yes, the `annotations` feature requires better documentation to make this clear, I've created https://github.com/influxdata/docs-v2/issues/1982 to request changes in the docs.
