### ISSUE TITLE
Configuring TLS in already configured Chronograf 1.8.5 results in system being returned to factory settings

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#5540]
Repro Steps:

OS ubuntu 18
* Configure 1.8.5 without TLS
* Set TLS_CERTIFICATE=`/etc/default/fullchain.pem` and  `TLS_PRIVATE_KEY=/etc/default/privkey.pem` in `/etc/default/chronograf `

observe that initial configuration is not retained.

**Comment by desa** [comment]
> Need to correct the findings. It appears that only the initial set-up screen reverts to defaults. Feels more like a mild inconvenience (more of a security issue) than a real bug.

**Comment by sranka** [comment]
Unable to reproduce with the following steps:
- install a fresh new 1.8.5 chronograf on a local Ubuntu 18.0.4, `chronograf` service is started automatically after installation
- configure InfluxDB connection using a UI wizard at http://localhost:8888
- `service chronograf stop`
- add TLS_CERTIFICATE and TLS_PRIVATE_KEY to /etc/default/chronograf
- open https://localhost:8888 => the initial configuration of InfluxDB is retained, the onboarding wizard is not shown 

Please reopen if there are other pre-conditions required to reproduce this issue.
