### ISSUE TITLE
repos.influxdata.com out of sync

### ISSUE THREAD

**Issue by danielsreichenbach** [influxdata/chronograf#5543]
It looks like packages on <https://repos.influxdata.com> are not updating again.

Currently this affects Chronograf where only version 1.8.4 is in the repo but that has a bug breaking any installation using OAuth, and 1.8.5 (fixing that in #5475 ) is not in the repos.

Could you please update it?

**Comment by russorat** [comment]
@danielsreichenbach sorry to keep missing this. i will get them updated today.

**Comment by russorat** [comment]
Should be there now. Sorry again. I will make sure they are updated next time.
