### ISSUE TITLE
Log viewer doesn't show database which has syslog measurment.

### ISSUE THREAD

**Issue by empz** [influxdata/chronograf#5544]
![image](https://user-images.githubusercontent.com/412489/88560772-d511ad80-d02e-11ea-8504-b714f7e1cdc3.png)

![image](https://user-images.githubusercontent.com/412489/88560792-dd69e880-d02e-11ea-9b9f-ed2517c89506.png)

I'm using the influxdb-sandbox setup.

**Comment by russorat** [comment]
@eparizzi that's strange. We will need to investigate if it's only looking at the default telegraf database.

**Comment by ChaoticEnigma** [comment]
I'm having the same problem. I have logs in the syslog measurement in the telegraf database:
![image](https://user-images.githubusercontent.com/2348393/101064742-568bc600-3562-11eb-9211-9dbdb9264ff6.png)

But I can't select the telegraf database in chronograf:
![image](https://user-images.githubusercontent.com/2348393/101064859-728f6780-3562-11eb-8075-4e1f7bba4f62.png)

And with the chronograf configuration being completely opaque, I can't even attempt a workaround.

I'm also using the TICK sandbox.

**Comment by Zagitta** [comment]
I am also experiencing this bug.

**Comment by timhallinflux** [comment]
@sranka see if you can reproduce this?

**Comment by sranka** [comment]
It can be reproduced with the following steps:
- create a new database
- open Logs Viewer - the new database does not appear in the selection
   - note: changing the source refreshes the database list properly

The list of available databases is wrongly cached in the browser's local storage. It must be rather re-fetched every time the logs page is opened.
