### ISSUE TITLE
Compatibility with InfluxDB Cloud 2

### ISSUE THREAD

**Issue by rhajek** [influxdata/chronograf#5546]
#### Authentication setup
https://v2.docs.influxdata.com/v2.0/reference/api/influxdb-1x/
url: like https://us-west-2-1.aws.cloud2.influxdata.com/
username: InfluxDB username (account email)
password: InfluxDB authentication token

￼Bugs and other backward compatibility issues:
* Buckets created in Cloud2 UI are not shown in Chronograf 1, mapping must be created https://v2.docs.influxdata.com/v2.0/reference/api/influxdb-1x/dbrp/ manually using curl tool
* Not implemented responses from CREATE/DELETE commands are with status 200. More clear is 501 “Not Implemented” ?

### Connection wizzard
  * detect version of InfluxDB using /ping
  * remove Kapacitor in wizard

￼￼![image](https://user-images.githubusercontent.com/2169548/88661743-5291f800-d0d9-11ea-9388-0cf8b1ff1dbf.png)
![image](https://user-images.githubusercontent.com/2169548/88661766-59206f80-d0d9-11ea-88b7-55cd44112c70.png)

###  Delete database, create database
![image](https://user-images.githubusercontent.com/2169548/88661783-60477d80-d0d9-11ea-812c-b0dcb672086f.png)

### Create/Delete user
![image](https://user-images.githubusercontent.com/2169548/88661921-938a0c80-d0d9-11ea-8b6c-27f2266b4fa1.png)

### Queries 
  * SHOW QUERIES is not implemented
![image](https://user-images.githubusercontent.com/2169548/88661943-997fed80-d0d9-11ea-8ee7-613f3b361584.png)

￼* Enable Flux queries (is this compatible with 1.8 ?)
![image](https://user-images.githubusercontent.com/2169548/88661962-9e44a180-d0d9-11ea-9a58-76d9afa5ff54.png)

**Comment by sranka** [comment]
Closing this in favor of #5617 and #5614 .
