### ISSUE TITLE
Editing of templated tasks doesn't work

### ISSUE THREAD

**Issue by Pavel-Egorov** [influxdata/chronograf#5547]
When I open a task which is based on a template in Edit mode (I mean through Alerting tab and then just press to the name of the desired task) I see template code instead of task' code. And if I change this code and then press Save changes it doesn't work also.

**Comment by russorat** [comment]
@Pavel-Egorov thanks. we don't support templated tasks in the chronograf UI right now.

**Comment by Pavel-Egorov** [comment]
Thank you for the response!
But I think it would be good to mark such tasks in special way to avoid misunderstanding. Or you can explicitly forbid their editing.
