### ISSUE TITLE
Dashboards cannot be migrated when migrating chronograf 1.7.11(bolt DB) to chronograf 1.8.0(etcd)

### ISSUE THREAD

**Issue by nemea31** [influxdata/chronograf#5550]
hi.
There was a problem migrating the bolt DB used in 1.7.11 from 1.8 or higher to etcd.

$ ./chronoctl migrate --from=chronograf-v1.db --to=etcd://192.168.56.105:2379
Performing non-idempotent db migration from "chronograf-v1.db" to "etcd://192.168.56.105:2379"...
NOTICE: New IDs will be generated for each resource.
  Saved 3 organizations.
  Saved 6 organization configs.
  Saved 0 dashboards.
  Saved 1 mappings.
  Saved 3 servers.
  Saved 4 sources.
Migration successful!

The other store is moved by etcd, but the Dashboard is not being migrated.
Is it related to this?
https://github.com/influxdata/chronograf/pull/5360
Isn't the id type changed from number to string so the query can't be made over 1.8?

**Comment by russorat** [comment]
@nemea31 thanks! We recommend you update from 1.7.11 to the latest Chronograf using the normal upgrade process and maintaining boltdb as the backing store. Once you are on the latest version, then try the migration again.

**Comment by jaemyeongroh** [comment]
The bolt DB used in 1.7.11 was used for 1.8.5 Chronograf.
Still, I couldn't see the saved dashboards.
In 1.7.11, the dashboards are visible.

**Comment by nemea31** [comment]
The bolt DB used in 1.7.11 was used for 1.8.5 Chronograf.
Still, I couldn't see the saved dashboards.
In 1.7.11, the dashboards are visible.

**Comment by timhallinflux** [comment]
@nemea31 following up on this somewhat old issue now.  What is the current state?
