### ISSUE TITLE
RFC: Change the queries in this view to not use counters and rather use derivatives

### ISSUE THREAD

**Issue by zabullet** [influxdata/chronograf#5552]
@ebb-tide @lpic10 

Some of the queries in this view are counters and are not very useful 

e.g.
https://github.com/influxdata/chronograf/blob/9eb861a164e3b4cc2339438a6d655efbc1ec3fcd/protoboards/mysql.json#L96

Would make more sense being

```SELECT NON_NEGATIVE_DERIVATIVE(mean("innodb_data_writes")) AS "writes", NON_NEGATIVE_DERIVATIVE(mean("innodb_data_reads")) AS "reads" FROM "telegraf"."autogen"."mysql" WHERE host =:host: AND time > :dashboardTime: GROUP BY time(:interval:) FILL(null)```

![image](https://user-images.githubusercontent.com/8068418/89229532-8093a280-d5d9-11ea-92a1-55702070e991.png)

is better than

![image](https://user-images.githubusercontent.com/8068418/89229582-96a16300-d5d9-11ea-9e67-4bb4d9d505b6.png)

**Comment by russorat** [comment]
@zabullet thanks for the issue. would you like to make a PR?

**Comment by zabullet** [comment]
@russorat 

I'm happy to do a PR, however, I just wanted make sure there wasn't a reason for not putting a derivative function before I changed it. I'll give the other contributors a couple of days to comment and then do a PR.

**Comment by zabullet** [comment]
See https://github.com/influxdata/chronograf/pull/5556
