### ISSUE TITLE
Unable to use latest 1.8.4 version

### ISSUE THREAD

**Issue by pnutmath** [influxdata/chronograf#5558]
I am currently using docker image of version 1.8.2

I have configured gitlab SSO. All setup is working fine.

When I tried to upgrade it to 1.8.4 or with latest tag it gives me following error:

`ERRO[0000] Failed to validate Oauth settings: missing Google oauth setting[s]: client id, client secret basepath=invalid component=server`

Why it is checking for google settings?

**Comment by dominikkv** [comment]
See https://github.com/influxdata/chronograf/issues/5482

**Comment by pnutmath** [comment]
Duplicate of #5482 

Thanks,

I can see release @v1.8.5 . but,
Don't we have updated image on docker hub? 

https://hub.docker.com/_/chronograf?tab=tags

**Comment by russorat** [comment]
we have updated to the latest tag in docker. sorry for the delay.

**Comment by pnutmath** [comment]
Thanks @russorat
