### ISSUE TITLE
int64 + mean overflows

### ISSUE THREAD

**Issue by elbaro** [influxdata/chronograf#5564]
Hi, I experimented with influxdb+chronograf by recording the current nano timestamps.
A `y=ax` graph was expected but the values even go to below zero.

I changed the default `mean` function to `max` and it works correctly.
```
SELECT mean("rt") AS "mean_rt" FROM "test"."autogen"."ping" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)
SELECT max("rt") AS "mean_rt" FROM "test"."autogen"."ping" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)
```
![image](https://user-images.githubusercontent.com/1851290/91149019-83c01100-e6f5-11ea-8ac8-f77894021213.png)

![image](https://user-images.githubusercontent.com/1851290/91148815-3e034880-e6f5-11ea-873f-c0296be9b8f2.png)

Is this because int64 overflow? Can you support this with int128/double128/BigDecimal/etc.

**Comment by russorat** [comment]
@elbaro thanks for the issue. Can you explain what you are actually trying to do any why such large numbers are required for your use case? i don't think influxdb supports int128 so thats not something we could support either.

**Comment by elbaro** [comment]
unix epochs in nanoseconds require int64.
We do not need int128 in influxdb. The problem is Chronograf fails to calculate the average of int64 timeseries.

**Comment by sranka** [comment]
@elbaro, I would like to reproduce this locally before taking further action, can you please better describe the dataset to use? I mean time intervals between reported measurements, and values for specific time (a constant, assuming y=ax)

**Comment by elbaro** [comment]
It was recorded every 15ms. 

I think you may not need many samples to reproduce this-
The unix timestamp right now is 1604597004 seconds = 1.6e18 nanoseconds.
int64 max is 9223372036854775807 = 9.2e18. If `mean` function calculates the sum in int64, 10~100 samples would be enough.

**Comment by sranka** [comment]
I tried to reproduce this with a dockerized InfluxDB 1.8 and the latest Chronograf 1.8.8, InfluxDB returns expected values and Chronograf line-chart visualization shows a simple ascending line. @elbaro What versions do you use?

*Data*:
```js
#!/usr/bin/env node
const {InfluxDB, Point} = require('@influxdata/influxdb-client')
const database = 'telegraf'
const retentionPolicy = 'autogen'
const bucket = `${database}/${retentionPolicy}`
const url = 'http://localhost:8086'
const token = 'my-token'
const org = ''

async function writeData() {
  const writeApi = new InfluxDB({url, token}).getWriteApi(org, bucket, 'ms')
  let time = new Date('2019-11-12T10:59:08.753Z').getTime() //
  const stop = new Date('2019-11-12T12:00:00.000Z').getTime() // 2019-11-12T10:59:08.753Z
  let count = 0
  while (time < stop) {
    writeApi.writePoint(
      new Point('ctest')
        .floatField('fvalue', time)
        .intField('ivalue', time)
        .timestamp(time)
    )
    count++
    if ((count + 1) % 1000 == 0) {
      console.log('flush ', count)
      await writeApi.flush()
    }
    time += 15
  }
  // close
  console.log('close')
  await writeApi.close().catch(console.error)
}

writeData()
```

*Query*:
```
SELECT mean("ivalue") AS "mean_ivalue", mean("fvalue") AS "mean_fvalue" FROM "telegraf"."autogen"."ctest" WHERE time > '2019-11-12T10:59:08.753Z' AND time < '2019-11-12T12:01:38.753Z' GROUP BY time(1m) FILL(null)
```

**Comment by elbaro** [comment]
It was a docker image 2 months ago. I just tried again with Chronograf 1.8.4 and could not reproduce.
