### ISSUE TITLE
Blank screen shown due to incorrect MIME type (Windows v1.8.6, chronograf-202008262010~nightly-0)

### ISSUE THREAD

**Issue by Cakez0r** [influxdata/chronograf#5565]
I downloaded both the v1.8.6 and nightly (chronograf-202008262010) windows binaries binaries https://portal.influxdata.com/downloads/

I run chronograf.exe which starts with no problem.
```
time="2020-09-01T11:22:56+06:30" level=info msg="Moving from version 1.8.0"
time="2020-09-01T11:22:56+06:30" level=info msg="Moving to version 202008262010~nightly"
time="2020-09-01T11:22:56+06:30" level=info msg="Successfully created backup/chronograf-v1.db.1.8.0"
time="2020-09-01T11:22:56+06:30" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
time="2020-09-01T11:22:56+06:30" level=info msg="Serving chronograf at http://[::]:8888" component=server
```

I then navigate to http://localhost:8888/ using Chrome (also tried Edge and Internet Explorer) and am presented with a empty, black screen. Developer console shows the error: `Refused to execute script from 'http://localhost:8888/src.1e3b6d12.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`

**Comment by Cakez0r** [comment]
Also present in 1.8.5.

Version 1.8.4 works correctly

**Comment by BadWolfCT** [comment]
Having the exact same issue. Windows 10, chrome, IE and edge all the same result. Any progress?
![image](https://user-images.githubusercontent.com/52155746/94917353-ad1c4b80-04b0-11eb-93b9-f714e106edc4.png)

**Comment by erzahoti** [comment]
Hi, I'm having the same issue here, any news?

**Comment by BadWolfCT** [comment]
While I wait for a resolution, to continue using it I downgraded to 1.8.4 and as the OP states that version works correctly.

**Comment by sranka** [comment]
It seems to happen only in Windows, it is not reproducible on Linux.

**Comment by sranka** [comment]
I tried the latest 1.8.7 release + nightly distributions, both work fine on Windows 10.0.19041.

**Comment by e97317** [comment]
Hi @sranka, 
Just downloaded today the **1.8.8** release for windows. 
Unzip the file.
Cleared all cache data from Chrome browser.
Ran chronograf.exe and got the very same error. 

![bug](https://user-images.githubusercontent.com/64333014/100864619-879ec480-3496-11eb-8965-2ce31b93d461.png)

Tripple checked I was running the 1.8.8 version and not my previous version (1.8.4).
Did the same test on another desktop, same results... 
I'm a bit confused here...

**Comment by sranka** [comment]
@e97317 thank you for letting me know, please see https://github.com/influxdata/chronograf/issues/5607#issuecomment-722427606 for details and instructions on how to resolve this

**Comment by sranka** [comment]
I'll take a look if it is feasible to enforce a correct mime type for chronograf to work properly even in the case of misconfigured windows.

**Comment by e97317** [comment]
> @e97317 thank you for letting me know, this issue depends on windows configuration, please see [#5607 (comment)](https://github.com/influxdata/chronograf/issues/5607#issuecomment-722427606) for details and instructions on how to resolve this

You are right... updating the registery key [HKEY_CLASSES_ROOT\.js]  to "Content Type"="text/**javascript**" did the job... now it works fine 👍 
Thanks for the quick answer!
