### ISSUE TITLE
 Chronograf (1.7.12) Expected number or array but got string: success.

### ISSUE THREAD

**Issue by rdxmb** [influxdata/chronograf#5569]
What browser are you using (name and version)?
FF 80.0

What operating system are you using?
Kubuntu 20.04

Please describe what you were trying to do when you encountered this error:
Trying to create an alert with field `result_type` from measurement `http_response`, which is a string. 

The "real" problem seems that I cannot undo that: When clicking on `response_time` or `result_code`, the error persists.

```
j@https://chronograf.example.com/src.6549ea42.js:3158:1898
parcelRequire<.SU7O</W.prototype.parseArray_@https://chronograf.example.com/src.6549ea42.js:3158:31912
parcelRequire<.SU7O</W.prototype.start_@https://chronograf.example.com/src.6549ea42.js:3158:35574
parcelRequire<.SU7O</W.prototype.updateOptions@https://chronograf.example.com/src.6549ea42.js:3158:36541
value@https://chronograf.example.com/src.6549ea42.js:3218:4878
xi@https://chronograf.example.com/src.6549ea42.js:716:84251
wi@https://chronograf.example.com/src.6549ea42.js:716:79945
ki@https://chronograf.example.com/src.6549ea42.js:716:79563
Ha@https://chronograf.example.com/src.6549ea42.js:716:78073
enqueueSetState@https://chronograf.example.com/src.6549ea42.js:716:47062
parcelRequire<.awqi</h.prototype.setState@https://chronograf.example.com/src.6549ea42.js:708:1621
t/<@https://chronograf.example.com/src.6549ea42.js:4421:2389
L@https://chronograf.example.com/src.6549ea42.js:5:4401
w/i._invoke</<@https://chronograf.example.com/src.6549ea42.js:5:4190
_/</t[r]@https://chronograf.example.com/src.6549ea42.js:5:4580
o@https://chronograf.example.com/src.6549ea42.js:4421:1802

```

**Comment by russorat** [comment]
@rdxmb thanks for the issue. could you upgrade to the latest chronograf and reopen if the issue persists?

**Comment by rdxmb** [comment]
ok, the error does not occur like above anymore with 1.8.6 There is only 

![Screenshot_20200915_225853](https://user-images.githubusercontent.com/30314040/93264184-08f38e80-f7a7-11ea-96c9-92c857d9eadf.png)

This is ok for me. Thanks.
