### ISSUE TITLE
configure Chronograf to authenticate and authorize with OAuth 2.0 

### ISSUE THREAD

**Issue by chenzhouly** [influxdata/chronograf#5575]
while configure Chronograf to authenticate and authorize with OAuth 2.0 ,i got such problem:

ERRO[0053] Unable to get OAuth Group malformed email address, expected "chenzhou" to contain @ symbol

i doult that the UserInfo got by the GENERIC_API_KEY must be a malformed email address?

**Comment by russorat** [comment]
@chenzhouly thank you for the issue. please take a look at https://docs.influxdata.com/chronograf/v1.8/administration/managing-security/ and if you are still having issues, post your existing oauth 2.0 config so that we can take a look.

**Comment by sranka** [comment]
This error indicates that a primary email is not found for a user. It has to be present.

**Comment by timhallinflux** [comment]
@pierwill  review for improvement related to docs?
