### ISSUE TITLE
How to use SSL certificate client authentication with ETCD

### ISSUE THREAD

**Issue by kannappan199** [influxdata/chronograf#5576]
How to use SSL certificate client authentication with ETCD for High availability? is this documented somewhere ? is this supported already ?

**Comment by sranka** [comment]
SSL/TLS client authentication configuration is currently not supported in etcd configuration of chronograf. Is this something that you necessarily rely upon, can you please describe your environment?

**Comment by timhallinflux** [comment]
@pierwill will need docs to describe configuration to support security setup.

**Comment by cocampbe** [comment]
I realize a change was made an pushed, but in trying to get chronograf to work with etcd using TLS, I think you need to add the ability to supply the CA cert. At this point I have ditched TLS as it is not working.

**Comment by sranka** [comment]
@cocampbe FYI, this is what for me

__ETCD__
```bash
#generate certificates for etcd
openssl req -newkey rsa:4096 \
            -x509 \
            -sha256 \
            -days 3650 \
            -nodes \
            -out server.crt \
            -keyout server.key \
            -addext "subjectAltName = IP:127.0.0.1" \
            -subj "/C=CZ/ST=Prague/L=Sestajovice/O=Security/OU=IT Department/CN=localhost"
# run etcd with HTTPS endpoint + TLS client authentication
# exclude --client-cert-auth to start HTTPs without TLS client configuration
etcd --cert-file ./server.crt --key-file ./server.key --client-cert-auth -- ./server.crt --advertise-client-urls=https://127.0.0.1:2379 --listen-client-urls=https://127.0.0.1:2379

__Chronograf__
# run chronograf with ETCD over HTTPS with client authentication
# use any certificate that is issued by etcd's --trusted-ca-file
export ETCD_ENDPOINTS=https://127.0.0.1:2379
export ETCD_CERTIFICATE=server.crt
export ETCD_PRIVATE_KEY=server.key
# The etcd server certificate must be trusted by the operating system, but
# the newly generated certificate is not trusted. It has to be added to a trusted certificate store 
# that varies between operating systems, the following environment variable sets a file with trusted certificates on Unix
export SSL_CERT_FILE=server.crt
/home/zavora/devel/influx/influxdata/chronograf/chronograf
```

I guess that adding a new env `ETCD_ROOT_CA` to point to a file that could be specifically used to trust ETCD server certificate might help with TLS trust configuration of ETCD server, it is now part of #5576 . The ETCD server could be then trusted in any OS with
```
export ETCD_ROOT_CA=server.crt
```
