### ISSUE TITLE
Add min/max tls settings and ciphers list to chronograf

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5589]
similar to https://docs.influxdata.com/influxdb/v1.8/administration/config/#recommended-server-configuration-for-modern-compatibility

> I’m looking for a way enforce TLS 1.2 or better only while disabling the use of TLS 1.0 and TLS 1.1 while using the https chronograf endpoint.

we need a way to specify min/max tls versions as well as the list of ciphers. This should be passed on the command line as well as via environment variables like the other options.

https://docs.influxdata.com/chronograf/v1.8/tools/chronograf-cli/#tls-transport-layer-security-flags

**Comment by timhallinflux** [comment]
examples exist in InfluxDB and Kapacitor for these same settings.

**Comment by sranka** [comment]
The following pull request contains similar changes that shall be inspected and followed: 
- https://github.com/influxdata/kapacitor/pull/2198 : Add TLS configuration options
- https://github.com/influxdata/kapacitor/pull/2322 : Add TLS 1.3 support
- https://github.com/influxdata/influxdb/pull/10150 : Allow specifying some TLS configuration.
- https://github.com/influxdata/influxdb/pull/18535 : feat: allow restricting TLS version and ciphers
- https://github.com/influxdata/influxdb/pull/17698 : fix(tls): Enable configuration of TLS 1.3 
-

**Comment by timhallinflux** [comment]
@sranka -- perfect.
