### ISSUE TITLE
Dashboard name truncated even with lots of room

### ISSUE THREAD

**Issue by danatinflux** [influxdata/chronograf#5593]
In the Dashboard view, the name of the dashboard gets truncated regardless of how much space is available:

![image](https://user-images.githubusercontent.com/44617130/95611000-0be44680-0a16-11eb-9894-0a62b3334ac0.png)

It would be great if we could make this larger, or ideally dynamic (e.g. go 'x' pixels until it's 'y' pixels from the 'source' icon).

Thanks!

**Comment by sranka** [comment]
@danatinflux I tried to reproduce this with chronograf 1.8.7 and latest Chrome, Firefox ... it seems to work fine. 

![image](https://user-images.githubusercontent.com/16321466/96472321-a1f74880-1230-11eb-82e1-e758000669d3.png)

Can you please also report chronograf and browser versions that you use?

**Comment by danatinflux** [comment]
@sranka It is in Opera, and appears to have issues with 1.8.4, 1.8.5, and 1.8.6 at least. 

Opera version Version:70.0.3728.178

**Comment by sranka** [comment]
chronograf 1.8.7 + opera 55.0.2994.56 works fine, I also upgraded to the latest stable Opera (71.0.3770.271 on Ubuntu 18.04.5 LTS (x86_64; ubuntu:GNOME)) and it works the same way. The HTML layout looks good ... Can you reproduce the same with Chrome/Firefox? Can you update to the latest stable Opera and try again?

**Comment by danatinflux** [comment]
I'm on a Mac (bleh) if that helps.

Here's my Opera version:

![image](https://user-images.githubusercontent.com/44617130/96497201-2e891300-11ff-11eb-905d-ec2e6f974960.png)


And it looks like it's still doing it:

![image](https://user-images.githubusercontent.com/44617130/96497456-93446d80-11ff-11eb-9f38-d200955b784e.png)

Appears to work fine on Firefox:

![image](https://user-images.githubusercontent.com/44617130/96497619-d43c8200-11ff-11eb-9882-90e41dfe4f7f.png)

**Comment by sranka** [comment]
Thank you for the details, I doubt that Opera on Linux is different in rendering than Opera on Mac, they use the same rendering engines. I think that this issue might be related to your settings of Opera.

**Comment by danatinflux** [comment]
Well, I'm not smart enough to set it up custom---it's all stock afaik. 

If it's just Opera, let's just note it and close it as 'we know, don't care'. :)

**Comment by sranka** [comment]
I can reproduce it now even with Chrome, changing the page zoom is key. 100% (no zoom)  does not reproduce the issue, whereas 80% does.

**Comment by danatinflux** [comment]
Ah! Curse my old eyes! So, is that a fixable thing?
