### ISSUE TITLE
Two informational window annotations is difficult for select and review

### ISSUE THREAD

**Issue by vit1251** [influxdata/chronograf#5605]
Let's I show example for visualization

![image](https://user-images.githubusercontent.com/110534/97369505-1d569b00-18be-11eb-952f-4c885108e156.png)

As you can see on display one single and two window annotations with different labels.

For first ping so easy get pin name but on second section on central point (where two mark so near) it impossible.

When you try to understand that stage name (in my case ) by select mark you always should increase scale for view difference between them. 

Could you please add color highlight annotation?  or make visual little different selected one or way to understand label under cursor.

**Comment by fragmuffin** [comment]
I'd love to see this too!
For our use-case, we've got a solar distribution system in the field, then the following events occur:
- Application Software is update to the latest version, a few hours later
- A fault occurs

It would be really awesome to see something like:
![image](https://user-images.githubusercontent.com/2626190/153534399-6352c86b-0c44-4a27-a6ec-13b056aaba21.png)
Then, using existing features, our service-techs could hover over each to see the version, and fault-code respectively.

**Comment by fragmuffin** [comment]
I'd love to see this too!
For our use-case, we've got a solar distribution system in the field, then the following events occur:
- Application Software is update to the latest version, a few hours later
- A fault occurs

It would be really awesome to see something like:
![chronograf-screenshot](https://user-images.githubusercontent.com/2626190/153535352-52efe2f6-420b-4019-98df-b8b0b4c83294.png)
Then, using existing features, our service-techs could hover over each to see the version, and fault-code respectively.

Another way to approach this feature could be to default all annotations to white (as it is now), then alter their colour based on a `type` (which would be an additional field).... or as a regex on `text` (eg: if `/^fault:/.test(text)` then red)

**Comment by sranka** [comment]
@vit1251 @fragmuffin thank you for a detailed explanation of the use case and for the suggestions of how this could be achieved
