### ISSUE TITLE
Upgrade to golang 1.15

### ISSUE THREAD

**Issue by sranka** [influxdata/chronograf#5609]
The currently used go1.12 is no longer supported. influxdata/influxdb already switched to 1.15 2 months ago

**Comment by timhallinflux** [comment]
Recently, the CVE noted in the subject and in the golang release notice below was announced.

https://groups.google.com/g/golang-announce/c/NpBGTTmKzpM/m/fLguyiM2CAAJ

1.14.12 and 1.15.5 versions of golong have been released with a fix for the vuln.

Please advance to 1.15.5.
