### ISSUE TITLE
Disable InfluxDB Admin page if v1 administration is not possible

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5614]
Currently, Chronograf can be used in compatibility mode with InfluxDB 2.0 OSS and InfluxDB Cloud.  However, neither of these editions provide `X-Influxdb-Version` and `X-Influxdb-Build` headers during the data source connection setup. 

Example headers: 
<img width="574" alt="headers" src="https://user-images.githubusercontent.com/23535264/99751065-55ed2d00-2a96-11eb-88bb-1a2dfa09def8.png">

Even if they did (and these were set to Version = Cloud | OSS and Build = 2.x), the administrative features should no longer be allowed for these editions. Those functions should now be performed within the native UI or via CLI for the 2.0 editions.

I propose displaying some helpful text (rather than the 3 panels currently displayed) if this is the case.  

`These functions are not available for the currently selected InfluxDB Connection.`

We cannot simply hide the "crown" icon as Chronograf can be connected to many different InfluxDB instances...which could be a mix of 1.x and 2.x targets.

**Comment by sranka** [comment]
I think that the `flux` query part of explorer should be also enabled for v2 instances (OSS and cloud), these are currently not detected. As a consequence, the explorer UI  cannot be used against v2 OSS, because the InfluxQL part fails on unsupported `SHOW DATABASES`.

**Comment by timhallinflux** [comment]
@sranka agreed.

**Comment by sranka** [comment]
Chronograf UI still uses InfluxQL for metadata queries (databases, tags, fields) even if the flux source is selected. Flux support for v2 InfluxDB thus requires a bunch of other code changes to work, so rather created #5617 to address it separately.

InfluxDB v2 cloud version now returns valid `X-Influxdb-Version` and `X-Influxdb-Build` headers (2.0; cloud2)  , OSS (2.0.2) returns empty version. `X-Influxdb-Version` can be thus used to distinguish between v1 vs v2 versions.
