### ISSUE TITLE
Add ServiceNow Event Handler UI

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5615]
Provide ability to configure ServiceNow event handler through the UI in the same fashion as Alerta, Telegram, PagerDuty, OpsGenie, etc.

Starting with Kapacitor 1.5.8 there are new event handlers.

**Comment by sranka** [comment]
This issue contained more feature requests, so it was split - BigPanda is now in https://github.com/influxdata/chronograf/issues/5674
