### ISSUE TITLE
Callback error when authenticating with Azure auth

### ISSUE THREAD

**Issue by samhld** [influxdata/chronograf#5625]
RE: callback processor (Line #: 137) from the below mentioned class.

https://github.com/influxdata/chronograf/blob/master/oauth2/mux.go 

```

token, err := conf.Exchange(ctx, code)
if err != nil {
                     log.Error("Unable to exchange code for token ", err.Error())
                     http.Redirect(w, r, j.FailureURL, http.StatusTemporaryRedirect)
                     return
                   }
```

Azure is sending auth callback response properly to the Chronograf instance from the GKE load balancer.

Below are the debug logs came out from the GKE Chronograf instance:

```
time="2020-12-02T19:30:05Z" level=debug msg=Request component=server method=GET  url="/oauth/azuread/callback?code=0.AAAAEWd
time="2020-12-02T19:30:35Z" level=error msg="Unable to exchange code for token context canceled" component=auth
time="2020-12-02T19:30:35Z" level=info msg="Response: Temporary Redirect" component=server method=GET response_time=30.001033915s status=307
```

**Comment by sranka** [comment]
Thank you @samhld for reporting an issue. I assume that the authentication also failed and that the user cannot access chronograf. What is the chronograf version? What is the chronograf OAuth configuration?

**Comment by samhld** [comment]
@sranka Thanks!  Answers below:
* "Did the authentication directly to Chronograf fail as well?"
     - NO --only through LB

* "What is the chronograf version?"
    - 1.8.8

* "What is the chronograf OAuth configuration?"
    - GENERIC with Azure opened connect

**Comment by sranka** [comment]
The `context canceled` error is caused by a networking timeout (30 seconds), it generally means chronograf server is not able to communicate with the configured OAuth token server (configured via GENERIC_TOKEN_URL env). A networking issue in GKE?

**Comment by samhld** [comment]
Issue is fixed -- thanks, @sranka !
