### ISSUE TITLE
LogViewer continues to issue queries in the background

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5629]
I do not have a database configured with the syslog measurement.  However, Chronograf continues to send queries to InfluxDB regularly in a vain attempt to pull the log data.  This seems very leaky.

**Comment by sranka** [comment]
`SELECT count("message") FROM "telegraf"."autogen"."syslog" WHERE time > now() - 30d GROUP BY time(86400s), "severity" FILL(0)` is sometimes not-cancelled and executes regularly after switching from log viewer to explorer.

**Comment by sranka** [comment]
it happens reproducibly when quickly entering and leaving the log view viewer
