### ISSUE TITLE
Handling auth failures -- data source connection setup

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5633]
Reproduction steps:

Start with:
InfluxDB v1 --- with authentication enabled.
Create three users with the following permissions:
influxdb_admin -- admin
influxdb_reader -- read-only permissions for telegraf database
influxdb_writer -- write-only permissions for telegraf database

Fire up a telegraf agent with the following input plugins
- CPU
- Disk
- DiskIO
- Mem
- Net
- Processes
- Swap
- System
use the influxdb v1 output plugin with the influxdb_writer and its password

Test case 1: 
Using InfluxDB v1 auth - attempt to create a data source connection using the admin user.  However, supply an incorrect password. 

_Current Behavior:_ The data source connection dialog acknowledges the connection to the InfluxDB instance (i.e. the URL is correct), but it does not correctly handle the incorrect password.  Subsequently, the Dashboard panel within the data source connection process, just spins as it attempts to load up the metadata.

**Correct Behavior:** Display the error dialog banner on the left -- with a message about incorrect username or password: unauthorized.  Also, display the red x in the progress banner for the connection dialog.  It should appear similar to this:
![Screen Shot 2020-12-08 at 2 10 52 PM](https://user-images.githubusercontent.com/23535264/101547509-32aff200-395f-11eb-8912-c9a552a6bae1.png)

Correct the password and complete the connection setup.

Now upgrade the InfluxDB v1 instance to InfluxDB v2 using the InfluxDB v2.0 upgrade command.

2. Using InfluxDB v1 auth - attempt to create a new data source connection using the read-only user.  However, supply an incorrect password.

_Current Behavior:_ The data source connection dialog acknowledges the connection to the InfluxDB instance (i.e. the URL is correct), but it does not correctly handle the incorrect password.  Subsequently, the Dashboard panel within the data source connection process, just spins as it attempts to load up the metadata.

**Correct Behavior:** Display the error dialog banner on the left -- with a message about incorrect username or password: unauthorized.  Also, display the red x in the progress banner for the connection dialog.  It should appear similar to this:
![Screen Shot 2020-12-08 at 2 10 52 PM](https://user-images.githubusercontent.com/23535264/101547509-32aff200-395f-11eb-8912-c9a552a6bae1.png)  The error response code in this case may be different as it is coming from an InfluxDB v2 instance using the v1 auth compatibility mode.

3. Using InfluxDB v2 auth - attempt to create a new data source connection using the new organization supplied as part of the upgrade process.  Provide an invalid token.

_Current Behavior:_ The data source connection dialog acknowledges the connection to the InfluxDB instance (i.e. the URL is correct), but it does not correctly handle the incorrect token.  Subsequently, the Dashboard panel within the data source connection process loads and the user is able to complete the connection setup.  Data explorer does not function properly because the org/token setup is invalid.

**Correct Behavior:** Display the error dialog banner on the left -- with a message about incorrect organization or token: unauthorized.  Also, display the red x in the progress banner for the connection dialog.  It should appear similar to this:
![Screen Shot 2020-12-08 at 2 10 52 PM](https://user-images.githubusercontent.com/23535264/101547509-32aff200-395f-11eb-8912-c9a552a6bae1.png)  The error response code in this case may be different as it is coming from an InfluxDB v2 instance using the v2 auth. 

Ensure that HTTP 401 errors are captured within the data source connection.  Users should not be allowed to create data source connections with invalid creds either for v1 or v2 editions.

**Comment by sranka** [comment]
chronograf never validated that the supplied credentials are correct. I'll try to add this functionality using

   * v1 auth: "SHOW DATABASES" InfluxQL query
   * v2 auth: "buckets()" FLUX query

These queries can validate credentials even for the simple db/bucket read grants. Users / tokens with write-only grants are IMHO functionally meaningless in chronograf. `SHOW DATABASES` passes for them, but flux's  `buckets()` query fails on 404 with `no buckets found` message.

**Comment by sranka** [comment]
@timhallinflux 
- the credentials will be also validated when the source is updated
- the dashboards panel can get stuck in a loading state even with valid credentials, it is another defect will be fixed
