### ISSUE TITLE
Connection Config Page -- using Database and Retention Policy when InfluxDB v2 Auth is selected

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5636]
![Screen Shot 2020-12-10 at 10 37 37 AM](https://user-images.githubusercontent.com/23535264/101815074-db7f5e00-3ad3-11eb-919f-651a19ab2868.png)

In a connection wizard, when using v2 Auth -- this panel should read:
Telegraf Bucket Name and the Default Retention Policy Field should be greyed out or removed.

**Comment by sranka** [comment]
A lot of UI code injects `telegraf database name` and `default retention policy` into InfluxQL:
  - Dashboards step in a Connection Wizard suggests and modifies protoboards using telegraf database and retention policy
  - the whole `Hosts UI` relies upon telegraf database
  - `Logs UI` prefers `telegraf database name` to show logs from

These labels are now correct unless new FLUX implementations are required.
