### ISSUE TITLE
login with oauth2,but can not logout?

### ISSUE THREAD

**Issue by hfutzhu** [influxdata/chronograf#5644]
i login with oauth2,but when i logout,it can not change user util i reopen the chrome?I set the "AUTH_DURATION"=0

**Comment by sranka** [comment]
Thank you for reporting an issue, can you please share your OAUTH configuration and chronograf version?

**Comment by hfutzhu** [comment]
version is 1.8.5。
config：
export USE_ID_TOKEN="true"
export JWKS_URL="http://198.87.103.221/auth-service/oauth/token_key"  
export GENERIC_NAME="nr-oauth2"
export PUBLIC_URL="http://198.87.91.38:8888"
export GENERIC_CLIENT_ID="client"
export GENERIC_CLIENT_SECRET="client"
export GENERIC_SCOPES="all"
export GENERIC_AUTH_URL="http://198.87.103.221/auth-service/oauth/authorize"
export GENERIC_TOKEN_URL="http://198.87.103.221/auth-service/oauth/token"
export GENERIC_API_KEY="eMail"
export GENERIC_API_URL="http://198.87.103.221/per-service/userInfo/access"

another question : i have another web, then  i want to  enter into the dashboad page without login ？sso login？how can i do ？

**Comment by sranka** [comment]
Thank you @hfutzhu for the details.

> i login with oauth2,but when i logout,it can not change user util i reopen the chrome?

To really log-out in the sense of single-sign-off you need to logout at the identity provider. You can also open a new private/incognito window to force re-authentication.

> i have another web, then i want to enter into the dashboad page without login ？sso login？how can i do ？
```
export REDIR_AUTH_LOGIN=generic
```
will sign in all the users automatically using the generic provider

**Comment by sranka** [comment]
@hfutzhu pls let us now if it helped

**Comment by hfutzhu** [comment]
export REDIR_AUTH_LOGIN=generic? i have a web named "A",i can login "A" with oauth2,there is  a link to chronograf,can i  enter into the chronograf dashboad page without login.? i set the REDIR_AUTH_LOGIN,but no useful.

**Comment by sranka** [comment]
After the users are authenticated, the originally requested (dashboard) URL is lost and the UI appears on the home page. ` REDIR_AUTH_LOGIN=generic` ensures that the users don't have to click the 'Login button' (get redirected to) at the generic provider site.

**Comment by hfutzhu** [comment]
> After the users are authenticated, the originally requested (dashboard) URL is lost and the UI appears on the home page. ` REDIR_AUTH_LOGIN=generic` ensures that the users don't have to click the 'Login button' to start authentication at the generic oauth2 authentication URL.

thanks a lot!i tried a lot,and have resolve it!
