### ISSUE TITLE
How to remove measurements

### ISSUE THREAD

**Issue by Kalypox** [influxdata/chronograf#5650]
Hi,

I have problem with chronograf and influxdb. I'm trying to remove data in my database.
For example:
![image](https://user-images.githubusercontent.com/2879180/103093353-5d09dc80-45fa-11eb-9120-4d318b96daee.png)
I would remove all "capteur_thp" entities.

The doc say:
![image](https://user-images.githubusercontent.com/2879180/103093420-98a4a680-45fa-11eb-8651-6d135ef87abb.png)

But when i try:
DROP MEASUREMENT "home_assistant.autogen"."data"."salon_capteur_thp_battery" for exemple, it doesn't works
I also tried:
DROP MEASUREMENT "salon_capteur_thp_battery"
DROP MEASUREMENT "home_assistant"."salon_capteur_thp_battery"
DROP MEASUREMENT "home_assistant"."data"."salon_capteur_thp_battery"

Any idea please ?

Thanks!

**Comment by sranka** [comment]
This is currently not supported by chronograf, since there is no option to select the active database. See also https://github.com/influxdata/chronograf/issues/5651#issuecomment-753937399 .
