### ISSUE TITLE
Delete series Chronograf Request failed with status code 400

### ISSUE THREAD

**Issue by Erriez** [influxdata/chronograf#5651]
**Problem:**
Cannot delete series via Chronograf, but works on the commandline.

Question asked on Chronograf forum:
https://community.influxdata.com/t/delete-series-chornograf-request-failed-with-status-code-400/17323

**Steps to reproduce:**

Delete some points from a measurement via Chronograf and compared this with the influx commandline:

Chronograf SELECT:

```sql
USE homeassistant
# Request failed with status code 400
# USE looks like not supported in Chronograf

SELECT * from "%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# Database name required
# So use the command below instead:

SELECT * from "homeassistant"."autogen"."%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# Correct output
```

`influxd` terminal SELECT:

```sql
USE "homeassistant"
# Using database homeassistant

SELECT * from "%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# name: %
# time                attribution_str device_class_str domain entity_id      friendly_name friendly_name_str i# con icon_str          value
# ----                --------------- ---------------- ------ ---------      ------------- ----------------- ---- --------          -----
# 1608314274417447936                                  sensor dht22_humidity 22            DHT22 Humidity         mdi:water-percent 12
# 1608314289059613952                                  sensor dht22_humidity 22            DHT22 Humidity         mdi:water-percent 11
# 1608314443618347776                                  sensor dht22_humidity 22            DHT22 Humidity         mdi:water-percent 12

SELECT * from "homeassistant"."autogen"."%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# Same output
```

Chronograf DELETE:

```sql
DELETE from "homeassistant"."autogen"."%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# Request failed with status code 400

# Question: What is the correct DELETE syntax in Chronograf?
```

Influxd terminal DELETE:

```sql
USE homeassistant
# Using database homeassistant

DELETE from "homeassistant"."autogen"."%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# ERR: error parsing query: retention policy not supported at line 1, char 1

DELETE from "%" where entity_id='dht22_humidity' and time < '2020-12-19T15:00:00Z'
# Works
```

**Expected behavior:**
Identical delete series behavior between commandline and Chronograf.

**Actual behavior:**
Cannot delete series via Chronograf which results in `Request failed with status code 400`.

**Environment info:**
* Chronograf: v1.8.8
* InfluxDB:  v3.7.9
* Homeassistant: 2020.12.2
* Home Assistant: OS 5.9

**Config:**
Not applicable.

**Logs:**
Not applicable.

**Comment by sranka** [comment]
A few observations
- the `DELETE` operation expects only the measurement name, it works with an active database
- `USE` is a command that is recognized only by the `influx` tool to set up an active database
- chronograf does not set up any active database for an explorer command, it could be enhanced to support `USE` command as well
