### ISSUE TITLE
Add additional show meta queries to the data explorer

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5661]
We should add the following show commands to the metadata query drop down in data explorer:
![image](https://user-images.githubusercontent.com/4805997/105222647-a113d280-5b0f-11eb-9254-0cc78be15e2f.png)

These commands allow for the `ON db_name` syntax, so they don't need to use the `USE` option:

- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-retention-policies
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-series
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-field-keys
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-tag-values-cardinality

These commands don't require a `db_name` or `use` but might be handy to add as well:

- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-diagnostics
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-subscriptions
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-stats
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shards 
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shard-groups
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-queries
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-grants
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-continuous-queries
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-users

These are related to query performance.

- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain-analyze

**Comment by timhallinflux** [comment]
I believe this is done?  With the exception of explain and explain analyze.  Add those for 1.9.

**Comment by sranka** [comment]
<details>
<summary>Available meta queries in 1.8.10</summary>

- Show Databases : SHOW DATABASES
- Create Database : CREATE DATABASE "db_name"
- Drop Database : DROP DATABASE "db_name"
- Show Measurements : SHOW MEASUREMENTS ON "db_name"
- Show Tag Keys : SHOW TAG KEYS ON "db_name" FROM "measurement_name"
- Show Tag Values : SHOW TAG VALUES ON "db_name" FROM "measurement_name" WITH KEY = "tag_key"
- Show Field Key Cardinality : SHOW FIELD KEY CARDINALITY ON "db_name"
- Show Measurement Cardinality : SHOW MEASUREMENT CARDINALITY ON "db_name"
- Show Series Cardinality : SHOW SERIES CARDINALITY ON "db_name"
- Show Tag Key Cardinality : SHOW TAG KEY CARDINALITY ON "db_name"
- Show Tag Values Cardinality : SHOW TAG VALUES CARDINALITY ON "db_name" WITH KEY = "tag_key"
- Show Retention Policies : SHOW RETENTION POLICIES on "db_name"
- Create Retention Policy : CREATE RETENTION POLICY "rp_name" ON "db_name" DURATION 30d REPLICATION 1 DEFAULT
- Drop Retention Policy : DROP RETENTION POLICY "rp_name" ON "db_name"
- Show Continuous Queries : SHOW CONTINUOUS QUERIES
- Create Continuous Query : CREATE CONTINUOUS QUERY "cq_name" ON "db_name" BEGIN SELECT min("field") INTO "target_measurement" FROM "current_measurement" GROUP BY time(30m) END
- Drop Continuous Query : DROP CONTINUOUS QUERY "cq_name" ON "db_name"
- Show Users : SHOW USERS
- Create User : CREATE USER "username" WITH PASSWORD 'password'
- Create Admin User : CREATE USER "username" WITH PASSWORD 'password' WITH ALL PRIVILEGES
- Drop User : DROP USER "username"
- Drop Measurement : USE "db_name"; DROP MEASUREMENT "measurement_name"
- Drop Series : USE "db_name"; DROP SERIES FROM "measurement_name" WHERE "tag" = 'value'
- Delete : USE "db_name"; DELETE FROM "measurement_name" WHERE "tag" = 'value' AND time < '2020-01-01'
- Show Stats : SHOW STATS
- Show Diagnostics : SHOW DIAGNOSTICS

</details>

The following items are in the scope of this issue:
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-field-keys
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-subscriptions
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shards
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-shard-groups
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-queries
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#show-grants
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain
- https://docs.influxdata.com/influxdb/v1.8/query_language/spec/#explain-analyze
