### ISSUE TITLE
No InfluxDB v2 Auth Slider: Issue with Interfacing Between InfluxDB 2 and Chronograf (latest version: 1.8.8)

### ISSUE THREAD

**Issue by solder-prog** [influxdata/chronograf#5662]
I could use assistance with a seemingly inexplicable problem occurring on the latest version of Chronograf. This is my current version as appearing on the configuration menu (from the left navigation bar):
![Screen Shot 2021-01-28 at 10 22 10 am](https://user-images.githubusercontent.com/77765846/106067458-d002f780-6152-11eb-8216-e496f96099f8.png)
Now this is what I see when I click 'Add Connection':
![Screen Shot 2021-01-28 at 10 22 20 am](https://user-images.githubusercontent.com/77765846/106067450-cc6f7080-6152-11eb-8bae-87a68bdd747f.png)
Reading through documentation and according to what I am trying to accomplish I should see this prompt:
![2-0-tools-chronograf-v2-auth](https://user-images.githubusercontent.com/77765846/106067683-4d2e6c80-6153-11eb-8460-378f0d5ea6c0.png)
I need this to connect to my InfluxDB 2 database but this button is not appearing.
I respectfully ask for suggestions, settings help to address this problem.

**Comment by sranka** [comment]
`v2 Auth` option is available since Chronograf 1.8.9

**Comment by matt-psaltis** [comment]
So question... Where might someone find 1.8.9? Tags on dockerhub have latest at 1.8.8.

Cheers!

**Comment by matt-psaltis** [comment]
Ah I see, the provided helm charts pull 1.8.8 from dockerhub there's a comment in there about using quay.io which is also mentioned in the releases section. So using the latest helm charts seems to pull an old version of Chronograf currently.
