### ISSUE TITLE
Chronograf 1.9 with Kapacitor 1.6 -- Flux tasks

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5663]
As part of the work planned for Kapacitor 1.6 is the introduction of the Flux-based task engine.  Chronograf currently only integrates with Kapacitor via the TICKscript engine.

At the moment, we do not plan to enhance Chronograf to author Flux tasks.  However, we should discuss whether Chronograf should list the Flux tasks and allow for an end user to activate/deactivate them from the UI.

@docmerlin -- we'll likely need to understand how to get the list of Flux tasks via an API as well as understanding the API for activate/deactivate.

**Comment by docmerlin** [comment]
The API should be the same as the influxdb tasks API.

**Comment by ivankudibal** [comment]
Kapacitor -- https://github.com/influxdata/kapacitor/pull/2555

**Comment by sranka** [comment]
Chronograf 1.9 will add the following functionality
1/ a new table with Flux Tasks under Alerting/Manage Task
   - lists all the tasks, activate/inactivate, delete, show detail
   - available only if flux tasks are enabled
2/ a flux task detail page with read-only flux script to show the flux task definition
3/ show tasks runs and possibly logs on a detail page
