### ISSUE TITLE
 Chronograf (1.8.4) n is undefined

### ISSUE THREAD

**Issue by erikvanderburg** [influxdata/chronograf#5669]
What browser are you using (name and version)? Firefox 85.0.2 64 bit

What operating system are you using? Mac OS Catalina 10.15.7

Please describe what you were trying to do when you encountered this error:
Switching predefined views

```
r@http://10.50.0.17:8888/src.bb6c33a8.js:1824:429
value/<@http://10.50.0.17:8888/src.bb6c33a8.js:4234:11871
mi@http://10.50.0.17:8888/src.bb6c33a8.js:717:73830
hi@http://10.50.0.17:8888/src.bb6c33a8.js:717:74057
ja@http://10.50.0.17:8888/src.bb6c33a8.js:717:64606
$a@http://10.50.0.17:8888/src.bb6c33a8.js:717:69008
oo@http://10.50.0.17:8888/src.bb6c33a8.js:717:91057
uo@http://10.50.0.17:8888/src.bb6c33a8.js:717:91442
Yo@http://10.50.0.17:8888/src.bb6c33a8.js:717:98524
$o@http://10.50.0.17:8888/src.bb6c33a8.js:717:97906
eu@http://10.50.0.17:8888/src.bb6c33a8.js:717:99279
Mn@http://10.50.0.17:8888/src.bb6c33a8.js:717:30667

```

**Comment by sranka** [comment]
Thank you for reporting an issue. Can you pls upgrade to 1.8.10, similar errors were fixed since 1.8.4.

**Comment by erikvanderburg** [comment]
Hi,


Thanks for comming back to me. Dockerhub only shows 1.8.8 as latest, is 
this correct?


Thanks in advance,


Met vriendelijke groet/Kind regards,

Erik van der Burg

<https://puur-it.nl>
Postbus 2931, 3800 GK Amersfoort
m +31 6 12706396
Op 25-02-2021 om 06:27 schreef Pavel Závora:

**Comment by sranka** [comment]
For the latest builds, see https://portal.influxdata.com/downloads/ , docker images are available in quay.io
