### ISSUE TITLE
Add cert-based auth for Chronograf HA migration

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5671]
Currently Chronograf HA is only supported using username/password for a secure communication with ETCD.

However, many folks are using cert-based auth to secure access to ETCD.  Adding support for cert-based authentication is the request here.  It appears supported in the general configuration per - https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#etcd-cert
but it is not supported for the migration.

__Desired behavior:__
Allow setting of CA, CERT, and KEY file to be set allowing for:
Migration to work -- here: https://github.com/influxdata/chronograf/blob/master/cmd/chronoctl/migrate.go

* Chronograf version: 1.8.x

**Comment by sranka** [comment]
implementation note: #5612 introduced TLS options to chronograf etcd client

**Comment by sranka** [comment]
FYI: there was no SSL (HTTPS) support at all in `chronoctl migrate`
