### ISSUE TITLE
Meta Service Connection URL in Connection Wizard shows up only under certain condition

### ISSUE THREAD

**Issue by tomklapka** [influxdata/chronograf#5707]
__Steps to reproduce:__
1. Install Chronograf 202103160646~nightly (git: a6f7a90c70c6fa7902f4922f3574ae97a0d7b597)
2. Go to connection wizard
3. Fill in InfluxDB URL, Name, login, password for your InfluxDB v.1 enterprise instance.
4. Wait for Meta Service Connection URL field to show up - it won't show up until you click in the Connection URL field and out again.

__Expected behavior:__
If credentials are mandatory to check the influxdb installation type, then allow to display the Meta Service Connection URL field almost immediately after login and password are filled in. The usual user flow assumes inserting the connection URL first, then connection name, username and password. No further steps should be required.

__Actual behavior:__
Meta Service Connection URL field remains hidden until credentials are filled in and user clicks in and out of the Connection URL field.

__Environment info:__
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"

* Chronograf version: 202103160646~nightly (git: a6f7a90c70c6fa7902f4922f3574ae97a0d7b597)
* Other relevant environment details: InfluxDB Enterprise 1.8.4: https://dl.influxdata.com/enterprise/releases/influxdb-data_1.8.4-c1.8.4_amd64.deb, https://dl.influxdata.com/enterprise/releases/influxdb-meta_1.8.4-c1.8.4_amd64.deb

__Config:__

__Logs:__

**Comment by sranka** [comment]
Thank @tomklapka for reporting an issue. It is reproducible, the following changes are required to fix the issue:
- it also has to react upon changes in username and password fields (as it currently does for URL)
- the connection should be deleted if the user cancels the creation wizard
