### ISSUE TITLE
Failed to add an annotation

### ISSUE THREAD

**Issue by tomklapka** [influxdata/chronograf#5709]
__Steps to reproduce:__
Given User has open Chronograf main page
When Click on Dashboards icon in the sidebar
When Click on the button Create Dashboard
And Clicks on the button Add Data of the newest cell
When Click on the retention policy 'telegraf.autogen' in the graph builder
When Click on the measurement 'cpu' in the graph builder
When Click on the field 'usage_idle' in the graph builder
Then The following query should be ful-filled into the query editor:
SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)
Then name the cell as 'CellToAnnotate1'
When Click on the button Save in the graph builder
When click on the time range drop down
When select the time range value 'Past 15m'
When click on the refresh time drop down
When select the refresh time value 'Paused'
When Activate Annotations
Then annotation controls appear
When Click the Annotate button
Then verify annotation count of '0' in the cell identified by 'CellToAnnotate1'
Then Annotation crosshair appears in the cell identified by 'CellToAnnotate1' - FAILED

![image](https://user-images.githubusercontent.com/30289695/111998473-50732280-8b1c-11eb-9534-b3f9e1088655.png)

__Expected behavior:__
Set the annotation bars in the cell.

__Actual behavior:__
Unable to move cursor to point of time and click or drag cursor to set an annotation.

__Environment info:__
* Chronograf version: 202103212147~nightly (git: 7c171e8e77f193214c87ca4199bff3ba69a11a35) 
* Other relevant environment details:  InfluxDB Enterprise 1.8.4, 

__Logs:__
No errors in log. 
Browser console errors:
src.30b509a4.js:1954 TypeError: Cannot read property 'dashboardID' of undefined
    at Function.w [as mapToProps] (src.30b509a4.js:2961)
    at p (src.30b509a4.js:804)
    at Function.p.mapToProps (src.30b509a4.js:804)
    at p (src.30b509a4.js:804)
    at src.30b509a4.js:814
    at src.30b509a4.js:756
    at Object.useMemo (src.30b509a4.js:726)
    at exports.useMemo (src.30b509a4.js:718)
    at x (src.30b509a4.js:756)
    at ua (src.30b509a4.js:726)

**Comment by sranka** [comment]
Reproducible, annotations cannot be added ... indeed a regression defect.

**Comment by sranka** [comment]
This defect is caused by dependency upgrades in 1.9. It may affect up to 47 components that use both redux `connect` and router `withRouter` HOF.
