### ISSUE TITLE
Flux is marked as disabled when using command line options to connect

### ISSUE THREAD

**Issue by jsternberg** [influxdata/chronograf#5723]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Start a v1 influxdb server with flux enabled.
2. Run chronograf with `--influxdb-url=ADDR`.
3. Attempt to switch to Flux in the data explorer or run a flux query.

__Expected behavior:__
The flux query runs.

__Actual behavior:__
The log says `flux not enabled` and any attempt to run a query returns the same error message.

__Environment info:__

* Chronograf version: 1.8.9.1

__Config:__
When running influxdb, use `INFLUXDB_HTTP_FLUX_ENABLED=true`.

__Logs:__

```
ERRO[0531] Error message Error flux not enabled: <nil>   component=server http_status =400
```

__Additional information:__

It appears that this was introduced by https://github.com/influxdata/chronograf/pull/5631. When you use the command line, the source type is marked as v1 and it relies on the version reported to shield v1 from this section of code. The version does not get filled out when the source is retrieved [here](https://github.com/influxdata/chronograf/blob/master/server/flux.go#L147). This causes the `hasFlux` code to erroneously declare that flux is not enabled because the source type is not v2.

**Comment by sranka** [comment]
Yes, it is indeed a regression defect caused by a configuration path that I didn't try. I am working on it.
