### ISSUE TITLE
Failed to Import Dashboard from File: Unparsable JSON

### ISSUE THREAD

**Issue by jjathman** [influxdata/chronograf#5733]
__Steps to reproduce:__

1. Create empty dashboard using Chronograf v1.8.10
2. Export the dashboard using the UI
2. Try to import the dashboard JSON file into Chronograf v1.7.17
3. Error message is shown

__Expected behavior:__
Import is successful.

__Actual behavior:__
Error message saying "Unparsable JSON"

__Environment info:__

* Chronograf version: 1.8.10 and 1.7.17
* Other relevant environment details: OS type and version, browser type and version, InfluxDB version ...

__Config:__
We are testing out an upgrade to Chronograf 1.8.10 from version 1.7.17. It appears as though any new dashboards created in our test version cannot be exported and then imported into our production version of 1.7.17. 

__Logs:__
`level=error msg="Error message Unparsable JSON" component=server http_status =400`

**Comment by sranka** [comment]
Thank you @jjathman for using chronograf and reporting an issue. 

1. See https://github.com/influxdata/chronograf#compatibility, there are incompatible changes in dashboard files between the versions, these are probably causing this issue.
2. Your steps describe a downgrade procedure that is not supported.

Feel free to reopen the issue with new/updated facts.
