### ISSUE TITLE
Failed to upload and manual entry by "Write Data"

### ISSUE THREAD

**Issue by Iszy-Ami** [influxdata/chronograf#5745]
Steps to reproduce:
1. Given User has open Chronograf main page
2. Click on Explore icon in the sidebar
3. Click on the button Flux
4. Click on the button Write Data 
5. When click on the button Upload File, upload the file and click on the button Write this file 
6. Or click on the button Manual entry, add manually data and click on the button Write

__Expected behavior:__
Except file

__Actual behavior:__
Data write failed: undefined.
in both cases

__Environment info:__
* Chronograf version: v1.8.10
* Other relevant environment details:  InfluxDB version 2.0

**Comment by sranka** [comment]
Thank you @Iszy-Ami for using chronograf and reporting an issue. The UI write functionality is now using V1 API and thus fails against InfluxDB v2.

As a workaround, you can
- use InfluxDB v2 UI to write the data
- use `influx write` command-line tool

It is a defect that the UI offers functionality that does not work, I am working on a solution for v2.
