### ISSUE TITLE
:dashboardTime: disappeared from chronograph query when divide one field by another

### ISSUE THREAD

**Issue by gazon1** [influxdata/chronograf#5766]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. convert query to influxdb:
-  `SELECT sum("post_view_tag_cat_qty_rec") as "a", sum("post_view_05_sec_qty_rec") as "b" FROM "rec"."autogen"."rec_hot_events_by_source" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(3600s) FILL(null)`
-  into http query to chronograph with [this](https://www.utilities-online.info/urlencode) service -> `http://192.168.7.100:8888/sources/1/chronograf/data-explorer?query=SELECT%20sum%28%22post_view_tag_cat_qty_rec%22%29%20as%20%22a%22%2C%20sum%28%22post_view_05_sec_qty_rec%22%29%20as%20%22b%22%20FROM%20%22rec%22.%22autogen%22.%22rec_hot_events_by_source%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20GROUP%20BY%20time%283600s%29%20FILL%28null%29`
 Everything is ok with this query in chronoghaph (look at the picture)
 ![Screenshot from 2021-06-08 13-28-17](https://user-images.githubusercontent.com/22683150/121171143-c86d0100-c85e-11eb-9aac-3194b56bb2a1.png)
2. But if I a add `/` to divide one field by another - `:dashboardTime:` disappeared from chronograph query: 
- convert query `SELECT sum("post_view_tag_cat_qty_rec") / sum("post_view_05_sec_qty_rec") FROM "rec"."autogen"."rec_hot_events_by_source" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(3600s) FILL(null)`
-  to url -> `http://192.168.7.100:8888/sources/1/chronograf/data-explorer?query=SELECT%20sum%28%22post_view_tag_cat_qty_rec%22%29%20/%20sum%28%22post_view_05_sec_qty_rec%22%29%20FROM%20%22rec%22.%22autogen%22.%22rec_hot_events_by_source%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20GROUP%20BY%20time%283600s%29%20FILL%28null%29`

![Screenshot from 2021-06-08 13-29-27](https://user-images.githubusercontent.com/22683150/121171149-ca36c480-c85e-11eb-8081-93d9cdc69f59.png)

__Environment info:__
* I run chronograph  in docker, image `chronograf:latest`

**Comment by sranka** [comment]
@gazon1 Thank you for reporting an issue. 

1. https://portal.influxdata.com/downloads/ contains links to the latest chronograf releases. For the latest influxdata release is now `quay.io/influxdb/chronograf:1.8.10`, which is (as of today) the same as `quay.io/influxdb/chronograf:latest`
2. this issue is also reproducible with the latest release

**Comment by sranka** [comment]
The format of queries that could be used in a query parameter is limited. Field's binary expression is currently not supported. Only field names and a limited set of functions on top of fields are now supported.

https://github.com/influxdata/chronograf/blob/master/influx/query.go#L203

**Comment by gazon1** [comment]
Thank you for reply!

> Field's binary expression is currently not supported. Only field names and a limited set of functions on top of fields are now supported.

So, your pr will fix the issue anyway?

**Comment by sranka** [comment]
Sure ... you can check the next nightly build once #5769 is merged.

**Comment by gazon1** [comment]
Great, thank your for quick reply and quick fix!
