### ISSUE TITLE
Log viewer - Can't listed database in influxdb 2

### ISSUE THREAD

**Issue by Iszy-Ami** [influxdata/chronograf#5780]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. When click on log
2.  choose connection
3. choose database

__Actual behavior:__
I can't  listed my database, just _internal.monitor and telegraf.autogen

__Environment info:__

* Chronograf version: 1.8.10
* Other relevant environment details: InfluxDB version 2

<img width="538" alt="Screenshot 2021-06-24 at 8 56 36" src="https://user-images.githubusercontent.com/56554624/123224356-09f1e300-d4d2-11eb-82be-eb4ef737d2e8.png">

**Comment by sranka** [comment]
Is the database list different to what you can see in Explorer UI / InfluxQL mode?

**Comment by sranka** [comment]
Log viewer works over v1 API, i.e. databases + retention policies with InfluxQL. Re-implement everything with v2 buckets  and flux is not a goal.
