### ISSUE TITLE
Custom canned app (intel_rdt) is not working - Chronograf 1.8.10-1

### ISSUE THREAD

**Issue by medawsonjr** [influxdata/chronograf#5781]
I'm using Telegraf 1.20.0 and have enabled the "intel_rdt" plugin. After the creator of this plugin sent me a patch to make this plugin report in the database in UTC, I was then able to use Query Builder to create a Custom Dashboard from the InfluxDB metrics (measurements show up in the db under "rdt_metrics").

Now, I'd like every host that shows up on the "Host List" screen to have this dashboard show up as an extra option along with "system" under the "Apps" heading. After being advised to use the "new_apps.sh", I created the attached JSON file and added it to the /usr/share/chronograf/canned directory and then restarted the chronograf daemon. However, I can never get it to show up under the "Apps" column alongside "system."

I've verified that the chronograf daemon has the correct directories configured on startup:
````
[mdawson@tms canned]$ ls -l /usr/share/chronograf/canned/intel_rdt.json 
-rw-r--r-- 1 root root 3342 Jun 28 11:23 /usr/share/chronograf/canned/intel_rdt.json
[mdawson@tms protoboards]$ pgrep chronograf
4981
[mdawson@tms protoboards]$ sudo cat /proc/4981/environ
LANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binHOME=/var/lib/chronografLOGNAME=chronografUSER=chronografSHELL=/bin/falseHOST=0.0.0.0PORT=8888BOLT_PATH=/var/lib/chronograf/chronograf-v1.dbCANNED_PATH=/usr/share/chronograf/cannedPROTOBOARDS_PATH=/usr/share/chronograf/protoboards
````
What else do I need to do to get this intel_rdt dashboard enabled?

[intel_rdt.txt](https://github.com/influxdata/chronograf/files/6728510/intel_rdt.txt)

**Comment by medawsonjr** [comment]
**BONUS**: Attached is my earlier futile attempt at creating a JSON file under /usr/share/chronograf/protoboards that mimics other files under that directory to no avail:

[intel_rdt.protoboards.txt](https://github.com/influxdata/chronograf/files/6728669/intel_rdt.protoboards.txt)

**Comment by sranka** [comment]
Your canned 'intel_rdt.txt' has the following errors:
- it is not a valid JSON (validated online at https://jsonformatter.curiousconcept.com)
   - there are several missing commas
   - invalid character '\'' in string escape code
- the measurement name is `rdt_metric`, your queries use it that way

Please try [intel_rdt.json.repaired.txt](https://github.com/influxdata/chronograf/files/6730457/intel_rdt.json.repaired.txt) and let me know.

**Comment by sranka** [comment]
FYI, chronograf 1.9 is now available for download at https://portal.influxdata.com/downloads/ .

**Comment by medawsonjr** [comment]
Worked like a charm! Thanks, Pavel!
