### ISSUE TITLE
Change default replication factor when creating a database

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5785]
The current behavior of Chronograf inputs Replication Factor of 3 when creating a database.
This value should be 2 by default, not 3.

**Comment by sranka** [comment]
Chronograf does not specify a replication factor when creating a database. The default replication factor is thus assigned by InfluxDB, so it is 3 when there are 3 and more nodes, as explained in https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#replication-factor. @russorat this issue should be rather created in influxdb git repo, shouldn't it? @russorat

**Comment by russorat** [comment]
all good. thanks!
