### ISSUE TITLE
Chronograf Build failed.

### ISSUE THREAD

**Issue by amanhcl** [influxdata/chronograf#5789]
go generate -x ./server
go-bindata -o swagger_gen.go -ignore go -nocompress -pkg server .
server/swagger.go:3: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
make: *** [Makefile:68: server/swagger_gen.go] Error 1

Getting this error while building chronograf. kindly help.

**Comment by sranka** [comment]
Install go-bindata:
`go get -u github.com/kevinburke/go-bindata/...`

**Comment by amanhcl** [comment]
i installed it. but still getting same issues.

**Comment by sranka** [comment]
So make sure that go $GOPATH/bin is in the PATH

```
> which go-bindata
/home/abc/.gvm/pkgsets/go1.16/global/bin/go-bindata

> set | grep GO
GOPATH=/home/zavora/.gvm/pkgsets/go1.16/global
GOROOT=/home/zavora/.gvm/gos/go1.16

```

**Comment by amanhcl** [comment]
seems something is wrong. Any idea?

[root@ip-172-31-2-97 src]# go get -u github.com/kevinburke/go-bindata/...
go: downloading github.com/kevinburke/go-bindata v3.22.0+incompatible
[root@ip-172-31-2-97 src]# which go-bindata
/usr/bin/which: no go-bindata in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/go/bin)

**Comment by sranka** [comment]
$GOPATH/bin is missing in the export
```
echo $GOPATH
export PATH=$GOPATH/bin:$PATH
make
```
