### ISSUE TITLE
Rename Chronograf armhf and arm64 rpms

### ISSUE THREAD

**Issue by codyshepherd** [influxdata/chronograf#5790]
The Chronograf arm64 rpm is named in a way that is incompatible with Yum. In the RedHat world, arm64 is called aarch64, and armhf is called armv7hl.

See [this issue in the build-scripts repository](https://github.com/influxdata/build-scripts/issues/6), as well as [a pair](https://github.com/influxdata/influxdb/pull/21749) of [PRs](https://github.com/influxdata/influxdb/pull/21775) to influxdb that change the way the rpm is named. Making this change in chronograf would allow the package to be in line with influxdb and telegraf in how arm architectures are handled by yum.

**Comment by sranka** [comment]
Thank you @codyshepherd for the links that provide a solution to copy to chronograf.
