### ISSUE TITLE
Want to change the Chronograf logo on the Main page.

### ISSUE THREAD

**Issue by amanhcl** [influxdata/chronograf#5793]
![image](https://user-images.githubusercontent.com/87191704/128983872-0100b93f-fdde-4f8f-8dc2-44849a2225c1.png)

Want to change the Chronograf icon on the status page. Tried replacing the svg files in the UI/Assets/images folder but it is not working.

**Comment by sranka** [comment]
It is a `character in a custom `icomoon` font, it is not customizable OOTB.

- https://github.com/influxdata/chronograf/blob/master/ui/src/side_nav/containers/SideNav.tsx#L72
- https://github.com/influxdata/chronograf/blob/master/ui/src/style/fonts/icon-font.scss#L55
