### ISSUE TITLE
NoPermissions button is confusing

### ISSUE THREAD

**Issue by pierwill** [influxdata/chronograf#5797]
__Expected behavior:__
The NoPermissions button should de-select all permissions.

__Actual behavior:__
I can click a set of permissions *and* the NoPermissions button.
How do I know what this will do?
The interface is confusing, and makes the result unclear.

<img width="259" alt="Screen Shot 2021-08-16 at 1 07 27 PM" src="https://user-images.githubusercontent.com/19642016/129609682-9e8fd320-abe1-4a4a-b82d-185ed2204c16.png">

**Comment by sranka** [comment]
Thank you @pierwill for posting an issue. [NoPermissions](https://docs.influxdata.com/enterprise_influxdb/v1.9/features/users/) is unfortunately a permission name of valid permission. It can be assigned together with other permissions. It is not clear to me that `Show Databases` is always possible without this permission.

**Comment by pierwill** [comment]
Okay. Thanks @sranka!
