### ISSUE TITLE
Time format issue when switching to horizontal table

### ISSUE THREAD

**Issue by afausti** [influxdata/chronograf#5800]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. On the Explore tool use table visualization type 
2. Select any Time Format different than Unix time
3. Switch from vertical table to horizontal table

__Expected behavior:__
After switching to horizontal table the Time Format should be respected
__Actual behavior:__
Time format is not respected

__Environment info:__

* Chronograf version: 1.9.0
* Other relevant environment details: macOS Big Sur version 11.5.1, Safari 14.1.2

<img width="1378" alt="Screen Shot 2021-08-27 at 8 58 47 AM" src="https://user-images.githubusercontent.com/13968086/131156571-55c925cc-aebf-4ec3-b4a7-4360b9e051c8.png">

**Comment by sranka** [comment]
Thank you @afausti for reporting an issue.

**Comment by afausti** [comment]
Thanks for fixing it!
