### ISSUE TITLE
As a user, I can see the filter input even if I scroll

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#581]
![scroll-issue](https://cloud.githubusercontent.com/assets/2433762/20401951/9a87bb42-acaf-11e6-9041-dcec31ef8beb.gif)

Probably should move the filter input to be in the right half of the heading

**Comment by nhaugo** [comment]
This should also be applied to the host list view, work with @alexpaxton on the design.

**Comment by alexpaxton** [comment]
@nhaugo tried to do this myself, but wasn't sure how to separate out the field from the thing it's filtering. They seem pretty tightly coupled. Need help

**Comment by 121watts** [comment]
@alexpaxton we can talk about this

**Comment by russorat** [comment]
fixed
