### ISSUE TITLE
v.windowPeriod is not updated when zooming in Dashboards

### ISSUE THREAD

**Issue by tboehme** [influxdata/chronograf#5814]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard with a cell based on a flux query showing a large time horizon (use range(start: dashboardTime, stop: upperDashboardTime) for data selection to work around issue #5810)
2. Use the aggregateWindow(every: v.windowPeriod, fn: mean) to aggregate the data
3. Now zoom into part of the data
4. Notice that the v.windowPeriod does not change and the data is not reloaded with higher resolution

When using InfluxQL and :interval: in Dashboard cells, the data is dynamically reloaded with a higher resolution (note: this only works in Dashboards, not in the explore view)

__Expected behavior:__
When zooming in, I expect v.windowPeriod to be recalculated based on the bounds of the currently displayed range and the data to be refreshed accordingly

__Actual behavior:__
v.windowPeriod depends on the date picker range only and does not change when zooming.

__Environment info:__

* Chronograf version:  1.9.0

**Comment by sranka** [comment]
Thank you from @tboeme for splitting the original issue and providing full reproduction instructions.
