### ISSUE TITLE
Unable to connect to InfluxDB: 401 Unauthorized

### ISSUE THREAD

**Issue by chenlujjj** [influxdata/chronograf#5822]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Install InfluxDB and Chronograf in my Mac using homebrew
2. InfluxDB version is 2.0.8, Chronograf version is 1.9.0
3. Try to connect to influxdb in chronograf, but it reports "Unable to connect to InfluxDB: 401 Unauthorized"

![image](https://user-images.githubusercontent.com/17081528/135558781-805b25f6-bfe7-4c03-ae7b-5e925609846d.png)

Not sure why this happens, the usename and password are correct.

**Comment by sranka** [comment]
Use InfluxDB v2 Authentication with organization and token:
![image](https://user-images.githubusercontent.com/16321466/135576274-eb075bea-e539-4464-931b-7a3abaf6b8a5.png)

Username+password authenticaiton is used against InfuxDB v1

**Comment by chenlujjj** [comment]
@sranka Thanks. Emmm, where is the organization token BTW ?

**Comment by chenlujjj** [comment]
I get it. First time using TICK. :-P
