### ISSUE TITLE
Chronograf opened in multiple tabs starts to reload them and presents same content on all

### ISSUE THREAD

**Issue by maraswrona** [influxdata/chronograf#5826]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open chronograf in the browser in one tab. Run any query.
2. Open the same chronograf in another tab. Try running a different query in this tab.

Cannot produce static screenshot, I could try recording a video to demonstrate this.

__Expected behavior:__
I should be able to open chronograf in multiple tabs, each containing different screen, query or visualization. And work with those tabs independently.

__Actual behavior:__
Both tabs start to periodically refresh automatically, without any action or click. Also when the "query refresh" option is disabled (besides, it's not the query that refreshes, it's entire page reload)

The second tab even if I try to configure another query, refreshes back to what the first tab was showing. Somehow the entire url with path and query string gets copied over and I see the same on tab 1 and tab 2. And it continues refreshing

It started behaving straight after I upgraded chronograf to version 1.9.1. On another machine I'm runnnig version 1.8.5 and this problem doesn't occur.

__Environment info:__

* Chronograf version: 1.9.1 (updated today via yum update)
- OS type and version: amazon linux 1
- browser type and version: chrome 95.0.4638.54
- InfluxDB version: 1.8.10

__Config:__
Default.

**Comment by sranka** [comment]
Thank you @maraswrona for posting a defect. This issue seems to be side-effect of #5808 that was introduced in 1.9.1 .

**Comment by sranka** [comment]
It was a bug in 1.9.1, it will be fixed in [nightly builds](https://portal.influxdata.com/downloads/) once #5830 is merged&closed.

**Comment by sranka** [comment]
The fix is now part of nightly builds that can be downloaded from https://portal.influxdata.com/downloads/
