### ISSUE TITLE
request timeout for more than 1 minute lasting queries

### ISSUE THREAD

**Issue by chrpinedo** [influxdata/chronograf#5828]
I have a query that takes more than 1 minute and it is canceled by chronograf:

```
oct 28 12:06:23 host chronograf[1089]: time="2021-10-28T12:06:23+02:00" level=error msg="Error message Timeout waiting for Influx response" component=server http_status =408
oct 28 12:06:23 host chronograf[1089]: time="2021-10-28T12:06:23+02:00" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="127.0.0.1:60158" response_time=1m0.001019305s status=408
```

The request timeout of influxdb queries should be a configurable parameter. However, it seems it is not configurable https://docs.influxdata.com/chronograf/v1.9/administration/config-options/.

Version of chronograf: 1.9.1
Version of influxdb: 1.8.10

**Comment by sranka** [comment]
Thank you @chrpinedo for posting an issue. AFAIK Chronograf itself does not impose any response timeout for queries. The InfluxDB server (or any proxy on the way to it) has to timeout the response processing.

I also proved this with 1.9.1 and a fake server written in node.js waiting 2 minutes before returning a response

```
const express = require('express')

const port = 8086

const app = express()
app.get('/ping', (req, resp) => {
  resp.set('X-Influxdb-Version', 'v1.8.9')
  resp.sendStatus(204)
  //resp.send('OK')
})
app.all('/query', async (req, resp, next) => {
  resp.set('X-Influxdb-Version', 'v1.8.9')
  resp.set('content-type', 'application/json')
  console.log(req.originalUrl, 'started', new Date().toISOString())

  let i = 120
  const timeReport = setInterval(() => {
    console.log(req.originalUrl, --i)
  }, 1000)
  setTimeout(() => {
    clearInterval(timeReport)
    console.log(req.originalUrl, 'response')
    resp.status(200)
    resp.send('{}')
    next()
  }, i * 1000)
})
app.listen(port, () => {
  console.log(`listening on http://localhost:${port}`)
})
```

**Comment by sranka** [comment]
Closing this as a duplicate issue, see https://github.com/influxdata/chronograf/issues/5829#issuecomment-956080115
