### ISSUE TITLE
query timeout

### ISSUE THREAD

**Issue by h5t4** [influxdata/chronograf#5829]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. select query that takes over a minute 

__Expected behavior:__
Query does not time out after a minute.

__Actual behavior:__
Query times out.  Query in influxdb continues to run and finishes successfully.

__Environment info:__

* Chronograf version: 
/usr/bin/chronograf -v
Chronograf 1.9.1 (git: 8b2a320a)

* Other relevant environment details: OS type and version, browser type and version, InfluxDB version ...
2021-10-28T11:15:17.732411Z	info	InfluxDB starting	{"log_id": "0XTec_P0000", "version": "1.8.10", "branch": "1.8", "commit": "688e697c51fd"}
2021-10-28T11:15:17.732438Z	info	Go runtime	{"log_id": "0XTec_P0000", "version": "go1.13.8", "maxprocs": 16}

__Config:__
\# /usr/lib/systemd/system/chronograf.service
\# If you modify this, please also make sure to edit init.sh

[Unit]
Description=Open source monitoring and visualization UI for the entire TICK stack. 
Documentation="https://www.influxdata.com/time-series-platform/chronograf/"
After=network-online.target

[Service]
User=chronograf
Group=chronograf
Environment="HOST=0.0.0.0"
Environment="PORT=8888"
Environment="BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"
Environment="CANNED_PATH=/usr/share/chronograf/canned"
Environment="PROTOBOARDS_PATH=/usr/share/chronograf/protoboards"
EnvironmentFile=-/etc/default/chronograf
ExecStart=/usr/bin/chronograf $CHRONOGRAF_OPTS
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target

__Logs:__
chronograf[12591]: time="2021-10-28T11:05:06Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:46984" response_time=1m0.060119602s status=408

**Comment by sranka** [comment]
Thank you @h5t4 for posting an issue. I can't reproduce this, as explained in #5823. Is this a regression defect on your side, was it ok prior to chronograf 1.9.1?

**Comment by h5t4** [comment]
Hi,
prior to  1.9.1 we did not have enough data to  generate select query's over a minute. 
Currently it always fails if select from influxDB takes over 1 minute. 
If I open InfluxDB  and do 'SHOW QUERIES '  I always saw that query actually runs after  chronograf stops with message 'Response: Request Timeout' . If I query directly influxdb then my query always finishes as expected. 


[root@tick ~]# journalctl --since today | grep Timeout
Nov 01 07:12:53 tick chronograf[12591]: time="2021-11-01T07:12:53Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:57206" response_time=1m0.038507252s status=408
Nov 01 07:15:22 tick chronograf[12591]: time="2021-11-01T07:15:22Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:57376" response_time=1m0.972306789s status=408
Nov 01 07:15:22 tick chronograf[12591]: time="2021-11-01T07:15:22Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:57390" response_time=1m0.549886429s status=408
Nov 01 07:15:22 tick chronograf[12591]: time="2021-11-01T07:15:22Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:57386" response_time=1m0.565840623s status=408
Nov 01 07:15:22 tick chronograf[12591]: time="2021-11-01T07:15:22Z" level=info msg="Response: Request Timeout" component=server method=POST remote_addr="[::1]:57380" response_time=1m0.991060509s status=40

**Comment by sranka** [comment]
Thank you for sharing more details. It is likely the case that the browser itself or a networking proxy/component in front of chronograf server causes this timeout. Chronograf itself does not impose any request timeout, I already tested/proved this locally with a fake InfluxDB server in https://github.com/influxdata/chronograf/issues/5828#issuecomment-955743869 . You can explore the networking setup on the way to chronograf, for example AWS ELB has a [default timeout of 60 seconds](https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/). You can troubleshoot this also
-  by using a different browser to see if it is still the case
-  trying to execute [the query directly without chronograf](https://docs.influxdata.com/influxdb/v1.8/tools/api/#query-data-with-a-select-statement)  to see if it works fine.

An associated InfluxDB query is indeed not terminated and kept running until it is finished, it should be terminated. This fact is however not related to this issue.

**Comment by h5t4** [comment]
Thank you for pointing me to right direction. 
It was indeed default apache ProxyPass timeout (used for basic authentication).

**Comment by sranka** [comment]
@h5t4 thank you for letting me know about the root cause. Just FYI, chronograf itself also added support basic authentication more than a year ago in https://github.com/influxdata/chronograf/pull/5577
