### ISSUE TITLE
Chronograf Version: 1.8.8 | Unable to get Hosts.

### ISSUE THREAD

**Issue by nayrbbizkit** [influxdata/chronograf#5832]
Hello Folks, 

I just installed a Chronograf version 1.8.8 and having an issue on getting the Data from my Influxdb source to display in Chronograf. I'm getting the message **_Unable to get Hosts_.**, is there a chronograf config files that needs to edit before launching it? I also tried a simple query but i only get a _**Request failed with status code 400**_. Thank you in advance!
![Chrono](https://user-images.githubusercontent.com/88015644/143185302-b665b5c1-ee79-4ecf-9649-28b5d05251db.JPG)
![2021-11-24 14_13_52-Window](https://user-images.githubusercontent.com/88015644/143185418-664b62bc-6a5c-4104-a50f-8845a6e3611b.png)

**Comment by sranka** [comment]
Hi @nayrbbizkit, can you please 
- add a screenshot that shows your InfluxDB connection details
- take a look at the 400 error in the Networking tab inside `Developer Tools` (CTRL+SHIFT+I) of your browser, what is the exact response to a `proxy` request?

**Comment by nayrbbizkit** [comment]
Hi @sranka,
Please see screenshot for your reference. I'm getting the following messages:
_**{code: 400, message: "received status code 401 from server: err: "}
code: 400
message: "received status code 401 from server: err: "**_

![Error 400](https://user-images.githubusercontent.com/88015644/143192092-579dd15e-5c92-4f81-b3ca-44275d60644f.JPG)

**Comment by sranka** [comment]
401 error means that the configured credentials are invalid. You can check your credentials outside of chronograf by opening http://172.22.6.221:8086/query?q=SHOW%20DATABASES .

What version of InfluxDB do you use? The setup is different for 1.8 and 2.x InfluxDB.
Please share also the screen that you see after you click on "Influx 1 (Default)" link.

**Comment by nayrbbizkit** [comment]
@sranka, InfluxDB version is 2.0.2. Btw, my InfluxDB and Chronograf are installed on a standalone/offline host (Centos 8).

I got the message: _**{"code":"unauthorized","message":"unauthorized access"}**_
![Chrono](https://user-images.githubusercontent.com/88015644/143194980-cf753fda-a1ec-4c63-b2b2-5a44af8406bd.JPG)

**Comment by sranka** [comment]
AFAIK the Hosts functionality is not available in InfluxDB v2, so I understand that you can't simply rely upon InfluxDB v2 built-in UI. You have to configure chronograf against InfluxDB v2:

1. upgrade/use chronograf to v1.9.1 to be able to fully communicate with InfluxDB v2
2. configure the InfluxDB connection to use v2 authentication and specify your organization and token, the UI connection wizard let you do it 
3. create "v1 dbrp mapping" for a `telegraf` bucket that is filled with monitoring data (required for the `Hosts` functionality),  see https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/dbrp/ for help. Something like:
   * `influx bucket list --org my-org --token my-token --host http://localhost:8086`
   * `influx v1 dbrp create --org my-org --token my-token --host http://localhost:8086  --bucket-id <telegraf_bucket_id> --db telegraf --rp default --default`
      *  use bucket id of your telegraf bucket from the previous command
   * `influx v1 dbrp list --org my-org --token my-token --host http://localhost:8086`

**Comment by nayrbbizkit** [comment]
Hi @sranka, thank you for your advice It finally shows one of the Host in the Chronograf, but i have more hosts that i want to display in Chronograf how do I create a multiple host using the V1 dbrp mapping? I'm sorry i am new to Influxdata's TIC stack.

Chronograf displayed Host:
![Bucketlist](https://user-images.githubusercontent.com/88015644/143373994-3636aa06-34d0-4cd2-9e13-e989e9259f0d.JPG)

InfluxDB List of Buckets/Host:
![InfluxBucket](https://user-images.githubusercontent.com/88015644/143374066-497d8a43-5b41-4de4-87cf-873c72c79dd6.JPG)

**Comment by sranka** [comment]
Change the configuration of all your telegraf instances to output measurements to the same bucket (which is mapped to v1 `telegraf` db). Telegraf OOTB decorates all measurements with a `host` tag, which is by default a [hostname](https://docs.influxdata.com/telegraf/v1.20/administration/configuration/#agent-configuration) of the server where telegraf runs. Chronograf then recognizes particular hosts using the `host` tag.

**Comment by nayrbbizkit** [comment]
I'm just exploring the Telegraf.conf, do you mean this specific output plugin?

  **## Destination bucket to write into.
#  bucket = ""
#   ## The value of this tag will be used to determine the bucket.  If this
#   ## tag is not set the 'bucket' option is used as the default.
#   # bucket_tag = ""
#
#   ## If true, the bucket tag will not be added to the metric.
#   # exclude_bucket_tag = false**

**Comment by sranka** [comment]
Yes, I mean [influxdb_v2](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb_v2) output.

**Comment by nayrbbizkit** [comment]
Hi @sranka, this is now working thank you so much for your help! 


![Now](https://user-images.githubusercontent.com/88015644/143538371-e775fdf5-05c4-4493-9222-62198ffeedaa.JPG)
