### ISSUE TITLE
Flux query editor/wizard not working on bigger or high cardinality influx database

### ISSUE THREAD

**Issue by MilanJaro** [influxdata/chronograf#5833]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Run chronograf
2. Select datasource and click "Flux"
3. In SCHEMA section select Bucket -> FIELDS -> ... nothing will appear

The same behaviour, when using Flux script wizard - fields will never appear.

__Expected behavior:__
Fields should be listed in SCHEMA and/or flux query wizard. Navigation and related flux queries going to influxdb backend should be optimized and better scoped or make this configurable.

__Actual behavior:__
It's impossible to use flux query editor on larger influx v2 database, because the list of fields is never rendered. By "larger" db I mean influx v2 instance storing data from 1000 linux servers monitored by telegraf and 1 month retention policy, but the same will be true for databases with high cardinality. Root cause seems to be the flux query for fields, which is fired by chronograf after selection of bucket:
```
from(bucket:"XYZ")
|>range(start:-30d)
|>group(columns:["_field","_measurement"],mode:"by")
|>distinct(column:"_field")
|>group()
|>map(fn:(r)=>({_measurement:r._measurement,_field:r._field}))
```
The query has hardcoded 30 days and trying to list all fields from all measurements in database. This is not only doing flux editor in chronograf useless, but also puts very high I/O load on influx database (which can go out of memory after this query).

__Environment info:__

* Chronograf version: 1.9.1
* Other relevant environment details: Centos 20.04.LTS, chronograf running in docker container, InfluxDB version 2.1.1

__Config:__
default

**Comment by sranka** [comment]
Thank you @MilanJaro for reporting an issue, a solution might described in https://github.com/influxdata/feature-requests/issues/329. Do you encounter the same issue with InfluxDB v2 flux/query editor?

**Comment by MilanJaro** [comment]
@sranka, hard to answer, I am not able to acces the link above - page not found.

**Comment by sranka** [comment]
@MilanJaro the link target requests backporting of v2 UI flux editor/wizard to chronograf. Can you please try InfuxDB v2 UI and check whether it works fine with your data?

**Comment by MilanJaro** [comment]
OK, in InfluxDB v2 UI it's working fine. The navigation (and related queries) is directly focused to the initial selection. The first query is just listing measurements limited to 200 items and selected time frame. This is fast. I would expect similar functionality in chronograf.
