### ISSUE TITLE
 Chronograf (1.9.1) Minified React error 

### ISSUE THREAD

**Issue by hj91** [influxdata/chronograf#5835]
Sudden crash on an ubuntu 18.04 machine

**Comment by sranka** [comment]
Thank you @hj91 for posting an issue. It is not clear what crashed (server / browser / ubuntu ). Can you please add stacktraces (browser/server) and actions taken so it could be possibly reproduced?

**Comment by hj91** [comment]
I don't have the relevant data right now so I am closing the issue for now. Will reopen it or create new one when this error reappears.
