### ISSUE TITLE
Flux-based dashboard does not respect selected dashboard range for display

### ISSUE THREAD

**Issue by jat255** [influxdata/chronograf#5846]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a flux query that covers a time range where there is no data
2. Set dashboard window to same range
3. View that dashboard to observe that the view is limited to just the time span where there is data

![image](https://user-images.githubusercontent.com/1278301/151226230-45afe6de-578f-4393-9a93-4373347442a8.png)

```
from(bucket: "solar_stats/autogen")
  |> range(start: dashboardTime, stop: upperDashboardTime)
  |> filter(fn: (r) => r._measurement == "inverter_data" and (r._field == "TodaysEnergy" and r._value >= 0))
```

__Expected behavior:__

I would expect that this would behave similarly to InfluxQL-based queries, where the null-data range is still shown, even if no data is present, as that's how things work with InfluxQL queries:

```
SELECT mean("TodaysEnergy") AS "mean_TodaysEnergy" FROM "solar_stats"."autogen"."inverter_data" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)
```

![image](https://user-images.githubusercontent.com/1278301/151226793-43b07673-9712-4f8b-997d-1c89a496a2d4.png)

I cannot use an InfluxQL query for this, as I need the use of `aggregateWindow()` in my actual application (my example above is simplified to more clearly demonstrate the behavior).

__Actual behavior:__

The dashboard view range is limited to just the range that has data defined.

__Environment info:__

* Chronograf version: v1.9.3
* Other relevant environment details: Arch Linux, Chrome browser v97, InfluxDB version: 1.8.10

Perhaps this could be controlled by an additional flag to the `range()` function?

**Comment by jat255** [comment]
It also does not make a difference if I explicitly set the time range (which is my actual application):

```
from(bucket: "solar_stats/autogen")
  |> range(start: -30d)
  |> filter(fn: (r) => r._measurement == "inverter_data" and (r._field == "TodaysEnergy" and r._value >= 0))
```

![image](https://user-images.githubusercontent.com/1278301/151227585-baa40ee7-8a78-4ac3-b4f1-c5a14cdf411e.png)

**Comment by sranka** [comment]
Thank you @jat255 for posting an issue. An equivalent flux query is a bit different, you have to require to return empty data for windows without data (as you do with FILL`(null)`) in influxQL:

```
from(bucket: "solar_stats/autogen")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "inverter_data" and (r._field == "TodaysEnergy" and r._value >= 0))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
  |> yield(name: "mean")
```

**Comment by sranka** [comment]
See https://docs.influxdata.com/flux/v0.x/stdlib/universe/aggregatewindow/#createempty for details.

**Comment by jat255** [comment]
Thanks for the assistance. 

This works:

```
from(bucket: "solar_stats/autogen")
  |> range(start: -30d)
  |> filter(fn: (r) => r._measurement == "inverter_data" and (r._field == "TodaysEnergy" and r._value >= 0))
  |> aggregateWindow(every: 10m, fn: mean, createEmpty:true)
```

![image](https://user-images.githubusercontent.com/1278301/151233901-1b28a051-4a38-4ca4-a7f6-5db7106a4c17.png)


But this does not:

```
from(bucket: "solar_stats/autogen")
  |> range(start: -30d)
  |> filter(fn: (r) => r._measurement == "inverter_data" and (r._field == "TodaysEnergy" and r._value >= 0))
  |> aggregateWindow(every: 10m, fn: mean, createEmpty:true)
  |> timeShift(duration: -6h)
  |> aggregateWindow(every: 1d, fn: last, createEmpty: true)
```
![image](https://user-images.githubusercontent.com/1278301/151233858-d0de9362-a13e-4457-9076-0654c9995218.png)


Is that because `last` is a selector and not an aggregator? What I'm ultimately after is the last value of "TodaysEnergy" for each day (the `timeShift` thing is a workaround for my timezone) over the last 30 days, even if those values are empty.

**Comment by sranka** [comment]
It works as you/I expect with the latest InfluxDB v2, but it seems to me that InfluxDB 1.8.10 skips empty tables with the `last` function selector. Please join [influxdata slack](https://community.influxdata.com/) and ask in a `flux` channel, you might get better answers regarding flux therein. The following workaround uses an expanded version of an `aggregateWindow` function to fill a constant value when no data are available.

```
from(bucket: "my-bucket")
  |> range(start: -30d)
  |> filter(fn: (r) => r["_measurement"] == "temperature2")
  |> window(every: v.windowPeriod, createEmpty: true)
  |> mean()
  |> duplicate(column: "_stop", as: "_time")
  |> window(every: inf, timeColumn: "_time")
  |> timeShift(duration: -6h)
  |> window(every: 1d, createEmpty: true)
  |> fill(value: -1.0)
  |> last()
  |> window(every: 1d, createEmpty: true)
  |> map(fn: (r) => ({r with  _value: if r._value < 0.0 then 0.0 else r._value }))
  |> duplicate(column: "_stop", as: "_time")
  |> window(every: inf, timeColumn: "_time")
```

**Comment by jat255** [comment]
Thanks for your help @sranka I had been putting off upgrading to 2.0+, so perhaps this will encourage me to do it!

**Comment by jat255** [comment]
Just confirming the method you suggested @sranka works fine in 2.1.1/Chronograf 1.9. Thanks again!
