### ISSUE TITLE
Graph legend values

### ISSUE THREAD

**Issue by RobMBSos** [influxdata/chronograf#5847]
I have moved from InfluxDB v1 to v2 and updated Chronograf too.
In the old visualization, I was able you use value legends as an alias at the Dashboards Data; check image:
![image](https://user-images.githubusercontent.com/15978656/151340435-8e2afa2d-4262-4df6-b0e7-24dd5f3462ef.png)
In the last version of Chronograf using Flux and InfluxDB, I am not able to change the legend, so it shows the full route to the data:
![image](https://user-images.githubusercontent.com/15978656/151340654-b046c1fc-f1b4-4a72-8f10-32e8ebf51f00.png)
I do not know if it is trivial, and I did not find the way to do it, or It should be a "Feature request" for a future build.
Thanks,
Roberto.

**Comment by sranka** [comment]
Thank you @RobMBSos for posting an issue. It sounds like a regression after an upgrade, but it is probably not, right? If you switched from InfluxQL to Flux, the visualizations are a bit different. You might be able to change the flux query to get a better legend (with a help of [drop](https://docs.influxdata.com/flux/v0.x/stdlib/universe/drop/) ), but it is currently hard to determine from your description. Knowing the type of visualization and a digest of result data would help.

AFAIK you cannot change value legend in chronograf. You can try the built-in UI of InfluxDB v2 if it is better.

**Comment by RobMBSos** [comment]
Dear @sranka thank you so much for your help.
I have tried the drop option, and it works for making the legend shorter:
![image](https://user-images.githubusercontent.com/15978656/151358944-226eda94-517f-46e6-8412-8b01d17b16ea.png)
The last problem for us is the topic value (v3/sevilleschools.....). How can I modify its name to an alias or a shorter version?
In old Chronograf using InfluxQL language, we did as:
mean("uplink_message_decoded_payload_xxx") AS "alias" but in Flux and new Chronograf I do not know how to.
Best, 
Roberto.

**Comment by sranka** [comment]
[map](https://docs.influxdata.com/flux/v0.x/stdlib/universe/map/) and/or [rename](https://docs.influxdata.com/flux/v0.x/stdlib/universe/map/) will help. 

Join [influxdata slack](https://community.influxdata.com/) and ask in a `flux` channel, you can ask about flux therein.

**Comment by RobMBSos** [comment]
@sranka thank you so much; I will do it!

**Comment by sranka** [comment]
Thank you @RobMBSos for your help. This works with v2 UI ... but does not in chronograf that parses flux using older flux API (which does have complex functions and dict library). This will work in chronograf:

```
topicAlias = (topicKey) => if topicKey == "v1" then "replacement1"
     else if topicKey == "v2" then "replacement2"
     else topicKey
```
