### ISSUE TITLE
Chronograf not displaying all tags of measurement

### ISSUE THREAD

**Issue by KannappanSomu** [influxdata/chronograf#5850]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.  open disk measurement from telegraf db
2. host and path tag missing in ui
3. but its present in db , verified via `show tag key` command and its visible in grafana as well 
4. developer tools of chronograf on browser says `show tag key `command successfull and returning all tags , but missing from ui 
![image](https://user-images.githubusercontent.com/55806176/152172380-a8229bd0-c135-45ad-a9c1-be415d4bb0e2.png)

![image](https://user-images.githubusercontent.com/55806176/152172609-22689487-7d1a-45a5-8419-8915c5a1377e.png)

![image](https://user-images.githubusercontent.com/55806176/152171929-8959cfe0-45fe-4842-8b05-03857a5010e0.png)

__Expected behavior:__
display all expected tags 

__Actual behavior:__
tags missing

__Environment info:__

* Chronograf version: 1.9.0 and 1.9.1

**Comment by sranka** [comment]
Thank you @KannappanSomu for reporting an issue. I appreciate that you added more details about the executed query, the UI list is however populated using a next query, which is:

```
SHOW TAG VALUES FROM "${rp}"."${_.escape(
    measurement
  )}" WITH KEY IN (${KEYS_OF_SHOW_TAGS_KEYS_QUERY})
```

Can you please share the results of the second query as they appear in the developer console? I can't reproduce your issue locally.

**Comment by KannappanSomu** [comment]
here is the request payload for second query , it includes host and tag keys , but UI is not displaying it 

`SHOW TAG VALUES FROM "autogen"."disk" WITH KEY IN ("_environment", "_resourcegroup_", "_subscription_", "application", "device", "fstype", "host", "mode", "path")`

![image](https://user-images.githubusercontent.com/55806176/152185673-fe59b5d1-295a-41b7-9f37-33627bea0ccd.png)

**Comment by KannappanSomu** [comment]
it doesnt work in 1.8.10 version as well

**Comment by sranka** [comment]
Thank you, I need the full response JSON (from the response tab) in order to continue with an investigation.

**Comment by sranka** [comment]
It is very likely that the server response is truncated because there are too many results.

**Comment by KannappanSomu** [comment]
yes , response has too many results as there is lot of  device tag values , how do we prevent this ? 


i m not able to paste full results here : 


{"results":[{"statement_id":0,"series":[{"name":"disk","columns":["key","value"],"values":[["_environment","pdev"],["_resourcegroup_","RG-INFLUX-ENTERPISE_DEV_WESTEU"],["_resourcegroup_","cl-elastic"],["_resourcegroup_","rg-influx-enterpise_dev_westeu"],["_resourcegroup_","rg-influx-enterpise_prod_westeu"],["_subscription_","DE Metrics Monitoring"],["_subscription_","de_metrics_monitoring"],["_subscription_","ims_general"],["application","Elastic Stack"],["application","Kafka"],["device","//catianasshare3.got.volvocars.net/9413-app-nasc3pngma0001"],["device","//closvw1165.cloud.volvocars.net/EPC_Jenkins_SW"],["device","//cm4dgot.vccnet.volvocars.net/config/TeamCenter/NRINT"],["device","//gbw9061118/proj/9413-shr-vc055900/61143(mosterga)/10_Systems/SAMS/TCidReplacement/docs"],["device","//gensvw1006.gen.volvocars.net/screendumps"],["device","//gensvw1012.gen.volvocars.net/VCCKIOSK"],["device","//gensvw1206.gen.volvocars.net/GBDATHUB"],["device","//gotcnmhm05.got.volvocars.net/9413-APP-NASANS-SYM/sympathy_logs"],["device","//gotsnm5101.got.volvocars.net/9413-app-naseldata/ElShare"],["device","//gotsnm5101/9413-APP-NASELDATA/ELShare"],["device","//gotsnm5303.got.volvocars.net/9413-app-nasc3pngma0001"],["device","//gotsvw11523.got.volvocars.net/WAS_Import"],["device","//nasweucvot2002p.got.volvocars.net/C_95400_DATA/"],["device","//qa1756010.got.volvocars.net/plasmoAdvancedData/Data"],["device","//seamt1756010left.got.volvocars.net/d$/PermaTrack/logs/"],["device","//seamt1756010right.got.volvocars.net/d$/PermaTrack/logs/"],["device","//vccsawesapdeplnprd.file.core.windows.net/sapinstallation"],["device","10.120.2.109:/9413-SHR-TAS-ScrewJointArchive"],["device","10.120.2.135:/9413-APP-NASVIDA0001/QA/VCC1113G"],["device","10.122.72.138:/9413-APP-NAS-GOTEdgeMigration2P"],["device","10.122.72.70:/9413-APP-NASWICE-Archival_New"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/OpenHarmony"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/aosp"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/aosp_ihu5_spa2"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/aosp_p"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/aosp_q_cx"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/genivi"],["device","10.237.14.134:/cm_new/repo-mirror-ssh/teslamotors"],["device","10.237.21.14:/ADAS/log"],

..
..
..

**Comment by sranka** [comment]
> yes , response has too many results as there is lot of device tag values , how do we prevent this ?

The code now loads all tag values using a single query. If the server does not return all values, the UI will not display the tags that you expect. You can inspect your InfluxDB server's https://docs.influxdata.com/influxdb/v1.8/administration/config/#max-row-limit--0 configuration and change it so that all values are returned.

**Comment by KannappanSomu** [comment]
we have default config , which as per documentation says will return unlimited rows.
 So what changes should we do in the config ?

**Comment by sranka** [comment]
Can you please attach a zip of the full response, so we could possibly later resume the investigation?
