### ISSUE TITLE
Tag values displayed as numbers in table graph when they are in a number-like format (leading '0x' or containing only numbers)

### ISSUE THREAD

**Issue by st-mono** [influxdata/chronograf#5857]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Using Influx CLI, create a test database with the following commands:
   ```
   create database tagvaluetest
   use tagvaluetest
   insert testing,testtag=01234567 aField=42
   insert testing,testtag=0x01234567 aField=42
   insert testing,testtag=0b01234567 aField=42
   insert testing,testtag=1234567 aField=42
   insert testing,testtag=0x12345678 aField=42
   ```
2. Using Influx CLI check the tag values:
`SHOW TAG VALUES ON "tagvaluetest" FROM "testing" WITH KEY = "testtag"`

   which gives the following results:
   ```
   name: testing
   key     value
   ---     -----
   testtag 01234567
   testtag 0b01234567
   testtag 0x01234567
   testtag 0x12345678
   testtag 1234567
   ```

3. Check the tag values on Chronograf
![image](https://user-images.githubusercontent.com/65218708/153191095-827e661d-d271-440b-945b-c4b784b9fe60.png)
Looks OK so far...

4. Run the following query and view it with table graph visualisation:
`SHOW TAG VALUES ON "tagvaluetest" FROM "testing" WITH KEY = "testtag"`
![image](https://user-images.githubusercontent.com/65218708/153191461-9bdfa87d-a502-4b16-88b4-b193a49f4807.png)
...and get the above result, where most of the tag values which start with "0" or "0x" are interpreted as numbers

5. It also displays incorrectly as a result of a `SELECT "aField", "testtag" FROM "tagvaluetest"."autogen"."testing"` query:
![image](https://user-images.githubusercontent.com/65218708/153193666-309b538f-2312-40bd-804f-f5e2c52b37a3.png)

__Expected behavior:__
As tag values are always strings, they should be dispayed as strings.

__Actual behavior:__
In the table graph of the results, the tag values that are somewhat number-like are listed in the table as numbers, rather than as a string.

__Environment info:__

* Chronograf version: Tested on 1.8.8 and 1.9.3
* Other relevant environment details:
  * OS type and version: Windows 10
  * Browser type and version: Mozilla Firefox 96.0.3 (64-bit), although seen on earlier versions too, Chrome Version 98.0.4758.82 (Official Build) (64-bit), Microsoft Edge Version 98.0.1108.43 (Official build) (64-bit)
  * InfluxDB version: 1.8.6

__Config:__
Default

**Comment by sranka** [comment]
Thank you @st-mono for reporting an issue with detailed instructions on how to reproduce it.

**Comment by sranka** [comment]
The current table cell also renders numbers out of string values that are parseable as numbers. This was also the state at least since chronograf 1.7.15 (there were some changes in #5073). There is a reason/consequence for doing so that must be first re-discovered before I try to fix this.

**Comment by sranka** [comment]
Unfortunately, the same table is used to visualize flux results that are currently always strings (even for data columns that carry only numbers).
