### ISSUE TITLE
Can't specify telegraf db

### ISSUE THREAD

**Issue by unixninja92** [influxdata/chronograf#586]
We use a non standard db name for telegraf metrics. The host list is currently empty because of this.

**Comment by goller** [comment]
Thank you for submitting the issue!  We'll try to finish in the next few hours.

We're going to add an input field to the connection screen allowing you to specify the telegraf database.

**Comment by unixninja92** [comment]
Thanks! Will it be in the quay.io docker hub?

**Comment by goller** [comment]
@unixninja92 Ok, fixed!

Here is what the connection screen looks like now:

<img width="784" alt="welcome" src="https://cloud.githubusercontent.com/assets/1922921/20450526/da8c70ea-adb6-11e6-829c-e247a5911ca8.png">

As for docker, yup, I've pushed up a new image to `quay.io/influxdb/chronograf:latest`

As an aside, we push up docker images to quay.io for each commit; they are tagged with the first 8 characters of the commit SHA.  For example, our merge commit was `62da746` and we push up 
`quay.io/influxdb/chronograf:62da746`

Let us know how if it works out!

**Comment by unixninja92** [comment]
You can't edit the telegraf database text field on the Welcome to Chronograf screen. It works when editing an existing influx db.

**Comment by unixninja92** [comment]
Not sure if this is a different issue or if it's related but it seems to take a while (30s+) for the host list to show what "apps" each host has.

**Comment by nhaugo** [comment]
The text edit box in the welcome page is not editable

**Comment by willpiers** [comment]
@unixninja92 fixed in master!

**Comment by sarthakbansal** [comment]
Host list is empty:
![image](https://cloud.githubusercontent.com/assets/14152438/21822105/f95aa4e2-d79b-11e6-9120-c2f9049e3033.png)

I'm only able to visualise database fields:
![image](https://cloud.githubusercontent.com/assets/14152438/21822157/22f0e65e-d79c-11e6-93cd-9ab444b938b4.png)

**Comment by goller** [comment]
@sarthakbansal Thanks for writing in!  I'm not sure how this relates to this issue #586.  If it relates, would add some more information?

If not, would you create a new issue?  Also, would you open up the web console and send us some information about what is happening in the host list?

**Comment by goller** [comment]
Ah @sarthakbansal I figured it out.  You need to update your telegraf configuration on windows.  

Check out my telegraf PR here: https://github.com/influxdata/telegraf/commit/fbf5bee051740155c7de8518fe137c87d9fced6e#diff-a39c8cf99e09bfef0f19651e4385b131   This shows you how to add the correct fields to windows.

Basically, make sure you have `Processor Queue Length` in your `inputs.win_perf_counters.object`:
```
  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
]
```
