### ISSUE TITLE
Chronograf Azure AD graph API deprecating , is microsoft graph api supported ? 

### ISSUE THREAD

**Issue by KannappanSomu** [influxdata/chronograf#5864]
1. Azure AD graph API is deprecating  in june , In documentation example https://docs.influxdata.com/chronograf/v1.9/administration/managing-security/#set-configurations-for-your-oauth-provider ,              
 I can see its using Azure AD graph API  (Domain : **graph.windows.net**)

2. Is the new microsoft graph API (Domain: **graph.microsoft.com**) supported already with chronograf ? Is this documented somewhere ? please provide examples to use OAUTH2.0 with microsoft graph API

**Comment by sranka** [comment]
Thank you for letting us know, chronograf needs a valid OpenID UserInfo endpoint to receive information about an authenticated user. This is still hosted (according to MS docs) at `graph.windows.net`. If you know the new way how to configure Azure AD, please let us know so we can update and repair the docs.

**Comment by KannappanSomu** [comment]
@sranka will test in our dummy environment and get back to you

**Comment by KannappanSomu** [comment]
Hi @sranka , 

Changing below two environment variable values , I was able to switch from Azure AD graph API to microsoft Graph API. 

**Prerequisite:** 

Azure AD application should have below permission for MS graph API

![image](https://user-images.githubusercontent.com/55806176/154249459-4c5d4aa4-fe00-4b60-87f0-46cccb5f0927.png)


`old value:`

`GENERIC_AUTH_URL=https://login.microsoftonline.com/<<TENANT-ID>>/oauth2/authorize?resource=https://`graph.windows.net``

`GENERIC_API_URL=https://`graph.windows.net`/**<<TENANT-ID>>**/me`?api-version=1.6``

`new value:`

`GENERIC_AUTH_URL=https://login.microsoftonline.com/<<TENANT-ID>>/oauth2/authorize?resource=https://`graph.microsoft.com``

`GENERIC_API_URL=https://`graph.microsoft.com/v1.0/me``


Changes done: 

- change domain from  `graph.windows.net` to `graph.windows.net`
- refer [microsoft document](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences#basic-requests) to restructure GENERIC_API_URL with` tenant id` **removed** from it as its optional value
- All the other values remain same as per existing documentation

Please test this at your end as well.

Also let me know how to contribute to your documents section `( is it hosted in GITHUB ? )` , so we can have seperate section for Azure AD with MS graph api at this location - https://docs.influxdata.com/chronograf/v1.9/administration/managing-security/#set-configurations-for-your-oauth-provider

**Comment by sranka** [comment]
Your doc changes look good to me. You can start a new documentation issue at the bottom of the affected documentation page:

![image](https://user-images.githubusercontent.com/16321466/154256456-31123027-2a34-4b3e-8951-4f4a235bafbc.png)

... or you may also contribute directly to the docs. Follow https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md and create a pull request that changes https://github.com/influxdata/docs-v2/blob/master/content/chronograf/v1.9/administration/managing-security.md


Thank you very much for your contribution!
