### ISSUE TITLE
Kapacitor is not running

### ISSUE THREAD

**Issue by mashirali** [influxdata/chronograf#5870]
<!-- Description for the error no host found>

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... just clone this loudml/chronograf repo and make the docker-compose up
2. ... No hosts found will be shown there

__Expected behavior:__
model for loudml has to work

__Actual behavior:__
No hosts found

__Environment info:__
Docker ENV

* Chronograf version: 
* Other relevant environment details: OS type and version, browser type and version, InfluxDB version ...

__Config:__
datasources:
  - name: influx
    type: influxdb
    addr: 192.168.160.1:8086
    database: telegraf
    measurement: loudml
  - name: kapacitor
    type: influxdb
    addr: 192.168.160.1:9092
    database: from_loudml
    measurement: loudml

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077

__Logs:__
Include a snippet of errors in the log.
![Screenshot 2022-02-22 123257](https://user-images.githubusercontent.com/57099739/155083923-c947dd40-c13d-484d-aad8-b5ac65b96a94.png)

**Comment by mashirali** [comment]
![Screenshot 2022-02-22 123257](https://user-images.githubusercontent.com/57099739/155113198-9f341d26-3def-4bd1-8954-afcca9cb55b3.png)
kapacitor is down

**Comment by sranka** [comment]
Can you please explain what is the issue herein and how is it related to chronograf?

**Comment by sranka** [comment]
Feel free to reopen with details of what is the issue on the chronograf side.
