### ISSUE TITLE
Unable to connect to source

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/chronograf#588]
While adding new source chronograf is showing `Unable to connect to source`. Though i am able to make curl request as you said.

**Comment by jademcgough** [comment]
Hi Gaurav,

There are two things I'd recommend trying:
- Make sure that you're specifying the correct protocol (`http` or `https`) and port for the influxdb server in your source (e.g. `http://localhost:8086`).
- Try refreshing the app in your browser after adding the source. There's a bug around adding new sources that I'm in the process of fixing.

Let me know if either of those fixes the issue.

**Comment by goller** [comment]
@gaurav-moonfroglabs Thanks for sending this in.

In lieu of adding the error message to the user interface,  I've added more extensive error logging to the server process.  

If you download master (or tonight's nightlies) you'll be able to get more information about the connection issue in the server logs.

Would you be able to attach them to this issue?

**Comment by gaurav-moonfroglabs** [comment]
Hey Goller,

Thanks for adding the logs... i will definitely pull the master for latest changes. Yes i have been working with the master branch of chronograf.

Will attach logs while trying with new logs you have put.
