### ISSUE TITLE
Host List TZ toggle broken

### ISSUE THREAD

**Issue by tjamesking** [influxdata/chronograf#5883]
__Steps to reproduce:__

1. ... Open the Hosts Lists view in Chronograf
2. ... Select a host
3. ... Timestamps are shown in UTC, click Local toggle to show in localtime

__Expected behavior:__
Timestamps change from UTC to localtime.

__Actual behavior:__
TZ cannot be changed in Host List view, currently selected option is not shaded, error appears in JS console when toggle is clicked.

TZ toggle in Dashboard and Explore views work as expected.

__Environment info:__

* Chronograf version: 1.9.3
* Other relevant environment details: mac OS 11.6.4, Firefox 97.0.2 / Chrome 99.0.4844.74, InfluxDB Enterprise 1.9.1

__Logs:__
Uncaught TypeError: e.onClick is not a function
    <anonymous> http://localhost:8888/src.523fb700.js:2325
    l http://localhost:8888/src.523fb700.js:726
    s http://localhost:8888/src.523fb700.js:726
    f http://localhost:8888/src.523fb700.js:726
    h http://localhost:8888/src.523fb700.js:726
    st http://localhost:8888/src.523fb700.js:726
    ut http://localhost:8888/src.523fb700.js:726
    ft http://localhost:8888/src.523fb700.js:726
    vt http://localhost:8888/src.523fb700.js:726
    R http://localhost:8888/src.523fb700.js:726
    A http://localhost:8888/src.523fb700.js:726
    ln http://localhost:8888/src.523fb700.js:726
    rn http://localhost:8888/src.523fb700.js:726
    unstable_runWithPriority http://localhost:8888/src.523fb700.js:722
    ri http://localhost:8888/src.523fb700.js:726
    F http://localhost:8888/src.523fb700.js:726
    tn http://localhost:8888/src.523fb700.js:726
    en http://localhost:8888/src.523fb700.js:726
    Jt http://localhost:8888/src.523fb700.js:726
    yt http://localhost:8888/src.523fb700.js:726
    mn http://localhost:8888/src.523fb700.js:726
    fo http://localhost:8888/src.523fb700.js:726
    Uu http://localhost:8888/src.523fb700.js:726
    Lu http://localhost:8888/src.523fb700.js:726
    Ru http://localhost:8888/src.523fb700.js:726
    Cu http://localhost:8888/src.523fb700.js:726
    oi http://localhost:8888/src.523fb700.js:726
    unstable_runWithPriority http://localhost:8888/src.523fb700.js:722
    ri http://localhost:8888/src.523fb700.js:726
    oi http://localhost:8888/src.523fb700.js:726
    ai http://localhost:8888/src.523fb700.js:726
    ku http://localhost:8888/src.523fb700.js:726
    enqueueSetState http://localhost:8888/src.523fb700.js:726
    setState http://localhost:8888/src.523fb700.js:718
    e http://localhost:8888/src.523fb700.js:4681
    f http://localhost:8888/src.523fb700.js:19
    _invoke http://localhost:8888/src.523fb700.js:19
    E http://localhost:8888/src.523fb700.js:19
    u http://localhost:8888/src.523fb700.js:4681
    promise callback*i http://localhost:8888/src.523fb700.js:4681
    u http://localhost:8888/src.523fb700.js:4681
    promise callback*i http://localhost:8888/src.523fb700.js:4681
    u http://localhost:8888/src.523fb700.js:4681
    promise callback*i http://localhost:8888/src.523fb700.js:4681
    G http://localhost:8888/src.523fb700.js:4681
    G http://localhost:8888/src.523fb700.js:4681
    value http://localhost:8888/src.523fb700.js:4681
    Oi http://localhost:8888/src.523fb700.js:726
    Ga http://localhost:8888/src.523fb700.js:726
    Ro http://localhost:8888/src.523fb700.js:726
    Lu http://localhost:8888/src.523fb700.js:726
    Ru http://localhost:8888/src.523fb700.js:726
    Cu http://localhost:8888/src.523fb700.js:726
    ku http://localhost:8888/src.523fb700.js:726
    dc http://localhost:8888/src.523fb700.js:726
    bc http://localhost:8888/src.523fb700.js:726
    Nu http://localhost:8888/src.523fb700.js:726
    bc http://localhost:8888/src.523fb700.js:726
    render http://localhost:8888/src.523fb700.js:726
    zo2T http://localhost:8888/src.523fb700.js:4681
    f http://localhost:8888/src.523fb700.js:1
    parcelRequire http://localhost:8888/src.523fb700.js:1
    <anonymous> http://localhost:8888/src.523fb700.js:1
src.523fb700.js:2325:2099

**Comment by tjamesking** [comment]
Upon closer examination, I found that homebrew is actually installing the binary for Chronograf 1.8.0 (which I'll open a separate bug report for).  However, after uninstalling the homebrew version and downloading the latest macOS tarball, I can verify that this TZ bug is still present in 1.9.3, just with a slightly different JS filename shown in the console error.

**Comment by sranka** [comment]
Thank you @tjamesking for reporting a defect, I can reproduce it also with chronograf 1.9.4 .
