### ISSUE TITLE
Homebrew installing Chronograf 1.8.0 binary instead of 1.9.3

### ISSUE THREAD

**Issue by tjamesking** [influxdata/chronograf#5884]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ... Install chronograf on macOS with "brew install chronograf"
2. ... Run "chronograf --version"

__Expected behavior:__
Chronograf reports version 1.9.3

__Actual behavior:__
Chronograf reports version 1.8.0

__Environment info:__

* Chronograf version: 1.9.3 / 1.8.0
* Other relevant environment details: macOS 11.6.4 Big Sur, Homebrew 3.4.2

**Comment by tjamesking** [comment]
```
$ brew --version
Homebrew 3.4.2
Homebrew/homebrew-core (git revision 49c92efa752; last commit 2022-03-16)
Homebrew/homebrew-cask (git revision 1cf4b8ff7b; last commit 2022-03-16)

$ /usr/local/Cellar/chronograf/1.9.3/bin/chronograf --version
Chronograf 1.8.0 (git: )

$ brew uninstall chronograf
Uninstalling /usr/local/Cellar/chronograf/1.9.3... (8 files, 67.8MB)

$ rm -f /Users/james.king/Library/Caches/Homebrew/downloads/*chronograf*

$ brew install chronograf
==> Downloading https://ghcr.io/v2/homebrew/core/chronograf/manifests/1.9.3
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/chronograf/blobs/sha256:f8786d16d900600eddd3642e91193b7abb8fc0437885e489e645368c6b93598f
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:f8786d16d900600eddd3642e91193b7abb8fc0437885e489e645368c6b93598f?se=2022-03-16T21%3A30%3A00Z&sig=UAO38a5Y
######################################################################## 100.0%
==> Pouring chronograf--1.9.3.big_sur.bottle.tar.gz
==> Caveats
To restart chronograf after an upgrade:
  brew services restart chronograf
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/chronograf/bin/chronograf
==> Summary
🍺  /usr/local/Cellar/chronograf/1.9.3: 8 files, 67.8MB
==> Running `brew cleanup chronograf`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ /usr/local/Cellar/chronograf/1.9.3/bin/chronograf --version
Chronograf 1.8.0 (git: )
```

**Comment by sranka** [comment]
Thank you @tjamesking for all the details and for splitting this issue from #5883. This is probably caused by a mistake during publishing the release. @ivankudibal @timhallinflux Can you please help with this?

**Comment by timhallinflux** [comment]
my guess is that we just haven't updated home brew.  strange.  we will investigate.

**Comment by timhallinflux** [comment]
https://formulae.brew.sh/formula/chronograf#default  This says 1.9.3.  🤔

**Comment by timhallinflux** [comment]
Ah, the CLI may just be reporting the wrong version.  Gotcha.

**Comment by sranka** [comment]
FYI: [macOS tarballs for 1.9.3](https://github.com/influxdata/chronograf/issues/5883#issuecomment-1069649647) are correct

**Comment by sranka** [comment]
The homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/chronograf.rb) builds chronograf using a `make` script that extracts version and commit details with git. Since the formula starts from a source tarball that is detouched from git, the version and commit details are simply wrong.
