### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by fabiopedrosa** [influxdata/chronograf#591]
At the moment, I have to keep going into the "Data sources" page, connect to a different host and have that single host in the hosts page. 

1) Can't I just have all the hosts shown in the hosts page?
2) How can I have a host associated with a exploration, so that switching explorations also changes hosts?
3) Wouldn't it make sense to have 1+ sources associated with each exploration?

**Comment by goller** [comment]
Hi @fabiopedrosa, thanks for writing!  @rkuchan and I are going to write up some documentation about this.

The short answer is that a data source is just the influxdb and hosts are all the hosts running telegraf.  Each telegraf would send its information into the influxdb data source.

All telgraf hosts would be shown on your hosts page.
Here is an example using one of our test kubernetes clusters:
![k8s](https://cloud.githubusercontent.com/assets/1922921/20530598/8ecc009a-b099-11e6-8f99-ff097c762e16.png)


As for switching hosts in explorations, here is how it works at the moment (but we are totally willing to make this better):

![groupby](https://cloud.githubusercontent.com/assets/1922921/20530456/0addc548-b099-11e6-91c5-11e5054350b5.png)
Essentially, you can select one or more hosts.

Your question about this is the second time we've had it.  Good user interface shouldn't need to be explained, so, I think we have work to do to make this better.

**Comment by fabiopedrosa** [comment]
Hi Chris,
thanks, makes a lot more sense now.
I have a couple other issues, but maybe I should create new issues? main one would be the ability to write custom querys.

**Comment by goller** [comment]
@fabiopedrosa Oh good ok. Yeah, feel free to create other issues!

**Comment by fabiopedrosa** [comment]
Sorry, didn't notice the issue in your reply before.

You are right, for telegraph data, you always have the tag *host* and therefore can filter or group there.

My use case is different: I have two different hosts, each has a influxdb. I have a single exploration/query that I want to run on both hosts. The only way I can do that right now is:
1) go into sources
2) *connect* to a influx host
3) check my graph
4) repeat for other host(s)

this how you handle this use case?

**Comment by goller** [comment]
@fabiopedrosa Ah I see!

<img width="1141" alt="explorations" src="https://cloud.githubusercontent.com/assets/1922921/20539814/14a22a06-b0bc-11e6-8a6d-7755fdb554f6.png">

We have not implemented that yet, but, will.  Our idea is that the box I've highlighted red would allow you to choose a different influxdb source.  The tracking issue is #108

**Comment by fabiopedrosa** [comment]
Ah, thanks. That would be perfect.
