### ISSUE TITLE
Make standalone binaries available for download

### ISSUE THREAD

**Issue by Tomcat-Engineering** [influxdata/chronograf#595]
Please could you publish tarballs containing the Chronograf binary plus the "canned" JSON files as part of your nightly releases?  You do this for the other parts of the TICK stack.  

Installing from a package (deb/rpm) does not suit our deployment system.  I'm after amd64 linux binaries and ideally OSX too.  

Thanks!

**Comment by Tomcat-Engineering** [comment]
Just realised that at the moment the RPM is essentially what I'm requesting but with a different filename...

**Comment by goller** [comment]
Hey @Tomcat-Engineering, absolutely!  @rossmcdonald is working on just that right now: https://github.com/influxdata/chronograf/pull/594

He is adding more automation around building chronograf.

**Comment by rossmcdonald** [comment]
We actually already build these:

* MacOS - https://dl.influxdata.com/chronograf/nightlies/chronograf-nightly_darwin_amd64.tar.gz
* Linux - https://dl.influxdata.com/chronograf/nightlies/chronograf-nightly_linux_amd64.tar.gz

I see that they're not listed on the Downloads page, though. I'll work on getting them added.

**Comment by Tomcat-Engineering** [comment]
Awesome, thanks!
