### ISSUE TITLE
As a user I can filter by series tags

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#597]
On the host list the app runs the ""show series from /^<app>$/" query.  This returns a number of tags, for example "disk,cluster_id=c94f3e09ee1413b3ca0e08d6829947e8,fstype=ext4,host=prod-c94f3e09-us-east-1-meta-0,path=/etc/hostname"

Every tag should be added to the host such that when filtering in the above example i should enter "ext4" into the filter menu and see the the hosts that have that value as a tag.

**Comment by timraymond** [comment]
@nhaugo Are we going to display these tags in the UI anywhere?
