### ISSUE TITLE
Please upgrade golang to 1.18.4 for security fixes

### ISSUE THREAD

**Issue by jdstrand** [influxdata/chronograf#5989]
https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE announced 1.18.4 for several security issues. I've not yet determined if those fixes are relevant for `chronograf`, but since `chronograf` was recently updated to 1.18.3 in preparation for `chronograf` 1.9.4, it would be nice to recompile and release 1.9.5 with 1.18.4 if possible.

**Comment by sranka** [comment]
@ivankudibal  this PR requires a new build image to be ready for review - https://github.com/influxdata/chronograf/blob/master/etc/README.md
