### ISSUE TITLE
BASE_PATH configuration is not working with Chronograf 1.10

### ISSUE THREAD

**Issue by afausti** [influxdata/chronograf#6000]
__Steps to reproduce:__

1. Start Chronograf 1.10 with `docker run -p 8888:8888 -e BASE_PATH=/chronograf quay.io/influxdb/chronograf:1.10.0`

__Expected behavior:__
It should open in the browser at `localhost:8888/chronograf`  like in previous versions.

__Actual behavior:__

We get a strange error message in the javascript console and it does not open:

<img width="1437" alt="Screen Shot 2022-09-09 at 1 45 32 PM" src="https://user-images.githubusercontent.com/13968086/189442673-521995a3-f0eb-46c9-8541-554c82174946.png">

__Environment info:__

* Chronograf version: 1.10.0

**Comment by sranka** [comment]
I was able to reproduce this locally, it is most likely caused by a new UI build system introduced in chronograf 1.10 .

**Comment by sranka** [comment]
The fix is already available in the nightly builds (see https://portal.influxdata.com/downloads/)
