### ISSUE TITLE
Add possibility to hide version on Auth login page

### ISSUE THREAD

**Issue by partamonov** [influxdata/chronograf#6002]
Now there is no way how I can remove deployed version from auth login page. Usually it is preferred way to remove any details about deployed product.

If that [string](https://github.com/influxdata/chronograf/blob/406065e391633812d378fd644cb2ef8922020dfd/ui/src/auth/Login.js#L55) can be changed or version omitted by some CLI flag or ENV var, that would be awesome

I checked it in v1.9.4

**Comment by sranka** [comment]
Thank you for reporting a defect. Can you please provide a rationale for why the version should be removed, it is opinionated otherwise.

FYI, the version is printed in https://github.com/influxdata/chronograf/blob/master/ui/src/auth/Login.js#L55, ... it is this way for more than 5 years.

**Comment by partamonov** [comment]
It usually suggested to hide server tokens to required minimum. 

* [Nginx](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens)
* [Apache](https://httpd.apache.org/docs/2.4/mod/core.html#serversignature).

Opposite to it, it is not really improving security, what is written in Apache docs.

So it can be considered opinionated too

**Comment by sranka** [comment]
Chronograf is IMHO not a platform (like Nginx, or Apache) to provide such a level of customization in a configuration. This type of customization can be still provided in a custom build, if necessary.
