### ISSUE TITLE
Chore, terminology in Chronograf

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#602]
Pointing out some places where Chronograf's wording could get confusing:

### ENDPOINTS vs. OUTPUT vs. ALERT
The `CONFIGURE KAPACITOR` page calls stuff like Slack an `alert endpoint`. The `KAPACITOR RULES` page refers to those alert endpoints as `outputs` when editing the rule and as `alerts` when viewing the rules.

I like `output` or `endpoint` (not just `alert`) but I think it should be one or the other throughout Chronograf.

### HOSTS and HOSTNAMES
The `HOST LIST` page refers to the Telegraf hostnames as `hosts` and `hostnames`. The `INFLUXDB SOURCES` page refers to the InfluxDB hostname as `host`. It might help clarify what Chronograf means to replace the `Host` header on the `INFLUXDB SOURCES` page with `InfluxDB Host`:

![image](https://cloud.githubusercontent.com/assets/8750814/21121821/6fd56b3c-c083-11e6-8d63-133e25fe6925.png)

### Time series vs. Metric
When editing a rule on the `KAPACITOR RULES` page, I first select a `time series`, but in the `Values` section, I see select a `metric`. I'd prefer to see `time series` throughout that page.

### Alert Type vs. Trigger
When I'm editing a rule something like threshold is called an `Alert Type`. That same category is called `Trigger` when I'm just viewing rules. I'm leaning towards `Rule Type`  or `Alert Type` and think it should at least be consistent.

## General Wording

* When I'm editing or creating a rule the `Values` header isn't very descriptive. I think I'd prefer something like `Conditions` or `Rule Conditions`.
* The `KAPACITOR RULES` page seems to have two titles: `KAPACITOR RULES` and `Alert Rules`. It might be nice if this page mimicked the `HOST LIST` and the `ALERT HISTORY` page, so, instead of `Alert Rules`, have `N Rules`:
![image](https://cloud.githubusercontent.com/assets/8750814/21122551/a5be3888-c087-11e6-91e3-0698566d62c6.png)

* The page titles in the `ALERTING` section on the sidebar could be a little odd for someone not very familiar with Kapacitor. Something as simple as the text below might help:
![image](https://cloud.githubusercontent.com/assets/8750814/21122581/d3144b9c-c087-11e6-88e8-5b6c714940ca.png)

**Comment by alexpaxton** [comment]
@rkuchan want to walk through the UI with me and make all the copy consistent? Been noticing some similar issues myself

**Comment by rkuchan** [comment]
@alexpaxton, yeah!

**Comment by rkuchan** [comment]
@alexpaxton, I edited the original issues with the stuff we talked about. I think I covered everything but feel free to add if you see anything missing!

**Comment by alexpaxton** [comment]
I vote:
- Endpoint
- *No opinion*
- Time Series
- Alert Type

**Comment by pauldix** [comment]
Yeah, should be `Alert Rules`. There are different concepts at work here.

* Alerting Rule - a rule that looks for conditions to trigger an Alert
* Alert - a discrete event that indicates when a rule was triggered
* Notification - a message sent to an Endpoint
* Endpoint - where notifications of Alerts go. Note that not every Alert may trigger a Notification in the future. For example, if they have limits set to only notify them of the first Alert in a 10 minute window. The Alert could actually be triggered many times in that window.

Finally, I think it should just be `Hosts`

**Comment by rkuchan** [comment]
I'll put together a glossary.

**Comment by nhaugo** [comment]
Steps for this ticket
- Change `Trigger` to `Rule Type` in the alert rule list 
- On alert config, change `Values` to `Rule Conditions`
- Title bar of alert rules list change `Kapacitor Rules` to `Alert Rules`

**Comment by alexpaxton** [comment]
@nhaugo I can handle this one
