### ISSUE TITLE
Chronograf crashes when a colon is entered 

### ISSUE THREAD

**Issue by jove01** [influxdata/chronograf#6052]
This issue from another user discribes a problem and you find this problem in many other foren.
#https://github.com/hassio-addons/addon-influxdb/issues/285

I hope it is no problem to refere to this issue.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Go to explore
2. insert Query  with copy and past
`CREATE CONTINUOUS QUERY "cq_1day" ON homeassistant BEGIN SELECT mean(value) AS value INTO homeassistant."infinite".:MEASUREMENT FROM homeassistant.autogen./.*/ GROUP BY time(1d), * END`
3. In other wise insert code step by step an by writing **:MEASUREMENT**, it crashes
4. The Link here ist dead
5. 
![grafik](https://github.com/influxdata/chronograf/assets/116289742/498533c2-94e3-46fc-be27-de9390808546)
![grafik](https://github.com/influxdata/chronograf/assets/116289742/fbd2b35c-b681-4733-a92b-157614ef190f)

__Expected behavior:__
Describe what you expected to happen.
It is passible to create a CONTINUOUS QUERY

__Actual behavior:__
Describe What actually happened.
An error occured

__Environment info:__
Home Assistant Community Add-on: InfluxDB 4.7.0
generic X86-64
`## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1329
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 468.7 GB
disk_used | 26.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.1), Mosquitto broker (6.2.1), OneDrive Backup (2.1.2), Studio Code Server (5.9.0), Duck DNS (1.15.0), Cloudflared (4.2.1), NGINX Home Assistant SSL proxy (3.5.0), evcc (0.118.10), RaspberryMatic CCU (3.69.7.20230626), MQTT Explorer (browser-1.0.1), MariaDB (2.6.1), modbus-proxy (1.0.15), Samba share (10.0.2), ESPHome (2023.7.0), InfluxDB (4.7.0), Grafana (9.0.2), PSA Car Controller (v3.0.12)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 14
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14. Juli 2023 um 20:37
-- | --
current_recorder_run | 24. Juli 2023 um 15:52
estimated_db_size | 1644.06 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>`

* Chronograf version: 
* Other relevant environment details: OS type and version, browser type and version, InfluxDB version ...
firefox or Edge

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.
`auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars: []
log_level: info`

__Logs:__
Include a snippet of errors in the log.
This is a protocol some day ago

[Error.docx](https://github.com/influxdata/chronograf/files/12148110/Error.docx)

**Comment by Mat0u5** [comment]
Can someone PLEASE fix this? I can't make a continuous query until this is fixed.
