### ISSUE TITLE
As a user I can see a singlestat in the data explorer

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#608]
If the user selects number as the graph type that type should appear in the right graph area.

* Provide the user with a graph-type dropdown
* The default graph is "graph"
* The dropdown should include the items graph and number

**Comment by nhaugo** [comment]
![graphtype](https://cloud.githubusercontent.com/assets/1003269/20690295/8d283094-b57e-11e6-9738-1edfcfcc0c63.png)

**Comment by nhaugo** [comment]
![graphtype](https://cloud.githubusercontent.com/assets/1003269/20690326/ce348998-b57e-11e6-9c57-5574bdba12d3.png)

**Comment by alexpaxton** [comment]
@nhaugo does the graph type dropdown only affect the appearance of the graph?

**Comment by nhaugo** [comment]
• If the user selects more than one field or has more than one query change the result to be "N/A"
• Add a tooltip when the N/A is hovered to show why

**Comment by nhaugo** [comment]
@alexpaxton yes

**Comment by nhaugo** [comment]
Blocked on #685

**Comment by 121watts** [comment]
Now we have dashboards that do these things!
