### ISSUE TITLE
As a user I can open a query in "editor mode" in the data explorer

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#610]
• The user should able to create a editable query box with a drop down on the "+" tab
• The action will create an "Editor" mode tab

**Comment by nhaugo** [comment]
The Schema Explorer is tied to Query tabs. We would like the Schema Explorer to still be accessible, but have it perform as a static browsable index and have no effect on the query. This way users using "Terminal" mode can still use the Schema Explorer for reference.

**Comment by rkuchan** [comment]
Needs more conversation. Concern over future requirements for the query editor, how it interacts with the UI, and how it give the user an amazing experience.

**Comment by nhaugo** [comment]
@willpiers can you change "raw text" to "InfluxQL"
