### ISSUE TITLE
As a user I can see the query error output in the data explorer

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#611]
See https://github.com/influxdata/enterprise/issues/1034
and https://github.com/influxdata/enterprise/issues/1018
• There should be a section under the query that will display errors
• The progress bar will fill 10% on request
• The bar should slowly fill, say 10%/sec for the next 8 seconds
• Upon return the progress bar should totally fill
• If the query was successful the user should get a green "Query OK" result in the message box
• If there was an error should be a red "Error" message and a "details" button to expand
• On click of the details button should expand the space and display the errors

![queryerror](https://cloud.githubusercontent.com/assets/1003269/20721793/f15ba222-b618-11e6-8e6e-8aaa1ac416e4.gif)

![queryok](https://cloud.githubusercontent.com/assets/1003269/20721795/f5037580-b618-11e6-8725-78b69838f5e3.gif)

**Comment by rkuchan** [comment]
What to do about warning (no data returned, etc.).

**Comment by alexpaxton** [comment]
@nhaugo I made a branch called `de-influxql-error-handling` should be ready for someone to build from

**Comment by nhaugo** [comment]
This probably needs to be wired up with error handling, can we get some eyes on @alexpaxton changes and see what needs to be done.

**Comment by alexpaxton** [comment]
@nhaugo @121watts I think this can be closed

**Comment by 121watts** [comment]
I agree. Closing.
