### ISSUE TITLE
As a user I can see a dashboard menu item in the Data menu and clicking it will bring up a dashboard selection table

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#612]

**Comment by nhaugo** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/1003269/20690356/f724d678-b57e-11e6-8d87-4a3bd85e1cff.png)

**Comment by timraymond** [comment]
This has been pushed up onto a branch here: https://github.com/influxdata/chronograf/tree/feature/tr-dashboard-frontend . Awaiting completion of the backend to rebase and open a PR.
