### ISSUE TITLE
As a user I can see the measurement name + field name as the label in the query tab in data explore

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#618]
Default: query

**Comment by alexpaxton** [comment]
@nhaugo my only concern is how to handle longer names in this context, though I'd have to see some different cases before deciding whether it breaks the UI or not

**Comment by alexpaxton** [comment]
@nhaugo @rkuchan here's some browser experiments with this one:


**Long Name + Truncation:**
<img width="427" alt="screen shot 2016-12-09 at 12 51 20 pm" src="https://cloud.githubusercontent.com/assets/2433762/21064250/ab9fd12e-be0e-11e6-8899-fc79e3402d6b.png">

**Long Name no truncation:**
<img width="575" alt="screen shot 2016-12-09 at 12 40 45 pm" src="https://cloud.githubusercontent.com/assets/2433762/21064258/b6e75228-be0e-11e6-9c7f-1e5e807ebab7.png">

**Short Name:**
<img width="559" alt="screen shot 2016-12-09 at 12 38 09 pm" src="https://cloud.githubusercontent.com/assets/2433762/21064273/c423fcf2-be0e-11e6-837c-4650d1e51e2f.png">

**Comment by rkuchan** [comment]
@alexpaxton - looks cool! I like the truncated long name more than the untruncated one. I think it'll look clearer especially when there are several queries for one graph.

**Comment by alexpaxton** [comment]
handled via #676
