### ISSUE TITLE
As a user I can see an indication of which graph line(s) is affected tab is a query tab is in focus.

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#619]
From @rkuchan Suggested alternative for making it easy to determine what line belong to what query: highlight the line on the graph when the user hovers over the relevant query tab.

**Comment by rkuchan** [comment]
Discussion needed. Implementation of this one is hard - what happens when there's a GROUP BY  tag clause in the query.

**Comment by alexpaxton** [comment]
@rkuchan I like that idea a lot. I was messing with this before and found it pretty difficult to match 1 query to 1 line. Using the number of series doesn't get you the number of lines either

**Comment by nhaugo** [comment]
@alexpaxton can you do a quick visual mockup

**Comment by 121watts** [comment]
I got it.
