### ISSUE TITLE
As a user I can save a data explorer graph to a dashboard

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#620]
![savetodash](https://cloud.githubusercontent.com/assets/1003269/20692098/930c2db0-b58a-11e6-8aad-869a52a9e78a.png)

**Comment by nhaugo** [comment]
• This should export all queries for the selected graph

**Comment by timraymond** [comment]
@nhaugo If I have an existing dashboard, where should the graph that is being added by this button appear? Should users be taken to the dashboard after the graph is added?

**Comment by nhaugo** [comment]
Right now appended to the end

**Comment by russorat** [comment]
you can do this via the Send to Dashboard button.
