### ISSUE TITLE
Time range for the "Select a Time Series” section is not configurable

### ISSUE THREAD

**Issue by kostasb** [influxdata/chronograf#624]
When configuring Kapacitor alerts in Chronograf, the time duration for the “Select a Time Series” query is permanently fixed to `now() - 15m` and there is no way to modify it.

This affects the graph plotted by the output of the query and limits user's visibility to only the last 15 minutes worth of data. The time range should be configurable.

(nightly build)

**Comment by nhaugo** [comment]
Can we add the "range" combo box to the top right of the kapacitor rule configulator as it is in the data explore and host view.
