### ISSUE TITLE
Add Alerta as kapacitor alert service.

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#625]
We need to support sending additional configuration information about alerta:

https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#alerta

**Comment by nhaugo** [comment]
Dupe of #320

**Comment by goller** [comment]
This was added in 1.2.0-beta2

![alerta](https://cloud.githubusercontent.com/assets/1922921/22855152/ad61af6e-f040-11e6-9033-c19bcefc3065.gif)
