### ISSUE TITLE
Add possibility to add a notification alert contact

### ISSUE THREAD

**Issue by hydro-b** [influxdata/chronograf#638]
In order to be able to send notifications created by an alert to a specific user (or group, consisting of list uf usres) the possibility should be added to add notification contacts in (Chronograf) alerting.

**Comment by agrrh** [comment]
@hydro-b 
As far, as I understand, alerting is Kapacitor responsibility, not Chronograf:
https://www.influxdata.com/time-series-platform/kapacitor/

**Comment by goller** [comment]
@agrrh Chronograf does have integration with kapacitor to send alerts.   Check out https://github.com/influxdata/chronograf/blob/master/docs/GETTING_STARTED.md#create-and-view-alerts   Chronograf supports creating and viewing threshold, relative and deadman alerts.

@hydro-b the kapacitor configuration should allow you to specify users and groups to send the alert to (although as you pointed out in #639 SMTP doesn't have that yet).

To get to the configuration click on kapacitor:

![config_kapa](https://cloud.githubusercontent.com/assets/1922921/20941150/d75b67de-bbba-11e6-8c64-c7445e37eb06.png)

However, these kapacitor parameters are global for all alerts.  We don't have support, yet, for per alerting rule overrides.  This is similar to issue #625.

**Comment by agrrh** [comment]
@goller
Wow!
Looks like nightly builds of Chronograf are much more flexible and useful than stable release from Downloads page on main site.
Gonna upgrade in few hours, thank you!

**Comment by nhaugo** [comment]
The proposed fix for #639 should cover this issue. I can closing it as a dupe.
