### ISSUE TITLE
Add possibility to specify a specific notification contact

### ISSUE THREAD

**Issue by hydro-b** [influxdata/chronograf#639]
Instead of a hardcoded list of recipitients of SMTP alerts in /etc/kapacitor/kapacitor.conf it should be possible to select, on a per rule basis, one or more notification contacts to send the alerts to.

**Comment by goller** [comment]
Hi @hydro-b thanks for writing in :)

It looks like we don't have UI around setting `to` in the SMTP configuration of kapacitor:

![smtp](https://cloud.githubusercontent.com/assets/1922921/20940845/cfab3b50-bbb9-11e6-9563-5e23352e1f2c.png)

From the SMTP configuration [documentation](https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#email):
```
     [smtp]
       enabled = true
       host = "localhost"
       port = 25
       username = ""
       password = ""
       from = "kapacitor@example.com"
       to = ["oncall@example.com"]
```

Additionally, we need to add support for specifying alert parameters during the alert rule creation workflow.

**Comment by nathanielc** [comment]
@goller Has the right idea. Kapacitor's API supports this type of configuration on a per rule basis. It just needs to be exposed via the Chronograf UI.

**Comment by nhaugo** [comment]
If feels like we need to allow for multiple instances of alert output types that can be assigned to rules in the UI, doing so should cover this and best I can tell #638

**Comment by goller** [comment]
Hi @hydro-b , we added sending email to specific people on a per rule basis in our 1.2.0-beta2 release.

Here is a gif of me testing it:

![email](https://cloud.githubusercontent.com/assets/1922921/22854993/193ebf2c-f03e-11e6-9ad5-2e21bfa2b0e3.gif)

Try it out!

**Comment by hydro-b** [comment]
Nice! Thanks for implementing. Will test this in final 1.2.0 version
