### ISSUE TITLE
Not able to setup Telegram in Kapacitor

### ISSUE THREAD

**Issue by fabiopedrosa** [influxdata/chronograf#640]
Always get a JSON response:

`{
    "error": "failed to override configuration telegram/: unknown options [parseMode chatID disableNotification disableWebPagePreview stateChangesOnly] in section telegram"
}`

**Comment by goller** [comment]
@fabiopedrosa I'm able to reproduce this.  Thanks for sending in the JSON response.

![telegram2](https://cloud.githubusercontent.com/assets/1922921/21037221/b0b6571e-bd91-11e6-9aa1-e5f8f270fb5d.png)

We aren't sending the right JSON to kapacitor :(

**Comment by nhaugo** [comment]
@nhaugo set up test telegram account
