### ISSUE TITLE
Inconsistent behavior on Function Selection

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#651]
There is inconsistent behavior on the function selection between the KapacitorUI and the DataExplorer.

## Kapacitor UI
![kapacitor](http://g.recordit.co/9vDRa3YdE8.gif)

## Data Explorer
![dataexplorer](http://g.recordit.co/avJ0raQKnn.gif)

I think users would prefer the behavior in the Kapacitor UI

**Comment by alexpaxton** [comment]
@jackzampolin I concur, the kapacitor UI functions feel smoother

Tangentially related, this interaction is pretty messy. Part of it is that the dropdown doesn't appear on top of everything else, which makes it tough to find the `Apply` button. I have a solution in mind
<img width="406" alt="screen shot 2016-12-06 at 1 17 32 pm" src="https://cloud.githubusercontent.com/assets/2433762/20943964/7e903714-bbb6-11e6-9be9-b058bbbe1db8.png">

**Comment by nhaugo** [comment]
verify fixed, maybe?
