### ISSUE TITLE
Can't select text in text fields

### ISSUE THREAD

**Issue by unixninja92** [influxdata/chronograf#652]
It is not possible to select text in any text fields.

**Comment by goller** [comment]
@unixninja92 is this the same problem as #670?

**Comment by unixninja92** [comment]
No, and I can't reproduce that bug when running a073f26.

**Comment by goller** [comment]
@unixninja92 Excellent.  The team will be releasing beta2 today with bug fixes including this one.

**Comment by unixninja92** [comment]
Selecting seems to be working now, but is invisible. You can't tell what is selected.

**Comment by goller** [comment]
Ah... perhaps I closed this too soon.  We'll take a look.

**Comment by mark-rushakoff** [comment]
Just ran into the same issue. In this screenshot I double clicked "Influx" to highlight it. I can't see the difference between the selected "Influx" and the unselected "123456".
<img width="206" alt="screen shot 2016-12-09 at 8 38 33 pm" src="https://cloud.githubusercontent.com/assets/290647/21071244/ab5e75f8-be4f-11e6-8026-5273b0e82190.png">

I'm running today's nightly.

**Comment by nhaugo** [comment]
@alexpaxton I think this is a CSS issue, can you take a look.

**Comment by alexpaxton** [comment]
Fixed via #684

**Comment by nhaugo** [comment]
connect #684
