### ISSUE TITLE
Selected tags are hard to find in data explorer

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/chronograf#662]
![chronograf-hard-to-find-tags](https://cloud.githubusercontent.com/assets/628831/20949486/670bedfa-bbce-11e6-8ca2-81c96a325a4f.gif)

**Comment by nhaugo** [comment]
@gunnaraasen @rossmcdonald what is the desired behavior here. It is hard to tell from the gif what you are hoping to have happen.

**Comment by gunnaraasen** [comment]
Desired behavior would be to have any selected tags listed first in the list of available values. The gif is trying to show that it's really hard to find out which specific tags are selected.

**Comment by russorat** [comment]
ui has been updated, this is no longer relevant
