### ISSUE TITLE
Derivative / Difference functions missing from UI

### ISSUE THREAD

**Issue by agrrh** [influxdata/chronograf#663]
Hello!

Currently I can't apply `derivative` / `difference` functions to haproxy metrics, so I'm unable to build sane graps to display 200/500 response codes or sessions count.

How can one apply those functions or workaround the issue to deal with "total"-type metrics?

Thank you in advance.

**Comment by goller** [comment]
Hello @agrrh, sadly you are right; we don't have the ability to build with `derivative` and `difference` yet.  However, we are working on that now.

HOWEVER!  There is a workaround for the moment.  We have a "precanned" layouts for haproxy:
https://github.com/influxdata/chronograf/blob/master/canned/haproxy.json

Our layout documentation is here: https://github.com/influxdata/chronograf/blob/master/docs/LAYOUT.md

Our idea is that the hosts that are collecting data with telegraf should automatically show up in the hosts list:

![chrono](https://cloud.githubusercontent.com/assets/1922921/20976721/048dff74-bc69-11e6-9c26-1ee135ed9c06.gif)

So, I created the HAProxy layout based on my previous experience with it, but, please go ahead and add/update the haproxy.json file!  PRs are gladly accepted for it.

BTW, if haproxy for that machine is not shown for you we have a known issue in the README:

> Currently, Chronograf requires users to run Telegraf's CPU and system plugins to ensure that all Apps appear on the HOST LIST page.

**Comment by agrrh** [comment]
@goller Thank you for such detailed answer, Chris.

To use "precanned" schemes is an acceptable yet not ideal way to solve the issue, I will definitely give it a try.

PS: How do you create these GIFs?

**Comment by goller** [comment]
@agrrh No problem; I agree about that is isn't ideal.  We are definitely making this better before we leave beta.  

As for gifs, I'm using Justin Frankel's licecap: http://www.cockos.com/licecap/

**Comment by poblahblahblah** [comment]
Is there any update on this request? This would be very helpful for stats pulled via the httpjson plugin.

**Comment by nhaugo** [comment]
Hi @poblahblahblah it turns out this turns into a very large feature for us and is not on the near term roadmap.

**Comment by negbie** [comment]
+1 for percentile

**Comment by pubyun** [comment]
+1 for percentile

**Comment by russorat** [comment]
connect #3895
