### ISSUE TITLE
URL to specific host graphs leads to download

### ISSUE THREAD

**Issue by agrrh** [influxdata/chronograf#664]
Hello!

When I share those URLs with my colleagues, browser is trying to download something:

```
$ curl -s -I 'http://tick.REDACTED.com:8888/sources/1/hosts/REDACTED.com?app=redis'
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 523
Content-Type: application/x-msdos-program
Last-Modified: Wed, 07 Dec 2016 10:56:02 GMT
Date: Wed, 07 Dec 2016 15:17:35 GMT
```

Looks like trailing `.com` part is the issue.

Probably `Content-Type` should be strictly set.

Please let me know if you need more info.

**Comment by goller** [comment]
@agrrh This is definitely a bug.  I've been able to reproduce it.

We are using the golang's (http.FileServer)[https://godoc.org/net/http#FileServer] and we'll need to explicitly set the content-type for your issue.

Another idea:
@121watts could we use a similar concept to the base64 encoding we used previously to hide the hostname?

**Comment by goller** [comment]
@agrrh I tracked it down.  Thank you again for the bug report.  I realize now that I understand more about this that it would not have been easy to figure out! Nice job!

**Comment by goller** [comment]
@agrrh the beta-2 release is out with this problem fixed; thanks for the report!

https://github.com/influxdata/chronograf/releases/tag/1.1.0-beta2
