### ISSUE TITLE
Default Telegraf Database reinserts itself when 

### ISSUE THREAD

**Issue by daviskirk** [influxdata/chronograf#670]
This might be related to #586 but when I try to edit the "Telegraf Database" field and erase all letters, the default database i.e. "telegraf" reinserts itself.  

`"telegraf" -> (backspace a few times) -> "t" -> (backspace once more) -> "telegraf"`

The only way to get around this is to write something after "telegraf" and then delete the first characters:

`"telegraf" -> "telegrafmy_host_metrics_db" ->  "my_host_metrics_db"`

using:
Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
chronograf_1.1.0~beta1_amd64.deb

**Comment by goller** [comment]
@daviskirk We'll be releasing beta2 today with the fix for this and other bugs.  Thanks for writing in!
