### ISSUE TITLE
Editing existing valid sources fails and freezes page

### ISSUE THREAD

**Issue by daviskirk** [influxdata/chronograf#671]
To recreate:

After creating multiple InfluxDB (valid, working) sources, go back to the sources page and click edit on one of the sources.
Without changing anything, click save. The error banner:

> There was a problem updating the source. Check the settings

appears.  

![image](https://cloud.githubusercontent.com/assets/1049817/21013741/7d320540-bd5b-11e6-9196-462bdd04ad2d.png)

After this, clicking around the menu, does not rerender the page (although the link in the url bar does change)

Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 16.04 (64-bit) and chronograf_1.1.0~beta1_amd64.deb

**Comment by goller** [comment]
@daviskirk Thanks for writing in!  We just fixed that in our nightlies: 
https://github.com/influxdata/chronograf/commit/9578b0d2960baadc8f12871d874d32fa65476e2b

@nhaugo @timhallinflux This is a pretty big bug, do you want us to create another beta release?

**Comment by goller** [comment]
@daviskirk The beta-2 release is out now:

https://github.com/influxdata/chronograf/releases/tag/1.1.0-beta2

Thanks again for the report!
