### ISSUE TITLE
UX bug setting up kapacitor with defaults

### ISSUE THREAD

**Issue by unixninja92** [influxdata/chronograf#675]
When setting up kapacitor the text fields for connection string and name have grayed out defaults. If you want to use those defaults, you have to type them in, the "Connect Kapacitor" button won't work if both of those fields don't have text that was typed in. There is no indication why pressing the button does nothing. 

Once you have set up kapacitor and try changing it to the defaults (by deleting the text in both fields) from the configuration you get the pop-up saying that settings have been changed when the button is pressed, even though nothing actually happened because of the above issue.

**Comment by alexpaxton** [comment]
@unixninja92 What do you think about this?

![reset-kap-defaults](https://cloud.githubusercontent.com/assets/2433762/21240167/e9e12758-c2be-11e6-91d5-8086da93e657.gif)

**Comment by unixninja92** [comment]
Looks good to me. I think you should either include the button or only have the text boxes fill with the defaults when first setting up and not have anything appear when the boxes are empty.

**Comment by alexpaxton** [comment]
Closed via #698

**Comment by unixninja92** [comment]
What I was trying to get at with this bug is that I think the page for setting up kapacitor should auto fill text boxes on first open the same way that the page for welcome screen/initial setup of influx does. 

Right now when you are adding a Kapacitor or Influx (post startup), it looks like you should be able to just press add source/kapacitor if the defaults work for you, but you can't because the defaults aren't actually in the text box. So it looks like the name is set to My Kapacitor (it's not) but it's not obvious why the Connect Kapcitor button is still greyed out. Does that make sense?
