### ISSUE TITLE
Unable to connect to influxdb (https)

### ISSUE THREAD

**Issue by Hijis** [influxdata/chronograf#680]
Chronograf unable to connect to influxdb through https using self signed ssl cert. 
I get 
TLS handshake error from 127.0.0.1:49383: EOF
error, while telegraf still able stream metrics to DB, and grafana is able to get them (both over https).

https://i.imgur.com/GniZua6.png
https://i.imgur.com/GJQbVkp.png
https://i.imgur.com/S6PAhKI.png

**Comment by nhaugo** [comment]
Looks like we can fix this with:
```go
    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
```

**Comment by goller** [comment]
@nhaugo I'm thinking we should have allowing self-signed certs (`InsecureSkipVerify`) as an option in the UI.  It feels more explicit rather than as a configuration option for all influx datasources.

**Comment by nhaugo** [comment]
• Update sources on boltdb side and api
• Add checkbox to source creation and initial setup screen
• Pass value when connecting

**Comment by goller** [comment]
Ok, I've completed the server side portion of this in #728.

**Comment by goller** [comment]
Hi @Hijis, @121watts PR to support self-signed support was just merged into master.  We plan on releasing our next beta tomorrow. Thanks again for the request!
