### ISSUE TITLE
[Feature request] multiple similar alert endpoints

### ISSUE THREAD

**Issue by rlex** [influxdata/chronograf#690]
Short story, we have per-project alert channels. 
So it will be nice to have multiple different endpoints with same, um, "engine"?
I'm not sure if it request for kapacitor or chronograf, so i'll write it here.

As an example, here is smtp config:
```
     [smtp]
       enabled = true
       host = "localhost"
       port = 25
       username = ""
       password = ""
       from = "kapacitor@example.com"
       to = ["oncall@example.com"]
       state-changes-only =  true
```

Probably "name" property can be implemented, so we can create different smtp outputs:
```
     [smtp]
       enabled = true
       host = "localhost"
       name = "oncall admins"
       port = 25
       username = ""
       password = ""
       from = "kapacitor@example.com"
       to = ["oncall@example.com"]
       state-changes-only =  true
     [smtp]
       enabled = true
       host = "localhost"
       name = "project admins"
       port = 25
       username = ""
       password = ""
       from = "kapacitor@example.com"
       to = ["project@example.com"]
       state-changes-only =  true
```

So when you create alert, you can choose proper destination from "oncall admins", "project admins", or both.

**Comment by nathanielc** [comment]
@rlex We (Kapacitor team) are working on a related but not quite the same thing. Based on your example you are using the same SMTP server and credentials but you want to have  different settings for  the `to`, `from`, etc fields.

See our WIP design doc here https://github.com/influxdata/kapacitor/blob/master/ALERT_DESIGN.md. The basic idea is you can configure `topics` and then different sets of handlers per topic. Then assign an alert to a topic. In your case a topic called `oncall` vs `project` might be the way to go.

This is still a WIP so if you have any feedback on the design please do comment. Thanks!

**Comment by russorat** [comment]
we have enabled this for a few of the kapacitor endpoints (kafka and slack)
