### ISSUE TITLE
Alert not working when condition is less than and equal to -n%

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/chronograf#692]
So i added the percentage as negative change from last 5 min in chronograf. The alerts are coming if i make percentage change as positive but not working as negative.

**Comment by goller** [comment]
Hey @gaurav-moonfroglabs I'm able to see the issue right now.  I've been talking to @nhaugo and I think we'll improve the UI to add your use case as well as make the clear what the alert currently does.

Right now, this alert will look for a change that is +/- change%.  Basically, it takes the absolute value of the change % and sees if it breaks that amount.  However, as you point out, it we be great to specify the direction of the change.

**Comment by gaurav-moonfroglabs** [comment]
Thanks @goller , also one more point i saw is we should be able to configure multiple slack channels and can divide the alerts on those channels as per need.

Because there can be multiple teams using same setup and has setup different alerts. And every team wants to send alert on there channel for there alerts only.

**Comment by goller** [comment]
@gaurav-moonfroglabs good point... we have a few cases around that issue where we want some per alert settings for kapacitor alert nodes like slack: #635, #638, #639, and #690

**Comment by willpiers** [comment]
Okay I'm having trouble reproducing this issue. I've POSTed a rule with the "less than or equal to n%" condition, with the following response:
<img width="735" alt="screen shot 2016-12-29 at 10 17 49 am" src="https://cloud.githubusercontent.com/assets/2482470/21549902/d3130326-cdb2-11e6-939a-e636a8a3c08e.png">
The TICKScript appears to set crit var to -5 and then properly use the crit function on the alert
<img width="396" alt="screen shot 2016-12-29 at 10 38 23 am" src="https://cloud.githubusercontent.com/assets/2482470/21549952/2ee9defe-cdb3-11e6-8c6b-9209bf5a5730.png">
Let me know what I'm missing @goller

**Comment by nhaugo** [comment]
This may also be related to #714. I am going to close this for now and do some testing around percentage change with the fixes that have been added. I'll reopen if I still see issues.
