### ISSUE TITLE
Highlight measurement

### ISSUE THREAD

**Issue by fabiopedrosa** [influxdata/chronograf#694]
While in an Exploration in the DE, looking at a series with hundreds of multiple measurement is difficult to know which measurement I'm hovering.

[GIF](http://g.recordit.co/FecH4URAek.gif)

**Comment by 121watts** [comment]
@fabiopedrosa that's an interesting one.  We do highlight the legend to indicate which series you're hovering.  But, with a particularly long list the highlighted measurement could potentially be off screen.  We could potentially place the highlighted measurement at the top of the list?  @alexpaxton thoughts?

**Comment by fabiopedrosa** [comment]
bringing it to top of the list would be great. even better would be only displaying measurements that have any value the hovered timestamp.

**Comment by willpiers** [comment]
I think that ☝️ is a pretty good suggestion. It would be weird to move things around within the list, but we should only show lines that have a point at the selected time stamp

**Comment by 121watts** [comment]
We do already only display measurements that match the hovered timestamp.  

![](http://g.recordit.co/pInKrFeztF.gif)

**Comment by fabiopedrosa** [comment]
Just checked and you're absolutely right. Then I would ask again to consider bringing to the top the one measurement hovered.

**Comment by nhaugo** [comment]
I am hesitant to change the sorting order based on the currently hovered line. I have noticed that the ordering is somewhat random, I opened #719 to address this. I want to make that change first then we can revisit sort order.

**Comment by jgtaylor** [comment]
I have the problem that with two queries in the same graph, each update changes the color and swaps the values.
<img width="275" alt="correct" src="https://cloud.githubusercontent.com/assets/12651312/22818990/4aa44b82-ef70-11e6-9cd9-371d3621ac0d.png"> -- working.

<img width="264" alt="incorrect" src="https://cloud.githubusercontent.com/assets/12651312/22818994/543297e4-ef70-11e6-9758-cbadf1925518.png"> -- issue.

**Comment by 121watts** [comment]
@jgtaylor which version are you using?

**Comment by jgtaylor** [comment]
# /usr/bin/chronograf -v
2017/02/10 17:52:41 Chronograf 1.2.0~beta1 (git: 2dbddaf84a03514471ac02d112bf4d63953bdfcf)

via a Docker image on a Mac.

**Comment by 121watts** [comment]
@jgtaylor This should be resolved with the 1.2 release.
