### ISSUE TITLE
Data Explorer scales graph incorrectly

### ISSUE THREAD

**Issue by juperala** [influxdata/chronograf#711]
Version: Chronograf 1.1.0-beta2 (Windows)

In Data Explorer creating a graph for showing binary data (values either 0 or 1) scales incorrectly. When data has only few concecutive 0 values in the given date range, the graph is scaled showing only the 1 values (see examples). This happens especially if visualization is configured to show longer time periods (e.g. Last 24 hours or above), while shorter time periods may show data correctly.

**Comment by goller** [comment]
Hi @juperala , thanks for writing in!  Your examples didn't seem to come through.  Would you be able to post 'em?

**Comment by juperala** [comment]
Hi,

Yes, here is the example graph demonstrating the issue:

Graph showing past 6 hours scales the y-axis correctly from 0 to 1:  
![visualization_6h](https://cloud.githubusercontent.com/assets/4807576/21416820/aeaf26f2-c81e-11e6-8681-d1deb97c8abb.png)

Exactly same graph for past 24 hours scales the y-axis incorrectly and shows only a straight line (when value=1) and the 0  values are not visible at the graph at all. 
![visualization_24h](https://cloud.githubusercontent.com/assets/4807576/21416825/b74593aa-c81e-11e6-870c-58ae5e6de285.png)

**Comment by nhaugo** [comment]
I have set up a test server to reproduce this.

**Comment by 121watts** [comment]
Thanks for reporting the issue!  I'm fixing this in https://github.com/influxdata/chronograf/issues/707.   Once that gets merged in you should be good to go @juperala
