### ISSUE TITLE
Ability to Select TCP and HTTP to send alerts using Chronograf

### ISSUE THREAD

**Issue by ryheena** [influxdata/chronograf#713]
I have an urgent need to be able to configure alerts based on a range of criteria and have those alerts aggregate data and send it over a range of TCP ports and/or the HTTP API.  Please add these options to the dropdown menu in addition to the third-party collection agents you already support.

**Comment by nhaugo** [comment]
See 
• https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#tcp
• https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#httpout

**Comment by ryheena** [comment]
Hi,
I understand this is possible using the alert node in kapacitor but the ask is to add this to the dropdown menu of options in Chronograf.  This is oddly missing from the set of alert options in the latest beta release of Chronograf.
-Ryan 

    On Tuesday, January 3, 2017 2:21 PM, Nathan Haugo <notifications@github.com> wrote:
 

 See
• https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#tcp
• https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#httpout—

**Comment by goller** [comment]
Hi @ryheena , thanks for writing in.  Currently, we do have httpOut nodes on each alert (although they are not configurable at the moment).

The location of the httpOut endpoint is a bit ugly, however, until we have httpOut and tcp options for our alerts, perhaps it will help you.

The httpOut is at `http://ryhennas-kapacitor-server:9092/kapacitor/v1/tasks/TASK_ID/output`

To get the value of `TASK_ID` run the `kapacitor` CLI program to get the tasks: `kapacitor list tasks`  The ID will be in the `ID` column and be prefixed with `chronograf-v1-`

Let me know if this helps!

**Comment by goller** [comment]
Hi @ryheena, we added support for HTTP and TCP (as well as others) into our 1.2.0-beta2 release yesterday.  For example to use HTTP, select it as the `Send Alert to` and add the url!

Here is a gif of me testing it out:

![http](https://cloud.githubusercontent.com/assets/1922921/22854915/95069f32-f03c-11e6-9b00-5c22e1fd4af1.gif)

Try it out!

**Comment by ryheena** [comment]
Alright!  Thank you very much.  This greatly improves the usability of Chronograf.
-Ryan 

    On Saturday, February 11, 2017 7:30 AM, Chris Goller <notifications@github.com> wrote:
 

 Hi @ryheena, we added support for HTTP and TCP (as well as others) into our 1.2.0-beta2 release yesterday. For example to use HTTP, select it as the Send Alert to and add the url!Here is a gif of me testing it out:Try it out!—
