### ISSUE TITLE
Kapacitor alert message % change value is float with uncontrollable decimal places

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/chronograf#714]
Can we handle the decimal places in alert message of %change in kapacitor alerts from chronograf.

Also past value and current value seems opposite when it alerts.

**Comment by gaurav-moonfroglabs** [comment]
1st issue to control decimal point is fixed for me.

Still i would like to know about second issue.

**Comment by nhaugo** [comment]
@gaurav-moonfroglabs I can reproduce the second issue, i will be checking in a fix soon. We will probably release another beta shortly to fix this and another fairly critical bug

**Comment by goller** [comment]
Hi  @gaurav-moonfroglabs this is fixed in #717 and will be in our beta5 release (7 Jan)

**Comment by nhaugo** [comment]
@gaurav-moonfroglabs as @goller mentioned this should be fixed in the https://github.com/influxdata/chronograf/releases/tag/1.1.0-beta5 release
