### ISSUE TITLE
[Feature Request] Ability to host under path other than the default '/'

### ISSUE THREAD

**Issue by lahma** [influxdata/chronograf#721]
I couldn't find neither documentation about this being possible nor the code path that would read some sort of configuration value for web app's base path.

Use case: I want to serve web apps using nginx reverse proxy (SSL and authentication done by nginx) and configure nginx to proxy requests from /chronograf to somehost:8888 . This is not possible at the moment as all served urls are hard coded to start with '/'. So nginx fails to find resources like https://myserver/style.css , correct path would be https://myserver/chronograf/styles.css .

**Comment by goller** [comment]
Hi there @lahma, thanks for writing in.  We _very_ much want to support this.  We've placed this into our 1.2.0-beta1 milestone to be completed in the next two weeks.

Essentially, we'll have an option to allow the server to run under an arbitrary path.

**Comment by curry684** [comment]
Having the same setup as @lahma I'm really waiting for this. When will the alpha Docker image support this?  😄

**Comment by timraymond** [comment]
@lahma @curry684 This should be available in our next release. The flag that controls will be `--basepath` and should be set to something like `--basepath /chronograf`.  Thanks for the suggestion! Enjoy!

**Comment by lahma** [comment]
I guess there's no environment variable yet that would make Docker usage without altering Dockerfile possible?

**Comment by goller** [comment]
@lahma That's totally an oversight.  I've just created #819 and will merge soon.  The variable will be `BASE_PATH`

**Comment by goller** [comment]
Ok @lahma, #819 is merged.  `BASE_PATH` is now in `quay.io/influxdb/chronograf:latest`

**Comment by curry684** [comment]
Verified to be working correctly in my docker setup with custom path behind Nginx, thanks @goller!

**Comment by lahma** [comment]
Also verified, works great using Docker now. Thank you @goller for the fast develivery!

**Comment by goller** [comment]
@curry684 @lahma Excellent!
