### ISSUE TITLE
rule created by kapacitor cmd does not show on Chronograf

### ISSUE THREAD

**Issue by hvnsweeting** [influxdata/chronograf#722]
I'm using 
```
kapacitor version
Kapacitor 1.1.1 (git: master d1e0173df2b9f44c64b7bbf1a120a1bdb3ef683e)
chronograf --version
2017/01/04 11:18:54 Chronograf 1.1.0~beta4 (git: c9befd8778912614e0d6fea31724cc57a11f5bf3)
```

I can create alert rules on Chronograf UI and it shows in output of ``kapacitor list tasks`` but for rules that I created by ``kapacitor NAME -tick TICK_SCRIPT``, they does not display on the UI.

What should I do to have those rules on ``Kapacitor rules`` on GUI? 

Thank you

PS: There was the same problem for entry on ``Alert history`` but I changed my TICKScript to write to "chronograf" influxdb database so I see alert history of my cmd-defined rules now.

**Comment by goller** [comment]
Hi there @hvnsweeting, thanks for writing in!  So, right now chronograf can only really understand alerts it creates itself.  However, kapacitor 1.2 will have a _bunch_ of new features around alerting that will make chronograf's support much better.

Our plan is to integrate with kapacitor's new alert manager feature.  When we do so, we'll be able to support your use case!

**Comment by jeremyd** [comment]
+1 I would *love to have this alerts show up in the UI.  All my tick scripts are currently loaded into kapdaemon via kapacitor command line.

**Comment by lin-credible** [comment]
**+1**

**Comment by nhaugo** [comment]
Dupe #221

**Comment by goller** [comment]
@hvnsweeting At long last all kapacitor tasks are on the the chronograf alert rules page!  It will be in our upcoming release.

**Comment by hvnsweeting** [comment]
yay, finally, thank you for all the great efforts <3
