### ISSUE TITLE
tmpltime() variable uses current computers timestamp

### ISSUE THREAD

**Issue by KoenR3** [influxdata/chronograf#723]
My usecase is the following:

All my metrics are being pumped into influxdb in UTC (as some are coming from different timezones).  

When I use chronograph and use tmpltime() to be able to do a range selection, it uses the computers local timezone.  However, the timestamps in influxdb are in UTC, which differs.  This makes for some very inconsistent behaviour (i.e. data from one hour ago using tmpltime() does not correspond to the data from one hour ago).  Is there a possiblity to add a tag to tmpltime() which would allow to select the timezone of the timestamps in influxdb to convert to the browser timezone?  Using something like moment.js should make this possible?

**Comment by nhaugo** [comment]
@KoenR3 it looks like this is in reference to the old chronograf, right now we are not making any changes to that code base. I will move this ticket to that repository, which is unfortunately closed source, so you wont be able to track it. Sorry about that.

**Comment by KoenR3** [comment]
@nhaugo I am using v1.0.0-rc1.  I am correct in assuming that this is the open source version?

**Comment by nhaugo** [comment]
That is the old version, the newer open source versions are 1.1.0-beta-1 and above, the current version is 1.1.0-beta-5.
