### ISSUE TITLE
Optimize loading of `Tags` tab in Data Explorer

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#750]
![gif](http://g.recordit.co/DjJW59Bq47.gif)

Large numbers of tags cause very slow loading (Shocking!). There is also no indication that the UI is loading data.

There is no indication that queries are running or data is loading. Pulling the tag names with `show tag keys` and then pulling the values with `limit/offset` queries (`show tag values on location from "reports_shodan" with key = "version" limit 10 offset 0`) could potentially help fix this problem.

**Comment by alexpaxton** [comment]
@jackzampolin @nhaugo I think a simple loading spinner could go a long way to remedy this issue. Just gotta tell users to wait a sec

**Comment by 121watts** [comment]
This should no longer be an issue because tags are now hidden under measurements.
