### ISSUE TITLE
Y axis on data explore does not properly display when two queries return very different results

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#753]
Reproduction steps:
• Enter one query where the peak y value is around 10
• Enter a second query where the peak y value is much lower, like 1

Depending on the order the queries are executed the max y value is either from query 1 or 2, if the larger query finishes first the graph looks right. However, if the smaller value query finishes first the y axis max is set very low and the larger query back fill color looks like background color.

It looks like you can just set up the queries and wait for this to happen since sometimes one query will finish before the other then next time they will finish in the other order.

**Comment by mmadhusudan** [comment]
I am using chronograf 1.6 version (the latest). I still see the issue. Do we have a roadmap on when this would be fixed?
![image](https://user-images.githubusercontent.com/44047445/46780490-9ff17980-cd3a-11e8-85b2-d32cdff2801f.png)
