### ISSUE TITLE
Adding Kapacitor with username and password fails to get config

### ISSUE THREAD

**Issue by brycekahle** [influxdata/chronograf#754]
OS: Using docker image, `latest` tag (`3c7e25b`)

Add a InfluxCloud hosted Kapacitor instance with a username and password.
The proxy request
```
http://localhost:7777/chronograf/v1/sources/1/kapacitors/1/proxy?path=%2Fkapacitor%2Fv1%2Fconfig%2Finfluxdb
```
to obtain the config at `/kapacitor/v1/config/influxdb` will fail with the error message: `unable to parse authentication credentials`. I proxied the request through Charles on my machine and confirmed no authentication information was added.

**Comment by goller** [comment]
@brycekahle Thanks for writing in!  I'll test it right now on InfluxCloud and figure it out.

**Comment by goller** [comment]
@brycekahle I found the problem and have  PR in: https://github.com/influxdata/chronograf/pull/755

I was able to test it against my own InfluxCloud kapacitor instance and was able to fix the auth.
However, cloud looks like it is running kapacitor 1.0.1.  @rossmcdonald Is there an upgrade plan to 1.1 (the minimum version for chronograf).

**Comment by brycekahle** [comment]
@goller Thanks for the quick fix! Let me know about the InfluxCloud upgrade. Chronograf will be a big help with defining alerts.
