### ISSUE TITLE
Sources page shows 2 Defaults

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#769]
<img width="648" alt="screen shot 2017-01-13 at 11 18 46 am" src="https://cloud.githubusercontent.com/assets/2433762/21942593/90f80c12-d982-11e6-9e2f-ef227a2a26a1.png">

Happens after I set a new default source, and the return to manage sources page. Only visible until page refresh

**Comment by jademcgough** [comment]
I've noticed this for a while too :(
