### ISSUE TITLE
Make refresh time configurable in dashboards

### ISSUE THREAD

**Issue by ndemengel** [influxdata/chronograf#781]
Hi guys,

First, thanks for all the good stuff!

Then, currently there's no way to specify data precision and refresh time for dashboards. It looks like the refresh time is hard-coded to 15s (autoRefreshMs) and the data precision in dashboard is 1min. It would be great to allow user to configure those parameters for dashboard and/or individual graphs, for instance : "refresh the view every 10 seconds", "display data with a 5 second precision".

I thank you in advance for considering this request.

**Comment by goller** [comment]
Hi @ndemengel, thanks for writing in! Sorry it took a bit to get back to you; we've been having our company get-together this week :)

I really like the request and I think it makes a lot of sense!  Do you think we should have specific choices (1h, 3h, 1d, etc) or allow the field to be specified directly by typing?  Or both?

**Comment by oboukili** [comment]
Hi guys,
As @goller suggested, having both (typing/choices) would be invaluable to set precision and/or refresh time, as an operational standpoint.

Thanks !

**Comment by ndemengel** [comment]
Hi @goller,

Given the many different scenarios one would want to set-up a graph/dashboard for, I suppose it would be better to just let the user type what she wants in the definition file.

Thanks again!

**Comment by nhaugo** [comment]
Split into two issues, precision moved to https://github.com/influxdata/chronograf/issues/913

**Comment by nhaugo** [comment]
Persist the last used value in browser local storage.

**Comment by nhaugo** [comment]
@alexpaxton can you pick a place and icon for the widget

**Comment by alexpaxton** [comment]
![screen shot 2017-02-22 at 11 32 46 am](https://cloud.githubusercontent.com/assets/2433762/23228815/c70c2646-f8f2-11e6-82b3-07c35b3d4e3b.png)

Screenshot from Chosen UI. Could be cool to add an optional custom text field to the dropdown component

**Comment by jaredscheib** [comment]
Here's a well-maintained React port of Chosen that could be super useful: https://github.com/JedWatson/react-select. Live demo here: http://jedwatson.github.io/react-select/.

**Comment by alexpaxton** [comment]
@jaredscheib so sick. That looks super useful
