### ISSUE TITLE
stateChangesOnly & exec

### ISSUE THREAD

**Issue by flcaza** [influxdata/chronograf#782]
Hi,

First of all great great work for this tool. 
Second I would like to be added more features in chronograf like stateChangesOnly or exec. I want to setup this but i can not do it from CreateNewRule page in chronograf.

IF you can add more rules will be very appreciate. 

Thank you !
Florin

**Comment by goller** [comment]
@flcaza Thanks for writing in!  I think we should absolutely support exec.  Currently, are alerts should all be constructed with `stateChangesOnly`.  However, I think we should expose a way _not_ have `stateChangesOnly`.

**Comment by goller** [comment]
Hi @flcaza, the team added in support for a lot more alerts nodes in yesterday's 1.2.0-beta2 release.

Here is a gif of me testing it out:

![exec](https://cloud.githubusercontent.com/assets/1922921/22854861/99695a2a-f03b-11e6-86b7-8e2228029afb.gif)

Try it out!

**Comment by sawo1337** [comment]
Can someone confirm if stateChangesOnly is supposed to be present by default in Chronograf? I'm using the latest official release, but stateChangesOnly is missing, I can add it manually obviously, but whenever I make an update to the task via Chronograf, that property gets removed?
