### ISSUE TITLE
Alert History

### ISSUE THREAD

**Issue by flcaza** [influxdata/chronograf#784]
Hi

Is any way to delete alert history ? at this moment i have 8410 Alerts (testing purpose) and i want to delete if it is possible.

Thank you !
Florin

**Comment by goller** [comment]
Hey @flcaza, sadly, we don't at the moment, although we have ideas around how we want to do it.  As a work around all the alerts are stored in your influx under the database `chronograf` and measurement `alert`.... you could remove them from there from now, but, we'll definitely make it a priority to make this far better.

**Comment by nhaugo** [comment]
@flcaza the other solution is to set the retention policy on the `chronograf` database. The alerts are currently put into your kapacitor's influxdb as the measurement `chronograf.<default rp>.alerts`. With kapacitor 1.2 alert state will be handled internally by kapacitor, so the source of this data will be changing. Therefore we will not be making changes to the current influxdb storage method of alerts.
