### ISSUE TITLE
Graph legend does not match table data when using non-alphabetically ordered select query

### ISSUE THREAD

**Issue by Jervelund** [influxdata/chronograf#785]
When viewing data for the following query in graph view, the contents of the legend does not match the contents of the table:
`SELECT "out", "err" FROM "udp"."autogen"."pid_outer" WHERE time > now() - 6h`

Notice that values/names in the graph legend are swapped, compared to data in the table view:
<img width="1585" alt="screen shot 2017-01-20 at 13 04 22" src="https://cloud.githubusercontent.com/assets/4208762/22149167/9f9caf62-df12-11e6-89ef-8c06cedf8dce.png">
<img width="1581" alt="screen shot 2017-01-20 at 13 04 33" src="https://cloud.githubusercontent.com/assets/4208762/22149168/9f9cd06e-df12-11e6-92f0-6aac4cbad66a.png">

Workaround is ordering measurements alphabetically in the query:
`SELECT "err", "out" FROM "udp"."autogen"."pid_outer" WHERE time > now() - 6h`
<img width="1584" alt="screen shot 2017-01-20 at 13 12 26" src="https://cloud.githubusercontent.com/assets/4208762/22149188/bf187114-df12-11e6-831d-4dc750a64ddb.png">
<img width="1584" alt="screen shot 2017-01-20 at 13 12 42" src="https://cloud.githubusercontent.com/assets/4208762/22149189/bf1a3120-df12-11e6-93e3-4b2626f07bd6.png">

Could it be related to this? https://github.com/influxdata/chronograf/pull/742

I'm using Chronograph 1.1.0~beta6 and Influx 1.1.1 from the influxdata website on Windows10.

**Comment by 121watts** [comment]
Thanks for opening the issue.  If I'm understanding you correctly, you'd like the fields in the table to be alphabetically sorted?

**Comment by Jervelund** [comment]
Not exactly. :-)

I'll try to rephrase:

If you look at the first screenshot, you can see "out" has a value of approx -20 while "err" has a value of approx -13. The table correctly displays the values which are stored in Influx.
If you look at the second screenshot, "out" has an incorrect value of -13 while "err" has an incorrect value of -20. The graph displays data incorrectly, as the name/value pairs are swapped.

This only occurs if the measurements queried are not in alphabetic order.
For screenshot 3 and 4 the query is alphabetic and shows data correctly in table view and graph view.

**Comment by 121watts** [comment]
Ah!  Okay.  That makes sense.  Looking into it.

**Comment by cryptoquick** [comment]
Hi, @Jervelund , @121watts and I have completely refactored the function responsible for this issue. Would you mind checking out Chronograf on this branch: https://github.com/influxdata/chronograf/tree/bugfix/legend-data-order
And could you tell us if this fixed your issue?

**Comment by Jervelund** [comment]
Hi @cryptoquick Thanks for the update. I have built on OS X 10.11.6 and tested against the same datasource as I used on the windows client.
The issue is solved.

**Comment by cryptoquick** [comment]
So glad to hear that, @Jervelund ! We should be shipping this fix soon in the latest release.

**Comment by 121watts** [comment]
@Jervelund, we just merged the refactor of the function causing this issue.  Should be 👍 .
