### ISSUE TITLE
Chronograf totally unusable if not running telegraf

### ISSUE THREAD

**Issue by oliverjanik** [influxdata/chronograf#792]
I really like InfluxDB but I'm testing out Chronograf 1.1.1 and it seems to be kind of broken out of the box.

I'm running InfluxDB on the same machine and I'm populating it with some custom telemetry from our app. I do not have telegraf running yet anywhere.

Right of the bat the homepage redirects to /sources/1/hosts and I get this in the console:
```
GET http://redacted/chronograf/v1/me 418 (I'm a teapot)
(anonymous) @ vendor.5263628….js:60
e.exports @ vendor.5263628….js:60
app.b6f8d96….js:4 TypeError: Cannot read property 'findIndex' of undefined
    at app.b6f8d96….js:2
(anonymous) @ app.b6f8d96….js:4
```

I go to /sources/1/dashboards and I'm greeted with:
```
GET http://13.55.32.250:8888/chronograf/v1/me 418 (I'm a teapot)
(anonymous) @ vendor.5263628….js:60
e.exports @ vendor.5263628….js:60
app.b6f8d96….js:3 Uncaught (in promise) TypeError: this.state.dashboards.map is not a function
    at Object.render (app.b6f8d96….js:3)
    at d._renderValidatedComponentWithoutOwnerOrContext (vendor.5263628….js:196)
    at d._renderValidatedComponent (vendor.5263628….js:196)
    at d._updateRenderedComponent (vendor.5263628….js:196)
    at d._performComponentUpdate (vendor.5263628….js:196)
    at d.updateComponent (vendor.5263628….js:196)
    at d.performUpdateIfNecessary (vendor.5263628….js:196)
    at Object.performUpdateIfNecessary (vendor.5263628….js:43)
    at s (vendor.5263628….js:43)
    at r.perform (vendor.5263628….js:45)
```

All I was hoping for:
- create charts based on queries (seems to work on in Data Explorer)
- Save charts into dashboards (where is this option?)
- Have dashboards displayed on a monitor in the office 24/7

Is Chronograf still an alpha product, not recommended for general use?
What's with the teapots?

**Comment by nhaugo** [comment]
Hi @oliverjanik chronograf 1.1+ is not yet suitable as a general purpose dashboard solution. With 1.2.x you should start to see some basic dashboarding features, but the initial goals of the project are to create an out of the box DevOps monitoring application that works with telegraf.

Chronograf is still in beta as you noted and is likely to remain that way for the next few months. 

The older 1.0 version of chornograf is still currently a better solution for the use cases you listed, but again, that should be changing with the next couple of releases (chronograf is on a two week cycle, we release every other friday).

You can read more about the goals of the project here https://www.influxdata.com/announcing-the-new-chronograf-a-ui-for-the-tick-stack-and-a-complete-open-source-monitoring-solution/

The 418 http error is a result of oauth not being set up, it isn't a critical error.

Please let me know if I can answer any other questions for you.
