### ISSUE TITLE
As a user I can send an alert as an http or tcp output

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#793]
• The alert output drop down should always have the option for tcp and http
• These outputs do not need to be pre configured
• If either is selected the user should be presented with text inputs that allow them to add an http or tcp  address and a message
• Initially do not do any validation of these fields
![httptcp](https://cloud.githubusercontent.com/assets/1003269/22256065/634e8f68-e20e-11e6-896f-1103f0bb4c9d.png)

**Comment by goller** [comment]
Backend support complete in #857
