### ISSUE TITLE
[kapacitor] Implement post alert output

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/chronograf#801]
The [`.post()`](http://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#post) output for kapacitor allows for the sending of requests containing alert data. This allows users to easily hook existing systems into kapacitor.

**Comment by goller** [comment]
Hey @jackzampolin, hope vacation is going well!  We added this in the 1.2.0-beta2 release!

**Comment by jackzampolin** [comment]
@goller Gangster! Thank you!
