### ISSUE TITLE
Unable to apply function to field when field below has function applied

### ISSUE THREAD

**Issue by Jervelund** [influxdata/chronograf#820]
When a function have been applied to a field, and an additional field is selected, it is mandatory to select a function in order for the field to be displayed in graph or in the table view.

There seems to be an issue when adding a field above an already selected field.

Example: "out_scaled" is already selected with the "mean" function. I now want to display "out" with the "mean" function as well.

Initial view:
<img width="500" alt="screen shot 2017-01-29 at 22 39 12" src="https://cloud.githubusercontent.com/assets/4208762/22408157/24f84c4e-e674-11e6-81ed-1a7eff1513fe.png">

After enabling the "out" field:
<img width="506" alt="screen shot 2017-01-29 at 22 39 17" src="https://cloud.githubusercontent.com/assets/4208762/22408174/adedfb0c-e674-11e6-8331-b66d2c71f569.png">

After opening the "Apply functions" dropdown for "out" (notice that the "mean" selection from "out_scaled" is displayed on top of the "Apply functions" dropdown):
<img width="498" alt="screen shot 2017-01-29 at 22 39 24" src="https://cloud.githubusercontent.com/assets/4208762/22408176/b353ed9a-e674-11e6-8b90-181f4bba181d.png">

After selecting "mean" in the dropdown for "out", the change is not possible to apply, as the <select> from out_scaled is covering up the "Apply" <li> at the top of the dropdown for "out".
<img width="508" alt="screen shot 2017-01-29 at 22 39 30" src="https://cloud.githubusercontent.com/assets/4208762/22408265/c61087ac-e676-11e6-838a-c1a8c432dc8a.png">

Chronograf 1.1.0~beta6 from website and Chrome 56.0.2924.76 (64-bit) on OSX10.11.6

**Comment by Jervelund** [comment]
Adding the following CSS ensures the "Apply" button stays on top:

```
.multi-select-dropdown__apply{
    position: relative;
    z-index: 1000;
}
```

<img width="508" alt="screen shot 2017-01-29 at 23 09 32" src="https://cloud.githubusercontent.com/assets/4208762/22408364/07935672-e678-11e6-837c-fc322a3ddaa4.png">

**Comment by goller** [comment]
@Jervelund Thanks for writing in, and thanks for the patch!  We'll get it worked in!
