### ISSUE TITLE
As a user I can enter meta server information in the connection config

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#825]
• Should work both on initial setup and editing
• Add a dropdown that allows users to enter meta info
• Store the information in bolt
• On edit meta info should be displayed if it exists

![meta](https://cloud.githubusercontent.com/assets/1003269/22471926/e04608d2-e788-11e6-8fca-7dd413e83364.png)

**Comment by jademcgough** [comment]
goller says that it shouldn't be necessary to have username and password for the meta, we can reuse the cluster info
