### ISSUE TITLE
Backend client for the enterprise meta service

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#826]
• Use connection string to find a member of the meta ring
• Get all members of meta service
• Find the leader
• Issue commands to meta service, check for current leader before issuing command
• Return json result from proxy

**Comment by jademcgough** [comment]
- should get a 307 when trying to query a non-leader, which will provide new leader

**Comment by goller** [comment]
• need shards (or perhaps `SHOW SHARDS` from db)
• /chronograf/v1/sources/1/roles (created, deleted, updated, get)
    - zero or more permissions
    - zero or more users.
•  /chronograf/v1/sources/1/users (created, deleted, updated, get)
    - zero or more permissions

• need permissions (static of list of strings that is version dependent)
  - 0     "ViewAdmin",
  - 1     "ViewChronograf",
  - 2     "CreateDatabase",
  - 3     "CreateUserAndRole",
  - 4     "AddRemoveNode",
  - 5     "DropDatabase",
  - 6     "DropData",
  - 7     "ReadData",
  - 8     "WriteData",
  - 9     "Rebalance",
 - 10     "ManageShard",
 - 11     "ManageContinuousQuery",
 - 12     "ManageQuery",
 - 13     "ManageSubscription",
 - 14     "Monitor",
 - 15     "CopyShard",

**Comment by nhaugo** [comment]
connect #101
