### ISSUE TITLE
As a user in DE I will get a warning if my query will return more data than the browser can handle

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#829]

**Comment by 121watts** [comment]
Does it makes more sense to truncate a large response on the server and then return an error.  Thoughts? @goller @nhaugo

**Comment by goller** [comment]
... brainstorming up alternatives besides byte limit and decimation: 

@121watts did you ever play around with `LIMIT` or `SLIMIT` ?

**Comment by goller** [comment]
# Minimizing time data
I think the only time we could filter by time would be if the number of values returned was larger than around 4000 (4k is 3840 wide).   

By default telegraf records at 10 second intervals so 4000 pixels is around 11 hours of data.

Here is a formula calculate a group by time that would result in the number of values equal to resolution:

[
![](https://latex.codecogs.com/gif.latex?\text{group&space;by&space;duration}&space;=&space;\frac{\text{view&space;duration}}{\text{resolution&space;pixels}&space;\times&space;\text{data&space;frequency}})
](
https://latex.codecogs.com/gif.latex?\text{group&space;by&space;duration}&space;=&space;\frac{\text{view&space;duration}}{\text{resolution&space;pixels}&space;\times&space;\text{data&space;frequency}})

This means that the chronograf front-end could inspect queries for the time range and group by to calculate the approximate number of values that would be returned.   If the number of values was much larger than the resolution the user could be warned.

### Query Builder Automatic group by
In the data explorer query build the user sets the time range window.  Currently, the user must set the group by time for aggregate functions.  However, with the knowledge of the screen resolution, that group by time could instead be calculated to give the most possible data points on the graph.

### InfluxQL Automatic group by when possible
With the upcoming structured query endpoint, it would be possible calculate the number of values by getting the AST of the query. In the AST it is possible to get the group by time and the time range.  The query could be manipulated to have an appropriate group by time.

# Minimizing Tag data
Time is only one dimension of the problem.  The other is the tag.  A pathological example where the number of tags dominate would be 2 million hosts that recorded 1 data point.  

When we graph the results of InfluxQL, we graph each tag as its own line graph.   However, the numbers of tags returned per query request can be limited by the `SLIMIT` keyword.    Using  `SLIMIT` it would be possible to restrict the amount of data returned on the wire.   You could imagine a progress load of tags into a graph with multiple calls with increasing `SOFFSET`.

# When to server-side filter?

1. no group by time
2. ... and ... whose time range was sufficiently large
3. ... and ... and user disregards the warning.

Honestly, that seems like a remote possibility.  If the warning could discuss how one could make a better query (e.g. suggesting an appropriate group by), I think most users would change their query.  Even better, the warning could ask the user to add the group by.

**Comment by 121watts** [comment]
@goller.  In your equation how to do we get the data frequency?
