### ISSUE TITLE
Chore tool tip cleanup

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#830]
@timhallinflux and @rkuchan to provide a list of widgets and tool tips

**Comment by rkuchan** [comment]
### Tooltips

| Widget  | Location(s) | (Recommended) Tooltip   |  
|---|---|---|
|  
![influxdb-source](https://cloud.githubusercontent.com/assets/8750814/24210250/c120dbb0-0ee5-11e7-8598-26ef09611fb3.png) | HOST LIST, EXPLORER, all DASHBOARDS, ALERT HISTORY, KAPACITOR RULES*  | InfluxDB source | 
| ![autorefresh-interval](https://cloud.githubusercontent.com/assets/8750814/24210408/376e4884-0ee6-11e7-97ce-1ae3f09e9f94.png)  | all DASHBOARDS, EXPLORER  | Autorefresh interval (that wording appears when you click on the widget but we kinda like the idea of replacing that with a tooltip)  |  
|  ![time-range](https://cloud.githubusercontent.com/assets/8750814/24211594/c9df903a-0ee9-11e7-9956-becb69a4f2a6.png)  |  all DASHBOARDS, EXPLORER, RULE CREATION | Time range (that wording appears when you click on the widget but we kind like the idea of replacing that with a tooltip)  |
|  ![full-screen](https://cloud.githubusercontent.com/assets/8750814/24211690/10639fce-0eea-11e7-84fe-50761536a479.png) | all DASHBOARDS | Full screen |
|  ![tag-key](https://cloud.githubusercontent.com/assets/8750814/24211752/41c2e480-0eea-11e7-98c5-9b27820d5d01.png) | EXPLORER | Tag key equals; Tag key does not equal | 

\* The InfluxDB source widget should probably also appear in the ADMIN section too.

### Bonus! Quick wording changes

* The `Filter by Hostname` and `Filter Alerts by Name` text on the HOST LIST and ALERT HISTORY pages aren't accurate. We think `Filter by column` or `Filter by column content` is more descriptive.
* The `Templates:` text on the rule creation page might be clearer if it says "Click to add template:`.
