### ISSUE TITLE
As a user I can see a retention policy management page

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#832]
• Add a menu item for Database and Retention Policies
• Show existing DBs
• Show existing RPs for each DB
• Create database button
• Create, delete and edit for retention policies on each DB
• Allow user to edit RF, duration and default status for RPs
• Test behavior for changing default status or deleting current default of RPs
• Warn people on deletion of default RP

![db-manager](https://cloud.githubusercontent.com/assets/1003269/23911946/8fdee7e0-089b-11e7-94c4-97556cf4e799.png)

**Comment by nhaugo** [comment]
Get left rail menu item name from @timhallinflux

**Comment by timraymond** [comment]
I started porting this over, and we're kind of in a weird place with this. The retention policies page as it exists in EW has dependencies on some things like clusterIDs that only exist in Enterprise. We want to support both ultimately, and we're going to run into this more, so I think it's worth having a larger conversation about how we want to handle different sets of queries, and queries that have to be directed to meta for Enterprise vs. OSS which can be directed at the query endpoint.
