### ISSUE TITLE
[Feature Request] option to add .details along with message under kapacitor rules

### ISSUE THREAD

**Issue by chetu** [influxdata/chronograf#838]
Need option to add 

.details along with message under kapacitor rules.

It will make easy to add email alert with proper   ##template.

**Comment by goller** [comment]
Hi there @chetu, thanks for writing in! Yup, I agree.  Do you think we should add the ability to fill out .detail for all alerts or just those like email that really do need it?

**Comment by chetu** [comment]
Hello Goller, 
Yes its much required , We see Influx-Telegraf-Kapacitor-Chronograf good replacement for monitoring tool like Nagios with more and more enhanced analytics usage .
Kapacitor TICK rules much effectively managed by Chronograf WUI.

**Comment by avdhoot** [comment]
@goller It is good have option (.detail) for all alerts so user can decide to use or not. Thanks

**Comment by partheshzeotap** [comment]
#834

**Comment by goller** [comment]
@chetu @avdhoot @partheshzeotap We've just merged in support for the detail field for kapacitor alerts.  It'll be out for our next release this Friday or in master now.  Let us know how it goes!
