### ISSUE TITLE
Number format (precision) in y axis' graph 

### ISSUE THREAD

**Issue by abouillot** [influxdata/chronograf#839]
I have some atmospheric pressure data to display - it will be in the range 870- 1090hPa with little variation over time.

When drawing the data, I only the values as 1K. If I divide by 1000, the value will be displayed with only two decimal.

It would be great to have a mean to control how the numbers are transformed, so the last digit could be known in such situation, as this can be significant for some use cases

**Comment by goller** [comment]
Hi @abouillot thanks for writing in! (and moving this from google groups).

Yeah, I see what you mean.  We need to have configurable sigfigs for sure.
