### ISSUE TITLE
[Feature Request] Increase the scroll bar area on very large lists

### ISSUE THREAD

**Issue by unixninja92** [influxdata/chronograf#843]
My hosts list says I have 789 hosts (most of which no longer exist), and my scroll bar is literally just a small circle. It would be really nice if there were only 50-100 hosts per page with next and back buttons.

**Comment by goller** [comment]
@unixninja92 Hey there again!  Yeah, pagination for sure.  We have about 600 hosts we regularly monitor and it is too much.  Definitely need this.

**Comment by nhaugo** [comment]
@unixninja92 is there any reason that keeping a minimum size on the scroll bar and changing the scroll rate to match won't resolve your issue? I'm not totally sure that pagination will make finding hosts any easier.

**Comment by unixninja92** [comment]
@nhaugo That sounds fine to me.

**Comment by jaredscheib** [comment]
@unixninja92 @nhaugo I made the scroll bar thumb element larger. Wouldn't be able to adjust the height and scroll rate without creating adding a custom scrollbar component, which would be a new feature to maintain. Happy to discuss tackling that if the current patch doesn't feel sufficient.
