### ISSUE TITLE
kapacitor rules [tasks] disable option

### ISSUE THREAD

**Issue by chetu** [influxdata/chronograf#847]
Need to option to mute kapacitor tasks from chronograf UI.

Right now we have to do it from kapacitor cli :
- **kapacitor list  tasks**
- **kapacitor disable taskid**

The requirement to mute rules is required when we plan downtime/maintenance to production servers and avoid all alerts during maintenance  period.

**Comment by goller** [comment]
@chetu thanks for writing in and absolutely we need to do this!

**Comment by alyan2008** [comment]
Yes, it will be very useful for us as well. Also I want to have the ability to write some comments when I disable tasks or I wan`t to disable it for some time (it should be automatically enabled after some time)

**Comment by goller** [comment]
@alyan2008 I agree that recording comments about alerts is important.  

@nathanielc does kapacitor have facilities for adding "notes" to a task?  I don't see anything in the API (https://github.com/influxdata/kapacitor/blob/master/client/API.md#tasks).

**Comment by nathanielc** [comment]
@goller No it does not. Slightly related we do plan to add a silence feature to Kapacitor that would allow you to silence individual alerts without needing to disable the entire task. That feature would accept "notes" about why an alert was silenced. Although there is some overlap here so we should make sure the use case is clear.

**Comment by goller** [comment]
Hi @chetu and @alyan2008, @121watts and I have  PR #868 up that implements disabling and enabling of the alerts.

We are hoping to get it merged in for today's release!

**Comment by goller** [comment]
We were able to get the disable/enable into 1.2.0-beta2 release yesterday.  

@alexpaxton styled it like this on the alerts page:

![kapacitor-checkboxes](https://cloud.githubusercontent.com/assets/1922921/22854703/272800de-f03a-11e6-8899-23a29a7291b3.gif)

Try it out!

**Comment by alekseyp** [comment]
Hey guys, it doesn't work when you have more then 1 alert.
It always disables/enables first one.

**Comment by goller** [comment]
@alekseyp Just reproduced this.  Expect a hotfix soon.

**Comment by lin-credible** [comment]
@goller  @alekseyp  **+1**
(It always disables/enables the first one).
