### ISSUE TITLE
On the hosts page if I filter all hosts I get "Loading Hosts..."

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#855]
I filtered for a host I thought existed, but didn't... so I waited :)

<img width="1213" alt="image" src="https://cloud.githubusercontent.com/assets/1922921/22752135/085f3d1e-edfd-11e6-84f1-0fe1753e8f0f.png">

**Comment by jademcgough** [comment]
heh, I'll fix this today

**Comment by jademcgough** [comment]
and by today, I mean in 20 days
