### ISSUE TITLE
As a monitoring expert I want to have additional conditions for rules

### ISSUE THREAD

**Issue by alyan2008** [influxdata/chronograf#858]
It will be very useful if I can create few rules and alert should be triggered when all of rules were triggered (AND) or when one rule from the list was triggered (OR).

**Comment by goller** [comment]
Hi @alyan2008 , thanks for writing in!  I think this is great.  We are going to continue to add more and more support in chronograf for the kapacitor features.   However, I think this is a duplicate of issue #741, so, I'm going to close it out.
