### ISSUE TITLE
As a user I can delete a cell

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#889]
• Cells should have an delete menu button in the upper right
• The menu should contain a delete item
• Delete should remove the cell from the workspace

![edit delete](https://cloud.githubusercontent.com/assets/1003269/22987415/7f9b9f6a-f363-11e6-946c-21013fbbb578.png)

![edit](https://cloud.githubusercontent.com/assets/1003269/22987471/b6d92420-f363-11e6-8e58-8ece30cfe6eb.png)

**Comment by timraymond** [comment]
Depends on #949
