### ISSUE TITLE
Play nice with authorization

### ISSUE THREAD

**Issue by bmorg** [influxdata/chronograf#890]
When adding a source, the provided user seems to need admin privileges in order to not get an error.

Otherwise there will be a "Unable to connect to source" error displayed in both the host list and a host's graphs, which both seem to otherwise work just fine.

Specifically, a `READ` grant on the `telegraf` database should be more than enough for Chronograf to work.

**Comment by goller** [comment]
Hi @bmorg, thanks for writing in! Yes, I agree.  We'll take a look at which queries are causing this problem.   At the very least we should state what permissions the chronograf user needs (for example it would need to `READ` kapacitor).

**Comment by bmorg** [comment]
Thanks @goller! I for one haven't even gotten around to installing Kapacitor yet, so I don't have a `kapacitor` database.

**Comment by goller** [comment]
@bmorg we found out that `SHOW DATABASES` for a read-only user is a limitation of influxdb at the moment.  However, @mark-rushakoff is writing support for `SHOW DATABASES` right now for InfluxDB 1.3.

**Comment by mark-rushakoff** [comment]
It's already merged in master of open source InfluxDB: https://github.com/influxdata/influxdb/pull/7974

**Comment by nhaugo** [comment]
Fixed by InfluxDB 1.3
