### ISSUE TITLE
As a user I can see the queries page from enterprise web

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#894]

**Comment by timraymond** [comment]
Chronograf should have a page resembling the following screenshot, which allows users to view which queries are currently executing, the database that those queries are executing against, and the running time of that query. There should also be a link for each query allowing users to kill running queries after confirming.

![influxdata_-_enterprise_manager_8](https://cloud.githubusercontent.com/assets/288061/23364094/a7f08356-fccb-11e6-9226-93bf3258f247.png)
