### ISSUE TITLE
chronograf not showing any data in dashboad 

### ISSUE THREAD

**Issue by kumar2000s** [influxdata/chronograf#895]
Hi
I have setup the chronograf but not showing any data in dashboad
i can see the below in logs

INFO[2714] Request component=server method=POST remote_addr=xx.xx.xx.xxx:62683 url=/chronograf/v1/sources/2/proxy
INFO[2714] Request component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/mappings
INFO[2716] Request component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/sources/2/kapacitors
INFO[2718] Request component=server method=GET remote_addr=xx.xx.xx.xxx:62683 url=/chronograf/v1/mappings
INFO[2718] Request component=server method=POST remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/sources/2/proxy
INFO[2718] Request component=server method=POST remote_addr=xx.xx.xx.xxx:62682 url=/chronograf/v1/sources/2/proxy
INFO[2771] Request component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/sources/2/hosts
INFO[2771] Serving assets component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/sources/2/hosts
![chronograph](https://cloud.githubusercontent.com/assets/12763366/22995413/c9578f32-f3f0-11e6-9a46-4438e4f7b7ca.PNG)

**Comment by goller** [comment]
Hi @kumar2000s , thanks for writing in!  

Easy question first... when you click on the white icon at the top of the menu bar:
![menu](https://cloud.githubusercontent.com/assets/1922921/22995518/da9b334e-f390-11e6-9f8d-2aa34a7c3828.png)

Are there any hosts there?  If not, have you installed telegraf? (here is the telegraf installation guide: https://github.com/influxdata/chronograf/blob/master/docs/INSTALLATION.md#telegraf-setup)

If you have done all those things, would you run the chronograf server with log level debug?
Here's how:
```sh
chronograf --log-level=debug
```
... and post those logs here?  That'll help us really dig into what is happening.

**Comment by kumar2000s** [comment]
Hi  Chris

yes the telegraf was installed , somehow i got it working. let me tell you
why it was not working for me.
initially i generated the custom telegraf conf file for cpu and mem metrics
only and the host was not visible in chronograf,
after some hit and trial i decided to use the original telegraf conf with
all metrics and then i was able to see the host in dashboard.

can you please help to understand this behavior ?

Regards
Sunil Kumar

**Comment by goller** [comment]
Hi @kumar2000s, ah!  Now I know what is going on.  This is one of our known issues here: https://github.com/influxdata/chronograf#known-issues

For now we require telegraf to have the `CPU` and `system` plugin enabled. 

I'm glad you figured it out!
