### ISSUE TITLE
custom name option for tasks ID created by chronograf

### ISSUE THREAD

**Issue by chetu** [influxdata/chronograf#899]
We need custom ID name of tasks.

it is important when we call kapacitor api for enable/disable/update specific tasks.

if we have custom name the API will have fixed name of tasks to call.

**Comment by chetu** [comment]
![tasks_name](https://cloud.githubusercontent.com/assets/395601/23012964/a54ec458-f44e-11e6-8418-90cce80d07fe.png)

**Comment by goller** [comment]
Hi @chetu, you are totally right.  I have some ideas I'm going to try right now to make this not terrible.  

Some background on the problem:  originally, we restricted which kapacitor alerts would be shown to the user in chronograf.  With our upcoming kapacitor editor we will be able to show all tasks.

**Comment by russorat** [comment]
alert rules will continue to have a chronograf name. in 1.5, we have added the ability to set the name of custom tick scripts through chronograf.
