### ISSUE TITLE
Precanned dashboards scaling issues (wrong interpolated values)

### ISSUE THREAD

**Issue by oboukili** [influxdata/chronograf#900]
On any dashboard, when selecting a different time interval, the interpolated values are off by a high margin (100/200/300% etc).

![chronograf-dashboard-scaling-issue](https://cloud.githubusercontent.com/assets/16975408/23027775/ae03a5a2-f465-11e6-9611-3cd62cbbe748.gif)

**Comment by goller** [comment]
Hi @oboukili, thanks for writing in !  Yikes, my instinct is that we are not using the `GROUP BY` correctly.  

If you can, would you tell us a bit about your telegraf setup?

**Comment by goller** [comment]
Ok @oboukili, I've confirmed that we aren't setting the right `GROUP BY` in our queries.

Notes:
To figure out the appropriate tags to group by see: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/elasticsearch/elasticsearch.go

"groupbys" in the [layout](https://github.com/influxdata/chronograf/blob/master/canned/elasticsearch.json) need to be updated.  Likely:

```json
"groupys": ["\"node_host\""]
```

**Comment by oboukili** [comment]
Hi @goller, thanks for your reply, 
about our telegraf setup, for this particular example (elasticsearch), the metrics come from a statsd elasticsearch plugin (https://github.com/Automattic/elasticsearch-statsd-plugin), sent to influxdb through the statsd telegraf input plugin.

The statsd templates for the statsd to influxdb translation is as follows:
`
[[inputs.statsd]]

    allowed_pending_messages = 20000
    metric_separator = "_"
    percentiles = [90]
    percentile_limit = 1000
    service_address = "127.0.0.1:8125"
    templates = [ 
       "elasticsearch.*.node.* measurement.es_cluster.measurement.es_node.field*",
       "elasticsearch.*.indices.* measurement.es_cluster.measurement.field*", 
       "elasticsearch.*.index.*.total measurement.es_cluster.measurement.es_index_name.measurement.field*", 
       "elasticsearch.*.index.* measurement.es_cluster.measurement.es_index_name.shard_id.field*"
     ]`

So that we basically end up with the same measurements naming scheme as telegraf.
We enforce a global "host" tag per instance, so let me change the dashboard "groupbys" and get back at you.

**Comment by oboukili** [comment]
That's way better, however the values still change due to the time resolution change (means, derivatives...etc). I believe this is related to #781.

**Comment by goller** [comment]
@oboukili oh good.  As for the values changes, would an example be that as you are zooming out the value at the peak changes because more data is used in the aggregate function?  Or, is data from additional tags being added to the aggregate?

Also, if you are interested, would you make a PR against the layout with your group bys?

**Comment by oboukili** [comment]
> As for the values changes, would an example be that as you are zooming out the value at the peak changes because more data is used in the aggregate function

^ Yes, this. However I believe it's **less** as I zoom out. I suppose to keep the dashboards responsive as the time interval increases, the same amount of data points are selected -> less data resolution. I believe being able to select data resolution (#781) would be the solution to keep coherent values.

About the PR, my "host" tag is not telegraf's ES input plugin "node_host" 's, so I think it would actually break things for most users!

**Comment by goller** [comment]
Ah right, yup, it would be less data.  I created issue #902 for the group by node_host stuff. 

Anyway, great that it worked out for you!
