### ISSUE TITLE
Chrongraf hostlist hangs

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/chronograf#901]
*1 In a Windows installation I cannot get Chronograf working. It hangs in the hostlist screen "Loading hosts...". 

*2 I got telegraf running but was not able tot get all system plugins working as described in the installation "manual". config file section [[inputs.processes]] makes it implossible to get telegraf working. After commenting out [[inputs.processes]] Telegraf repeats error "ERROR in input [inputs.system]: not implemented yet". cpu stuff is working fine and reaching the InfluxDB...

Possebly the 2 issues are related??

**Comment by goller** [comment]
Hi @Kortenbach, thanks for writing in!

You are right, they are related.  Configuring telegraf for windows is different than the other platforms.  We haven't specified the differences in our documentation (but we should).

First, try to use telegraf's default windows configuration here: https://github.com/influxdata/telegraf/blob/master/etc/telegraf_windows.conf

I bet that once you have that in place it'll start working!

If you are interested, it would be awesome if you would send in a PR for setting up windows telegraf and chronograf.

**Comment by Kortenbach** [comment]
I am working on it. Next monday i will continue my work on this. When done
i will send you the docs!

Op 16 feb. 2017 6:28 p.m. schreef "Chris Goller" <notifications@github.com>:

**Comment by goller** [comment]
Great!  Thanks again for reporting this.

**Comment by Kortenbach** [comment]
Hi Chris,

I tried using  https://github.com/influxdata/telegraf/blob/master/etc/
telegraf_windows.conf as my config file for Telegraf but no success...
Chronograf URL "http://localhost:8888/sources/6/hosts" still hangs at "HOST
LIST" with message "loading Hosts...".
Please help.

Best regards,

Bert Kortenbach

**Comment by Kortenbach** [comment]
Looking at this “windows” config file I noticed that all the “measurement” id’s (cpu, disk etc) had “win_” as prefix. I tried removing it (since chronograf will probably not know about this prefix) and that fixed my hanging host list…

**Comment by Kortenbach** [comment]
Looking at this “windows” config file I noticed that all the “measurement”
id’s (cpu, disk etc) had “win_” as prefix. I tried removing it (since
chronograf will probably not know about this prefix) and that fixed my
hanging host list…

**Comment by Kortenbach** [comment]
Hi Chris,

As promised my documentation on installing the TICK stack in Windows (7):

1.1                    Introduction

This is a short report about my experience with InfluxDB and the TICK
stack. Here “TICK” stands for “Telegraf”, “InfluxDB”, “Chronograf” and
“Kapacitor”.



Product

Short description

Telegraf

Telegraf is the metrics gathering agent in the TICK stack. It gathers data
and sends it to InfluxDB.

InfluxDB

A timeseries database. Consists of one exe and a configuration file.
Behaves like an http server and can run as a Windows service.

Chronograf

Chronograf is the user interface component of InfluxData's TICK stack. It
enables graphical and tabular views of the data contained in InfluxDB

Kapacitor

Kapacitor is the data processing platform of the TICK stack. Kapacitor is
responsible for creating and sending alerts in Chronograf


1.2                    Installation

For a more elaborate version see:
https://github.com/influxdata/chronograf/blob/master/docs/INSTALLATION.md
1.2.1              Telegraf

Telegraf in Windows can be treated as a portable application. Just download
it and run “telegraf -config telegraf.conf”. (TODO:Issue with log file
directory. Will output to StdErr for now).
1.2.2              InfluxDB

InfluxDB in Windows can be treated as a portable application. Just download
it and run “influxd.exe”. As mentioned before it acts like an http server.
By default you connect to it over port 8086. You can verify if influxDB is
running by going to your favorite browser and typing “
http://localhost:8086/query?q=SHOW%20DATABASES ”. This will show a JSON
result containing at least one database called "_internal"
1.2.3              Chronograf

Chronograf in Windows can be treated as a portable application. Just
download it and run “Chronograf.exe”. To verify if chronograf is working go
to your favorite browser and type http://localhost:8888. You should see a
form with a black background. You need to fill in ‘ connection string’ (
http://localhost:8086) ‘name’ (influx1 is fine) and ‘Telegraf database’
(telegraf).

Now, Chronograf cannot work properly without having Telegraf around to
provide some basic information about the machine that InfluxDB is running
on. To get it running you need to edit telegraf.conf. See
https://github.com/influxdata/chronograf/blob/master/docs/INSTALLATION.md
on how to do that. Once you succeed try typing:
http://localhost:8086/query?q=select%20*%20from%20telegraf..cpu in your
browser. This will show a JSON result containing a variety of information
about the PC that Telegraf is running on.

Now you should be able to connect Chronograf to your influxDB instance
(this is where I got stuck and posted an issue on github (#901)). Answer:
Need to use this config file:
https://github.com/influxdata/telegraf/blob/master/etc/telegraf_windows.conf.
This did not work either. Looking at this “windows” config file I noticed
that all the “measurement” id’s (cpu, disk etc) had “win_” as prefix. I
tried removing it (since chronograf will probably not know about this
prefix) and that fixed my hanging host list…

Once you start Chronograf you quickly realize you’re dealing with Beta
release software. It doesn’t provide all the features that we need in our
company. That’s why I started to take a look an “Grafana”. Grafana is a
more mature software that’s currently on version 4.1.2. It supports
InfluxDB a database and, like Chronograf, specializes in time-series data…
1.2.4              Grafana

Grafana in Windows can be treated as a portable application. Just download
it and unpack.

-          Copy …\conf\sample.ini to custom.ini

-          Change custom.ini: Change “http_port” from 3000 to 8080. (3000
has permission issues).

-          Run “\bin\ grafana-server.exe”.

-          Go to your browser and type “localhost:8080”.

-          Log in using the default user “admin” and password “admin”.

At this point Grafana shows you a nice wizard.

-          Wizard step 1: Click “Create your first datasource”

o   Fill in the following values:

o   Name: Local influxDB

o   Type: InfluxDB

o   URL: http://localhost:8086

o   Access: direct (“proxy” can help with Cross Origin Site Resource issues)

o   Database: MyInfluxDB or <your database name>

-          Klick “Save&test”. Grafana will show a big green message if all
is OK.

-          Wizard step 2: Klick “Create your first dashboard”

o   Select “Graph”

o   Klick on the graph title and select “edit” from the pop-up menu

o   Klick the small triangle left from the query to open the query builder

o   FROM <default> (=select from your default database)

o   …

So far Gafana seems much more capable that Chronograf.

TODO: Further exploration of Grafana.



More reading http://docs.grafana.org/installation/windows/ ,
http://docs.grafana.org/guides/gettingstarted/ and

http://docs.grafana.org/guides/basic_concepts/


1.2.5              Kapacitor

Kapacitor in Windows can be treated as a portable application. Just
download it and run “Kapacitord.exe”. To verify that Kapacitor is working
go to your command line, go to the directory containing kapacitor and type
“kapacitor list tasks”. It should see an empty list of tasks.
1.3                    Working with the TICK stack



https://github.com/influxdata/chronograf/blob/master/docs/GETTING_STARTED.md

**Comment by goller** [comment]
@Kortenbach thank you very much for writing this!  You mention that chronograf doesn't provide all the features you need yet.  What features would be helpful?

**Comment by Kortenbach** [comment]
Hi Chris,

We have been using our own time-series database and graphing for some years
now and we are trying to migrate to InfluxDB.
I'll show you some pictures of our graphing tool. It may give you some new
ideas:
[image: Inline image 1]
- The two offset settings make it possible to scale your graph in
y-direction. In this way you can assign the bottom 10% of the graph's
"paper" to a line (0..10%) and the next 10% of the paper to another line
(11..20%). Or chose to display two lines occupying the same space on your
paper so they can be compared.
- It also allows for fixed graph scaling and can display all lines as an
interpolated (smooth) or skipping (block shaped) line (temperature vs
status).
- It doesn't require the end-user to have any knowledge of query-building
and uses a calendar + time selector to select start- and end time of the
graph. Alternatively the user can select x-hours back in time from now().

I was wondering why you chose to built Chronograf when you could choose to
extend Grafana to fit your needs...

Best regards,

Bert Kortenbach.

**Comment by Kortenbach** [comment]
Hi, Chris,

I have a small yet pressing matter that I would like to discuss with you:

SELECT MEAN("temperature") ... GROUP BY time(60s) fill(average)--> This
works
SELECT "temperature" ... GROUP BY time(60s) fill(average) --> This returns
a http 400 error

Although I can imagine why the second example doesn't work, I also can
imagine a way in which it would work:
- Suppose I would like to find "Temperature" in 60s intervals.
- That would, at some point,  require me to find the temperature at
03:00:00 which doesn't exist in the database.
- The database COULD return the interpolated value between 02:59:30 and
03:00:30 (timestamps that are in the database)
   requiring only a two sample interpolation. Instead it qualifies my query
as "bad". Why?

Does the "mean" version require *all* samples between two timestamps to
work (instead of just 2)?
If yes:Isn't there a large performance penalty for doing that?

Best regards,

Bert Kortenbach

**Comment by zhangjianpinghik** [comment]
when the Chrongraf work long time, the hostlist loading.......
