### ISSUE TITLE
Improve alert history

### ISSUE THREAD

**Issue by alyan2008** [influxdata/chronograf#903]
Currently I have more than 41000 alerts for the last 7 days and all those alerts display in one window. In result it`s very heavy tab, it`s very hard to scroll and find something. Browser just freezes.

**Comment by cryptoquick** [comment]
@jaredscheib Hey, we should make the pagination we're making for the Hosts page componentized enough to reuse for the Alerts page as well. Two birds with one stone.

**Comment by nhaugo** [comment]
@alyan2008 we will be integrating with the kapacitor alert api soon https://github.com/influxdata/kapacitor/issues/829

Thus we are not likely to address this problem until then. The temporary workaround is to set the retention policy of the `chronograf` database so the older alerts start falling off.

https://docs.influxdata.com/influxdb/v0.9/query_language/database_management/#modify-retention-policies-with-alter-retention-policy

**Comment by nhaugo** [comment]
We are looking to work around this by limiting the range of time alerts are returned from. #1030
