### ISSUE TITLE
Make data precision configurable in dashboards

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#913]
See https://github.com/influxdata/chronograf/issues/781 for context

**Comment by minhaz1** [comment]
Was this added? I'm unclear on how to display any higher precision for my data. For example, I have some prices that are $0.20, from 0.20 to 0.21 is a 5% fluctuation, which is a huge window. The data I have in influxdb has higher precision, so is there any way for me to visualize it with higher precision in chronograf?
