### ISSUE TITLE
Bug in data explorer: graph spinner spins forever when one InfluxQL query is invalid

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#914]
This bug is a specific case of the more general #611.

Server error response from invalid InfluxQL queries are not being handled: `{"code":400,"message":"received status code 400 from server: err: error parsing query: found asdf, expected ; at line 1, char 46"}`.

This is not indicated to the user in the UI, so the spinner will simply hang. Or, new data and graphs will not successfully display, if the invalid InfluxQL query was added after a successful graph display.

**Comment by timraymond** [comment]
What's the course of action / AC here? Is it just to implement #611 ?
