### ISSUE TITLE
Bugs on dashboards: empty axes flashing and text size

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#915]
1. Cells flash empty axes every ~7 seconds when cells are "No Results" (see GIF)
![dashboardsflash](https://cloud.githubusercontent.com/assets/6403018/23225360/777c94b4-f8e6-11e6-9183-44180bebd5e8.gif)
2. "No Results" should resize when the cell is small enough (see top-right of GIF)

**Comment by 121watts** [comment]
@jaredscheib for #2 I dont think that we should even allow graphs that tiny.

**Comment by alexpaxton** [comment]
Limiting Graph size would be awesome
