### ISSUE TITLE
Support for Multiple Kapacitor instances

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#918]
Use Case: We have two kapacitor instance running active/active setup. Would like Chronograf to support multiple Kapacitor instances in terms of creating tasks and saving them to these instances.

**Comment by goller** [comment]
Hi @danyli78, thanks for writing in.  Agreed. I could imagine when one would want  staging/production kapacitors as well.

The chronograf go server supports multiple kapacitors today, but, we need to add UI to support more than one.  Currently, it is hardcoded to take the first kapacitor:

https://github.com/influxdata/chronograf/blob/master/ui/src/shared/apis/index.js#L64

**Comment by alexpaxton** [comment]
**redesigned config page**
![screen shot 2017-04-04 at 3 17 10 pm](https://cloud.githubusercontent.com/assets/2433762/24878123/b4ffdd6c-1de6-11e7-97ca-8e555e15eddd.png)

Clicking the name of a kapacitor node takes you to the edit view for it. Still working out that design

**Comment by alexpaxton** [comment]
**Kapacitor Create/Edit View**
![edit-create-kap-node](https://cloud.githubusercontent.com/assets/2433762/24881639/50856944-1df3-11e7-9c7b-6e9e267ea5be.png)

**Comment by alexpaxton** [comment]
Looks like this is related to #1089

**Comment by alexpaxton** [comment]
**Navigation change to match config page change**
<img width="268" alt="screen shot 2017-04-10 at 5 06 47 pm" src="https://cloud.githubusercontent.com/assets/2433762/24887394/36bd6346-1e10-11e7-8643-b870db766a2a.png">

**Comment by alexpaxton** [comment]
Connect #982 
Connect #1139
