### ISSUE TITLE
HipChat setup: Edit placeholder text/add stuff for clarity

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#919]
### Current setup
Current HipChat placeholders:

HipChat URL: `https://subdomain.hipchat.com/v2/room`
Room: ` ` (blank)
Token: ` ` (blank)

#### HipChat URL:
`https://your-subdomain.hipchat.com/v2/room`

I think this clarifies that they need to update the subdomain part of the URL.

> Initially I thought `https://<subdomain>.hipchat.com/v2/room` would work but then, you'd have to surround the Room and Token placeholders in `<>` and it got too messy/busy.

#### Room:
`your-hipchat-room`

#### Token:
`your-hipchat-token`

> I think that's clear. `your-hipchat-api-access-token-for-sending-notifications` seems a bit much.

Creating the correct token isn't incredibly straightforward. I think having a link to the more-detailed Kapacitor documentation (https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#hipchat-api-access-token) would help. Maybe something like a question mark (see terrible example below) that either:

* Links directly to https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#hipchat-api-access-token
* Or has a tooltip that says something like: Need help creating a token? Check out [these steps](https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#hipchat-api-access-token).

![image](https://cloud.githubusercontent.com/assets/8750814/23281044/76b4a356-f9d0-11e6-90f1-9a8e71ec3633.png)

**Comment by nhaugo** [comment]
Removing test button request, moved into #1082

**Comment by lukevmorris** [comment]
- [ ] `subdomain` => `your-subdomain`
- [ ] Room placeholder
- [ ] Room `?` tooltip
- [ ] Token placeholder
- [ ] Token `?` tooltip
