### ISSUE TITLE
Telegram setup: Edit placeholder text/add stuff for clarity

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#921]
### Current setup

Current Telegram setup:

![image](https://cloud.githubusercontent.com/assets/8750814/23282071/8e673992-f9d4-11e6-8e41-4035ea048e15.png)

#### Description

This is nit, but I like `Send alert messages to a Telegram bot` more than `You can have alerts sent to Telegram by entering info below`.

Setting up a Telegram bot isn't incredibly straightforward. I think linking to the more detailed Kapacitor documentation (https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-bot) would be helpful. Maybe something like:

* The text: Send alert messages to a [Telegram bot](https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-bot), where Telegram bot links directly to the Kapacitor docs
* A question mark icon next to Telegram bot that links directly to the Kapacitor docs
* A question mark icon with a tooltip that says: Need help creating a bot? Check out [these steps](https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-bot).

#### Telegram URL
Er, get rid of this option entirely. When I setup Telegram with Kapacitor I didn't have to touch that setting;  I'd like to confirm that with someone else who's used this, but I'm almost certain that users never need to edit that URL.

#### Token and Chat ID
Change blank to `your-telegram-token`
Change blank to `your-telegram-chat-id`

Creating the correct token/identifying your chat id isn't incredibly straightforward. I think having a link to the more-detailed Kapacitor documentation (https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-api-access-token & https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-chat-id) would help. Maybe something like a question mark (see terrible example below) that either:

* Links directly to https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-api-access-token | https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-chat-id
* Or has a tooltip that says something like: Need help finding your token | chat id? Check out [these steps](https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-api-access-token | https://docs.influxdata.com/kapacitor/latest/guides/event-handler-setup/#telegram-chat-id).

![image](https://cloud.githubusercontent.com/assets/8750814/23283027/b90f3e48-f9d8-11e6-85a9-31e8adbc1fec.png)

#### Parse Mode

A couple things:

* The default `Parse Mode` is Markdown so maybe have the Markdown checkbox selected by default
* Instead of `Parse Mode` have: `Select the alert message format` 

#### Disable checkboxes

Instead of `Disable Web Page Preview`, what about: Disable [link previews](https://telegram.org/blog/link-preview) in alert messages.

Instead of `Disable Notification`, what about: Disable notifications on iOS devices and disable sounds on Android devices. Android users continue to receive notifications.

> That last one is wordy but I think it's clearer. The first time I saw that I thought it was disabling the event handler altogether :/

**Comment by nhaugo** [comment]
Removing the request for "test telegram" and moving that into its own issue.

**Comment by nhaugo** [comment]
@alexpaxton to add design for help callout, or just say use '?'

**Comment by nhaugo** [comment]
For the short term, link to the kapacitor documentation. Drop a new issues when closing this to write chronograf docs for this.

**Comment by lukevmorris** [comment]
- [ ] Update Telegram Alert description and add link
- [ ] Remove Telegram URL
- [ ] Placeholder for Token
- [ ] `?` for Token
- [ ] Placeholder for Chat ID
- [ ] `?` for Chat ID
- [ ] Parse Mode => Select the alert message format
- [ ] Message Format > Markdown selected by default
- [ ] Disable Web Page Preview => Disable <link previews> in alert messages
- [ ] Disable Notification => Disable notifications on iOS devices and disable sounds on Android devices. Android users continue to receive notifications.

@rkuchan Can you verify that I got everything?
@nhaugo Can you verify that we're removing Telegram URL?

**Comment by rkuchan** [comment]
@lukevmorris looks good!
