### ISSUE TITLE
Users should be able to CRUD roles when using an Influx Enterprise source

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#932]
A menu entry should appear on the left rail when connected to an Influx Enterprise source. This will take the user to a page where they are able to Create roles on the cluster. Each role should have a drilldown link bringing users to a page listing a stubbed-out list of permissions (this list will be vivified in another issue). From this page, users should be able to delete roles.

The API has been updated in #101 to support managing access control on Influx Enterprise. `swagger.json` lists all the new endpoints, though as of this writing these aren't visible on the `/docs` endpoint due to some issue with `Redoc` that will be separately filed.

The following screenshots are from the equivalent access control features found there. The HTML / CSS should be used from these pages.

### Roles Index
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23372838/472d603c-fceb-11e6-8309-24dd14a125f1.png)

### Roles Drilldown
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23372850/57cb1ede-fceb-11e6-8ad2-9409fdff0164.png)

**Comment by timraymond** [comment]
Need design for:
- Create Role Page

**Comment by RomanGotsiy** [comment]
Sorry for watching you 👀  😂 
ReDoc author here

What's the issue with ReDoc? Maybe I could help?

**Comment by goller** [comment]
Hey @RomanGotsiy, thanks for ReDoc; I love it!  I bet @timraymond was caught right between ReDoc's 0.10.0 and 0.10.1 release.  Later that day when I tried it I had to problems.  We are using https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js right now and I think using latest is a good thing! 

Yay for react!
