### ISSUE TITLE
Permissions should be assignable to Roles

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#933]
Dependent on: #932 

The drilldown page for Roles should allow for permissions to be assigned to a particular role. See the APIs implemented in #101 for more information on how this should be accomplished. Some permissions should be assignable only to the "all" scope, while others should be assignable to a subset of databases (including all databases). The full list of these is found below.

### Individually Assignable Permissions

- View Admin
- View Chronograf
- Create Users & Roles
- Drop Data
- Read
- Write
- Manage Continuous Queries
- Manage Queries
- Manage Subscriptions
- Monitor

### "all" Scope permissions

- Create Database
- Add/Remove Nodes
- Drop Databases
- Rebalance
- Manage Shards
- Copy Shard

## Role Drilldown Page
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23373283/45b3c280-fced-11e6-8179-f1b198898346.png)

## Permission Assignment Dialog
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23373290/530c2e22-fced-11e6-898b-495fd81f0675.png)

## Permission Assignment Dialog when scoping by DB
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23373311/6e771c9e-fced-11e6-9f5c-1c82bfc63ae8.png)

**Comment by goller** [comment]
@timraymond Perhaps I should modify the `/permissions` endpoint to return the permissions that are acceptable per scope?

**Comment by timraymond** [comment]
@goller Yeah, that might be better than encoding that knowledge in the frontend. It might also be beneficial to add the pretty-printed name and description for each permission "id" (keyword?)

**Comment by goller** [comment]
Currently, `/permissions` returns: 

```json
{
  "permissions": [
    "READ",
    "WRITE"
  ],
  "links": {
    "self": "/chronograf/v1/sources/1/permissions",
    "source": "/chronograf/v1/sources/1"
  }
}
```

I think it could return:

```json
{
    "permissions": [
        {
            "scope": "all",
            "allowed": [
                "READ",
                "WRITE"
            ]
        },
        {
            "scope": "database",
            "allowed": [
                "READ",
                "WRITE"
            ]
        }
    ],
    "links": {
        "self": "/chronograf/v1/sources/1/permissions",
        "source": "/chronograf/v1/sources/1"
    }
}
```

**Comment by timraymond** [comment]
Need design for how to add permissions without a modal
