### ISSUE TITLE
It should be possible to manage database users for a source

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#934]
There should be a users management page that will allow users to:

- [x] View the database users present on a source
- [x] View the roles which that database user is assigned to if the source is Influx Enterprise
- [x] Delete database users
- [x] Create new users
- [x] Create new user on top not bottom
- [x] Filter users by user name
- [x] Filter roles by role name

Clicking on the name of a database user should bring the user to a drilldown page where permissions can be assigned to users and their password can be changed. For this card, these pages should be stubbed out so they can be completed in another card. Omit the "Roles" and "Web Users" tabs.

These is the relevant flats from Enterprise Web from where the HTML / CSS should be taken. Please change the text "Cluster Accounts" to "Database Users."

The APIs for accomplishing this were added in #101 and should be uniform across both Influx Enterprise and OSS sources.

For adding new users, omit the "Role" dropdown for OSS sources.

AC: For OSS, I should be able to visit a user management page, create a new user, then delete that user. For Influx Enterprise, I should be able to visit that page, create a user and simultaneously assign them to a previously-created role, and then delete that user.

## Account Management Page
![influxdata_-_enterprise_manager_and_slack](https://cloud.githubusercontent.com/assets/288061/23375391/390f47ee-fcf6-11e6-8ca4-29e34a9bb798.png)

## Create User Dialog
![influxdata_-_enterprise_manager_and_new_issue_ _influxdata_chronograf](https://cloud.githubusercontent.com/assets/288061/23375469/82b88978-fcf6-11e6-95e4-9f79832df956.png)

## Account Drilldown Page -> Permissions
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23379291/67ccf262-fd04-11e6-8be3-f36b34bd27f5.png)

## Account Drilldown -> Account Details
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23379329/92631ea2-fd04-11e6-81bc-d98efe692e77.png)

**Comment by timraymond** [comment]
Need design for replacing create user dialog

**Comment by nhaugo** [comment]
• Create new user on top not bottom
• Filter is on usernames and roles

[enterprise-users-page.pdf](https://github.com/influxdata/chronograf/files/812349/enterprise-users-page.pdf)
