### ISSUE TITLE
Database Users should be assignable to Roles

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#937]
Depends on #932 

From the Role drilldown page, there should be a tab called "Users," which allows database users to be assigned to a role and removed from that role.

**Note:** Omit the "Cluster" part of the add user dialog.

See the following screenshot from Enterprise Web for relevant HTML / CSS. Substitute "Cluster Account" for "Database User" in all instances.

## Role <-> DB User Association
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23378872/bc383016-fd02-11e6-8e3d-02f511618e57.png)

## Add DB User Dialog
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23378881/c6b0b1da-fd02-11e6-8bb4-67f466d6fe2d.png)

**Comment by nhaugo** [comment]
[enterprise-users-page.pdf](https://github.com/influxdata/chronograf/files/812362/enterprise-users-page.pdf)
