### ISSUE TITLE
Permissions should be assignable to Users

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#938]
Depends on #934 

It should be possible to assign/revoke permissions directly to users using the APIs implemented in #101. Permissions follow the same rules as outlined in #933 , and the dialog for adding permissions should be identical as the one in #933 . **However**, for OSS the list of permissions should be "Read" and "Write," which are both scoped by database (or all databases).

The relevant page from Enterprise Web is shown below.

## DB User Permission Assignment
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23379247/40964522-fd04-11e6-8ce3-5f276be59efa.png)

EDIT: Add info re: OSS permissions.

**Comment by nhaugo** [comment]
[enterprise-users-page.pdf](https://github.com/influxdata/chronograf/files/812365/enterprise-users-page.pdf)
