### ISSUE TITLE
Users should be able to change DB User Passwords

### ISSUE THREAD

**Issue by timraymond** [influxdata/chronograf#939]
Depends on #934 

From the DB User drilldown page, it should be possible to change a database user's password using the fields added in #934 to the "Account Details" page. See the following screenshot. This should be possible using the user update endpoints from the API in #101.

## DB User -> change password
![influxdata_-_enterprise_manager](https://cloud.githubusercontent.com/assets/288061/23379595/85921132-fd05-11e6-8bd0-d7805e65b047.png)

**Comment by nhaugo** [comment]
• Create new user on top not bottom
• Filter is on usernames and roles

[enterprise-users-page.pdf](https://github.com/influxdata/chronograf/files/812346/enterprise-users-page.pdf)
