### ISSUE TITLE
install chronograf from source error [chronograf/oauth2]

### ISSUE THREAD

**Issue by lin-credible** [influxdata/chronograf#943]
`os`: CentOS7
`Chronograf`: v1.2.0-beta4

```
...chronograf]# make
......
go build -o chronograf -ldflags "-s -X main.version=1.2.0-beta4-6-g740e99b -X main.commit=740e99b3" ./cmd/chronograf/main.go
# github.com/influxdata/chronograf/oauth2
oauth2/github.go:125: not enough arguments in call to client.Organizations.List
	have (string, *"github.com/google/go-github/github".ListOptions)
	want ("context".Context, string, *"github.com/google/go-github/github".ListOptions)
oauth2/github.go:141: not enough arguments in call to client.Users.ListEmails
	have (nil)
	want ("context".Context, *"github.com/google/go-github/github".ListOptions)
make: *** [chronograf] Error 2
```

**Comment by lin-credible** [comment]
I got it. @goller  💯 


---
Something others:
I really like `chronograf`, thanks so so so much for building this! but it's difficult for me. I'm going to try my best to understand your awesome job.

**Comment by goller** [comment]
@lin-credible great! contributions would be welcome!  Are you interested in contributing code?  Javascript?  Go?  

I could help point you in the right direction if you want.

**Comment by lin-credible** [comment]
@goller Javascript 🌹
I'm so excited about it... 🤗

**Comment by lin-credible** [comment]
@goller Could you send me some documents about `chronograf`? Just like you said you could help point me in the right direction. Your project is very large, I wanna know some design documents, OK? about the framework, the API design, etc. I really appreciate this.
