### ISSUE TITLE
As a user I can see an edit overlay

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#950]
• This puts a yellow border around the selected graph 
• This opens an overlay area

[graph-editing.pdf](https://github.com/influxdata/chronograf/files/825341/graph-editing.pdf)

**Comment by lukevmorris** [comment]
We now have the ability to add/remove queries in a cell, and edit a particular query, within Overlay Technologies. Still to do:
- [ ] Communicate with Goller about dashboard/cell schema changes
- [ ] Modify a cell's Visualization Type
- [ ] Save/Cancel changes made to the cell while in the overlay
