### ISSUE TITLE
Support for multiple graphs for each value of a tag in dashboard

### ISSUE THREAD

**Issue by lin-credible** [influxdata/chronograf#958]
Now:  
<img width="391" alt="screen shot 2017-03-02 at 16 41 27" src="https://cloud.githubusercontent.com/assets/3191641/23499500/5a5209b4-ff67-11e6-970d-7dbad3309c01.png">

Hope so: (DATA EXPLORE) or (CPU0 Usage, CPU1 Usage ...etc)
<img width="340" alt="screen shot 2017-03-02 at 17 02 33" src="https://cloud.githubusercontent.com/assets/3191641/23500191/143793ec-ff6a-11e6-83a8-3fd5f14581ed.png">

**Comment by lin-credible** [comment]
Could I change the default layout of 'CPU Usage' and add a `'groupbys'` ?

![cpu_disk_groupby](https://cloud.githubusercontent.com/assets/3191641/23501108/7f910396-ff6d-11e6-8c46-c52f5c138d3a.png)

**Comment by lin-credible** [comment]
How can I change the default layout of 'CPU'? @goller 😊

**Comment by nhaugo** [comment]
@lin-credible This looks like it might be an improvement, do you want to submit a PR?

**Comment by lin-credible** [comment]
@nhaugo 

<img width="409" alt="screen shot 2017-03-03 at 18 29 50" src="https://cloud.githubusercontent.com/assets/3191641/23547827/adf2a6fe-003f-11e7-8df9-2a22fa3b5ac0.png">
As the picture above, I think we need a better method to handle this... 
Is there a way to show these?
Here is the graph of [netdata](http://netdata.firehol.org/):  

![netdatas](https://cloud.githubusercontent.com/assets/3191641/23547952/35e13b2a-0040-11e7-95fa-b908ddaf3323.png)

**Comment by nhaugo** [comment]
@lin-credible Ah, I see what you are saying. Thanks for the examples of what you are looking for. We could probably build something that generate a graph per provided tag, that sounds like it might be a pretty nice feature. I'm going to rename this ticket and push it later in the 1.2.x timeline.

**Comment by lin-credible** [comment]
I have a bad idea:
<img width="114" alt="screen shot 2017-03-04 at 14 55 06" src="https://cloud.githubusercontent.com/assets/3191641/23576813/9c5e7106-00ea-11e7-97b5-8fc949dc922a.png">

`*.json` file:
<img width="605" alt="screen shot 2017-03-04 at 14 57 44" src="https://cloud.githubusercontent.com/assets/3191641/23576835/05ef6cec-00eb-11e7-83e6-56fe2b715ff7.png">

result:
<img width="1109" alt="screen shot 2017-03-04 at 15 05 21" src="https://cloud.githubusercontent.com/assets/3191641/23576904/2d8b2bbe-00ec-11e7-990b-84c039168366.png">

🔔 As we all know, the number of CPUs per server is different, so we can't do it like above 😂 

---
I'm new to TICK, so I need to learn it's framework and some details of the architecture more. I'm curious about the TICK, thanks so ... much for your amazing job.

**Comment by russorat** [comment]
this will be solved once we complete #2962
