### ISSUE TITLE
No Host on the host list page

### ISSUE THREAD

**Issue by ouassila** [influxdata/chronograf#961]
On a fresh install of Chrongraf, after adding a new source the host list page stuck on  "Loading Hosts ..." and no hosts:

![image](https://cloud.githubusercontent.com/assets/9214730/23552939/9da382ee-001e-11e7-80e1-3cc2dfbda4dd.png)

While checking the js console output I see errors like this :

![image](https://cloud.githubusercontent.com/assets/9214730/23552886/65f71022-001e-11e7-9f57-f110c9041a60.png)

**Comment by nhaugo** [comment]
Hi @ouassila do you have telegraf data going into the database? Chronograf assumes there is telegraf data available to generate the host list. We will be working on a new home page before the project goes GA.

**Comment by Devon21** [comment]
I'm running into the same issue.. I was able to connect to the DB using version 1.0, but not on this new version. chronograf-1.2.0~beta4-1.

**Comment by jaredscheib** [comment]
Hi @ouassila @Devon21, we've been able to reproduce this error only when Telegraf is not running. I'm going to create a story for creating higher-level checks that ensure Telegraf is running, among other prerequisites for Chronograf to work as expected. 

In the meantime, have you two verified that you have Telegraf running, and that it's sending data to InfluxDB? Please follow the steps at  https://github.com/influxdata/chronograf/blob/master/docs/INSTALLATION.md#telegraf-setup to ensure Telegraf is running properly, and let us know if this issue persists once it's definitely running. Thanks!

**Comment by Devon21** [comment]
Both services are running and up to date. One config I might need to share is that we are using udp in the telegraf config. 

$ rpm -qa | grep telegraf
telegraf-1.2.1-1.x86_64
$ rpm -qa | grep chronograf
chronograf-1.2.0~beta4-1.x86_64
$ sudo service telegraf status
telegraf Process is running [ OK ]
$ sudo service chronograf status
[OK] Service running.

So I tried to connect using both, udp and tcp. 
udp://hostname:25826	
http://hostname:8086

This was working using 1.0 on both. 

Thx 
Devon

**Comment by goller** [comment]
Hey @Devon21, thank for the extra information.  Would you be able to run these two queries against influxdb?

```
use telegraf
show tag values from system with key = "host"
```

I'm curious if data comes back from the telegraf measurement.

**Comment by Devon21** [comment]
We have data coming in, Network and system loads from our servers. Once I upgraded to chronograf 1.2, I'm not able to connect to influxdb.

**Comment by goller** [comment]
@Devon21 cool ok... so I _might_ know what theproblem is... if you update the influxdb source, would you change the telegraf database to your custom database name?

(you may have already done this)

**Comment by Devon21** [comment]
@goller we have done that, still hangs on the host page. I do not get a error stating chronograf can not connect.

**Comment by goller** [comment]
hmmm... @Devon21 would you be able to run the chronograf server with the `--log-level=debug ` and send in the log?  It's a long shot, but, perhaps it'll shed some light for me.

**Comment by Devon21** [comment]
@goller Here you go

`time="2017-03-11T01:41:09Z" level=debug msg=query command="SHOW DATABASES" component=proxy db= host="db-hostname:8086" rp=

time="2017-03-11T01:41:09Z" level=debug msg=query command="select mean(usage_user) from cpu where cpu = 'cpu-total' and time > now() - 10m group by host; select mean(\"load1\") from \"system\" where time > now() - 10m group by host;  select mean(\"Percent_Processor_Time\") from win_cpu where time > now() - 10m group by host; select mean(\"Processor_Queue_Length\") from win_system where time > now() - 10s group by host; select non_negative_derivative(mean(uptime)) as deltaUptime from \"system\" where time > now() - 10m group by host, time(1m) fill(0); show tag values from system with key = \"host\"" component=proxy db=db-name host="db-hostname:8086" rp=`

**Comment by goller** [comment]
@Devon21 would sharing your telegraf.conf here?  If not, what telegraf plugins are you running?

**Comment by goller** [comment]
@Devon21 I think you ran into this issue in telegraf: https://github.com/influxdata/telegraf/issues/2448

I think your script that your inputs.exec is running is not returning data to telegraf.    Would you try adding the plugins here: https://github.com/influxdata/chronograf/blob/master/docs/INSTALLATION.md#telegraf-setup

**Comment by Devon21** [comment]
Thank you for the help.. Everything is working now. Enabled the required plugins.

**Comment by goller** [comment]
@Devon21 great!

**Comment by goller** [comment]
@ouassila Have you been able to get host data yet?

**Comment by asanami** [comment]
It looks like the hosts are only registered if the database configured in telegraf is 'telegraf'.  If this is set to a custom database name, then the host doesn't appear in the list.

**Comment by pierrick-openIT** [comment]
hi, i have the same issue. Host list is empty because i use custom database name.

**Comment by perzizzle** [comment]
Did everyone figure out a solution? We use a measurement prefix to organize our measurements which breaks the host list dashboard. I don't see anyway to configure the db, or measurement.

**Comment by jaredscheib** [comment]
cc @russorat -- is this something we might address in the host list refactor?

**Comment by prandelicious** [comment]
I'm also experiencing the same issue with Chronograf 1.6.2 and using a custom database instead of _telegraf_

**Comment by VVilaplana** [comment]
chronograf 1.7.17 and still the same :(
