### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by lin-credible** [influxdata/chronograf#978]
`i18n` 🇺🇸 🇨🇳 
I'm Chinese. China needs the TICK and DevOps, and I'm sure that China has a huge market. If we wanna do something about internationalization, I will do my best if you need. ❤️ : ) 

> So ... excited about it

**Comment by goller** [comment]
Hey @lin-credible, I think this would be wonderful.  I'm not familiar with how to do internationalization in Javascript.  How do you recommend doing it?

**Comment by lin-credible** [comment]
@goller I know some other open source projects, they support `Internationalization` with `i18n`. I'm also not familiar with it... I know, it needs a lot of work in translating : (, but `Chronograf` can just support it :smile:

**Comment by lin-credible** [comment]
Talk later
💛
