### ISSUE TITLE
Kapacitor alert destination dropdown overflows/resizes page

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/chronograf#982]
![o7uk6jehb1](https://cloud.githubusercontent.com/assets/290647/23763303/d80f3fac-04ad-11e7-94ca-21bec97d3cc3.gif)

@121watts suggested moving the dropdown to the top of the `.rule-section-body`.

cc @alexpaxton

**Comment by alexpaxton** [comment]
Lets use a radio button group instead of a dropdown

<img width="985" alt="screen shot 2017-03-27 at 5 04 24 pm" src="https://cloud.githubusercontent.com/assets/2433762/24383158/2e0dd114-1310-11e7-8567-e8dcf53bbf6b.png">

**Comment by 121watts** [comment]
Yes!
