### ISSUE TITLE
Add Source "breadcrumb" consistently across the UI

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#983]
Since Chronograf can be connected to one or more InfluxDB instances or InfluxEnterprise clusters -- it is difficult to see which source you are connected to.  

The same will be true for the Alert History page for Kapacitor.  

Please enhance the UI to provide the source context....

**Comment by jademcgough** [comment]
We should abstract this into a reusable component that makes use of the current source in props if it's provided.
