### ISSUE TITLE
Server response data incorrect

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#984]
- [x] when creating a user, if i do a POST to
`/chronograf/v1/sources/1/users`
with payload
`{"name":"aaaa","password":"aaa","roles":[],"permissions":[],"links":{"self":""}}`
then the server response at key `data` is
`{"name":"aaaa","links":{"self":"/chronograf/v1/sources/1/users/aaaa"}}`,
but I am wanting
`{"name":"aaaa","roles":[],"permissions":[],"links":{"self":"/chronograf/v1/sources/1/users/aaaa"}}`

- [x] when getting roles, if i do a GET to `/chronograf/v1/sources/1/roles`,
roles with no users have no `users` key, such as ```        {
            "links": {
                "self": "/chronograf/v1/sources/1/roles/telegraf-readers"
            },
            "name": "telegraf-readers",
            "permissions": [
                {
                    "allowed": [
                        "ReadData"
                    ],
                    "name": "telegraf",
                    "scope": "database"
                }
            ]
        },``` but I am wanting `"users": [],`
- [x] when creating a new role, the server should not allow me to create a role with a name that already exists. currently, it does.

**Comment by jaredscheib** [comment]
Updated with 2 different requests -- thanks!

**Comment by jaredscheib** [comment]
Added another

**Comment by goller** [comment]
Fixed in #995 and #996
